config {
    type: "view",
    description: 
        `
        PIC: nguyen.tran; 
        Type: Table; 
        `,
    //tags: ["custom_1h_past10"]
}

WITH
    cte AS (
        SELECT
            customer_id
            , customer_group
            , REGEXP_REPLACE(kam_pic, r'@BUYMED.COM', '') AS pic
            , SAFE_CAST(sales_target AS FLOAT64) AS target
            , month
        FROM (
            SELECT
                SAFE_CAST(SPLIT(code, "_")[SAFE_OFFSET(0)] AS INT64) AS customer_id
                , REGEXP_REPLACE(code, SPLIT(code, "_")[SAFE_OFFSET(0)]||"_", "") AS customer_group
                -- , SPLIT(code, "_")[SAFE_OFFSET(1)] AS customer_group
                , type
                , NULLIF(UPPER(value), "NAN")  AS value
                , DATE_TRUNC(DATE(submit_at), MONTH ) AS month
            FROM collector.data_prd
            WHERE DATE(submit_at) >= DATE_TRUNC(CURRENT_DATE("+7"), MONTH) - INTERVAL 3 MONTH
                AND object = "Customer_PIC"
                AND type IN ("SALES_TARGET","KAM_PIC")
                AND submit_id >= 5732
                AND submit_id <> 10205
            QUALIFY ROW_NUMBER() over (PARTITION BY code, object, type, month ORDER BY submit_id DESC) = 1
        )
        PIVOT ( MAX(value) FOR type IN ("SALES_TARGET" AS sales_target, "KAM_PIC" AS kam_pic) )
        WHERE customer_id IS NOT NULL
    ),

    final AS (
        SELECT *
        FROM cte
        UNION ALL
        SELECT
            a.customer_id
            , "PHARMA_COMPANY"
            , "TUNG.NGUYENXUAN"
            , 0
            , (SELECT MAX(month) FROM cte WHERE customer_group = 'PHARMA_COMPANY')
        FROM ${ref("dim_customer")} AS a
        WHERE 1=1
            AND a.business_scope = "PHARMA_COMPANY"
            AND NOT EXISTS (SELECT 1 FROM cte AS b WHERE a.customer_id = b.customer_id AND b.month = (SELECT MAX(month) FROM cte WHERE customer_group = 'PHARMA_COMPANY') )
        UNION ALL
        SELECT
            a.customer_id
            , "CLINIC"
            , UPPER(pic.pic) AS pic
            , 0
            , (SELECT MAX(month) FROM cte WHERE customer_group = 'CLINIC')
        FROM ${ref("dim_customer")} AS a
            LEFT JOIN ${ref('dim_province')} AS p ON a.province_code = p.province_code
            LEFT JOIN (
                SELECT *
                FROM UNNEST([
                    STRUCT('lan.trankim' AS pic, '1R0VW12DX4A'  AS region_code),
                    STRUCT('lan.trankim',        '2GRTBAEQDX4'),
                    STRUCT('lan.trankim',        '3BE9QP72U1Y'),
                    STRUCT('lan.trankim',        '413WEL1ABCL'),
                    STRUCT('lan.trankim',        '528UQP72U1Y'),
                    STRUCT('lan.trankim',        '6PB4LEU4ABC'),
                    STRUCT('xuan.mai',           '73XF1R94ABC'),
                    STRUCT('lan.trankim',        '8C1BDCT3PAB'),
                    STRUCT('lan.trankim',        '113RVDTCV2U1'),
                    STRUCT('xuan.mai',           '107TQTAR1Y7G')
                ]) AS t
            ) AS pic ON pic.region_code = p.region_code
        WHERE 1=1
            AND a.business_scope = "CLINIC"
            AND NOT EXISTS (SELECT 1 FROM cte AS b WHERE a.customer_id = b.customer_id AND b.month = (SELECT MAX(month) FROM cte WHERE customer_group = 'CLINIC') )
    )

SELECT
    *
FROM final
QUALIFY ROW_NUMBER() OVER(PARTITION BY customer_id, month) =1
