config {
    type: "view",
    description: 
        `
        PIC: nguyen.tran; 
        Type: Table; 
        `,
    //tags: ["custom_1h_past10"]
}

WITH
    cte AS (
        SELECT
            customer_id
            , customer_group
            , REGEXP_REPLACE(kam_pic, r'@BUYMED.COM', '') AS pic
            , SAFE_CAST(sales_target AS FLOAT64) AS target
            , month
        FROM (
            SELECT
                SAFE_CAST(SPLIT(code, "_")[SAFE_OFFSET(0)] AS INT64) AS customer_id
                , REGEXP_REPLACE(code, SPLIT(code, "_")[SAFE_OFFSET(0)]||"_", "") AS customer_group
                -- , SPLIT(code, "_")[SAFE_OFFSET(1)] AS customer_group
                , type
                , NULLIF(UPPER(value), "NAN")  AS value
                , DATE_TRUNC(DATE(submit_at), MONTH ) AS month
            FROM collector.data_prd
            WHERE DATE(submit_at) >= DATE_TRUNC(CURRENT_DATE("+7"), MONTH) - INTERVAL 3 MONTH
                AND object = "Customer_PIC"
                AND type IN ("SALES_TARGET","KAM_PIC")
                AND submit_id >= 5732
                AND submit_id <> 10205
            QUALIFY ROW_NUMBER() over (PARTITION BY code, object, type, month ORDER BY submit_id DESC) = 1
        )
        PIVOT ( MAX(value) FOR type IN ("SALES_TARGET" AS sales_target, "KAM_PIC" AS kam_pic) )
        WHERE customer_id IS NOT NULL
    )

SELECT *
FROM cte
UNION ALL
SELECT
    a.customer_id
    , "PHARMA_COMPANY"
    , "tung.nguyenxuan"
    , 0
    , DATE_TRUNC(CURRENT_DATE("+7"), MONTH)
FROM ${ref("dim_customer")} AS a
WHERE 1=1
    AND a.business_scope = "PHARMA_COMPANY"
    AND NOT EXISTS (SELECT 1 FROM cte AS b WHERE a.customer_id = b.customer_id AND b.month = DATE_TRUNC(CURRENT_DATE("+7"), MONTH) )

