config {
    type: "incremental",
    description: 
        `
        Details of the items in the order, with combos split into normal products and its prices recalculated according to the corresponding combo, partition by outbound_date;
        PIC: van.lethuy; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.platinum}.marketplace_prd_order_v2_order_item,
            ${source.platinum}.marketplace_prd_order_v2_order,
            ${source.platinum}.warehouse_prd_core_delivery_order
        `,
    bigquery: {
        partitionBy: "outbound_date_local",
        clusterBy: ["order_id", "sku_code"]
    },
    tags: ["custom_1h_past5", "MARKETPLACE"],

}

pre_operations {
  ${when(
    incremental(),
    `
      DELETE FROM ${self()}
      WHERE outbound_date_local >= DATE_SUB(DATE_TRUNC(CURRENT_DATE("+7"), MONTH), INTERVAL 3 MONTH);

      DELETE FROM ${self()}
      WHERE outbound_date_local < '2024-01-01';
    `
  )}
}


with params as (
    select
            -- date('2025-01-01') as start_date

        ${when(
            incremental(),
            "date_trunc(date_sub(current_date('+07'), interval 3 month), month)",
            "date('2024-01-01')"
        )} as start_date

)

select *
from ${ref(`fact_fin_soi_sku_flattening`)}
where 1=1
and outbound_date_local is not null
and created_date_local >= (select date_sub(start_date, interval 3 month) from params)
and outbound_date_local >= (select start_date from params)