config {
    type: "incremental",
    description: 
        `
        Details of the items in the order, with combos split into normal products and its prices recalculated according to the corresponding combo, partition by outbound_date;
        PIC: van.lethuy; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.platinum}.marketplace_prd_order_v2_order_item,
            ${source.platinum}.marketplace_prd_order_v2_order,
            ${source.platinum}.warehouse_prd_core_delivery_order
        `,
    bigquery: {
        partitionBy: "outbound_date_local",
        clusterBy: ["order_id", "sku_code"]
    },
    tags: ["custom_1h_past5", "MARKETPLACE"],

}

pre_operations {
  ${when(
    incremental(),
    `
      DELETE FROM ${self()}
      WHERE outbound_date_local >= DATE_SUB(DATE_TRUNC(CURRENT_DATE("+7"), MONTH), INTERVAL 3 MONTH);

      DELETE FROM ${self()}
      WHERE outbound_date_local >= '2024-01-01';
    `,
    `
      DELETE FROM ${self()} WHERE TRUE;
    `
  )}
}


with params as (
    select
            -- date('2025-01-01') as start_date

        ${when(
            incremental(),
            "date_trunc(date_sub(current_date('+07'), interval 3 month), month)",
            "date('2024-01-01')"
        )} as start_date

)
, t0 as (
select date(created_time,'+07') as created_date_local
    , mg_id
    , order_id
    , product_id
    , sku_level
    , sku as sku_code
    , vat
    , type
    , seller_code
    , seller_class
    , deal_code
    , deal_pricing_type
    , price as actual_sale_price
    , seller_price as actual_seller_price
    , charge_deal_fee_value
    , quantity as actual_ordered_qty
    , reserved_quantity as actual_reserved_qty
    , outbound_quantity as actual_outbound_qty
    , returned_quantity as actual_returned_qty
    , seller_revenue
    , extra_props
    , outbound_infos
    , return_infos
from ${source.platinum}.marketplace_prd_order_v2_order_item oi
where 1=1
and created_date >= (select date_sub(start_date, interval 3 month) from params)
)
, prd_0 as (
select m.*
    , coalesce(json_extract_scalar(ob.campaign_code), deal_code) as promotion_code
    , sku_code as bom_sku_code
    , product_id as bom_product_id
    , sku_level as bom_sku_level
    , actual_sale_price as original_bom_price
    , actual_seller_price as bom_seller_price
    , safe_cast(json_extract_scalar(ob.quantity) as int64) as bom_outbound_qty
    , json_extract_scalar(ob.exp_date) as bom_exp_date
    , json_extract_scalar(ob.lot) as bom_lot
    , json_extract_scalar(ob.do_code) as do_code
    , json_extract_scalar(ob.po_code) as po_code
    , m.vat as bom_vat
from t0 as m, unnest(json_query_array(outbound_infos)) as ob
where 1=1
and m.outbound_infos is not null
)
, product as (
select m.*
    , safe_cast(json_value(extra_props, '$.deal_vendor_price') as float64) as deal_vendor_price
    , safe_cast(json_value(extra_props, '$.deal_info.discounted') as float64) as deal_sale_price
from prd_0 as m
where 1=1
)
, combo as (
select m.*
    , coalesce(json_extract_scalar(combo_item.campaign_code), deal_code) as promotion_code
    , json_extract_scalar(combo_item.sku ) as bom_sku_code
    , safe_cast(json_extract_scalar(combo_item.product_id) as int64) as bom_product_id
    , json_extract_scalar(combo_item.sku_level ) as bom_sku_level
    , safe_cast(json_extract_scalar(combo_item.price) as float64) as original_bom_price
    , safe_cast(json_extract_scalar(combo_item.seller_price) as float64) as bom_seller_price
    , safe_cast(json_extract_scalar(ob_info.quantity) as int64) as bom_outbound_qty
    , json_extract_scalar(ob_info.exp_date) as bom_exp_date
    , json_extract_scalar(ob_info.lot) as bom_lot
    , json_extract_scalar(ob_info.do_code) as do_code
    , json_extract_scalar(ob_info.po_code) as po_code
    , coalesce(safe_cast(json_extract_scalar(combo_item.vat) as int64), m.vat) as bom_vat
    , safe_cast(json_value(extra_props, '$.deal_vendor_price') as float64) as deal_vendor_price
    , safe_cast(json_value(extra_props, '$.deal_info.discounted') as float64) as deal_sale_price
from t0 as m
    , unnest(json_query_array(m.extra_props, '$.sub_items')) AS combo_item
    , unnest(json_query_array(combo_item.outbound_infos)) AS ob_info
where 1=1
and outbound_infos is null
)
, soi0 as (
    select 'combo' as product_type
        , c.*
    from combo c
    union all
    select 'product' as product_type
        , p.*
    from product p
)
, so as (
    select order_id
        , customer_id
        , warehouse_code
        , sale_order_code as so_code
        , status
    from ${source.platinum}.marketplace_prd_order_v2_order o
    where 1=1
    and created_date >= (select date_sub(start_date, interval 3 month) from params)
)
, tdo as (
    select delivery_order_code as do_code
        , date(outbound_time,'+07') as outbound_date_local
    from  ${source.platinum}.warehouse_prd_core_delivery_order tdo
    where 1=1
    and created_date >= (select date_sub(start_date, interval 3 month) from params)
    and status not like '%CANCEL%'
)
, soi as (
select so.so_code
    , so.customer_id
    , so.warehouse_code
    , so.status
    , tdo.outbound_date_local
    , soi0.*
    , coalesce(case
        when product_type = 'product' then original_bom_price
        when product_type = 'combo' then original_bom_price * least(((actual_sale_price * actual_outbound_qty)
            / sum(original_bom_price * bom_outbound_qty) over (partition by soi0.order_id, soi0.product_id))
            ,1)
        end,0) as bom_sale_price
    , case
        when product_type = 'product' then deal_vendor_price
        when product_type = 'combo' then original_bom_price * least(((deal_vendor_price * actual_outbound_qty)
            / sum(original_bom_price * bom_outbound_qty) over (partition by soi0.order_id, soi0.product_id))
            ,1)
        end as bom_deal_purchase_price
from soi0
inner join so on so.order_id = soi0.order_id
inner join tdo on soi0.do_code = tdo.do_code
where 1=1
)
, fin as (
    select *
    from soi
    where 1=1
    and outbound_date_local is not null
    and outbound_date_local >= (select start_date from params)
)
select *
from fin
where 1=1

