config {
    type: "table", 
    description: 
        `
        Margin from External Seller's Products
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: daily at 8h30, 10h30, 12h30, 15h30, 17h30;
        Source: 
            ${source.ref}.fact_outbound_item,
            ${source.ref}.fact_order_item,
            ${source.ref}.fact_po_item,
            ${source.ref}.fact_vendor_bill_item,
            ${source.ref}.fact_price_after_rebate,
        `,
    columns: {
    },
    tags: ["8h30", "10h30", "12h30", "15h30" ,"17h30"],
    bigquery: {
        partitionBy: "DATE(created_at)",
        clusterBy: ["sku_code", "product_id"]
    }

}

