config {
    type: "table", 
    description: 
        `
        Sales Price, Purchase Price, Price after rebate of MEDX's Products in each Order (serving the purpose of calculating margin)
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.ref}.fact_outbound_item,
            ${source.ref}.fact_order_item,
            ${source.ref}.fact_po_item,
            ${source.ref}.fact_vendor_bill_item,
            ${source.ref}.fact_price_after_rebate,
        `,
    columns: {
    },
    tags: ["custom_1h_past5"],
    bigquery: {
        partitionBy: "DATE(created_at)",
        clusterBy: ["sku_code", "product_id"]

    },
    assertions: {
        nonNull: ["created_at", "product_id", "sku_code", "po_code"]
  
    }
}

WITH
    outbound_item AS (
        SELECT
            a.mg_id
            , a.order_id
            , a.created_at
            , a.sku_code AS sku_code_original
            , a.sku_bom_code AS sku_code
            , a.product_id AS product_id_original
            , a.product_bom_id AS product_id
            , a.seller_code
            , a.outbound_quantity
            , a.po_code
            , DATE(TIMESTAMP_ADD(b.outbound_time, INTERVAL 7 HOUR)) AS outbound_date
        FROM ${ref('fact_outbound_item')} AS a
            LEFT JOIN (
                SELECT *
                FROM ${ref('warehouse_prd_core_delivery_order')}
                WHERE created_date >= '2024-06-01'
            ) AS b 
                ON a.do_code = b.delivery_order_code
        WHERE
            created_at >= '2024-06-01'
            AND outbound_time >= TIMESTAMP_SUB('2024-06-01', INTERVAL 7 HOUR)
    )

    , order_item AS (
        SELECT
            mg_id
            , order_id
            , sku_orignal_code AS sku_code_original
            , sku_code
            , product_id
            , sales_price AS unit_price
            , sales_price_original AS unit_price_original
            , item_type
        FROM ${ref('fact_order_item')}
        WHERE
            created_at >= '2024-06-01'
    )

    , po_price AS (
        SELECT
            DATE(created_time) AS po_created_date
            , po_code
            , product_id
            , REGEXP_REPLACE(sku, r'MEDX-HN', 'MEDX') AS sku_code
            , fc_code
            , avg_unit_price AS po_purchase_price
            , vendor_code
            , line_manager_combine
        FROM ${ref('fact_po_item')}
        GROUP BY ALL
    )

    , vendor_bill_price AS (
        SELECT
            po_code
            , product_id
            , REGEXP_REPLACE(sku_code, r'MEDX-HN', 'MEDX') AS sku_code
            , fc_code
            , price_unit_vat AS vb_purchase_price
        FROM ${ref('fact_vendor_bill_item')} 
        GROUP BY ALL
    )

    , price_after_rebate AS (
        SELECT
            rebate_date
            , a.product_id
            , b.sku_code
            , fc_code
            , vendor_code
            , price_after_rebate
            , price_after_rebate_with_adhoc_promotion
        FROM ${ref('fact_price_after_rebate')} AS a
            LEFT JOIN ${ref('dim_sku')} AS b ON a.product_id = b.product_id AND b.seller_code = "MEDX"
    )

SELECT
    ob.created_at
    , ob.outbound_date
    , ob.order_id
    , ob.sku_code_original
    , ob.sku_code
    , ob.product_id_original
    , ob.product_id
    , ob.seller_code
    , oi.unit_price
    , ob.outbound_quantity
    , ob.po_code
    , p.po_purchase_price
    , v.vb_purchase_price
    , p.fc_code AS po_fc_code
    , r.price_after_rebate
    , r.price_after_rebate_with_adhoc_promotion
    , oi.item_type
FROM outbound_item AS ob
    LEFT JOIN order_item AS oi 
        ON ob.mg_id = oi.mg_id AND ob.sku_code = oi.sku_code
    LEFT JOIN vendor_bill_price AS v
        ON v.po_code = ob.po_code AND v.sku_code = ob.sku_code
    LEFT JOIN po_price AS p 
        ON p.po_code = ob.po_code AND p.sku_code = ob.sku_code
    LEFT JOIN price_after_rebate AS r
        ON r.sku_code = ob.sku_code
        AND r.vendor_code = p.line_manager_combine
        AND r.fc_code = p.fc_code
        AND r.rebate_date = p.po_created_date