config {
    type: "view",
    schema: "de_buymed_vn",
    name: "metadata_table_migrate",
    description: "PIC: Minh Luu"
}
SELECT 
    table_id,
    dataset_id,
    dataset_id || "." || table_id full_table_id,
    TIMESTAMP_MILLIS(last_modified_time) last_modified_time,
    TIMESTAMP_MILLIS(creation_time) creation_time,
    row_count,
    CASE 
        WHEN size_bytes / (1024 * 1024 * 1024) > 1 THEN CAST(size_bytes / (1024 * 1024 * 1024) AS STRING ) || " GB" 
        WHEN size_bytes / (1024 * 1024 ) > 1 THEN CAST(size_bytes / (1024 * 1024 ) AS STRING ) || " MB" 
        ELSE  CAST(size_bytes AS STRING ) || " byte" 
    END AS readable_size,
    size_bytes,
    CASE
        WHEN type = 1 THEN "BASE TABLE"
        WHEN type = 2 THEN "VIEW"
        WHEN type = 3 THEN "EXTERNAL"
        WHEN type = 6 THEN "SNAPSHOT"
        WHEN type = 5 THEN "CLONE"
        ELSE "UNKNOWN"
    END AS table_type,
    REGEXP_CONTAINS(table_id,"drop") is_migrated,
    IF(
        REGEXP_CONTAINS(table_id,"_migrate_drop_"),
        PARSE_TIMESTAMP("%Y%m%dT%H%M%S", SPLIT(table_id,"_migrate_drop_")[1] )
        , CAST(NULL AS TIMESTAMP)
    ) migrated_time
FROM (
    SELECT * FROM silver_buymed_vn.__TABLES__
    UNION ALL 
    SELECT * FROM silver_buymed_vn_restricted.__TABLES__
    UNION ALL
    SELECT * FROM silver_buymed_th.__TABLES__
    UNION ALL
    SELECT * FROM silver_buymed_cam.__TABLES__
)
WHERE REGEXP_CONTAINS(table_id, "migrate")