config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "marketplace_prd_order_v2_reconciliation",
    description : `
    PIC: minh.luu
    Partition by: created date
    cluster by: "start_date","reconciliation_status","from_time","reconcile_schedule_time_index"
    `,
    tags:["platinum","marketplace_prd_order-v2"]
}

  WITH silver AS (
    SELECT
      key,mg_id,to_time,seller_code,reconcile_schedule_time_index,reconciliation_status,created_time,reconciled_time,allow_confirm_time,from_time,bonus_amount,fulfillment_fee,last_updated_time,listing_fee,penalty_fee,total_buyer_fee,total_payment,total_revenue,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.marketplace_prd_order_v2_reconciliation
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,to_time,seller_code,reconcile_schedule_time_index,reconciliation_status,created_time,reconciled_time,allow_confirm_time,from_time,bonus_amount,fulfillment_fee,last_updated_time,listing_fee,penalty_fee,total_buyer_fee,total_payment,total_revenue,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `marketplace_prd_order_v2_reconciliation`)}
  )
  SELECT *
  FROM (
    SELECT p.*
    FROM platinum p
    LEFT JOIN silver s 
        ON p.mg_id = s.mg_id 
    WHERE s.mg_id is null 

    UNION ALL 

    SELECT s.*
    FROM silver s
    WHERE action <> "d"
  )
  WHERE created_time is not null and last_updated_time is not null 
  