config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "marketplace_prd_order_v2_invoice",
    description : `
    PIC: minh.luu
    Partition by: created date
    Cluster by: "delivered_time","invoice_deadline","invoice_status"
    `,
    tags:["platinum","marketplace_prd_order-v2"]
}

  WITH silver AS (
    SELECT
      key,mg_id,order_code,seller_code,circa_issuance,created_time,customer_code,customer_id,delivered_time,downloaded_file,invoice_code,invoice_deadline,invoice_id,invoice_price,invoice_status,last_updated_time,no_need_invoice,order_id,order_seller_code,order_seller_id,request,seller_downloaded_file,seller_sent_mail,helo,invoice_document_url,is_late,issued_time,mail_from,mail_processing_status,return_status,return_ticket_ids,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.marketplace_prd_order_v2_invoice
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,order_code,seller_code,circa_issuance,created_time,customer_code,customer_id,delivered_time,downloaded_file,invoice_code,invoice_deadline,invoice_id,invoice_price,invoice_status,last_updated_time,no_need_invoice,order_id,order_seller_code,order_seller_id,request,seller_downloaded_file,seller_sent_mail,helo,invoice_document_url,is_late,issued_time,mail_from,mail_processing_status,return_status,return_ticket_ids,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `marketplace_prd_order_v2_invoice`)}
  )

SELECT * FROM (
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
)
WHERE created_time is not null and last_updated_time is not null 