config {
    type: "assertion",
    name: "gold_buymed_vn2_fact_order_item_strategic_assertions_nonNull",
    description: `PIC: Minhluu
    Source: fact_order_item_strategic`,
    tags: ['0h00']
}

SELECT 
    "order_id IS NOT NULL" as reason,
    order_created_time
FROM 
    ${ref(`fact_order_item_strategic`)}
WHERE order_id IS NULL

UNION ALL 

SELECT 
    "product_id IS NOT NULL" as reason,
    order_created_time
FROM 
    ${ref(`fact_order_item_strategic`)}
WHERE product_id IS NULL

