config {
    type: "table", // view, table , incremental
    name: "example_model",
    description: `PIC: <name> , model_type: <view, material_view, table, incremental> ; schedule: 0h00 daily
    Source:
        ${source.silver}.<table_name>
        ${source.silver}.<table2_name>`,
    columns:{
        ele_id: "NonNull | <more description if required> | <When it is reference column from silver or platinum, you can write which source here>",
        ele_name: "Nullable | <Null Reason> | <more desciption if required>",
        created_time: "NonNull | Datetime is in +7 timezone", // Timestamp_add + 7 rather than datetime(col, "+7") 
        Logic_column : "Nullable | Reason for this column | if a = b then Wrong, if a = a then Right, else Null",
        Nullable_Column : "Nullable | < When is it Null? > ",
        Source_insure_NonNull : "NonNull | <more desciption if required>",
        NonNull_Column : "NonNull | <more desciption if required>"
    },
    tags: ["example"], // 0h00, 1h00, ..., you can go to workflow to track or request Minhluu to add new tags
    bigquery: { /* except view */
        partitionBy: "DATE(created_time)",
        // clusterBy: ["cart_id"] // Optional
    },
    assertions: { /* guaranteed columns: primary key, Source_insure_NonNull */
        uniqueKey : "ele_id",
        /* uniqueKeys : [["order_id","item_id"]] // For if composite primary key */

        nonNull : ("ele_id" , "Source_insure_NonNull"),
        rowConditions : [
            `created_time BETWEEN ( TIMESTAMP(CURRENT_DATETIME("+7") - INTERVAL 1 MONTH) ) AND TIMESTAMP(CURRENT_DATETIME("+7"))`, // snapshot
            `email like "%@%.%"`, // format
            `Source_insure_NonNull in ("AAAA","BBBB","CCCC")` // Source system insure data in cases 
        ]
        /* For more detail read: https://cloud.google.com/dataform/docs/assertions */
    },
    dependencies: [
        /* 
        */
        {"name":"4_assertions__assertions","includeDependentAssertions":false}
    ]
}

WITH dedup_full_table AS (
    SELECT 
        customer_id,
        flatten_location
    FROM ${source.platinum}.marketplace_prd_cart_cart
)

SELECT
    "1b2c" AS ele_id,
    "Hello World" AS ele_name,
    "minh.luu@buymed.com" AS email,
    Timestamp_add(current_timestamp(), interval +7 hour) AS created_time,
    CASE
        WHEN "a" = "b" THEN "WRONG"
        WHEN "a" = "a" THEN "RIGHT"
        ELSE NULL
    END AS Logic_column,
    NULL AS Nullable_Column,
    "NonNull" AS Source_insure_NonNull,
    CASE
        WHEN "Nullable_Column" IS NOT NULL THEN "Column_value"
        ELSE "Default_Value"
    END AS NonNull_Column

post_operations {                
    /*
    Why we create primary key and foregin key ?
        In typical relational databases, primary keys and foreign keys are used to ensure data integrity. 
        A primary key value is unique for each row and is not NULL. Each foreign key value in a row must be present 
        in the primary key column of the primary key table, or be NULL. Primary and foreign key relationships are 
        created and managed through DDL statements.
        Ref-page : https://cloud.google.com/bigquery/docs/information-schema-table-constraints#:~:text=In%20typical%20relational,DDL%20statements.
    
    But in BigQuery, we set these key constraints without enforced. For the reason, please read:
        https://stackoverflow.com/questions/42938662/google-bigquery-there-are-no-primary-key-or-unique-constraints-how-do-you-preve#:~:text=So%2C%20on%20BigQuery%2C%20you%20actually%20let%20all%20data%20in%2C%20and%20favor%20an%20append%2Donly%20design.%20That%20means%20that%20by%20design%20you%20have%20a%20database%20that%20holds%20a%20new%20row%20for%20every%20update.%20Hence%20if%20you%20want%20to%20use%20the%20latest%20data%2C%20you%20need%20to%20pick%20the%20last%20row%20and%20use%20that.
    
    So why we still set key constrains in Bigquery? The reason is provide information to users, give better optimize queries faster
        Ref-page : https://cloud.google.com/blog/products/data-analytics/join-optimizations-with-bigquery-primary-and-foreign-keys#:~:text=Why%20create%20Primary,and%20Join%20Reordering.
    */
    ALTER TABLE ${self()} 
        ADD PRIMARY KEY (ele_id) NOT ENFORCED;
        -- ADD FOREIGN KEY (ele_id) references ${ref(`temp`)}(order_id) NOT ENFORCED;

        /*
        There's a problem when getting data from tables like dim_supplier or source.silver.seller. 
        We usually use Foreign Keys to show where the data comes from.
        You want to use Foreign Key to note where you get from
        But Dataform gives an error if we use the ${ref()} function because it thinks there's a circular dependency.
        This error isn't really a problem because BigQuery doesn't strictly check Foreign Keys

        > To bypass this error and still set foreign key, I was make source.ref constrains in js folder - include folder
        > bellow is example
        */
        -- ADD FOREIGN KEY (ele_id) references ${source.ref}.temp (order_id) NOT ENFORCED, 
    ALTER TABLE ${self()}
        ALTER COLUMN NonNull_Column SET DEFAULT "Default_Value"; -- Optional
}