config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "core_prd_activity_activity",
    description : `

    Partition by: created date
    ClusterBy: ["template_code"]
    `,
    tags:["platinum","core_prd_activity"]
}
 
  WITH silver AS (
    SELECT
      key, mg_id, path, ua_metadata, result_error_code, created_time, account_id, template_code, data, primary_key, keys, session, ip, result_status, username, fullname, activity_id, type, target, method, user_agent, result_message, synced_at, extra_props, action, ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.core_prd_activity_activity
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
      AND NOT(action ='d'
      
               AND DATE(created_time, 'Asia/Ho_Chi_Minh') < DATE_SUB(CURRENT_DATE('Asia/Ho_Chi_Minh'), INTERVAL 12 MONTH))
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC
    )
  ), platinum AS (
    SELECT 
      key, mg_id, path, ua_metadata, result_error_code, created_time, account_id, template_code, data, primary_key, keys, session, ip, result_status, username, fullname, activity_id, type, target, method, user_agent, result_message, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `core_prd_activity_activity`)}
  )
SELECT p.*
FROM platinum p
WHERE NOT EXISTS (SELECT 1 FROM silver s WHERE s.mg_id = p.mg_id)


  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
