config {
    type: 'incremental',
    schema: "buying_agent_input",
    tags: ["AI_Buying_Agent"]
}

SELECT
    SAFE_CAST(product_id AS STRING)  AS  product_id
    , ingredient_name AS active_ingredient
    , volume AS strength
    , CURRENT_DATE("+7") AS snapshot_date
FROM ${ref("dim_product_ingredient")}

post_operations {
    IF NOT EXISTS (
        SELECT 1
        FROM buying_agent_input.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
        WHERE table_name = 'product_ingredients'
        AND constraint_type = 'PRIMARY KEY'
    ) THEN
    ALTER TABLE ${self()} 
        ADD PRIMARY KEY (product_id, active_ingredient, snapshot_date) NOT ENFORCED,
        ADD FOREIGN KEY (product_id, snapshot_date) REFERENCES ${ref("buying_agent_input",  "product_catalog")}(product_id, snapshot_date) NOT ENFORCED;
    END IF;
}