config {
  type: "view",
  dependencies: ["fact_order_item", "dim_calendar", "agg_seller_classification"],
  tags: ["STRATEGIC-DASHBOARDING"]
}

WITH cte_date AS (
	select date_sub( timestamp( date_trunc( date_sub( current_date('+7'), interval 12 month) , month ) ) , interval 7 hour ) as start_date
  	-- select  timestamp( date_trunc( current_date('+7') , month ) ) as start_date
  -- select date_sub( timestamp( date_trunc( current_date('+7'), month ) ) , interval 7 hour ) as start_date
--   SELECT date_sub( timestamp( date_trunc( date_sub( current_date('+7'), interval 1 day) , day ) ) , interval 7 hour ) as start_date
)

, cte_agg as (
SELECT 
  FORMAT_TIMESTAMP('%Y-%m', created_at) as year_month
  -- , SUM(oi.outbound_quantity * sales_price) as outbound
  -- , SUM(GREATEST(oi.outbound_quantity, oi.reserved_quantity) * sales_price) / SUM(oi.demand_quantity * sales_price) as fr
  , ROUND(
    100 * SUM(GREATEST(oi.outbound_quantity, oi.reserved_quantity) * sales_price) / SUM(oi.demand_quantity * sales_price)
    , 2
  ) AS fulfillment_rate
--   , COUNT(DISTINCT(oi.seller_code)) as active_seller
  , COUNT(DISTINCT(oi.product_id)) as active_product
FROM gold_buymed_vn2.fact_order_item as oi
WHERE 
  created_at >= (SELECT start_date FROM cte_date)
GROUP BY 1
)

, cte_seller AS (
    SELECT 
        year_month
        , COUNT(DISTINCT supplier_id ) as active_seller
    FROM gold_buymed_vn2.agg_seller_classification
    WHERE 
        active_seller = 1
    --     som = DATE_TRUNC(CURRENT_DATE("+7"), MONTH)
    GROUP BY 1
)

SELECT
  year_month,
  metric,
  performance
FROM
  cte_agg,
  UNNEST([
    STRUCT('FFR' AS metric, fulfillment_rate AS performance)
    , STRUCT('PRODUCT' AS metric, active_product AS performance)
  ]) AS record
UNION ALL
SELECT
  year_month,
  metric,
  performance
FROM
  cte_seller,
  UNNEST([
        STRUCT('SELLER' AS metric, active_seller AS performance)
  ]) AS record


