config {
  type: "view",
  dependencies: ["fact_order", "dim_calendar"],
  tags: ["STRATEGIC-DASHBOARDING"]
}

WITH cte_agg as (
SELECT
  c.year_month
  , ROUND(
      100 * COUNTIF(TIMESTAMP_DIFF(o.delivered_time, o.expected_delivery_time, SECOND) <= 0) / COUNT(1)
    , 2
  ) AS ontime_percentage
FROM gold_buymed_vn2.fact_order as o
LEFT JOIN ${ref("dim_calendar")} as c on DATE(o.created_at) = c.Date
WHERE 
  o.delivered_time is not null
GROUP BY 1
)

SELECT
  year_month,
  metric,
  performance
FROM
  cte_agg,
  UNNEST([
    STRUCT('ONTIME' AS metric, ontime_percentage AS performance)
  ]) AS record


