config {
  type: "view",
  dependencies: ["fact_order", "dim_calendar"],
  tags: ["STRATEGIC-DASHBOARDING"]
}

WITH cte_agg as (
SELECT
  c.year_month
  -- COUNT(1) AS count_orders
  -- , SUM(
  --   CASE WHEN order_status = "CANCEL" THEN ordered_amount
  --   ELSE 0
  --   END
  -- ) AS canceled_amount
  , ROUND(
      100 * SUM(CASE WHEN order_status = "CANCEL" THEN ordered_amount ELSE 0 END) / (SUM(ordered_amount) + 1)
    , 2
  ) AS cancellation_percentage
FROM gold_buymed_vn2.fact_order as o
LEFT JOIN ${ref("dim_calendar")} as c on DATE(o.created_at) = c.Date

GROUP BY 1
)

SELECT
  year_month,
  metric,
  performance
FROM
  cte_agg,
  UNNEST([
    STRUCT('CANCEL' AS metric, cancellation_percentage AS performance)
  ]) AS record