config {
  type: "view",
  tags: ["FC-PRODUCTIVITY"]
}

with cte_date as (
	select date_sub(date_trunc(date_sub( current_timestamp() , interval 1 day), day), interval 7 hour)  as start_date
)

select
    a.mg_id
    , CAST(SPLIT(a.audit_session_task_code, '-')[OFFSET(2)] AS INT64) as ticket_id
    , a.audit_session_task_code as ticket_code
    , a.warehouse_code as fc_code
    , timestamp_add( a.start_time, interval 7 hour ) as start_at
    , timestamp_add( a.end_time, interval 7 hour ) as done_at
    , a.audit_by AS employee_id
    , a.total_checked_lines AS total_sku
    , a.total_sku_items as total_item
    , timestamp_add( current_timestamp, interval 7 hour ) as transformed_at
    , 'CYCLE_COUNT' as stage_code
FROM ${source.platinum}.warehouse_prd_inventory_audit_session_task as a
where
   a.end_time >= (select start_date from cte_date)