
config {
    type: "table",
    description: `cos_demand_planning detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    disabled: true,
   // tags: ["custom_2h_past5"],
    name: "cos_assortment_nso",
    columns: {
        
    }
}


Select * 
       ,concat(product_id, "_",1) as product_client_id
       ,concat(product_id, "_",pos_code) as product_pos_code

from ${source.external}.cos_assortment_nso
where product_id is not null 
