
config {
    type: "table",
    description: `tracking performance của mặt hàng trending. Report for team chị Đức
                 PIC: huyen.ngo; model_type: Table ;
                 schedule: At minute 5 every 2 hours`,
    tags: ["custom_2h_past5"],
    disabled: true,
    name: "purchase_top_trending",
    columns: {
        
    }
}

SELECT   
        trial_period
       -- ,CASE WHEN dat_time IS NOT NULL THEN CAST(dat_time AS DATE) ELSE NULL END AS date_time
       ,date_time
       -- ,CASE WHEN product_id IS NOT NULL AND product_id <> 'New' THEN CAST(product_id AS INT64) ELSE product_id END AS 
       ,product_id
       ,CONCAT(product_id, '_', 1) AS product_client_id
       ,product_name 
       ,brand
FROM buymed_external.purchase_top_trending
WHERE (product_id IS NOT NULL
    OR product_id <> 'New'
    OR product_name IS NOT NULL)
