config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "seller_prd_purchasing_purchase_order_item",
    description : `
    PIC: minh.luu
    Partition by: created date
    Cluster By: ["product_id","warehouse_code","vendor_code","po_code"]
    `,
    tags:["platinum","seller_prd_purchasing"]
}
  WITH silver AS (
    SELECT
      key,mg_id,purchaser_code,refer_price,discount_price,delivery_warehouse_code,product_code,unit_price,vat_price,source_quotation,unit,discount_percent,po_id,po_item_id,warehouse_code,seller_code,product_name,vat,price_after_discount,expect_quantity,po_code,vendor_code,product_id,sku,total_price,created_time,bill_quantity,last_updated_time,contract_price_code,price_after_rebate,actual_quantity,description,gift_quantity,image_url,packaging,is_near_expiration,quotation_unit_price,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.seller_prd_purchasing_purchase_order_item
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,purchaser_code,refer_price,discount_price,delivery_warehouse_code,product_code,unit_price,vat_price,source_quotation,unit,discount_percent,po_id,po_item_id,warehouse_code,seller_code,product_name,vat,price_after_discount,expect_quantity,po_code,vendor_code,product_id,sku,total_price,created_time,bill_quantity,last_updated_time,contract_price_code,price_after_rebate,actual_quantity,description,gift_quantity,image_url,packaging,is_near_expiration,quotation_unit_price,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `seller_prd_purchasing_purchase_order_item`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"