config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "seller_prd_purchasing_inbound_request_item",
    description : `
    PIC: minh.luu
    Internal: internal.thuocsi.vn/internal-seller/MEDX/PUR_HCM/inbound-request

    partitionBy: created_date
    clusterBy: ["inbound_request_code","status","sku","product_id"]
    `,
    tags:["platinum","seller_prd_purchasing"]
}

  WITH silver AS (
    SELECT
      key,mg_id,apply_time,sku,inbound_request_id,inbound_request_item_code,expect_quantity,status,vendor_code,seller_code,warehouse_code,inbound_request_code,inbound_request_item_id,is_active,created_time,product_code,product_id,inbound_request_type,last_updated_time,synced_at,extra_props,action,ingest_time,metadata,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.seller_prd_purchasing_inbound_request_item
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,apply_time,sku,inbound_request_id,inbound_request_item_code,expect_quantity,status,vendor_code,seller_code,warehouse_code,inbound_request_code,inbound_request_item_id,is_active,created_time,product_code,product_id,inbound_request_type,last_updated_time,synced_at,extra_props,action,ingest_time,metadata,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `seller_prd_purchasing_inbound_request_item`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  