config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "seller_prd_promotion_promotion_gift_by_level_item",
    tags:["platinum","seller_prd_promotion"]
}
SELECT
    *,
    CASE
        WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
        ELSE DATE( '2099-01-01' )
    END
    created_date
FROM ${source.silver}.seller_prd_promotion_promotion_gift_by_level_item
QUALIFY ROW_NUMBER() OVER (_window) = 1 
        WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC,
        IF
            (action='d',3,
            IF
            (action='u',2,1)) DESC
        ,last_updated_time DESC)