config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "seller_prd_purchasing_vendor_bill_item",
    description : `
    PIC: minh.luu
    Internal: internal-seller/MEDX/PUR_HCM/vendor-bill
    Partition by: created date
    Cluster By: ["vendor_bill_id","po_code","product_id"]
    `,
    tags:["platinum","seller_prd_purchasing"]
}
  WITH silver AS (
    SELECT
      key,mg_id,growth_invoice_id,quantity,total_price,product_id,lot,po_code,vendor_bill_code,vat,discount_price,vendor_bill_item_code,growth_invoice_item_id,item_name,unit,vat_price,total_discount_price,price,sku,vendor_bill_id,created_time,is_inbound_completed,price_after_discount,product_name,product_code,exp_date,discount_percent,last_updated_time,actual_quantity,po_trackings,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.seller_prd_purchasing_vendor_bill_item
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,growth_invoice_id,quantity,total_price,product_id,lot,po_code,vendor_bill_code,vat,discount_price,vendor_bill_item_code,growth_invoice_item_id,item_name,unit,vat_price,total_discount_price,price,sku,vendor_bill_id,created_time,is_inbound_completed,price_after_discount,product_name,product_code,exp_date,discount_percent,last_updated_time,actual_quantity,po_trackings,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `seller_prd_purchasing_vendor_bill_item`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"