config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "seller_prd_purchasing_contract_price_item",
    description : `
    PIC: minh.luu
    Internal: 

    partitionBy: created_date
    clusterBy:
    `,
    tags:["platinum","seller_prd_purchasing"]
}

  WITH silver AS (
    SELECT
      key,mg_id,warehouse_code,created_time,contract_price_id,unit_price,vat,contract_price_item_id,product_id,contract_price_code,product_code,product_name,discount,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.seller_prd_purchasing_contract_price_item
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          )
  ), platinum AS (
    SELECT 
      key,mg_id,warehouse_code,created_time,contract_price_id,unit_price,vat,contract_price_item_id,product_id,contract_price_code,product_code,product_name,discount,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `seller_prd_purchasing_contract_price_item`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  