
config {
  type: "view",
  schema: "platinum_buymed_vn",
  name: "seller_prd_core_vendor_store_tag",
  description : `
  PIC: long.nguyen
  Partition by: created date
  `,
  tags:["platinum","seller_prd_core_vendor_store_tag"]
}

WITH silver AS (
  SELECT
    key, mg_id, tag_code, position, code, type, title, title_color, background_title_color, title_banner, tag_id, seller_code, is_active, background_color, created_time, last_updated_time, synced_at, extra_props, action, ingest_time,
    CASE
      WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
      ELSE DATE('2099-01-01')
    END created_date,
    CAST(NULL AS DATETIME) AS platinum_refresh
  FROM silver_buymed_vn.seller_prd_core_vendor_store_tag
  -- WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
  QUALIFY ROW_NUMBER() OVER (_window) = 1
    -- AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
  WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
      IF(action='d',3, IF(action='u',2,1)) DESC,
      last_updated_time DESC
  )
)

-- platinum AS (
--   SELECT
--     key, mg_id, tag_code, position, code, type, title, title_color, background_title_color, title_banner, tag_id, seller_code, is_active, background_color, created_time, last_updated_time, synced_at, extra_props, action, ingest_time,
--     created_date,
--     platinum_refresh
--   FROM ${ref(`platinum_buymed_vn__stg`, `seller_prd_core_vendor_store_tag`)}
-- )

-- SELECT p.*
-- FROM platinum p
-- LEFT JOIN silver s
--   ON p.mg_id = s.mg_id
-- WHERE s.mg_id IS NULL

-- UNION ALL

SELECT s.*
FROM silver s
WHERE action <> "d"
