config {
    type:"view",
    name: "seller_prd_promotion_promotion_discount_item",
    schema: "platinum_buymed_vn",
    tags: ["platinum","seller_prd_promotion"]
}
WITH over_tbl AS (
        SELECT
            mg_id,
            ARRAY_AGG(
                key 
                ORDER BY
                    synced_at DESC,
                    IF (action='d',3, IF (action='u',2,1)) DESC,
                    last_updated_time DESC
                LIMIT 1
            )[0] key ,
            ARRAY_AGG(
                action 
                ORDER BY
                    synced_at DESC,
                    IF (action='d',3, IF (action='u',2,1)) DESC,
                    last_updated_time DESC
                LIMIT 1
            )[0] action
        FROM ${source.silver}.seller_prd_promotion_promotion_discount_item
        
        GROUP BY mg_id HAVING action != "d"
    )
    SELECT
        * ,
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END AS created_date,
        CURRENT_DATETIME() AS platinum_refresh
    FROM ${source.silver}.seller_prd_promotion_promotion_discount_item
    WHERE key IN (SELECT o.key FROM over_tbl o)
    

    -- For stituation that key is dedup because of manual import
    QUALIFY ROW_NUMBER() OVER(w) = 1
    WINDOW w AS (
        PARTITION BY mg_id
        ORDER BY synced_at desc,
            synced_at DESC,
        IF (action='d',3, IF (action='u',2,1)) DESC,
        last_updated_time DESC
    )