config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "seller_prd_core_setting_for_sc",
    tags:["platinum","seller_prd_core"]
}
SELECT
    *,
    CASE
        WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
        ELSE DATE( '2099-01-01' )
    END
    created_date
FROM ${source.silver}.seller_prd_core_setting_for_sc
QUALIFY ROW_NUMBER() OVER (_window) = 1 AND action <> 'd'
WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
    IF
        (action='d',3,
        IF
        (action='u',2,1)) DESC
    ,last_updated_time DESC)