config {
    type: "table",
    description: "PIC: huong.dang, schedule 2:00am daily",
    schema: "gold_ml",
    tags: ["2h00"]
}

WITH
  A AS(
  SELECT
    DATE(TIMESTAMP_ADD(TIMESTAMP(JSON_VALUE(extra_props, '$.created_time')), INTERVAL 7 HOUR)) AS date,
    -- JSON_VALUE(extra_props, '$.source') AS competitor,
    JSON_VALUE(extra_props, '$.market_name') AS competitor_product_name,
    SAFE_CAST(JSON_VALUE(extra_props, '$.market_price') AS INT64) AS competitor_price,
    SAFE_CAST(JSON_VALUE(extra_props, '$.product_id') AS INT64) AS product_id,
  IF
    ( LOWER(JSON_VALUE(extra_props, '$.market_data.unit'))= '', NULL, LOWER(JSON_VALUE(extra_props, '$.market_data.unit')) ) AS competitor_unit
  FROM
    ${ref('marketplace_prd_product_v2_product_market_price')}
  WHERE
    JSON_VALUE(extra_props, '$.source') IS NOT NULL
    AND JSON_VALUE(extra_props, '$.product_id') IS NOT NULL
    AND JSON_VALUE(extra_props, '$.market_price') IS NOT NULL)

SELECT
  DISTINCT date,
  product_id,
  MIN(competitor_price) OVER (PARTITION BY date, product_id) AS min_competitor_price
FROM A
ORDER BY 2