config {
    type:"operations",
    description: "PIC:MinhLuu",
    tags: ['6h00']
}

IF( (SELECT IF(max(date)="2024-10-02",1,0) FROM ${ref(`agg_gmv_by_price_sku_fc_code`)}) =0 )
  THEN 
    Create OR REPLACE table dataform_assertions.Huong_dim_order_channel AS ( select * FROM ${ref(`dim_order_channel`)} WHERE created_time > "2024-09-01");
    Create OR REPLACE table dataform_assertions.Huong_agg_gmv_by_price_sku_fc_code AS ( select * FROM ${ref(`agg_gmv_by_price_sku_fc_code`)});
    Create OR REPLACE table dataform_assertions.Huong_fact_order AS (SELECT * FROM ${ref(`fact_order`)} WHERE created_at > "2024-09-01");
    CREATE OR REPLACE table dataform_assertions.Huong_dim_calendar AS (SELECT * FROM ${ref(`dim_calendar`)}); 
    -- For dim_calendar check the day of today
    CREATE table dataform_assertions.Huong_fact_order_item AS (SELECT * FROM ${ref(`fact_order_item`)} WHERE created_at > "2024-09-01");

    CREATE OR REPLACE TABLE gold_buymed_vn2.agg_gmv_by_price_sku_fc_code AS (
        WITH
            order_status AS(
            SELECT
                DATE(a.created_at) AS created_date,
                a.order_id,
                CASE
                WHEN a.fc_code IS NULL THEN "BD"
                ELSE a.fc_code
            END AS fc_code
            FROM  ${ref('fact_order')} AS a
            LEFT JOIN ${ref(`dim_order_channel`)} AS c USING (order_id)
            WHERE EXTRACT(YEAR FROM a.created_at) >= 2024
                AND a.order_status <> "CANCEL"
                AND c.order_channel = "MARKETPLACE")


            SELECT
            b.created_date AS date,
            a.product_id,
            c.sow,
            a.sku_code,
            a.sales_price,
            count (a.sales_price) AS frequent_price,
            CONCAT(a.sku_code,"_", b.fc_code ) AS sku_fc_code,
            CONCAT(a.product_id,"_", b.fc_code, "_", a.seller_code ) AS product_fc_seller,
            SUM(a.demand_quantity) AS demand_quantity
            FROM ${ref('fact_order_item')} AS a
            LEFT JOIN order_status AS b USING (order_id)
            LEFT JOIN ${ref('dim_calendar')} AS c ON b.created_date = c.date
            WHERE
            (a.item_type IN ("NORMAL", "DEAL")
                AND a.seller_code="MEDX"
                AND b.created_date IS NOT NULL)
            GROUP BY ALL
    );

    ASSERT (SELECT FALSE) AS "Do ma đó chị Hương";

  END IF;