

config {
    type: "incremental",
    name: "seller_prd_promotion_log_price_after_rebate",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id',
        nonNull: ["created_date"]
    },
    bigquery: {
        partitionBy: "created_date"
    },
    tags:["custom_2h_past5"]
}

SELECT
 * ,
 CASE 
    WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
    ELSE "2099-01-01"
  END AS created_date
FROM ${source.silver}.seller_prd_promotion_log_price_after_rebate o 
 ${
    when(incremental(), 
      `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()}) 
      QUALIFY ROW_NUMBER() OVER (_window) = 1`,
      `QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'`
    )
  }
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)



