config {
    type: "incremental",
    name: "monitoring_prd_realtime_user_failed_login_v8",
    schema: "platinum_buymed_vn",
    assertions: {
         uniqueKey: 'mg_id'
     },
    bigquery: {
        partitionBy: "created_date"
    },
    description: `PIC: MinhLuu, Internal: https://internal.thuocsi.vn/crm/customer/realtime?status=FAILED
    To be like on the Tnternal page:
        SELECT 
            m.customer_id,
            m.customer_name, 
            m.phone,
            m.address,
            m.created_time,
            m.result_error,
            m.ua_metadata
            -- Except note content, I has not find which way to map
        FROM ${source.platinum}.monitoring_prd_realtime_user_failed_login_v8 m
    `,
    tags: ["custom_2h_past5"]
}

pre_operations {
  ${
    when(incremental(),
      `
      --
      DECLARE checkpoint_date ARRAY<date>;

      SET checkpoint_date = ARRAY( 
        SELECT DISTINCT date(created_time,'+7')
        FROM silver_buymed_vn.monitoring_prd_realtime_user_failed_login_v8 
        WHERE ingest_time >= TIMESTAMP(DATE_TRUNC(CURRENT_DATETIME() - interval 6 DAY,DAY))
        AND created_time IS NOT NULL
      );

      DELETE FROM platinum_buymed_vn.monitoring_prd_realtime_user_failed_login_v8
      where created_date in UNNEST(checkpoint_date)
      and mg_id in ( 
        SELECT DISTINCT mg_id 
        FROM silver_buymed_vn.monitoring_prd_realtime_user_failed_login_v8 
        WHERE ingest_time >= TIMESTAMP(DATE_TRUNC(CURRENT_DATETIME() - interval 6 DAY,DAY) )
        );

      `,
      ``
    )
  }
}
--
SELECT 
  *, 
FROM (
  SELECT
    *,
    CASE 
      WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
      ELSE "2099-01-01"
    END AS created_date

  FROM
    ${source.silver}.monitoring_prd_realtime_user_failed_login_v8 o 
    ${ when(incremental(),  `WHERE ingest_time > TIMESTAMP(DATE_TRUNC(CURRENT_DATETIME() - interval 6 DAY,DAY) )`  )}
  QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER (_window) <> 'd'
  WINDOW _window AS ( 
    PARTITION BY mg_id
    ORDER BY 
      synced_at DESC,
      IF (action='d',3, IF (action='u',2,1)) DESC,
      last_updated_time DESC)
)
-- all record deleted include action "d"
-- Special case for order -- PIC: AnhLe