config {
    type: "view",
    name: "platform_monitoring_prd_collector_shield_device_activity",
    schema: "platinum_buymed_vn",
    tags:["platform_monitoring_prd_collector"]
}

SELECT *, 
  CASE 
    WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
    ELSE "2099-01-01"
  END AS created_date
FROM ${source.silver}.platform_monitoring_prd_collector_shield_device_activity o 
  
  QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'
  WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
      last_updated_time DESC
  )