config {
    type: "table", 
    description: 
        `
        The display price of SKUs (calculated according to the pricing formula) for GOLD-level customers in 3 cities HCM, HN, DN;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.ref}.dim_sku_sales_region_current,
            ${source.platinum}.marketplace_prd_pricing_v2_setting,
            ${source.platinum}.marketplace_prd_pricing_v2_price_level, 
            ${source.platinum}.marketplace_prd_pricing_v2_dynamic_level
        `,
    tags: ["custom_1h_past5", "PRICING"],
    columns: {
      customer_level_fee_value: "Fee value corresponding to PLATINUM/GOLD level",
      dynamic_pricing_level_fee_value: "Fee value corresponding to dynamic pricing level", 
      pricing_price_level_fee_value: "Fee value corresponding to price range", 
      delivery_region_fee_value: "Fee value corresponding to delivery region",
      platform_fee: "Formula: SETTING_PRICE * 0.02 * CUSTOMER_LEVEL * DYNAMIC_LEVEL * PRICE_RANGE * PRICING_STRATEGY ",
      delivery_fee: "Formula: SETTING_PRICE * 0.01 * DELIVERY_REGION * DYNAMIC_LEVEL * PRICE_RANGE",
      service_fee: "Total fees added to the setting price",
      display_price: "Price of SKUs on thuocsi.vn after added service fees"
    },

    assertions: {
      uniqueKey: ["sku_key_sales_region_code"],
      nonNull: ["sku_code", "sku_key", "sales_region_code"]
    }
}

-- Get current_time
with
--     cte_date as (
--       SELECT TIMESTAMP_SUB(TIMESTAMP_TRUNC(current_timestamp(),day), interval 7 HOUR) as trunc_timestamp
--     )

-- Get customer level fee. Using LEVEL_GOLD to apply all calculate pricing.
    get_customer_level_fee as (
        select
            code as customer_level,
            fee_value
        from ${source.platinum}.marketplace_prd_pricing_v2_setting
        where
            type = 'CUSTOMER_LEVEL'
            and upper(code) = 'LEVEL_GOLD' -- LEVEL_PLATINUM LEVEL_SILVER
        QUALIFY ROW_NUMBER() OVER (PARTITION BY type, code ORDER BY ingest_time DESC) = 1
    )

-- Get delivery fee. Depending on sale_region_code to get this fee. If MIENBAC then get fee following Ha Noi city, MIENTRUNG - Da Nang City and MIENNAM - HCM 
    , get_delivery_fee as (
        select
            b.district_name as district_level,
            a.fee_value,
            case
                when b.district_code = "019" then "MIENBAC"
                when b.district_code = "760" then "MIENNAM"
                when b.district_code = "495" then "MIENTRUNG"
            end as sales_region_code
        from ${source.platinum}.marketplace_prd_pricing_v2_setting as a
            left join ${ref('dim_district')} as b on a.code = b.district_code
        where
            a.type = 'DELIVERY_REGION'
            and b.district_code IN ("019","760","495")
        QUALIFY
            ROW_NUMBER() OVER (PARTITION BY a.type, a.code ORDER BY a.ingest_time DESC) = 1
    )

-- Get price range. In this code section, appending a row with all null values. This row applies for sku that have price over 100.000.000 because
-- table price_level doesn't have row fee_value for price range over 100.000.000. I use this solution because I use cross join in below section code
    , get_price_range_fee as (
        select from_price, to_price ,fee_value, false as flag
        from ${source.platinum}.marketplace_prd_pricing_v2_price_level
        QUALIFY ROW_NUMBER() OVER (PARTITION BY code ORDER BY ingest_time desc) = 1
        UNION ALL
        SELECT
          *
        FROM
            UNNEST([
              (null, null, null, true)
              ])
    )

-- get columns that to show in report and calculate 2 fee type.
-- Note: I use cross join because deserting apply fees to all sku.
    , get_columns as (
        select 
            TIMESTAMP_ADD(current_timestamp(), INTERVAL 7 HOUR) AS transformed_at,
            a.mg_id,
            a.sku_last_updated_at,
            a.product_id,
            a.sku_code,
            a.product_name,
            a.sales_region_code,
            a.seller_code,
            a.seller_class,
            a.fv_code,
            a.cic_name,
            a.purchase_price,
            a.purchase_price * (1 + a.vat/100) as purchase_price_after_VAT, -- [.Purchase_Price]*(1+[.VAT]/100)
            a.retail_price_value,
            a.retail_price_type,
            a.dynamic_pricing_level,
            d.customer_level,
            d.fee_value as customer_level_fee_value,
            a.pricing_strategy,
            b.fee_value as dynamic_pricing_level_fee_value,
            c.fee_value as pricing_price_level_fee_value,
            e.fee_value as delivery_region_fee_value,

            -- platform fee
            if (
                a.retail_price_value > 0,
                a.retail_price_value * 0.02 * d.fee_value                                          -- Customer Level
                    * IF( p.is_combo AND a.seller_class = "EXTERNAL", 1, COALESCE(b.fee_value,1))  -- Dynamic Level
                    * c.fee_value                                                                  -- Price Range
                    * COALESCE(NULLIF(a.pricing_strategy, 0),1),                           -- Pricing Strategy
                null
            ) as platform_fee,

            -- delivery fee, If fee_value corresponding to dynamic_pricing_level of SKU greater than 4, we assign fee_value = 4 to calculate delivery fee
            if (
                a.retail_price_value > 0,
                a.retail_price_value * 0.01 * e.fee_value                                               -- Delivery Level
                * IF( p.is_combo AND a.seller_class = "EXTERNAL", 1, LEAST(COALESCE(b.fee_value,1),4))  -- Dynamic Level 
                * c.fee_value,                                                                          -- Price Range
                null
            ) as logistic_fee,

            a.fee_code,
            a.sku_key_sales_region_code,
            a.sku_key,
            a.sub_sku_code,
            a.use_skus_price

        from ${ref('dim_sku_sales_region_current')} AS a
            left join ${ref('dim_product')} AS p ON a.product_id = p.product_id
            left join (
                select *
                from  ${source.platinum}.marketplace_prd_pricing_v2_dynamic_level
                QUALIFY ROW_NUMBER() OVER (PARTITION BY level ORDER BY ingest_time desc) = 1
            ) AS b on a.dynamic_pricing_level = b.level 
            cross join get_price_range_fee AS c
            cross join get_customer_level_fee AS d
            left join get_delivery_fee AS e on a.sales_region_code = e.sales_region_code
        where 
            ((a.retail_price_value >= coalesce(c.from_price,0) and a.retail_price_value <= c.to_price)
            or ((a.retail_price_value is null or a.retail_price_value > 100000000) and c.flag = true))
    ),

    normal_product AS (
        select
            * EXCEPT (mg_id),

            CASE
                when retail_price_value is null or retail_price_value > 100000000 or dynamic_pricing_level_fee_value is null then 0
                when retail_price_type = "FIXED_PRICE" and retail_price_value > 1 then 0
                when retail_price_type = "CUSTOM_FEE" and retail_price_value > 1 then
                    CASE
                        WHEN fee_code = '1BRTE9AQ1PG' THEN platform_fee
                        WHEN fee_code = '3WQD9UBW961' THEN logistic_fee
                        ELSE platform_fee + logistic_fee
                    END
                when retail_price_value > 1 then platform_fee + logistic_fee
            end as service_fee,

            ROUND(
                CASE
                    when retail_price_value is null or retail_price_value > 100000000 or dynamic_pricing_level_fee_value is null then retail_price_value
                    when retail_price_type = "FIXED_PRICE" and retail_price_value > 1 then retail_price_value
                    when retail_price_type = "CUSTOM_FEE" and retail_price_value > 1 then
                        CASE
                            WHEN fee_code = '1BRTE9AQ1PG' THEN retail_price_value + platform_fee
                            WHEN fee_code = '3WQD9UBW961' THEN retail_price_value + logistic_fee
                            ELSE retail_price_value + platform_fee + logistic_fee
                        END
                    when retail_price_value > 1 then retail_price_value + platform_fee + logistic_fee
                end,
                -2
            ) as display_price
        from get_columns
        WHERE
            use_skus_price IS NULL
            OR use_skus_price = FALSE
            OR seller_class = "EXTERNAL"
    ),

    combo_product AS (
        SELECT
            * EXCEPT (mg_id, sku_original_code, item_code, display_price, quantity)
            , NULL AS service_fee
            , SUM(display_price * quantity) AS display_price
        FROM (
            SELECT
                a.*
                , s.sku AS sku_original_code
                , JSON_VALUE(ss, '$.item_code') AS item_code
                , SAFE_CAST(JSON_VALUE(ss, '$.quantity') AS INT64) AS quantity
                , n.display_price
            FROM get_columns AS a
                LEFT JOIN ${source.platinum}.marketplace_prd_product_v2_sku AS s ON a.mg_id = s.mg_id
                , UNNEST(JSON_QUERY_ARRAY(s.skus)) AS ss
                LEFT JOIN normal_product AS n ON JSON_VALUE(ss, '$.item_code') = n.sub_sku_code
            WHERE a.use_skus_price = true AND a.seller_class <> "EXTERNAL"
        )
        GROUP BY ALL
    )

SELECT *
FROM normal_product
UNION ALL
SELECT *
FROM combo_product  
