config {
    type: "table", 
    description: 
        `
        All types of SKU prices including display price (calculated according to the pricing formula for GOLD-level customer in HCM, HN, DN corresponding to 3 sales regions ), deal price, campaign price, setting price, purchase price, price after rebate and the net price received of external seller;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.ref}.adhoc_pricing_display_price,
            ${source.ref}.adhoc_pricing_promotion_price,
            ${source.ref}.adhoc_pricing_seller_price,
            ${source.ref}.adhoc_pricing_price_after_rebate
        `,
    tags: ["custom_1h_past5", "PRICING"],

    columns: {
        purchase_price: "The unit price in the latest PO (purchase order)",
        purchase_price_after_VAT: "The unit price after VAT in the latest PO (purchase order)",
        retail_price_value: 'The setting price of SKUs',
        rebate_price: 'Price after rebate',
        rebate_price_with_adhoc_promotion: 'Price after rebate with adhoc promotion',
        display_price: 'The price is calculated using the pricing formula from the setting price',
        campaign_price: 'The price in the latest active campaign.',
        deal_price: 'The price in the latest active deal',
        display_price_seller_without_promo: "The price of the external SKUs is calculated using the pricing formula from the setting price.",
        display_price_seller_with_promo: "Campaign Price or Deal Price of external SKUs",
        seller_received_with_promo: "The amount that the seller will receive for a SKUs in promotion (Estimated)",
        seller_received_without_promo: "The amount that the seller will receive based on the setting price (without promotion)",
        sku_display_price: 'The actual display price of SKUs on the thuocsi.vn platform'
  }
}

WITH
    cte AS (
        SELECT 
            a.transformed_at,
            a.sku_last_updated_at,
            d.rebate_date_get_at,
            a.product_id,
            a.sku_code,
            a.seller_class,
            a.product_name,
            a.sales_region_code,
            a.sku_key_sales_region_code,
            a.sku_key,
            a.cic_name, 
            a.retail_price_value,
            a.purchase_price,
            a.purchase_price_after_VAT,
            d.price_after_rebate AS rebate_price,
            d.price_after_rebate_with_adhoc_promotion AS rebate_price_with_adhoc_promotion,
            b.cost_price_of_deal AS deal_cost,
            d.price_contract,
            a.display_price,
            b.campaign_price,
            COALESCE(b.campaign_type, b.deal_type) AS promotion_type,
            b.deal_price,
            c.display_price_seller_with_promo,
            c.display_price_seller_without_promo,
            c.seller_received_with_promo,
            c.seller_received_without_promo,
            -- IF(
            --     seller_class = 'INTERNAL',
            --     COALESCE( b.campaign_price, b.deal_price, a.display_price),
            --     COALESCE(c.display_price_seller_with_promo, c.display_price_seller_without_promo)
            -- ) AS sku_display_price
            -- COALESCE( b.campaign_price, b.deal_price, a.display_price) AS sku_display_price
            -- LEAST( 
            --     IFNULL(b.campaign_price, a.display_price)
            --     ,IFNULL(b.deal_price, a.display_price)
            --     , a.display_price
            -- ) AS sku_display_price
            COALESCE(
                b.campaign_price,
                LEAST( COALESCE(b.deal_price, a.display_price), a.display_price),
                a.display_price
            ) AS sku_display_price,
            CASE
                WHEN b.campaign_price IS NOT NULL THEN "CAMPAIGN"
                WHEN b.deal_price IS NOT NULL AND b.deal_price < a.display_price THEN "DEAL"
                ELSE "DISPLAY"
            END AS sku_display_price_type
        FROM ${ref('adhoc_pricing_display_price')} AS a
            LEFT JOIN ${ref('adhoc_pricing_promotion_price')} AS b 
                ON a.sku_code = b.sku_code AND a.sales_region_code = b.sales_region_code
            LEFT JOIN ${ref('adhoc_pricing_seller_price')} AS c 
                ON a.sku_code = c.sku_code AND a.sales_region_code = c.sales_region_code
            LEFT JOIN ${ref('adhoc_pricing_price_after_rebate')} AS d 
                ON a.sku_code = d.sku_code AND a.sales_region_code = d.sales_region_code
)

SELECT
    *
    , CASE
        WHEN sku_display_price_type IN ("CAMPAIGN", "DEAL") THEN COALESCE(deal_cost, rebate_price_with_adhoc_promotion)
        ELSE rebate_price_with_adhoc_promotion
    END AS final_rebate
FROM cte