config {
    type: "table", 
    description: 
        `
        Display price of the External SKUs, Net price received by the Seller after deducting taxes and fees;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.ref}.dim_sku_sales_region_current,
            ${source.ref}.dim_supplier, 
            ${source.ref}.dim_product, 
            ${source.ref}.adhoc_pricing_display_price,
            ${source.ref}.adhoc_pricing_promotion_price,
            ${source.platinum}.marketplace_prd_product_v2_product_fee_config
        `,
    tags: ["gold_custom_20m", "PRICING"],
}

-- step 1: get some fee to calculate seller_received_value
with

    seller_fee_config as (
        SELECT
            *
            , IFNULL(SAFE.PARSE_TIMESTAMP("%F %T", from_time_index), created_time) AS index
        FROM ${source.platinum}.marketplace_prd_product_v2_product_fee_config
        QUALIFY ROW_NUMBER() over (PARTITION BY product_id, location_code ORDER BY index DESC) = 1
    ),

    combo AS (
        SELECT
            a.sku AS combo_sku_code
            , s.sales_region_code
--             , a.retail_price_value AS combo_retail_price_value
            , JSON_VALUE(ss, '$.item_code') AS sub_item_code
            , SAFE_CAST(JSON_VALUE(ss, '$.quantity') AS INT64) AS quantity
            , n.product_id AS sub_product_id
            , n.retail_price_value AS sub_retail_price_value
            , sf.fulfillment_fee_percent
            , sf.sale_fee_percent
            , SUM(n.retail_price_value * SAFE_CAST(JSON_VALUE(ss, '$.quantity') AS INT64)) OVER(PARTITION BY a.sku, s.sales_region_code) AS combo_retail_price_value
        FROM ${ref('dim_sku_sales_region_current')} AS s
            LEFT JOIN ${source.platinum}.marketplace_prd_product_v2_sku AS a ON a.mg_id = s.mg_id
            , UNNEST(JSON_QUERY_ARRAY(a.skus)) AS ss
            LEFT JOIN ${ref('dim_sku_sales_region_current')} AS n ON JSON_VALUE(ss, '$.item_code') = n.sub_sku_code
            LEFT JOIN seller_fee_config AS sf ON sf.product_id = n.product_id AND sf.location_code = s.sales_region_code
        WHERE a.seller_class = "EXTERNAL"
    )

-- step 2: get necessary columns to calculate price for seller
    , get_columns as (
        select
            a.sku_code,
            a.product_id,
            a.sales_region_code,
            c.seller_code,
            sel.supplier_type,
            a.platform_fee,
            a.logistic_fee,
            a.service_fee,
            a.retail_price_type,
            a.retail_price_value,
            b.deal_code,
            b.deal_type,
            b.charge_deal_fee,
            b.charge_fee,
            b.campaign_price,
            b.deal_price,
            a.display_price,
            a.delivery_region_fee_value,
            c.sku_level,
            e.product_category_code,
            COALESCE(f.fulfillment_fee_percent, g.combo_fulfillment_fee_percent) AS fullfilment_fee_seller,
            COALESCE(f.sale_fee_percent, g.combo_sale_fee_percent) AS sale_fee_percent,
            IF(COALESCE(campaign_price, deal_price) > display_price, NULL, COALESCE(campaign_price, deal_price)) as promotion_price,
            a.sku_key_sales_region_code,
            a.sku_key
        from ${ref('adhoc_pricing_display_price')} AS a
            left join ${ref('adhoc_pricing_promotion_price')} AS b
                on a.sku_code = b.sku_code and a.sales_region_code = b.sales_region_code
            left join ${ref('dim_sku_sales_region_current')} AS c
                on a.sku_code = c.sku_code and a.sales_region_code = c.sales_region_code
            left join ${ref('dim_supplier')} AS sel
                on c.seller_code = sel.supplier_code
            left join ${ref('dim_product')} AS e
                on c.product_id = e.product_id
            -- left join cte_category_seller_level AS f
            --     on concat(e.product_category_code,"_",IF(sel.supplier_type = "MARKET", "MARKET", c.sku_level)) = f.cate_level_code
            left join seller_fee_config AS f
                on f.product_id = c.product_id and f.location_code = c.sales_region_code
            left join (
                SELECT
                    combo_sku_code
                    , sales_region_code
                    , SUM(SAFE_DIVIDE(sub_retail_price_value * quantity * fulfillment_fee_percent, combo_retail_price_value)) AS combo_fulfillment_fee_percent
                    , SUM(SAFE_DIVIDE(sub_retail_price_value * quantity * sale_fee_percent, combo_retail_price_value)) AS combo_sale_fee_percent
                FROM combo
                GROUP BY ALL
            ) AS g ON g.combo_sku_code = a.sku_code AND g.sales_region_code = a.sales_region_code
        where sel.supplier_class = "EXTERNAL"
    )

-- step 3: calculate price by BU's logic
select
    *,
    -- calculate seller_fee (percentage)
    if(
        supplier_type in ("MARKET", "BIZ_HOUSEHOLD"),
        fullfilment_fee_seller + sale_fee_percent + 1.5,
        fullfilment_fee_seller + sale_fee_percent
    ) as seller_fee_tax,

    if(
        supplier_type in ("MARKET", "BIZ_HOUSEHOLD"),
        1.5,
        null
    ) as seller_tax,

    fullfilment_fee_seller + sale_fee_percent as seller_fee,

    -- calculate price_seller_original
    if(
        promotion_price is not null,
        promotion_price - service_fee,
        if (retail_price_value > 1, retail_price_value, null)
    ) as price_seller_original,

    display_price as display_price_seller_without_promo,
    promotion_price AS display_price_seller_with_promo,

    -- calculate seller received without promotion = retail_price_value * (1 - seller_fee)
    if (
        retail_price_value > 1,
        if(
            supplier_type in ("MARKET", "BIZ_HOUSEHOLD"),
            retail_price_value * (1 - (fullfilment_fee_seller + sale_fee_percent + 1.5 + 1) / 100),
            retail_price_value * (1 - (fullfilment_fee_seller + sale_fee_percent + 1) / 100)
        ),
        null
    ) as seller_received_without_promo,

    if (
        retail_price_value > 1,
        if(
            supplier_type in ("MARKET", "BIZ_HOUSEHOLD"),
            retail_price_value * 1.5 / 100,
            null
        ),
        null
    ) as tax_without_promo,

    if (
        retail_price_value > 1,
        retail_price_value * (fullfilment_fee_seller + sale_fee_percent + 1) / 100,
        null
    ) as fee_without_promo,

    -- calculate seller received with promotion
    -- Nếu bên chịu phí (tức field charge_deal_fee) là thuocsi.vn (tức value = "MARKETPLACE") thì lấy giá retail_price_value * (1 - seller_fee)
    -- Nếu bên chịu phí là seller (tức value <> "MARKETPLACE") thì lấy giá promotion * (1 - seller_fee)
    if (
        promotion_price is not null ,
        case
            when COALESCE(charge_fee, charge_deal_fee) = 'MARKETPLACE' and supplier_type in ("MARKET", "BIZ_HOUSEHOLD")
                then retail_price_value * (1 - (fullfilment_fee_seller + sale_fee_percent + 1.5 + 1) / 100)
            when COALESCE(charge_fee, charge_deal_fee) = 'MARKETPLACE' and supplier_type not in ("MARKET", "BIZ_HOUSEHOLD")
                then retail_price_value * (1 - (fullfilment_fee_seller + sale_fee_percent + 1) / 100)
            when COALESCE(charge_fee, charge_deal_fee) != 'MARKETPLACE' and supplier_type in ("MARKET", "BIZ_HOUSEHOLD")
                then ( promotion_price - service_fee ) * (1 - (fullfilment_fee_seller + sale_fee_percent + 1.5 + 1) / 100)
            when COALESCE(charge_fee, charge_deal_fee) != 'MARKETPLACE' and supplier_type not in ("MARKET", "BIZ_HOUSEHOLD")
                then ( promotion_price - service_fee ) * (1 - (fullfilment_fee_seller + sale_fee_percent + 1) / 100)
        end,
        null
    ) as seller_received_with_promo,

    if (
        promotion_price is not null ,
        case
            when COALESCE(charge_fee, charge_deal_fee) = 'MARKETPLACE' and supplier_type in ("MARKET", "BIZ_HOUSEHOLD")
                then retail_price_value *  1.5 / 100
            when COALESCE(charge_fee, charge_deal_fee) != 'MARKETPLACE' and supplier_type in ("MARKET", "BIZ_HOUSEHOLD")
                then ( promotion_price - service_fee) *  1.5 / 100
        end,
        null
    ) as tax_with_promo,

    if (
        promotion_price is not null ,
        case
            when COALESCE(charge_fee, charge_deal_fee) = 'MARKETPLACE'
                then retail_price_value *  (fullfilment_fee_seller + sale_fee_percent + 1) / 100
            when COALESCE(charge_fee, charge_deal_fee) != 'MARKETPLACE'
                then ( promotion_price - service_fee) *  (fullfilment_fee_seller + sale_fee_percent+ 1) / 100
        end,
        null
    ) as fee_with_promo
from get_columns