config {
    type: "table", 
    description: 
        `
        Price After Rebate of MEDX SKUs on current date (the price after rebate from the favourite vendor, or the highest price among other vendors if the favourite vendor's price is not available);
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.ref}.dim_sku_sales_region_current,
            ${source.ref}.dim_vendor,
            ${source.platinum}.seller_prd_purchasing_contract_price,
            ${source.platinum}.seller_prd_promotion_log_price_after_rebate
        `,
    tags: ["custom_1h_past10", "PRICING"],

    assertions: {
      uniqueKey: ["product_sales_region_code", "sku_key_sales_region_code"],
      nonNull: ["sku_code", "sales_region_code"]
    }
}


SELECT 
    rebate_date AS rebate_date_get_at,
    last_updated_at,
    ingest_at,
    product_id,
    sku_code,
    sales_region_code,
    vendor_code,
    price_after_rebate,
    price_after_rebate_with_adhoc_promotion,
    price_contract,
    price_expected_on_bill,
    rebate,
    contract_price_id,
    product_sales_region_code,
    sku_key_sales_region_code,
    rebate_reserve
FROM ${ref('fact_price_after_rebate_fv_vendor')}
WHERE rebate_date >= DATE_SUB(CURRENT_DATE("+7"), INTERVAL 2 DAY)
QUALIFY ROW_NUMBER() OVER(PARTITION BY sku_code, sales_region_code ORDER BY last_updated_at DESC) = 1
