config {
    type: "incremental",
    name: "accounting_prd_core_bill_historical_cut_off",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id || date_index'
    },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["platinum_som_cutoff"]
}

js {
    /*
        Trigger time : 2h10am at start of month with vietnam timezone
        It means current_timestamp will be 19h00 at end of previous month with UTC timezone
    */
    const start_of_VN_month_timestamp_in_UTC = `TIMESTAMP_TRUNC(CURRENT_TIMESTAMP() , DAY) + INTERVAL 17 HOUR -- Mean: 05-31T17:00:00` 
    const end_of_VN_month_day = `TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY)`
}

SELECT 
    *, 
    CASE 
        WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
        ELSE "2099-01-01"
    END AS created_date,
    FORMAT_TIMESTAMP('%y%m%d', ${end_of_VN_month_day} )   as date_index 

    -- "250228" as date_index 
    -- the date_index alway is the end of month, because we run in 0h15m the som in UTC +7, but timestamp return UTC timezone meaning 0h15m -7 Hour so finaly it return last day in our timezone perspective
FROM ${source.silver}.accounting_prd_core_bill 
-- WHERE last_updated_time < TIMESTAMP("2025-03-01") - INTERVAL 7 HOUR
WHERE synced_at < ${start_of_VN_month_timestamp_in_UTC}
OR (
    created_time < ${start_of_VN_month_timestamp_in_UTC}
AND (
    last_updated_time < ${start_of_VN_month_timestamp_in_UTC}
    OR last_updated_time is null
))
QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW _window AS ( 
    PARTITION BY   mg_id 
    ORDER BY 
        synced_at DESC, 
        IF (action='d',3,IF (action='u',2,1)) DESC,
        last_updated_time DESC
    )

