config {
    type: "table", 
    description: 
        `
        All possible prices of SKUs;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.silver}.marketplace_prd_product_v2_product_market_price
        `,
    tags: ["custom_1h_past5", "PRICING"]
}

WITH 
  price_full AS (
      select 
        a.product_id,
        a.sku_code,
        a.sales_region_code,
        a.prices,
        SPLIT(a.prices, '_&_')[OFFSET(0)] AS customer_level,
        SPLIT(a.prices, '_&_')[OFFSET(1)] AS delivery_fee,
        b.campaign_price,
        b.deal_price,
        a.display_price,
        COALESCE(
            b.campaign_price,
            LEAST( b.deal_price, a.display_price ),
            a.display_price
        ) AS sku_display_price,
        a.sku_key_sales_region_code

    from ${ref('adhoc_pricing_display_price_full')} a
    left join ${ref('adhoc_pricing_promotion_price_full')} b 
      on a.sku_code = b.sku_code 
      and a.sales_region_code = b.sales_region_code
      AND a.prices = b.prices
    left join ${ref('adhoc_pricing_seller_price_full')} c 
      on a.sku_code = c.sku_code 
      and a.sales_region_code = c.sales_region_code
      AND a.prices = c.prices
)

SELECT
  *
FROM price_full