config {
    type: "table", 
    description: 
        `
        All display prices of SKUs for 3 customer levels (SILVER, GOLD, DIAMOND) & 4 delivery fee coefficients;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.ref}.dim_sku_sales_region_current,
            ${source.platinum}.marketplace_prd_pricing_v2_setting,
            ${source.platinum}.marketplace_prd_pricing_v2_price_level, 
            ${source.platinum}.marketplace_prd_pricing_v2_dynamic_level
        `,
    tags: ["custom_1h_past5", "PRICING"]
}

with

-- Get customer level fee.
    get_customer_level_fee as (
        select
            code as customer_level,
            fee_value
        from ${source.platinum}.marketplace_prd_pricing_v2_setting
        where
            type = 'CUSTOMER_LEVEL'
            and upper(code) IN ('LEVEL_GOLD', 'LEVEL_SILVER', 'LEVEL_DIAMOND') 
        QUALIFY ROW_NUMBER() OVER (PARTITION BY type, code ORDER BY ingest_time DESC) = 1
    )

-- Get delivery fee. 
    , get_delivery_fee as (
        SELECT DISTINCT
            b.sales_region_code
            , a.fee_value
            , DENSE_RANK() over (ORDER BY a.fee_value) as delivery_level
        FROM (
            SELECT
                code as province_code
                , fee_value
            FROM ${source.platinum}.marketplace_prd_pricing_v2_setting
            WHERE
                type = 'DELIVERY_REGION' OR type is null
            QUALIFY ROW_NUMBER() over (_window) = 1 AND FIRST_VALUE(action) over (_window) <> 'd'
            WINDOW _window AS (PARTITION BY type, code ORDER BY synced_at DESC, last_updated_time DESC)
        ) as a
            LEFT JOIN ${ref('dim_fc_service_area')} as b 
                ON a.province_code = b.service_area_code
        WHERE
            b.sales_region_code is not null
    )

-- Get price range. In this code section, appending a row with all null values. This row applies for sku that have price over 100.000.000 because
-- table price_level doesn't have row fee_value for price range over 100.000.000. I use this solution because I use cross join in below section code
    , get_price_range_fee as (
        select from_price, to_price ,fee_value, false as flag
        from ${source.platinum}.marketplace_prd_pricing_v2_price_level
        QUALIFY ROW_NUMBER() OVER (PARTITION BY code ORDER BY ingest_time desc) = 1
        UNION ALL
        SELECT
          *
        FROM
            UNNEST([
              (null, null, null, true)
              ])
    )

-- get columns that to show in report and calculate 2 fee type.
-- Note: I use cross join because deserting apply fees to all sku.
    , get_columns as (
        select 
            a.product_id,
            a.sku_code,
            a.sales_region_code,
            a.seller_class,
            CONCAT(d.customer_level, "_&_Delivery_Fee_", e.delivery_level) AS prices,

            a.retail_price_type,
            a.retail_price_value,
            b.fee_value as dynamic_pricing_level_fee_value,

            -- platform fee
            if (
                a.retail_price_value > 0,
                a.retail_price_value * 0.02 * d.fee_value * COALESCE(b.fee_value,1)  * c.fee_value *
                    IF(a.pricing_strategy = 0, 1, a.pricing_strategy),
                null
            ) as platform_fee,

            -- delivery fee, If fee_value corresponding to dynamic_pricing_level of SKU greater than 4, we assign fee_value = 4 to calculate delivery fee
            if (
                a.retail_price_value > 0,
                a.retail_price_value * 0.01 * e.fee_value * LEAST(COALESCE(b.fee_value,1),4) * c.fee_value,
                null
            ) as logistic_fee,

            a.fee_code,
            a.sku_key_sales_region_code,
            a.sku_key

        from ${ref('dim_sku_sales_region_current')} AS a
            left join (
                select *
                from  ${source.platinum}.marketplace_prd_pricing_v2_dynamic_level
                QUALIFY ROW_NUMBER() OVER (PARTITION BY level ORDER BY ingest_time desc) = 1
            ) AS b on a.dynamic_pricing_level = b.level
            cross join get_price_range_fee AS c
            cross join get_customer_level_fee AS d
            left join get_delivery_fee AS e on a.sales_region_code = e.sales_region_code
        where 
            (a.retail_price_value >= coalesce(c.from_price,0) and a.retail_price_value <= c.to_price)
            or ((a.retail_price_value is null or a.retail_price_value > 100000000) and c.flag = true)
    )

  -- calculate display price 
select 
    *,

    CASE
        when retail_price_value is null or retail_price_value > 100000000 or dynamic_pricing_level_fee_value is null then 0
        when retail_price_type = "FIXED_PRICE" and retail_price_value > 1 then 0
        when retail_price_type = "CUSTOM_FEE" and retail_price_value > 1 then
            CASE
                WHEN fee_code = '1BRTE9AQ1PG' THEN platform_fee
                WHEN fee_code = '3WQD9UBW961' THEN logistic_fee
                ELSE platform_fee + logistic_fee
            END
        when retail_price_value > 1 then platform_fee + logistic_fee
    end as service_fee,
    
    ROUND( 
        CASE
            when retail_price_value is null or retail_price_value > 100000000 or dynamic_pricing_level_fee_value is null then retail_price_value
            when retail_price_type = "FIXED_PRICE" and retail_price_value > 1 then retail_price_value
            when retail_price_type = "CUSTOM_FEE" and retail_price_value > 1 then
                CASE
                    WHEN fee_code = '1BRTE9AQ1PG' THEN retail_price_value + platform_fee
                    WHEN fee_code = '3WQD9UBW961' THEN retail_price_value + logistic_fee
                    ELSE retail_price_value + platform_fee + logistic_fee
                END
            when retail_price_value > 1 then retail_price_value + platform_fee + logistic_fee
        end, 
        -2
    ) as display_price
from get_columns