config {
    type: "table", 
    description: 
        `
        All Price after discount of SKUs;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        `,
    tags: ["custom_1h_past10", "PRICING"]
}

WITH
    area AS (
        SELECT
            voucher_code
            ,CASE
                WHEN b LIKE "%MIENBAC%" THEN "MIENBAC"
                WHEN b LIKE "%MIENNAM%" THEN "MIENNAM"
                WHEN b = "00" THEN "00"
                WHEN b IS NULL THEN "00"
                ELSE c.sales_region_code
            END
            AS area_code
        FROM ${ref("dim_voucher")}
            , UNNEST(JSON_QUERY_ARRAY(scopes)) AS a
            LEFT JOIN UNNEST(JSON_VALUE_ARRAY(a, "$.area_codes")) AS b
            LEFT JOIN ${ref("dim_fc_service_area")} AS c ON c.service_area_code = b
        WHERE JSON_VALUE(a, '$.type') = "AREA"
    ),

    voucher AS (
        SELECT
            a.product_id
            , a.seller_code
            , a.voucher_code
            , b.voucher_discount
            , b.percentage_discount
            , a.min_sku_quantity
            , SAFE_DIVIDE(b.voucher_discount, a.min_sku_quantity) AS avg_discount
            , IFNULL(mov,0) AS mov1
            , discount_type
            , c.area_code
            , b.charge_fee
            , b.max_discount
            , b.display_name
        FROM ${ref("dim_voucher_product")} AS a
            LEFT JOIN ${ref("dim_voucher")} AS b USING(voucher_code)
            LEFT JOIN area AS c USING(voucher_code)
        WHERE
            b.voucher_status = "ACTIVE"
            AND b.is_specific
            AND b.all_customer
            AND c.area_code IS NOT NULL
        QUALIFY ROW_NUMBER() over (PARTITION BY product_id, a.seller_code, area_code ORDER BY mov1, a.min_sku_quantity, voucher_discount DESC, max_discount DESC ) = 1
    ),

    final_price AS (
        SELECT
            a.*
            , b.campaign_price
            , b.deal_price
            , ROUND(
                COALESCE(
                    b.campaign_price,
                    LEAST( b.deal_price, a.display_price ),
                    a.display_price
                ),
                -2
            )
                AS sku_final_price
        FROM ${ref("adhoc_pricing_display_price_full")} AS a
            LEFT JOIN ${ref("adhoc_pricing_promotion_price_full")} AS b
                ON a.sku_code = b.sku_code AND a.sales_region_code = b.sales_region_code AND a.prices = b.prices
    )

SELECT
    a.product_id
    , a.sku_code
    , a.sku_key
    , a.sku_key_sales_region_code
    , a.sales_region_code
    , a.display_price
    , a.campaign_price
    , a.deal_price
    , sku_final_price
    , charge_fee
    , IFNULL(
        IF(
            discount_type = "ABSOLUTE",
            c.avg_discount,
            a.sku_final_price * SAFE_CAST(c.percentage_discount AS FLOAT64) / 100
        )
        , 0
     ) AS product_voucher_discount
    , ROUND(
        a.sku_final_price * 0.995 - ROUND(a.sku_final_price * 0.00256, -2)
            - IFNULL(
                IF(
                    discount_type = "ABSOLUTE",
                    c.avg_discount,
                    a.sku_final_price * SAFE_CAST(c.percentage_discount AS FLOAT64) / 100
                )
              , 0)
        , -2
    ) AS price_after_discount_level1
    , ROUND(
        a.sku_final_price * 0.995 - ROUND(a.sku_final_price * 0.005, -2)
            - IFNULL(
                IF(
                    discount_type = "ABSOLUTE",
                    c.avg_discount,
                    a.sku_final_price * SAFE_CAST(c.percentage_discount AS FLOAT64) / 100
                )
              , 0)
        , -2
    ) AS price_after_discount_level2
    , ROUND(
        a.sku_final_price * 0.995 - ROUND(a.sku_final_price * 0.006, -2)
            - IFNULL(
                IF(
                    discount_type = "ABSOLUTE",
                    c.avg_discount,
                    a.sku_final_price * SAFE_CAST(c.percentage_discount AS FLOAT64) / 100
                )
              , 0)
        , -2
    ) AS price_after_discount_level3
    , c.voucher_code
    , a.prices
    -- , c.area_code
FROM final_price AS a
    LEFT JOIN voucher AS c 
        ON c.product_id = a.product_id AND c.seller_code = a.seller_code
            AND (c.area_code ="00" OR c.area_code = a.sales_region_code)
WHERE 1=1
    AND a.sales_region_code <> "MIENTRUNG"
-- QUALIFY ROW_NUMBER() OVER(PARTITION BY sku_key_sales_region_code) = 1
