config {
    type: "table", 
    description: 
        `
        PIC: huyen.nguyenthu; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.ref}.fact_mission_process_log_v2
        `,
    tags: ["custom_1h_past7"]
}


SELECT
  DISTINCT luckywheel_id
  , lucky_wheel_code
  , customer_id
  , gamification_detail_id
  , status
  , completed_date
  , completed_time
FROM ${ref('fact_mission_process_log_v2')} 

