config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Customers in the Cambodia marketplace.`,
    tags: ['AI_THUOCSI_CAM']
}

SELECT
    customer_id
    , customer_name
    , user_created_date
    , user_activated_date
    , first_order_date
    , user_system_status AS customer_status
    , business_scope
    , customer_level
    , a.last_login_at
    , JSON_VALUE(w.extra_props, "$.name_en") AS customer_ward_name
    , JSON_VALUE(d.extra_props, "$.name_en") AS customer_district_name
    , JSON_VALUE(p.extra_props, "$.name_en") AS customer_province_name
    , p.region_name AS customer_region_name
FROM `lakehouse-prod-394907.gold_buymed_cam.dim_customer` AS a
    LEFT JOIN `platinum_buymed_cam.core_prd_master_data_ward` AS w ON w.code = a.ward_code
    LEFT JOIN `platinum_buymed_cam.core_prd_master_data_district` AS d ON d.code = a.district_code
    LEFT JOIN `platinum_buymed_cam.core_prd_master_data_province` AS p ON p.code = a.province_code