config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Product-SKU in the Cambodia marketplace.`,
    tags: ['AI_THUOCSI_CAM']
}

SELECT
    s.product_id
    , s.product_name
    , s.sku_code
    -- , s.sku_key
    , s.seller_code
    , sl.seller_class
    , sl.name AS seller_name
    , p.product_category AS product_category
    , p.brand
    , p.manufacturer AS manufacturer_name
    , p.origin
    , s.sku_status
    , s.sku_active
FROM `lakehouse-prod-394907.gold_buymed_cam.dim_sku` AS s
    LEFT JOIN `lakehouse-prod-394907.gold_buymed_cam.dim_product` AS p ON s.product_id = p.product_id
    LEFT JOIN lakehouse-prod-394907.platinum_buymed_cam.seller_prd_core_seller AS sl ON sl.code = s.seller_code