config {
    type: 'view',
    schema: "buymed_innovation",
    description: `All orders item in the Cambodia marketplace.`,
    tags: ['AI_THUOCSI_CAM']
}

WITH
    fact_order AS ( 
        SELECT
            a.created_date
            , FORMAT_DATE("%Y-%m", a.created_date ) AS year_month
            , DATE_TRUNC(a.created_date, MONTH) AS som
            , DATETIME(a.created_time, "+7") AS created_time
            , DATETIME(a.delivered_time, "+7") AS delivered_time
            , order_id
            , customer_id
            , price AS gmv
            , status
            , total_discount
            , JSON_VALUE(w.extra_props, "$.name_en") AS shipping_ward_name
            , JSON_VALUE(d.extra_props, "$.name_en") AS shipping_district_name
            , JSON_VALUE(p.extra_props, "$.name_en") AS shipping_province_name
            , p.region_name AS shipping_region_name
            , CASE
                WHEN REGEXP_CONTAINS(TO_JSON_STRING(a.tags), '\"ORDER_ASSIST\"') THEN 'ASSIST_ORDER' 
                ELSE 'SELF_ORDER' 
            END AS assist_order
        FROM platinum_buymed_cam.marketplace_prd_order_v2_order AS a
            LEFT JOIN `platinum_buymed_cam.core_prd_master_data_ward` AS w ON w.code = a.customer_ward_code
            LEFT JOIN `platinum_buymed_cam.core_prd_master_data_district` AS d ON d.code = a.customer_district_code
            LEFT JOIN `platinum_buymed_cam.core_prd_master_data_province` AS p ON p.code = a.customer_province_code
        WHERE 1=1
            -- AND created_date >= "2025-01-01"
            AND status <> "CANCEL"
    ),

    order_item AS (
        SELECT
            a.created_date
            , DATETIME(a.created_time, "+7") AS created_time
            , o.delivered_time
            , a.order_id
            , a.product_id
            , a.sku AS sku_code
            , a.quantity
            , a.total_price
            , a.price * a.outbound_quantity AS total_outbound
            , s.seller_class
            , o.customer_id
            , o.status AS order_status
            , o.shipping_ward_name
            , o.shipping_district_name
            , o.shipping_province_name
            , o.shipping_region_name
            , o.assist_order
            , o.total_discount / COUNT(1) OVER(PARTITION BY a.order_id) AS total_discount
            , IF(a.vat > 0, "TRADING", "NON-TRADING") AS trading_type
        FROM platinum_buymed_cam.marketplace_prd_order_v2_order_item AS a
            LEFT JOIN platinum_buymed_cam.seller_prd_core_seller AS s ON a.seller_code = s.code
            LEFT JOIN fact_order AS o ON a.order_id = o.order_id
        WHERE 1=1
            AND a.created_date >= "2025-01-01"
            AND o.created_date >= "2025-01-01"
            -- AND o.status <> "CANCEL"
    )

    , new_customer AS (
        SELECT
            customer_id
            , MIN_BY(year_month, created_date) AS first_order_year_month
            , MIN_BY(som, created_date) AS first_order_som
            , MIN(created_date) AS first_order_date
            , "NEW" AS customer_active_type
        FROM fact_order
        GROUP BY ALL
    )

    , reapeat_customer AS (
        SELECT
            customer_id
            , year_month
            , som
            , LEAD(som) over (PARTITION BY customer_id ORDER BY som DESC) AS before_som
        FROM fact_order
    )

    , active_customer AS (
        SELECT * , IF(DATE_DIFF(som, before_som, MONTH) = 1, "REPEAT", "REACQUIRED") AS customer_active_type
        FROM reapeat_customer
        WHERE som <> before_som
        UNION ALL
        SELECT * FROM new_customer
    )

SELECT
    oi.*
    , COALESCE(ac.customer_active_type, ac1.customer_active_type) AS customer_active_type
FROM order_item AS oi
    LEFT JOIN active_customer AS ac 
        ON DATE_TRUNC(oi.created_date, MONTH) = ac.som AND oi.customer_id = ac.customer_id AND ac.customer_active_type <> "NEW"
    LEFT JOIN active_customer AS ac1
        ON oi.created_date = ac1.before_som AND oi.customer_id = ac1.customer_id AND ac1.customer_active_type = "NEW"

