config {
    type: "table",
    description: "PIC: dong.le",
    name: "dim_stock_classification",
    tags: ["12h00"],
}

SELECT
    a.sku,
    a.warehouse_code,
    b.ts_latest_put,
    c.ts_latest_pick
FROM ${ref("dedup_warehouse_prd_inventory_sku_merge")} a
LEFT JOIN ${ref("agg_latest_put_by_sku_fc")} b
    ON a.sku = b.sku AND a.warehouse_code = b.warehouse_code
LEFT JOIN ${ref("agg_latest_pick_by_sku_fc")} c
    ON a.sku = c.sku AND a.warehouse_code = c.warehouse_code