config {
    type: "table",
    description: "Source: warehouse_prd_inventory_sku_location_merge | Schedule: every 30 mins from 9am to 6pm | PIC: dong.le",
    name: "fact_stock_sku_item",
    tags: ["custom_30min_9to18"],
    columns: {
      
    }
}

WITH
  dedup_inventory_sku_location AS ${dedup.dedup(
  source.silver + `.warehouse_prd_inventory_sku_location_merge`,
  "sku, warehouse_code, location_code, stock_quantity"
)}

SELECT
  CONCAT(b.sku_key, "_", a.warehouse_code) as sku_fc_key,
  a.sku as sku_code,
  CONCAT(a.location_code, "_", a.warehouse_code) as location_fc_code,
  a.warehouse_code as fc_code,
  a.location_code,
  a.stock_quantity,
  datetime(current_timestamp(), "Asia/Ho_Chi_Minh") as last_updated_time
FROM dedup_inventory_sku_location a
LEFT JOIN ${ref("dim_sku")} b
ON a.sku = b.sku_code
WHERE stock_quantity > 0 AND a.warehouse_code IN (
  SELECT fc_code FROM ${ref("dim_fc")}
)