config { 
    type: "incremental",
    description: "PIC: anh.letam",
	  name: "fact_cart_item_deleted",
    bigquery: {
    partitionBy: "date(time_ingested_to_mongo)",
    clusterBy: ["cart_id"]
  },
   
}

select
  * , `${source.silver}.mongoid_to_timestamp` (mg_id) as time_ingested_to_mongo,
  date(created_time) as created_at
from
  ${source.silver}.marketplace_prd_cart_cart_item_deleted
${ when(incremental(), `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()} )`) }
QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)