config {
    type: "table",
    description: `Started time: 20240801| PIC: tu.dang; model_type: incremetal ;schedule: 12h00
    Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order`,
    tags: ["12h00"],
    name: "fact_checkout_item",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer",
        sku: "NonNull |" | docs.sku,
        item_code: "NonNull |" | docs.item_code,
        price: "The cost of the item. This field indicates the selling price of the product at the time of the order",
        quantity: "The number of units of the item ordered. This field shows the amount of product ordered by the customer",
        order_item_created_time: "NonNull | The datetime when the order item was created, adjusted to the 'Asia/Ho_Chi_Minh' timezone",
        cart_item_created_time: "NonNull | The datetime when the item was added to the cart, adjusted to the 'Asia/Ho_Chi_Minh' timezone. This helps in understanding customer behavior before purchase",
        page: "Nullable | The webpage where the item was ordered from. This field is used for tracking the source page of the order",
        event_source: "Nullable | The source of the event, indicating how the item was ordered. This can help identify whether the order was placed via promotion, same-seller or something else",
        event_screen: "Nullable | The screen on which the event occurred. This provides additional context on the user interface interaction",
        tags: "Nullable | Tags associated with the order item. These tags can be used for categorization and analysis purposes",
        sku_key: "NonNull | " + docs.sku_key,
        province_code: "Nullable | " + docs.province_code
    },
    bigquery: {
        partitionBy: "date(order_item_created_time)"
    }
}
 

with stg_order as (
  SELECT 
    order_id, 
    province_code, 
    status, 
    -- source,
    JSON_VALUE(source_detail, '$.platform') as platform
  FROM  ${source.platinum}.marketplace_prd_order_v2_order
  where created_date >= "2024-06-01"
) 

SELECT  oi.order_id
     , oi.customer_id
     , oi.created_at
     , date(oi.created_at) as created_date
     , oi.seller_code
     , oi.sku_code
     , oi.product_id
     , oi.demand_quantity
     , oi.sales_price
     , oi.event_source
     , oi.event_screen
     , oi.province_code
     , oi.sku_key_sales_region_code
     , o.platform
     , o.status as order_status
     , sum(fm.final_price_after_rebate* fm.outbound_quantity ) as purchase_amount,
       sum(unit_price* fm.outbound_quantity) as outbound_amount
FROM ${ref('fact_order_item')} oi
left join stg_order o on oi.order_id = o.order_id
left join ${ref('fact_margin')} fm on oi.mg_id = fm.mg_id and oi.sku_code= fm.sku_code
where date(oi.created_at) >= "2024-06-01"
group by all
