config {
    type: "table", 
    description: 
        `PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: 0h30 daily;
        Source: 
            ${source.silver}.monitoring_prd_realtime_supply_margin_sku
        `,
    columns: {
        date: "NON-NULL | Margin date in +7 Timezone",
        product_id: "NON-NULL",
        sku_code: "NON-NULL",
        province_code: "NON-NULL",
        total_price: "Total ordered amount of SKU in Margin Date",
        total_purchasing_value: "Total purchasing amount of SKU in Margin Date",
        total_quantity: "Total ordered quantity of SKU in Margin Date",
        sales_region_code: "NON-NULL",
    },
    tags: ["0h30"],
    bigquery: {
        partitionBy: "date",
        clusterBy: ["sku_code", "province_code"]

    },
    assertions: {
        nonNull: ["date", "product_id", "sku_code", "province_code", "sales_region_code"]
    }
}

SELECT
    PARSE_DATE("%Y/%m/%d", a.day_str) AS  date
    , a.location_code AS province_code
    , s.product_id
    , a.sku AS sku_code
    --, a.margin
    , a.total_price
    , a.total_purchasing_value
    , a.total_quantity
    , b.region_code AS sales_region_code
FROM (
    SELECT *
    FROM ${source.silver}.monitoring_prd_realtime_supply_margin_sku
    WHERE
        ingest_time >= TIMESTAMP_SUB('2024-06-01', INTERVAL 7 HOUR)
        AND (created_time >= TIMESTAMP_SUB('2024-06-01', INTERVAL 7 HOUR) OR created_time IS NULL)
    QUALIFY ROW_NUMBER() over (_window) = 1 AND FIRST_VALUE(action) over (_window) <> 'd'
    WINDOW _window AS (PARTITION BY mg_id ORDER BY synced_at DESC, last_updated_time DESC)
) AS a
    LEFT JOIN ${source.gold}.dim_sales_region_service_area AS b ON b.service_area_code = a.location_code
    LEFT JOIN ${source.gold}.dim_sku AS s ON s.sku_code = a.sku
WHERE
    a.span = 'DAY'
    AND location_code <> '00'
    AND location_code IS NOT NULL
    AND s.sku_code IS NOT NULL



