config {
  type: "table",
  description: "Source: warehouse_prd_inbound_inbound_ticket, warehouse_prd_inbound_inbound_ticket_item, only select tickets with status not in (CANCEL, COMPLETED) | Schedule: every 30 mins from 9am-6pm | PIC: dong.le",
  name: "fact_stock_incoming",
  tags: ["custom_30min_9to18"],
  columns: {
    po_code: "associated purchase order code with the pick ticket",
    ib_status: "status of the pick ticket",
    created_date: "date the ticket was created",
    incoming_type: "categorized as IN-PARTNER if status is WAITING, IN-HUB if status is IN_TRANSIT, else IN-FC",
    sku_fc_key: "concatenation of sku key and warehouse code",
    sku_code: "unique sku identifier",
    fc_code: "warehouse code",
    demand_quantity: "demand quantity from ticket item",
    inbound_quantity: "inbound quantity from ticket item",
    incoming_quantity: "= demand_quantity - inbound_quantity"
  },
  bigquery: {
    partitionBy: "created_date"
  }
}

WITH dedup_inbound_ticket AS ${dedup.dedup(
  "lakehouse-prod-394907.silver_buymed_vn.warehouse_prd_inbound_inbound_ticket",
  "ticket_id, po_code, status, created_time",
  "timestamp(date_sub(current_date(),interval 1 month))"
)},

dedup_inbound_ticket_item AS ${dedup.dedup(
  "lakehouse-prod-394907.silver_buymed_vn.warehouse_prd_inbound_inbound_ticket_item",
  "ticket_id, sku as sku_code, warehouse_code as fc_code, demand_quantity, inbound_quantity",
  "timestamp(date_sub(current_date(),interval 1 month))"
)}

SELECT
    a.po_code
    , a.status as ib_status
    , DATE(a.created_time, "Asia/Ho_Chi_Minh") as created_date
    , DATETIME(a.created_time, "Asia/Ho_Chi_Minh") as created_time
    , CASE
        WHEN a.status = "WAITING" THEN "IN-PARTNER"
        WHEN a.status = "IN_TRANSIT" THEN "IN-HUB"
        ELSE "IN-FC"
    END as incoming_type
    , CONCAT(c.sku_key, "_", b.fc_code) as sku_fc_key
    , b.sku_code
    , b.fc_code
    , b.demand_quantity
    , b.inbound_quantity
    , b.demand_quantity - b.inbound_quantity as incoming_quantity

FROM dedup_inbound_ticket_item b
LEFT JOIN dedup_inbound_ticket a on b.ticket_id = a.ticket_id
LEFT JOIN ${ref("dim_sku")} c on b.sku_code = c.sku_code
WHERE a.status NOT IN ("CANCEL", "COMPLETED")