config { 
    type: "table",
    description: "PIC: anh.letam",
    tags: ['24HOUR'],
	name: "fact_cart_item_deleted"
}
select *,
	   silver_buymed_vn.mongoid_to_timestamp(mg_id) as time_ingested_to_mongo 
from silver_buymed_vn.marketplace_prd_cart_cart_item_deleted

--from ${source_base.SILVER}.marketplace_prd_cart_cart_item_deleted_backup_2

--${ when(incremental(), `WHERE (SELECT time_ingested_to_mongo is null FROM ${self()})`)}