-- config {
--     type: 'table',

-- }

-- SELECT
--     event,
--     account_id,
--     account_type,
--     DATETIME(created_time, "Asia/Ho_Chi_Minh") AS created_time,
--     JSON_EXTRACT_SCALAR(extra_props, '$.metadata.productId') AS product_id,
--     JSON_EXTRACT_SCALAR(extra_props, '$.metadata.productStatus') AS product_status,
--     JSON_EXTRACT_SCALAR(extra_props, '$.metadata.sellerCode') AS seller_code,
--     JSON_EXTRACT_SCALAR(extra_props, '$.metadata.hasEverSold') AS has_ever_sold
-- FROM
--     ${source.silver}.monitoring_prd_collector_user_stats_${datetime.current_date()}
-- WHERE
--     event IN ("SUGGESTION_SELLING_UPDATE_PRODUCT",
--         "SUGGESTION_SELLING_CREATE_PRODUCT",
--         "SUGGESTION_SELLING_CTA_CLICK")

