config {
    type: "table",
    description: `Started time: 20240801| PIC: tu.dang; model_type: incremetal ;schedule: 12h00
    Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order`,
    tags: ["12h00"],
    name: "fact_checkout_item",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer",
        sku: "NonNull |" | docs.sku,
        item_code: "NonNull |" | docs.item_code,
        price: "The cost of the item. This field indicates the selling price of the product at the time of the order",
        quantity: "The number of units of the item ordered. This field shows the amount of product ordered by the customer",
        order_item_created_time: "NonNull | The datetime when the order item was created, adjusted to the 'Asia/Ho_Chi_Minh' timezone",
        cart_item_created_time: "NonNull | The datetime when the item was added to the cart, adjusted to the 'Asia/Ho_Chi_Minh' timezone. This helps in understanding customer behavior before purchase",
        page: "Nullable | The webpage where the item was ordered from. This field is used for tracking the source page of the order",
        event_source: "Nullable | The source of the event, indicating how the item was ordered. This can help identify whether the order was placed via promotion, same-seller or something else",
        event_screen: "Nullable | The screen on which the event occurred. This provides additional context on the user interface interaction",
        tags: "Nullable | Tags associated with the order item. These tags can be used for categorization and analysis purposes",
        sku_key: "NonNull | " + docs.sku_key,
        province_code: "Nullable | " + docs.province_code
    },
    bigquery: {
        partitionBy: "date(order_item_created_time)"
    }
}
 
WITH stg_order_item as   (
    SELECT 
        order_id,
        customer_id,
        product_id,
        sku,
        item_code,
        outbound_infos,
        extra_props,
        price,
        quantity,
        DATETIME(created_time, 'Asia/Ho_Chi_Minh') as order_item_created_time,
        DATETIME(cart_item_created_time, 'Asia/Ho_Chi_Minh') as cart_item_created_time,
        page,
        event_source,
        event_screen,
        tags,
        product_id || "_" || seller_code as sku_key,
        mg_id,
        created_date
    FROM ${source.platinum}.marketplace_prd_order_v2_order_item
    where created_date >= "2024-07-01"
)
,
stg_order as (
  SELECT 
    order_id, 
    province_code, 
    status, 
    -- source,
    JSON_VALUE(source_detail, '$.platform') as platform
  FROM ${source.platinum}.marketplace_prd_order_v2_order
  where created_date >= "2024-07-01"
) 

SELECT
  a.order_id,
  b.status as order_status,
  a.customer_id,
  a.product_id,
  a.sku,
  a.item_code,
  a.price,
  a.quantity,
  a.order_item_created_time,
  a.cart_item_created_time,
  a.page,
  a.event_source,
  a.event_screen,
  a.tags,
  b.province_code,
  a.sku_key,
  b.platform,
 
FROM stg_order_item a
LEFT JOIN stg_order b
  ON a.order_id = b.order_id
where created_date >= "2024-07-01"
