config {
    type: "incremental",
    description: " 6 months| PIC: minh.luu",
    tags: ["12h00"],
    name: "fact_checkout_item",
    bigquery: {
        partitionBy: "DATE(order_item_created_time)"
    }
}

-- TODO:
-- - Setup primary key
-- - Setup fact key
-- - column type and description
-- - auto test in duration time


-- WITH filter_time as (
--   select timestamp_sub(timestamp(current_date("+7")),interval 1 day ) as start_date
-- ), -- TODO: create include for filter_time named Filter day

WITH stg_order_item as   ${dedup.dedup(
      "lakehouse-prod-394907.silver_buymed_vn.marketplace_prd_order_v2_order_item",
      `
      order_id,
      customer_id,
      sku,
      item_code,
      price,
      quantity,
      DATETIME(created_time, 'Asia/Ho_Chi_Minh') as order_item_created_time,
      DATETIME(cart_item_created_time, 'Asia/Ho_Chi_Minh') as cart_item_created_time,
      page,
      event_source,
      event_screen,
      tags
      `,
      start_timestamp= when(incremental(),
              ` TIMESTAMP(current_datetime() - INTERVAL 2 DAY )`,
              ` TIMESTAMP_SECONDS(0)`)                           

)}
,

stg_order as ${dedup.dedup(
  "lakehouse-prod-394907.silver_buymed_vn.marketplace_prd_order_v2_order",
  "order_id, province_code",
  start_timestamp= when(incremental(),
            ` TIMESTAMP(current_datetime() - INTERVAL 2 DAY )`, 
            ` TIMESTAMP_SECONDS(0)`)
)}

SELECT 
  a.order_id,
  a.customer_id,
  a.sku,
  a.item_code,
  a.price,
  a.quantity,
  a.order_item_created_time,
  a.cart_item_created_time,
  a.page,
  a.event_source,
  a.event_screen,
  a.tags,
  b.province_code
FROM stg_order_item a
LEFT JOIN stg_order b
  ON a.order_id = b.order_id

${
  when(incremental(),
   `WHERE order_item_created_time > (SELECT MAX(order_item_created_time) FROM ${self()})`,
   `WHERE order_item_created_time > DATE_TRUNC(CURRENT_DATETIME('+7') - INTERVAL 6 MONTH,  MONTH)`)
}

-- post_operations {
--   ${
--     when(incremental(),
--       "",
--       `ALTER TABLE ${self()} ADD PRIMARY KEY (product_id) NOT ENFORCED;`
--     )
--   }
-- }
