config {
  type: "table",
  description: 
        `
        Customer information, address, tax code in the invoice for each order;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: Hourly;
        Source: 
            ${source.platinum}.accounting_prd_invoice_order,
            ${source.platinum}.accounting_prd_invoice_order_invoice

        `,
  bigquery: {
    partitionBy: "date(invoice_time)",
    clusterBy: ["order_id"]
  },
  tags: ["custom_1h_past5"]
}

SELECT
    io.order_id
    , io.customer_request AS invoice_request
    , COALESCE(ioi.buyer_name, io.buyer_name) AS buyer_name
    , COALESCE(ioi.customer_tax_code, io.customer_tax_code) AS customer_tax_code
    , COALESCE(ioi.customer_name, io.customer_name) AS invoice_name
    , COALESCE(ioi.customer_address, io.customer_address) AS invoice_address
    , CASE 
        WHEN io.customer_request = true THEN 'Có lấy hóa đơn'
        WHEN io.customer_request = false THEN 'Không yêu cầu xuất hóa đơn' 
      END AS invoice_note
    , io.sale_order_code
    , ioi.seller_code
    , ioi.code AS invoice_code
    , TIMESTAMP_ADD( COALESCE(ioi.arising_time, ioi.created_time), interval 7 hour) AS invoice_time
    , ioi.customer_id
    , STRING(JSON_QUERY_ARRAY(ioi.invoice_data)[SAFE_OFFSET(0)].invoice_no) AS invoice_number
    , REGEXP_REPLACE(STRING(JSON_QUERY_ARRAY(ioi.invoice_data)[SAFE_OFFSET(0)].pdf_url), 'storage.googleapis.com', 'cdn-gcs.thuocsi.vn') AS invoice_url
    , SAFE_CAST(COALESCE(JSON_VALUE(ioi.extra_props, '$.is_shadow_invoice'), 'false') AS BOOLEAN) AS is_shadow_invoice
FROM ${source.platinum}.accounting_prd_invoice_order AS io
    LEFT JOIN ${source.platinum}.accounting_prd_invoice_order_invoice AS ioi
        USING(order_id)
    LEFT JOIN ${ref('fact_order')} AS fo
        USING(order_id)
WHERE 1=1
  AND fo.order_status <> "CANCEL"
  AND io.created_date >= "2025-01-01"
  AND ioi.created_date >= "2025-01-01"
  AND DATE(fo.created_at) >= "2025-01-01"