config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "integration_prd_tpl_callback_callback",
    description : `
    PIC: minh.luu
    Partition by: created date
    Cluster by: status, ingest_time
    `,
    tags:["platinum","integration_prd_tpl_callback"]
}
 
  WITH silver AS (
    SELECT
      key,mg_id,so,action_time,cod,created_source,external_tpl_name,extra_callback,last_updated_time,num_package,status,status_name,tpl_code,tpl_status,tpl_status_name,warehouse_code,weight,hub_code,logs,type,deliver_id,deliver_name,updated_by,reason,reason_code,rescheduled_delivery_time,total_fee,height,length,width,sale_order,external_tpl_id,current_location,action_name,rescheduled_pickup_time,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN silver_buymed_vn.MONGOID_TIMESTAMP(mg_id) IS NOT NULL THEN DATE(DATETIME(silver_buymed_vn.MONGOID_TIMESTAMP(mg_id), 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.integration_prd_tpl_callback_callback
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,so,action_time,cod,created_source,external_tpl_name,extra_callback,last_updated_time,num_package,status,status_name,tpl_code,tpl_status,tpl_status_name,warehouse_code,weight,hub_code,logs,type,deliver_id,deliver_name,updated_by,reason,reason_code,rescheduled_delivery_time,total_fee,height,length,width,sale_order,external_tpl_id,current_location,action_name,rescheduled_pickup_time,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `integration_prd_tpl_callback_callback`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  