config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Price for CIRCA FS, OS on thuocsi.vn`,
    tags: ['AI_CIRCA']
}

SELECT 
  cutoff_date
  , product_id
  , fc_code
  , CASE fc_code 
      WHEN 'BD' THEN 'MIENNAM'
      WHEN 'HN' THEN 'MIENBAC'
    END AS sales_region
  , sku_code
  , seller_code
  , price_after_discount
  , cogs
FROM gold_buymed_vn2.fact_product_sku_pricing_circa_ver2