config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Product of Circa COS.`,
    tags: ['AI_CIRCA']
}

SELECT voucher_code
       ,start_date
       ,end_date
       ,is_expired
       ,limit_value -- số lượng giới hạn
       ,created_date
       ,created_by
       ,client_id
       ,campaign_code
       ,campaign_name
       ,'VOUCHER_DISCOUNT' AS voucher_type 

FROM ${ref('gold_buymed_vn2', 'dim_promotion_voucher_circa')} 

UNION ALL 


SELECT gift_code
       ,start_date
       ,end_date
       ,is_expired
       ,limit_value -- số lượng giới hạn
       ,created_date
       ,created_by
       ,client_id
       ,campaign_code
       ,campaign_name
       ,'VOUCHER_GIFT' AS voucher_type 
FROM ${ref('gold_buymed_vn2', 'dim_promotion_gift')} 


