config {
    type: 'table',
    schema: "buymed_innovation",
    description: `All online orders of Circa.`,
    tags: ['AI_CIRCA', "custom_1h_past10"]
}


SELECT 
    o.* EXCEPT (status, deliver_status, pos_status, price, total_price)
    -- , price AS or
    , o.price AS total_item_amount
    , o.total_price AS order_amount
    , o.o2o_status AS status
    , oi.product_id
    , oi.product_name
    , oi.unit
    , oi.price AS unit_price
    , oi.quantity
    , oi.origin_price
    , is_deal1k
    , deal_name
    , campaign_name
FROM ${ref("gold_buymed_vn2", "circa_online_order_item")} AS oi
    LEFT JOIN ${ref("gold_buymed_vn2", "circa_online_order")} AS o USING(order_code)


