config {
    type: 'view',
    schema: "buymed_innovation",
    description: "Margin of Circa COS.",
    //tags: ['AI_CIRCA']
}
SELECT 
 e.name AS client_name
,o.client_id
,o.created_date
,o.created_hour
,pos_type
,pos_code
,pos_name
,SUM(gmv) gmv
,SUM(cogs_circa) cogs_circa
,SUM(cogs_buymed) cogs_buymed
,SUM(gross_profit_circa) gross_profit_circa
,SUM(gross_profit_buymed) gross_profit_buymed
,SAFE_DIVIDE(SUM(gross_profit_circa), SUM(gmv)) AS gross_margin_circa
,SAFE_DIVIDE(SUM(gross_profit_circa), SUM(gmv)) AS gross_margin_buymed
,SUM(voucher_circa) voucher_circa
,SUM(voucher_buymed) voucher_buymed
,SUM(deal) deal
,SUM(net_profit_circa) net_profit_circa
,SUM(net_profit_buymed) net_profit_buymed
,SAFE_DIVIDE(SUM(net_profit_circa), SUM(gmv)) AS net_margin_circa
,SAFE_DIVIDE(SUM(net_profit_buymed), SUM(gmv)) AS net_margin_buymed
FROM buymed_innovation.circa_fact_net_margin o 
LEFT JOIN buymed_circa_v2.entity_client e ON o.client_id = e.id
GROUP BY ALL