config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Price Circa.`,
    tags: ['AI_CIRCA']
}

WITH base_data AS (
SELECT DISTINCT product_id
               ,seller_code
               ,unit
               ,convert_rate
               ,sale_unit_price AS sales_price
               ,price_af_discount AS sales_price_after_discount
               ,discount_type
               ,CONCAT(client_id, "_", product_id) AS product_id_key
               ,client_type
               ,client_name
FROM ${ref("gold_buymed_vn2", "cos_adhoc_product_price_fs")}

UNION ALL

SELECT DISTINCT product_id
               ,seller_code
               ,unit
               ,convert_rate
               ,final_sale_price AS sales_price
               ,price_af_discount AS sales_price_after_discount
               ,discount_type
               ,CONCAT(client_id, "_", product_id) AS product_id_key
               ,client_type
               ,client_name
FROM ${ref("gold_buymed_vn2", "cos_adhoc_pos_product_client")}
WHERE seller_code = 'CIRCA'
), ts_unit AS (
    SELECT DISTINCT product_id
                   ,unit
    FROM gold_buymed_vn2.dim_product
), have_ts_unit AS(
SELECT a.* FROM base_data a
LEFT JOIN ts_unit b ON lower(a.unit) = lower(b.unit)
WHERE b.product_id IS NOT NULL
)
SELECT *  
FROM have_ts_unit
