config {
    type: 'view',
    schema: "buymed_innovation",
    description: `All orders item of Circa.`,
    tags: ['AI_CIRCA']
}

WITH 
    voucher AS (
        SELECT 
            v.order_code_used
            , v.voucher_code
            , v.campaign_code
        FROM ${ref('gold_buymed_vn2','cos_voucher_info')} AS v
        QUALIFY ROW_NUMBER() OVER(PARTITION BY order_code_used) = 1
        -- WHERE v.campaign_code = "CAMPAIGN000165"
    ),

    fact_order AS (
        SELECT
            o.created_date AS date
            , o.completed_at AS order_completed_at
            , o.order_code
            , o.order_id
            , CASE
                     WHEN entity_id = '00000000-0000-0000-0000-000000000000'
                       OR entity_id = '0'
                     THEN CONCAT(entity_id, o.order_code)
                     ELSE entity_id
             END AS customer_id
            , o.client_id
            , o.pos_id
            , o.pos_code
            , p.name AS pos_name
            , IF(p.type = "FS", "FS", "COS") AS pos_type
            , o.channel
            , o.type AS online_or_offline_order
            , g.ward_name
            , g.district_name
            , g.province_name
            , COALESCE(o.medicine_cutting_fee, 0) AS medicine_cutting_fee
            , o.discount_amount
            , v.voucher_code
            , IF(v.campaign_code = "CAMPAIGN000165", true, false) AS is_referral
            , o.status AS order_status
            , SUM(o.total_amount)- SUM(COALESCE(c.rev_return, 0))  - SUM(COALESCE(delivery_amount, 0)) AS revenue
            -- , IF(o.order_code IN (SELECT order_code_used FROM referral ), true, false) AS is_referral
        FROM ${ref('gold_buymed_vn2','cos_fact_order')} AS o
        LEFT JOIN ${ref("gold_buymed_vn2", "cos_return_completed")} c ON o.order_code = c.order_code
            LEFT JOIN buymed_circa_v2.entity_pos_profile AS p ON o.pos_code = p.code
            LEFT JOIN voucher AS v ON v.order_code_used = o.order_code
            LEFT JOIN ${ref('gold_buymed_vn2','dim_geo_location')} AS g ON g.location_code = COALESCE(p.ward, p.district, p.province)
        WHERE 1=1
            AND o.completed_date IS NOT NULL
            AND o.completed_date >= "2018-01-01"
            -- AND o.completed_date >= DATE_SUB(DATE_TRUNC(CURRENT_DATE("+7"), MONTH), INTERVAL 1 MONTH)
            AND o.status IN ('COMPLETED', 'COMPLETED_SHIPPING')
            AND o.status <> "CANCELED"
            AND o.pos_id <> "0afdb831-b60d-4254-8822-df13e39c90e7"
        GROUP BY ALL
    ),

    fact_order_item AS (
            SELECT
               o.date
             , o.order_completed_at
             , o.order_code
             , o.order_id
             , o.order_status
             , o.customer_id
             , o.client_id
             , o.pos_id
             , o.pos_code
             , o.pos_name
             , o.pos_type
             , o.channel
             , o.ward_name
             , o.district_name
             , o.province_name
             , oi.product_id
             , oi.quantity
             , oi.qty_rt
             , oi.unit
             , oi.discount_amount AS discount_deal
             , promotion_event_code AS deal_code
             , campaign_code AS campaign_deal_code
             , campaign_name AS campaign_deal_name
             , oi.unit_price * (oi.quantity - COALESCE(oi.qty_rt,0)) AS total_item_amount
             , oi.unit_price_before_discount * (oi.quantity - COALESCE(oi.qty_rt,0)) AS total_item_amount_before_deal
             , o.medicine_cutting_fee / COUNT(*) OVER(PARTITION BY oi.order_id) AS medicine_cutting_fee
             , o.discount_amount / COUNT(*) OVER(PARTITION BY oi.order_id) AS discount_voucher
             , CONCAT(oi.client_id, "_", oi.product_id) AS product_id_key
             , o.voucher_code
             , o.is_referral
             , CONCAT(d.customer_phone, d.customer_name) AS o2o_customer_key
             , o.online_or_offline_order
           FROM ${ref('gold_buymed_vn2','cos_fact_order_item')} oi
           LEFT JOIN fact_order o ON oi.order_id = o.order_id
           LEFT JOIN buymed_circa_v2.order_delivery_info d ON d.order_id = o.order_id AND o.channel = "O2O"
           WHERE o.order_id IS NOT NULL
    
    )

    , valid_order AS (
        SELECT DISTINCT
            i.order_code
        FROM ${ref("gold_buymed_vn2", "cos_fact_order_item")} i
        INNER JOIN fact_order o ON i.order_code = o.order_code
        WHERE (i.quantity - COALESCE(i.qty_rt, 0)) > 0
    )

   , orders_weekly AS (
        SELECT
            DATE_TRUNC(o.date, WEEK(MONDAY)) AS week_start
            , FORMAT_DATE('%Y_W%W', o.date) AS week_label
            , o.customer_id
        FROM fact_order AS o
            LEFT JOIN buymed_circa_v2.entity_customer AS c ON o.customer_id = c.id
            LEFT JOIN valid_order i ON o.order_code = i.order_code
        WHERE 1=1
            AND o.client_id = 1
            AND i.order_code IS NOT NULL

            -- AND o.customer_id <> '00000000-0000-0000-0000-000000000000'
            -- AND c.phone_number IS NOT NULL
            -- AND c.phone_number <> ""
            -- AND REGEXP_REPLACE(c.phone_number, '0','') <> ""
    ),

    customer_first_order AS (
        SELECT DISTINCT
            customer_id
            , MIN(week_start) AS first_week
        FROM orders_weekly
        GROUP BY 1
    ),

    customer_weeks AS (
        SELECT DISTINCT
            o.customer_id
            , o.week_start
            , o.week_label
            , i.first_week
        FROM orders_weekly o
        LEFT JOIN customer_first_order i
            ON o.customer_id = i.customer_id
        WHERE o.week_start >= "2028-01-01"
    ),

    labeled_customers AS (
        SELECT
            cw.customer_id
            , cw.week_label
            , cw.week_start
            , CASE WHEN cw.week_start = cw.first_week THEN 1 ELSE 0 END AS is_new
            , CASE WHEN EXISTS (
                SELECT 1
                FROM customer_weeks prev
                WHERE prev.customer_id = cw.customer_id
                AND prev.week_start = cw.week_start - INTERVAL 7 DAY
            ) THEN 1 ELSE 0 END AS is_repeat
            ,CASE
                WHEN EXISTS (
                    SELECT 1
                    FROM customer_weeks prev
                    WHERE prev.customer_id = cw.customer_id
                    AND prev.week_start < cw.week_start - INTERVAL 7 DAY
                )
                AND NOT EXISTS (
                    SELECT 1
                    FROM customer_weeks prev
                    WHERE prev.customer_id = cw.customer_id
                    AND prev.week_start = cw.week_start - INTERVAL 7 DAY
                )
            THEN 1 ELSE 0 END AS is_reacquire
        FROM customer_weeks cw
    ),

    active_customer AS (
        SELECT DISTINCT
            -- week_label
            week_start
            , customer_id
            , CASE
                WHEN is_new = 1 THEN 'NEW'
                WHEN is_repeat = 1 THEN 'REPEAT'
                WHEN is_reacquire = 1 THEN 'REACQUIRED'
            END AS customer_active_type
        FROM labeled_customers
    )

SELECT
    oi.* EXCEPT(total_item_amount , medicine_cutting_fee, discount_voucher, quantity, total_item_amount_before_deal, discount_deal )
    , SUM(oi.quantity - COALESCE(oi.qty_rt, 0)) AS quantity
    , SUM(oi.total_item_amount) AS total_item_amount
    , SUM(oi.total_item_amount_before_deal) AS total_item_amount_before_deal
    , SUM(oi.total_item_amount_before_deal) - SUM(oi.total_item_amount) AS discount_deal
    , SUM(oi.medicine_cutting_fee) AS medicine_cutting_fee
    , SUM(oi.discount_voucher) AS discount_voucher
    , SUM(total_item_amount) + SUM(oi.medicine_cutting_fee)  AS gmv_circa
    , SUM(total_item_amount_before_deal) + SUM(oi.medicine_cutting_fee)  AS gmv_circa_before_deal
    , ac.customer_active_type
    , CONCAT(oi.order_code, oi.product_id_key) AS order_product_unit_key
FROM fact_order_item AS oi
    LEFT JOIN active_customer AS ac 
        ON oi.customer_id = ac.customer_id
        AND DATE_TRUNC(oi.date, WEEK(MONDAY)) = ac.week_start
        WHERE oi.quantity - COALESCE(oi.qty_rt, 0) > 0 
GROUP BY ALL