config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Price Circa.`,
    tags: ['AI_CIRCA']
}

  SELECT DISTINCT
     product_id
    , competitor_unit AS unit
    , market_price_aft_convert AS competior_price
    , CASE WHEN competitor = 'LongChau' THEN 'Long Châu'
           ELSE competitor END AS competitor
  FROM ${ref('adhoc_pricing_competitor_price')} m
  WHERE qc = "QC" and competitor IN ('LongChau', 'Pharmacity')
  GROUP BY ALL