config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Gross Margin of Circa COS.`,
    tags: ['AI_CIRCA']
}

WITH 
    cogs AS (
        SELECT  
            i.order_id
            , CONCAT(client_id, "_", product_id) AS product_id_key
            , unit
            , SUM(i.unit_cost_price *  (i.quantity - COALESCE(i.qty_rt,0) )) AS cogs
        FROM ${ref('gold_buymed_vn2','cos_fact_order_item')} AS i
        WHERE owner_name = 'CIRCA'
        GROUP BY ALL
    ),

    map_cogs_buymed AS (
        SELECT
            i.*
            , CASE
                WHEN i.fulfillment_method = 'SO_THUOCSI' AND cogs_base_unit_ts IS NOT NULL THEN cogs_base_unit_ts
                ELSE base_unit_cost_price
            END AS base_unit_cost_price_ts
        FROM ${ref("gold_buymed_vn2", "cos_fact_order_item")} i
        LEFT JOIN ${ref("gold_buymed_vn2", "circa_cogs_thuocsi_by_po")} p ON i.po_code = p.po_code
                                                                AND i.product_id = p.product_id
        WHERE i.client_id = 1
    )
    , cogs_buymed AS (
        SELECT
            i.order_code
            , i.product_id
            , SUM(i.discount_amount * (i.quantity - COALESCE(i.qty_rt, 0))) AS discount_deal
            , SUM(
                CASE
                    WHEN i.owner_name <> 'CIRCA MARKETING'
                        AND i.gift_code IS NOT NULL
                        AND i.gift_code <> ''
                        AND i.unit_price = 0
                        AND i.product_id NOT IN (941832, 941878, 1101283, 2003919, 2004189)
                    THEN i.unit_cost_price * (i.quantity - COALESCE(i.qty_rt, 0))
                    ELSE 0
                END
            ) AS cogs_circa_gift
            , SUM(
                CASE
                    WHEN i.owner_name = 'CIRCA MARKETING'
                        AND i.product_id NOT IN (941832, 941878, 1101283, 2003919, 2004189)
                    THEN i.unit_cost_price * (i.quantity - COALESCE(i.qty_rt, 0))
                    ELSE 0
                END
            ) AS cogs_mkt
            , SUM(
                CASE
                    WHEN i.owner_name <> 'CIRCA MARKETING'
                        AND (i.gift_code IS NULL OR i.gift_code = '')
                        AND i.unit_price <> 0
                    THEN i.unit_cost_price * (i.quantity - COALESCE(i.qty_rt, 0))
                    ELSE 0
                END
            ) AS cogs_circa
            , SUM(
                CASE
                    WHEN i.owner_name <> 'CIRCA MARKETING'
                        AND i.gift_code IS NOT NULL
                        AND i.gift_code <> ''
                        AND i.unit_price = 0
                        AND i.product_id NOT IN (941832, 941878, 1101283, 2003919, 2004189)
                    THEN i.base_unit_cost_price_ts * i.convert_rate * (i.quantity - COALESCE(i.qty_rt, 0))
                    ELSE 0
                END
            ) AS cogs_buymed_gift
            , SUM(
                CASE
                    WHEN i.owner_name = 'CIRCA MARKETING'
                        AND i.product_id NOT IN (941832, 941878, 1101283, 2003919, 2004189)
                    THEN i.base_unit_cost_price_ts * i.convert_rate * (i.quantity - COALESCE(i.qty_rt, 0))
                    ELSE 0
                END
            ) AS cogs_buymed_mkt
            , SUM(
                CASE
                    WHEN i.owner_name <> 'CIRCA MARKETING'
                        AND (i.gift_code IS NULL OR i.gift_code = '')
                        AND i.unit_price <> 0
                    THEN i.base_unit_cost_price_ts * i.convert_rate * (i.quantity - COALESCE(i.qty_rt, 0))
                    ELSE 0
                END
            ) AS cogs_buymed
        FROM map_cogs_buymed AS i
        LEFT JOIN ${ref("gold_buymed_vn2", "cos_fact_order")} o ON i.order_id = o.order_id
        WHERE i.client_id = 1
        AND o.pos_id <> '0afdb831-b60d-4254-8822-df13e39c90e7'
        GROUP BY ALL
    )

SELECT
    o.date
    , o.order_id
    , o.customer_id
    , o.product_id_key
    , o.unit
    , o.pos_name
    , o.pos_type
    , o.gmv_circa AS gmv_circa
    , cogs.cogs AS total_cost
    , CONCAT(o.order_id, o.product_id_key, o.unit) AS order_product_unit_key
FROM (
    SELECT
        date
        , order_id
        , customer_id
        , product_id_key
        , unit
        , SUM(gmv_circa) AS gmv_circa
        , pos_name
        , pos_type
    FROM ${ref('buymed_innovation', 'circa_fact_order')} 
    WHERE 1=1
        AND client_id = 1
        AND order_status IN ('COMPLETED', 'COMPLETED_SHIPPING')
    GROUP BY ALL
) AS o
    LEFT JOIN cogs ON o.order_id = cogs.order_id AND o.product_id_key = cogs.product_id_key AND o.unit = cogs.unit
WHERE  1=1
GROUP BY ALL