config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Margin of Circa.`,
    tags: ['AI_CIRCA']
}

SELECT
    o.date
    , o.gmv_circa
    , o.pos_name
    , o.pos_type
    , SUM(COALESCE(oi.unit_cost_price, 0) * COALESCE(CAST(oi.quantity AS NUMERIC), 0)) AS total_cost
FROM ${ref('gold_buymed_vn2','cos_fact_order_item')} AS oi
    LEFT JOIN ${ref('buymed_innovation', 'circa_fact_order')} AS o ON oi.order_id = o.order_id
WHERE o.order_id IS NOT NULL
GROUP BY ALL