config {
    type:"operations",
    tags: ["AI_CIRCA"]
}

-- fact_order

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_order`
AS (SELECT * EXCEPT(order_completed_at), DATETIME(order_completed_at) AS order_completed_at FROM  ${ref("buymed_innovation", "circa_fact_order")});


-- fact_margin

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_margin`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_margin")});

-- fact_net_margin

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_net_margin`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_net_margin")});

-- fact_target

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_target`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_target")});

-- fact_purchase_order

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_purchase_order`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_purchase_order")});

-- fact_inventory

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_inventory`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_inventory")});

-- fact_order_online

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_order_online`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_order_online")});

-- fact_vision_ai_camera
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_vision_ai_camera`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_vision_ai_camera")});

-- fact_thuocsi_pricing
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_thuocsi_pricing`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_thuocsi_pricing")});

-- fact_thuocsi_product_sku_status
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_thuocsi_product_sku_status`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_thuocsi_product_sku_status")});

-- dim_customer

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_dim_customer`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_dim_customer")});

-- dim_product

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_dim_product`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_dim_product")});

-- dim_product_substitute

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_dim_product_substitute`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_dim_product_substitute")});

-- agg_inventory

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_agg_inventory`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_agg_inventory")});

-- agg_loss_sale

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_agg_loss_sale`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_agg_loss_sale")});

-- agg_online_leadtime

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_agg_online_leadtime`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_agg_online_leadtime")});

-- circa_chat_sessions
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_chat_sessions`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_chat_sessions")});

-- circa_chat_users
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_chat_users`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_chat_users")});

-- circa_inventory_cutoff
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_inventory_cutoff`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_inventory_cutoff")});

-- dim_competitor_price
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_dim_competitor_price`
AS (SELECT * FROM  ${ref("buymed_innovation", "thuocsi_vn_agg_competitor_price")}
    WHERE LOWER(competitor_name) IN ('longchau', 'pharmacity')
);

-- dim_pos
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_dim_pos`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_dim_pos")});


-- dim_product_price
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_dim_product_price`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_dim_product_price")});


-- dim_product_price
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_gross_net_margin`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_gross_net_margin")});

-- flash_sales
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_flash_sales`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_gross_net_margin")});

-- consumer_tracking_events
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_consumer_tracking_events`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_consumer_tracking_events")});

-- retail_unit
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_dim_product_retail_unit`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_dim_product_retail_unit")});

-- -- dim_competitor_price
-- CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_dim_product_competitor_price`
-- AS (SELECT * FROM  ${ref("buymed_innovation", "circa_dim_product_competitor_price")});








