config {
    type:"operations",
    tags: ["AI_CIRCA"]
}

-- fact_order

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_order`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_order")});


-- fact_margin

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_margin`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_margin")});

-- fact_net_margin

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_net_margin`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_net_margin")});

-- fact_target

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_target`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_target")});

-- fact_purchase_order

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_purchase_order`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_purchase_order")});

-- fact_inventory

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_inventory`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_inventory")});

-- fact_order_online

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_fact_order_online`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_fact_order_online")});

-- dim_customer

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_dim_customer`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_dim_customer")});

-- dim_product_sku

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_dim_product`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_dim_product")});

-- agg_inventory

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_agg_inventory`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_agg_inventory")});

-- agg_loss_sale

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_agg_loss_sale`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_agg_loss_sale")});

-- agg_online_leadtime

CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_agg_online_leadtime`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_agg_online_leadtime")});

-- circa_chat_sessions
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_chat_sessions`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_chat_sessions")});

-- circa_chat_users
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_chat_users`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_chat_users")});

-- circa_inventory_cutoff
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_inventory_cutoff`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_inventory_cutoff")});
-- circa_inventory_cutoff
CREATE OR REPLACE VIEW `rumi_buymed_circa.circa_dim_pos`
AS (SELECT * FROM  ${ref("buymed_innovation", "circa_dim_pos")});





