config {
    type: "view",
    tags: ["KPI_FULFILLMENT"]
}

WITH cte_date AS (
  SELECT
    DATETIME_SUB(DATETIME_TRUNC(CURRENT_DATETIME(), MONTH),INTERVAL 2 month ) AS start_date,
    DATETIME_SUB(DATETIME_TRUNC(CURRENT_DATETIME(), MONTH),INTERVAL 3 month ) AS start_date_scan  
  )
,
cte_stage as (
  SELECT * FROM UNNEST (['QC','PACK']) as stage
) 

select
   s.stage
  , pi.mg_id
  , coalesce(p.ticket_id , st.ticket_id) as ticket_id
  , p.status as original_status
  , p.so as parent_code
  , p.warehouse_code as location_code
  , case
    when s.stage = 'QC' then p.qc_id
    when s.stage = 'PACK' then p.pack_id
    else null
  end as pic_id
  , case
    when s.stage = 'QC' then timestamp_add(p.start_qc_time , interval 7 hour)
    when s.stage = 'PACK' then timestamp_add(p.start_pack_time , interval 7 hour)
  end ts_start
  , case
    when s.stage = 'QC' then timestamp_add(p.end_qc_time , interval 7 hour)
    when s.stage = 'PACK' then timestamp_add(p.end_time , interval 7 hour)
  end ts_done
  , pi.sku as sku_code
  , json_value(json_extract_array(pi.location_details)[safe_offset(0)],"$.location_code") as location_shelf
  , case
    when s.stage = 'QC' then pi.fulfilled_quantity
    when s.stage = 'PACK' then pi.fulfilled_quantity
  end qty_start
  , case
    when s.stage = 'QC' then pi.scanned_quantity
    when s.stage = 'PACK' then pi.scanned_quantity
  end qty_done,
from cte_stage as s,
  (
    select *
    from ${source.platinum}.warehouse_prd_picking_pick_ticket
    where created_date >= (select DATE(start_date_scan) from cte_date) 
  ) p 
left join (
  select *
  from ${source.platinum}.warehouse_prd_picking_sub_pick_ticket
  where created_date >= (select DATE(start_date_scan) from cte_date) 
) as st on p.ticket_id = st.pick_ticket_id and st.status in ('MERGED','DONE')
left join (
  select *
  from ${source.platinum}.warehouse_prd_picking_pick_ticket_item
  where created_date >= (select DATE(start_date_scan) from cte_date) 
) pi on p.ticket_id = pi.ticket_id
where coalesce(end_qc_time, end_pick_time) >= (select timestamp(start_date) from cte_date)