config {
    type: "table", 
    description: 
        `
        Workflow Ticket;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.platinum}.platform_organization_prd_workflow_task_instance,
            ${source.platinum}.platform_organization_prd_workflow_request_manager
        `,
    tags: ["custom_1h_past5"]
}



WITH 
    cte_main AS (
        SELECT 
            a.task_instance_code
            , a.name AS step_name
            , a.workflow_instance_code
            , a.request_code
            , b.name as request_name
            , a.workflow_code
            , b.workflow_name
            , b.created_date
            , DATE(TIMESTAMP_ADD(b.completed_time, INTERVAL 7 HOUR)) AS completed_date
            , a.status as task_status
            , b.status as request_status
            , a.step_no
            , a.step_title
            , a.input_data
            , a.metadata
            , a.comment
        FROM ${source.platinum}.platform_organization_prd_workflow_task_instance AS a 
            LEFT JOIN ${source.platinum}.platform_organization_prd_workflow_request_manager AS b ON a.request_code = b.request_code
        WHERE
            a.workflow_code IN ("WF1090", "WF1088", "WF1095")
        QUALIFY ROW_NUMBER() OVER (_window) = 1
        WINDOW _window AS (
            PARTITION BY a.request_code 
            ORDER BY a.step_no DESC
        )
    )

    , cte_parsed AS (
        SELECT
            a.*  EXCEPT (input_data, metadata)
            , JSON_EXTRACT_SCALAR(a.metadata, "$.assignee_email") AS agent_email
            , IFNULL( SAFE_CAST(JSON_EXTRACT_SCALAR(a.input_data, "$.customerID") AS INT64), -1) AS customer_id
            , LPAD(JSON_EXTRACT_SCALAR(a.input_data, "$.customer_phone"), 10, '0') AS phone
            , COALESCE(
                JSON_EXTRACT_SCALAR(a.input_data, "$.reason1")
                , JSON_EXTRACT_SCALAR(a.input_data, "$.reason2") 
                , JSON_EXTRACT_SCALAR(a.input_data, "$.reason3") 
                , JSON_EXTRACT_SCALAR(a.input_data, "$.reason4") 
                , JSON_EXTRACT_SCALAR(a.input_data, "$.reason5") 
                , JSON_EXTRACT_SCALAR(a.input_data, "$.result") 
                , "..."
              ) AS reason_key
            , JSON_EXTRACT_SCALAR(a.input_data, "$.customer_address") as address
            , JSON_EXTRACT_SCALAR(a.input_data, "$.area") as region
        FROM cte_main AS a
    )

SELECT 
    a.*
    , cus.customer_id AS customer_id_mapping
    , cus.customer_phone
    , cus.customer_name
    , cus.first_purchase AS first_order_at
    , cus.last_purchase AS last_order_at
    , MIN(IF(o.order_status <> 'CANCEL', o.created_at, NULL)) AS first_order_aft_care
FROM cte_parsed AS a
    LEFT JOIN ${ref('dim_customer')} AS cus ON a.phone = cus.customer_phone
    LEFT JOIN ${ref('fact_order')} AS o
        ON o.customer_id = cus.customer_id
            AND o.created_at >= DATE_SUB(a.created_date, INTERVAL 7 DAY)
GROUP BY ALL