config {
    type: "table", 
    description: 
        `
        Workflow Ticket;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.platinum}.marketplace_prd_product_v2_product_market_price
        `,
    tags: ["custom_1h_past5"]
}

WITH 
    cte_main AS (
        SELECT 
            a.task_instance_code
            , a.workflow_instance_code
            , a.request_code
            , b.name as request_name
            , a.workflow_code
            , a.created_date
            , a.status as task_status
            , b.status as request_status
            , a.step_no
            , a.step_title
            , a.input_data
            , a.metadata
            , a.comment
        FROM ${source.platinum}.platform_organization_prd_workflow_task_instance AS a 
            LEFT JOIN ${source.platinum}.platform_organization_prd_workflow_request_manager AS b ON a.request_code = b.request_code
        WHERE
            a.workflow_code IN ("WF1090", "WF1088", "WF1095")
        QUALIFY ROW_NUMBER() OVER (_window) = 1
        WINDOW _window AS (
            PARTITION BY a.request_code 
            ORDER BY a.step_no DESC
        )
    )

    , cte_parsed AS (
        SELECT
            a.*
            , JSON_EXTRACT_SCALAR(a.metadata, "$.assignee_email") AS agent_email
            , IFNULL( SAFE_CAST(JSON_EXTRACT_SCALAR(a.input_data, "$.customerID") AS INT64), -1) AS customer_id
            , LPAD(JSON_EXTRACT_SCALAR(a.input_data, "$.customer_phone"), 10, '0') AS lead_phone
            , COALESCE(
                JSON_EXTRACT_SCALAR(a.input_data, "$.reason1")
                , JSON_EXTRACT_SCALAR(a.input_data, "$.reason2") 
                , JSON_EXTRACT_SCALAR(a.input_data, "$.reason3") 
                , JSON_EXTRACT_SCALAR(a.input_data, "$.reason4") 
                , JSON_EXTRACT_SCALAR(a.input_data, "$.reason5") 
                , "..."
              ) AS reason_key
            , JSON_EXTRACT_SCALAR(a.input_data, "$.customer_address") as lead_address
            , JSON_EXTRACT_SCALAR(a.input_data, "$.area") as lead_region
        FROM cte_main AS a
    )

SELECT 
    a.*
    , cus.customer_id
    , cus.customer_phone
    , cus.customer_name
    , cus.first_order_at
    , cus.last_order_at
FROM cte_parsed AS a
LEFT JOIN ${ref('dim_customer')} AS cus ON a.lead_phone = cus.customer_phone