config {
    type: "incremental",
    description: 
        `
        Log of changing status of a SO;
        PIC: nguyen.tran; 
        Type: Table; 
		Refresh Schedule: hourly; 
        Source: 
            ${source.platinum}.integration_prd_tpl_callback_callback
        `,
    tags: ["custom_1h_past5"],
    columns: {
        transformed_at: 'Thời gian transform dữ liệu',
        so_code: 'Mã SO',
        tracking_code: 'Mã theo dõi giao vận',
        delivery_status: 'Trạng thái của một mã vận đơn',
        status_name: 'Tên trạng thái của một mã vận đơn',
        delivery_ts: 'Thời gian ghi nhận trạng thái'
    }, 

    bigquery: {
        partitionBy: "DATE(delivery_ts)",
        clusterBy: ["so_code"]
    }
}

pre_operations {
    ${
        when(incremental(),
        `
        DECLARE new_records ARRAY<STRING>;
        DECLARE checkpoint_date ARRAY<DATE>;
        DECLARE checkpoint_delivery DATE;
        SET (new_records, checkpoint_date, checkpoint_delivery) = (
            SELECT AS STRUCT
                ARRAY_AGG(DISTINCT so) AS new_records,
                ARRAY_AGG(DISTINCT created_date) AS checkpoint_date,
                MIN(created_date) AS checkpoint_delivery
            FROM platinum_buymed_vn.integration_prd_tpl_callback_callback 
            WHERE created_date >= date_trunc(date_sub(current_date(),interval 7 month), month)
                AND last_updated_time >= CURRENT_TIMESTAMP() - INTERVAL 2 HOUR);
        
        DELETE FROM ${self()}
        WHERE so_code IN UNNEST(new_records);

        `

    )}
}

with cte_date as (
	select  date_trunc(date_sub(current_date(),interval 7 month), month) as date_scan_2
)

, cte_data as (
	select so,
		action_time,
		tpl_code,
		status,
		status_name,
		logs,
        hub_code
	from ${source.platinum}.integration_prd_tpl_callback_callback
	where 
        ${when(incremental(), 
        `created_date IN UNNEST(checkpoint_date) 
        AND created_date >= checkpoint_delivery
        AND so IN UNNEST(new_records)`
        , 
        `created_date >= (select date_scan_2 from cte_date)`
        )}
)

select  
    TIMESTAMP_ADD(current_timestamp(),interval 7 hour) as transformed_at,
	so as so_code, 
	tpl_code as tracking_code,
	status as delivery_status,
	status_name,
	timestamp_add(action_time, interval 7 hour) as delivery_ts,
    hub_code
from cte_data

union all

select 
    TIMESTAMP_ADD(current_timestamp(),interval 7 hour) as transformed_at,
	a.so as so_code, 
	json_value(b,"$.tpl_code") as tracking_code,
    json_value(b,"$.status") as delivery_status,
    json_value(b,"$.status_name") as status_name,
    timestamp_add(timestamp(json_value(b,"$.action_time")), interval 7 hour) as delivery_ts,
    json_value(b,"$.hub_code") as hub_code
from cte_data a
left join unnest(json_extract_array(a.logs)) b