
config {
    type: "incremental",
    name: "marketplace_prd_customer_log",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id'
    },
    tags:["custom_1h_past5"],
    bigquery: {
        partitionBy: "created_date"
    }
}


SELECT
 *,
 DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh')) as created_date
FROM ${source.silver}.marketplace_prd_customer_log o 
  ${ when(incremental(), `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()})`)}
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC)


