config {
    type: "incremental",
    name: "marketplace_prd_customer_request_license",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id',
        nonNull: ["created_date"]
    },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["platinum_custom_1h_past7","marketplace_prd_customer"]
}

pre_operations {
  ${
    when(incremental(),
      `
        # Incremental
        DECLARE has_new_data BOOLEAN;
        DECLARE has_delete_data BOOLEAN;
        DECLARE Ingest_checkpoint TIMESTAMP;
        DECLARE checkpoint_date ARRAY<date>;
        
        SET Ingest_checkpoint = (
            SELECT max(ingest_time)  - INTERVAL 1 HOUR  
            FROM ${self()}
            WHERE created_date >= CURRENT_DATE() - INTERVAL 1 MONTH
        );
        IF Ingest_checkpoint IS NULL THEN 
            SET Ingest_checkpoint = (
                SELECT max(ingest_time)  - INTERVAL 1 HOUR  FROM ${self()}
            );
        END IF;

        SET ( has_new_data, checkpoint_date, has_delete_data ) = (
            SELECT AS STRUCT
                IF (
                    COUNT(*) > 0 , TRUE, FALSE
                ) has_new_data,
                /*
                    has_new_data describe the existance of data after the last refresh time of platinum
                */
                ARRAY_AGG(
                    DISTINCT IF(created_time is NULL, "2099-01-01" , DATE( DATETIME(created_time,'Asia/Ho_Chi_Minh') ) )
                ) AS checkpoint_date,
                COUNTIF( action = 'd' ) > 0 AS has_delete_data
            FROM silver_buymed_vn.marketplace_prd_customer_request_license
            WHERE ingest_time > Ingest_checkpoint
        );

        CREATE TEMP TABLE new_records AS (
          SELECT DISTINCT mg_id
          FROM silver_buymed_vn.marketplace_prd_customer_request_license
          WHERE ingest_time > Ingest_checkpoint
        );

        IF ( has_new_data = TRUE ) THEN
            IF (has_delete_data = TRUE) THEN
              -- if has deleted, then we must get created_date of old data from platinum
              -- In silver, delete event doesn't store created_time
              -- So this step is required
              SET checkpoint_date = ARRAY(
                SELECT DISTINCT created_date
                FROM ${self()}
                WHERE mg_id IN (SELECT mg_id FROM new_records)
              );
            END IF;

            DELETE FROM ${self()}
            WHERE
                created_date IN UNNEST(checkpoint_date)
                AND mg_id IN (SELECT mg_id FROM new_records)
            ;
        ELSE
            SET Ingest_checkpoint = TIMESTAMP("2099-01-01T00:00:00");
        END IF ;
      `      
    )
  }
}

WITH over_tbl AS (
    SELECT
        mg_id,
        ARRAY_AGG(
            key 
            ORDER BY
                synced_at DESC,
                last_updated_time DESC
            LIMIT 1
        )[0] key ,
        ARRAY_AGG(
            action 
            ORDER BY
                synced_at DESC,
                last_updated_time DESC
            LIMIT 1
        )[0] action
    FROM silver_buymed_vn.marketplace_prd_customer_request_license
    ${when(incremental(),  `
    WHERE ingest_time > Ingest_checkpoint - INTERVAL 2 HOUR
    AND mg_id IN (SELECT n.mg_id FROM new_records n)
    ` )}
    GROUP BY mg_id HAVING action != "d"
)
SELECT
    *,
    CASE
        WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
        ELSE DATE( '2099-01-01' )
    END AS created_date,
    CURRENT_DATETIME() AS platinum_refresh
FROM silver_buymed_vn.marketplace_prd_customer_request_license
WHERE key IN (SELECT o.key FROM over_tbl o)
${when(incremental(),  `
    AND ingest_time > Ingest_checkpoint - INTERVAL 2 HOUR
    ` )}