config {
    type: "table",
    description: `circa_tracking
                  PIC: huyen.ngo & ha.lekim; 
                  model_type: Table ;
                  schedule: Every 20 mins`,
    tags:  ["gold_custom_20m"],
    name: "circa_agg_tracking",
    columns: {
    }
    
    ,bigquery: {
        partitionBy: "created_date"
    }
}
WITH
  fact_order_item AS (
       SELECT
           i.order_code
           , CASE
               WHEN COUNTIF(i.gift_code IS NOT NULL) > 0
                 OR COUNTIF(i.owner_name = 'CIRCA_MARKETING' OR i.owner_name = 'MARKETING') > 0
               THEN true
               ELSE false
           END AS is_have_voucher
           ,SUM(
               CASE
                   WHEN i.gift_code IS NULL THEN i.unit_price_before_discount * i.quantity_po
                   ELSE 0
               END
           ) AS gmv
       FROM  ${ref("gold_buymed_vn2", "fact_fin_circa_order_item")} i
       GROUP BY ALL
)
,  fact_order AS (
  SELECT
    o.created_date
    , CASE WHEN i.customer_phone IS NULL
                      OR i.customer_phone = ''
                      OR i.customer_phone = '0'
                      OR i.customer_phone = '000000000'
                      OR i.customer_phone = '0000000001'
                      OR i.customer_phone = '000000001'
                      THEN i.order_code ELSE i.customer_phone END AS customer_id
    ,EXTRACT(HOUR FROM o.created_at) AS created_hour
    ,o.created_at
    ,o.pos_id
    ,o.client_id
    ,o.order_code
    ,o.status
    ,o.type AS channel
    ,voucher_code
    ,SUM( total_order_discount_amount + total_loyalty_discount_amount ) AS voucher_discount
    ,SUM( external_discount_amount  ) AS external_discount_amount
 FROM  ${ref("gold_buymed_vn2", "fact_fin_circa_order")} o 
 LEFT JOIN ${ref("gold_buymed_vn2", "cos_fact_order")} i ON o.order_id = i.order_id
  WHERE o.status NOT IN ('RETURNED', 'FAILED_SHIPMENT', 'OUT_OF_STOCK','CANCELED' )
  GROUP BY ALL ) 
 
  SELECT
     o.created_date
   , o.created_at
   , customer_id
  -- , o.pos_id
   , o.client_id
   , e.client_name
   , p.code AS pos_code
   , p.name AS pos_name
   , IF (p.type = 'FS', 'FS', 'COS') AS pos_type
   , o.order_code
   , o.status
   , o.channel
   , ROUND(gmv) AS gmv
    , CASE WHEN voucher_code IS NOT NULL
               OR is_have_voucher= true THEN true 
          ELSE false 
     END AS is_have_voucher
    , CASE
           WHEN customer_id IS NULL THEN TRUE
           WHEN ROW_NUMBER() OVER (
               PARTITION BY customer_id
               ORDER BY o.created_at 
           ) = 1 THEN TRUE
           ELSE FALSE
      END AS is_first_order
    , CASE
           WHEN customer_id IS NULL THEN TRUE
           WHEN ROW_NUMBER() OVER (
               PARTITION BY customer_id, channel
               ORDER BY o.created_at 
           ) = 1 THEN TRUE
           ELSE FALSE
      END AS is_first_channel_order
    ,TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) AS refresh_at
  FROM fact_order_item AS i
  INNER JOIN fact_order o ON i.order_code = o.order_code 
  LEFT JOIN  ${ref("gold_buymed_vn2", "circa_pos_profile")} AS p ON o.pos_id = p.id
  LEFT JOIN ${ref("gold_buymed_vn2", "circa_dim_entity_client")} e ON o.client_id = e.client_id
   WHERE o.client_id NOT IN (5,6,7)
     AND  o.pos_id NOT IN ( '0afdb831-b60d-4254-8822-df13e39c90e7')
  GROUP BY ALL
  