config {
    type: "table",
    description: `circa_fact_net_margin
                  PIC: huyen.ngo & ha.lekim; 
                  model_type: Table ;
                  schedule: At minute 30 every hour`,
    tags:  ["gold_custom_20m"],
    name: "circa_fact_net_margin",
    columns: {
    }
    
    ,bigquery: {
        partitionBy: "DATE_TRUNC(created_date,month)"
    }
}

WITH fact_order_item AS (
    SELECT
      completed_date,
      created_date,
      completed_hour,
      created_hour,
      pos_id,
      affiliate_pos_id,
      client_id,
      order_code,
      order_id,
      status,
      channel,
      affiliate_tag,
      product_id,
      sku_code,
      COALESCE(SUM(gmv),0) gmv,
      COALESCE(SUM(cogs_circa),0) cogs_circa,
      COALESCE(SUM(voucher_discount),0) + COALESCE(SUM(total_loyalty_discount_amount),0) + COALESCE(SUM(deal_1k_amount),0) + COALESCE(SUM(external_discount_amount),0) AS voucher_circa,
      COALESCE(SUM(order_discount_product),0) as voucher_product,
      COALESCE(SUM(discount_deal),0) AS deal,
      COALESCE(SUM(cogs_mkt_circa),0) AS voucher_gift_circa
    FROM
      ${ref("gold_buymed_vn2", "fact_circa_margin_item")}
    WHERE
      order_code IS NOT NULL
    GROUP BY
      ALL )
    , fact_return_item as (
        select 
        completed_date,
        order_id,
        product_id,
        sku_code,
        sum(return_amount) as return_amount,
        SUM(cogs_circa_return) as cogs_circa_return,
        SUM(voucher_gift_circa_return) AS voucher_gift_circa_return,
        sum(deal_return) deal_return,
        sum(voucher_circa_return) voucher_circa_return,
        sum(order_discount_product) voucher_product_return
      FROM ${ref("gold_buymed_vn2", "fact_circa_margin_return_item")}
      GROUP BY ALL
    )
  , final as (
    select a.*,
    b.completed_date as completed_return_date,
    coalesce(b.return_amount,0) as return_amount,
    coalesce(b.cogs_circa_return,0) as cogs_circa_return,
    coalesce(b.deal_return,0) as deal_return,
    coalesce(b.voucher_circa_return,0) as voucher_circa_return,
    coalesce(b.voucher_gift_circa_return,0) as voucher_gift_circa_return,
    coalesce(b.voucher_product_return,0 ) voucher_product_return,
    a.gmv - a.deal - a.voucher_circa - coalesce(b.return_amount,0) as net_revenue,
    a.gmv - a.deal - a.voucher_circa - coalesce(b.return_amount,0) - a.cogs_circa + coalesce(b.cogs_circa_return,0)
        as gross_profit_circa,
    a.gmv - a.deal - a.voucher_circa - coalesce(b.return_amount,0) - a.cogs_circa + coalesce(b.cogs_circa_return,0) - a.voucher_gift_circa + coalesce(b.voucher_gift_circa_return,0)
        as net_profit_circa
    from fact_order_item a
    left join fact_return_item b 
    on a.order_id = b.order_id
    and a.product_id = b.product_id
    and a.sku_code = b.sku_code
  )
  SELECT
    a.completed_date,
    a.completed_return_date,
    a.completed_hour,
    a.created_date,
    a.created_hour,
    a.client_id,
    p.code AS pos_code,
    p.name AS pos_name,
    p_1.code as affiliate_pos_code,
    p_1.name as affiliate_pos_name,
  IF
    (p.type = 'FS', 'FS', 'COS') AS pos_type,
    a.order_code,
    a.status,
    a.channel,
    a.affiliate_tag,
    a.product_id,
    a.sku_code,
    dim_product.product_name,
    dim_product.brand,
    CASE 
      WHEN dim_product.brand_type LIKE '%BRAND%NAME%' THEN 'BRANDNAME'
      WHEN dim_product.brand_type LIKE '%BRAND%GENERIC%' THEN 'BRAND_GENERIC'
      WHEN dim_product.brand_type = 'PORTFOLIO' THEN 'BUYMED SELECTED'
      WHEN dim_product.brand_type = 'MARKET_PLACE' THEN 'HIGH MARGIN'
    ELSE dim_product.brand_type END AS brand_type,
    dim_product.product_category,
    dim_product.cat2,
    dim_product.cat3,
    dim_product.cat4,
    a.gmv,
    a.deal,
    a.voucher_circa,
    a.return_amount,
    a.cogs_circa_return,
    a.deal_return,
    a.voucher_product,
    a.voucher_circa_return,
    a.voucher_gift_circa_return,
    a.voucher_product_return,
    a.net_revenue,
    a.cogs_circa,
    a.gross_profit_circa,
    safe_divide(a.gross_profit_circa, a.net_revenue) as gross_margin_circa,
    a.voucher_gift_circa,
    a.net_profit_circa,
    safe_divide(a.net_profit_circa, a.net_revenue) as net_margin_circa,
    CONCAT(a.client_id, "_", a.product_id) AS product_id_key,
    CONCAT(a.order_code, CONCAT(a.client_id, "_", a.product_id)) AS order_product_unit_key,
    TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) AS refresh_at
  FROM
    final AS a
  LEFT JOIN ${ref("gold_buymed_vn2", "circa_pos_profile")} AS p ON a.pos_id = p.id
  LEFT JOIN ${ref("gold_buymed_vn2", "circa_pos_profile")} AS p_1 ON a.affiliate_pos_id = p_1.id
  LEFT JOIN ${ref("gold_buymed_vn2", "cos_dim_product")} AS dim_product 
  on a.product_id = dim_product.product_id 
  and a.client_id = dim_product.client_id
   WHERE a.client_id NOT IN (5,6,7)
   and a.created_date >= date_sub(date_trunc(current_date(),month), interval 12 month) 