config {
    type: "table",
    description: `circa_fact_net_margin
                  PIC: huyen.ngo & ha.lekim; 
                  model_type: Table ;
                  schedule: At minute 30 every hour`,
    tags:  ["gold_custom_20m"],
    name: "circa_fact_net_margin",
    columns: {
    }
    
    ,bigquery: {
        partitionBy: "created_date"
    }
}

WITH base_data AS (
    SELECT
      completed_date,
      created_date,
      completed_hour,
      created_hour,
      pos_id,
      client_id,
      order_code,
      status,
      channel,
      product_id,
      COALESCE(SUM(gmv),0) gmv,
      COALESCE(SUM(cogs_circa),0) cogs_circa,
      COALESCE(SUM(cogs_circa*0.03),0) rebate,
      COALESCE(SUM(voucher_discount),0) + COALESCE(SUM(total_loyalty_discount_amount),0) + COALESCE(SUM(deal_1k_amount),0) + COALESCE(SUM(external_discount_amount),0) AS voucher_circa,
      COALESCE(SUM(discount_deal),0) AS deal,
      COALESCE(SUM(cogs_mkt_circa),0) AS voucher_gift_circa
    FROM
      ${ref("gold_buymed_vn2", "fact_circa_margin_item")}
    WHERE
      order_code IS NOT NULL
    GROUP BY
      ALL )
, final as (
  select 
  *,
  a.gmv - a.deal - a.voucher_circa as net_revenue,
  a.gmv - a.deal - a.voucher_circa - a.cogs_circa + a.rebate AS gross_profit_circa,
  a.gmv - a.deal - a.voucher_circa - a.cogs_circa + a.rebate - a.voucher_gift_circa as net_profit_circa
  from base_data a
)
  SELECT
    a.completed_date,
    a.completed_hour,
    a.created_date,
    a.created_hour,
    a.client_id,
    p.code AS pos_code,
    p.name AS pos_name,
  IF
    (p.type = 'FS', 'FS', 'COS') AS pos_type,
    a.order_code,
    a.status,
    a.channel,
    a.product_id,
    a.gmv,
    a.deal, 
    a.voucher_circa,
    a.net_revenue,
    a.cogs_circa,
    a.rebate,
    a.gross_profit_circa,
    SAFE_DIVIDE(a.gross_profit_circa, a.net_revenue) AS gross_margin_circa,
    a.net_profit_circa,
    SAFE_DIVIDE(a.net_profit_circa, a.net_revenue) AS net_margin_circa,
    CONCAT(a.client_id, "_", a.product_id) AS product_id_key,
    CONCAT(a.order_code, CONCAT(a.client_id, "_", a.product_id)) AS order_product_unit_key,
    TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) AS refresh_at
  FROM
    final AS a
  LEFT JOIN
    ${ref("gold_buymed_vn2", "circa_pos_profile")} AS p ON a.pos_id = p.id
   WHERE a.client_id NOT IN (5,6,7)