config {
    type: "view",
    description: "PIC: huong.dang",
    tags: ['STRATEGIC-REPORTING'],
}

SELECT 
    CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    "THAILAND" AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER_ACTIVE_ENTERPRISE' AS measure,
    CAST(NULL AS STRING) AS supplier_class,
    COUNT(distinct IF(active_customer <> 0, customer_id,NULL)) value

FROM lakehouse-prod-394907.gold_buymed_th.dim_customer_profiling dcp 
LEFT JOIN lakehouse-prod-394907.gold_buymed_th.dim_calendar dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5

UNION ALL 

SELECT 
    CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    "THAILAND" AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER_NEW_ENTERPRISE' AS measure,
    CAST(NULL AS STRING) AS supplier_class,
    COUNT(distinct IF(new_customer <> 0, customer_id,NULL)) value

FROM lakehouse-prod-394907.gold_buymed_th.dim_customer_profiling dcp 
LEFT JOIN lakehouse-prod-394907.gold_buymed_th.dim_calendar dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5

UNION ALL 

SELECT 
    CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    "THAILAND" AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER_REACQUIRED_ENTERPRISE' AS measure,
    CAST(NULL AS STRING) AS supplier_class,
    COUNT(distinct IF(reacquire_customer <> 0, customer_id,NULL)) value

FROM lakehouse-prod-394907.gold_buymed_th.dim_customer_profiling dcp 
LEFT JOIN lakehouse-prod-394907.gold_buymed_th.dim_calendar dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5

UNION ALL 

SELECT 
    CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    "THAILAND" AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER_REPEAT_ENTERPRISE' AS measure,
    CAST(NULL AS STRING) AS supplier_class,
    COUNT(distinct IF(repeat_customer <> 0, customer_id,NULL)) value

FROM lakehouse-prod-394907.gold_buymed_th.dim_customer_profiling dcp 
LEFT JOIN lakehouse-prod-394907.gold_buymed_th.dim_calendar dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5