config {
  type: "operations",
  tags: ["00h00"]
}
CREATE OR REPLACE ROW ACCESS POLICY
  access_high_security
ON
    collector.data_prd GRANT TO (
        "user:hau.lecong@buymed.com",
        "user:nguyen.tran@buymed.com",
        "serviceAccount:nguyen-tran-service-account@lakehouse-prod-394907.iam.gserviceaccount.com",
        "serviceAccount:nguyen-tran-service-account-2@lakehouse-prod-394907.iam.gserviceaccount.com",
        "user:minh.luugia@buymed.com",

        "serviceAccount:warehousing-finance-dataform@lakehouse-prod-394907.iam.gserviceaccount.com"
        "serviceAccount:collector@lakehouse-prod-394907.iam.gserviceaccount.com"

    )
FILTER USING
( 
TRUE
);


CREATE OR REPLACE ROW ACCESS POLICY 
  medium_security
ON 
collector.data_prd GRANT TO (
    "user:huong.dang@buymed.com",
    "user:huyen.ngo@buymed.com",

    "user:chien.le@buymed.com",
    "user:trinh.nguyenbao@buymed.com",
    "user:thach.nguyenngoc@buymed.com",
    "user:ha.lekim@buymed.com",
    "user:khanh.nguyenhung@buymed.com",

    "user:panida.t@buymed.com",

    "serviceAccount:warehousing-dataform@lakehouse-prod-394907.iam.gserviceaccount.com",
    "serviceAccount:buymed-transformation-dataform@lakehouse-prod-394907.iam.gserviceaccount.com",
    "serviceAccount:staging-dataform-2@lakehouse-prod-394907.iam.gserviceaccount.com",
    "serviceAccount:staging-dataform-3@lakehouse-prod-394907.iam.gserviceaccount.com",
    "serviceAccount:staging-dataform@lakehouse-prod-394907.iam.gserviceaccount.com",

    "serviceAccount:warehousing-dataform@lakehouse-prod-394907.iam.gserviceaccount.com",
    "serviceAccount:warehousing-sub-dataform@lakehouse-prod-394907.iam.gserviceaccount.com",
    "serviceAccount:service-231189618019@gcp-sa-dataform.iam.gserviceaccount.com"
)
FILTER USING (
object not like "EXPENSE"
);