config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "platform_billing_prd_invoice_v2_log_hilo_factory_client",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","platform_billing_prd_invoice-v2"]
}

WITH silver AS (
    SELECT 
        key,
        mg_id,
        req_url,
        caller,
        req_header,
        req_form_data,
        created_time,
        keys,
        date,
        last_updated_time,
        status,
        req_method,
        req_body,
        total_time,
        results,
        synced_at,
        extra_props,
        action,
        ingest_time
        ,CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END AS created_date
        , CAST( null AS DATETIME) 
        
    FROM ${source.silver}.platform_billing_prd_invoice_v2_log_hilo_factory_client
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
        AND FIRST_VALUE(action) OVER(_window) != "d"
        AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
        WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC,
        IF
            (action='d',3,
            IF
            (action='u',2,1)) DESC,
        last_updated_time DESC)
), platinum AS (
    SELECT 
        key,
        mg_id,
        req_url,
        caller,
        req_header,
        req_form_data,
        created_time,
        keys,
        date,
        last_updated_time,
        status,
        req_method,
        req_body,
        total_time,
        results,
        synced_at,
        extra_props,
        action,
        ingest_time
        , created_date 
        , platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`,`platform_billing_prd_invoice_v2_log_hilo_factory_client`) }
)

SELECT p.*
FROM platinum p
LEFT JOIN silver s 
    ON p.mg_id = s.mg_id 
WHERE s.mg_id is null 

UNION ALL 

SELECT s.*
FROM silver s

-- SELECT *
-- FROM (
--     SELECT *
--     FROM platinum 
--     UNION ALL 
--     SELECT *
--     FROM  silver 
-- )
-- QUALIFY ROW_NUMBER() OVER (_window) = 1
--     AND FIRST_VALUE(action) OVER (_window ) != "d"
-- WINDOW _window AS (
-- PARTITION BY mg_id
-- ORDER BY synced_at DESC,
-- IF
--     (action='d',3,
--     IF
--     (action='u',2,1)) DESC,
--     last_updated_time DESC)
