config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "seller_prd_promotion_log_price_after_rebate",
    description : `
    PIC: minh.luu
    Partition by: created date
    Cluster by: "vendor_code", "warehouse_code","product_code","version"
    `,
    tags:["platinum","seller_prd_promotion_log"]
}

  WITH silver AS (
    SELECT
      key,mg_id,contract_price_code,product_code,vendor_code,version,warehouse_code,adhoc_promotion,contract_price_id,created_time,discount,fixed_promotion,fomular,last_updated_time,price_after_rebate,price_after_rebate_with_adhoc_promotion,price_after_vat,price_contract,product_id,product_name,rebate,vat,adhoc_promotion_codes,fixed_promotion_codes,rebate_codes,vendor_code_applied,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.seller_prd_promotion_log_price_after_rebate
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,contract_price_code,product_code,vendor_code,version,warehouse_code,adhoc_promotion,contract_price_id,created_time,discount,fixed_promotion,fomular,last_updated_time,price_after_rebate,price_after_rebate_with_adhoc_promotion,price_after_vat,price_contract,product_id,product_name,rebate,vat,adhoc_promotion_codes,fixed_promotion_codes,rebate_codes,vendor_code_applied,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `seller_prd_promotion_log_price_after_rebate`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
