config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_inbound_put_ticket_item",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","warehouse_prd_inbound"]
}


SELECT 
    *,
    CASE
        WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
        ELSE DATE( '2099-01-01' )
    END
    created_date
FROM ${source.silver}.warehouse_prd_inbound_put_ticket_item
QUALIFY ROW_NUMBER() OVER (_window) = 1 
WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
    IF
        (action='d',3,
        IF
        (action='u',2,1)) DESC
    ,last_updated_time DESC)



