config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_inventory_transfer",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","warehouse_prd_inventory"]
}

WITH silver AS (
    SELECT 
        key, mg_id, transfer_id, code, created_by, created_by_name, created_time, destination_location, done_auto, in_main, in_warehouse, last_updated_time, out_main, out_warehouse, reference, references, request_id, sort_queue_value, source_location, status, transfer_created_time, type, version_no, warehouse_code, completed_by, completed_by_name, transfer_finish_time, without_queue, synced_at, extra_props, action, ingest_time
        ,CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END AS created_date
        , CAST( null AS DATETIME) 
        
    FROM ${source.silver}.warehouse_prd_inventory_transfer
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
        AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
    WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC,
        IF
            (action='d',3,
            IF
            (action='u',2,1)) DESC,
    last_updated_time DESC)
), platinum AS (
    SELECT
        key, mg_id, transfer_id, code, created_by, created_by_name, created_time, destination_location, done_auto, in_main, in_warehouse, last_updated_time, out_main, out_warehouse, reference, references, request_id, sort_queue_value, source_location, status, transfer_created_time, type, version_no, warehouse_code, completed_by, completed_by_name, transfer_finish_time, without_queue, synced_at, extra_props, action, ingest_time
        , created_date 
        , platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`,`warehouse_prd_inventory_transfer`) }
)

SELECT p.*
FROM platinum p
LEFT JOIN silver s 
    ON p.mg_id = s.mg_id 
WHERE s.mg_id is null 

UNION ALL 

SELECT s.*
FROM silver s
WHERE action <> "d"
