config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_picking_sub_pick_ticket",
    description : `
    PIC: minh.luu
    Partition by: created date
    Cluster by: ["ticket_id","pick_ticket_id"]
    `,
    tags:["platinum","warehouse_prd_picking"]
}
 
  WITH silver AS (
    SELECT
      key, mg_id, weights, version_no, type, zone, scheduled_date, created_time, ticket_id, warehouse_code, total_item, sale_order_code, tags, pick_ticket_id, priority, total_sku, status, last_updated_time, employee, employee_id, start_time, baskets, updated_by, end_time, merged_time, synced_at, extra_props, action, ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.warehouse_prd_picking_sub_pick_ticket
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
        AND NOT (action = 'd' AND ingest_time BETWEEN '2026-04-19 17:00:00' AND '2026-04-26 17:00:00')
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key, mg_id, weights, version_no, type, zone, scheduled_date, created_time, ticket_id, warehouse_code, total_item, sale_order_code, tags, pick_ticket_id, priority, total_sku, status, last_updated_time, employee, employee_id, start_time, baskets, updated_by, end_time, merged_time, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_picking_sub_pick_ticket`)}
  )
SELECT p.*
FROM platinum p
WHERE NOT EXISTS (SELECT 1 FROM silver s WHERE s.mg_id = p.mg_id)

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  