config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_picking_sub_pick_ticket_item",
    description : `
    PIC: minh.luu
    Partition by: created date
    Cluster by: ["ticket_id","pick_ticket_id"]
    `,
    tags:["platinum","warehouse_prd_picking"]
}
 
  WITH silver AS (
    SELECT
      key, mg_id, unit, warehouse_code, line_id, sku, is_external_seller, is_combo, pick_quantity, status, pick_ticket_id, weight, packaging, is_red_tag, quantity, details, ticket_id, name, redundant_picked_quantity, version_no, created_time, product_type, image_url, product_id, seller_code, tags, sale_order_code, pick_line_id, is_link, location_details, last_updated_time, updated_by, is_fragile, synced_at, extra_props, action, ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.warehouse_prd_picking_sub_pick_ticket_item
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
        AND NOT (action = 'd' AND ingest_time BETWEEN '2026-04-19 17:00:00' AND '2026-04-26 17:00:00')
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key, mg_id, unit, warehouse_code, line_id, sku, is_external_seller, is_combo, pick_quantity, status, pick_ticket_id, weight, packaging, is_red_tag, quantity, details, ticket_id, name, redundant_picked_quantity, version_no, created_time, product_type, image_url, product_id, seller_code, tags, sale_order_code, pick_line_id, is_link, location_details, last_updated_time, updated_by, is_fragile, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_picking_sub_pick_ticket_item`)}
  )
SELECT p.*
FROM platinum p
WHERE NOT EXISTS (SELECT 1 FROM silver s WHERE s.mg_id = p.mg_id)

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  