config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_picking_task_item",
    description : `
    PIC: minh.luu
    Partition by: created date
    Cluster by: ["seller_code","sku","task_id","line_id"]
    `,
    tags:["platinum","warehouse_prd_picking"]
}
 
  WITH silver AS (
    SELECT
      key,mg_id,created_time,line_id,pick_ticket_line_id,product_id,name,weight,details,task_id,sku,seller_code,packaging,demand_quantity,processed_quantity,last_updated_time,pick_result,location_details,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.warehouse_prd_picking_task_item
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,created_time,line_id,pick_ticket_line_id,product_id,name,weight,details,task_id,sku,seller_code,packaging,demand_quantity,processed_quantity,last_updated_time,pick_result,location_details,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_picking_task_item`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  