config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_inventory_sku",
    description : `
    PIC: minh.luu
    Partition by: created date
    Cluster by: status
    `,
    tags:["platinum","warehouse_prd_inventory"]
}


WITH silver AS (
    SELECT
      key, mg_id, sku, warehouse_code, admin_id, available_quantity, created_time, image_url, keyword, missing_quantity, name, on_hold_quantity, packaging, product_code, product_id, seller_code, status, stock_quantity, version_no, last_updated_time, updated_by, min_quantity, is_draft, is_pending, is_ignore, unit, product_type, height, image_urls, is_fragile, is_frozen, length, weight, width, is_liquid, is_portable, max_quantity, is_full_package, synced_at, extra_props, action, ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.warehouse_prd_inventory_sku
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
      AND NOT (action = 'd' AND ingest_time BETWEEN '2026-04-19 17:00:00' AND '2026-04-26 17:00:00')
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC
          
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key, mg_id, sku, warehouse_code, admin_id, available_quantity, created_time, image_url, keyword, missing_quantity, name, on_hold_quantity, packaging, product_code, product_id, seller_code, status, stock_quantity, version_no, last_updated_time, updated_by, min_quantity, is_draft, is_pending, is_ignore, unit, product_type, height, image_urls, is_fragile, is_frozen, length, weight, width, is_liquid, is_portable, max_quantity, is_full_package, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_inventory_sku`)}
  )
SELECT p.*
FROM platinum p
WHERE NOT EXISTS (SELECT 1 FROM silver s WHERE s.mg_id = p.mg_id)

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  
