config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_inventory_location",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","warehouse_prd_inventory"]
}

  WITH silver AS (
    SELECT
      key,mg_id,version_no,created_by,code,is_temp_storage,type,is_used,is_pick,parent_order,status,created_time,name,level,is_last_child,is_put,is_zone,location_id,warehouse_code,keyword,parent,reference,last_updated_time,height,length,width,is_full,mapped_sku_total,mapped_skus,shelf_type,seller_tags,updated_by,tags,remain_location_area,is_printed,is_shelf,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.warehouse_prd_inventory_location
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,version_no,created_by,code,is_temp_storage,type,is_used,is_pick,parent_order,status,created_time,name,level,is_last_child,is_put,is_zone,location_id,warehouse_code,keyword,parent,reference,last_updated_time,height,length,width,is_full,mapped_sku_total,mapped_skus,shelf_type,seller_tags,updated_by,tags,remain_location_area,is_printed,is_shelf,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_inventory_location`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"