config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_inventory_transfer_sku",
    description : `
    PIC: minh.luu
    Partition by: created date
    `
}

WITH silver AS (
    SELECT 
        key,
        mg_id,
        line_id,
        transfer_id,
        admin_id,
        created_time,
        demand_quantity,
        destination_location,
        done_quantity,
        from_location,
        in_main,
        in_warehouse,
        last_updated_time,
        location_details,
        name,
        on_hold_quantity,
        out_main,
        out_warehouse,
        packaging,
        product_id,
        reference,
        references,
        sku,
        source_location,
        status,
        to_location,
        to_real_location,
        transfer_code,
        vat,
        version_no,
        warehouse_code,
        transfer_finish_time,
        expired_date,
        lot,
        extra_data,
        synced_at,
        extra_props,
        action,
        ingest_time
        ,CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END AS created_date
        , CAST( null AS DATETIME) 
        
    FROM ${source.silver}.warehouse_prd_inventory_transfer_sku
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER(_window) != "d"
        WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC,
        IF
            (action='d',3,
            IF
            (action='u',2,1)) DESC,
    last_updated_time DESC)
), platinum AS (
    SELECT
        key,
        mg_id,
        line_id,
        transfer_id,
        admin_id,
        created_time,
        demand_quantity,
        destination_location,
        done_quantity,
        from_location,
        in_main,
        in_warehouse,
        last_updated_time,
        location_details,
        name,
        on_hold_quantity,
        out_main,
        out_warehouse,
        packaging,
        product_id,
        reference,
        references,
        sku,
        source_location,
        status,
        to_location,
        to_real_location,
        transfer_code,
        vat,
        version_no,
        warehouse_code,
        transfer_finish_time,
        expired_date,
        lot,
        extra_data,
        synced_at,
        extra_props,
        action,
        ingest_time
        , created_date 
        , platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`,`warehouse_prd_inventory_transfer_sku`) }
)

SELECT p.*
FROM platinum p
LEFT JOIN silver s 
    ON p.mg_id = s.mg_id 
WHERE s.mg_id is null 

UNION ALL 

SELECT s.*
FROM silver s

-- SELECT *
-- FROM (
--     SELECT *
--     FROM platinum 
--     UNION ALL 
--     SELECT *
--     FROM  silver 
-- )
-- QUALIFY ROW_NUMBER() OVER (_window) = 1
--     AND FIRST_VALUE(action) OVER (_window ) != "d"
-- WINDOW _window AS (
-- PARTITION BY mg_id
-- ORDER BY synced_at DESC,
-- IF
--     (action='d',3,
--     IF
--     (action='u',2,1)) DESC,
--     last_updated_time DESC)
