
config {
  type: "view",
  schema: "platinum_buymed_vn",
  name: "warehouse_prd_inbound_return_ticket_item",
  description : `
  PIC: long.nguyen@buymed.com
  Partition by: created date
  `,
  tags:["platinum","warehouse_prd_inbound"]
}

WITH silver AS (
  SELECT
    key, mg_id, name, lot, demand_quantity, lot_date_infos, ticket_id, sku, order_item_type, image_url, is_fragile, details, version_no, warehouse_code, return_code, seller_code, so, product_id, product_return_type, packaging, expired_date, vat, done_quantity, created_by, created_time, line_id, admin_product_id, real_details, is_check_med_nt, last_updated_time, updated_by, synced_at, extra_props, action, ingest_time,
    CASE
      WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
      ELSE DATE('2099-01-01')
    END created_date,
    CAST(NULL AS DATETIME) AS platinum_refresh
  FROM silver_buymed_vn.warehouse_prd_inbound_return_ticket_item
  WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
  QUALIFY ROW_NUMBER() OVER (_window) = 1
    AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
  WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
      IF(action='d',3, IF(action='u',2,1)) DESC,
      last_updated_time DESC
  )
),

platinum AS (
  SELECT
    key, mg_id, name, lot, demand_quantity, lot_date_infos, ticket_id, sku, order_item_type, image_url, is_fragile, details, version_no, warehouse_code, return_code, seller_code, so, product_id, product_return_type, packaging, expired_date, vat, done_quantity, created_by, created_time, line_id, admin_product_id, real_details, is_check_med_nt, last_updated_time, updated_by, synced_at, extra_props, action, ingest_time,
    created_date,
    platinum_refresh
  FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_inbound_return_ticket_item`)}
)

SELECT p.*
FROM platinum p
LEFT JOIN silver s
  ON p.mg_id = s.mg_id
WHERE s.mg_id IS NULL

UNION ALL

SELECT s.*
FROM silver s
WHERE action <> "d"