config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_inbound_receipt",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","warehouse_prd_inbound"]
}

  WITH silver AS (
    SELECT
      key,mg_id,version_no,created_time,inbound_ticket_id,check_in_code,start_time,last_updated_time,code,receipt_session_code,po_code,total_sku,type,tags,is_allow_auto_inbound,created_by,warehouse_code,employee_id,employee,end_time,status,updated_by,ticket_id,external_type,destination_warehouse_code,total_item,is_co_checking,basket_code,has_both_vat_type,zone,put_code,seller_code,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.warehouse_prd_inbound_receipt
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,version_no,created_time,inbound_ticket_id,check_in_code,start_time,last_updated_time,code,receipt_session_code,po_code,total_sku,type,tags,is_allow_auto_inbound,created_by,warehouse_code,employee_id,employee,end_time,status,updated_by,ticket_id,external_type,destination_warehouse_code,total_item,is_co_checking,basket_code,has_both_vat_type,zone,put_code,seller_code,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_inbound_receipt`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  