config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_core_sale_order_item",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","warehouse_prd_core"]
}

  WITH silver AS (
    SELECT
      key,mg_id,marketplace_item_type,sale_order_code,sku,admin_id,admin_product_id,created_time,erp_product_id,image_url,is_fragile,last_updated_time,line_id,name,order_quantity,packaging,pick_items,product_id,product_name,product_type,rate_tax,seller_code,status,tags,unit,unit_price,version_no,weight,reserved_quantity,scanned_quantity,outbound_quantity,delivered_quantity,completed_quantity,is_near_exp,is_external_seller,sub_items,is_important,is_red_tag,is_frozen,returned_quantity,is_full_package,link_code,link_item_quantity,link_quantity,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.warehouse_prd_core_sale_order_item
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,marketplace_item_type,sale_order_code,sku,admin_id,admin_product_id,created_time,erp_product_id,image_url,is_fragile,last_updated_time,line_id,name,order_quantity,packaging,pick_items,product_id,product_name,product_type,rate_tax,seller_code,status,tags,unit,unit_price,version_no,weight,reserved_quantity,scanned_quantity,outbound_quantity,delivered_quantity,completed_quantity,is_near_exp,is_external_seller,sub_items,is_important,is_red_tag,is_frozen,returned_quantity,is_full_package,link_code,link_item_quantity,link_quantity,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_core_sale_order_item`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"