config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_inbound_put_ticket_item",
    description : `
    PIC: minh.luu
    Partition by: created date
    Cluster by: ["put_code","ticket_id","seller_code","warehouse_code"]
    `,
    tags:["platinum","warehouse_prd_inbound"]
}



  WITH silver AS (
    SELECT
      key,mg_id,ticket_id,put_code,seller_code,demand_quantity,is_fragile,version_no,created_time,admin_product_id,product_code,lot,done_quantity,basket_code,zone,created_by,warehouse_code,tags,name,image_url,expired_date,vat,put_result,product_id,sku,demand_location,location_trading_type,last_updated_time,location_details,updated_by,packaging,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.warehouse_prd_inbound_put_ticket_item
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,ticket_id,put_code,seller_code,demand_quantity,is_fragile,version_no,created_time,admin_product_id,product_code,lot,done_quantity,basket_code,zone,created_by,warehouse_code,tags,name,image_url,expired_date,vat,put_result,product_id,sku,demand_location,location_trading_type,last_updated_time,location_details,updated_by,packaging,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_inbound_put_ticket_item`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  


