config {
    type: "view",
    name: "warehouse_prd_inventory_sku",
    schema: "platinum_buymed_vn",
    tags: ["platinum_daily_AM_9_00","warehouse_prd_inventory"]
}


SELECT
  *
FROM ${ref(`platinum_buymed_vn__stg`,`warehouse_prd_inventory_sku`)}
WHERE NOT ( 
  (created_time is not null and last_updated_time is not null) 
  or (created_time is null and last_updated_time is not null) 
  or (created_time is not null and last_updated_time is null)
)
