config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_core_delivery_order",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","warehouse_prd_core"]
}

  WITH silver AS (
    SELECT
      key,mg_id,version_no,delivery_order_code,status,fee,admin_id,reference_id,payment_method_name,tags,customer_delivery_info,is_do_printed,warehouse_code,sale_order_code,type,priority,payment_method,discount_amount,created_time,cod_amount,delivery_amount,last_updated_time,action_time,external_tpl_name,logs,ready_delivery_time,tpl_code,tracking_code,updated_by,outbound_time,delivered_time,completed_time,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.warehouse_prd_core_delivery_order
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,version_no,delivery_order_code,status,fee,admin_id,reference_id,payment_method_name,tags,customer_delivery_info,is_do_printed,warehouse_code,sale_order_code,type,priority,payment_method,discount_amount,created_time,cod_amount,delivery_amount,last_updated_time,action_time,external_tpl_name,logs,ready_delivery_time,tpl_code,tracking_code,updated_by,outbound_time,delivered_time,completed_time,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_core_delivery_order`)}
  )

  
SELECT *
FROM (
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
)
WHERE created_time is not null and last_updated_time is not null 
