config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_inbound_put_ticket",
    description : `
    PIC: minh.luu
    Partition by: created date
    Cluster By: ["source_location","status","type","warehouse_code"]
    `,
    tags:["platinum","warehouse_prd_inbound"]
}


  WITH silver AS (
    SELECT
      key,mg_id,code,basket_code,basket_codes,callback_refs,created_by,created_time,is_callback,is_expired_sla,last_updated_time,reference,references,source_location,status,ticket_id,total_item,total_sku,type,version_no,warehouse_code,zone,employee,employee_id,start_put_time,updated_by,end_put_time,end_time,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.warehouse_prd_inbound_put_ticket
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,code,basket_code,basket_codes,callback_refs,created_by,created_time,is_callback,is_expired_sla,last_updated_time,reference,references,source_location,status,ticket_id,total_item,total_sku,type,version_no,warehouse_code,zone,employee,employee_id,start_put_time,updated_by,end_put_time,end_time,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_inbound_put_ticket`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
    


