config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_inventory_sku_lot_date_v2",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","warehouse_prd_inventory"]
}

WITH silver AS (
    SELECT 
        key ,mg_id ,sku_code ,admin_id ,created_time ,expired_date ,image_url ,keyword ,last_updated_time ,lot ,name ,packaging ,product_code ,product_id ,seller_code ,sku ,stock_quantity ,vat ,version_no ,warehouse_code ,synced_at ,extra_props ,action ,ingest_time ,CASE     WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))     ELSE DATE( '2099-01-01' ) END AS created_date , CAST( null AS DATETIME) 
        
    FROM ${source.silver}.warehouse_prd_inventory_sku_lot_date_v2
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
        AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
        WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC,
        IF
            (action='d',3,
            IF
            (action='u',2,1)) DESC,
    last_updated_time DESC)
), platinum AS (
    SELECT 
        key, mg_id, sku_code, admin_id, created_time, expired_date, image_url, keyword, last_updated_time, lot, name, packaging, product_code, product_id, seller_code, sku, stock_quantity, vat, version_no, warehouse_code, synced_at, extra_props, action, ingest_time, created_date , platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`,`warehouse_prd_inventory_sku_lot_date_v2`) }
)

SELECT p.*
FROM platinum p
LEFT JOIN silver s 
    ON p.mg_id = s.mg_id 
WHERE s.mg_id is null 

UNION ALL 

SELECT s.*
FROM silver s
WHERE action <> "d"
