config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "warehouse_prd_picking_qc_supplement_data",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","warehouse_prd_picking"]
}


  WITH silver AS (
    SELECT
      key,mg_id,ticket_id,created_by,created_by_name,items,last_updated_time,so,warehouse_code,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN silver_buymed_vn.MONGOID_TIMESTAMP(mg_id) IS NOT NULL THEN DATE(DATETIME(silver_buymed_vn.MONGOID_TIMESTAMP(mg_id), 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.warehouse_prd_picking_qc_supplement_data
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,ticket_id,created_by,created_by_name,items,last_updated_time,so,warehouse_code,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `warehouse_prd_picking_qc_supplement_data`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"