config {
    type: 'view',
    schema: "buymed_innovation",
    description: `All orders item in the Vietnam marketplace (including tender orders).`
}

SELECT
    created_date
    , order_id
    , total_price
    , seller_class
FROM ${source.platinum}.marketplace_prd_order_v2_order_item AS a
WHERE 1=1
    AND created_date >= DATE_TRUNC(CURRENT_DATE("+7"), MONTH ) - INTERVAL 1 MONTH
UNION ALL
SELECT
    created_date
    , order_id
    , total_amount
    , "INTERNAL" AS seller_class
FROM ${source.platinum}.tender_prd_core_tender_order_items AS a
WHERE 1=1
    AND created_date >= DATE_TRUNC(CURRENT_DATE("+7"), MONTH ) - INTERVAL 1 MONTH

