config {
    type:"table",
    description: `PIC: Huong.Dang; Schedule: 0h00 daily
    Source;
        ${source.ref}.agg_strategic_gmv-before-cancel
        ${source.ref}.agg_strategic_gmv-after-cancel_cancel
        ${source.ref}.agg_strategic_gmv-fulfilled
        ${source.ref}.agg_strategic_gmv-unff
        ${source.ref}.agg_strategic_gmv-return
        ${source.ref}.agg_strategic_gmv-backlog`,
    columns: {
        date: "NonNull |",
        location: "Nullable |",
        channel: "Nullable |",
        measure: "NonNull |",
        value: "Nullable |"
    },
    tags: ["0h00", 'STRATEGIC-REPORTING']
}

-- Base calendar with date filter
WITH base_calendar AS (
  SELECT eom, date
  FROM ${ref(`dim_calendar`)}
  WHERE date >= "2023-01-01"
),
-- Order_item metrics
order_metrics AS (
  SELECT
    DATE(created_time) as order_date,
    location,
    channel,
    supplier_class,
    SUM(sales_price * demand_quantity) AS gmv_before_cancel,
    SUM(IF(order_status LIKE "CANCEL" AND sale_order_code IS NULL, sales_price * demand_quantity, 0)) AS cancel_before_ffm,
    SUM(IF(order_status LIKE "CANCEL", sales_price * demand_quantity, 0)) AS cancel,
    SUM(IF(order_status LIKE "CANCEL" AND sale_order_code IS NOT NULL, sales_price * demand_quantity, 0)) AS cancel_after_ffm,
    SUM(IF(order_status NOT LIKE "CANCEL", (outbound_quantity - returned_quantity) * sales_price, 0)) AS fulfilled_amount,
    SUM(IF(order_status NOT LIKE "CANCEL", returned_quantity * sales_price, 0)) AS returned_amount,
    SUM(IF(order_status NOT LIKE "CANCEL" AND order_status NOT IN ("DELIVERING", "DELIVERED", "COMPLETED"), (demand_quantity - outbound_quantity) * sales_price, 0)) AS gmv_backlog,
    SUM((listed_price - sales_price) * demand_quantity) AS commercial_amount,
    SUM(IF(commercial_type = "DEAL", (listed_price - sales_price) * demand_quantity, 0)) AS commercial_deal_amount,
    SUM(IF(commercial_type = "CAMPAIGN", (listed_price - sales_price) * demand_quantity, 0)) AS commercial_campaign_amount,
    SUM(IF(commercial_type = "COMBO", (listed_price - sales_price) * demand_quantity, 0)) AS commercial_combo_amount,
    SUM(IF(order_status NOT LIKE "CANCEL" AND order_status IN ("DELIVERING", "DELIVERED", "COMPLETED"), (demand_quantity - outbound_quantity) * sales_price, 0)) AS gmv_unff,
    SUM(listed_price * demand_quantity) AS gmv_with_listed_price,
    SUM(IF(order_status NOT LIKE "CANCEL", returned_quantity * sales_price, 0)) AS gmv_return,
    SUM(demand_quantity) AS item_sold
  FROM ${ref(`fact_strategic_sale_order_item_single`)} as f
  GROUP BY 1, 2, 3, 4
),

-- Delivery metrics
delivery_metrics AS (
  SELECT 
    DATE(do.created_time) as delivery_date,
    do.location,
    do.channel,
    CAST(NULL AS STRING) AS supplier_class,
    COUNT(DISTINCT CASE 
      WHEN DATE(do.created_time) <= '2023-05-31' THEN sale_order_code 
      ELSE delivery_order_code 
    END) AS do_count
  FROM ${ref(`fact_strategic_delivery_order`)} do
  GROUP BY 1, 2, 3, 4
),

-- Sale order metrics
sales_order_metrics AS (
  SELECT 
    order_date,
    so.location,
    so.channel,
    CAST(NULL AS STRING) AS supplier_class,
    COUNT(DISTINCT order_id ) AS so_count
  FROM ${ref(`fact_strategic_sale_order`)} so
  GROUP BY 1, 2, 3, 4
)

  SELECT
    CURRENT_DATETIME("+7") AS refresh_time,
    c.eom as date,
    m.location,
    m.channel,
    m.supplier_class,
    metric.measure,
    metric.value
  FROM order_metrics m
  CROSS JOIN UNNEST([
    STRUCT("GMV_BEFORE_CANCEL" AS measure, m.gmv_before_cancel AS value),
    STRUCT("GMV_AFTER_CANCEL", (m.gmv_before_cancel - m.cancel_before_ffm)),
    STRUCT("CANCEL", m.cancel),
    STRUCT("CANCEL_AFTER_FFM", m.cancel_after_ffm),
    STRUCT("CANCEL_BEFORE_FFM", m.cancel_before_ffm),
    STRUCT("GMV_FULFILLED", m.fulfilled_amount),
    STRUCT("NMV", m.cancel_after_ffm + m.fulfilled_amount + m.gmv_backlog + m.returned_amount),
    STRUCT("COMMERCIAL_AMOUNT", m.commercial_amount),
    STRUCT("COMMERCIAL_DEAL_AMOUNT", m.commercial_deal_amount),
    STRUCT("COMMERCIAL_CAMPAIGN_AMOUNT", m.commercial_campaign_amount),
    STRUCT("COMMERCIAL_COMBO_AMOUNT", m.commercial_combo_amount),
    STRUCT("GMV_UNFF", m.gmv_unff),
    STRUCT("GMV_WITH_LISTED_PRICE", m.gmv_with_listed_price),
    STRUCT("ITEM_SOLD", m.item_sold),
    STRUCT("GMV_BACKLOG", m.gmv_backlog),
    STRUCT("GMV_RETURN", m.gmv_return)
  ]) AS metric
INNER JOIN base_calendar c ON DATE(m.order_date) = c.date


UNION ALL
SELECT 
  CURRENT_DATETIME("+7") AS refresh_time,
  c.eom as date,
  d.location,
  d.channel,
  d.supplier_class,
  "DO" AS measure,
  d.do_count AS value
FROM delivery_metrics d
INNER JOIN base_calendar c ON DATE(d.delivery_date) = c.date


UNION ALL
SELECT 
  CURRENT_DATETIME("+7") AS refresh_time,
  c.eom as date,
  so.location,
  so.channel,
  so.supplier_class,
  "SO" AS measure,
  so.so_count AS value
FROM sales_order_metrics so
INNER JOIN base_calendar c ON DATE(so.order_date) = c.date


UNION ALL
SELECT 
a.refresh_time,
a.date,
a.location,
a.channel,
a.supplier_class,
a.measure,
a.value
FROM ${ref(`agg_strategic_customer`)} a
WHERE EXISTS (
  SELECT 1 FROM base_calendar c WHERE c.date = a.date
)

UNION ALL
SELECT
  refresh_time,
  a.date,
  location,
  channel,
  supplier_class,
  CONCAT(measure, "_ENTERPRISE") AS measure,
  value
FROM ${ref(`agg_strategic_customer`)} a
WHERE EXISTS (
  SELECT 1 FROM base_calendar c WHERE c.date = a.date
)

UNION ALL
SELECT 
refresh_time,
date,
location,
channel,
supplier_class,
measure,
value
FROM ${ref(`agg_inventory_cutoff`)}

-- UNION ALL
-- SELECT
--   CURRENT_DATETIME("+7") AS refresh_time,
--   eom AS date,
--   location,
--   channel,
--   supplier_class,
--   "SO" AS measure,
--   SO_count AS value
-- FROM ${ref(`fact_strategic_sale_order`)}
