config {
    name: "agg_strategic_customer",
    type: "view",
    description: "PIC: huong.dang",
    tags: ['STRATEGIC-REPORTING'],
}

WITH 

union_table AS (

    SELECT 
        CURRENT_DATETIME("+7") AS refresh_time,
        CAST(dc.eom AS DATE) AS date,
        dcp.location,
        dcp.channel,
        'CUSTOMER_ACTIVE' AS measure,
        CAST(NULL AS STRING) AS supplier_class,
        COUNT(DISTINCT IF(dcp.active_customer <> 0, dcp.customer_id, NULL)) AS value
    FROM ${ref(`dim_customer_profiling_all_channel`)} dcp 
    LEFT JOIN ${ref(`dim_calendar`)} dc  ON dcp.som = dc.som
    GROUP BY 1,2,3,4,5,6

    UNION ALL 

    SELECT 
        CURRENT_DATETIME("+7") AS refresh_time,
        CAST(dc.eom AS DATE) AS date,
        dcp.location,
        dcp.channel,
        'CUSTOMER_NEW' AS measure,
        CAST(NULL AS STRING) AS supplier_class,
        COUNT(DISTINCT IF(dcp.new_customer <> 0, dcp.customer_id, NULL)) AS value
    FROM ${ref(`dim_customer_profiling_all_channel`)} dcp 
    LEFT JOIN ${ref(`dim_calendar`)} dc  ON dcp.som = dc.som
    GROUP BY 1,2,3,4,5,6

    UNION ALL 

    SELECT 
        CURRENT_DATETIME("+7") AS refresh_time,
        CAST(dc.eom AS DATE) AS date,
        dcp.location,
        dcp.channel,
        'CUSTOMER_REACQUIRED' AS measure,
        CAST(NULL AS STRING) AS supplier_class,
        COUNT(DISTINCT IF(dcp.reacquire_customer <> 0, dcp.customer_id, NULL)) AS value
    FROM ${ref(`dim_customer_profiling_all_channel`)} dcp 
    LEFT JOIN ${ref(`dim_calendar`)} dc ON dcp.som = dc.som
    GROUP BY 1,2,3,4,5,6

    UNION ALL 

    SELECT 
        CURRENT_DATETIME("+7") AS refresh_time,
        CAST(dc.eom AS DATE) AS date,
        dcp.location,
        dcp.channel,
        'CUSTOMER_REPEAT' AS measure,
        CAST(NULL AS STRING) AS supplier_class,
        COUNT(DISTINCT IF(dcp.repeat_customer <> 0, dcp.customer_id, NULL)) AS value
    FROM ${ref(`dim_customer_profiling_all_channel`)} dcp 
    LEFT JOIN ${ref(`dim_calendar`)} dc  ON dcp.som = dc.som
    GROUP BY 1,2,3,4,5,6
)

SELECT *
FROM union_table