config {
    name: "agg_strategic_customer",
    type: "view",
    description: "PIC: huong.dang",
    tags: ['STRATEGIC-REPORTING'],
}

WITH channel AS (
    SELECT 
        customer_id,
        channel,
        DATE_TRUNC(DATE(order_date), MONTH) AS som
    FROM ${ref(`fact_strategic_sale_order`)}
    WHERE status <> 'CANCEL'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY 
            customer_id,
            DATE_TRUNC(DATE(order_date), MONTH)
        ORDER BY order_date DESC
    ) = 1
),

union_table AS (

    SELECT 
        CURRENT_DATETIME("+7") AS refresh_time,
        CAST(dc.eom AS DATE) AS date,
        dcp.location,
        ch.channel,
        'CUSTOMER_ACTIVE' AS measure,
        CAST(NULL AS STRING) AS supplier_class,
        COUNT(DISTINCT IF(dcp.active_customer <> 0, dcp.customer_id, NULL)) AS value
    FROM ${ref(`dim_customer_profiling`)} dcp 
    LEFT JOIN ${ref(`dim_calendar`)} dc  ON dcp.som = dc.som
    LEFT JOIN channel ch ON dcp.customer_id = ch.customer_id AND dcp.som = ch.som
    GROUP BY 1,2,3,4,5,6

    UNION ALL 

    SELECT 
        CURRENT_DATETIME("+7") AS refresh_time,
        CAST(dc.eom AS DATE) AS date,
        dcp.location,
        ch.channel,
        'CUSTOMER_NEW' AS measure,
        CAST(NULL AS STRING) AS supplier_class,
        COUNT(DISTINCT IF(dcp.new_customer <> 0, dcp.customer_id, NULL)) AS value
    FROM ${ref(`dim_customer_profiling`)} dcp 
    LEFT JOIN ${ref(`dim_calendar`)} dc  ON dcp.som = dc.som
    LEFT JOIN channel ch ON dcp.customer_id = ch.customer_id AND dcp.som = ch.som
    GROUP BY 1,2,3,4,5,6

    UNION ALL 

    SELECT 
        CURRENT_DATETIME("+7") AS refresh_time,
        CAST(dc.eom AS DATE) AS date,
        dcp.location,
        ch.channel,
        'CUSTOMER_REACQUIRED' AS measure,
        CAST(NULL AS STRING) AS supplier_class,
        COUNT(DISTINCT IF(dcp.reacquire_customer <> 0, dcp.customer_id, NULL)) AS value
    FROM ${ref(`dim_customer_profiling`)} dcp 
    LEFT JOIN ${ref(`dim_calendar`)} dc ON dcp.som = dc.som
    LEFT JOIN channel ch ON dcp.customer_id = ch.customer_id AND dcp.som = ch.som
    GROUP BY 1,2,3,4,5,6

    UNION ALL 

    SELECT 
        CURRENT_DATETIME("+7") AS refresh_time,
        CAST(dc.eom AS DATE) AS date,
        dcp.location,
        ch.channel,
        'CUSTOMER_REPEAT' AS measure,
        CAST(NULL AS STRING) AS supplier_class,
        COUNT(DISTINCT IF(dcp.repeat_customer <> 0, dcp.customer_id, NULL)) AS value
    FROM ${ref(`dim_customer_profiling`)} dcp 
    LEFT JOIN ${ref(`dim_calendar`)} dc 
        ON dcp.som = dc.som
    LEFT JOIN channel ch
        ON dcp.customer_id = ch.customer_id
        AND dcp.som = ch.som
    GROUP BY 1,2,3,4,5,6
)

SELECT *
FROM union_table