config {
    type: "assertion",
    description: "PIC: Minh Luu",
    tags: "Assert_Platinum_test"
}


/*
    What does I test?
        - 
*/

WITH silver as (
    SELECT *
    FROM (
        SELECT mg_id, created_time, last_updated_time, synced_at, ingest_time, action

        FROM lakehouse-prod-394907.silver_buymed_vn.marketplace_prd_order_v2_order_item o 
        WHERE ingest_time > "2024-10-20"
        QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER (_window) <> 'd'
        WINDOW _window AS ( 
            PARTITION BY mg_id
            ORDER BY synced_at DESC,
            IF (action = 'd', 3, IF (action = 'u', 2, 1)) DESC,
            last_updated_time DESC
        )
    )
    WHERE created_time is not null and last_updated_time is not null
    AND created_time >= "2024-10-20"
)

, platinum as (
    SELECT mg_id
    FROM ${source.platinum}.marketplace_prd_order_v2_order_item
    WHERE created_time >= "2024-10-20"
    AND created_date >= "2024-10-20"
)

SELECT s.*, TIMESTAMP_TRUNC(current_timestamp(), HOUR) AS refresh_time
FROM silver s left join platinum p using(mg_id)
WHERE p.mg_id is null
AND ingest_time < TIMESTAMP_TRUNC(current_timestamp(), HOUR)
