config {
    type: "incremental",
    name: "marketplace_prd_order_v2_order_item",
    schema: "platinum_buymed_vn",
    assertions: {
         uniqueKey: 'mg_id'
     },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["custom_1h_past7","marketplace_prd_order-v2"]
}
pre_operations {
  ${
    when(incremental(),
        `
        # Incremental
        DECLARE has_new_data BOOLEAN;
        DECLARE Ingest_checkpoint TIMESTAMP;
        DECLARE checkpoint_date ARRAY<date>;
        DECLARE new_records ARRAY<STRING>;
        DECLARE deleted_records ARRAY<STRING>;
        
        SET Ingest_checkpoint = (SELECT max(ingest_time) FROM ${self()});

        SET ( has_new_data, checkpoint_date, new_records, deleted_records ) = ( 
            SELECT AS STRUCT 
                IF ( 
                    COUNT(*) > 0 , TRUE, FALSE 
                ) has_new_data,
                /* 
                    has_new_data describe the existance of data after the last refresh time of platinum 
                */
                ARRAY_AGG(
                    DISTINCT IF(created_time is NULL, "2099-01-01" , DATE( DATETIME(created_time,'Asia/Ho_Chi_Minh') ) )
                ) AS checkpoint_date,
                ARRAY_AGG (
                    DISTINCT mg_id IGNORE NULLS
                ) AS new_records,
                ARRAY_AGG (
                    DISTINCT IF(action = 'd',mg_id, NULL) IGNORE NULLS
                ) AS deleted_records
            FROM ${source.silver}.marketplace_prd_order_v2_order_item
            WHERE ingest_time > Ingest_checkpoint 
            -- AND ingest_time < TEMP_timestamp
        );

        IF ( has_new_data = TRUE ) THEN
            IF (SELECT ARRAY_LENGTH(deleted_records) > 0) THEN 
              SET checkpoint_date = ARRAY( 
                SELECT DISTINCT created_date
                FROM ${self()} 
                WHERE mg_id IN UNNEST(new_records)
              );
            END IF;

            DELETE FROM ${self()}
            WHERE 
                created_date IN UNNEST(checkpoint_date)
                AND mg_id IN UNNEST(new_records)
            ;
        ELSE 
            SET Ingest_checkpoint = TIMESTAMP("2099-01-01T00:00:00");
        END IF ;
    
      `,
      ``
    )
  }
}

--

SELECT 
  *
FROM (
  SELECT
    *,
    CASE 
      WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
      ELSE "2099-01-01"
    END AS created_date

  FROM
    ${source.silver}.marketplace_prd_order_v2_order_item s
    ${ when(incremental(), 
      `WHERE s.ingest_time > Ingest_checkpoint - INTERVAL 2 HOUR
          -- AND s.ingest_time < TEMP_timestamp
          AND s.mg_id IN UNNEST(new_records) `, 
      // `WHERE ingest_time > "2025-01-01" AND ingest_time <= "2025-01-22T13:00:00"` 
      )}  
  QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER (_window) <> 'd'
  WINDOW _window AS ( 
    PARTITION BY mg_id
    ORDER BY 
      synced_at DESC,
      IF (action='d',3, IF (action='u',2,1)) DESC,
      last_updated_time DESC)
)
WHERE created_time is not null and last_updated_time is not null 
-- all record deleted include action "d"
-- Special case for order -- PIC: AnhLe