config {
    type: "incremental",
    name: "marketplace_prd_order_v2_order",
    schema: "platinum_buymed_vn",
    assertions: {
         uniqueKey: 'mg_id',
         nonNull: ['created_date'],
         rowConditions: [
        '(created_time is not null and last_updated_time is not null) or (created_time is null and last_updated_time is not null) or (created_time is not null and last_updated_time is null)',
        'action != "d"'
    ]
     },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["custom_1h_past7"]
}
pre_operations {
  ${
    when(incremental(),
      `
      --
      DECLARE checkpoint_date ARRAY<date>;

      SET checkpoint_date = ARRAY( 
        SELECT DISTINCT date(created_time,'+7')
        FROM silver_buymed_vn.marketplace_prd_order_v2_order 
        WHERE ingest_time >= TIMESTAMP_TRUNC((CURRENT_TIMESTAMP() - interval 6 HOUR), HOUR)
        AND created_time IS NOT NULL
      );

      DELETE FROM platinum_buymed_vn.marketplace_prd_order_v2_order
      where created_date in UNNEST(checkpoint_date)
      and mg_id in ( 
        SELECT DISTINCT mg_id 
        FROM silver_buymed_vn.marketplace_prd_order_v2_order 
        WHERE ingest_time >= TIMESTAMP_TRUNC((CURRENT_TIMESTAMP() - interval 6 HOUR), HOUR)
        );

      `,
      ``
    )
  }
}
--
SELECT 
  *,
  DATE_TRUNC(
    CASE 
    WHEN created_time IS NULL THEN DATETIME("2099-01-01T00:00:00")
    WHEN MOD(EXTRACT(HOUR FROM created_time), 2) = 1 THEN DATETIME(created_time - interval 1 hour)
    ELSE DATETIME(created_time)
  END, HOUR) AS partition_time -- Use for partition each two hour, only apply for table that have high frequency update
FROM (
  SELECT
    *,
    CASE 
      WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
      ELSE "2099-01-01"
    END AS created_date

  FROM
    ${source.silver}.marketplace_prd_order_v2_order o 
    ${ when(incremental(),  `WHERE ingest_time > TIMESTAMP_TRUNC((CURRENT_TIMESTAMP() - interval 6 HOUR), HOUR)`  )}
  QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER (_window) <> 'd'
  WINDOW _window AS ( 
    PARTITION BY mg_id
    ORDER BY 
      synced_at DESC,
      IF (action='d',3, IF (action='u',2,1)) DESC,
      last_updated_time DESC)
)
WHERE created_time is not null and last_updated_time is not null 
-- all record deleted include action "d"
-- Special case for order -- PIC: AnhLe