config {
    type: "incremental",
    description: "PIC: minh.luu "
}

js {
    const start_date = `"2025-05-11"`
    const refresh_interval = `"INTERVAL 2 HOUR"`
}

WITH base AS (
    SELECT
        user_email,
        execution_time AS last_execution_time
        -- user_name,

    FROM ${ref(`base_information_schema_job`)} 
    WHERE 1=1
    ${ when(
        incremental(),
        `AND execution_time >= CURRENT_TIMESTAMP() - ${refresh_interval}`,
        `AND execution_time >= ${start_date}`
    )}
)
, int_incremental AS (
    SELECT 
        user_email,
        last_execution_time
    FROM base 

    ${ when(
        incremental(),
        `
        UNION ALL
        SELECT 
            user_email,
            last_execution_time
        FROM ${self()}
        `
    )}
)
, int_distinct AS (
    SELECT 
        user_email,
        max(last_execution_time) last_execution_time
    FROM int_incremental
    GROUP BY 1
)
, base_user AS (

    SELECT i.name, i.team, ARRAY_TO_STRING(i.regexp,"|" ) regexp_pattern
    FROM UNNEST( [
        STRUCT('minh.luu' AS name, 'Infra' AS team,     ['minhluu','minh.luu','minh-luu'] AS regexp),
        STRUCT('huong.dang',       'BI-core' ,          ['huongdang','huong.dang','huong-dang']),
        STRUCT('huyen.nguyen',     'BI-core' ,          ['huyennguyen','huyen.nguyen','huyen-nguyen']),
        STRUCT('nguyen.tran',      'BI-core' ,          ['nguyentran','nguyen.tran','nguyen-tran']),
        STRUCT('huyen.ngo',        'BI-core' ,          ['huyenngo','huyen.ngo','huyen-ngo']),
        STRUCT('minh.ly',          'BI-fin' ,           ['minhly','minh.ly','minh-ly']),
        STRUCT('van.le',           'BI-fin' ,           ['vanle','van.le','van-le']),
        STRUCT('thach.nguyen',     'BI-growth',         ['thachnguyen','thach.nguyen','thach-nguyen']),
        STRUCT('chien.le',         'BI-growth',         ['chienle','chien.le','chien-le']),
        STRUCT('matthew.s',        'Product Director',  ['matthews','matthew.s','matthew-s']),
        STRUCT('khanh.nguyenhung', 'BI-warehouse',      ['khanhnguyenhung','khanh.nguyenhung','khanh-nguyen-hung','khanh.nguyen','khanh-nguyen']),
        STRUCT('nhan.tran',        'Infra',             ['nhantran','nhan.tran','nhan-tran']),
        STRUCT('tin.nguyen',       'BI-fin' ,           ['tinnguyen','tin.nguyen','tin-nguyen']),
        STRUCT('pakawat.k',        'BI-cam',            ['pakawatk','pakawat.k','pakawat-k']),
        STRUCT('supeerana.p',      'BI-th',             ['supeeranap','supeerana.p','supeerana-p']),
        STRUCT('tanawin.b',        'BA-th',             ['tanawinb','tanawin.b','tanawin-b']),
        STRUCT('tien.ho',          'Infra',             ['tienho','tien.ho','tien-ho']),
        STRUCT('thi.nguyen',       'AI',                ['thinguyen','thi.nguyen','thi-nguyen']),
        STRUCT('phuoc.le',         'AI',                ['phuocle','phuoc.le','phuoc-le']),
        STRUCT('hung.vo',          'AI',                ['hungvo','hung.vo','hung-vo'])
    ]) i

)

SELECT 
    user_email,
    last_execution_time,
    COALESCE(bu.name, SPLIT(LOWER(user_email),"@")[0] ) AS user_name, 
    CASE
        WHEN LOWER(user_email) like "%serviceaccount%" AND LOWER(user_email) like "%dataform%"  THEN "Dataform"
        WHEN LOWER(user_email) like "%serviceaccount%" THEN "Service Account"
        WHEN LOWER(user_email) like "%@buymed.com" THEN "User"
    END AS type,
    -- CASE 
    --     WHEN LOWER(user_)
    -- END AS team 


FROM int_distinct m
LEFT JOIN base_user bu ON  REGEXP_CONTAINS( LOWER(user_email),regexp_pattern  )