config {
    type: "incremental", // view, table , incremental
    name: "fact_bigquery_activity",
    description: `PIC: <minh.luu> , model_type: incremental ; schedule: every 1h`,
    columns:{
    },
    tags: ["bq_job"],
    bigquery: { /* except view */
        partitionBy: "DATE(execution_time)",
        clusterBy: ["user_email","state","job_id"]
    }
}

pre_operations {
    DECLARE execution_time_checkpoint TIMESTAMP;
    ${when(
        incremental(),
        `
        SET execution_time_checkpoint = (SELECT max(execution_time) - INTERVAL 2 HOUR FROM ${self()});
        DELETE FROM ${self()} WHERE execution_time >= execution_time_checkpoint;`,
        `SET execution_time_checkpoint = CURRENT_TIMESTAMP() - INTERVAL 15 DAY`
    )}
}

SELECT 
    base_key,
    job_id,
    job_type,
    priority,
    state,
    statement_type,
    query,
    
    total_bytes_processed,
    total_bytes_billed,
    
    execution_time + INTERVAL 7 HOUR AS execution_time_vn,
    execution_time,
    user_email,
    

    label.* except(base_key)
    

    
FROM ${ref('base_information_schema_job')} base 
LEFT JOIN ${ref('int_bq_label_and_table')} label USING ( base_key )

WHERE execution_time >= execution_time_checkpoint

