config {
    type: "operations",
    name: "fact_bq_activity_permission"
}

CREATE OR REPLACE ROW ACCESS POLICY
  bq_user_filter
ON
    ${ref(`fact_bq_activity`)} GRANT TO (
        "user:hau.lecong@buymed.com",
        "user:chien.le@buymed.com",
        "user:trinh.nguyenbao@buymed.com"
    )
FILTER USING
  (user_email = SESSION_USER() and execution_time >= CURRENT_TIMESTAMP() - INTERVAL 7 DAY );


CREATE OR REPLACE ROW ACCESS POLICY 
  bq_core_team
ON 
  ${ref(`fact_bq_activity`)} GRANT TO (
    "user:nguyen.tran@buymed.com",
    "serviceAccount:nguyen-tran-service-account@lakehouse-prod-394907.iam.gserviceaccount.com"
    "user:minh.luugia@buymed.com",
    "user:huong.dang@buymed.com",
    "user:huyen.ngo@buymed.com"
  )
FILTER USING (
  TRUE
);