config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every 2 hours`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past15"],
    name: "cos_return_completed_detail",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}

Select b.*
      ,c.product_id
      ,c.sku_code
      ,c.lot_date
      ,sum(c.quantity) as quantity
      ,sum(c.base_quantity) as base_quantity
from ${source.ref}.cos_return_completed b
left join ${source.circa_os}.order_return_order_item c on b.id = c.return_order_id
where pos_code not in ('POS0140','POS0184')
group by all
union all 
Select b.*
      ,c.product_id
      ,'' as sku_code
      ,c.lot_date
      ,sum(c.quantity) as quantity
      ,sum(base_quantity) as base_quantity
from ${source.ref}.cos_return_completed b
left join ${source.circa}.order_order_item c on b.id = c.order_id
where pos_code in ('POS0140','POS0184')
group by all

