config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every 2 hours`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past15"],
    name: "cos_return_completed",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}

with return_completed as (
    select o.id
           ,o.code
           ,sum(total_amount) as total_amount
           ,sum(total_item_amount - medicine_cutting_fee) as gmv_return
           ,sum(total_amount) as rev_return
    from ${source.circa}.order_order o
    left join ${source.circa}.entity_pos_profile p on o.pos_id = p.id
    where o.pos_id in ("b6c40920-af79-4fb0-bdc4-9965ddb885d2", "e737c882-e90c-4fd2-8a4f-ac6afd248a33")
          and o.type = 'RETURN' 
          and o.status = 'COMPLETED'
    group by all

    union all

    select c.id
          ,c.code
          ,sum(total_amount) as total_amount
          ,sum(total_item_amount) as gmv_return
          ,sum(total_amount - loyalty_discount_amount)  as rev_return
    from ${source.circa_os}.order_return_order c
    left join ${source.ref}.circa_pos_profile p on c.pos_id = p.id
    where c.status = 'COMPLETED'
          and p.id is not null
    group by all
)
, cte_fs as
    (select distinct o.id as order_id
       ,datetime_add(o.created_at, interval 7 hour) as created_at
       ,o.pos_id
       ,p.code as pos_code
       ,o.code as order_code
       ,o.total_amount
       ,cast(return_id as string) as return_codes
       ,o.total_item_amount
       ,o.medicine_cutting_fee
       ,o.discount_amount
       ,1 as client_id
from ${source.circa}.order_order o
left join unnest(JSON_VALUE_ARRAY(order_return_codes)) as return_id
left join ${source.circa}.entity_pos_profile p on o.pos_id = p.id
where pos_id in ("b6c40920-af79-4fb0-bdc4-9965ddb885d2", "e737c882-e90c-4fd2-8a4f-ac6afd248a33")
      and o.type <> 'RETURN'
group by all)
,cte_os as
    (select distinct
        o.id as order_id
       ,datetime_add(o.created_at, interval 7 hour) as created_at
       ,o.pos_id
       ,p.code as pos_code
       ,o.code as order_code
       ,o.total_amount
       ,rt.code as return_codes 
       ,o.total_item_amount
       ,o.medicine_cutting_fee
       ,o.discount_amount
       ,o.client_id
from ${source.circa_os}.order_order o
left join unnest(JSON_VALUE_ARRAY(order_return_codes)) as return_codes
left join (Select * from ${source.circa_os}.order_return_order where status = 'COMPLETED') as rt on return_codes  = rt.code
-- unnest(JSON_VALUE_ARRAY(order_return_codes)) as return_id
left join ${source.ref}.circa_pos_profile p on o.pos_id = p.id and o.client_id = p.client_id
where o.type <> 'RETURN'
      and p.id is not null
      and rt.code is not null
group by all)
, _all as
(
select f.* 
       ,c.id
       ,coalesce(sum(c.total_amount), 0) as total_return_amount
       ,sum(gmv_return) as gmv_return
       ,sum(rev_return) as rev_return
       ,f.total_amount - coalesce(sum(c.rev_return), 0) as rev_exclude_return
       ,(f.total_item_amount + f.medicine_cutting_fee - gmv_return) as gmv_exclude_return
from cte_fs f
left join return_completed c on f.return_codes = c.code
where f.return_codes is not null
group by all

union all

select o.* 
       ,c.id
       ,coalesce(sum(c.total_amount), 0) as total_return_amount
       ,sum(gmv_return) as gmv_return
       ,sum(rev_return) as rev_return
       ,o.total_amount - coalesce(sum(c.rev_return), 0) as rev_exclude_return
       ,(o.total_item_amount + o.medicine_cutting_fee - gmv_return) as gmv_exclude_return
from cte_os o
left join return_completed c on o.return_codes = c.code
where c.code is not null
group by all
)
Select timestamp_add(current_timestamp(), interval 7 hour) as transformed_at
       , * from _all 
-- where order_code = 'DHC00255137'