config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every 2 hours`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past5"],
    name: "cos_return_completed",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}

with return_completed as (
    select o.id
           ,o.code
           ,total_amount
    from ${source.circa}.order_order o
    left join ${source.circa}.entity_pos_profile p on o.pos_id = p.id
    where pos_id in ("b6c40920-af79-4fb0-bdc4-9965ddb885d2", "e737c882-e90c-4fd2-8a4f-ac6afd248a33")
          and o.type = 'RETURN' 
          and o.status = 'COMPLETED'

    union all

    select c.id
          ,c.code
          ,total_amount
    from ${source.circa_os}.order_return_order c
    left join ${source.ref}.circa_pos_profile p on c.pos_id = p.id
    where c.status = 'COMPLETED'
          and p.id is not null
),

cte_fs as
    (select o.id as order_id
       ,o.created_at
       ,pos_id
       ,p.code as pos_code
       ,o.code as order_code
       ,o.total_amount
       ,cast(return_id as string) as return_codes
       ,1 as client_id
from ${source.circa}.order_order o
left join unnest(JSON_VALUE_ARRAY(order_return_codes)) as return_id
left join ${source.circa}.entity_pos_profile p on o.pos_id = p.id
where pos_id in ("b6c40920-af79-4fb0-bdc4-9965ddb885d2", "e737c882-e90c-4fd2-8a4f-ac6afd248a33")
      and o.type <> 'RETURN'
group by all)
,cte_os as
    (select
        o.id as order_id
       ,o.created_at
       ,pos_id
       ,p.code as pos_code
       ,o.code as order_code
       ,o.total_amount
       ,cast(return_id as string) as return_codes
       ,o.client_id
from ${source.circa_os}.order_order o
left join unnest(JSON_VALUE_ARRAY(order_return_codes)) AS return_id
left join ${source.ref}.circa_pos_profile p on o.pos_id = p.id and o.client_id = p.client_id
where o.type <> 'RETURN'
      and p.id is not null
group by all)
, _all as
(
select f.*
       ,c.id
       ,COALESCE(SUM(f.total_amount), 0) as total_return_amount
       ,f.total_amount - COALESCE(SUM(c.total_amount), 0) AS exclude_return
from cte_fs f
left join return_completed c on f.return_codes = c.code
where f.return_codes is not null
--where f.total_amount > c.total_amount
group by all

union all

select o.*
       ,c.id
       ,COALESCE(SUM(c.total_amount), 0) as total_return_amount
       ,o.total_amount - COALESCE(SUM(c.total_amount), 0) AS exclude_return
from cte_os o
left join return_completed c on o.return_codes = c.code
--where o.total_amount > c.total_amount
group by all
)
Select * from _all 
where total_return_amount <> 0