config {
    type: "table",
    description: `PIC: huyen.nguyenthu;
    Source:
        ${source.ref}.adhoc_pricing_competitor_price
        ${source.ref}.dim_fc_service_area
        ${source.ref}.adhoc_pricing_v2
        ${source.ref}.cos_adhoc_pos_product`
      ,
    tags: ["custom_1h_past5"],
    name: "adhoc_pricing_compare",
    columns: {
        product_id: "NonNull | The unique identifier for each product"
        
    }
}

WITH
  market_price AS (
  SELECT
    product_id
    , s.sales_region_code
    , min(market_price_aft_convert) AS min_price
    , max(market_price_aft_convert) AS max_price
  FROM ${ref('adhoc_pricing_competitor_price')} m
  LEFT JOIN ${ref('dim_fc_service_area')} s ON m.province_code = s.service_area_code
  GROUP BY ALL
  ),

  thuocsi_price AS (
  SELECT
      product_id
       , sales_region_code
      , min(sku_display_price) AS min_sku_display_price
      , max(sku_display_price) AS max_sku_display_price
      , min(price_after_discount) AS min_price_after_discount
      , max(price_after_discount) AS max_price_after_discount
  FROM ${ref('adhoc_pricing_v2')}
  GROUP BY ALL
  ),

  os_price AS (
    SELECT
      l.product_id
      , l.sales_region_code
      , l.max_convert_rate
      , SAFE_DIVIDE(l.max_convert_rate, p.convert_rate) AS max_unit
    FROM (
      SELECT
        product_id
        , sales_region_code
        , max(convert_rate) AS max_convert_rate
        FROM ${ref('cos_adhoc_pos_product')}
        GROUP BY ALL) AS l
    LEFT JOIN ${ref('cos_adhoc_pos_product')} p 
      ON l.product_id = p.product_id
      AND l.sales_region_code = p.sales_region_code
    GROUP BY ALL
  )

  SELECT
    o.product_id
    , o.sales_region_code
    , SAFE_CAST(SAFE_DIVIDE(o.max_convert_rate, o.max_unit) AS INT64) AS convert_rate
    , SAFE_DIVIDE(m.min_price, o.max_unit) AS min_market_price
    , SAFE_DIVIDE(m.max_price, o.max_unit) AS max_market_price
    , SAFE_DIVIDE(t.min_sku_display_price, o.max_unit) AS min_thuocsi_display_price
    , SAFE_DIVIDE(t.max_sku_display_price, o.max_unit) AS max_thuocsi_display_price
    , SAFE_DIVIDE(t.min_price_after_discount, o.max_unit) AS min_thuocsi_aft_dis_price
    , SAFE_DIVIDE(t.max_price_after_discount, o.max_unit) AS max_thuocsi_aft_dis_price
  FROM os_price o
  LEFT JOIN market_price m 
    ON o.product_id = m.product_id 
    AND o.sales_region_code = m.sales_region_code
  LEFT JOIN thuocsi_price t 
    ON o.product_id = t.product_id 
    AND o.sales_region_code = t.sales_region_code
  GROUP BY ALL