
config {
    type: "table",
    description: `cos_demand_planning detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_2h_past5"],
    name: "all_sku_medigo",
    columns: {
        
    }
}



Select *
from buymed_external.all_skus_medigo
where id_mdg is not null



