config {
    type: "table",
    description: `"tracking_purchase_put PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_1h_past5"],
    name: "circa_tracking_rcv_put",
    columns: {
        
    }
}



with base_unit_selection as (
  select
    product_id
    ,client_id
    ,base_unit
    ,row_number() over (partition by product_id, client_id order by count(*) desc) as rn
  from  ${source.ref}.cos_product_convert_base_unit
  where client_id = 1
  group by product_id, client_id, base_unit
), base_unit as (
select a.*
from  ${source.ref}.cos_product_convert_base_unit a
left join  base_unit_selection b on a.product_id = b.product_id
                                    and a.client_id = b.client_id
                                    and a.base_unit = b.base_unit
where b.rn = 1
), rcv  as (
Select distinct r.code
                ,r.status
                ,r.id
                ,dest_pos_id as pos_id
                ,p.name as pos_name
                ,datetime_add(r.created_at, interval 7 hour) as created_at
                ,date(datetime_add(r.created_at, interval 7 hour)) as created_date
                ,ri.product_id
                ,ri.unit_id 
                ,sum(rid.quantity) as demand_quantity
                ,unit as rcv_unit
                ,sum(rid.received_quantity) as received_quantity
                ,r.client_id
                ,p.code as pos_code
                ,'TRANSFER_IN' as fulfillment_method
 from ${source.circa_os}.inventory_transfer_request r 
 left join ${source.circa_os}.inventory_transfer_item ri on r.id = ri.transfer_request_id 
 left join ${source.circa_os}.inventory_transfer_item_detail rid on ri.id = rid.transfer_item_id 
left join ${source.ref}.circa_pos_profile p on r.dest_pos_id = p.id and r.client_id = p.client_id
where p.id is not null
      and r.type = 'TRANSFER_IN'
      and r.status <> 'CANCELED'
      and r.status <> 'PROCESSING'
      --and r.code = 'RCV00006775'
     and r.client_id = 1
group by all
),t as (
    select distinct put.ref_id
                   ,putd.product_id 
                   ,sum(putd.quantity)  as put_quantity
                   ,putd.unit as put_unit
                   ,put.status as put_status
                   ,put.client_id
 from ${source.circa_os}.inventory_put_ticket put 
    left join  ${source.circa_os}.inventory_put_ticket_item putd  on putd.put_ticket_id = put.id 
    where put.client_id = 1
    --where put.code = 'PUT22073'
   group by all
),base_tracking as(
select distinct rcv.*
               ,put_quantity
               ,put_unit
               ,put_quantity * cv.convert_rate as put_base_qty 
from rcv
left join t on rcv.id = t.ref_id
              and rcv.product_id = t.product_id   
              and rcv.client_id = t.client_id
left join  ${source.ref}.cos_dim_product td on t.product_id = td.product_id
left join  base_unit cv on cv.product_id = t.product_id
                        and Put_unit = cv.convert_unit
                                                                                              
where rcv.id is not null                                                                                                 
group by all
),to_check as (
Select distinct base_tracking.* except (pos_id,put_quantity,put_base_qty)
      ,sum(put_quantity) as total_put_quantity
      ,sum(put_base_qty) as put_base_qty
      ,base_tracking.received_quantity  * cv.convert_rate as po_base_qty
from base_tracking
left join base_unit cv on cv.product_id = base_tracking.product_id and rcv_unit = cv.convert_unit 
group by all
)
Select to_check.* except (unit_id)
       ,concat(product_id,"_", pos_code) as product_pos_code
       ,concat(product_id, "_", client_id) as product_client_id
       ,case when to_check.put_base_qty <> po_base_qty then 'true'
            when to_check.total_put_quantity is null and to_check.received_quantity > 0 then 'not_yet_put'
            when  to_check.total_put_quantity is null and to_check.received_quantity  =  0 then 'not_yet_have_item'
            else 'false' end as is_difference
from to_check
