
config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At minute 10 every hour`,
    tags:["custom_1h_past10"],
    name: "circa_fact_order_voucher"
}



SELECT DISTINCT TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) AS transformed_at
                ,order_code
                ,ov.created_at
                ,voucher_code
                ,ov.paid_source
                ,discount_amount
                ,cp.code AS Campaign_code
                ,cp.name AS Compaign_name
FROM  ${source.circa_os}.order_order_voucher ov
LEFT JOIN ${source.circa_os}.promotion_promotion_voucher us  ON ov.voucher_code = us.code
LEFT JOIN ${source.circa_os}.promotion_promotion_campaign cp ON us.promotion_campaign_id = cp.id
WHERE voucher_code NOT LIKE "%TECHTEST%"
      AND cp.name NOT LIKE'%Tech Test%'


