config {
    type: "table",
    description: `"tracking_purchase_put 
                     PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour
                     Bảng này dùng để kiểm tra hàng nhận từ luân chuẩn đã put lên kệ chưa, put có chênh lệch số lượng nhận không`,
    tags: ["custom_1h_past5"],
    name: "circa_tracking_rcv_put",
    columns: {
        
    }
}

-- quy đổi lấy đơn vị base_unit
WITH base_unit_selection AS (
    SELECT
        product_id
        , client_id
        , base_unit
        , ROW_NUMBER() OVER (
            PARTITION BY product_id, client_id
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM ${source.ref}.cos_product_convert_base_unit
    WHERE client_id = 1
    GROUP BY ALL
)

, base_unit AS (
    SELECT
        a.*
    FROM ${source.ref}.cos_product_convert_base_unit a
    LEFT JOIN base_unit_selection b ON a.product_id = b.product_id
        AND a.client_id = b.client_id
        AND a.base_unit = b.base_unit
    WHERE b.rn = 1
)
--Lấy số lượng nhận từ các phiếu transfer
, rcv AS (
    SELECT DISTINCT
        r.code
        , r.status
        , r.id
        , ri.id AS ref_item_id
        , dest_pos_id AS pos_id
        , p.name AS pos_name
        , DATETIME_ADD(r.created_at, INTERVAL 7 HOUR) AS created_at
        , DATE(DATETIME_ADD(r.created_at, INTERVAL 7 HOUR)) AS created_date
        , ri.product_id
        , ri.unit_id
        , SUM(rid.quantity) AS demand_quantity
        , unit AS rcv_unit
        , SUM(rid.received_quantity) AS received_quantity
        , r.client_id
        , p.code AS pos_code
        , 'TRANSFER_IN' AS fulfillment_method
    FROM ${source.circa_os}.inventory_transfer_request r
    LEFT JOIN ${source.circa_os}.inventory_transfer_item ri ON r.id = ri.transfer_request_id
    LEFT JOIN ${source.circa_os}.inventory_transfer_item_detail rid ON ri.id = rid.transfer_item_id
    LEFT JOIN ${source.ref}.circa_pos_profile p ON r.dest_pos_id = p.id
        AND r.client_id = p.client_id
    WHERE p.id IS NOT NULL
        AND r.type = 'TRANSFER_IN'
        AND r.status <> 'CANCELED'
        AND r.status <> 'PROCESSING'
        -- AND r.code = 'RCV00006775'
        AND r.client_id = 1
    GROUP BY ALL
)
-- số lượng từ các phiếu put lên kệ
, t AS (
    SELECT DISTINCT
        put.ref_id
        , putd.ref_id AS ref_item_id
        , putd.product_id
        , SUM(putd.quantity) AS put_quantity
        , putd.unit AS put_unit
        , put.status AS put_status
        , put.client_id
    FROM ${source.circa_os}.inventory_put_ticket put
    LEFT JOIN ${source.circa_os}.inventory_put_ticket_item putd
        ON putd.put_ticket_id = put.id
    WHERE put.client_id = 1
        -- WHERE put.code = 'PUT22073'
    GROUP BY ALL
)
-- quy đổi sang base_unit
, base_tracking AS (
    SELECT DISTINCT
        rcv.*
        , put_quantity
        , put_unit
        , put_quantity * cv.convert_rate AS put_base_qty
    FROM rcv
    LEFT JOIN t ON rcv.id = t.ref_id
                AND rcv.ref_item_id = t.ref_item_id
                AND rcv.product_id = t.product_id
                AND rcv.client_id = t.client_id
    LEFT JOIN ${source.ref}.cos_dim_product td ON t.product_id = td.product_id
    LEFT JOIN base_unit cv ON cv.product_id = t.product_id AND put_unit = cv.convert_unit
    WHERE rcv.id IS NOT NULL
    GROUP BY ALL
)

, to_check AS (
    SELECT DISTINCT
        base_tracking.* EXCEPT (pos_id, put_quantity, put_base_qty)
        , SUM(put_quantity) AS total_put_quantity
        , SUM(put_base_qty) AS put_base_qty
        , base_tracking.received_quantity * cv.convert_rate AS po_base_qty
    FROM base_tracking
    LEFT JOIN base_unit cv ON cv.product_id = base_tracking.product_id
                          AND rcv_unit = cv.convert_unit
    GROUP BY ALL
)

SELECT
    to_check.* EXCEPT (unit_id, ref_item_id)
    , CONCAT(product_id, "_", pos_code) AS product_pos_code
    , CONCAT(product_id, "_", client_id) AS product_client_id
    , CASE
        WHEN to_check.put_base_qty <> po_base_qty THEN 'true'
        WHEN to_check.total_put_quantity IS NULL
            AND to_check.received_quantity > 0 THEN 'not_yet_put'
        WHEN to_check.total_put_quantity IS NULL
            AND to_check.received_quantity = 0 THEN 'not_yet_have_item'
        ELSE 'false'
    END AS is_difference
FROM to_check
-- where code = 'RCV00008634'
--       and product_id = 2302
