config {
    type: "table",
    description: `LASt 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every 2 hours.Circa Pre_order `,
    tags: ["custom_1h_pASt15"],
    name: "circa_pre_order",
    columns: {
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}


SELECT o.*
        ,coalesce(i.product_id, d.product_id) AS product_id
        ,coalesce(p.product_name, d.product_name) AS product_name 
        ,d.quantity AS demand_quantity
        ,d.unit AS demand_unit
        ,i.quantity AS sales_qty
        ,i.unit AS sales_unit 
        ,i.unit_price
        ,i.unit_cost_price
        ,sum (i.quantity * i.unit_price) AS item_amount
        ,i.lot_date
        ,i.po_code
        ,i.owner_name
        ,i.distributor_id
        ,CONCAT(coalesce(i.product_id, d.product_id), "_",i.client_id) AS product_client_id
 FROM  ${source.ref}.cos_fact_order o 
LEFT JOIN  ${source.ref}.cos_fact_order_item i ON o.order_id = i.order_id
LEFT JOIN  ${source.ref}.cos_dim_product p ON i.product_id = p.product_id AND o.client_id = p.client_id
LEFT JOIN  ${source.ref}.cos_order_item_demand d on o.order_id = d.order_id
WHERE delivery_scheduled_time IS NOT NULL
GROUP BY ALL
