
config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 10h30`,
    tags:["10h30"],
    name: "circa_fact_order_voucher"
}



select distinct order_code
                ,ov.created_at
                , voucher_code
                , ov.paid_source
                , discount_amount
                ,cp.code as Campaign_code
                ,cp.name as Compaign_name
from${source.circa_os}.order_order_voucher ov
left join ${source.circa_os}.promotion_promotion_voucher us  on ov.voucher_code = us.code
left join${source.circa_os}.promotion_promotion_campaign cp on us.promotion_campaign_id = cp.id
where voucher_code not like "%TECHTEST%"
      and cp.name not like '%Tech Test%'


