config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every 2 hours.Circa Pre_order `
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past5"],
    name: "circa_pre_order",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}


 Select o.*
        ,i.* except (order_id,completed_date,discount_amount,client_id)
        ,i.discount_amount as discount_amount_item
        ,concat(i.product_id, "_",i.client_id) as product_client_id
 from ${source.ref}.cos_fact_order o 
 left join ${source.ref}.cos_fact_order_item i on o.order_id = i.order_id
 where origin_order_id in (Select order_id from ${source.ref}.cos_fact_order
                                        where pre_order_required = 'true')