config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At minute 10 every 1 hour.Circa online order item `
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past10"],
    name: "circa_online_order_item",
    columns: {
       
    },
    bigquery: {
        partitionBy: "created_date"
    }
}

WITH base_data AS (
SELECT TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR)                          AS transformed_at
      ,product_id
      ,product_name
      ,SAFE_CAST(JSON_VALUE(extra_props, '$.origin_price') AS INT64) AS origin_price
      ,JSON_VALUE(extra_props, '$.promotion_event_id') AS promotion_event_id
      ,unit
      ,unit_code
      ,price --as unit_price
      ,quantity    
      ,order_id
      ,order_code
      ,total_price --= unit_price * quanitty
      ,DATETIME_ADD(created_time, INTERVAL 7 hour)                                   AS created_time
      ,DATE(DATETIME_ADD(created_time, INTERVAL 7 hour))                             AS created_date
      ,action
      ,DATETIME_ADD(last_updated_time, INTERVAL 7 hour)                              AS last_updated_time
      ,DATETIME_ADD(platinum_refresh, INTERVAL 7 hour)                               AS platinum_refresh
FROM platinum_buymed_vn.circa_online_prd_order_order_item 
)
SELECT a.*
       ,origin_price - price AS discount_amount
       ,d.deal_code
       ,d.deal_name
       ,d.campaign_code
       ,d.campaign_name
FROM base_data a 
LEFT JOIN ${source.ref}.dim_promotion_event_circa d ON a.promotion_event_id = d.id 

