config {
    type: "table",
    //disabled: true,
    description: `Last 13 month| PIC: huyen.ngo`,
    tags: ["10h30"],
    name: "circa_pos_profile"
}
with t as (
select p.*
       ,s.* except (status)
       ,case when p.code = 'POS0010' then 'Active'
       else s.status end as actual_status
from ${source.circa_os}.entity_pos_profile p 
left join ( Select * from  ${source.external}.circa_store_status 
--where store_format like '%Circa%'
) s on p.code = s.pos_code
where type in ('CIRCA', 'FS')
    and code not in ('POS0006','POS0024','POS0030','POS0001','POS0047','POS0020','POS0020')
    --and s.pos_code is null
   
)
Select timestamp_add(current_timestamp(), interval 7 hour) as transformed_at
       ,t.*
      ,customer_level
from t 
left join ${source.ref}.dim_customer m on t.thuocsi_id = m.customer_id