config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At minute 10 every 1 hour.Circa online order item `,
    tags: ["circa_online"],
    name: "circa_online_order_item",
    columns: {
       
    },
    bigquery: {
        partitionBy: "created_date"
    }
}

WITH base_data AS (
  SELECT
      TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR)                             AS transformed_at
    , t.product_id
    , CASE 
          WHEN SAFE_CAST(JSON_VALUE(t.extra_props, '$.origin_price') AS INT64) IS NULL 
               THEN t.price
          ELSE SAFE_CAST(JSON_VALUE(t.extra_props, '$.origin_price') AS INT64)
      END                                                                             AS origin_price
    , JSON_VALUE(t.extra_props, '$.promotion_event_id')                               AS promotion_event_id
    , ARRAY_TO_STRING(
          ARRAY(
              SELECT JSON_EXTRACT_SCALAR(tag)
              FROM UNNEST(JSON_EXTRACT_ARRAY(t.extra_props, '$.tags')) AS tag
          ), 
          ' ,'
      )                                                                               AS tag_list
    , t.unit
    , t.unit_code
    , t.price
    , t.quantity
    , JSON_value(t.extra_props, '$.reserved_quantity')                              AS reserved_quantity
    , t.order_id
    , t.order_code
    , t.total_price
    , DATETIME_ADD(t.created_time, INTERVAL 7 HOUR)                                   AS created_time
    , DATE(DATETIME_ADD(t.created_time, INTERVAL 7 HOUR))                             AS created_date
    , t.action
    , DATETIME_ADD(t.last_updated_time, INTERVAL 7 HOUR)                              AS last_updated_time
    , DATETIME_ADD(t.platinum_refresh, INTERVAL 7 HOUR)                               AS platinum_refresh
  FROM platinum_buymed_vn.circa_online_prd_order_order_item t
), base_unit_selection AS (
    SELECT DISTINCT
         product_id
        ,client_id
        ,base_unit
        ,ROW_NUMBER() OVER (PARTITION BY product_id, client_id ORDER BY COUNT(*) DESC) AS rn
    FROM ${source.ref}.cos_product_convert_base_unit
    WHERE client_id = 1
    GROUP BY product_id, client_id, base_unit
)
,base_unit AS (
    SELECT a.*
    FROM ${source.ref}.cos_product_convert_base_unit a
    LEFT JOIN base_unit_selection b 
        ON a.product_id = b.product_id
        AND a.client_id = b.client_id
        AND a.base_unit = b.base_unit
    WHERE b.rn = 1
)

SELECT
    a.* 
  , a.quantity * cv.convert_rate AS base_quantity
  , cv.base_unit
  , CASE WHEN tag_list like '%deal_1000%' AND price = 1000 THEN TRUE ELSE FALSE END                   AS is_deal1k 
  , origin_price - price                                                                              AS discount_amount
  , d.deal_code
  , d.deal_name
  , d.campaign_code
  , d.campaign_name
  ,product_name
FROM base_data a
LEFT JOIN ${source.ref}.dim_promotion_event_circa d  ON a.promotion_event_id = d.id
LEFT JOIN (SELECT * FROM ${source.ref}.cos_dim_product WHERE client_id = 1) p on a.product_id = p.product_id
LEFT JOIN base_unit cv ON a.product_id = cv.product_id AND a.unit = cv.convert_unit
 
