config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At minute 10 every 1 hour.Circa online order `
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past10"],
    name: "circa_online_order",
    columns: {
        order_code: "NonNull |" + docs.order_code,
        account_id: "NonNull | The unique identifier for each customer"
       
    },
    bigquery: {
        partitionBy: "date(delivery_time)"
    }
}
WITH created_by AS (
            SELECT DISTINCT order_code, event_name, action_by_name 
            FROM platinum_buymed_vn.circa_online_prd_order_order_event
            WHERE event_name  = 'CREATE_ORDER'
               OR event_name = 'ADMIN_CREATE_ORDER'
     )
, delivery_time AS (
    SELECT DISTINCT order_code
                    ,DATETIME_ADD(synced_at, INTERVAL 7 HOUR) AS last_status_time
    FROM platinum_buymed_vn.circa_online_prd_order_order_event
    -- WHERE order_code = 'DH000938'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY order_code ORDER BY synced_at DESC) = 1
)
, online_order AS (
SELECT TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR)                           AS transformed_at
      ,o.order_code
      ,order_id
      ,customer_phone
      ,receiver_code
      ,receiver_name
      ,receiver_phone_number
      ,action_by_name                                                                AS create_order_by
      ,account_id                                                                    -- tạo tài khoản sẽ có account_id, ko tạo tk ~ acount_id = 0
      ,payment_method                                                                --Banking/COD
      ,payment_status                                                                --COMPLETED/WAIT_FOR_PAYMENT/NULL
      ,deliver_method                                                                --FAST/NORMAL
      ,price
      ,total_price
      ,total_discount
      ,total_product
      ,DATETIME_ADD(created_time, INTERVAL 7 hour)                                   AS created_time
      ,DATE(DATETIME_ADD(created_time, INTERVAL 7 hour))                             AS created_date
      ,DATETIME_ADD(last_updated_time, INTERVAL 7 hour)                              AS last_updated_time
      ,DATETIME_ADD(delivery_date, INTERVAL 7 hour)                                  AS delivery_time
      ,DATETIME_ADD(paid_time, INTERVAL 7 hour)                                      AS paid_time
      ,DATETIME_ADD(platinum_refresh, INTERVAL 7 hour)                               AS platinum_refresh
      ,l.last_status_time
      ,o.type                                                                        AS customer_type
      ,o.status                                                                      AS o2o_status -- DELIVERED/WAIT_TO_DELIVER/WAIT_TO_CONFIRM/CANCEL  
      ,o.cancellation_type
      ,o.cancellation_note
      ,sale_order_status                                                             --NULL/WAIT_TO_DELIVER/NEW/DELIVERED/CANCELED/FAIL_TO_DELIVER
      ,i.order_code                                                                  AS assigned_order_codes
      ,i.pos_id                                                                      AS assigned_pos_id  
      ,p.code                                                                        AS assigned_pos_code 
      ,p.name                                                                        AS assigned_pos_name
FROM platinum_buymed_vn.circa_online_prd_order_order o 
LEFT JOIN (
    SELECT DISTINCT order_code, reference_order_in_platform, pos_id
    FROM ${source.ref}.cos_fact_order 
    WHERE channel = 'O2O' 
          AND status IN ('COMPLETED', 'COMPLETE_SHIPPING','AWAITING_SHIPMENT','SHIPPING','FAILED_SHIPMENT','PICKING')
    ) i ON o.order_code = i.reference_order_in_platform
LEFT JOIN created_by c ON c.order_code = o.order_code
LEFT JOIN delivery_time l ON l.order_code = o.order_code
LEFT JOIN ${source.ref}.circa_pos_profile p on i.pos_id = p.id
)

SELECT o.*
       ,v.code AS voucher_code 
FROM online_order o
LEFT JOIN ${source.ref}.cos_voucher_info v ON o.assigned_order_codes = v.order_code_used