config {
    type: "table",
    //disabled: true,
    description: `PIC: huyen.ngo`,
    tags: ["10h30"],
    name: "circa_pos_profile"
}




WITH t AS (
SELECT p.* except(thuocsi_id)
     ,CASE WHEN code = 'POS0042' THEN 30365
           WHEN code = 'POS0043' THEN 56487
           WHEN code = 'POS0046' THEN 89
           WHEN code = 'POS0054' THEN 362470
     ELSE thuocsi_id END AS thuocsi_id
     ,s.* EXCEPT (status)
     ,CASE WHEN p.code = 'POS0010' THEN 'Active'
           ELSE s.status
      END AS actual_status
FROM ${source.circa_os}.entity_pos_profile p 
LEFT JOIN (SELECT * FROM ${source.external}.circa_store_status 
           --WHERE store_format LIKE '%Circa%'
          ) s ON p.code = s.pos_code
WHERE type IN ('CIRCA', 'FS')
  AND code NOT IN ('POS0006','POS0024','POS0030','POS0001','POS0047','POS0020','POS0020')
  --AND s.pos_code IS NULL
)

SELECT TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) AS transformed_at
     ,t.*
     
     ,customer_level
FROM t 
LEFT JOIN ${source.ref}.dim_customer m ON t.thuocsi_id = m.customer_id
