
config {
    type: "table",
    description: `Circa OS Transaction order item detail 
                  PIC: huyen.ngo; 
                  model_type: Table ;
                  schedule: At minute 20 every hour`,
    tags:  ["custom_1h_past20"],
    name: "circa_cogs_thuocsi",
    columns: {
    
    },
    bigquery: {
        partitionBy: "created_date"
    }
}

        SELECT
              created_date
            , order_id
            , sub_product_id AS product_id
            , price
            , SUM(outbound_quantity) AS outbound_quantity
            , SUM(outbound_quantity * 	rebate_without_reserve ) / NULLIF(SUM(outbound_quantity), 0) AS unit_cost_price
        FROM gold_buymed_vn2.fact_order_item_margin_internal_outbound
        WHERE created_date >= '2024-10-01'
            -- and order_id = 37245644
        GROUP BY ALL
        UNION ALL
        SELECT
              a.created_date
            , a.order_id
            , a.product_id
            , price
            , SUM(outbound_quantity) AS outbound_quantity
            , SUM(cogs * outbound_quantity)/ NULLIF(SUM(outbound_quantity), 0) AS unit_cost_price
        FROM gold_buymed_vn2.fact_order_item_margin_seller_for_circa AS a
        WHERE 1=1 
            AND a.created_date >= '2024-10-01'
        GROUP BY ALL
