config {
    type: "table", 
    description: 
        `PIC: huyen.ngo; 
        Current inventory,
        Type: Table; 
        Refresh Schedule: At minute 20 past hour;
        `,
    tags: ["custom_1h_past20"],
    columns: {
    }}

SELECT DISTINCT o.id
               ,o.code 
               ,o.pos_id 
               ,o.reason
               ,DATETIME_ADD (o.created_at, INTERVAL 7 HOUR) AS created_at 
               ,DATETIME_ADD(o.updated_at, INTERVAL 7 HOUR) AS updated_at
               ,DATETIME_ADD(o.completed_at, INTERVAL 7 HOUR) AS completed_at
               ,e.name AS updated_by
               ,product_id
               ,lot_date
               ,is_increase 
               ,SUM (
                    CASE WHEN is_increase = true THEN 1
                         ELSE -1 END * quantity_change
                    ) AS quantity_change
               ,SUM (
                    CASE WHEN is_increase = true THEN 1
                         ELSE -1 END * base_quantity_change
                    ) AS  base_quantity_change
               ,location_detail_id
               --,location_id
               ,l.name AS location_name
               ,unit_id
               ,CONCAT(i.product_id, o.client_id) AS product_client_id
FROM ${source.circa_os}.inventory_change_quantity o 
LEFT JOIN ${source.circa_os}.inventory_change_quantity_item i ON o.id = i.change_quantity_id
LEFT JOIN ${source.circa_os}.entity_entity e ON o.updated_by = e.id AND o.client_id = e.client_id 
LEFT JOIN ${source.circa_os}.inventory_location l ON i.location_id = l.id AND o.client_id = l.client_id 
-- where o.client_id = 35 
--        and o.code = 'ADQ03671'
GROUP BY ALL