config {
    type: "table",
    description: `circa_cogs_thuocsi_by_po
                  PIC: huyen.ngo; 
                  model_type: Table ;
                  schedule: At minute 20 every hour`,
    tags:  ["custom_1h_past23"],
    name: "circa_cogs_thuocsi_by_po",
    columns: {
    
    }
    ,
    bigquery: {
        partitionBy: "created_date"
    }
}

WITH base_unit_selection AS (
    SELECT
         product_id
        ,client_id
        ,base_unit
        ,ROW_NUMBER() OVER (
            PARTITION BY product_id, client_id
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM `lakehouse-prod-394907.gold_buymed_vn2.cos_product_convert_base_unit`
    GROUP BY
         product_id
        ,client_id
        ,base_unit
),

base_unit AS (
    SELECT
         a.*
    FROM `lakehouse-prod-394907.gold_buymed_vn2.cos_product_convert_base_unit` a
    JOIN base_unit_selection b
      ON a.product_id = b.product_id
     AND a.client_id  = b.client_id
     AND a.base_unit  = b.base_unit
    WHERE b.rn = 1
),

t AS (
    SELECT
        created_date
        ,i.po_code
        ,o.client_id
        ,o.order_id
        ,i.product_id
        ,CASE WHEN o.po_code = 'PO00026356' AND product_id = 5398 THEN 'hộp'
              ELSE i.unit END AS unit
        ,SUM(i.quantity)  AS qty
        ,AVG(i.unit_price) AS avg_unit_price
    FROM `gold_buymed_vn2.cos_purchase_order_item` i
    JOIN `gold_buymed_vn2.cos_purchase_order` o ON o.po_id = i.po_id
    WHERE o.fulfillment_method = 'SO_THUOCSI'
      AND o.client_id = 1
      AND o.po_status NOT IN ('SEPERATED','PENDING','WAIT_FOR_ORDER','CANCELED')
      AND i.unit_price <> 0
    GROUP BY ALL
),

p AS (
    SELECT
         CAST(order_id AS STRING) AS order_id
        ,product_id
        ,AVG(unit_cost_price) AS avg_unit_cost_price
    FROM `gold_buymed_vn2.circa_cogs_thuocsi`
    GROUP BY
         order_id
        ,product_id
),

final AS (
    SELECT DISTINCT
          created_date
         ,t.po_code
        ,t.client_id
        ,t.order_id
        ,t.product_id
        ,t.unit
        ,t.qty
        ,t.avg_unit_price
        ,p.avg_unit_cost_price
        ,cv.convert_rate
        ,cv.base_unit
    FROM t
    LEFT JOIN p ON t.order_id  = p.order_id AND t.product_id = p.product_id
    LEFT JOIN base_unit cv ON t.client_id  = cv.client_id
                             AND t.product_id = cv.product_id
                             AND t.unit       = cv.convert_unit
)

SELECT
     *
    ,SAFE_DIVIDE(avg_unit_cost_price, convert_rate) AS cogs_base_unit_ts
FROM final
