
config {
    type: "table",
    description: `cos_demand_planning detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_2h_past5"],
    name: "clearance_sale_sep",
    columns: {
        
    }
}


with base_data as (
      Select * 
       ,concat(product_id, "_", 1) as product_client_id
       ,concat(product_id, "_", pos_code) as product_pos_code
from buymed_external.clearance_sale_sep
where product_id is not null
qualify row_number() over(partition by product_id,pos_code order by product_id desc ) =1
)

Select base_data.* 
       ,r.convert_rate
from base_data 
left join ${source.circa_os}.product_retail_unit r on base_data.product_id = r.product_id
                                                    and base_data.unit = r.unit
where r.client_id = 1

