
config {
    type: "table",
    description: `cos_demand_planning detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_2h_past5"],
    name: "clearance_sale_sep",
    columns: {
        
    }
}


Select * 
       ,concat(product_id, "_", 1) as product_client_id
from buymed_external.clearance_sale_sep
where product_id is not null
qualify row_number() over(partition by product_id,pos_code order by product_id desc ) =1

