config {
    type: "table",
    description: `compare_price_fs_thuocsi
             PIC: huyen.ngo; model_type: Table ;schedule: At minute 23 past hour`,
    tags: ["custom_1h_past23"],
    name: "compare_price_fs_thuocsi",
}

SELECT
    o.*
    , r.base_unit
    , t.* EXCEPT(product_id, fc_code)
    , ROUND(t.min_price_thuocsi / convert_rate) AS min_base_unit_price_thuocsi
    , CASE
        WHEN unit_price > min_price_thuocsi THEN '> thuocsi_price'
        WHEN unit_price < min_price_thuocsi THEN '< thuocsi_price'
        WHEN unit_price = min_price_thuocsi THEN '= thuocsi_price'
        ELSE NULL
      END AS compare_price
    , CONCAT(o.product_id, "_", o.client_id) AS product_client_id
    , 'yes' AS is_same_unit
FROM ${ref('circafs_lastest_price')} o
LEFT JOIN ${ref('thuocsi_price_fs')} t
    ON o.product_id = t.product_id
    AND o.fc_code = t.fc_code
LEFT JOIN ${source.ref}.cos_product_convert_base_unit r
    ON o.product_id = r.product_id
    AND o.unit = r.convert_unit
    AND o.client_id = r.client_id
WHERE o.unit = LOWER(t.thuocsi_unit)

UNION ALL

SELECT
    o.*
    , r.base_unit
    , t.* EXCEPT(product_id, fc_code)
    , ROUND(t.min_price_thuocsi / convert_rate) AS min_base_unit_price_thuocsi
    , CASE
        WHEN ROUND(o.base_unit_price) > ROUND(t.min_price_thuocsi / convert_rate) THEN '> thuocsi_price'
        WHEN ROUND(o.base_unit_price) < ROUND(t.min_price_thuocsi / convert_rate) THEN '< thuocsi_price'
        WHEN ROUND(o.base_unit_price) = ROUND(t.min_price_thuocsi / convert_rate) THEN '= thuocsi_price'
        ELSE 'can_not_convert_unit'
      END AS compare_price
    , CONCAT(o.product_id, "_", o.client_id) AS product_client_id
    , 'no' AS is_same_unit
FROM ${ref('circafs_lastest_price')} o
LEFT JOIN ${ref('thuocsi_price_fs')} t
    ON o.product_id = t.product_id
    AND o.fc_code = t.fc_code
LEFT JOIN ${source.ref}.cos_product_convert_base_unit r
    ON o.product_id = r.product_id
    AND LOWER(t.thuocsi_unit) = LOWER(r.convert_unit)
    AND o.client_id = r.client_id
WHERE o.unit <> LOWER(t.thuocsi_unit)