config {
    type: "table",
    description: ` PIC: huyen.nguyen; model_type: Table ;schedule: At minute 5 past hour 6, 8, 10, 12, 14, 16, 18, 20 and 22`,
    tags: ["custom_2h_past5"]
}

with product_base_unit as
    (select product_id,
            unit as convert_unit,
            convert_rate
     from  ${source.circa_os}.product_retail_unit
     )

    , inventory as (
    select a.product_id,
           sum(a.on_hand_qty) as on_hand_quantity,
           b.pos_id,
           a.seller_code,
           sku_code
    from  ${source.circa_os}.inventory_location_detail as a
    left join  ${source.circa_os}.inventory_location as b on a.location_id = b.id
    where deleted_at is null
    group by all),

full_unit as (SELECT
    i.pos_id,
    ru.product_id,
    ru.unit,
    ru.convert_rate,
    ru.base_unit,
    i.seller_code
FROM  inventory AS i
JOIN  ${source.circa_os}.product_retail_unit AS ru
    ON i.product_id = ru.product_id
GROUP BY ALL),

inventory_full_unit as (select i.pos_id
    , i.product_id
    , u.unit
    , u.convert_rate
    , i.on_hand_quantity
    , i.seller_code
    , i.sku_code
    , u.base_unit
    , i.product_id || '_' || u.unit || '_' || i.pos_id          as sku_unit_pos
from inventory i
left join full_unit u on i.pos_id = u.pos_id and i.product_id = u.product_id),

has_price as (
    select
        ps.pos_id,
        pd.product_id,
        pd.seller_code,
        pd.sku_code,
        pd.sale_price,
        pd.unit,
        bu.convert_rate,
        pd.product_id || '_' || pd.unit || '_' || ps.pos_id as sku_unit_pos,
        case when bu.product_id is not null then true else false end as is_thuocsi_unit,
        max(datetime(pd.updated_at, "Asia/Ho_Chi_Minh")) as last_updated_at
    from  ${source.circa_os}.product_price_sheet_detail as pd
    left join  ${source.circa_os}.product_price_sheet as ps on pd.price_sheet_id = ps.id
    left join product_base_unit as bu on pd.product_id = bu.product_id and pd.unit = bu.convert_unit
    group by all),

count_ord as ( select o.pos_id,
                    oi.product_id,
                    max(o.created_date) as latest_ord,
                    COUNT(distinct o.order_id) as no_ord,
                    SUM(unit_price * quantity) AS GMV
             from ${ref('cos_fact_order')} o
             left join ${ref('cos_fact_order_item')} oi
                        on o.order_id = oi.order_id
             where status like "%COMPLETE%"
             group by 1,2),

combine_has_stock as (select i.product_id,
           i.pos_id,
           i.seller_code,
           i.sku_code,
           i.unit,
           i.convert_rate,
           p.is_thuocsi_unit,
           i.base_unit as is_base_unit,
           p.last_updated_at,
           p.sale_price as sale_unit_price,
           i.sku_unit_pos,
           case when i.on_hand_quantity > 0 then "Available" else "Unavailable" end as have_stock,
           case when p.sale_price is null then "Price not set" else "Price set" end as price_set_check,
            case when DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<16 THEN "15D"
            WHEN DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<31 THEN "30D"
            WHEN DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<46 THEN "45D"
            WHEN DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<61 THEN "60D"
            WHEN DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<90 THEN "90D" else "Others" END AS latest_date_order_range,
            case when DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<16 and on_hand_quantity >0 THEN "DEAD-1:No-Demand 15D"
            WHEN DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<31 and on_hand_quantity >0 THEN "DEAD-2:No-Demand 30D"
            WHEN DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<46 and on_hand_quantity >0 THEN "DEAD-3:No-Demand 45D"
            WHEN DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<61 and on_hand_quantity >0 THEN "DEAD-4:No-Demand 60D"
            WHEN DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<90 and on_hand_quantity >0 THEN "DEAD-5:No-Demand 90D"
            else "Others" END AS stock_aging_type,
            no_ord,GMV,
            latest_ord,
            on_hand_quantity
    from inventory_full_unit i
    left join has_price p
        on i.pos_id = p.pos_id and i.product_id = p.product_id and i.seller_code = p.seller_code and i.unit = p.unit
    left join count_ord co on i.pos_id = co.pos_id and i.product_id = co.product_id
    group by all),

has_price_non_stock as (
        select p.product_id,
           p.pos_id,
           p.seller_code,
           p.sku_code,
           p.unit,
           p.convert_rate,
           p.is_thuocsi_unit,
           u.base_unit as is_base_unit,
           p.last_updated_at,
           p.sale_price as sale_unit_price,
           p.sku_unit_pos,
           "Unavailable" as have_stock,
           case when p.sale_price is null then "Price not set" else "Price set" end as price_set_check,
           "Others" as latest_date_order_range,
            "Others" AS stock_aging_type,
            0 as no_ord,
            0 as GMV,
            CAST(NULL AS DATE) as latest_ord,
            0 as on_hand_quantity
    from has_price p
    left join full_unit u on p.pos_id = u.pos_id and p.product_id = u.product_id
    where concat(p.pos_id, p.product_id, p.seller_code, p.unit) not in (select concat(pos_id, product_id, seller_code, unit) from combine_has_stock)
),

combine as (
    select * from combine_has_stock
    union all
    select * from has_price_non_stock
),

check_unit_pricing as
    (
        select product_id,
               pos_id,
               max(case when sale_unit_price >= 0 then 0 else 1 end ) as check_price_unit
        from combine
        where unit is not null
        group by all
    ),
    cte_os as (
        select
            id as pos_id,
            province,
            s.sales_region_code
        from  ${source.circa_os}.entity_pos_profile m
        left join ${ref('dim_fc_service_area')} s on m.province = s.service_area_code),

    cte_fs as (
        select
            id as pos_id,
            province,
            s.sales_region_code
        from buymed_circa.entity_pos_profile m
        left join ${ref('dim_fc_service_area')} s on m.province = s.service_area_code
        where id in ("b6c40920-af79-4fb0-bdc4-9965ddb885d2", "e737c882-e90c-4fd2-8a4f-ac6afd248a33")
        ),

    pos_region as (
    select * from cte_fs
    union all
    select * from cte_os)
select i.*,
       case when (cup.check_price_unit = 1 and i.unit is not null) or price_set_check like "Price not set" then "contain unit not set"
       else "set full" end as check_unit_price_set,
       pr.sales_region_code
from combine i
left join check_unit_pricing cup on i.product_id= cup.product_id and i.pos_id = cup.pos_id
left join pos_region pr on i.pos_id = pr.pos_id
group by all