config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every 2 hours.Circa OS Transaction order `
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past5"],
    name: "cos_fact_order",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}
with return_cancel as (
    select o.code
    from ${source.circa}.order_order o
    left join ${source.circa}.entity_pos_profile p on o.pos_id = p.id
        where pos_id in ("b6c40920-af79-4fb0-bdc4-9965ddb885d2", "e737c882-e90c-4fd2-8a4f-ac6afd248a33")
              and o.type = 'RETURN' 
              and (o.status = 'CANCELED' or o.status = 'PENDING')
    
    union all
    select c.code
    from ${source.circa_os}.order_return_order c
    left join ${source.ref}.circa_pos_profile p on c.pos_id = p.id
        where (c.status = 'CANCELED' or c.status = 'PENDING')
),
cte_fs as
    (select o.id as order_id
       ,pos_id, p.code as pos_code
       ,entity_id
       ,o.code as order_code
       ,o.total_amount
       ,actual_total_item_amount
       ,o.total_item_amount
       ,discount_amount
       ,o.created_by
       ,o.updated_by
       ,en.name
       ,o.status
       ,o.note, o.type
       ,o.source_type
       ,delivery_type
       ,channel
       ,date(datetime_add(o.created_at, interval 7 hour)) as created_date
       ,datetime_add(o.created_at, interval 7 hour) as created_at
       ,fulfillment_status
       ,cast (null as string) as reference_order_in_platform
       ,cast(null as string) as origin_order_id
       ,cast (null as timestamp) as end_pick_at
       ,datetime_add(completed_at, interval 7 hour) as completed_at
       ,date(datetime_add(completed_at, interval 7 hour))  as completed_date
       ,cast (null as timestamp) as delivery_scheduled_time
       ,cast (null as timestamp) as pre_order_scheduled_time
       , cast (null as string) as pre_order_required
       ,medicine_cutting_fee
       ,string_agg(CAST(return_id as string)) as return_codes
       ,1 as client_id
from ${source.circa}.order_order o
left join UNNEST(JSON_VALUE_ARRAY(order_return_codes)) AS return_id
left join ${source.circa}.entity_pos_profile p on o.pos_id = p.id
left join ${source.circa}.entity_entity en on o.updated_by = en.id
where pos_id in ("b6c40920-af79-4fb0-bdc4-9965ddb885d2", "e737c882-e90c-4fd2-8a4f-ac6afd248a33")
      and o.type <> 'RETURN'
group by all)
,cte_os as
    (select o.id as order_id
       ,pos_id, p.code as pos_code
       ,entity_id
       ,o.code as order_code
       ,o.total_amount -- Tiền hàng + phí cắt liều - giảm giá
       ,actual_total_item_amount --hình như giống o.total_item_amount
       ,o.total_item_amount -- tiền hàng
       ,discount_amount -- khuyến mãi 
       ,o.created_by
       ,o.updated_by
       ,en.name
       ,o.status
       ,o.note
       ,o.type
       ,o.source_type
       ,delivery_type
       ,channel
       ,date(datetime_add(o.created_at, interval 7 hour)) as created_date
       ,datetime_add(o.created_at, interval 7 hour) as created_at
       ,fulfillment_status
       ,reference_order_in_platform
       ,o.origin_order_id
       ,datetime_add(o.end_pick_at, interval 7 hour) as end_pick_at
       ,coalesce(datetime_add(o.completed_at, interval 7 hour),datetime_add(o.updated_at, interval 7 hour))  as completed_at
       ,coalesce(date(datetime_add(o.completed_at, interval 7 hour)),date(datetime_add(o.updated_at, interval 7 hour)))  as completed_date
       ,datetime_add(delivery_scheduled_time, interval 7 hour) as delivery_scheduled_time
       ,datetime_add(pre_order_scheduled_time, interval 7 hour) as pre_order_scheduled_time
       ,cast(pre_order_required as string) as pre_order_required
       ,medicine_cutting_fee -- tiền cắt liều
       ,string_agg(CAST(return_id as string)) as return_codes
       ,o.client_id
from ${source.circa_os}.order_order o
left join UNNEST(JSON_VALUE_ARRAY(order_return_codes)) AS return_id
left join ${source.ref}.circa_pos_profile p on o.pos_id = p.id and o.client_id = p.client_id
left join ${source.circa_os}.entity_entity en on o.updated_by = en.id
where o.type <> 'RETURN'
      and o.status <> 'PENDING'
      and p.id is not null
group by all)
select
    *
    , case
        when return_codes is null or return_codes in (select * from return_cancel) then "NORMAL"
        else "RETURN"
    end as order_type
from cte_fs
union all
select
    *
    , case
        when return_codes is null or return_codes in (select * from return_cancel) then "NORMAL"
        else "RETURN"
    end as order_type
from cte_os
--gmv = Giá bán * sản phẩm + bất kì phí nào khác (hiện tại có phí cắt liều) - những đơn return hoặc return 1 phần  = total_item_amount + medicine_cutting_fee - return
