
config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    name: "cos_sku_oos_sup",
    columns: {/*
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"*/
        
    }
}
 
with stock_status as (
    Select distinct
         product_id
        ,pos_id
        ,cutoff_date_index
        ,sum(on_hand_qty) as total_quantity
        ,a.client_id
    from buymed_circa_v2.inventory_location_detail_historical_cut_off a 
    left join buymed_circa_v2.inventory_location as b on a.location_id = b.id
    where a.client_id = 1 
          and b.client_id = 1
    group by all
),
zero_stock_candidates AS (
    Select
        s.product_id
        ,s.pos_id
        ,min(s.cutoff_date_index) as first_zero_date
        ,client_id
    from stock_status s
    where s.total_quantity = 0
      and not exists (
          Select 1
          from stock_status ss
          where ss.product_id = s.product_id
                and ss.pos_id = s.pos_id
                and ss.cutoff_date_index > s.cutoff_date_index
                and ss.total_quantity > 0
      )
    group by all
)
,zero_and_stable_inventory as (
Select distinct
    z.product_id
    ,z.pos_id
    ,z.first_zero_date
    ,p.name as pos_name
    ,z.client_id
from zero_stock_candidates z
left join `buymed_circa_v2.entity_pos_profile` p on z.pos_id = p.id
where p.type = 'CIRCA'
      and pos_id not in ('c95a3338-4f5e-4264-958b-0d02e3fea49b','0d4c2e76-c6bf-487d-bf3e-d0b608d9fb5d')
order by product_id
)
select distinct
  a.product_id
  ,a.pos_id
  ,min(first_zero_date) as last_zero_date
  ,st.product_status
  ,date_diff(current_date(), min(first_zero_date), day) as days_since_zero
  ,a.client_id
  ,concat(a.product_id, "_", a.client_id) as product_client_id
from zero_and_stable_inventory a
left join ${source.ref}.cos_sku_status st on a.product_id = st.product_id and  a.pos_id = st.pos_id
where st.product_status ='OOS'
group by all
union all
Select distinct 
 s.product_id
 ,pos_id
 ,DATE(th.created_time)
 ,s.product_status
,date_diff(current_date(), date(th.created_time), day) as days_since_zero
,s.client_id
,concat(s.product_id, "_", s.client_id) as product_client_id
from ${source.ref}.cos_sku_status s
left join (Select distinct product_id,created_time
                        , row_number() over (partition by product_id order by created_time desc) as rn
                          from ${source.ref}.adhoc_pm_master_sku p
                         left join ${source.ref}.staging_sku_status_history t on p.sku_code = t.sku) th on s.product_id = th.product_id
where s.product_status not in (Select distinct product_status from ${source.ref}.cos_sku_status  where product_status = 'OOS' or product_status = 'NORMAL'   )
and created_time >= '2024-05-01'
and rn = 1


