config {
    type: "table", 
    description: 
        `PIC: tu.dang; 
        Type: Table; 
        Refresh Schedule: At minute 10 past hour 7, 10, 13, 16 and 19;
        Source: 
        `,
    tags: ["adhoc-office"],
    columns: {

    }}

With inventory as (select a.product_id,
                          a.lot_date,
                          case
            when tax_rate <= 0 then 0
                else tax_rate end as tax_rate,
                          a.cost_price_include_tax,
                          a.on_hand_qty as on_hand_quantity,
                          a.location_id,
                          a.doc_code, product_id || "_" || lot_date || "_" || tax_rate as product_lot_date_vat
                   from ${source.circa_os}.inventory_location_detail as a
where 
doc_code is not null and 
deleted_at is null  )

SELECT a.*,
       b.pos_id,
    --    ru.unit as base_unit,
       b.location_type, 
    --    ru.sale_allowed,
    --    c.min_cost_price_include_tax,
    --    c.max_cost_price_include_tax,
    --    sku_code || '_' || unit || '_' || b.pos_id as sku_unit_pos
FROM inventory as a
         left join ${source.circa_os}.inventory_location as b on a.location_id = b.id
        --  left join ${source.circa_os}.product_retail_unit as ru on a.product_id = ru.product_id and ru.base_unit = true
        --  left join `${source.circa_os}.inventory_cost_price` as c on c.product_id = a.product_id and c.pos_id =b.pos_id
-- WHERE deleted_at is null