config {
    type: "table",
    description: ` PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 past hour 6, 8, 10, 12, 14, 16, 18, 20 and 22`,
    name: "cos_stock_aging_type",
    tags: ["custom_2h_past5"]
}


with count_ord as ( select distinct o.pos_id
                    ,oi.product_id
                    ,max(o.created_date) as latest_ord
                    ,count(distinct o.order_id) as no_ord
                    ,sum(unit_price * quantity) as GMV
                    ,sum(unit_cost_price * quantity) as cogs
                    ,o.client_id
             from  ${source.ref}.cos_fact_order o
             left join  ${source.ref}.cos_fact_order_item oi
                        on o.order_id = oi.order_id
             where status like "%COMPLETE%"
                   and o.client_id = 1
                   and owner_name not in ('CIRCA MARKETING')
             group by all)
,first_time_have_inventory as
(
Select distinct l.pos_id
                ,p.name as pos_name
                ,a.product_id
                ,min(date_add(a.created_at, interval 7 hour) ) as firstime_have_inventory
                ,a.client_id
                ,p.code as pos_code
from ${source.circa_os}.inventory_allocation a
left join ${source.circa_os}.inventory_location_detail ld ON a.location_detail_id = ld.id and a.client_id = ld.client_id
left join ${source.circa_os}.inventory_location l on ld.location_id = l.id and a.client_id = l.client_id
left join ${source.ref}.circa_pos_profile p on l.pos_id = p.id  and a.client_id = p.client_id
where a.client_id = 1 
      and p.id is not null
      and ld.seller_code not in ( 'CIRCA_MKP', 'MARKETING')
group by all
),lastdate_pur as (
         Select distinct o.pos_id
                        ,i.product_id
                        ,max(date(i.created_at)) as lastdate_pur
         from ${source.ref}.cos_purchase_order o 
         left join ${source.ref}.cos_purchase_order_item i on o.po_id = i.po_id
         where received_quantity > 0 
                and i.seller_code not in ( 'CIRCA_MKP', 'MARKETING')
                and o.client_id = 1
         group by all 

)
, inventory as (
      Select distinct 
             pos_id
             ,product_id
             ,sum(on_hand_quantity) as stock_qty
             ,sum(on_hand_quantity * cost_price_include_tax) as stock_value
      from  ${source.ref}.cos_fact_inventory
      where client_id = 1
           and seller_code not in ( 'CIRCA_MKP', 'MARKETING')
      group by all
), add_order_range as (

Select a.*
       ,b.GMV
       ,b.cogs
       ,b.no_ord
       ,b.latest_ord
       ,lastdate_pur
       ,stock_qty
       ,stock_value
       ,case when stock_qty > 0 then 'Available' else 'Unavailable' end as stock_check 
       ,case when DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<16 then "15D"
             when DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<31 and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day ) >= 16 then "30D"
             when DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<46 and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day ) >= 31 then "45D"
             when DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<61 and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day ) >= 46 then "60D"
             when DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day )<91 and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day ) >= 61 then "90D"
             when DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),latest_ord,day ) > 90 then "> 90D" 
             when b.latest_ord is null and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),date(firstime_have_inventory),day )<16 then "15D"
             when b.latest_ord is null and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),date(firstime_have_inventory),day )<31 and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),date(firstime_have_inventory),day ) >= 16 then "30D"
             when b.latest_ord is null and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),date(firstime_have_inventory),day )<46 and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),date(firstime_have_inventory),day ) >= 31 then "45D"
             when b.latest_ord is null and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),date(firstime_have_inventory),day )<61 and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),date(firstime_have_inventory),day ) >= 46 then "60D"
             when b.latest_ord is null and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),date(firstime_have_inventory),day )< 91 and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),date(firstime_have_inventory),day ) >=61 then "90D"
             when b.latest_ord is null and DATE_DIFF(CURRENT_DATE( "Asia/Ho_Chi_Minh"),date(firstime_have_inventory),day ) > 90 then "> 90D" 
             end as latest_date_order_range

 from first_time_have_inventory a
left join count_ord b on a.pos_id = b.pos_id and a.product_id = b.product_id
left join inventory i on a.pos_id = i.pos_id and a.product_id = i.product_id 
left join lastdate_pur p on a.pos_id = p.pos_id and a.product_id = p.product_id 
where a.pos_id not in ('9dd83081-9919-4bc3-84bd-f5dfece10049')
)
Select *
      ,concat(product_id, "_", client_id) as product_client_id
      ,concat(product_id, "_", pos_code) as product_pos_code
      ,case when latest_date_order_range = "15D" THEN "1:No-Demand 15D"
            when latest_date_order_range = "30D" THEN "2:No-Demand 30D"
            when latest_date_order_range = "45D" THEN "3:No-Demand 45D"
            when latest_date_order_range = "60D" THEN "4:No-Demand 60D"
            when latest_date_order_range = "90D" THEN "5:No-Demand 90D"
            when latest_date_order_range = "> 90D" THEN "6:No-Demand > 90D"
      end as stock_aging_type
from add_order_range
