
config {
    type: "table",
    description: `cos_demand_planning detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_2h_past5"],
    name: "cos_demand_planning",
    columns: {
        
    }
}
WITH base_data AS (
    SELECT * 
           ,CONCAT(product_id, "_",1) AS product_client_id
    FROM ${source.external}.cos_demand_planning
    WHERE created_date IS NOT NULL

), _all AS (
    SELECT base_data.* 
           ,CASE 
                WHEN base_data.purchase_unit = 'unit' THEN cv.base_unit
                ELSE base_data.purchase_unit 
            END AS purchase_unit_convert
           ,cv.convert_rate
    FROM base_data 
    LEFT JOIN (
        SELECT DISTINCT a.product_id
                        ,a.unit AS base_unit
                        ,client_id
                        ,CONCAT(product_id, "_",client_id) AS product_client_id
                        ,convert_rate
        FROM ${source.circa_os}.product_retail_unit AS a
        WHERE a.base_unit IS TRUE 
              AND (unit IS NOT NULL OR unit <> "")
              AND client_id = 1
        QUALIFY ROW_NUMBER() OVER(PARTITION BY product_id, client_id ORDER BY updated_at DESC) = 1
    ) cv ON base_data.product_client_id = cv.product_client_id
    WHERE base_data.purchase_unit = 'unit'
          -- AND base_data.product_id = 185548 
          -- AND cv.client_id = 1

    UNION ALL

    -- có unit trong bán lẻ
    SELECT base_data.* 
           ,base_data.purchase_unit AS purchase_unit_convert
           ,r.convert_rate
    FROM base_data 
    LEFT JOIN ${source.circa_os}.product_retail_unit r ON base_data.product_id = r.product_id
                                                       AND base_data.purchase_unit = r.unit
    WHERE base_data.purchase_unit <> 'unit'
          AND r.client_id = 1

    UNION ALL

    -- ko có unit trong bán lẻ
    SELECT base_data.* 
           ,base_data.purchase_unit AS purchase_unit_convert
           ,1 AS convert_rate
    FROM base_data 
    WHERE base_data.purchase_unit <> 'unit'
          AND CONCAT(product_id, "_",purchase_unit) NOT IN (
              SELECT DISTINCT CONCAT(product_id, "_",unit) AS product_client_id
              FROM ${source.circa_os}.product_retail_unit
              WHERE client_id = 1
          )

)
SELECT * EXCEPT (line_amount)
       ,CASE 
            WHEN line_amount IS NULL THEN purchase_price_after_vat * qty_to_order 
            ELSE line_amount 
        END AS line_amount
FROM _all
-- where channel = 'EXTERNAL'
--        and _all.created_date = '2025-09-05'


