config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every 2 hours.Circa /cos_order_item_demand `
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past5"],
    name: "cos_product_loss_sale",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}



Select distinct p.name 
                ,date(datetime_add(o.created_at, interval 7 hour)) as created_date
                ,datetime_add(o.created_at, interval 7 hour) as created_at
                ,datetime_add(o.date_time, interval 7 hour) as date_time
                ,datetime_add(o.updated_at, interval 7 hour) as updated_at
                ,o.id
                ,unit
                ,unit_id
                ,product_id
                ,product_name
                ,unit
                ,price
                ,quantity
                ,total_amount
                ,o.client_id
                ,concat(product_id, "_", 1) as product_client_id
from ${source.circa_os}.product_product_loss_sale o
left join ${source.ref}.circa_pos_profile p on o.pos_id = p.id 
where p.id is not null 

