config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour;Table này dùng để tracking những đơn hàng đã được đặt nhưng hàng chưa về, sử dụng cho report Purchase Planner`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past5"],
    name: "cos_pending_purchase",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}

with t as
(Select 
        i.* 
        ,dis.seller_code
from ${source.circa_os}.order_purchase_order i
left join ${source.circa_os}.entity_distributor  dis on dis.id = i.distributor_id and i.client_id = dis.client_id
WHERE Status <> 'WAITING_PAYMENT'
      and status <> 'COMPLETED'
      and status <> 'CANCELED'
      and status <> 'SEPERATED'
      and status <> 'PENDING' 
      and i.client_id = 1
      --lấy những đơn đã đặt mua nhưng hàng chưa về 
),Pending_item_external as (
Select distinct
        datetime(t.created_at) as created_at
       ,t.id 
       ,t.pos_id
       ,i.product_id
       ,i.unit
       ,i.sku
       ,t.status as po_status
       ,'' as so_status
       ,i.quantity as quantity
       ,''as base_quantity
       ,t.fulfillment_method
       ,t.code
       ,'' as so_code
      
from t 
left join ${source.circa_os}.order_purchase_order_item i on t.id = i.purchase_order_id
where t.fulfillment_method <> 'SO_THUOCSI'
and date(t.created_at) >=  '2025-04-11'
--Lấy những đơn hàng mua ngoài hoặc import stock
)
,Map_thuocsi as (
Select distinct
        coalesce(datetime(t.created_at),o.created_at) as created_at
       ,t.id 
       ,coalesce(t.pos_id,p.id) as pos_id
       ,a.product_id
       ,td.unit
       ,a.sku_code as sku_code
       ,t.status as po_status
       ,o.order_status as so_status
       ,a.demand_quantity as quantity
       ,''as base_quantity
       ,t.fulfillment_method
       ,t.code
       ,SAFE_CAST(o.order_id as string) as so_code
      
from ${source.ref}.fact_order o 
left join ${source.ref}.fact_order_item a on o.order_id = a.order_id 
left join t on t.sale_order_number = SAFE_CAST(o.order_id as string) and t.seller_code = a.seller_code
left join ${source.ref}.dim_product td on a.product_id = td.product_id
left join ${source.circa_os}.entity_pos_profile p on o.customer_id = p.thuocsi_id
where  TO_JSON_STRING(customer_tags) LIKE "%CIRCACOS%"
       and o.order_status <> 'CANCEL'
       and t.code is not null
       and p.id is not null
       and date(created_date) >=  '2025-06-01' 
group by all
--Lấy những đơn hàng đặt mua thuốc sỉ
)
,not_seperated as (
Select distinct
        coalesce(datetime(t.created_at),o.created_at) as created_at
       ,t.id 
       ,coalesce(t.pos_id,p.id) as pos_id
       ,a.product_id
       ,td.unit
       ,a.sku_code as sku_code
       ,t.status as po_status
       ,o.order_status as so_status
       ,a.demand_quantity as quantity
       ,''as base_quantity
       ,t.fulfillment_method
       ,t.code
       ,SAFE_CAST(o.order_id as string) as so_code
      
from ${source.ref}.fact_order o 
left join ${source.ref}.fact_order_item a on o.order_id = a.order_id 
left join t on t.sale_order_number = SAFE_CAST(o.order_id as string) and t.seller_code = a.seller_code
left join ${source.ref}.dim_product td on a.product_id = td.product_id
left join ${source.circa_os}.entity_pos_profile p on o.customer_id = p.thuocsi_id
where  TO_JSON_STRING(customer_tags) LIKE "%CIRCACOS%"
       and o.order_status <> 'CANCEL'
       and t.code is not null
       and t.seller_code is null
       and p.id is not null
       and date(created_date) >=  '2025-06-01' 
group by all
)
,Pending as (
Select * from Pending_item_external
union all
Select * from Map_thuocsi
union all 
Select * from not_seperated
)
Select p.*
       ,concat(p.product_id, "_", 1) as product_client_id
 from Pending p 
 where p.id not in 
(Select distinct purchase_order_id from ${source.circa_os}.order_goods_receipt where status = 'COMPLETED' and client_id = 1) -- điều kiện này dùng để loại trừ những trường hợp cửa hàng đã nhận hàng nhưng ko bấm hoàn thành trên pos
-- union all
--  Select p.*
--  from Pending p 
--  where p.id is null