config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    name: "cos_sku_status",
    columns: {/*
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"*/
        
    }
}
with base_data as (
Select distinct product_id
from ${source.circa_os}.order_purchase_order_item
where (sku is not null or sku <> '')
     and received_quantity <> 0
) --lấy danh sách sản phẩm đã mua trong quá khứ
,inventory_by_product as (
Select distinct v.product_id
                ,pos_id
                ,sum(v.on_hand_quantity) as current_stock_by_product
                ,td.convert_rate
                ,td.unit 
                ,sum(v.on_hand_quantity)/td.convert_rate as stock_qty
                ,sum(cost_price_include_tax * v.on_hand_quantity) as current_stock_value
                ,p.client_id
from ${source.ref}.cos_fact_inventory v
left join ${source.ref}.circa_pos_profile p on v.pos_id = p.id 
left join ${source.ref}.cos_dim_product td on v.product_id = td.product_id
where p.type = 'CIRCA'
      and p.id is not null
      and seller_code not in ( 'CIRCA_MKP', 'MARKETING')
      and v.location_type <> 'CANCELLED'
group by all
---- tổng tồn kho hiện tại theo product , pos
), by_product as (
Select distinct o.product_id
            , o.* except (product_id)
            ,concat(o.product_id, "_", o.client_id) as product_client_id
            ,case when o.current_stock_by_product > 0 then 'NORMAL'
                    else 'OOS' END AS product_status
from inventory_by_product o
left join base_data on o.product_id = base_data.product_id 
-- lấy trạng thái hiện tại của sản phẩm theo tồn kho, detail by sku
)
Select p.*
        ,ts.sku_system_status as thuocsi_status from by_product p 
left join ${source.ref}.sku_status_thuocsi ts on p.product_id =  ts.product_id
