config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every 2 hours.Circa /cos_order_item_demand `
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past15"],
    name: "cos_product_loss_sale",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}



Select distinct p.name 
                ,o.pos_id
                ,date(datetime_add(o.created_at, interval 7 hour)) as created_date
                ,datetime_add(o.created_at, interval 7 hour) as created_at
                ,datetime_add(o.date_time, interval 7 hour) as date_time
                ,datetime_add(o.updated_at, interval 7 hour) as updated_at
                ,o.id
                ,o.unit
                ,unit_id
                ,o.product_id
                ,o.product_name
                ,case when td.product_categories is null then 'Khác' else td.product_categories end as product_categories
                ,price
                ,quantity
                ,total_amount
                ,o.client_id
                ,concat(o.product_id, "_", o.client_id) as product_client_id
from ${source.circa_os}.product_product_loss_sale o
left join ${source.ref}.circa_pos_profile p on o.pos_id = p.id 
left join  ${source.ref}.cos_dim_product td on o.product_id = td.product_id and o.client_id = td.client_id
where p.id is not null 
     and o.id not in ('8af8dcfb-da91-413c-9ccf-02525bd00876','c5d6fcaf-2d1d-4868-be4c-00b4ae6d7ae8','b729fb2c-7b00-455b-9d28-c5a942bc90fa','03e178f2-4bca-4dbe-9967-134d6618632d','08c9e5da-3ace-478b-a7dd-be17f1f208fb','cca7ed6c-6f2c-40f2-836c-3aad6495105a','b913b653-1268-4d59-bdbe-3b157c2ee469','51ca37f6-fbb8-4dd8-af5e-8d07c09ff8f6')
