config {
    type: "table",
    description: 
        `PIC: huyen.ngo; 
         model_type: table ;
         schedule: At minute 10 every hour;
    Source:
      ${source.circa_os}.inventory_allocation,
      ${source.circa_os}.inventory_location,
      ${source.circa_os}.inventory_location_detail`,
    tags: ["custom_1h_past5"],
    name: "cos_inventory_location_detail_historical",
    columns: {
        
    },
    bigquery: {
        partitionBy: "created_date"
    }
}

WITH cte AS (SELECT
    a.created_at AS created_time,
    DATE(a.created_at) AS created_date,
    l.pos_id,
    a.product_id,
    a.sku_code,
    a.ref_number,
    ld.doc_code,
    ld.doc_type,
    a.type,
    l.location_type,
    a.lot_date,
    ld.tax_rate,
    a.location_id,
   SUM(
      CASE
         WHEN type = 'SALE_ORDERED' THEN -1
         WHEN type = 'RETURN_PURCHASE_ORDER' THEN -1
         WHEN type = 'TRANSFER_OUT' THEN -1
         WHEN type = 'TRANSFER_LOCATION_OUT' THEN -1
         WHEN type = 'CHANGE_QUANTITY_DECREASE' THEN -1
         WHEN type = 'ADD_DETAIL_TRANSFER_IN' THEN -1
         WHEN type = 'GOODS_RETURN_RECEIPT' THEN -1
         WHEN type = 'COMPLETED_PURCHASE_ORDER' then -1
         WHEN type = 'COMPLETED_RETURN_ORDER' then -1
         ELSE 1
      END * base_quantity
   ) AS ending_stock,
   ld.cost_price_include_tax,
   ld.cost_price_without_tax,
   CONCAT(a.product_id, "_", a.lot_date, "_", ld.tax_rate) as product_lotdate_vat
FROM ${source.circa_os}.inventory_allocation a
LEFT JOIN ${source.circa_os}.inventory_location_detail ld ON a.location_detail_id = ld.id
LEFT JOIN ${source.circa_os}.inventory_location l ON ld.location_id = l.id
GROUP BY ALL)

SELECT *
    , SUM(ending_stock) OVER (PARTITION BY pos_id, product_id, sku_code, location_id, lot_date, tax_rate ORDER BY created_time ASC) AS cumulative_ending_stock
from cte
group by all
