config {
    type: "table",
    description: `PIC: huyen.ngo;
                  model_type: Table ;
                  schedule: At minute 15 past hour.Circa voucher - chứa tất cả các voucher, được tạo ra từ đâ, thuộc campaign nào, đã sử dụng hay chưa, sử dụng trong đơn hàng nào `,
    tags: ["custom_1h_past15"],
    name: "cos_voucher_info",
    columns: {
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}

-- Lấy những voucher được tặng cho customers
WITH t AS ( 
    SELECT DISTINCT
         v.gift_id
        ,v.gift_code
        ,DATETIME_ADD(v.created_at, INTERVAL 7 HOUR)                            AS voucher_created_at
        ,voucher_id
        ,voucher_code
        ,customer_id                                                            AS gift_for_customer_id 
        ,JSON_EXTRACT_SCALAR(order_code)                                        AS order_code_created
        ,e.phone_number                                                         AS gift_for_customer_phone
        ,e.name                                                                 AS gift_for_customer_name
        ,pr.code                                                                AS pos_code_create_voucher
        ,pr.name                                                                AS pos_name_create_voucher
    FROM ${source.circa_os}.promotion_gift_voucher v --  voucher dc tặng cho ai 
    LEFT JOIN UNNEST(JSON_EXTRACT_ARRAY(assigned_order_codes))                  AS order_code
    LEFT JOIN ${source.circa_os}.entity_customer e ON v.customer_id = e.id
    LEFT JOIN ${source.ref}.cos_fact_order o ON CAST(JSON_EXTRACT_SCALAR(order_code) AS STRING) = o.order_code
    LEFT JOIN ${source.ref}.circa_pos_profile pr ON o.pos_id = pr.id
    WHERE v.gift_code NOT LIKE '%TEST%'
          --AND pr.id IS NOT NULL
)

,map_voucher AS (
    SELECT DISTINCT
         TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR)                    AS transformed_at
         ,us.id                                                                 AS voucher_id
        ,us.code                                                                AS voucher_code
        ,t.order_code_created
        ,DATETIME_ADD(us.created_at, INTERVAL 7 HOUR)                           AS created_at
        ,DATE(DATETIME_ADD(us.created_at, INTERVAL 7 HOUR))                     AS created_date
        ,DATETIME_ADD(us.start_date, INTERVAL 7 HOUR)                           AS start_date
        ,DATETIME_ADD(us.end_date, INTERVAL 7 HOUR)                             AS end_date
        ,us.discount_value
        ,us.percent
        ,us.promotion_voucher_type
        ,us.is_active
        ,COALESCE(ov.entity_id, gift_for_customer_id)                            AS customer_id
        ,COALESCE(ov.customer_phone, gift_for_customer_phone)                    AS customer_phone
        ,COALESCE(ov.customer_name, gift_for_customer_name)                      AS customer_name
        ,voucher_created_at 
        ,DATE(DATETIME_ADD(ov.created_at, INTERVAL 7 HOUR))                      AS date_used
        ,CASE  
            WHEN ov.created_at IS NOT NULL THEN "Yes" 
            ELSE "No" 
         END                                                                    AS is_used
        ,ov.order_code                                                          AS order_code_used 
        ,ov.channel                                                             AS channel_used
        ,ov.discount_amount                                                     AS actual_discount_amount
        ,cp.campaign_code                                                       AS campaign_code
        ,cp.campaign_name                                                       AS campaign_name
        ,pr.code                                                                AS pos_code_used
        ,pos_code_create_voucher
        ,pos_name_create_voucher
        ,pr.name                                                                AS pos_name_used
        ,us.client_id
    FROM ${source.circa_os}.promotion_promotion_voucher us -- bảng chứa tất cả các mã voucher
    LEFT JOIN (
        SELECT v.*
              ,o.pos_id
              ,o.entity_id
              ,o.channel
              ,o.customer_phone 
              ,o.customer_name
        FROM ${source.circa_os}.order_order_voucher v -- voucher được apply trong đơn hàng
        LEFT JOIN ${source.ref}.cos_fact_order  o ON v.order_code = o.order_code
        WHERE is_valid = TRUE
             AND status <> 'CANCELED'
    ) ov ON ov.voucher_id = us.id
    LEFT JOIN t ON us.code = t.voucher_code
    LEFT JOIN ${source.ref}.circa_pos_profile pr ON ov.pos_id = pr.id
    --LEFT JOIN ${source.circa_os}.entity_customer e ON ov.entity_id = e.id
    LEFT JOIN ${source.ref}.dim_campaign_circa cp -- thông tin campaign
        ON us.promotion_campaign_id = cp.id 
        AND us.client_id = cp.client_id
    WHERE us.is_sample = FALSE
         AND cp.id is not null
          --AND pr.id IS NOT NULL
)

SELECT 
     map_voucher.*
    ,e.id AS customer_id_gift
    ,e.phone_number AS customer_phone_gift -- người tặng voucher
    ,CASE WHEN end_date > TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR)
          THEN FALSE ELSE TRUE
     END                                                                   AS is_expired
    ,concat(map_voucher.voucher_code, '_', map_voucher.client_id) as voucher_key
    ,COALESCE(pos_code_used, pos_code_create_voucher)                      AS pos_code_map
FROM map_voucher
LEFT JOIN ${source.ref}.cos_fact_order o ON map_voucher.order_code_created = o.order_code
LEFT JOIN ${source.circa_os}.entity_customer e ON o.entity_id = e.id
