config {
    type: "table",
    description: `Tracking price for Circa OS
             PIC: huyen.ngo; model_type: Table ;schedule: At minute 15 past hour`,
    tags: ["custom_1h_past15"],
    name: "cos_adhoc_pos_product_client",
}

WITH thuosi_unit AS (
    SELECT DISTINCT product_id
                   ,unit
    FROM ${ref('dim_product')}
)
,product_base_unit AS (
    SELECT DISTINCT product_id
                   ,unit AS convert_unit
                   ,base_unit
                   ,convert_rate
                   ,sale_allowed
                   ,purchase_allowed
                   ,list_price
    FROM ${source.circa_os}.product_retail_unit
    WHERE client_id = 1
)
,count_ord AS (
    SELECT DISTINCT oi.product_id
                   , oi.seller_code
                   ,MAX(o.created_date) AS latest_ord
                   ,COUNT(DISTINCT o.order_id) AS no_ord
                   ,SUM(quantity * unit_price_before_discount) AS GMV
    FROM ${ref('cos_fact_order')} o
    LEFT JOIN ${ref('cos_fact_order_item')} oi ON o.order_id = oi.order_id
    WHERE status LIKE "%COMPLETE%"
         AND o.client_id =1 
    GROUP BY ALL
),L1M AS (
    SELECT DISTINCT oi.product_id
                   , oi.unit
                   , oi.seller_code
                   ,MAX(o.created_date) AS latest_ord_L1M
                   ,COUNT(DISTINCT o.order_id) AS no_ord_L1M
                   ,SUM(quantity * unit_price_before_discount) AS GMV_L1M
    FROM ${ref('cos_fact_order')} o
    LEFT JOIN ${ref('cos_fact_order_item')} oi ON o.order_id = oi.order_id
    WHERE status LIKE "%COMPLETE%"
          AND o.created_date >= CURRENT_DATE() - INTERVAL 1 MONTH
          AND o.client_id =1 
    GROUP BY ALL
)
,inventory AS (
    SELECT DISTINCT a.product_id
                   ,SUM(a.on_hand_quantity) AS on_hand_quantity
                   ,seller_code
                   ,sku_code
    FROM ${ref('cos_fact_inventory')} a
    LEFT JOIN ${ref('circa_pos_profile')} p ON a.pos_id = p.id
    WHERE a.client_id = 1
          AND p.actual_status <> "Inactive"
    GROUP BY ALL
), last_purchase AS (
  SELECT DISTINCT
     product_id
    ,seller_code
    ,unit_price
    ,unit
    ,created_at AS latest_order
FROM (
    SELECT
         i.product_id
        ,i.unit_price
        ,unit
        ,o.client_id
        ,o.created_at
        ,seller_code
        ,ROW_NUMBER() OVER (
             PARTITION BY i.product_id, seller_code
             ORDER BY o.created_at DESC
         ) AS rn
    FROM lakehouse-prod-394907.gold_buymed_vn2.cos_purchase_order o
    LEFT JOIN lakehouse-prod-394907.gold_buymed_vn2.cos_purchase_order_item i ON o.po_id = i.po_id
    WHERE o.client_id = 1
      AND unit_price > 0
)
WHERE rn = 1
)
,full_unit AS (
    SELECT DISTINCT ru.product_id
                   ,ru.convert_unit AS unit
                   ,ru.convert_rate
                   ,seller_code
                   ,ru.base_unit
                   ,ru.list_price
    FROM inventory AS i
    JOIN product_base_unit AS ru ON i.product_id = ru.product_id
    GROUP BY ALL
)
,inventory_full_unit AS (
    SELECT DISTINCT i.product_id
                   ,u.unit
                   ,u.convert_rate
                   ,i.on_hand_quantity
                   ,i.sku_code
                   ,i.seller_code
                   ,u.base_unit
                   ,u.list_price
    FROM inventory i
    LEFT JOIN full_unit u ON i.product_id = u.product_id
)
,has_price AS (
    SELECT DISTINCT s.product_id
                   ,s.seller_code
                   ,s.sku_code
                   ,pd.purchase_price
                   ,pd.cost_price
                   ,pd.market_price
                   ,pd.auto_sale_price
                   ,pd.sale_price
                   ,bu.list_price
                   ,CASE WHEN cost_price > 0 AND market_price > 0 THEN (pd.cost_price - pd.market_price)/ pd.cost_price ELSE NULL END AS gap_ts_market
                   ,CASE WHEN td.price_type = 'DYNAMIC' THEN pd.auto_sale_price
                         WHEN td.price_type <> 'DYNAMIC' THEN pd.sale_price ELSE NULL END AS final_sale_price
                   ,CASE WHEN td.price_type = 'DYNAMIC' THEN 'DYNAMIC'
                         WHEN td.price_type <> 'DYNAMIC' THEN 'MANUAL' END AS price_type
                   ,pd.unit
                   ,bu.base_unit
                   ,bu.convert_rate
                   ,CASE WHEN t.unit IS NOT NULL THEN TRUE ELSE FALSE END AS is_thuocsi_unit
                   ,CASE WHEN LOWER(pd.unit) = LOWER(pr.unit) THEN TRUE ELSE FALSE END AS is_purchase_unit
                   ,sale_allowed
                   ,purchase_allowed
                   ,MAX(DATETIME(pd.updated_at, "Asia/Ho_Chi_Minh")) AS last_updated_at
                   ,pr.web_status
    FROM ${source.circa_os}.product_price_sheet_sku_detail AS pd
    LEFT JOIN ${source.circa_os}.product_price_sheet_sku AS s ON pd.price_sheet_sku_id = s.id
    LEFT JOIN ${source.circa_os}.product_price_sheet AS ps ON s.price_sheet_id = ps.id
    LEFT JOIN product_base_unit AS bu ON s.product_id = bu.product_id AND pd.unit = bu.convert_unit
    LEFT JOIN thuosi_unit t ON s.product_id = t.product_id AND LOWER(pd.unit) = LOWER(t.unit)
    LEFT JOIN ${source.circa_os}.product_sku td ON td.product_id = s.product_id AND td.client_id = ps.client_id AND td.sku_code = s.sku_code
    LEFT JOIN ${ref('cos_dim_product')} pr ON pr.product_id = s.product_id AND pr.client_id = ps.client_id 
    WHERE bu.convert_unit IS NOT NULL
      AND ps.client_id = 1
      AND ps.name = 'Bảng giá client 1'
      AND s.seller_code IS NOT NULL
      AND ps.channel = 'OFFLINE'
    GROUP BY ALL
)
,combine_unit AS (
    SELECT DISTINCT p.product_id
                   ,p.seller_code
                   ,p.sku_code
                   ,p.unit
                   ,i.convert_rate
                   ,p.is_thuocsi_unit
                   ,is_purchase_unit
                   ,sale_allowed
                   ,purchase_allowed
                   ,web_status
                   ,i.base_unit AS is_base_unit
                   ,p.last_updated_at
                   ,p.purchase_price
                   ,po.unit_price AS last_price
                   ,p.cost_price
                   ,p.market_price
                   ,p.list_price
                   ,p.auto_sale_price
                   ,p.sale_price AS sale_unit_price
                   ,final_sale_price
                   ,price_type
                   ,gap_ts_market
                   ,CASE WHEN on_hand_quantity > 0 THEN purchase_price ELSE cost_price END AS exp_cost_price
                   ,CASE WHEN i.on_hand_quantity > 0 THEN "Available" ELSE "Unavailable" END AS have_stock
                   ,CASE WHEN (p.sale_price IS NULL OR p.sale_price = 0) THEN "Price not set" ELSE "Price set" END AS price_set_check
                   ,CASE WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 16 THEN "15D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 31 THEN "30D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 46 THEN "45D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 61 THEN "60D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 90 THEN "90D" ELSE "Others" END AS latest_date_order_range
                   ,CASE WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 16 AND on_hand_quantity > 0 THEN "No-Demand 15D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 31 AND on_hand_quantity > 0 THEN "No-Demand 30D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 46 AND on_hand_quantity > 0 THEN "No-Demand 45D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 61 AND on_hand_quantity > 0 THEN "No-Demand 60D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 90 AND on_hand_quantity > 0 THEN "No-Demand 90D"
                         ELSE "Others" END AS stock_aging_type
                   ,no_ord
                   ,GMV
                   ,latest_ord
                   ,latest_ord_L1M
                   ,no_ord_L1M
                   ,GMV_L1M
                   ,on_hand_quantity
                   ,SAFE_DIVIDE(po.unit_price, i.convert_rate) AS base_unit_price
    FROM has_price p
    LEFT JOIN inventory_full_unit i ON i.product_id = p.product_id AND i.unit = p.unit AND p.sku_code = i.sku_code
    LEFT JOIN count_ord co ON i.product_id = co.product_id AND i.seller_code = co.seller_code
    LEFT JOIN L1M l ON p.product_id = l.product_id AND LOWER(p.unit) = LOWER(l.unit) AND i.seller_code = l.seller_code
    LEFT JOIN last_purchase po ON i.product_id = po.product_id AND LOWER(i.unit) = LOWER(po.unit) AND i.seller_code = po.seller_code
    GROUP BY ALL
),base_price AS (
    SELECT
        product_id,
        seller_code,
        MAX(base_unit_price) AS base_unit_price
    FROM combine_unit
    WHERE last_price IS NOT NULL
    GROUP BY ALL
), combine AS (

SELECT  b.* EXCEPT(purchase_price)
        , 
   ROUND( COALESCE(
        b.last_price,
        bp.base_unit_price * b.convert_rate
    )) AS purchase_price
FROM combine_unit b
LEFT JOIN base_price bp
    ON b.product_id = bp.product_id
    AND b.seller_code = bp.seller_code
)
,check_unit_pricing AS (
    SELECT DISTINCT product_id
                   ,COUNT(*) AS total_units
                   ,SUM(CASE WHEN (sale_unit_price IS NULL OR sale_unit_price = 0) THEN 1 ELSE 0 END) AS unset_units
    FROM combine
    GROUP BY product_id
)
,_all AS (
    SELECT i.*
          ,CASE WHEN final_sale_price > 0 AND exp_cost_price > 0 THEN (final_sale_price - exp_cost_price)/ final_sale_price ELSE NULL END AS exp_mar
          ,CASE WHEN cup.unset_units = cup.total_units THEN "not set full"
                WHEN cup.unset_units > 0 THEN "contain unit not set"
                ELSE "set full" END AS check_unit_price_set
          ,1 AS client_id
    FROM combine i
    LEFT JOIN check_unit_pricing cup ON i.product_id = cup.product_id
    GROUP BY ALL
), base AS (
SELECT a.*
      ,pro.unit_name as web_unit
      ,pro.is_default as is_default_web
      ,pro.web_unit_status
      ,pro.unit_price as unit_price_web
      ,CONCAT(a.product_id,"_", lower(a.unit)) AS key_compare
      ,CONCAT(a.product_id, "_", client_id) AS product_client_id
      ,MIN(p.min_cost_price_include_tax * a.convert_rate) AS min_cost_price_include_tax
      ,MAX(p.max_cost_price_include_tax * a.convert_rate) AS max_cost_price_include_tax
FROM _all a
LEFT JOIN ${source.circa_os}.inventory_cost_price p ON a.seller_code = p.seller_code 
                                                    AND a.product_id = p.product_id
                                                    AND a.sku_code = p.sku_code
LEFT JOIN  ${source.ref}.dim_product_price_online pro ON a.product_id = pro.product_id AND a.unit = pro.unit_name
GROUP BY ALL
)
, promo AS (
   
SELECT DISTINCT product_id
                ,unit
                ,o.created_at 
                ,sku_code
                ,i.percent
                ,i.discount_value
                ,i.specific_price
                ,i.discount_type --FIXED_PRICE/SPECIFIC_PRICE/PERCENT
FROM ${ref('dim_promotion_event_circa')} o 
LEFT JOIN ${ref('dim_promotion_event_item_circa')} i ON o.id = i.promotion_event_id
WHERE is_expired = FALSE
     AND is_active = true
     AND o.client_id = 1
    -- AND i.discount_type ='FIXED_PRICE'
    -- AND  product_id = 8742 
QUALIFY ROW_NUMBER() OVER (PARTITION BY product_id, sku_code ORDER BY created_at DESC) = 1
ORDER BY o.created_at DESC
)SELECT b.*
    , p.discount_type
    , p.percent
    , CASE WHEN p.discount_type = 'FIXED_PRICE' AND p.unit = 'combo' THEN  p.discount_value
           WHEN p.discount_type = 'FIXED_PRICE'
            THEN ROUND(
                     (
                        p.discount_value
                        / src.convert_rate
                        * b.convert_rate
                    )
                , 0)
        END AS discount_value
    , CASE WHEN p.discount_type = 'SPECIFIC_PRICE'   AND p.unit = 'combo' THEN p.specific_price
        WHEN p.discount_type = 'SPECIFIC_PRICE'
            THEN ROUND(
                    p.specific_price
                    / src.convert_rate
                    * b.convert_rate
                , 0) END AS specific_price
    ,  CASE WHEN p.discount_type = 'PERCENT' AND p.unit = 'combo' THEN ROUND(b.final_sale_price * (1 - p.percent / 100), 0)
         WHEN p.discount_type = 'PERCENT'
            THEN ROUND(b.final_sale_price * (1 - p.percent / 100), 0)
        WHEN p.discount_type = 'FIXED_PRICE' AND p.unit = 'combo' THEN  ROUND( b.final_sale_price - p.discount_value)
        WHEN p.discount_type = 'FIXED_PRICE'
            THEN ROUND(
                    b.final_sale_price
                    - (
                        p.discount_value
                        / src.convert_rate
                        * b.convert_rate
                    )
                , 0)
        WHEN p.discount_type = 'SPECIFIC_PRICE'   AND p.unit = 'combo' THEN p.specific_price
        WHEN p.discount_type = 'SPECIFIC_PRICE'
            THEN ROUND(
                    p.specific_price
                    / src.convert_rate
                    * b.convert_rate
                , 0)
        ELSE b.final_sale_price
      END AS price_af_discount
      ,'COS' AS client_type
      ,'CIRCA' AS client_name
FROM base b
LEFT JOIN promo p ON b.product_id = p.product_id AND b.sku_code = p.sku_code
LEFT JOIN base src ON p.product_id = src.product_id AND p.unit = src.unit AND b.sku_code = p.sku_code AND b.seller_code = src.seller_code
WHERE b.client_id = 1
