config {
    type: "table",
    description: `Last 13 month| PIC: tu.dang; model_type: Table ;schedule: At minute 5 past hour 6, 8, 10, 12, 14, 16, 18, 20 and 22`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_2h_past5"],
    name: "cos_fact_order",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}



-- "b6c40920-af79-4fb0-bdc4-9965ddb885d2", "e737c882-e90c-4fd2-8a4f-ac6afd248a33"
with cte_fs as
    (select o.id as order_id,
       pos_id, p.code as pos_code,
       entity_id,
       o.code as order_code,
       o.status,
       note, o.type,
       source_type,
       delivery_type,
       channel,
       date(DATETIME_ADD(o.created_at, INTERVAL 7 HOUR)) as created_date,
       DATETIME_ADD(o.created_at, INTERVAL 7 HOUR) as created_at,
       fulfillment_status,
       date(DATETIME_ADD(completed_at, INTERVAL 7 HOUR))  as completed_date,medicine_cutting_fee

from ${source.circa}.order_order o
left join ${source.circa}.entity_pos_profile p on o.pos_id = p.id
where pos_id in ("b6c40920-af79-4fb0-bdc4-9965ddb885d2", "e737c882-e90c-4fd2-8a4f-ac6afd248a33")),
cte_os as
    (select o.id as order_id,
       pos_id, p.code as pos_code,
       entity_id,
       o.code as order_code,
       o.status,
       note, o.type,
       source_type,
       delivery_type,
       channel,
       date(DATETIME_ADD(o.created_at, INTERVAL 7 HOUR)) as created_date,
       DATETIME_ADD(o.created_at, INTERVAL 7 HOUR) as created_at,
       fulfillment_status,
       date(DATETIME_ADD(completed_at, INTERVAL 7 HOUR))  as completed_date,medicine_cutting_fee

from ${source.circa_os}.order_order o
left join ${source.circa_os}.entity_pos_profile p on o.pos_id = p.id   )
select * from cte_fs
union all 
select * from cte_os