config {
    type: "table",
    description: `Circa OS purchase order PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_1h_past5"],
    name: "cos_purchase_order",
    columns: {
        
    }
}
select distinct
     a.id as po_id
    ,a.pos_id
    ,a.distributor_id
    ,a.source_id
    ,a.code as po_code
    ,a.status as po_status
    ,a.total_item_amount as po_amount
    ,a.actual_total_amount as actual_po_amount
    ,sum(a.total_amount - coalesce(rt.actual_total_amount,0)) as actual_po_amount_af_rt
    ,date(datetime_add(a.created_at, interval 7 hour)) as created_date
    ,date(datetime_add(a.completed_at, interval 7 hour)) as completed_date
    ,datetime_add(a.created_at, interval 7 hour) as created_at
    ,a.location_type
    ,a.fulfillment_method
    ,a.sale_order_number as order_id
    ,a.created_by
    ,a.note
    ,a.source_type
    ,a.discount_amount
    ,a.delivery_fee_amount
    ,a.sub_payment_method
    ,a.sub_type
    ,o.order_status
    ,o.so_status
    ,a.payment_method
    ,date(o.created_at) as so_created_date
    --,tags
    ,case 
        when to_json_string(o.tags) like '%vip%' then 'vip'
        else 'others'
     end as vip_tag
    ,so_code
    ,eo.name as owner_name
    ,dis.name as Vendor
    ,a.client_id
    ,a.recon_payment_method
from ${source.circa_os}.order_purchase_order as a 
left join ${source.ref}.fact_order as o on a.sale_order_number = safe_cast(o.order_id as string)
left join ${source.circa_os}.entity_owner as eo on a.owner_id = eo.id and a.client_id = eo.client_id
left join ${source.circa_os}.entity_distributor dis on a.distributor_id = dis.id and a.client_id = dis.client_id
left join ${source.circa_os}.order_return_po rt on a.id = rt.source_id and a.client_id = rt.client_id-- Lấy nhừng PO có trả hàng 
left join ${source.ref}.circa_pos_profile p on a.pos_id = p.id and a.client_id = p.client_id
where a.status <> 'CANCELED'
      and p.id is not null
group by all