config {
    type: "table",
    description: `Circa OS purchase order item detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 15 every hour`,
    tags: ["custom_1h_past15"],
    name: "cos_purchase_order_item",
    columns: {
        
    }
}

SELECT DISTINCT
        TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR)                                                               AS transformed_at
       ,DATETIME_ADD(c.created_at, INTERVAL 7 HOUR)                                                                       AS created_at
       ,a.purchase_order_id                                                                                               AS po_id
       ,c.code                                                                                                            AS po_code
       ,a.product_id
       ,a.sku AS sku_code
       ,c.status
       ,COALESCE(
            CASE
                WHEN b.quantity <> 0 THEN b.quantity
                ELSE b.received_quantity
            END
        ,a.quantity)                                                                                                      AS quantity
       ,b.received_quantity
       ,b.received_quantity - COALESCE(x.quantity,0)                                                                      AS actual_quantity
       ,b.base_quantity
       ,(b.received_quantity - COALESCE(x.quantity,0)  )  * rt.convert_rate                                               AS actual_base_quantity
       ,CASE
            WHEN b.tax_rate <= 0 THEN 0
            ELSE b.tax_rate
        END                                                                                                               AS tax_rate
       ,a.unit_price
       ,a.unit
       ,a.unit_id
       -- ,CASE
       --      WHEN a.amount <> 0 THEN a.amount
       --      WHEN a.amount = 0 THEN b.quantity * a.unit_price
       --  END AS PO_item_amount
       ,b.received_quantity * a.unit_price                                                                                AS PO_item_amount
       ,(b.received_quantity - COALESCE(x.quantity,0)  ) * a.unit_price                                                   AS actual_po_item_amount
       ,b.lot_date
       ,a.product_id || "_" || b.lot_date                                                                                   AS product_lot_date
       ,a.sku || "_" || b.lot_date || "_" || b.tax_rate                                                                     AS sku_lotdate_vat
       ,il.location_type
       -- ,a.discount_amount
       ,b.discount_amount                                                                                                 AS item_discount_amt
       ,c.code || "_" || a.sku || "_" || b.lot_date || "_" || b.tax_rate                                                    AS item_src_po_code
       ,a.seller_code
       ,eo.name
       ,c.distributor_id
       ,dis.name                                                                                                          AS Vendor
       ,c.client_id
       ,CONCAT(a.product_id, "_", c.client_id)                                                                            AS product_client_id
       ,rt.convert_rate
       ,b.received_quantity * rt.convert_rate                                                                             AS base_qty_received
       ,c.fulfillment_method                                                                                              AS Channel
       ,p.code
       ,p.code AS pos_code
       ,CONCAT(a.product_id, "_", p.code) AS product_pos_code
FROM ${source.circa_os}.order_purchase_order_item AS a
LEFT JOIN ${source.circa_os}.order_purchase_order AS c ON a.purchase_order_id = c.id
LEFT JOIN ${source.circa_os}.order_po_item_detail AS b ON a.id = b.po_item_id
LEFT JOIN (
   SELECT
    rto.source_id
    ,rto.client_id
    ,rti.product_id
    ,rti.unit_id
    ,rtid.lot_date
    ,SUM(rtid.quantity) AS quantity
    ,SUM(rtid.base_quantity) AS base_quantity
   -- ,SUM(rti.amount) AS amount
  FROM ${source.circa_os}.order_return_po rto
  LEFT JOIN ${source.circa_os}.order_return_po_item rti ON rto.id = rti.return_po_id
  LEFT JOIN ${source.circa_os}.order_return_po_item_detail rtid ON rti.id = rtid.return_po_item_id 
  WHERE rto.status NOT IN ('PENDING', 'CANCELED')
  GROUP BY ALL
) x ON c.id = x.source_id AND c.client_id = x.client_id AND a.product_id = x.product_id AND a.unit_id = x.unit_id AND b.lot_date = x.lot_date

LEFT JOIN ${source.circa_os}.inventory_location AS il ON b.location_id = il.id AND c.client_id = il.client_id
LEFT JOIN ${source.circa_os}.entity_owner AS eo ON a.seller_code = eo.seller_code AND c.client_id = eo.client_id
LEFT JOIN ${source.circa_os}.entity_distributor AS dis ON c.distributor_id = dis.id AND c.client_id = dis.client_id
LEFT JOIN ${source.ref}.circa_pos_profile AS p ON c.pos_id = p.id AND c.client_id = p.client_id
LEFT JOIN ${source.circa_os}.product_retail_unit AS rt ON a.unit = rt.unit
                                                      AND a.product_id = rt.product_id
                                                      AND c.client_id = rt.client_id
WHERE c.status <> 'CANCELED'
  AND eo.name NOT LIKE '%TEST%'
  AND p.id IS NOT NULL
GROUP BY ALL
