config {
    type: "table", 
    description: 
        `PIC: huyen.ngo; 
        Current inventory,
        Type: Table; 
        Refresh Schedule: At minute 20 past hour;
        `,
    tags: ["custom_1h_past20"],
    columns: {
    }}
  WITH inventory AS (
    SELECT DISTINCT
        a.product_id
        ,a.sku_code
        ,a.lot_date
        ,CASE
            WHEN tax_rate <= 0 THEN 0 ELSE tax_rate
        END AS tax_rate
        ,a.on_hand_qty AS on_hand_quantity
        ,a.location_id
        ,doc_code
        ,a.cost_price_include_tax
        ,product_id || "_" || lot_date AS product_lot_date
        ,product_id || "_" || lot_date || "_" || tax_rate || "_" || a.client_id AS product_lot_date_vat_client_id
        ,a.client_id
        ,pos_id
    FROM ${source.circa_os}.inventory_location_detail AS a
    WHERE doc_code IS NOT NULL
          AND deleted_at IS NULL
)
,_all AS (
    SELECT DISTINCT
         a.product_id
        ,a.sku_code
        ,a.lot_date
        ,a.tax_rate
        ,doc_code
        ,a.cost_price_include_tax
        ,a.location_id
        ,product_lot_date
        ,a.product_lot_date_vat_client_id
        ,SUM(a.on_hand_quantity) AS on_hand_quantity
        ,b.pos_id
        ,location_type
        ,b.name AS location_name
        ,a.client_id
        ,CONCAT(a.product_id,"_", p.code) AS product_pos_code
    FROM inventory AS a
    LEFT JOIN ${source.ref}.circa_pos_profile p ON a.client_id = p.client_id  AND a.pos_id = p.id
    LEFT JOIN ${source.circa_os}.inventory_location AS b ON a.location_id = b.id  AND b.pos_id = p.id AND p.client_id = b.client_id
    WHERE p.id IS NOT NULL
    GROUP BY ALL
)
SELECT TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) AS transformed_at
       ,i.*
       ,CONCAT(i.product_id, "_", i.client_id) AS product_client_id
       ,eo.name AS owner_name
       ,eo.seller_code
       ,o.sale_order_number AS SO_code
       ,o.distributor_id
       ,o.fulfillment_method
FROM _all i 
LEFT JOIN ${source.circa_os}.order_purchase_order o ON i.doc_code = o.code AND i.client_id = o.client_id
LEFT JOIN ${source.circa_os}.entity_owner eo ON o.owner_id = eo.id AND i.client_id = eo.client_id
