
config {
    type: "table",
    description: `cos_demand_planning detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_2h_past5"],
    name: "cos_demand_planning",
    columns: {
        
    }
}

with base_data as (
Select * 
       ,concat(product_id, "_",1) as product_client_id
from ${source.external}.cos_demand_planning
where created_date is not null

), _all as (
Select base_data.* 
       ,case when base_data.purchase_unit = 'unit' then cv.base_unit
        else base_data.purchase_unit end as purchase_unit_convert
       ,cv.convert_rate
from base_data 
left join ( select distinct a.product_id
                     ,a.unit as base_unit
                     ,client_id
                     ,concat(product_id, "_",client_id) as product_client_id
                     ,convert_rate
      from ${source.circa_os}.product_retail_unit as a
      where a.base_unit is true 
            and (unit is not null or unit <> "")
            and client_id = 1
            qualify row_number() over(partition by product_id, client_id order by updated_at desc ) =1
      ) cv on base_data.product_client_id = cv.product_client_id
        where  base_data.purchase_unit = 'unit'
              -- and base_data.product_id = 185548 
              -- and cv.client_id = 1
union all
--có unit trong bán lẻ
Select base_data.* 
       , base_data.purchase_unit as purchase_unit_convert
       ,r.convert_rate
from base_data 
left join ${source.circa_os}.product_retail_unit r on base_data.product_id = r.product_id
                                                    and base_data.purchase_unit = r.unit
where base_data.purchase_unit <> 'unit'
      and r.client_id = 1

union all
--ko có unit trong bán lẻ

Select base_data.* 
       , base_data.purchase_unit as purchase_unit_convert
       ,1 as convert_rate
from base_data 
where base_data.purchase_unit <> 'unit'
      and concat(product_id, "_",purchase_unit) not in 
                (Select distinct concat(product_id, "_",unit) as product_client_id
                from ${source.circa_os}.product_retail_unit
                where client_id = 1
                )

)
Select * except (line_amount)
       ,case when line_amount is null then purchase_price_after_vat * qty_to_order 
       else line_amount end as line_amount
 from _all 
-- where channel = 'EXTERNAL'
--        and _all.created_date = '2025-09-05'


