config {
    type: "table",
    description: ` PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 past hour 6, 8, 10, 12, 14, 16, 18, 20 and 22`,
    name: "cos_stock_aging_type",
    tags: ["custom_2h_past5"]
}


WITH count_ord AS ( -- đếm số lượng đơn 
     SELECT DISTINCT o.pos_id
                    ,oi.product_id
                    ,MAX(o.created_date) AS latest_ord
                    ,COUNT(DISTINCT o.order_id) AS no_ord
                    ,SUM(unit_price_before_discount * (quantity - COALESCE(qty_rt, 0))) AS GMV
                    ,SUM(unit_cost_price * (quantity - COALESCE(qty_rt, 0))) AS cogs
                    ,o.client_id
     FROM  ${source.ref}.cos_fact_order o
     LEFT JOIN  ${source.ref}.cos_fact_order_item oi ON o.order_id = oi.order_id
     WHERE status LIKE "%COMPLETE%"
          -- AND o.client_id = 1
           AND owner_name NOT IN ('CIRCA MARKETING')
     GROUP BY ALL
)
,first_time_have_inventory AS ( -- ngày đầu tiên có tồn kho
     SELECT DISTINCT l.pos_id
                     ,p.name AS pos_name
                     ,a.product_id
                     ,MIN(DATE_ADD(a.created_at, INTERVAL 7 HOUR)) AS firstime_have_inventory
                     ,a.client_id
                     ,p.code AS pos_code
     FROM ${source.circa_os}.inventory_allocation a
     LEFT JOIN ${source.circa_os}.inventory_location_detail ld  ON a.location_detail_id = ld.id AND a.client_id = ld.client_id
     LEFT JOIN ${source.circa_os}.inventory_location l  ON ld.location_id = l.id AND a.client_id = l.client_id
     LEFT JOIN ${source.ref}.circa_pos_profile p  ON l.pos_id = p.id AND a.client_id = p.client_id
     WHERE  p.id IS NOT NULL
           AND ld.seller_code NOT IN ('CIRCA_MKP', 'MARKETING')
     GROUP BY ALL
)
,lastdate_pur AS ( -- lần cuối mua hàng
     SELECT DISTINCT o.pos_id
                     ,i.product_id
                     ,MAX(DATE(i.created_at)) AS lastdate_pur
                     ,o.client_id
     FROM ${source.ref}.cos_purchase_order o 
     LEFT JOIN ${source.ref}.cos_purchase_order_item i ON o.po_id = i.po_id
     WHERE received_quantity > 0 
           AND i.seller_code NOT IN ('CIRCA_MKP', 'MARKETING')
         --  AND o.client_id = 1
     GROUP BY ALL
)
,inventory AS ( -- tồn kho hiện tại
     SELECT DISTINCT 
            pos_id
           ,product_id
           ,SUM(on_hand_quantity) AS stock_qty
           ,SUM(on_hand_quantity * cost_price_include_tax) AS stock_value
           ,client_id
     FROM  ${source.ref}.cos_fact_inventory
     WHERE seller_code NOT IN ('CIRCA_MKP', 'MARKETING')
     GROUP BY ALL
)
,add_order_range AS (
     SELECT a.*
           ,b.GMV
           ,b.cogs
           ,b.no_ord
           ,b.latest_ord
           ,lastdate_pur
           ,stock_qty
           ,stock_value
           ,CASE WHEN stock_qty > 0 THEN 'Available' ELSE 'Unavailable' END AS stock_check 
           ,CASE 
                WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), latest_ord, DAY) < 16 THEN "15D"
                WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), latest_ord, DAY) < 31 AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), latest_ord, DAY) >= 16 THEN "30D"
                WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), latest_ord, DAY) < 46 AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), latest_ord, DAY) >= 31 THEN "45D"
                WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), latest_ord, DAY) < 61 AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), latest_ord, DAY) >= 46 THEN "60D"
                WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), latest_ord, DAY) < 91 AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), latest_ord, DAY) >= 61 THEN "90D"
                WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), latest_ord, DAY) >= 91 THEN "> 90D" 
                WHEN b.latest_ord IS NULL AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), DATE(firstime_have_inventory), DAY) < 16 THEN "15D"
                WHEN b.latest_ord IS NULL AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), DATE(firstime_have_inventory), DAY) < 31 AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), DATE(firstime_have_inventory), DAY) >= 16 THEN "30D"
                WHEN b.latest_ord IS NULL AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), DATE(firstime_have_inventory), DAY) < 46 AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), DATE(firstime_have_inventory), DAY) >= 31 THEN "45D"
                WHEN b.latest_ord IS NULL AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), DATE(firstime_have_inventory), DAY) < 61 AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), DATE(firstime_have_inventory), DAY) >= 46 THEN "60D"
                WHEN b.latest_ord IS NULL AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), DATE(firstime_have_inventory), DAY) < 91 AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), DATE(firstime_have_inventory), DAY) >= 61 THEN "90D"
                WHEN b.latest_ord IS NULL AND DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"), DATE(firstime_have_inventory), DAY) >= 91 THEN "> 90D" 
           END AS latest_date_order_range
        --   ,a.client_id
     FROM first_time_have_inventory a
     LEFT JOIN count_ord b  ON a.pos_id = b.pos_id AND a.product_id = b.product_id AND a.client_id = b.client_id
     LEFT JOIN inventory i  ON a.pos_id = i.pos_id AND a.product_id = i.product_id AND a.client_id = i.client_id
     LEFT JOIN lastdate_pur p  ON a.pos_id = p.pos_id AND a.product_id = p.product_id AND a.client_id = p.client_id
    -- WHERE a.pos_id NOT IN ('9dd83081-9919-4bc3-84bd-f5dfece10049')
)
SELECT *
      ,CONCAT(product_id, "_", client_id) AS product_client_id
      ,CONCAT(product_id, "_", pos_code) AS product_pos_code
      ,CASE 
           WHEN latest_date_order_range = "15D" THEN "1:No-Demand 15D"
           WHEN latest_date_order_range = "30D" THEN "2:No-Demand 30D"
           WHEN latest_date_order_range = "45D" THEN "3:No-Demand 45D"
           WHEN latest_date_order_range = "60D" THEN "4:No-Demand 60D"
           WHEN latest_date_order_range = "90D" THEN "5:No-Demand 90D"
           WHEN latest_date_order_range = "> 90D" THEN "6:No-Demand > 90D"
       END AS stock_aging_type
FROM add_order_range
