config {
    type: "table",
    description: `PIC: huyen.ngo;
                  model_type: Table ;
                  schedule: At minute 15 past hour.Circa voucher - chứa tất cả các voucher, được tạo ra từ đâ, thuộc campaign nào, đã sử dụng hay chưa, sử dụng trong đơn hàng nào `,
    tags: ["custom_1h_past15"],
    name: "cos_voucher_info",
    columns: {
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}

-- Lấy những voucher được tặng cho customers
WITH t AS ( 
    SELECT DISTINCT
         gift_id
        ,gift_code
        ,DATETIME_ADD(v.created_at, INTERVAL 7 HOUR)                            AS voucher_created_at
        ,voucher_id
        ,voucher_code
        ,customer_id                                                            AS gift_for_customer_id 
        ,JSON_EXTRACT_SCALAR(order_code)                                        AS order_code_created
        ,e.phone_number                                                         AS gift_for_customer_phone
        ,e.name                                                                 AS gift_for_customer_name
        ,pr.code                                                                AS pos_code_create_voucher
        ,pr.name                                                                AS pos_name_create_voucher
    FROM ${source.circa_os}.promotion_gift_voucher v --  voucher dc tặng cho ai 
    LEFT JOIN UNNEST(JSON_EXTRACT_ARRAY(assigned_order_codes))                  AS order_code
    LEFT JOIN ${source.circa_os}.entity_customer e ON v.customer_id = e.id
    LEFT JOIN ${source.ref}.cos_fact_order o ON CAST(JSON_EXTRACT_SCALAR(order_code) AS STRING) = o.order_code
    LEFT JOIN ${source.ref}.circa_pos_profile pr ON o.pos_id = pr.id
    WHERE gift_code NOT LIKE '%TEST%'
          --AND pr.id IS NOT NULL
)

,map_voucher AS (
    SELECT DISTINCT
         TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR)                    AS transformed_at
        ,us.code                                                                AS voucher_code
        ,t.order_code_created
        ,DATETIME_ADD(us.created_at, INTERVAL 7 HOUR)                           AS created_at
        ,DATE(DATETIME_ADD(us.created_at, INTERVAL 7 HOUR))                     AS created_date
        ,DATETIME_ADD(us.start_date, INTERVAL 7 HOUR)                           AS start_date
        ,DATETIME_ADD(us.end_date, INTERVAL 7 HOUR)                             AS end_date
        ,us.discount_value
        ,us.percent
        ,us.promotion_voucher_type
        ,us.is_active
        ,COALESCE(o.entity_id, gift_for_customer_id)                            AS customer_id
        ,COALESCE(e.phone_number, gift_for_customer_phone)                      AS customer_phone
        ,COALESCE(e.name, gift_for_customer_name)                               AS customer_name
        ,voucher_created_at 
        ,DATETIME_ADD(ov.created_at, INTERVAL 7 HOUR)                           AS date_used
        ,CASE  
            WHEN ov.created_at IS NOT NULL THEN "Yes" 
            ELSE "No" 
         END                                                                    AS is_used
        ,ov.order_code                                                          AS order_code_used 
        ,o.channel                                                              AS channel_used
        ,ov.discount_amount                                                     AS actual_discount_amount
        ,cp.code                                                                AS campaign_code
        ,cp.name                                                                AS campaign_name
        ,pr.code                                                                AS pos_code_used
        ,pos_code_create_voucher
        ,pr.name                                                                AS pos_name_used
        ,us.client_id
    FROM ${source.circa_os}.promotion_promotion_voucher us -- bảng chứa tất cả các mã voucher
    LEFT JOIN (
        SELECT * 
        FROM ${source.circa_os}.order_order_voucher -- voucher được apply trong đơn hàng
        WHERE is_valid = TRUE
    ) ov ON ov.voucher_id = us.id
    LEFT JOIN t ON us.code = t.voucher_code
    LEFT JOIN (
        SELECT * 
        FROM ${source.ref}.cos_fact_order 
        WHERE status <> 'CANCELED'
    ) o ON ov.order_id = o.order_id
    LEFT JOIN ${source.ref}.circa_pos_profile pr ON o.pos_id = pr.id
    LEFT JOIN ${source.circa_os}.entity_customer e ON o.entity_id = e.id
    LEFT JOIN ${source.circa_os}.promotion_promotion_campaign cp -- thông tin campaign
        ON us.promotion_campaign_id = cp.id 
        AND us.client_id = cp.client_id
    WHERE us.is_sample = FALSE
          --AND pr.id IS NOT NULL
)

SELECT 
     map_voucher.*
    ,e.id AS customer_id_gift
    ,e.phone_number AS customer_phone_gift -- người tặng voucher
FROM map_voucher
LEFT JOIN ${source.ref}.cos_fact_order o ON map_voucher.order_code_created = o.order_code
LEFT JOIN ${source.circa_os}.entity_customer e ON o.entity_id = e.id
