config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour;Table này dùng để tracking những đơn hàng đã được đặt nhưng hàng chưa về, sử dụng cho report Purchase Planner`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past5"],
    name: "cos_pending_dont_have_po",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    }
}


Select distinct
        datetime(o.created_at) as created_at
       ,case when p.id is not null then p.id 
             when p.id is null and o.customer_name = 'Circa Đà Nẵng' then '775e6511-76fc-4f50-933a-e1feb57de848'
             when p.id is null and (o.customer_name = 'Circa Hàm Nghi' or o.customer_name = 'Circa 80 Hàm Nghi') then 'a3e26e59-5a08-4beb-ae01-5e23a34bab74'
             when p.id is null and o.customer_name = 'COS Mizuki' then 'a87bdc94-0df3-4148-8064-fc9a3e6741bb'
             when p.id is null and (o.customer_name = 'Circa 136B CMT8' or o.customer_name = 'Circa 136B Cách Mạng Tháng 8')  then '436c78a1-252b-4f11-bc9e-0354c05f911e'
             when p.id is null and (o.customer_name = 'COS 1115 CMT8' or o.customer_name = 'Circa 1115 CMT8') then 'b922759c-b7c9-4b2b-975c-f3ea9d50deab'
             when p.id is null and (o.customer_name = 'COS Circa Ni Sư Huỳnh Liên' or o.customer_name = 'COS Ni Sư Huỳnh Liên') then '31493e74-3404-4c0e-a906-93691a6ee319'
             when p.id is null and (o.customer_name = 'Circa Vinhome Beverley' or o.customer_name = 'Circa Vimhome Berveley' or o.customer_name = 'Circa Beverly - Vinhomes' or  o.customer_name = 'Nhà thuốc Circa Beverly' ) then 'f2b46d1a-d5c9-45b8-8e90-4390babd87cb'
             when p.id is null and o.customer_name = 'COS Nguyễn Trãi' then '5976e784-3be9-4504-8b8f-cb28424cbeb2'
             when p.id is null and o.customer_name = 'COS Lý Thường Kiệt' then 'f8aa9f5c-183a-4fb2-a6a6-8f2ecf5d56f9'
             when p.id is null and (o.customer_name = 'Circa Sunrise Riverside' or o.customer_name = 'COS Circa Sunrise Riverside' or o.customer_name = 'COS Sunrise riverside' or o.customer_name = 'COS Sunrise Riverside') then 'b9ce5177-b294-4282-b2d5-728ab91ab14c'
             when p.id is null and o.customer_name = 'Circa Medora' then '73dcf891-f4a1-42c5-bea4-115412f1018d'
             when p.id is null and o.customer_name = 'Circa Astoria' then '61437f95-55ba-44b6-a994-99f2d9209c79'
             when p.id is null and o.customer_name = 'Circa Tâm Việt' then '265ed9b9-1e48-4390-8321-42c95529072e'
             when p.id is null and o.customer_name = 'Hub Nadyphar' then '9dd83081-9919-4bc3-84bd-f5dfece10049'
             else ''
            end as pos_id
       ,a.product_id
       ,td.unit
       ,a.sku_code as sku_code
       ,o.order_status as so_status
       ,sum(a.demand_quantity) as quantity
       ,sum(a.outbound_quantity) as quantity_received
       ,'SO_THUOCSI' as fulfillment_method
       ,SAFE_CAST(o.order_id as string) as so_code
       ,o.customer_id
       ,o.customer_name
       ,1 as client_id
       ,sum(sales_price * demand_quantity) as gmv_demand
       ,sum(sales_price * outbound_quantity) as gmv_actual
    ,concat(a.product_id, "_", 1) as product_client_id
from ${source.ref}.fact_order o 
left join ${source.ref}.fact_order_item a on o.order_id = a.order_id 
left join ${source.ref}.dim_product td on a.product_id = td.product_id
left join ${source.ref}.os_map_idthuocsi map on o.customer_id = map.id_thuocisi
left join ${source.ref}.circa_pos_profile p on map.pos_code = p.code
where REGEXP_CONTAINS(TO_JSON_STRING(customer_tags), r'\"CIRCACOS\"')
       and o.order_status <> 'CANCEL'
       and date(created_date) >=  '2025-07-01' 
       and SAFE_CAST(o.order_id as string) not in ( Select distinct sale_order_number from `buymed_circa_v2.order_purchase_order` where sale_order_number is not null)
       --and o.order_id = 36646246
group by all
order by pos_id
