
config {
    type: "table",
    description: `cos_demand_planning detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_2h_past5"],
    name: "cos_demand_planning",
    columns: {
        
    }
}

Select * from buymed_external.cos_demand_planning
where created_date is not null

