config {
    type: "table",
    description: `Circa OS Transaction order item detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_1h_past5"],
    name: "cos_fact_order_item",
    columns: {

        
    }
}


WITH base_data as (
    select
        a.id
        ,case when c.type = 'ONLINE' then b.id else a.id end as item_id--=llocation.item_ref_id
        ,a.order_id
        ,c.code
        ,a.note
        ,c.type
        ,a.product_id
        ,"NULL" as sku_code
        ,a.unit
        --         a.unit_id,
        --         a.location_id,
        ,case when c.type = 'ONLINE' then b.base_quantity else a.base_quantity end as base_quantity_original
        ,case
            when a.product_id = 1 then 1
            when a.lot_date = '' then b.quantity
            else a.quantity
        end as original_quantity
        ,a.unit_price
        ,case
            when a.tax_rate <= 0 then 0
                else a.tax_rate end as tax_rate
        ,a.discount_amount
        ,a.promotion_event_code
        ,case when c.type = 'ONLINE' then b.lot_date else a.lot_date end as lot_date
        ,case when c.type = 'ONLINE' then b.lot_id else a.lot_id end as lot_id
        ,case
            when a.quantity = 0 then 0
            when c.total_item_amount = 0 then 0
            when c.total_item_amount < c.discount_amount then a.unit_price
            else ROUND((a.unit_price / c.total_item_amount) * c.discount_amount, 4)
        end as discount_voucher_on_item
        ,DATETIME(a.created_at, "asia/Ho_Chi_Minh") as created_at, pos_id
    from ${source.circa}.order_order_item as a
    left join ${source.circa}.order_so_item_detail as b ON a.id = b.item_id
    left join ${source.circa}.order_order as c ON c.id = a.order_id
    WHERE date(c.created_at) >= "2024-11-01"
)
,cte_not_online as (
    select
        a.*
        ,(a.discount_amount + a.unit_price) as unit_price_before_discount
        ,case when a.type = 'RETURN' then original_quantity * (-1) else original_quantity end as quantity
        ,case when a.type = 'RETURN' then base_quantity_original * (-1) else base_quantity_original end as base_quantity
        ,case when a.unit_price = 0 then 0 else ia.cost_price_include_tax end as cost_price_include_tax
        ,case when a.unit_price = 0 then 0 else ia.cost_price_without_tax end as cost_price_without_tax
        ,il.location_type
        ,ld.doc_code
        ,so as sale_order_number
    from base_data as a
    left join ${source.circa}.inventory_allocation as ia ON a.item_id = ia.item_ref_id
    left join ${source.circa}.inventory_location as il ON ia.location_id = il.id
    left join ${source.circa}.inventory_location_detail ld ON ia.location_detail_id = ld.id
    left join UNNEST(JSON_VALUE_ARRAY(ld.sale_order_numbers)) as so
    WHERE a.type <> 'ONLINE'
),
cte_online as (
    select
        a.*
        ,(a.discount_amount + a.unit_price) as unit_price_before_discount
        ,case when a.type = 'RETURN' then original_quantity * (-1) else original_quantity end as quantity
        ,case when a.type = 'RETURN' then base_quantity_original * (-1) else base_quantity_original end as base_quantity
        , ia.cost_price_include_tax  as cost_price_include_tax
        , ia.cost_price_without_tax  as cost_price_without_tax
        ,il.location_type
        ,ld.doc_code
        ,so as sale_order_number
    from base_data as a
    left join ${source.circa}.inventory_allocation as ia ON a.item_id = ia.item_ref_id
    left join ${source.circa}.inventory_location as il ON ia.location_id = il.id
    left join ${source.circa}.inventory_location_detail ld ON ia.location_detail_id = ld.id
    left join UNNEST(JSON_VALUE_ARRAY(ld.sale_order_numbers)) as so
    WHERE a.type = 'ONLINE'

)
,cte_fs as
(select
       order_id
      ,product_id
      ,sku_code
      ,quantity
      ,unit
      ,unit_price
      ,discount_amount
      ,unit_price_before_discount
      ,lot_date
      ,base_quantity
      ,tax_rate
      ,product_id || '_' || lot_date || '_' || tax_rate as product_lot_date_vat
      ,sku_code || '_' || lot_date || '_' || tax_rate as sku_lotdate_vat
      ,cost_price_include_tax as base_unit_cost_price
      ,"CIRCA" as owner_name
      ,doc_code as po_code
      ,sale_order_number
      ,promotion_event_code
from (
    select * from cte_not_online
    UNION ALL
    select * from cte_online
    qualify row_number() over(partition by id) = 1) a
where item_id  is not null or item_id <> ""
-- and date(created_at) >= "2024-11-01" --date( date_trunc( date_sub( current_date('+7'), interval 12 month) , month ) )
and pos_id in ("b6c40920-af79-4fb0-bdc4-9965ddb885d2", "e737c882-e90c-4fd2-8a4f-ac6afd248a33")
)
,
 cte_os as (
select
  order_id
  --   o.code as order_code,
  ,oi.product_id
  ,oi.sku_code
  ,quantity
  ,unit
  ,unit_price
  ,oi.discount_amount
  ,(oi.discount_amount + oi.unit_price) as unit_price_before_discount
  ,oi.lot_date
  ,oi.base_quantity
  --   amount
  ,oi.tax_rate
  ,oi.product_id || '_' || oi.lot_date || '_' || oi.tax_rate as product_lot_date_vat
  ,oi.sku_code || '_' || oi.lot_date || '_' || oi.tax_rate as sku_lotdate_vat
  ,al.cost_price_include_tax/al.base_quantity as base_unit_cost_price
  --   item_ref_id,
  --   oi.product_id || '_' || oi.unit|| '_' || o.pos_id as sku_unit_pos,
  --   latest_cost_price,
  --   max_cost_price_include_tax,
  --   min_cost_price_include_tax,
  ,eo.name as owner_name
  ,po.code as po_code
  ,po.sale_order_number
  ,promotion_event_code
from ${source.circa_os}.order_order o
left join ${source.circa_os}.order_order_item oi ON o.id = oi.order_id
left join ${source.circa_os}.inventory_allocation as al ON oi.id = al.item_ref_id
left join ${source.circa_os}.inventory_location_detail ld ON al.location_detail_id = ld.id --
left join ${source.circa_os}.inventory_cost_price as cp on oi.product_id = cp.product_id and o.pos_id=cp.pos_id
left join ${source.circa_os}.order_purchase_order po on  ld.doc_code = po.code
left join ${source.circa_os}.entity_owner eo on po.owner_id = eo.id
where
  o.status LIKE '%COMPLETE%'
  and o.client_id = 1
  and al.client_id = 1
  and ld.client_id = 1
  and po.client_id = 1
  and eo.client_id = 1

  -- group by all
    qualify row_number() over(partition by oi.id order by base_unit_cost_price desc) = 1
    ),
order_items as (select *
from cte_fs
union all
select * from cte_os)

select i.*
      ,base_unit_cost_price * convert_rate  as unit_cost_price
from order_items i
left join ${ref('cos_fact_order')} fo on i.order_id = fo.order_id
left join  ${source.ref}.cos_product_convert_base_unit  cv on cv.product_id = i.product_id and cv.convert_unit = i.unit
where fo.order_id is not null

