config {
    type: "table",
    description: `Tracking price for Circa OS
             PIC: huyen.ngo; model_type: Table ;schedule: At minute 15 past hour`,
    tags: ["custom_1h_past15"],
    name: "cos_adhoc_pos_product_client",
}


WITH thuosi_unit AS (
    SELECT DISTINCT product_id
                   ,unit
    FROM ${source.ref}.dim_product
)
,product_base_unit AS (
    SELECT DISTINCT product_id
                   ,unit AS convert_unit
                   ,base_unit
                   ,convert_rate
                   ,sale_allowed
                   ,purchase_allowed
    FROM ${source.circa_os}.product_retail_unit
    WHERE client_id = 1
)
,count_ord AS (
    SELECT DISTINCT oi.product_id
                   ,MAX(o.created_date) AS latest_ord
                   ,COUNT(DISTINCT o.order_id) AS no_ord
                   ,SUM(unit_price * quantity) AS GMV
    FROM ${source.ref}.cos_fact_order o
    LEFT JOIN ${source.ref}.cos_fact_order_item oi ON o.order_id = oi.order_id
    WHERE status LIKE "%COMPLETE%"
    GROUP BY ALL
)
,inventory AS (
    SELECT DISTINCT a.product_id
                   ,SUM(a.on_hand_quantity) AS on_hand_quantity
                   ,seller_code
                   ,sku_code
    FROM ${source.ref}.cos_fact_inventory a
    LEFT JOIN ${source.ref}.circa_pos_profile p ON a.pos_id = p.id
    WHERE a.client_id = 1
          AND p.actual_status <> "Inactive"
    GROUP BY ALL
)
,full_unit AS (
    SELECT DISTINCT ru.product_id
                   ,ru.convert_unit AS unit
                   ,ru.convert_rate
                   ,seller_code
                   ,ru.base_unit
    FROM inventory AS i
    JOIN product_base_unit AS ru ON i.product_id = ru.product_id
    GROUP BY ALL
)
,inventory_full_unit AS (
    SELECT DISTINCT i.product_id
                   ,u.unit
                   ,u.convert_rate
                   ,i.on_hand_quantity
                   ,i.sku_code
                   ,i.seller_code
                   ,u.base_unit
    FROM inventory i
    LEFT JOIN full_unit u ON i.product_id = u.product_id
)
,has_price AS (
    SELECT DISTINCT s.product_id
                   ,s.seller_code
                   ,s.sku_code
                   ,pd.purchase_price
                   ,pd.cost_price
                   ,pd.market_price
                   ,pd.auto_sale_price
                   ,pd.sale_price
                   ,CASE WHEN cost_price > 0 AND market_price > 0 THEN (pd.cost_price - pd.market_price)/ pd.cost_price ELSE NULL END AS gap_ts_market
                   ,CASE WHEN td.price_type = 'DYNAMIC' THEN pd.auto_sale_price
                         WHEN td.price_type <> 'DYNAMIC' THEN pd.sale_price ELSE NULL END AS final_sale_price
                   ,pd.unit
                   ,bu.base_unit
                   ,bu.convert_rate
                   ,CASE WHEN t.unit IS NOT NULL THEN TRUE ELSE FALSE END AS is_thuocsi_unit
                   ,CASE WHEN LOWER(pd.unit) = LOWER(pr.unit) THEN TRUE ELSE FALSE END AS is_purchase_unit
                   ,sale_allowed
                   ,purchase_allowed
                   ,MAX(DATETIME(pd.updated_at, "Asia/Ho_Chi_Minh")) AS last_updated_at
    FROM ${source.circa_os}.product_price_sheet_sku_detail AS pd
    LEFT JOIN ${source.circa_os}.product_price_sheet_sku AS s ON pd.price_sheet_sku_id = s.id
    LEFT JOIN ${source.circa_os}.product_price_sheet AS ps ON s.price_sheet_id = ps.id
    LEFT JOIN product_base_unit AS bu ON s.product_id = bu.product_id AND pd.unit = bu.convert_unit
    LEFT JOIN thuosi_unit t ON s.product_id = t.product_id AND LOWER(pd.unit) = LOWER(t.unit)
    LEFT JOIN ${source.circa_os}.product_sku td ON td.product_id = s.product_id AND td.client_id = ps.client_id AND td.sku_code = s.sku_code
    LEFT JOIN ${source.ref}.cos_dim_product pr ON pr.product_id = s.product_id AND pr.client_id = ps.client_id 
    WHERE bu.convert_unit IS NOT NULL
      AND ps.client_id = 1
      AND ps.name = 'Bảng giá client 1'
      AND s.seller_code IS NOT NULL
      AND ps.channel = 'OFFLINE'
    GROUP BY ALL
)
,combine AS (
    SELECT DISTINCT p.product_id
                   ,p.seller_code
                   ,p.sku_code
                   ,p.unit
                   ,i.convert_rate
                   ,p.is_thuocsi_unit
                   ,is_purchase_unit
                   ,sale_allowed
                   ,purchase_allowed
                   ,i.base_unit AS is_base_unit
                   ,p.last_updated_at
                   ,p.purchase_price
                   ,p.cost_price
                   ,p.market_price
                   ,p.auto_sale_price
                   ,p.sale_price AS sale_unit_price
                   ,final_sale_price
                   ,gap_ts_market
                   ,CASE WHEN on_hand_quantity > 0 THEN purchase_price ELSE cost_price END AS exp_cost_price
                   ,CASE WHEN i.on_hand_quantity > 0 THEN "Available" ELSE "Unavailable" END AS have_stock
                   ,CASE WHEN (p.sale_price IS NULL OR p.sale_price = 0) THEN "Price not set" ELSE "Price set" END AS price_set_check
                   ,CASE WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 16 THEN "15D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 31 THEN "30D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 46 THEN "45D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 61 THEN "60D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 90 THEN "90D" ELSE "Others" END AS latest_date_order_range
                   ,CASE WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 16 AND on_hand_quantity > 0 THEN "No-Demand 15D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 31 AND on_hand_quantity > 0 THEN "No-Demand 30D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 46 AND on_hand_quantity > 0 THEN "No-Demand 45D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 61 AND on_hand_quantity > 0 THEN "No-Demand 60D"
                         WHEN DATE_DIFF(CURRENT_DATE("Asia/Ho_Chi_Minh"),latest_ord,DAY) < 90 AND on_hand_quantity > 0 THEN "No-Demand 90D"
                         ELSE "Others" END AS stock_aging_type
                   ,no_ord
                   ,GMV
                   ,latest_ord
                   ,on_hand_quantity
    FROM has_price p
    LEFT JOIN inventory_full_unit i ON i.product_id = p.product_id AND i.unit = p.unit AND p.sku_code = i.sku_code
    LEFT JOIN count_ord co ON i.product_id = co.product_id
    GROUP BY ALL
)
,check_unit_pricing AS (
    SELECT DISTINCT product_id
                   ,COUNT(*) AS total_units
                   ,SUM(CASE WHEN (sale_unit_price IS NULL OR sale_unit_price = 0) THEN 1 ELSE 0 END) AS unset_units
    FROM combine
    GROUP BY product_id
)
,_all AS (
    SELECT i.*
          ,CASE WHEN final_sale_price > 0 AND exp_cost_price > 0 THEN (final_sale_price - exp_cost_price)/ final_sale_price ELSE NULL END AS exp_mar
          ,CASE WHEN cup.unset_units = cup.total_units THEN "not set full"
                WHEN cup.unset_units > 0 THEN "contain unit not set"
                ELSE "set full" END AS check_unit_price_set
          ,1 AS client_id
    FROM combine i
    LEFT JOIN check_unit_pricing cup ON i.product_id = cup.product_id
    GROUP BY ALL
)
SELECT a.*
      ,pro.unit_name as web_unit
      ,pro.is_default as is_default_web
      ,pro.unit_price as unit_price_web
      ,pro.unit_status
      ,CONCAT(a.product_id,"_", convert_rate) AS key_compare
      ,CONCAT(a.product_id, "_", client_id) AS product_client_id
      ,MIN(p.min_cost_price_include_tax * a.convert_rate) AS min_cost_price_include_tax
      ,MAX(p.max_cost_price_include_tax * a.convert_rate) AS max_cost_price_include_tax
FROM _all a
LEFT JOIN ${source.circa_os}.inventory_cost_price p ON a.seller_code = p.seller_code 
                                                    AND a.product_id = p.product_id
                                                    AND a.sku_code = p.sku_code
LEFT JOIN  ${source.ref}.product_price_online pro ON a.product_id = pro.product_id AND a.unit = pro.unit_name
GROUP BY ALL



