config {
    type: "table",
    description: `Circa OS purchase order
                  PIC: huyen.ngo; 
                  model_type: Table ;schedule: At minute 10 every hour`,
    tags: ["gold_custom_20m"],
    name: "cos_purchase_order"

}

SELECT DISTINCT
     TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) AS transformed_at
    ,a.id AS po_id
    ,a.pos_id
    ,a.distributor_id
    ,a.source_id
    ,a.code AS po_code
    ,a.status AS po_status
    ,SUM(a.discount_amount) AS discount_amount
    --,a.total_item_amount AS po_amount
    ,SUM(a.total_item_amount - COALESCE(rt.total_item_amount, 0)) AS actual_po_amount_item_af_rt -- thực nhận tiền hàng
    --,a.actual_total_amount AS actual_po_amount
    ,SUM(a.actual_total_amount - COALESCE(rt.actual_total_amount, 0)) AS actual_po_amount_af_rt -- thực nhận tổng đơn, đã trừ discount
    ,DATE(DATETIME_ADD(a.created_at, INTERVAL 7 HOUR)) AS created_date
    ,DATE(DATETIME_ADD(a.completed_at, INTERVAL 7 HOUR)) AS completed_date
    ,DATETIME_ADD(a.created_at, INTERVAL 7 HOUR) AS created_at
    ,DATETIME_ADD(a.stock_at, INTERVAL 7 HOUR) AS stock_at
    ,a.location_type
    ,a.fulfillment_method
    ,a.sale_order_number AS order_id
    ,a.created_by
    ,e.name as created_by_name
    ,a.note
    ,a.source_type
    --,a.discount_amount
    ,a.delivery_fee_amount
    ,a.sub_payment_method
    ,a.sub_type
    ,o.order_status
    ,o.so_status
    ,map.id_thuocisi
    ,customer_id
    ,CASE 
        WHEN (map.id_thuocisi IS NOT NULL OR (a.source_type = 'REQUEST_PO' AND fulfillment_method <> 'IMPORT_STOCK'))
             AND a.client_id = 1
             AND a.status <> 'CANCELED'
             AND a.status <> 'PENDING'
        THEN 1 ELSE 0
     END AS store_id
    ,a.payment_method
    ,o.created_date AS so_created_date
    ,TO_JSON_STRING(order_tag) AS order_tag
    ,CASE 
        WHEN TO_JSON_STRING(o.order_tag) LIKE '%vip%' THEN 'vip'
        ELSE 'others'
     END AS vip_tag
    ,CASE WHEN fulfillment_method = 'SO_THUOCSI' 
                              AND (dis.name like '%MEDX%' OR dis.name like '%Buymed%') THEN 'MEDX'
                              WHEN fulfillment_method = 'IMPORT_STOCK' THEN 'IMPORT_STOCK'
                              WHEN fulfillment_method = 'EXTERNAL' THEN 'EXTERNAL'
                              WHEN fulfillment_method = 'SO_THUOCSI'AND dis.name NOT LIKE '%MEDX%' AND dis.name NOT LIKE '%Buymed%' THEN 'SELLER' 
                              END AS vendor_type
    ,so_code
    ,a.owner_id 
    ,eo.seller_code AS owner_code
    ,eo.name AS owner_name
    ,dis.name AS Vendor
    ,a.client_id
    ,a.recon_payment_method
    ,p.code AS pos_code
FROM ${source.circa_os}.order_purchase_order AS a 
LEFT JOIN ${source.ref}.map_order_thuoc_si AS o ON a.sale_order_number = SAFE_CAST(o.order_id AS STRING)
LEFT JOIN ${source.circa_os}.entity_owner AS eo ON a.owner_id = eo.id AND a.client_id = eo.client_id
LEFT JOIN ${source.circa_os}.entity_distributor dis ON a.distributor_id = dis.id AND a.client_id = dis.client_id
LEFT JOIN (
    SELECT DISTINCT source_id, client_id, SUM(actual_total_amount) AS actual_total_amount,  SUM(total_item_amount) AS total_item_amount
    FROM ${source.circa_os}.order_return_po
    WHERE status NOT IN ('PENDING', 'CANCELED')
    GROUP BY ALL
) AS rt ON a.id = rt.source_id AND a.client_id = rt.client_id -- Lấy nhừng PO có trả hàng 
LEFT JOIN ${source.ref}.circa_pos_profile p ON a.pos_id = p.id AND a.client_id = p.client_id
LEFT JOIN ${source.ref}.os_map_idthuocsi map ON o.customer_id = map.id_thuocisi
LEFT JOIN  ${source.circa_os}.entity_entity e on a.created_by = e.id AND a.client_id = e.client_id 
WHERE  p.id IS NOT NULL
GROUP BY ALL
