config {
    type: "table",
    description: `LASt fact_order_survey month
                  PIC: huyen.ngo; model_type: Table ;schedule: At minute 15 pASt hour. `,
    tags: ["custom_1h_pASt15"],
    name: "fact_order_survey",
    columns: {
        order_id: "NonNull |" + docs.order_id

        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}


SELECT DISTINCT
            s.id AS survey_id
           ,order_id
           ,datetime_add(s.created_at, INTERVAL 7 hour ) AS created_at
           ,date (datetime_add(s.created_at, INTERVAL 7 hour )) AS created_date
           ,s.created_by
           ,e.email AS employee_email
           ,e.name AS employee_name
           ,rating
           ,feedback
FROM ${source.circa_os}.order_order_survey s
LEFT JOIN ${source.circa_os}.entity_entity e on s.created_by = e.id
WHERE rating not in (4,5)