config {
    type: "table",
    description: `inventory_cutoff_som PIC: huyen.ngo; model_type: Table ;schedule: manual refresh`,
    tags: ["circa_cutoff"],
    name: "/inventory_cutoff_som",
    columns: {
        
    }
}

SELECT DISTINCT
       a.cutoff_date_index
     , DATE_ADD(DATE_TRUNC(a.cutoff_date_index, MONTH), INTERVAL 1 MONTH) AS som
     , b.pos_id
     , a.product_id
     , SUM(on_hand_qty) AS on_hand_qty
     , SUM(on_hand_qty * cost_price_include_tax) AS stock_value
     , a.client_id
     , CASE 
           WHEN DATE(DATETIME_ADD(a.updated_at, INTERVAL 7 HOUR)) > DATE(a.cutoff_date_index) THEN 0 
           ELSE 1
       END AS is_same_day
FROM buymed_circa_v2.inventory_location_detail_historical_cut_off AS a
LEFT JOIN lakehouse-prod-394907.buymed_circa_v2.inventory_location AS b 
       ON a.location_id = b.id 
      AND a.client_id = b.client_id
WHERE  a.cutoff_date_index >= '2025-12-30'
  AND a.cutoff_date_index IN (
        '2025-12-31'
      , '2026-01-31'
      , '2026-02-28'
      , '2026-03-31'
  )
GROUP BY ALL