config {
    type: "incremental",
    description: `inventory_cutoff_product 
                   PIC: huyen.ngo; model_type: Table ;schedule: At 8h30`,
    tags: ["8h30"],
    name: "inventory_cutoff_product",
    columns: {
        
    },
    bigquery: {
        partitionBy: "cutoff_date_index"
    }
}

js {
    const start_date =
        ` DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY) `
    const end_date = ` CURRENT_DATE() `
}
pre_operations {
  ${when(
    incremental(),
    `
    DELETE
    FROM ${self()}
    WHERE cutoff_date_index >= ${start_date}
    `,
    `SELECT 1`
  )}
}


SELECT
       a.cutoff_date_index
     , DATE_ADD(a.cutoff_date_index, INTERVAL 1 DAY) AS date_map
     , b.pos_id
     , a.product_id
     , SUM(on_hand_qty) AS on_hand_qty
     , SUM(on_hand_qty * cost_price_include_tax) AS stock_value
     , a.client_id
     , CASE 
           WHEN DATE(DATETIME_ADD(a.updated_at, INTERVAL 7 HOUR)) > DATE(a.cutoff_date_index) THEN 0 
           ELSE 1
       END AS is_same_day
     , CONCAT(a.product_id, "_", b.client_id) AS product_client_id
FROM  ${source.circa_os}.inventory_location_detail_historical_cut_off AS a
LEFT JOIN  ${source.circa_os}.inventory_location AS b 
       ON a.location_id = b.id 
      AND a.client_id = b.client_id
WHERE   a.client_id = 1
      AND cutoff_date_index >= ${when(incremental(), start_date, `'2026-07-01'`)}
      -- a.cutoff_date_index <= DATE_SUB(CURRENT_DATE("Asia/Ho_Chi_Minh"), INTERVAL 2 DAY)
      -- AND

GROUP BY ALL
-- 


