config {
    type: "table",
    description: `inventory_cutoff_som PIC: huyen.ngo; model_type: Table ;schedule: manual refresh`,
    tags: ["circa_cutoff"],
    name: "inventory_cutoff_som",
    columns: {
        
    }
}

SELECT DISTINCT
       a.cutoff_date_index
     , CASE 
    WHEN a.cutoff_date_index = DATE_SUB(CURRENT_DATE('Asia/Ho_Chi_Minh'), INTERVAL 1 DAY)
        THEN a.cutoff_date_index

    ELSE DATE_ADD(
            DATE_TRUNC(a.cutoff_date_index, MONTH),
            INTERVAL 1 MONTH
         )
END AS som
     , b.pos_id
     , a.product_id
     , SUM(on_hand_qty) AS on_hand_qty
     , SUM(on_hand_qty * cost_price_include_tax) AS stock_value
     , a.client_id
     , CASE 
           WHEN DATE(DATETIME_ADD(a.updated_at, INTERVAL 7 HOUR)) > DATE(a.cutoff_date_index) THEN 0 
           ELSE 1
       END AS is_same_day
     , CONCAT(a.product_id, "_", b.client_id) AS product_client_id
FROM ${source.circa_os}.inventory_location_detail_historical_cut_off AS a
LEFT JOIN ${source.circa_os}.inventory_location AS b 
       ON a.location_id = b.id 
      AND a.client_id = b.client_id
WHERE  a.cutoff_date_index >= '2025-12-30'
  AND a.cutoff_date_index IN (
        '2025-12-31'
      , '2026-01-31'
      , '2026-02-28'
      , '2026-03-31'
      , '2026-04-30'
      , '2026-05-31'
      , DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)
  )
GROUP BY ALL

UNION ALL

SELECT DISTINCT
       a.cutoff_date_index
     , DATE_TRUNC(a.cutoff_date_index, MONTH) AS som
     , b.pos_id
     , a.product_id
     , SUM(on_hand_qty) AS on_hand_qty
     , SUM(on_hand_qty * cost_price_include_tax) AS stock_value
     , a.client_id
     , CASE 
           WHEN DATE(DATETIME_ADD(a.updated_at, INTERVAL 7 HOUR)) > DATE(a.cutoff_date_index) THEN 0 
           ELSE 1
       END AS is_same_day
     , CONCAT(a.product_id, "_", b.client_id) AS product_client_id
FROM ${source.circa_os}.inventory_location_detail_historical_cut_off AS a
LEFT JOIN ${source.circa_os}.inventory_location AS b 
       ON a.location_id = b.id 
      AND a.client_id = b.client_id
WHERE  a.cutoff_date_index >= '2026-03-20'
  AND a.cutoff_date_index IN (
       '2026-03-20'
  )
      AND a.client_id = 38
GROUP BY ALL

UNION ALL

SELECT DISTINCT
       a.cutoff_date_index
     , DATE_TRUNC(a.cutoff_date_index, MONTH) AS som
     , b.pos_id
     , a.product_id
     , SUM(on_hand_qty) AS on_hand_qty
     , SUM(on_hand_qty * cost_price_include_tax) AS stock_value
     , a.client_id
     , CASE 
           WHEN DATE(DATETIME_ADD(a.updated_at, INTERVAL 7 HOUR)) > DATE(a.cutoff_date_index) THEN 0 
           ELSE 1
       END AS is_same_day
     , CONCAT(a.product_id, "_", b.client_id) AS product_client_id
FROM ${source.circa_os}.inventory_location_detail_historical_cut_off AS a
LEFT JOIN ${source.circa_os}.inventory_location AS b 
       ON a.location_id = b.id 
      AND a.client_id = b.client_id
WHERE  a.cutoff_date_index >= '2026-03-13'
  AND a.cutoff_date_index IN (
       '2026-03-13'
  )
      AND a.client_id = 39
GROUP BY ALL


UNION ALL

SELECT DISTINCT
       a.cutoff_date_index
     , DATE_TRUNC(a.cutoff_date_index, MONTH) AS som
     , b.pos_id
     , a.product_id
     , SUM(on_hand_qty) AS on_hand_qty
     , SUM(on_hand_qty * cost_price_include_tax) AS stock_value
     , a.client_id
     , CASE 
           WHEN DATE(DATETIME_ADD(a.updated_at, INTERVAL 7 HOUR)) > DATE(a.cutoff_date_index) THEN 0 
           ELSE 1
       END AS is_same_day
     , CONCAT(a.product_id, "_", b.client_id) AS product_client_id
FROM ${source.circa_os}.inventory_location_detail_historical_cut_off AS a
LEFT JOIN ${source.circa_os}.inventory_location AS b 
       ON a.location_id = b.id 
      AND a.client_id = b.client_id
WHERE  a.cutoff_date_index >= '2026-03-27'
  AND a.cutoff_date_index IN (
       '2026-03-27'
  )
      AND a.client_id = 40
GROUP BY ALL

