config {
    type: "table",
    description: `inventory_cutoff_dbd PIC: huyen.ngo; model_type: Table ;schedule: At 8h30`,
    tags: ["8h30"],
    name: "inventory_cutoff_product",
    columns: {
        
    }
}

SELECT DISTINCT
       a.cutoff_date_index
     , DATE_ADD(a.cutoff_date_index, INTERVAL 1 DAY) AS date_map
     , b.pos_id
     , a.product_id
     , SUM(on_hand_qty) AS on_hand_qty
     , SUM(on_hand_qty * cost_price_include_tax) AS stock_value
     , a.client_id
     , CASE 
           WHEN DATE(DATETIME_ADD(a.updated_at, INTERVAL 7 HOUR)) > DATE(a.cutoff_date_index) THEN 0 
           ELSE 1
       END AS is_same_day
     , CONCAT(a.product_id, "_", b.client_id) AS product_client_id
FROM  ${source.circa_os}.inventory_location_detail_historical_cut_off AS a
LEFT JOIN  ${source.circa_os}.inventory_location AS b 
       ON a.location_id = b.id 
      AND a.client_id = b.client_id
WHERE a.cutoff_date_index >= DATE_SUB( CURRENT_DATE("Asia/Ho_Chi_Minh"),INTERVAL 1 MONTH)
      AND a.cutoff_date_index <= DATE_SUB(CURRENT_DATE("Asia/Ho_Chi_Minh"), INTERVAL 2 DAY)
      AND a.client_id = 1
GROUP BY ALL

UNION ALL

SELECT DISTINCT
       CURRENT_DATE("Asia/Ho_Chi_Minh") AS _today
     , CURRENT_DATE("Asia/Ho_Chi_Minh")  AS date_map
     , pos_id
     , product_id
     , SUM(on_hand_quantity) AS on_hand_qty
     , SUM(on_hand_quantity * cost_price_include_tax) AS stock_value
     , client_id
     ,  1 AS is_same_day
     , CONCAT(product_id, "_", client_id) AS product_client_id
FROM  ${source.ref}.cos_fact_inventory
WHERE client_id = 1
GROUP BY ALL
