config {
    type: "table",
    description: `inventory_cutoff_dbd PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["8h30"],
    disabled: true,
    name: "inventory_cutoff_dbd",
    columns: {
        
    }
}

select distinct

      a.cutoff_date_index
      ,b.pos_id
      ,sum(on_hand_qty) as on_hand_qty
      ,sum(on_hand_qty * cost_price_include_tax) as stock_value
      ,a.client_id
from buymed_circa_v2.inventory_location_detail_historical_cut_off as a
left join `buymed_circa_v2.inventory_location` as b on a.location_id = b.id
--where a.client_id = 1 
group by all