
config {
    type: "table",
    description: `map_order_thuoc_si  item detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_1h_past5"],
    name: "map_order_thuoc_si",
    columns: {
        
    }
}


select o.order_id
      ,case when p.id is not null then p.id 
             when p.id is null and o.customer_name = 'Circa Đà Nẵng' then '775e6511-76fc-4f50-933a-e1feb57de848'
             when p.id is null and (o.customer_name = 'Circa Hàm Nghi' or o.customer_name = 'Circa 80 Hàm Nghi') then 'a3e26e59-5a08-4beb-ae01-5e23a34bab74'
             when p.id is null and o.customer_name = 'COS Mizuki' then 'a87bdc94-0df3-4148-8064-fc9a3e6741bb'
             when p.id is null and (o.customer_name = 'Circa 136B CMT8' or o.customer_name = 'Circa 136B Cách Mạng Tháng 8')  then '436c78a1-252b-4f11-bc9e-0354c05f911e'
             when p.id is null and (o.customer_name = 'COS 1115 CMT8' or o.customer_name = 'Circa 1115 CMT8') then 'b922759c-b7c9-4b2b-975c-f3ea9d50deab'
             when p.id is null and (o.customer_name = 'COS Circa Ni Sư Huỳnh Liên' or o.customer_name = 'COS Ni Sư Huỳnh Liên' or o.customer_name ='Circa 242 Ni Sư Huỳnh Liên' ) then '31493e74-3404-4c0e-a906-93691a6ee319'
             when p.id is null and (o.customer_name = 'Circa Vinhome Beverley' or o.customer_name = 'Circa Vimhome Berveley' or o.customer_name = 'Circa Beverly - Vinhomes' or  o.customer_name = 'Nhà thuốc Circa Beverly' ) then 'f2b46d1a-d5c9-45b8-8e90-4390babd87cb'
             when p.id is null and o.customer_name = 'COS Nguyễn Trãi' then '5976e784-3be9-4504-8b8f-cb28424cbeb2'
             when p.id is null and o.customer_name = 'COS Lý Thường Kiệt' then 'f8aa9f5c-183a-4fb2-a6a6-8f2ecf5d56f9'
             when p.id is null and (o.customer_name = 'Circa Sunrise Riverside' or o.customer_name = 'COS Circa Sunrise Riverside' or o.customer_name = 'COS Sunrise riverside' or o.customer_name = 'COS Sunrise Riverside') then 'b9ce5177-b294-4282-b2d5-728ab91ab14c'
             when p.id is null and (o.customer_name = 'Circa Medora' or o.customer_name = 'circa medora' or o.customer_name = 'Nhà thuốc Circa Medora') then '73dcf891-f4a1-42c5-bea4-115412f1018d'
             when p.id is null and o.customer_name = 'Circa Astoria' then '61437f95-55ba-44b6-a994-99f2d9209c79'
             when p.id is null and o.customer_name = 'Circa Tâm Việt' or o.customer_name = 'Nhà thuốc Circa Tâm Việt' then '265ed9b9-1e48-4390-8321-42c95529072e'
             when p.id is null and o.customer_name = 'Hub Nadyphar' then '9dd83081-9919-4bc3-84bd-f5dfece10049'
             when p.id is null and (o.customer_name = 'Circa Cityland' or o.customer_name = 'Nhà Thuốc Circa Cityland') then '55388c70-30fe-4c80-b119-92b24a1aa1bf'
             when p.id is null and o.customer_name = 'Circa Tâm An' then '94c6f221-5015-47da-b1ea-887fa75ccc3a'
             when p.id is null and o.customer_name = 'Circa Mira - Lê Văn Việt' then '9b37d4ec-b0ea-4e1a-9c6d-292c8e450b25'
             when p.id is null and o.customer_name = 'Nhà thuốc Circa Astoria' then '61437f95-55ba-44b6-a994-99f2d9209c79'
             when p.id is null and o.customer_name = 'Circa Symphony' then 'faeb1575-3ba0-4684-9ea9-621d6c3fc606'
             when p.id is null and o.customer_name = 'Circa Phamix' then '023b98c8-df83-45b7-b94e-471e81580c5b'
             when p.id is null and o.customer_name = 'Circa Medly' then 'bd0a5c91-c25f-4d49-92b4-7fe5ea174a5f'
             else ''
            end as pos_id
       ,o.customer_name
       ,customer_id
       ,o.tags as order_tag
       ,date(o.created_at) as created_date
       ,o.order_status 
       ,order_type
       ,o.so_code
       ,o.so_status
       ,o.gmv
       ,actual_sales_amount
       ,invoice_amount
       --,po.po_code
       --,po.po_status
from ${source.ref}.fact_order o
left join ${source.ref}.dim_customer c using (customer_id)
left join lakehouse-prod-394907.gold_buymed_vn2.os_map_idthuocsi map on o.customer_id = map.id_thuocisi
left join lakehouse-prod-394907.gold_buymed_vn2.circa_pos_profile p on map.pos_code = p.code
--left join ${source.ref}.cos_purchase_order po on SAFE_CAST(o.order_id as string) = po.order_id
where REGEXP_CONTAINS(TO_JSON_STRING(customer_tags), r'\"CIRCACOS\"')
       and date(o.created_at)>"2024-10-01"
       and o.order_status <> 'CANCEL'