
config {
    type: "table",
    description: `map_order_thuoc_si  item detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    tags: ["custom_1h_past15"],
    name: "map_order_thuoc_si",
    columns: {
        
    }
}


select o.order_id
      ,case when p.id is not null then p.id 
             when p.id is null and (o.customer_name = 'Circa Đà Nẵng' or o.customer_name = 'CIRCA CENTRAL') then '775e6511-76fc-4f50-933a-e1feb57de848'
             when p.id is null and (o.customer_name = 'Circa Hàm Nghi' or o.customer_name = 'Circa 80 Hàm Nghi' or o.customer_name = 'COS Circa Hàm Nghi' or o.customer_name ='CIRCA SIGNATURE') then 'a3e26e59-5a08-4beb-ae01-5e23a34bab74'
             when p.id is null and (o.customer_name = 'COS Mizuki' or o.customer_name = 'CIRCA MIZUKI') then 'a87bdc94-0df3-4148-8064-fc9a3e6741bb'
             when p.id is null and (o.customer_name = 'Circa 136B CMT8' or o.customer_name = 'Circa 136B Cách Mạng Tháng 8' or o.customer_name ='CIRCA MORA')  then '436c78a1-252b-4f11-bc9e-0354c05f911e'
             when p.id is null and (o.customer_name = 'COS 1115 CMT8' or o.customer_name = 'Circa 1115 CMT8'or o.customer_name = 'CIRCA THỐNG NHẤT') then 'b922759c-b7c9-4b2b-975c-f3ea9d50deab'
             when p.id is null and (o.customer_name = 'COS Circa Ni Sư Huỳnh Liên' or o.customer_name = 'COS Ni Sư Huỳnh Liên' or o.customer_name ='Circa 242 Ni Sư Huỳnh Liên' or o.customer_name ='CIRCA LUMINA' ) then '31493e74-3404-4c0e-a906-93691a6ee319'
             when p.id is null and (o.customer_name = 'Circa Vinhome Beverley' or o.customer_name = 'Circa Vimhome Berveley' or o.customer_name = 'Circa Beverly - Vinhomes' or  o.customer_name = 'Nhà thuốc Circa Beverly' ) then 'f2b46d1a-d5c9-45b8-8e90-4390babd87cb'
             when p.id is null and (o.customer_name = 'CIRCA URBAN' or o.customer_name = 'COS Nguyễn Trãi' or o.customer_name = 'COS 212A/56 Nguyễn Trãi') then '5976e784-3be9-4504-8b8f-cb28424cbeb2'
             when p.id is null and (o.customer_name = 'COS Lý Thường Kiệt' or o.customer_name ='CIRCA ELANA') then 'f8aa9f5c-183a-4fb2-a6a6-8f2ecf5d56f9'
             when p.id is null and (o.customer_name = 'CIRCA SUNRISE' or o.customer_name = 'Circa Sunrise Riverside' or o.customer_name = 'COS Circa Sunrise Riverside' or o.customer_name = 'COS Sunrise riverside' or o.customer_name = 'COS Sunrise Riverside') then 'b9ce5177-b294-4282-b2d5-728ab91ab14c'
             when p.id is null and (o.customer_name = 'Circa Medora' or o.customer_name = 'circa medora' or o.customer_name = 'Nhà thuốc Circa Medora'or o.customer_name ='CIRCA MEDORA') then '73dcf891-f4a1-42c5-bea4-115412f1018d'
             when p.id is null and o.customer_name = 'Circa Astoria' then '61437f95-55ba-44b6-a994-99f2d9209c79'
             when p.id is null and (o.customer_name = 'Circa Tâm Việt' or o.customer_name = 'Nhà thuốc Circa Tâm Việt'or o.customer_name = 'CIRCA TAM VIET') then '265ed9b9-1e48-4390-8321-42c95529072e'
             when p.id is null and o.customer_name = 'Hub Nadyphar' then '9dd83081-9919-4bc3-84bd-f5dfece10049'
             when p.id is null and (o.customer_name = 'Circa Cityland' or o.customer_name = 'Nhà Thuốc Circa Cityland') then '55388c70-30fe-4c80-b119-92b24a1aa1bf'
             when p.id is null and (o.customer_name = 'Circa Tâm An' or o.customer_name = 'CIrca Tâm An') then '94c6f221-5015-47da-b1ea-887fa75ccc3a'
             when p.id is null and (o.customer_name = 'Circa Mira - Lê Văn Việt' or o.customer_name = 'Nhà thuốc Mira' or o.customer_name = 'Nhà thuốc Circa Mira' or o.customer_name ='CIRCA MIRA') then '9b37d4ec-b0ea-4e1a-9c6d-292c8e450b25'
             when p.id is null and o.customer_name = 'Nhà thuốc Circa Astoria' then '61437f95-55ba-44b6-a994-99f2d9209c79'
             when p.id is null and (o.customer_name = 'Circa Symphony' or o.customer_name = 'Nhà thuốc Symphony' or o.customer_name = 'Circa Symphony - HCM' or o.customer_name = 'CIRCA SYMPHONY') then 'faeb1575-3ba0-4684-9ea9-621d6c3fc606'
             when p.id is null and (o.customer_name = 'Circa Phamix' or o.customer_name = 'Circa Phamix - HCM' or o.customer_name = 'Nhà thuốc Phamix' or o.customer_name = 'CIRCA PHAMIX') then '023b98c8-df83-45b7-b94e-471e81580c5b'
             when p.id is null and (o.customer_name = 'Circa Medly' or o.customer_name = 'Nhà thuốc Circa Medly' or o.customer_name = 'Circa Medly - HCM' or o.customer_name = 'Nhà thuốc Medly' or o.customer_name ='CIRCA MEDLY') then 'bd0a5c91-c25f-4d49-92b4-7fe5ea174a5f'
             when p.id is null and (o.customer_name = 'Circa Florita' or o.customer_name = 'CIRCA FLORITA') then 'c476efb2-415c-429a-978e-d389b4b06607'
             when p.id is null and (o.customer_name = 'Circa PharmaOne' or o.customer_name = 'CIRCA PHARMA ONE' or o.customer_name = 'CIRCA PHARMA ONE') then 'ef29a397-72d8-40c3-9602-e1cbbc5d1da1'
             when p.id is null and (o.customer_name = 'Circa Rainbow' or o.customer_name = 'CIRCA RAINBOW') then '1b294ac9-ab33-46d7-97b8-840441918613'
             when p.id is null and o.customer_name = 'Circa Eco Green' then 'ec523737-4c3f-4296-ae6f-f081544ac4de'
             when p.id is null and o.customer_name = 'Circa Celadon' then '164538d8-6baa-4401-9f8f-9fbb50e8fa96'
             when p.id is null and (o.customer_name = 'Circa Ehome 3'or o.customer_name = 'CIRCA EHOME') then 'efff4c29-2b1f-415b-803e-be26de02acf4'
             when p.id is null and (o.customer_name = 'Circa Nam Việt' or o.customer_name = 'CIRCA NAM VIET') then '674741b7-ad96-4aa1-bc19-54bbc2f9031f'
             when p.id is null and o.customer_name = 'CIRCA ECO GREEN' then 'ec523737-4c3f-4296-ae6f-f081544ac4de'
             when p.id is null and o.customer_name = 'CIRCA CELADON' then '164538d8-6baa-4401-9f8f-9fbb50e8fa96'
             when p.id is null and o.customer_name = 'CIRCA AKARI' then '71e79e7f-8e5e-4598-abb0-dd89ed5431db'
             when p.id is null and o.customer_name = 'CIRCA ASTORIA' then '61437f95-55ba-44b6-a994-99f2d9209c79'
             when p.id is null and o.customer_name = 'CIRCA CITYLAND' then '55388c70-30fe-4c80-b119-92b24a1aa1bf'
             when p.id is null and o.customer_name = 'CIRCA BEVERLY' then 'f2b46d1a-d5c9-45b8-8e90-4390babd87cb'
             when p.id is null and o.customer_name = 'CIRCA TAM AN' then '94c6f221-5015-47da-b1ea-887fa75ccc3a'
             when p.id is null and o.customer_name = 'KHO TỔNG HUB LÝ THƯỜNG KIỆT' then '9dd83081-9919-4bc3-84bd-f5dfece10049'
             when p.id is null and o.customer_name = 'CIRCA BELVITA' then '98f26020-1df8-4bc7-bdec-b958823447cf'
             when p.id is null and o.customer_id = 407640 and o.customer_name = 'Chị Tình - Circa Mira' then '9b37d4ec-b0ea-4e1a-9c6d-292c8e450b25'
             when p.id is null and o.customer_id = 407640 and o.customer_name = 'Chị Nhi - Tâm An - Store Manager' then '94c6f221-5015-47da-b1ea-887fa75ccc3a'
             when p.id is null and o.customer_id = 407640 and o.customer_name = 'Chị An - Cityland - Store Manager' then '55388c70-30fe-4c80-b119-92b24a1aa1bf'
             when p.id is null and o.customer_id = 407640 and o.customer_name = 'Chị Dung - Medora - Store Manager' then '73dcf891-f4a1-42c5-bea4-115412f1018d'
             when p.id is null and o.customer_id = 407640 and o.customer_name = 'Chị Dung - Tâm Việt - Store Manager' then '265ed9b9-1e48-4390-8321-42c95529072e'
             when p.id is null and o.customer_id = 407640 and o.customer_name = 'Chị Ngân - Symphony - Store Manager' then 'faeb1575-3ba0-4684-9ea9-621d6c3fc606'
             when p.id is null and o.customer_id = 407640 and o.customer_name = 'Chị Lệ - Medly - Store Manager' then 'bd0a5c91-c25f-4d49-92b4-7fe5ea174a5f'
             when p.id is null and o.customer_id = 407640 and o.customer_name = 'Chị Minh - La Astoria - Store Manager' then '61437f95-55ba-44b6-a994-99f2d9209c79'
             when p.id is null and o.customer_id = 409603 and o.customer_name = 'Chị Ngân - Symphony - Store Manager' then 'faeb1575-3ba0-4684-9ea9-621d6c3fc606'
             when p.id is null and o.customer_id = 409603 and o.customer_name = 'Chị Lệ - Medly - Store Manager' then 'bd0a5c91-c25f-4d49-92b4-7fe5ea174a5f'
             when SPLIT(o.note,'-')[OFFSET(0)] = 'POS0018' then 'a3e26e59-5a08-4beb-ae01-5e23a34bab74'
             else ''
            end as pos_id
       ,SPLIT(o.note,'-')[OFFSET(0)] AS pos_code
       ,o.customer_name
       ,customer_id
       ,o.tags as order_tag
       ,date(o.created_at) as created_date
       ,o.order_status 
       ,order_type
       ,o.so_code
       ,o.so_status
       ,o.gmv
       ,actual_sales_amount
       ,invoice_amount
       --,po.po_code
       --,po.po_status
from ${source.ref}.fact_order o
left join ${source.ref}.dim_customer c using (customer_id)
left join lakehouse-prod-394907.gold_buymed_vn2.os_map_idthuocsi map on o.customer_id = map.id_thuocisi
left join lakehouse-prod-394907.gold_buymed_vn2.circa_pos_profile p on map.pos_code = p.code
--left join ${source.ref}.cos_purchase_order po on SAFE_CAST(o.order_id as string) = po.order_id
where (REGEXP_CONTAINS(TO_JSON_STRING(customer_tags), r'\"CIRCACOS\"')  OR REGEXP_CONTAINS(TO_JSON_STRING(customer_tags), r'\"CIRCA_FS\"'))
       and date(o.created_at)>"2024-10-01"
       and o.order_status <> 'CANCEL'
       -- and customer_id <> 352665 -- Tech-Trúc Trần
       -- and customer_id <> 409603 -- Circa Marketing Hà Nội
       -- and customer_id <> 407640 -- Circa Marketing
       -- and customer_id <> 409156 -- Nhà thuốc Circa Admin
       -- --408981: master HN 
       -- --392301: master HCM