
config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: `,
    tags:["10h30"],
    name: "o2o_order_delivery"
}

with t as (
Select 
        o.assigned_pos_code as pos_code
       ,o.assigned_order_codes as order_code
       ,i.order_code as order_code_platform
       ,i.sender_name
       ,i.status as deliver_status
       ,o.o2o_status as order_status
       -- ,o.canceled_by_user_type
       ,o.cancellation_type
       ,o.cancellation_note
       ,DATETIME_ADD(i.created_time, INTERVAL 7 HOUR) as created_order_time
       ,DATETIME_ADD(i.last_updated_time, INTERVAL 7 HOUR) as last_order_time
       --,delivery_type
       ,i.delivery_carrier
       ,i.delivery_carrier_code
       ,DATETIME_ADD(o.created_time, INTERVAL 7 HOUR) as created_time_plaform
       ,date(DATETIME_ADD(o.created_time, INTERVAL 7 HOUR)) as created_date_plaform

from ${source.platinum}.circa_online_prd_order_sale_order i 
left join ${source.ref}.circa_online_order o on o.order_code = i.order_code
where i.sender_name not like '%FC Circa%'
        and i.sender_name not like '%Tech Test%'
        and i.sender_name not like '%[TECH]%'
        and i.sender_name <> 'Tech - Cao Lăm Miền Nam'
        and extract (year from o.created_date) >= 2024
        --and reference_order_in_platform = 'DH000458'
      -- qualify row_number () over (PARTITION BY i.order_code order by expired_time desc) = 1
), map_event as (
Select t.*
       ,e.note as detail_note
       ,event_name as event_name_detail_system
       ,case when SPLIT(event_name, '/')[OFFSET(0)] = 'OPS_CANCEL_ORDER' then 'CANCEL'
             when  SPLIT(event_name, '/')[OFFSET(0)] = '3PL_ORDER_CANCEL' then '3PL_ORDER_CANCEL'
             when SPLIT(event_name, '/')[OFFSET(0)] like '%DELIVERED%' then 'DELIVERED' 
             when event_name like 'PROCESS_ORDER/WAIT_TO_DELIVER' then 'PROCESS_ORDER/WAIT_TO_DELIVER'
             when event_name like 'PROCESS_ORDER/WAIT_TO_PACK' then 'PROCESS_ORDER/WAIT_TO_PACK'
             when SPLIT(event_name, '/')[OFFSET(0)] like '%DELIVERED%' then 'DELIVERED' 
             when SPLIT(event_name, '/')[OFFSET(0)] like 'SYNC_POS_ORDER%' then   concat(SPLIT(event_name, '/')[OFFSET(0)], '/', SPLIT(event_name, '/')[OFFSET(ARRAY_LENGTH(SPLIT(event_name, '/')) - 1)]) 
             else SPLIT(event_name, '/')[OFFSET(0)]
         end as event_name_detail
        ,DATETIME_ADD(e.created_time, INTERVAL 7 HOUR)as event_name_detail_time
        ,e.action_status_code

from t
left join ${source.platinum}.circa_online_prd_order_order_event e on t.order_code_platform = e.order_code
where pos_code is not null
) 
--  SELECT * FROM t
--  WHERE order_code_platform ='DH001828'
Select *
       ,CASE WHEN event_name_detail IN ('CREATE_ORDER','WAIT_TO_CONFIRM', 'ADMIN_CREATE_ORDER', 'WAIT_FOR_PAYMENT') THEN "1. created_order"
                      WHEN event_name_detail IN ('RECEIVE_PAYMENT') THEN "2. recceive_payment"
                      WHEN event_name_detail IN ('CONFIRM_ORDER', 'PROCESS_ORDER') THEN '3. confirm_order'
                      WHEN event_name_detail IN ('OPS_RESET_STORE' ) THEN "4. reset_store"
                      WHEN event_name_detail IN ('CREATE_POS_ORDER','SYNC_POS_ORDER', 'PROCESS_ORDER/WAIT_TO_PACK', 'PROCESS_ORDER/WAIT_TO_DELIVER', 'SYNC_POS_ORDER/CALLBACK', 'SYNC_POS_ORDER/SUCCESS', 'POS_PROCESSING_EXPIRED', 'RETRY_SYNC_POS_ORDER' ) THEN "5. pos_process"
                      WHEN event_name_detail IN ('BOOK_3PL','WAIT_TO_DELIVER', 'SYNC_POS_ORDER/WAIT_TO_DELIVER', 'BOOK_3PL_FAILED' ) THEN "6. book_deliver"
                      WHEN event_name_detail IN ('3PL_ORDER_PICKING','3PL_ORDER_DELIVERING', '3PL_ORDER_PICKED', '3PL_ORDER_WAIT_TO_DELIVER', 'FAIL_TO_DELIVER','CANCEL_ORDER','3PL_ORDER_FAIL_TO_DELIVER'  ) THEN "7. delivering"
                      WHEN event_name_detail IN ( 'DELIVERED') THEN '8. delivered'
                 END AS group_event
 from map_event
 where order_status = 'DELIVERED'
