config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour;Table này dùng để tracking những đơn hàng đã được đặt nhưng hàng chưa về, sử dụng cho report Purchase Planner`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_1h_past5"],
    name: "price_inventory_by_pos",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    }
}

with price_tbl AS (
  Select distinct 
     product_id
    ,unit
    ,convert_rate
    ,sale_unit_price
    ,price_set_check
    ,is_base_unit
    ,seller_code
    ,client_id
  from gold_buymed_vn2.cos_adhoc_pos_product_client
  where client_id = 1
  -- WHERE
  --   seller_code = 'CIRCA'
),
inv_tbl as  (
  Select
    pos_id
    ,product_id
    ,seller_code
    ,sum(on_hand_quantity) as qty
    ,sum(on_hand_quantity * cost_price_include_tax) as stock_value
  from `gold_buymed_vn2.cos_fact_inventory`
  where client_id = 1
  group by all

),_all as (
Select
  p.product_id
  ,p.unit
  ,is_base_unit
  ,p.sale_unit_price
  ,price_set_check
  ,i.pos_id
  ,pos.name as pos_name
  ,p.seller_code
  ,concat(p.seller_code, "_", p.client_id) as seller_client_id
  ,case
    when p.is_base_unit = true then i.qty
    else 0
  end as qty
  ,i.stock_value
  ,concat(p.product_id, "_", p.client_id) as product_client_id
from price_tbl p
left join inv_tbl i on p.product_id = i.product_id and p.seller_code = i.seller_code
left join `gold_buymed_vn2.circa_pos_profile` pos on i.pos_id = pos.id
where pos.id is not null
)
Select *
      ,case when qty > 0 then 'Available'
            else 'Unavailable' end as stock_check
from _all
    -- and p.product_id = 1165 
