config {
    type: "table",
    description: `Last 13 month
                  PIC: huyen.ngo; 
                  model_type: Table ;
                  schedule: At minute 15 every hour;
                  Table này dùng để map giá theo từng unit và tồn kho`,
    tags: ["custom_1h_past15"],
    name: "price_inventory_by_pos",
    columns: {
        
    }
}
WITH price_tbl AS (
    SELECT DISTINCT
         product_id
        ,unit
        ,convert_rate
        ,sale_unit_price
        ,price_set_check
        ,is_base_unit
        ,seller_code
        ,client_id
    FROM ${source.ref}.cos_adhoc_pos_product_client
    WHERE client_id = 1
),
inv_tbl AS (
    SELECT
         pos_id
        ,product_id
        ,seller_code
        ,SUM(on_hand_quantity)                                              AS qty
        ,SUM(on_hand_quantity * cost_price_include_tax)                     AS stock_value
    FROM ${source.ref}.cos_fact_inventory
    WHERE client_id = 1
    GROUP BY ALL
),
_all AS (
    SELECT
         p.product_id
        ,p.unit
        ,is_base_unit
        ,p.sale_unit_price
        ,price_set_check
        ,i.pos_id
        ,pos.name AS pos_name
        ,p.seller_code
        ,CONCAT(p.seller_code, '_', p.client_id)                           AS seller_client_id
        ,CASE 
            WHEN p.is_base_unit = TRUE THEN i.qty
            ELSE i.qty / CASE 
                WHEN convert_rate IS NULL OR convert_rate = 0 THEN 1
                ELSE convert_rate 
            END
        END                                                                 AS qty -- lấy stock_qty theo tất cả đơn vị
        ,i.stock_value
        ,CONCAT(p.product_id, '_', p.client_id)                             AS product_client_id
    FROM price_tbl p
    LEFT JOIN inv_tbl i ON p.product_id = i.product_id  AND p.seller_code = i.seller_code
    LEFT JOIN ${source.ref}.circa_pos_profile pos ON i.pos_id = pos.id
    WHERE pos.id IS NOT NULL
)
SELECT *
       ,CASE 
            WHEN qty > 0 THEN 'Available'
            ELSE 'Unavailable' 
        END AS stock_check
FROM _all

    -- and p.product_id = 1165 
