config {
    type: "table",
    description: `Request purchase order (request mua hàng từ các cừa hàng Circa) 
                  PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    tags: ["custom_1h_past5"],
    name: "request_purchase_order",
    columns: {
        
    }
}

SELECT TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR)                     AS transformed_at
       ,o.id
       ,o.code
       ,o.pos_id
       ,o.status
       ,CASE
             WHEN o.status = 'CANCELED' THEN 'Đã hủy'
             WHEN o.status = 'DENIED' THEN 'Từ chối'
             WHEN o.status = 'ORDERED' THEN 'Đã đặt hàng'
             WHEN o.status = 'PARTIAL_ORDERED' THEN 'Đặt thiếu hàng'
             WHEN o.status = 'PENDING' THEN 'Nháp'
             WHEN o.status = 'PO_CREATED' THEN 'Đã tạo PO'
             WHEN o.status = 'PROCESSED' THEN 'Đã kiểm duyệt'
             WHEN o.status = 'WAITING_PROCESS' THEN 'Chờ kiểm duyệt'
             WHEN o.status = 'PROCESSING' THEN 'Đang kiểm duyệt'
             WHEN o.status = 'COMPLETED' THEN 'Đã hoàn tất'
             WHEN o.status = 'ORDER_FAILED' THEN 'Thất bại'
             ELSE NULL
        END AS status_vn
       ,o.note
       ,o.request_reason
       ,DATE_ADD(o.waiting_process_at, INTERVAL 7 HOUR) AS submit_at
       ,DATE(DATE_ADD(o.waiting_process_at, INTERVAL 7 HOUR)) AS submit_date
       ,DATE_ADD(o.accepted_at, INTERVAL 7 HOUR) AS accepted_at
       ,DATE_ADD(o.denied_at, INTERVAL 7 HOUR) AS denied_at
       ,o.cancel_note
       ,DATE_ADD(o.expected_time, INTERVAL 7 HOUR) AS request_at
       ,i.product_id
       ,i.unit
       ,i.amount
       ,i.quantity
       ,i.ordered_quantity
       ,i.accepted_quantity
       ,failed_purchase_count
       ,i.convert_rate
       ,JSON_VALUE(accepted_quantity_history, '$[0].PoCode')   AS po_code
       ,JSON_VALUE(accepted_quantity_history, '$[0].so_code')  AS so_code
       ,JSON_VALUE(accepted_quantity_history, '$[0].Status')   AS so_status
       ,JSON_VALUE(accepted_quantity_history, '$[0].SourceType') AS source_type
       ,i.tax_rate
       ,i.unit_price
       ,o.client_id
       ,CONCAT(i.product_id, "_", o.client_id) AS product_client_id
FROM ${source.circa_os}.order_request_purchase_order o
LEFT JOIN ${source.circa_os}.order_request_purchase_order_item i ON o.id = i.request_purchase_order_id
LEFT JOIN ${source.ref}.circa_pos_profile p ON o.pos_id = p.id
WHERE p.id IS NOT NULL
      AND o.status <> 'PENDING'

