config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    name: "sku_status_thuocsi",
    columns: {/*
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"*/
        
    }
}


with base_data as (
Select distinct product_id
from ${source.circa_os}.order_purchase_order_item
where (sku is not null or sku <> '')
     and received_quantity <> 0
) --lấy danh sách sản phẩm đã mua trong quá khứ
, thuocsi_sku_status as 
( select distinct
    a.product_id
    ,sku_system_status
    ,row_number() over (partition by a.product_id
      order by 
        case a.sku_system_status
          when 'NORMAL' then 1
          when 'LIMIT' then 2
          when 'OUT_OF_STOCK' then 3
          when 'SUSPENDED' then 4
          else 5
        end
        -- sai rồi, nếu sp ko có trạng thái 
    ) as row_num
  from ${source.ref}.adhoc_pm_master_sku a
  where product_id in (Select distinct product_id from base_data)
        and a.fc_code = 'BD'
        and sku_system_status <> 'GIFT'
        )
        Select * from thuocsi_sku_status
        where row_num = 1