config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At minute 15 past 2 hours`,
    name: "sku_status_thuocsi",
    tags: ["custom_1h_past15"],
    columns: {/*"*/
        
    }
}

WITH base_data AS (
    SELECT DISTINCT product_id
    FROM ${source.circa_os}.order_purchase_order_item
    WHERE (sku IS NOT NULL OR sku <> '')
      AND received_quantity <> 0
) -- lấy danh sách sản phẩm đã mua trong quá khứ
,thuocsi_sku_status AS (
    SELECT DISTINCT
            a.product_id
           ,sku_system_status
           ,ROW_NUMBER() OVER (
                PARTITION BY a.product_id
                ORDER BY CASE a.sku_system_status
                            WHEN 'NORMAL' THEN 1
                            WHEN 'LIMIT' THEN 2
                            WHEN 'OUT_OF_STOCK' THEN 3
                            WHEN 'SUSPENDED' THEN 4
                            ELSE 5
                         END
            ) AS row_num
    FROM ${source.ref}.adhoc_pm_master_sku a
    WHERE product_id IN (SELECT DISTINCT product_id FROM base_data)
      AND a.fc_code = 'BD'
      AND sku_system_status <> 'GIFT'
)
SELECT *
FROM thuocsi_sku_status
WHERE row_num = 1
