config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At minute 15 past 2 hours`,
    name: "sku_status_thuocsi",
    tags: ["custom_1h_past15"],
    columns: {/*"*/
        
    }
}

WITH base_data AS (
    SELECT DISTINCT product_id
    FROM gold_buymed_vn2.cos_dim_product
),


sku_aggregated AS (
    SELECT
        a.product_id
        ,a.sku_system_status
        ,SUM(a.available_qty) OVER (PARTITION BY a.product_id) AS available_qty
        ,ROW_NUMBER() OVER (
            PARTITION BY a.product_id
            ORDER BY CASE a.sku_system_status
                        WHEN 'NORMAL'       THEN 1
                        WHEN 'LIMIT'        THEN 2
                        WHEN 'OUT_OF_STOCK' THEN 3
                        WHEN 'SUSPENDED'    THEN 4
                        ELSE 5
                     END
        ) AS row_num
    FROM ${source.ref}.adhoc_pm_master_sku a
    INNER JOIN base_data b ON a.product_id = b.product_id
    WHERE a.sku_system_status <> 'GIFT'
    --AND a.fc_code = 'BD'
)

SELECT
     product_id
    ,sku_system_status
    ,available_qty
FROM sku_aggregated
WHERE row_num = 1