config {
    type: "table",
    description: ` target OS PIC: huyen.ngo; model_type: Table ;schedule: Manual`,
    //tags:["10h30"],
    name: "target_sales"
}

WITH target_old AS (
    SELECT *
    FROM buymed_external.target_sales_v2
    WHERE pos_code IS NOT NULL
      AND month <= '2025-11-01'

    UNION ALL 

    SELECT *
    FROM buymed_external.target_sales_fs
    WHERE pos_code IS NOT NULL
)
,target_from_m12 AS (
    SELECT *
    FROM (
        SELECT
                code AS pos_code
               ,DATE(submit_at) AS year_month
               ,type
               ,value
        FROM collector.data_prd
        WHERE object = 'CIRCA_TARGET'
          AND type IN (
                'ACTIVE_CUSTOMERS'
               ,'TARGET_REVENUE'
               ,'TARGET_MARGIN'
               ,'REPEAT_CUSTOMERS'
               ,'TARGET_GMV'
               ,'TARGET_TRANSACTIONS'
          )
    )
    PIVOT (
        MAX(value) FOR type IN (
            'ACTIVE_CUSTOMERS'
           ,'TARGET_REVENUE'
           ,'TARGET_MARGIN'
           ,'REPEAT_CUSTOMERS'
           ,'TARGET_GMV'
           ,'TARGET_TRANSACTIONS'
        )
    )
)
SELECT Pos_Code                               AS pos_code 
       ,Month                                 AS year_month
       ,Target_GMV                            AS target_gmv
       ,Target_Net_Rev_af_tax                 AS target_rev_vat_in
       ,Target_Margin                         AS target_margin
       ,Target_transactions                   AS target_transactions
       ,NULL                                  AS target_active_customers
       ,NULL                                  AS target_repeat_customers
FROM target_old
WHERE pos_code <> 'Chưa có mã'

UNION ALL 

SELECT pos_code                               AS pos_code 
       ,year_month                            AS year_month
       ,CAST(NULL AS FLOAT64)                 AS target_gmv
       ,CAST(TARGET_REVENUE AS FLOAT64)       AS target_rev_vat_in
       ,NULL                                  AS target_margin
       ,CAST(TARGET_TRANSACTIONS AS INT64)    AS target_transactions
       ,CAST(ACTIVE_CUSTOMERS AS INT64)       AS target_active_customers
       ,CAST(REPEAT_CUSTOMERS AS INT64)       AS target_repeat_customers
FROM target_from_m12
WHERE pos_code <> 'Chưa có mã'
