config {
    type: "table",
    description: `thuocsi_price_by_level - lấy giá mua hàng từng sản phẩm theo level của FS trên sàn thuốc sỉ
             PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 past 2 hours `,
    tags: ["custom_1h_past15"],
    name: "thuocsi_price_fs",
}
 
with t as (
select
  a.product_id,
  a.fc_code,
  a.price_after_discount as min_price_thuocsi,
  CASE WHEN td.unit = 'Tube' THEN 'Tuýp' ELSE td.unit END AS thuocsi_unit
from `gold_buymed_vn2.dim_product_sku_pricing` a
left join `platinum_buymed_vn.marketplace_prd_product_v2_sku` b on a.item_code = b.item_code
left join gold_buymed_vn2.dim_product td ON td.product_id = a.product_id
where (a.seller_code = 'MEDX' or a.seller_class = 'EXTERNAL')
  and b.status in ('NORMAL', 'LIMIT')
  and b.is_active
  and a.fc_code in ('HN', 'BD')
qualify row_number() over(partition by a.product_id, a.fc_code order by a.price_after_discount asc) = 1
)
    SELECT DISTINCT
            t.*
           ,CONCAT(t.product_id, '_', t.fc_code) AS product_fc_code
    FROM t
    LEFT JOIN ${source.ref}.circafs_lastest_price p ON t.product_id = p.product_id AND t.fc_code = p.fc_code
    --WHERE CONCAT(t.product_id, '_', fc_code) IN (SELECT DISTINCT product_thuocsi_id FROM ${source.ref}.circafs_lastest_price)
    GROUP BY ALL
format lại, đổi dấu , ra phía trước