config {
    type: "table",
    description: `thuocsi_price_by_level - lấy giá mua hàng từng sản phẩm theo level của FS trên sàn thuốc sỉ
             PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 past 2 hours `,
    tags: ["custom_1h_past15"],
    name: "thuocsi_price_fs",
}
 
WITH t AS (
    SELECT
          a.product_id
        , a.fc_code
        , a.price_after_discount AS min_price_thuocsi
        , CASE 
            WHEN td.unit = 'Tube' THEN 'Tuýp' 
            ELSE td.unit 
          END AS thuocsi_unit
    FROM `gold_buymed_vn2.dim_product_sku_pricing` a
    LEFT JOIN `platinum_buymed_vn.marketplace_prd_product_v2_sku` b ON a.item_code = b.item_code
    LEFT JOIN `gold_buymed_vn2.dim_product` td  ON td.product_id = a.product_id
    WHERE (a.seller_code = 'MEDX' OR a.seller_class = 'EXTERNAL')
      AND b.status IN ('NORMAL', 'LIMIT')
      AND b.is_active
      AND a.fc_code IN ('HN', 'BD')
    QUALIFY ROW_NUMBER() OVER (PARTITION BY a.product_id, a.fc_code 
            ORDER BY a.price_after_discount ASC
        ) = 1
)

SELECT DISTINCT
      t.*
    , CONCAT(t.product_id, '_', t.fc_code) AS product_fc_code
FROM t
LEFT JOIN ${source.ref}.circafs_lastest_price p ON t.product_id = p.product_id 
                                           AND t.fc_code = p.fc_code

GROUP BY ALL