config {
    type: "table",
    description: `thuocsi_price_by_level - lấy giá mua hàng từng sản phẩm theo level của FS trên sàn thuốc sỉ
             PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 past 2 hours `,
    tags: ["custom_1h_past15"],
    name: "thuocsi_price_by_level",
}
 
 WITH fee AS (
    SELECT DISTINCT
            c.province_name
           ,c.district_name
           ,c.sales_region_code
           ,a.fee_value
           ,a.district_code
           ,CONCAT("Delivery_Fee_", DENSE_RANK() OVER (ORDER BY a.fee_value)) AS delivery_level
    FROM (
        SELECT
                code AS district_code
               ,fee_value
        FROM platinum_buymed_vn.marketplace_prd_pricing_v2_setting
        WHERE type = 'DELIVERY_REGION'
           OR type IS NULL
          AND LENGTH(code) = 3
        QUALIFY ROW_NUMBER() OVER (PARTITION BY type, code ORDER BY synced_at DESC, last_updated_time DESC) = 1
    ) AS a
    LEFT JOIN ${source.ref}.dim_geo_location AS c ON c.district_code = a.district_code
    WHERE c.sales_region_code IS NOT NULL
)
,price AS (
    SELECT DISTINCT
            m.customer_id
           ,p.product_id
           ,CASE WHEN td.unit = 'Tube' THEN 'Tuýp' ELSE td.unit END AS thuocsi_unit
           ,MIN(p.sku_display_price) AS min_price
           ,CONCAT(p.product_id, '_', customer_id) AS product_thuocsi_id
    FROM ${source.ref}.dim_customer m
    LEFT JOIN fee ON m.district_code = fee.district_code
    LEFT JOIN ${source.ref}.adhoc_pricing_full p ON fee.delivery_level = p.delivery_fee
                                                AND m.customer_level = p.customer_level
                                                AND p.sales_region_code = m.config_fc
    LEFT JOIN ${source.ref}.dim_product td ON p.product_id = td.product_id
    WHERE m.customer_id IN (SELECT DISTINCT thuocsi_id FROM ${source.ref}.circa_pos_profile WHERE type = 'FS')
      AND CONCAT(p.product_id, '_', customer_id) IN (SELECT DISTINCT product_thuocsi_id FROM ${source.ref}.circafs_lastest_price)
    GROUP BY ALL
)
,_all AS (
    SELECT price.*
           ,CONCAT(product_id, '_', LOWER(thuocsi_unit)) AS productid_unit
           ,p.client_id
    FROM price
    LEFT JOIN ${source.ref}.circa_pos_profile p ON price.customer_id = p.thuocsi_id
)
SELECT DISTINCT p.*
       ,po.name
       ,r.* EXCEPT (product_id, client_id)
       ,p.min_price / convert_rate AS base_unit_price_thuocsi
FROM _all p 
LEFT JOIN gold_buymed_vn2.circa_pos_profile po ON p.customer_id = po.thuocsi_id
LEFT JOIN gold_buymed_vn2.cos_product_convert_base_unit r ON p.product_id = r.product_id
                                                        AND LOWER(p.thuocsi_unit) = LOWER(r.convert_unit)
                                                        AND po.client_id = r.client_id
-- WHERE r.convert_rate IS NULL
ORDER BY po.name
