config {
    type: "table",
    description: `"tracking_purchase_put - Tracking quy trình nhận hàng qua phiếu GR, put lên kệ bằng phiếu PUT
                   PIC: huyen.ngo; model_type: Table ;schedule: At minute 15 every hour`,
    /**/
    tags: ["custom_1h_past15"],
    name: "tracking_purchase_put",
    columns: {
        
    }
}
WITH base_unit_selection AS (
    SELECT
            product_id
           ,client_id
           ,base_unit
           ,ROW_NUMBER() OVER (PARTITION BY product_id, client_id ORDER BY COUNT(*) DESC) AS rn
    FROM ${source.ref}.cos_product_convert_base_unit
    WHERE client_id = 1
    GROUP BY product_id, client_id, base_unit
)
,base_unit AS (
    SELECT a.*
    FROM ${source.ref}.cos_product_convert_base_unit a
    LEFT JOIN base_unit_selection b ON a.product_id = b.product_id
                                    AND a.client_id = b.client_id
                                    AND a.base_unit = b.base_unit
    WHERE b.rn = 1
)
,purchase_order AS (
    SELECT DISTINCT 
            o.code
           ,o.status
           ,o.id
           ,o.pos_id 
           ,p.name AS pos_name
           ,DATETIME_ADD(o.created_at, INTERVAL 7 HOUR) AS created_at
           ,DATE(DATETIME_ADD(o.created_at, INTERVAL 7 HOUR)) AS created_date
           ,i.product_id
           ,i.id AS item_id
           ,SUM(i.quantity) AS demand_quantity
           ,i.unit AS po_unit
           ,SUM(i.received_quantity) AS received_quantity
           ,o.client_id
           ,p.pos_code
           ,o.fulfillment_method
    FROM ${source.circa_os}.order_purchase_order o 
    LEFT JOIN ${source.circa_os}.order_purchase_order_item i ON o.id = i.purchase_order_id
    LEFT JOIN ${source.ref}.circa_pos_profile p ON o.pos_id = p.id
    WHERE o.status <> 'SEPERATED'
      AND p.id IS NOT NULL
      AND o.client_id = 1
      AND i.product_id IS NOT NULL
    -- AND o.code = 'CO00004664'
    GROUP BY ALL
)
,t AS (
    SELECT DISTINCT
            rc.purchase_order_id
           ,rci.ref_id
           ,putd.product_id 
           ,SUM(putd.quantity) AS put_quantity
           ,putd.unit AS put_unit
           ,put.status AS put_status
           ,rc.client_id
    FROM ${source.circa_os}.order_goods_receipt rc
    LEFT JOIN ${source.circa_os}.order_goods_receipt_item rci ON rc.id = rci.goods_receipt_id
    LEFT JOIN ${source.circa_os}.inventory_put_ticket put ON put.goods_receipt_id = rc.id
    LEFT JOIN ${source.circa_os}.inventory_put_ticket_item putd ON putd.put_ticket_id = put.id
                                                                AND rci.id = putd.ref_id
    WHERE rci.received_quantity <> 0
      AND rc.status <> 'CANCELED'
      AND rc.client_id = 1
    GROUP BY ALL
)
,base_tracking AS (
    SELECT DISTINCT
            purchase_order.* EXCEPT (item_id)
           ,put_quantity
           ,put_unit
           -- ,put_status
           ,put_quantity * cv.convert_rate AS put_base_qty 
    FROM purchase_order
    LEFT JOIN t ON purchase_order.id = t.purchase_order_id
               AND purchase_order.item_id = t.ref_id
               AND purchase_order.product_id = t.product_id
               AND purchase_order.client_id = t.client_id
    LEFT JOIN ${source.ref}.cos_dim_product td ON t.product_id = td.product_id
    LEFT JOIN base_unit cv ON cv.product_id = t.product_id
                           AND put_unit = cv.convert_unit
    WHERE purchase_order.id IS NOT NULL
    GROUP BY ALL
)
,to_check AS (
    SELECT DISTINCT
            base_tracking.* EXCEPT (pos_id, put_quantity, put_base_qty)
           ,SUM(put_quantity) AS total_put_quantity
           ,SUM(put_base_qty) AS put_base_qty
           ,base_tracking.received_quantity * cv.convert_rate AS po_base_qty
    FROM base_tracking
    LEFT JOIN base_unit cv ON cv.product_id = base_tracking.product_id
                           AND po_unit = cv.convert_unit
    GROUP BY ALL
)
SELECT to_check.* 
       ,CONCAT(product_id, "_", pos_code) AS product_pos_code
       ,CONCAT(product_id, "_", client_id) AS product_client_id
       ,CASE 
            WHEN to_check.put_base_qty <> po_base_qty THEN 'true'
            WHEN to_check.total_put_quantity IS NULL AND to_check.received_quantity > 0 THEN 'not_yet_put'
            WHEN to_check.total_put_quantity IS NULL AND to_check.received_quantity = 0 THEN 'not_yet_have_item'
            ELSE 'false'
        END AS is_difference
FROM to_check
