config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every 2 hours.Circa OS Transaction order `
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_3h_past5"],
    name: "cos_voucher_info",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}



with t as (
Select distinct
        gift_id
        ,gift_code
        ,DATETIME_ADD(v.created_at, INTERVAL 7 HOUR) as created_at
        ,voucher_id
        ,voucher_code
        ,JSON_EXTRACT_SCALAR(order_code) as order_code_created
FROM ${source.circa_os}.promotion_gift_voucher v,
UNNEST(JSON_EXTRACT_ARRAY(assigned_order_codes)) AS order_code
where gift_code not like '%TEST%'
)
Select distinct 
               us.code
              ,DATETIME_ADD(us.created_at, INTERVAL 7 HOUR) as created_at
              ,DATETIME_ADD(us.start_date, INTERVAL 7 HOUR) as start_date
              ,DATETIME_ADD(us.end_date, INTERVAL 7 HOUR) as end_date
              ,us.discount_value
              ,us.percent
              ,us.promotion_voucher_type
              ,e.name
              ,COALESCE(i.customer_phone, e.phone_number) AS customer_phone
              ,DATETIME_ADD(ov.created_at, INTERVAL 7 HOUR) as Date_used
              ,case when ov.created_at is not null then "Yes"
                     else "No"
                     end as Is_used
               ,ov.order_code as order_code_use
               ,cp.code as Campaign_code
               ,cp.name as Compaign_name
               ,pr.code as Pos_code
               ,pr.name as Pos_name
from  ${source.circa_os}.promotion_promotion_voucher us  
left join t on us.code = t.voucher_code
left join ${source.ref}.cos_fact_order o on o.order_code = t.order_code_created
left join ${source.circa_os}.entity_pos_profile pr on o.pos_id = pr.id
left join  ${source.circa_os}.order_delivery_info i ON o.order_id = i.order_id
left join ${source.circa_os}.entity_entity e ON o.entity_id = e.id
left join ${source.circa_os}.order_order_voucher ov on ov.voucher_id = t.voucher_id
left join ${source.circa_os}.promotion_promotion_campaign cp on us.promotion_campaign_id = cp.id