config {
    type: "table", 
    description: 
        `
        All types of SKU prices including display price (calculated according to the pricing formula for PLATINUM-level customer in HCM, HN, DN corresponding to 3 sales regions ), deal price, campaign price, setting price, purchase price, price after rebate and the net price received of external seller;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.platinum}.marketplace_prd_promotion_voucher,
            ${source.ref}.dim_promotion
        `,
    tags: ["custom_1h_past5"]
}

SELECT 
    a.transformed_at,
    a.sku_last_updated_at,
    d.rebate_date_get_at,
    a.product_id,
    a.sku_code,
    a.supplier_class,
    a.product_name,
    a.sales_region_code,
    CONCAT(a.product_id, "_", a.seller_code, "_", a.sales_region_code) AS sku_key_sales_region_code,
    a.cic_name, 
    a.retail_price_value,
    a.purchase_price,
    a.purchase_price_after_VAT,
    d.price_after_rebate AS rebate_price,
    d.price_after_rebate_with_adhoc_promotion AS rebate_price_with_adhoc_promotion,
    d.price_contract,
    a.display_price,
    b.campaign_price,
    COALESCE(b.campaign_type, b.deal_type) AS promotion_type,
    b.deal_price,
    c.display_price_seller_with_promo,
    c.display_price_seller_without_promo,
    c.seller_received_with_promo,
    c.seller_received_without_promo,
    IF(
        supplier_class = 'INTERNAL',
        COALESCE( b.campaign_price, b.deal_price, a.display_price),
        COALESCE(c.display_price_seller_with_promo, c.display_price_seller_without_promo)
    ) AS sku_display_price
FROM ${source.gold}.adhoc_pricing_display_price_v2 AS a
    LEFT JOIN ${source.gold}.adhoc_pricing_promotion_price_v2 AS b 
        ON a.sku_code = b.sku_code AND a.sales_region_code = b.sales_region_code
    LEFT JOIN ${source.gold}.adhoc_pricing_seller_pricing_v2 AS c 
        ON a.sku_code = c.sku_code AND a.sales_region_code = c.sales_region_code
    LEFT JOIN ${source.gold}.adhoc_pricing_rebate_price AS d 
        ON a.sku_code = d.sku_code AND a.sales_region_code = d.sales_region_code