
-- new
config {
    type: "view",
    name: "platform_event_prd_management_participant",
    schema: "platinum_buymed_vn",
}

-- new




SELECT
 *,
 date(created_time) as created_date
FROM lakehouse-prod-394907.silver_buymed_vn.platform_event_prd_management_participant o 
  
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)