
-- new
config {
    type: "table",
    name: "integration_prd_tpl_callback_callback",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id'
    }
}


SELECT
 *
FROM ${source.silver}.integration_prd_tpl_callback_callback o 
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)
