config {
    type: "table",
    schema: "platinum_buymed_vn",
    name: "marketplace_prd_product_v2_pr_sku_item_pricing_level_log",
    assertions: {
        uniqueKey: 'mg_id',
        // nonNull: ["created_date"]
    },
    bigquery: {
        partitionBy: "created_date"
    },
    tags:["custom_2h_past7"]
}
SELECT
 *,
 CASE 
    WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
    ELSE "2099-01-01"
  END AS created_date
FROM lakehouse-prod-394907.silver_buymed_vn.marketplace_prd_product_v2_pr_sku_item_pricing_level_log o 
 QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC)