config {
    type: "view",
    name: "pim_prd_product_brand",
    schema: "platinum_buymed_vn",
    tags:["pim_prd_product"]
}

SELECT *,
 CASE 
    WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
    ELSE "2099-01-01"
  END AS created_date
FROM ${source.silver}.pim_prd_product_brand
QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)