config {
    type: "table",
    name: "marketplace_prd_product_v2_wishlist",
    schema: "platinum_buymed_vn",
    // assertions: {
    //     uniqueKey: 'mg_id',
    //     nonNull: ["created_date"]
    // },
    bigquery: {
        partitionBy: "created_date"
    },
    tags:["platinum_custom_2h_past5","marketplace_prd_product-v2","VN_product"]
}

SELECT *,
 CASE 
    WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
    ELSE "2099-01-01"
  END AS created_date
FROM ${source.silver}.marketplace_prd_product_v2_wishlist
QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)