config {
    type: "table", 
    description: 
        `PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.platinum}.marketplace_prd_order_v2_order,
            ${source.platinum}.marketplace_prd_customer_customer_rating,
            ${source.ref}.fact_outbound_ticket,
            ${source.platinum}.accounting_prd_core_credit_note,
            ${source.platinum}.accounting_prd_core_bill
        `,
    tags: ["custom_1h_past5"],
    columns: {
        created_at: "The date and time when the order was placed, timezone +7",
        last_updated_time: "The last and time when the record was updated, timezone +7",
        confirmed_time: "The date and time when the record was confirmed, timezone +7",
        customer_id: "Foregin key for dim_customer, a unique identifier for customer who placed the order",
        order_id: "Primary key, a unique identifier for the order",
        so_code: "A code representing the sales order, another unique identifier for the order, it has more meaning with the fulfillment system than order_id",
        order_status: "The current status of the order in our e-commerce marketplace user interface, WAIT_TO_CONFIRM: Order received, awaiting sys confirmation,PROCESSING: Order confirmed, being prepared for fulfillment,WAIT_TO_DELIVER: Ready for delivery, not yet shipped,DELIVERING: Shipped and en route to the customer,DELIVERED: Successfully delivered to the customer,COMPLETED: Order and all associated processes fully complete,CANCEL: Order cancelled by customer",
        so_status: "The current status of the order in our fulfillment process system,RETURNED: Item returned, awaiting system review for inspection or refund actions,CHECKING: Under system inspection for quality or order accuracy before further action,DELIVERING: Item en route, indicating active delivery from warehouse to customer,TRANSPORTING: In transit, covering item's journey from origin to delivery point,CANCEL: Cancelled by system or customer, stopping all order processing and delivery,DELIVERED: Successfully reached customer, marking completion of delivery process,WAIT_TO_DELIVERY: Packed and ready, pending delivery service pickup for dispatch,COMPLETED: Order fully processed, including post-delivery actions like payment settlement",
        ordered_line_items: "The total number of stock-keeping units (SKUs) placed",
        ordered_quantity: "The total quantity of items ordered",
        ordered_amount: "The total valuation, the original valuation of all product in the order",
        ordered_amount_aft_discount: "The total valuation of the order after discounts and fees have been applied",
        notional_amount: "The notional or theoretical or potential delivered amount of the order",
        has_deal: "Indicates whether the order includes a special deal or promotion",
        payment_method: "The method of payment used for the order",
        shipping_address: "Full text detail of shipping address provided by the customer",
        shipping_province_code: "Foregin key for dim_province, the code for the province in the shipping address, under region level",
        shipping_disitrict_code: "Foregin key for dim_district, the code for the district in the shipping address, under province level",
        shipping_ward_code: "Foregin key for dim_ward and dim_location, the code for the ward in the shipping address, under district level",
        customer_order_index: "The number of orders related to the customer at the moment he/she placed the order",
        fc_code: "Foregin key for dim_fc, the code for the fulfillment center or warehouse from which the order is shipped",
        order_type: "Indicate the type of order, classified as either a 'split_order' or 'normal_order' otherwise",
        assist_order: "True or False, Indicate whether the order was placed by the assistance from salesperson",
        return_amount: "the amount associated with a return, if appicable",
        employee_id: "Foregin key for dim_employee, a unique identifier for salesperson who helped customer placing the order"
    },
    bigquery: {
        partitionBy: "DATETIME_TRUNC((created_at),month)",
        clusterBy: ["order_id"]
    },

    //assertions: {
    //  uniqueKey: ["order_id"],
    //  nonNull: ["order_id", "customer_id"]
    //}
}

WITH
  return_amount AS (
    SELECT 
      order_id
      ,SUM(amount) AS return_amount
    FROM ${source.platinum}.accounting_prd_core_credit_note
    WHERE type = "RETURN"
    GROUP BY 1 
  ),


  invoice_amount AS(
    SELECT 
      order_id
      ,SUM(total_order_amount) AS invoice_amount
    FROM ${source.platinum}.accounting_prd_core_bill
    WHERE status <> "CANCEL"
    GROUP BY 1 
  ),

  actual_sales_amount AS(
    SELECT 
      a.order_id
      , GREATEST(SUM(a.invoice_amount) - SUM(b.return_amount), 0) AS actual_sales_amount,
    FROM invoice_amount AS a
      LEFT JOIN return_amount AS b ON a.order_id = b.order_id
    GROUP BY 1 
  ),

  customer_rating AS(
    SELECT
      order_id,
      type,
      point,
      feedback
    FROM ${source.platinum}.marketplace_prd_customer_customer_rating
    QUALIFY ROW_NUMBER() OVER(PARTITION BY order_id ORDER BY last_updated_time DESC) = 1
  ),

  fact_order AS(
    SELECT
      TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) AS transformed_at,
      DATETIME(a.created_time, 'Asia/Ho_Chi_Minh') AS created_at,
      DATETIME(a.last_updated_time, 'Asia/Ho_Chi_Minh') AS last_updated_time,
      DATETIME(a.confirmation_date,'Asia/Ho_Chi_Minh' ) AS confirmed_time,
      a.customer_id,
      a.customer_name, -- Không được xóa, vì name này là shipping_name khác với customer_name trong dim_customer
      a.customer_phone,-- Không được xóa, vì phone này là shipping_phone khác với customer_phone trong dim_customer
      a.order_id,
      a.sale_order_code AS so_code,
      a.status AS order_status,
      a.total_item AS ordered_line_items,
      a.total_quantity AS ordered_quantity,
      a.price AS ordered_amount,
      a.total_price AS ordered_amount_aft_discount,
      a.total_notional_price AS total_notional_amount,
      a.notional_price AS notional_amount,
      a.has_deal,
      a.payment_method,
      a.payment_method_percentage,
      a.customer_shipping_address AS shipping_address,
      a.customer_district_code AS shiping_district_code,
      CASE
        WHEN SAFE_CAST(a.customer_ward_code AS integer) > 0 THEN a.customer_ward_code
        ELSE
          a.customer_district_code
      END AS shipping_ward_code,
      -- COALESCE(a.customer_ward_code, a.customer_district_code)  AS shipping_ward_code,
      a.customer_ward_code AS original_shipping_ward_code,
      a.customer_province_code AS shipping_province_code,
      a.customer_order_index,
      CASE
        WHEN (a.warehouse_code IS NULL) OR (a.warehouse_code ="") THEN "BD" -- huong.dang add
        ELSE a.warehouse_code
      END
        AS fc_code,
      a.sale_order_status AS so_status,
      JSON_VALUE(a.extra_props, '$.note') AS note,
      JSON_VALUE(a.extra_props, '$.auto_cancel_overdue_transfer') AS auto_cancel_overdue_transfer,
      a.system_display,
      JSON_VALUE(a.source_detail, '$.platform') AS source_detail_platform,
      a.source,
      CASE
        WHEN TO_JSON_STRING(a.tags) LIKE '%MULTIPLE_DELIVERY_ORDER%' THEN 'split_order'
        ELSE 'normal_order'
      END AS order_type,
      CASE
        WHEN TO_JSON_STRING(a.tags) LIKE '%ORDER_ASSIST%' THEN TRUE
        ELSE FALSE
      END AS assist_order,
      r.type,
      JSON_VALUE(a.extra_props,"$.confirm_type") AS confirm_type,-- tung.vu added
      JSON_VALUE(a.extra_props,"$.note") AS customer_note,
      JSON_VALUE(a.invoice, '$.invoice_request') AS invoice_request,-- tung.vu added
      JSON_VALUE(a.invoice, '$.company_address') AS company_invoice_address,
      JSON_VALUE(a.invoice, '$.company_name') AS company_invoice_name,-- nguyen.tran added
      r.point,
      r.feedback,
      DATETIME(TIMESTAMP(JSON_VALUE(a.extra_props, '$.cancel_time')),'Asia/Ho_Chi_Minh') AS cancel_time,
      DATETIME(TIMESTAMP(JSON_VALUE(a.extra_props, '$.completed_time')),'Asia/Ho_Chi_Minh') AS completed_time,
      DATETIME(a.outbound_date, 'Asia/Ho_Chi_Minh') AS outbound_time,
      JSON_VALUE(a.extra_props, "$.employee_id") AS employee_id,
      --For order which is created by an employee instead of customer (order_assist)
      DATETIME(a.delivery_date,'Asia/Ho_Chi_Minh') AS expected_delivery_time,
      DATETIME(a.delivered_time,'Asia/Ho_Chi_Minh') AS delivered_time,
      JSON_VALUE(a.extra_props, "$.brand_code") AS brand_code,
      created_by_account_id,
      is_split_delivery_order,
      total_discount,
      b.return_amount,
      c.invoice_amount,
      d.actual_sales_amount,
      COALESCE(a.status, a.sale_order_status) AS sales_status,
      CASE
        WHEN TO_JSON_STRING(tags) LIKE '%SELLER_9SUUUUUUUU%' AND SOURCE = 'brand-portal' THEN 'Consignment Buymed'
        WHEN TO_JSON_STRING(tags) LIKE '%SELLER_VUUUUUUUUU%' AND SOURCE = 'brand-portal' THEN 'Nature Gift Pharma'
        WHEN TO_JSON_STRING(tags) LIKE '%SELLER_Y5STYACBVI%' AND SOURCE = 'brand-portal' THEN 'Duong Anh'
      END AS seller_brand_portal,
      CASE
        WHEN TO_JSON_STRING(a.tags) LIKE '%CO_INTERNAL%' THEN "CO_Sale_Order"
        WHEN TO_JSON_STRING(a.tags) LIKE '%SO_INTERNAL%' THEN "SO_Sale_Receipt"
      END AS internal_portal_type,
      -- e.carrier_name,
      a.province_code,
      a.redeem_code,

      CASE
        WHEN a.source = 'brand-portal' AND JSON_VALUE(a.extra_props, "$.brand_code") IN ('Q8HDUVQX', '2E84FW961P', 'PG961P') THEN 'TENDER'
        WHEN TO_JSON_STRING(JSON_VALUE_ARRAY(a.extra_props, '$.customer_tags')) LIKE '%TENDER%' THEN 'TENDER'
        WHEN a.source IN ('brand-portal', 'clinic-portal') OR customer_id IN (360299, 360439) THEN 'DISTRIBUTION'
        WHEN a.source = 'internal-portal' THEN 'CONSIGNMENT'
        WHEN TO_JSON_STRING(JSON_VALUE_ARRAY(a.extra_props, '$.customer_tags')) LIKE '%"CIRCA"%' THEN 'CIRCA'
        ELSE 'MARKETPLACE'
      END AS channel,

      CASE
          WHEN a.status = 'WAIT_TO_CONFIRM' THEN 1
          WHEN a.status = 'CONFIRMED' THEN 2
          WHEN a.status = 'PROCESSING' THEN 3
          WHEN a.status = 'WAIT_TO_DELIVER' THEN 4
          WHEN a.status = 'DELIVERING' THEN 5
          WHEN a.status = 'DELIVERED' THEN 6
          WHEN a.status = 'COMPLETED' THEN 7
      END AS order_status_seq,

      a.customer_level,
      a.tags,
      IF(a.status = 'CANCEL', "CANCELLED", "NORMAL") AS cancellation,

      redeem_apply_result

    FROM ${source.platinum}.marketplace_prd_order_v2_order AS a
      LEFT JOIN customer_rating r 
        ON a.order_id=r.order_id
      LEFT JOIN return_amount AS b 
        ON a.order_id = b.order_id
      LEFT JOIN invoice_amount AS c 
        ON a.order_id = c.order_id
      LEFT JOIN actual_sales_amount AS d 
        ON a.order_id = d.order_id
      -- LEFT JOIN (
      --   SELECT
      --     order_id, carrier_name
      --   FROM ${ref('fact_outbound_ticket')}
      --   WHERE
      --     REGEXP_CONTAINS(reference_code, r'-F|-P1')
      --   QUALIFY ROW_NUMBER() OVER(PARTITION BY order_id, reference_code ) = 1
      -- ) e ON e.order_id = a.order_id
    WHERE
      a.status <> 'REVERTING' 
  ),

  fact_order_v2 AS (
    SELECT
      a.*,
      CONCAT(CAST(FORMAT_DATE('%m-%Y', date(created_at)) AS STRING), "_", customer_id) as month_id,
      CASE
        WHEN sales_status IN ("CANCEL", "REVERTING") THEN 0
        WHEN sales_status IN ("RETURN","RETURNING","RETURNED","REFUNDED") THEN actual_sales_amount
        WHEN sales_status IN ("COMPLETED", "DELIVERED") AND return_amount > 0 THEN actual_sales_amount
        ELSE ordered_amount_aft_discount
      END AS sales_amount,
        --old loggic
      --   CASE
      --       WHEN ordered_amount + 50001 <= ordered_amount_aft_discount THEN ordered_amount_aft_discount
      --       ELSE ordered_amount 
      -- END AS gmv
      
      -- new logic
      -- some order_id have order_amount = 0 so = > get from ordered_amount_aft_discount to match with fact_sku_order_item_combo
        CASE
            WHEN ordered_amount = 0 THEN ordered_amount_aft_discount
            ELSE ordered_amount 
        END AS gmv
    FROM
      fact_order AS a
  ),

  Orders AS (
    SELECT
      DATE(created_at) AS created_date,
      customer_id,
      FORMAT_DATE('%m-%Y', DATE(created_at)) AS created_month,
      EXTRACT(YEAR FROM DATE(created_at)) AS year,
      EXTRACT(MONTH FROM DATE(created_at)) AS month
    FROM fact_order_v2
    WHERE order_status != "CANCEL" 
    QUALIFY
      ROW_NUMBER() OVER (PARTITION BY customer_id, FORMAT_DATE('%m-%Y', date(created_at)) ORDER BY created_at DESC) = 1
    ORDER BY created_date
  ),

  Orders_prev AS (
    SELECT  
      customer_id,
      created_month,
      year,
      month,
      LAG(created_month) OVER (PARTITION BY customer_id ORDER BY year, month) AS prev_created_month,
      LAG(year) OVER (PARTITION BY customer_id ORDER BY year, month) AS prev_year,
      LAG(month) OVER (PARTITION BY customer_id ORDER BY year, month) AS prev_month
    FROM Orders
  ),

  OrderCustomerType AS (
    SELECT
      CONCAT(cast(created_month as string), "_", customer_id) as month_id,
      customer_id,
      created_month,
      year,
      month,
      prev_created_month,
      prev_year,
      prev_month,
      CASE
        WHEN prev_created_month IS NULL THEN 'New Customer' 
        ELSE
          CASE
            WHEN (year - prev_year) * 12 + (month - prev_month) > 1 THEN 'Reacquire Customer' --caculate the period of prev month and curent row month to find out customer type 
            ELSE 'Repeat Customer'
          END
      END AS customer_type
    FROM Orders_prev
  )

SELECT 
  a.*
  , b.customer_type 
FROM fact_order_v2 AS a 
  LEFT JOIN  OrderCustomerType AS b 
    ON a.month_id = b.month_id
QUALIFY ROW_NUMBER() OVER(PARTITION BY order_id) = 1
