config {
  type: "table",
  description: 
        `
        Details of the items in the order, with combos split into normal products and its prices recalculated according to the corresponding combo;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: daily at 8h30, 10h30, 12h30, 15h30, 17h30, 20h30;
        Source: 
            ${source.platinum}.marketplace_prd_order_v2_order_item,
            ${source.ref}.fact_order
        `,
  bigquery: {
    partitionBy: "date(created_at)",
    clusterBy: ["order_id", "sku_code"]
  },
  tags: ["8h30", "10h30", "12h30", "15h30" ,"17h30", "20h30"],
  columns: {
    created_timekey: "Foreign-Key to Dim_DateTime ",
    created_at: "UTC, When the item was placed",
    item_type: "Normal: type + Combo: sub_type",
    promotion_code: "deal_code + campaign_code",
    sku_orignal_code: "Combo sku_code if buyers placed combo items",
    sku_code: "Single/BOM sku_code if its original is a combo one",
    product_id: "Single/BOM producdt_id if it original is a combo one",
    demand_quantity: "Quantity by BOM SKUs",
    sales_price: "UnitPrice by BOM SKUs"
  }
}

SELECT 
    oi.*
    , CONCAT(product_id, "_", seller_code) AS sku_key
    , o.shipping_province_code AS province_code
    , fc.sales_region_code
    , CONCAT(oi.product_id, "_", oi.seller_code, "_", fc.sales_region_code) AS sku_key_sales_region_code
    , CASE
        WHEN STRPOS(tag_code, "E7GB") > 0 OR STRPOS(sub_tag_code, "E7GB") > 0 THEN "E7GB_MIENBAC"
        WHEN STRPOS(tag_code, "C7GB") > 0 OR STRPOS(sub_tag_code, "C7GB") >0  THEN "C7GB_MIENNAM"
      END AS push_tag
FROM ${ref("fact_order_item_combo")} AS oi 
    LEFT JOIN ${ref('fact_order')} AS o ON oi.order_id = o.order_id
    LEFT JOIN ${ref('dim_fc_service_area')} AS fc ON fc.service_area_code = o.shipping_province_code
