
config {
  type: "incremental",
  bigquery: {
    partitionBy: "date(created_at)",
    clusterBy: ["order_id", "sku_code"]
  },
  name: "fact_order_item_sku_combo",
  tags: [ "8h30", "10h30", "12h30", "15h30" ,"17h30"],
  description: "PIC: anh.letam",
}

pre_operations {
    ${when(
        incremental(),
        `     
            DELETE FROM ${self()}
            WHERE DATE(created_at) >= DATE_SUB(DATE_TRUNC(CURRENT_DATE("+7"), MONTH), INTERVAL 3 MONTH);
            DELETE FROM ${self()}
            WHERE DATE(created_at) < DATE_SUB(DATE_TRUNC(CURRENT_DATE("+7"), MONTH), INTERVAL 12 MONTH);
            
        `
        )
    }
}

with cte_date as (
	select timestamp( date_trunc( date_sub( current_date('+7'), ${when(incremental(),'interval 3 month','interval 12 month')}) , month ) ) as start_date
)
 
select
          oi.mg_id
          , oi.order_id
          , oi.customer_id
          , FORMAT_TIMESTAMP("%Y%m%d%H", oi.created_time ) as created_timekey
          , TIMESTAMP_ADD(oi.created_time, INTERVAL 7 HOUR) as created_at
          , oi.ingest_time as ingested_at
          , current_timestamp transformed_at
          , oi.extra_props
          , oi.product_id
          , oi.sku as sku_code
          , oi.item_code
          , oi.seller_code
          , oi.type as item_type
          , oi.deal_code
          , oi.quantity as demand_quantity
          , oi.price as sales_price
          , oi.charge_deal_fee_value
          , oi.reserved_quantity
          , oi.outbound_quantity
          , oi.returned_quantity
          , oi.seller_price
          , oi.vat
          , oi.none_vat
          , to_json_string(oi.tags) as tag_code
          , oi.sku_status
          , cast(json_value(extra_props, "$.is_important") as BOOLEAN) as is_important
          , coalesce(
            json_extract_scalar( oi.extra_props, "$.campaign_code" ), oi.deal_code
            ) as promotion_code
      FROM ${source.platinum}.marketplace_prd_order_v2_order_item as oi
where created_date >= (select DATE(start_date) from cte_date)