config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "accounting_prd_invoice_order_invoice",
    description : `
    Partition by: created date
    `,
    tags:["platinum","accounting_prd_invoice"]
}

  WITH silver AS (
    SELECT
      key, mg_id, customer_tax_code, amount_without_8_percent_vat, currency_code, bought_time, sync_token, seller_code, created_by_name, customer_email, is_sync_main_circa, code, buyer_name, customer_request, partner_invoice, customer_address, vat_5_percent_amount, vat_8_percent_amount, amount_without_vat, is_skip_check_exported, vat_type, created_time, customer_code, amount_without_5_percent_vat, pattern, is_sync_circa, customer_name, customer_phone, amount_in_words, status, sale_order_code, do_code, series, customer_id, amount, order_id, payment_method, vat_amount, type, last_updated_time, log, amount_without_10_percent_vat, arising_time, created_by_id, hilo_reference_key, invoice_data, is_block_export_invoice, is_import_excel, is_replaced_invoice, is_waiting_tax_of_code, old_code, outbound_time, seller_invoice_code, tax_of_code, vat_10_percent_amount, synced_at, extra_props, action, ingest_time,
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.accounting_prd_invoice_order_invoice
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key, mg_id, customer_tax_code, amount_without_8_percent_vat, currency_code, bought_time, sync_token, seller_code, created_by_name, customer_email, is_sync_main_circa, code, buyer_name, customer_request, partner_invoice, customer_address, vat_5_percent_amount, vat_8_percent_amount, amount_without_vat, is_skip_check_exported, vat_type, created_time, customer_code, amount_without_5_percent_vat, pattern, is_sync_circa, customer_name, customer_phone, amount_in_words, status, sale_order_code, do_code, series, customer_id, amount, order_id, payment_method, vat_amount, type, last_updated_time, log, amount_without_10_percent_vat, arising_time, created_by_id, hilo_reference_key, invoice_data, is_block_export_invoice, is_import_excel, is_replaced_invoice, is_waiting_tax_of_code, old_code, outbound_time, seller_invoice_code, tax_of_code, vat_10_percent_amount, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `accounting_prd_invoice_order_invoice`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"