config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "accounting_prd_core_bill",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","accounting_prd_core"]
}

  WITH silver AS (
    SELECT
      key,mg_id,order_id,status,bill_code,bill_id,created_by,created_by_source,created_time,customer_id,is_auto_create,is_split_delivery_order,credit_note_ids,last_updated_time,order_amount,remain_amount,sale_order_code,total_order_amount,unique_key,vat,actual_amount,auto_complete_fail,do_code,lost_amount,received_amount,return_amount,spent_amount,completed_debt_time,completed_debt_time_info,fee_and_discount_by_do,completed_time,is_auto_complete,payment_ids,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.accounting_prd_core_bill
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,order_id,status,bill_code,bill_id,created_by,created_by_source,created_time,customer_id,is_auto_create,is_split_delivery_order,credit_note_ids,last_updated_time,order_amount,remain_amount,sale_order_code,total_order_amount,unique_key,vat,actual_amount,auto_complete_fail,do_code,lost_amount,received_amount,return_amount,spent_amount,completed_debt_time,completed_debt_time_info,fee_and_discount_by_do,completed_time,is_auto_complete,payment_ids,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `accounting_prd_core_bill`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"