config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "accounting_prd_invoice_order_invoice_item",
    description : `
    Partition by: created date
    `,
    tags:["platinum","accounting_prd_invoice"]
}

  WITH silver AS (
    SELECT
      key, mg_id, product_code, quantity, order_item_type, is_invalid_vat_master_data, product_name, price_without_vat, vat, vat_amount, created_time, product_id, amount_without_vat, amount, lot, expiry_date, order_id, do_code, invoice_code, sku_code, unit, price, synced_at, extra_props, action, ingest_time,
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.accounting_prd_invoice_order_invoice_item
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC
    )
  ), platinum AS (
    SELECT 
      key, mg_id, product_code, quantity, order_item_type, is_invalid_vat_master_data, product_name, price_without_vat, vat, vat_amount, created_time, product_id, amount_without_vat, amount, lot, expiry_date, order_id, do_code, invoice_code, sku_code, unit, price, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `accounting_prd_invoice_order_invoice_item`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"