-- config {
--     type: "incremental",
--     name: "warehouse_prd_inventory_sku_location_suggestion",
--     schema: "platinum_buymed_vn",
--     assertions: {
--         uniqueKey: 'mg_id'
--     },
--     bigquery: {
--         partitionBy: "ingest_date"
--     },
--     description: "",
--     tags: ["custom_1h_past5","warehouse_prd_inventory"]
-- }


-- js {
--   incremental_time = `TIMESTAMP(DATE_TRUNC(CURRENT_DATETIME() - INTERVAL 4 HOUR, DAY))`
--   table_name = `warehouse_prd_inventory_sku_location_suggestion`
-- }


-- pre_operations {
--   ${
--     when(incremental(),
--       `--Incremental--
--       DECLARE checkpoint_date ARRAY<date>;

--       CREATE TEMP TABLE tmp1 AS (
--         SELECT * , 
--           CASE 
--               WHEN ingest_time IS NOT NULL THEN DATE(DATETIME(ingest_time,'Asia/Ho_Chi_Minh'))
--               ELSE "2099-01-01"
--             END AS ingest_date
--         FROM ${source.silver}.${table_name}
--         WHERE ingest_time >= ${incremental_time}
--         QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER (_window) <> 'd'
--         WINDOW _window AS ( 
--             PARTITION BY mg_id
--             ORDER BY synced_at DESC,
--             IF (action = 'd', 3, IF (action = 'u', 2, 1)) DESC,
--             last_updated_time DESC
--         )
--       );
--       --

--       SET checkpoint_date = ARRAY( 
--         SELECT DATE( COALESCE(silver_new.ingest_time, platinum.ingest_time) ,'+7')
--         FROM tmp1 silver_new
--         LEFT JOIN ${self()} platinum ON platinum.mg_id = silver_new.mg_id
--         GROUP BY 1
--       );

--       DELETE FROM ${source.platinum}.${table_name}
--       where ingest_date in UNNEST(checkpoint_date)
--       and mg_id in ( 
--         SELECT DISTINCT mg_id 
--         FROM tmp1
--         );

--       `,
--       `--FullRefresh--
--       CREATE TEMP TABLE tmp1 AS (

--           SELECT * , 
--             CASE 
--                 WHEN ingest_time IS NOT NULL THEN DATE(DATETIME(ingest_time,'Asia/Ho_Chi_Minh'))
--                 ELSE "2099-01-01"
--               END AS ingest_date
--           FROM ${source.silver}.${table_name}
--           QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER (_window) <> 'd'
--           WINDOW _window AS ( 
--               PARTITION BY mg_id
--               ORDER BY synced_at DESC,
--               IF (action = 'd', 3, IF (action = 'u', 2, 1)) DESC,
--               last_updated_time DESC
--         )
--         -- all record deleted include action "d"
--         -- Special case for order -- PIC: AnhLe
--       )`
--     )
--   }
-- }
-- -- 
-- SELECT * FROM tmp1

