
-- new
config {
    type: "incremental",
    name: "warehouse_prd_inbound_waiting_inbound_item",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id'
    },
    bigquery: {
        partitionBy: "DATE(ingest_time)"
    },
    tags:["custom_2h_past5","warehouse_prd_inbound"]
}


SELECT
 *,
FROM ${source.silver}.warehouse_prd_inbound_waiting_inbound_item o 
  ${ when(incremental(), `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()})`)}
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)

post_operations {
  ${
    when(incremental(),
      `
      -- Delete rows using the temporary table
      DELETE FROM ${self()}
      WHERE 
         (key) IN (
        SELECT (key) FROM ${self()} 
        QUALIFY ROW_NUMBER() OVER (_window) > 1
        OR FIRST_VALUE(action) OVER (_window) = "d"
      WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC,
        IF(action = 'd', 3, IF(action = 'u', 2, 1)) DESC,
        last_updated_time DESC
      )
      ) ;
      `,
      ``
    )
  }
}
