config {
    type: "incremental",
    name: "staging_warehouse_prd_inbound_return_ticket",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id',
        nonNull: ["created_date"]
    },
    bigquery: {
        partitionBy: "created_date"
    }
}

pre_operations {
  ${
    when(incremental(),
      `
      DECLARE min_created_date DATE;
      DECLARE max_created_date DATE;

      -- Setting the min_created_date
      SET min_created_date = (
        SELECT MIN(DATE(created_time)) AS min_created_date
        FROM ${source.silver}.warehouse_prd_inbound_return_ticket 
        WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()}) AND action = "u"
      );

      -- Setting the max_created_date
      SET max_created_date = (
        SELECT MAX(DATE(created_time)) AS max_created_date
        FROM ${source.silver}.warehouse_prd_inbound_return_ticket 
        WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()}) AND action = "u"
      );
      `,
      ``
    )
  }
}

SELECT
 *,
 date(created_time) as created_date
FROM ${source.silver}.warehouse_prd_inbound_return_ticket o 
 ${
    when(incremental(), 
      `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()}) 
      QUALIFY ROW_NUMBER() OVER (_window) = 1`,
      `QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'`
    )
  }
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)

post_operations {
  ${
    when(incremental(),
      `
      -- Variable declarations and assignments at the start of the block
      

      IF min_created_date IS NOT NULL AND max_created_date IS NOT NULL THEN

        -- Delete rows using the temporary table
        DELETE FROM ${self()}
        WHERE created_date BETWEEN min_created_date AND max_created_date
          AND (key) IN (
            SELECT (key)
            FROM ${self()}
            WHERE created_date BETWEEN min_created_date AND max_created_date
            QUALIFY ROW_NUMBER() OVER (_window) > 1
            WINDOW _window AS (
              PARTITION BY mg_id
              ORDER BY synced_at DESC,
              IF(action = 'd', 3, IF(action = 'u', 2, 1)) DESC,
              last_updated_time DESC
            )
          );

      END IF;

      IF EXISTS (SELECT mg_id FROM ${self()} WHERE action = "d") THEN
        DELETE FROM ${self()} WHERE mg_id IN (SELECT mg_id FROM ${self()} WHERE action = "d");
      END IF;

      `,
      ``
    )
  }
}