config {
    type: "incremental",
    name: "warehouse_prd_core_warehouse_kpi_report",
    schema: "platinum_buymed_vn",
    assertions: { // Will rewrite latter
         uniqueKey: 'mg_id'
     },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["platinum_custom_1h_past7","warehouse_prd_core"]
}
pre_operations {
  ${
    when(incremental(),
      `
      DECLARE Ingest_checkpoint TIMESTAMP;
      DECLARE checkpoint_date ARRAY<date>;

      SET Ingest_checkpoint = (SELECT max(ingest_time) FROM ${self()});

      SET checkpoint_date = ARRAY( 
        SELECT DISTINCT IF(created_time is NULL, "2099-01-01" , DATE( DATETIME(created_time,'Asia/Ho_Chi_Minh') ) )
        FROM ${source.silver}.warehouse_prd_core_warehouse_kpi_report 
        WHERE ingest_time > Ingest_checkpoint
      );
      
      IF ( SELECT ARRAY_LENGTH(checkpoint_date) > 0 ) THEN
            DELETE FROM ${self()}
            where created_date in UNNEST(checkpoint_date)
            and mg_id in ( 
              SELECT DISTINCT mg_id 
              FROM ${source.silver}.warehouse_prd_core_warehouse_kpi_report
              WHERE ingest_time > Ingest_checkpoint
              );
      END IF;

      `,
      ``
    )
  }
}

--

SELECT
*,
CASE 
    WHEN date IS NOT NULL THEN DATE(DATETIME(TIMESTAMP_SECONDS(date),"+7"))
    ELSE "2099-01-01"
END AS created_date
FROM ${source.silver}.warehouse_prd_core_warehouse_kpi_report o 
${ when(incremental(), `WHERE ingest_time > Ingest_checkpoint ` )}

QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
_window AS (
PARTITION BY
    mg_id
ORDER BY
    synced_at DESC,
    IF
        (action='d',3,
        IF
        (action='u',2,1)) DESC,
        last_updated_time DESC)
