
-- new
config {
    type: "incremental",
    name: "staging_warehouse_prd_inbound_put_ticket_item",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id',
        nonNull : ["created_date"]
    },
    bigquery: {
        partitionBy: "created_date"
    }
}

pre_operations {
  ${
    when(incremental(),
      `
      CREATE OR REPLACE TEMP TABLE range_created_time_table AS
      SELECT MIN(DATE(created_time)) AS min_created_date, MAX(DATE(created_time)) AS max_created_date
      FROM ${source.silver}.warehouse_prd_inbound_put_ticket_item WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()}) and action = "u";
      `,
      ``
    )
  }
}

SELECT
 *,
 date(created_time) as created_date
FROM ${source.silver}.warehouse_prd_inbound_put_ticket_item o 
 ${
    when(incremental(), 
      `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()}) 
      QUALIFY ROW_NUMBER() OVER (_window) = 1`,
      `QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'`
    )
  }
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)

post_operations {
  ${
    when(incremental(),
      `
      -- Delete rows using the temporary table
      IF EXISTS (SELECT * from range_created_time_table where min_created_date is not null and max_created_date is not null)
      then

      DECLARE min_created_date DATE;
DECLARE max_created_date DATE;

-- Set the variables with the min and max created_date values
      DECLARE min_created_date DATE;
      DECLARE max_created_date DATE;
      SET min_created_date = (SELECT min_created_date FROM range_created_time_table );
      SET max_created_date = (SELECT max_created_date FROM range_created_time_table);
      DELETE FROM ${self()}
      WHERE (created_date BETWEEN min_created_date
        AND max_created_date
          and 
         (key) IN (
        SELECT (key) FROM ${self()} where created_date BETWEEN min_created_date
        AND max_created_date 
        QUALIFY ROW_NUMBER() OVER (_window) > 1
        --OR FIRST_VALUE(action) OVER (_window) = "d"
      WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC,
        IF(action = 'd', 3, IF(action = 'u', 2, 1)) DESC,
        last_updated_time DESC
      )
      ));
      end if;
     
      if EXISTS (SELECT mg_id as action_d
      FROM ${self()} where action = "d" )
      then
      delete from  ${self()} where mg_id in (select mg_id from ${self()} where action = "d");
      end if;
      
      `,
      ``
    )
  }
}
