config {
    type: "incremental",
    name: "warehouse_prd_picking_pick_ticket_item",
    schema: "platinum_buymed_vn",
    assertions: {
         uniqueKey: 'mg_id',
         nonNull: ['created_date'],
         //rowConditions: [
         //   '(created_time is not null and last_updated_time is not null) or (created_time is null and last_updated_time is not null) or (created_time is not null and last_updated_time is null)',
         //   'action != "d"'
        //]
     },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["custom_1h_past7","warehouse_prd_picking"]
}



pre_operations {
  ${
    when(incremental(),
      `
      DECLARE Ingest_checkpoint TIMESTAMP;
      DECLARE checkpoint_date ARRAY<date>;

      SET Ingest_checkpoint = TIMESTAMP_SUB(TIMESTAMP(CURRENT_DATE("+7")), INTERVAL 31 HOUR);
      -- Ingest_checkpoint = (SELECT max(ingest_time) FROM ${self()});

      SET checkpoint_date = ARRAY( 
        SELECT DISTINCT IF(created_time is NULL, "2099-01-01" , DATE( DATETIME(created_time,'Asia/Ho_Chi_Minh') ) )
        FROM silver_buymed_vn.warehouse_prd_picking_pick_ticket_item
        WHERE ingest_time >= Ingest_checkpoint
      );
      
      IF ( SELECT ARRAY_LENGTH(checkpoint_date) > 0 ) THEN
            DELETE FROM ${self()}
            where created_date in UNNEST(checkpoint_date)
            and mg_id in ( 
              SELECT DISTINCT mg_id 
              FROM silver_buymed_vn.warehouse_prd_picking_pick_ticket_item
              WHERE ingest_time >= Ingest_checkpoint
              );
      END IF;

      `,
      ``
    )
  }
}

--

SELECT
*,
CASE 
    WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
    ELSE "2099-01-01"
END AS created_date
FROM ${source.silver}.warehouse_prd_picking_pick_ticket_item o
${ when(incremental(), `WHERE ingest_time >= Ingest_checkpoint ` )}

QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
_window AS (
PARTITION BY
    mg_id
ORDER BY
    synced_at DESC,
IF
    (action='d',3,
    IF
    (action='u',2,1)) DESC,
    last_updated_time DESC)

