

config {
    type: "table",
    name: "warehouse_prd_inbound_damage_ticket_item",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id',
        
    },
    tags: ["warehouse_prd_inbound"]
}

SELECT
 * ,
FROM ${source.silver}.warehouse_prd_inbound_damage_ticket_item o 
QUALIFY ROW_NUMBER() OVER (_window) = 1
AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)



