config {
    type: "incremental",
    name: "warehouse_prd_inventory_transfer_sku",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id',
        // nonNull: ["created_date"]
    },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["custom_2h_past5"]
}

pre_operations {
  ${
    when(incremental(),
      `
      --
      DECLARE checkpoint_date ARRAY<date>;

      SET checkpoint_date = ARRAY( 
        SELECT DISTINCT date(created_time,'+7')
        FROM silver_buymed_vn.warehouse_prd_inventory_transfer_sku 
        WHERE ingest_time >= TIMESTAMP_TRUNC((CURRENT_TIMESTAMP() - interval 6 hour), HOUR)
        AND created_time IS NOT NULL
      );

      DELETE FROM platinum_buymed_vn.warehouse_prd_inventory_transfer_sku
      where created_date in UNNEST(checkpoint_date)
      and mg_id in ( 
        SELECT DISTINCT mg_id 
        FROM silver_buymed_vn.warehouse_prd_inventory_transfer_sku 
        WHERE ingest_time >= TIMESTAMP_TRUNC((CURRENT_TIMESTAMP() - interval 6 hour), HOUR)
        );

      `,
      ``
    )
  }
}
--

SELECT
  *,
  CASE 
    WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
    ELSE "2099-01-01"
  END AS created_date

FROM
  ${source.silver}.warehouse_prd_inventory_transfer_sku o 
  ${ when(incremental(),  `WHERE ingest_time > TIMESTAMP_TRUNC((CURRENT_TIMESTAMP() - interval 6 hour), HOUR)`  )}
QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW _window AS ( 
  PARTITION BY mg_id
  ORDER BY 
    synced_at DESC,
    IF (action='d',3, IF (action='u',2,1)) DESC,
    last_updated_time DESC)
