config {
    type: "view",
    description: `PIC: minh.luu, model_type: view, schedule: daily
    Source
        ${source.ref}.dim_order
        ${source.ref}.dim_calendar
        ${source.ref}.fact_order`,
    columns: {
        metric_code: "NonNull | Concat of order_channel and metric lv2 column",
        date: "NonNull | End of month",
        value: "NonNull | gmv"
    }
}
SELECT
    dim_calendar.eom as date,
    "GMV_" || dim_order.order_channel AS metric_code,
    IF(SUM(fact_order.gmv) = 0, NULL,SUM(fact_order.gmv))  as value

FROM `lakehouse-prod-394907.gold_buymed_vn2.fact_order` fact_order
LEFT JOIN `lakehouse-prod-394907.gold_buymed_vn2.dim_order` dim_order
    ON fact_order.order_id = dim_order.order_id
LEFT JOIN `lakehouse-prod-394907.gold_buymed_vn2.dim_calendar` dim_calendar
    ON fact_order.created_date = dim_calendar.Date
GROUP BY 1,2
ORDER BY eom
-- post_operations {
--     ALTER VIEW ${self()} ADD PRIMARY KEY (year_month) NOT ENFORCED
-- }