config {
    type:"table",
    description: `PIC: Huong.Dang; Schedule: 0h00 daily`,
    tags: ('0h00')
}


SELECT *, 
CASE 
WHEN measure = 'GMV_WITH_LISTED_PRICE' THEN 'GMV_GENERAL'
ELSE measure END AS GMV_GENERAL,
"Vietnam" as Country
FROM ${ref(`agg_strategic_general_vn`)}

UNION ALL

SELECT *, 
NULL as GMV_GENERAL,
"Thailand" as Country
FROM ${ref(`agg_strategic_general_thailand`)}

UNION ALL

SELECT *,
NULL as GMV_GENERAL,
"Cambodia" as Country
FROM ${ref(`agg_strategic_general_cambodia`)}
