config {
    type:"table",
    description: `PIC: minh.luu; Schedule: 0h00 daily
    Source;
        ${source.ref}.agg_strategic_gmv-before-cancel
        ${source.ref}.agg_strategic_gmv-after-cancel_cancel
        ${source.ref}.agg_strategic_gmv-fulfilled
        ${source.ref}.agg_strategic_gmv-unff
        ${source.ref}.agg_strategic_gmv-return
        ${source.ref}.agg_strategic_gmv-backlog`,
    columns: {
        date: "NonNull |",
        location: "Nullable |",
        channel: "Nullable |",
        measure: "NonNull |",
        value: "Nullable |"
    },
    tags: ("0h00")
}

js {
    // Measure List for aggregate formula
    sale_order_measure_list = [
        {
            name: "GMV-BEFORE-CANCEL",
            logic: `SUM( fs.sales_price * fs.demand_quantity )`
        },
        // A special case, we need to divide the Marketplace into Seller Center and MEDX for GMV after cancellations only.
        // {
        //     name: "GMV-AFTER-CANCEL",
        //     logic: `
        //     SUM( 
        //     ( fs.sales_price * demand_quantity )  
        //     - IF( fs.order_status like "CANCEL" AND fs.sale_order_code is null, ( fs.sales_price * demand_quantity ),0 )
        //     )`
        // },
        {
            name: "CANCEL",
            logic: `SUM(IF( fs.order_status like "CANCEL", ( fs.sales_price * demand_quantity ), 0))`
        },
        {
            name: "GMV-WITH-LISTED-PRICE",
            logic: "SUM(fs.listed_price * fs.demand_quantity)"
        },
        {
            name: "CANCEL-BEFORE-FFM",
            logic: `SUM(IF( fs.order_status like "CANCEL" AND fs.sale_order_code is null, ( fs.sales_price * demand_quantity ),0 ))`
        },
        {
            name: "CANCEL-AFTER-FFM",
            logic: `SUM(IF( fs.order_status like "CANCEL" AND fs.sale_order_code is not null, ( fs.sales_price * demand_quantity ),0 ))`
        },
        {
            name: "GMV-FULFILLED",
            logic: `SUM(IF( fs.order_status not like "CANCEL" ,(fs.outbound_quantity - fs.returned_quantity),0) * fs.sales_price)`
        },
        {
            name: "GMV-UNFF",
            logic: `SUM(IF( fs.order_status not like "CANCEL" AND fs.order_status in ("DELIVERING","DELIVERED","COMPLETED"),(fs.demand_quantity - fs.outbound_quantity ) ,0 ) * fs.sales_price)`,
        },
        {
            name: "GMV-BACKLOG",
            logic: `SUM(IF( fs.order_status not like "CANCEL" AND fs.order_status not in ("DELIVERING","DELIVERED","COMPLETED"),  (fs.demand_quantity - fs.outbound_quantity ) ,0 ) * fs.sales_price)`,
        },
        {
            name: "GMV-RETURN",
            logic:`SUM(IF( fs.order_status not like "CANCEL" , fs.returned_quantity, 0) * fs.sales_price)`,
        },
        {
            name: "NMV",
            logic: `SUM(IF( fs.order_status like "CANCEL" AND fs.sale_order_code is not null, ( fs.sales_price * fs.demand_quantity ),0 ) -- AS cancel_after_ffm
                + IF( fs.order_status not like "CANCEL" ,(fs.outbound_quantity - fs.returned_quantity),0) * fs.sales_price -- AS fulfilled_amount
                + IF( fs.order_status not like "CANCEL" AND fs.order_status not in ("DELIVERING","DELIVERED","COMPLETED"),  (fs.demand_quantity - fs.outbound_quantity ) ,0 ) * fs.sales_price -- AS backlog_amount,
                + IF( fs.order_status not like "CANCEL" , fs.returned_quantity, 0) * fs.sales_price)  -- AS returned_amount,`
        },
        {
            name: "COMMERICAL-AMOUNT",
            logic: `SUM((fs.listed_price - fs.sales_price) * fs.demand_quantity)`
        },
        {
            name: "COMMERICAL-DEAL-AMOUNT",
            logic: `SUM(IF( commercial_type = "DEAL", (fs.listed_price - fs.sales_price) * demand_quantity, 0))`
        },
        {
            name: "COMMERICAL-CAMPAIGN-AMOUNT",
            logic: `SUM(IF( commercial_type = "CAMPAIGN", (fs.listed_price - fs.sales_price) * demand_quantity, 0))`
        },
        {
            name: "COMMERICAL-COMBO-AMOUNT",
            logic: `SUM(IF( commercial_type = "COMBO",(fs.listed_price - fs.sales_price) * demand_quantity, 0))`
        },
        {
            name: "SO",
            logic: "COUNT(distinct fs.order_id)"
        },
        {
            name: "ITEM-SOLD",
            logic: "SUM(fs.demand_quantity)"
        },
        {
            name: "FFM_RATE",
            logic: `
            (
            SUM( 
            ( fs.sales_price * demand_quantity )  
            - IF( fs.order_status like "CANCEL" AND fs.sale_order_code is null, ( fs.sales_price * demand_quantity ),0 )
            ) -- GMV-AFTER-CANCEL
            
            - SUM(IF( fs.order_status not like "CANCEL" AND fs.order_status in ("DELIVERING","DELIVERED","COMPLETED"),(fs.demand_quantity - fs.outbound_quantity ) ,0 ) * fs.sales_price)
                -- GMV-UNFF
            )
            /

            SUM( 
            ( fs.sales_price * demand_quantity )  
            - IF( fs.order_status like "CANCEL" AND fs.sale_order_code is null, ( fs.sales_price * demand_quantity ),0 )
            ) -- GMV-AFTER-CANCEL
            * 100
            `
        },

    ]

    delivery_order_measure_list = [
        {
            name: "DO",
            logic: `COUNT(DISTINCT do.delivery_order_code)`
        }
    ]
}

WITH ois AS ( -- FOR DO
    -- actually, it just exclude 36 order, so if you query raw, don't need this, the error is very small, but in agg_general, dataform take all fact_strategic, so I will include it
    -- I just exclude the orders that is contains all test item
    SELECT 
        order_id,
        STRING_AGG(DISTINCT supplier_class) supplier_class
    FROM ${ref(`fact_strategic_sale_order_item_single`)} ois 
    GROUP BY 1
), GMV_AFTER_CANCEL_case AS (
    SELECT 
        CURRENT_DATETIME("+7") AS refresh_time,
        dc.eom as date,
        CASE
            WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
            WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
            WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
            ELSE "GMV-VN-REGION-UNKNOWN" 
        END AS location,
        CASE
            WHEN doc.order_channel IN ("MARKETPLACE","CONSIGNMENT" ) THEN
                IF( REGEXP_CONTAINS(fs.supplier_code,"MEDX") ,
                    "MEDX",
                    "SC"
                )
            ELSE doc.order_channel
        END AS channel,
        "GMV-AFTER-CANCEL" AS measure,
        SUM( 
            ( fs.sales_price * demand_quantity )  
            - IF( fs.order_status like "CANCEL" AND fs.sale_order_code is null, ( fs.sales_price * demand_quantity ),0 ) 
        ) value

    FROM ${ref(`fact_strategic_sale_order_item_single`)} fs 
    LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = fs.order_id 
    LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON fs.order_id = dosr.order_id 
    LEFT JOIN ${ref(`dim_calendar`)} dc ON date(fs.created_time) = dc.date
    WHERE  doc.order_channel NOT IN ("TENDER","CONSIGNMENT-RECOGNITION")
    AND doc.order_channel is not null
    AND fs.supplier_class not like "TECH"
    AND date > "2023-01-01"
    GROUP BY 1,2,3,4,5

    UNION ALL 

    SELECT 
        CURRENT_DATETIME("+7") AS refresh_time,
        dc.eom as date,
        CASE
            WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
            WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
            WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
            ELSE "GMV-VN-REGION-UNKNOWN" 
        END AS location,
        order_channel  as channel,
        "GMV-AFTER-CANCEL" AS measure,
        SUM( 
            ( fs.sales_price * demand_quantity )  
            - IF( fs.order_status like "CANCEL" AND fs.sale_order_code is null, ( fs.sales_price * demand_quantity ),0 ) 
        ) value

    FROM ${ref(`fact_strategic_sale_order_item_single`)} fs 
    LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = fs.order_id 
    LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON fs.order_id = dosr.order_id 
    LEFT JOIN ${ref(`dim_calendar`)} dc ON date(fs.confirmation_time) = dc.date
    WHERE  doc.order_channel LIKE "TENDER"
    AND fs.order_status not like "WAIT_TO_CONFIRM"
    AND fs.supplier_class not like "TECH"
    AND date > "2023-01-01"
    GROUP BY 1,2,3,4,5
)

${
    sale_order_measure_list.map((measure,i)=> `
SELECT 
    CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
        ELSE "GMV-VN-REGION-UNKNOWN" 
    END AS location,
    CASE
        WHEN doc.order_channel IN ("MARKETPLACE","CONSIGNMENT" ) THEN "MARKETPLACE"
        ELSE doc.order_channel
    END AS channel,
    "${measure.name}" AS measure,
    ${measure.logic} value

FROM ${ref(`fact_strategic_sale_order_item_single`)} fs 
LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = fs.order_id 
LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON fs.order_id = dosr.order_id 
LEFT JOIN ${ref(`dim_calendar`)} dc ON date(fs.created_time) = dc.date
WHERE  doc.order_channel NOT IN ("TENDER","CONSIGNMENT-RECOGNITION")
AND doc.order_channel is not null
AND fs.supplier_class not like "TECH"
AND date > "2023-01-01"
GROUP BY 1,2,3,4,5

UNION ALL 

SELECT 
    CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
        ELSE "GMV-VN-REGION-UNKNOWN" 
    END AS location,
    order_channel  as channel,
    "${measure.name}" AS measure,
    ${measure.logic} value

FROM ${ref(`fact_strategic_sale_order_item_single`)} fs 
LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = fs.order_id 
LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON fs.order_id = dosr.order_id 
LEFT JOIN ${ref(`dim_calendar`)} dc ON date(fs.confirmation_time) = dc.date
WHERE  doc.order_channel LIKE "TENDER"
AND fs.order_status not like "WAIT_TO_CONFIRM"
AND fs.supplier_class not like "TECH"
AND date > "2023-01-01"
GROUP BY 1,2,3,4,5

${i < sale_order_measure_list.length - 1 ? 'UNION ALL':''}
    `).join('')
}

UNION ALL 


${
    delivery_order_measure_list.map((measure,i)=> `
SELECT 
CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
        ELSE "GMV-VN-REGION-UNKNOWN" 
    END AS location,
    CASE
        WHEN doc.order_channel IN ("MARKETPLACE","CONSIGNMENT" ) THEN "MARKETPLACE"
        ELSE doc.order_channel
    END AS channel,
    'DO' AS measure,
    COUNT(DISTINCT do.delivery_order_code) as value

FROM ${ref(`fact_strategic_delivery_order`)} do 
LEFT JOIN ois ON do.order_id = ois.order_id
LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = do.order_id 
LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON do.order_id = dosr.order_id 
LEFT JOIN ${ref(`dim_order_status`)} dos ON dos.order_id = do.order_id
LEFT JOIN ${ref(`dim_calendar`)} dc ON date(do.created_time) = dc.date
WHERE  doc.order_channel NOT IN ("TENDER","CONSIGNMENT-RECOGNITION")
AND doc.order_channel is not null
AND ois.supplier_class not like "TECH"
AND date > "2023-01-01"
GROUP BY 1,2,3,4,5

UNION ALL 

SELECT 
CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
        ELSE "GMV-VN-REGION-UNKNOWN" 
    END AS location,
    order_channel  as channel,
    'DO' AS measure,
    COUNT(DISTINCT do.delivery_order_code) as value


FROM ${ref(`fact_strategic_delivery_order`)} do 
LEFT JOIN ois ON do.order_id = ois.order_id
LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = do.order_id 
LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON do.order_id = dosr.order_id 
LEFT JOIN ${ref(`dim_order_status`)} dos ON dos.order_id = do.order_id
LEFT JOIN ${ref(`dim_calendar`)} dc ON date(do.confirmation_time) = dc.date
WHERE  doc.order_channel LIKE "TENDER"
AND dos.crm_status not like "WAIT_TO_CONFIRM"
AND ois.supplier_class not like "TECH"
AND date > "2023-01-01"
GROUP BY 1,2,3,4,5

${i < delivery_order_measure_list.length - 1 ? 'UNION ALL':''}
    `).join('')
}

UNION ALL 
-- For Special Case
SELECT * FROM GMV_AFTER_CANCEL_case

UNION ALL 
-- For Special Case
SELECT * FROM ${ref(`agg_strategic_customer`)}
WHERE date >= "2023-01-01"
