config {
    type:"table",
    description: `PIC: Huong.Dang; Schedule: 0h00 daily
    Source;
        ${source.ref}.agg_strategic_gmv-before-cancel
        ${source.ref}.agg_strategic_gmv-after-cancel_cancel
        ${source.ref}.agg_strategic_gmv-fulfilled
        ${source.ref}.agg_strategic_gmv-unff
        ${source.ref}.agg_strategic_gmv-return
        ${source.ref}.agg_strategic_gmv-backlog`,
    columns: {
        date: "NonNull |",
        location: "Nullable |",
        channel: "Nullable |",
        measure: "NonNull |",
        value: "Nullable |"
    },
    tags: ("0h00")
}

-- Optimized base calendar with date filtering
WITH base_calendar AS (
  SELECT 
    eom,
    date
  FROM ${ref(`dim_calendar`)}
  WHERE date >= "2023-01-01"),


-- Order_item metrics
order_metrics AS (
  SELECT
    DATE(created_time) as order_date,
    location,
    channel,
    supplier_class,
    -- shipping_ward_code,
    SUM(sales_price * demand_quantity) as gmv_before_cancel,
    SUM(IF(order_status LIKE "CANCEL" AND sale_order_code is null, (sales_price * demand_quantity ),0 )) as cancel_before_ffm,
    SUM(IF(order_status LIKE "CANCEL", (sales_price * demand_quantity), 0)) as cancel,
    SUM(IF(order_status LIKE "CANCEL" AND sale_order_code is not null, (sales_price * demand_quantity ),0 )) as cancel_after_ffm,
    SUM(IF(order_status NOT LIKE "CANCEL",(outbound_quantity - returned_quantity) * sales_price, 0)) as fulfilled_amount,
    SUM(IF(order_status NOT LIKE "CANCEL" , returned_quantity, 0) * sales_price) as returned_amount,
    SUM(IF(order_status NOT LIKE "CANCEL" AND order_status not in ("DELIVERING","DELIVERED","COMPLETED"),  (demand_quantity - outbound_quantity ) ,0 ) * sales_price) as gmv_backlog,
    SUM((listed_price - sales_price) * demand_quantity) as commercial_amount,
    SUM(IF(commercial_type = "DEAL", (listed_price - sales_price) * demand_quantity, 0)) as commercial_deal_amount,
    SUM(IF(commercial_type = "CAMPAIGN", (listed_price - sales_price) * demand_quantity, 0)) as commercial_campaign_amount,
    SUM(IF(commercial_type = "COMBO",(listed_price - sales_price) * demand_quantity, 0)) as commercial_combo_amount,
    SUM(IF(order_status NOT LIKE "CANCEL" AND order_status in ("DELIVERING","DELIVERED","COMPLETED"),(demand_quantity - outbound_quantity ) ,0 ) * sales_price) as gmv_unff,
    SUM(listed_price * demand_quantity) as gmv_with_listed_price,
    SUM(IF(order_status NOT LIKE "CANCEL" , returned_quantity, 0) * sales_price) as gmv_return,
    SUM(demand_quantity) as item_sold
  FROM ${ref(`fact_strategic_sale_order_item_single`)}
  GROUP BY 1, 2, 3, 4),


-- Delivery metrics
delivery_metrics AS (
  SELECT 
    DATE(do.created_time) as delivery_date,
    do.location,
    do.channel,
    CAST(NULL AS STRING) AS supplier_class,
    -- shipping_ward_code,
    COUNT(DISTINCT do.delivery_order_code) as do_count
  FROM ${ref(`fact_strategic_delivery_order`)} do 
  GROUP BY 1, 2, 3, 4)


SELECT 
  CURRENT_DATETIME("+7") AS refresh_time,
  c.eom as date,
  m.location,
  m.channel,
  measure,
  supplier_class,
--   shipping_ward_code,
  value
  
FROM order_metrics m
CROSS JOIN UNNEST([
  STRUCT("GMV_BEFORE_CANCEL" as measure, gmv_before_cancel as value),
  STRUCT("GMV_AFTER_CANCEL" as measure, (gmv_before_cancel - cancel_before_ffm) as value),
  STRUCT("CANCEL" as measure, cancel as value ),
  STRUCT("CANCEL_AFTER_FFM" as measure, cancel_after_ffm as value),
  STRUCT("CANCEL_BEFORE_FFM" as measure, cancel_before_ffm as value),
  STRUCT("GMV_FULFILLED" as measure, fulfilled_amount as value),
  STRUCT("NMV" as measure, (cancel_after_ffm + fulfilled_amount +  gmv_backlog + returned_amount) as value),
  STRUCT("COMMERCIAL_AMOUNT" as measure, commercial_amount as value),
  STRUCT("COMMERCIAL_DEAL_AMOUNT" as measure, commercial_deal_amount as value),
  STRUCT("COMMERCIAL_CAMPAIGN_AMOUNT" as measure, commercial_campaign_amount as value),
  STRUCT("COMMERCIAL_COMBO_AMOUNT" as measure, commercial_combo_amount as value),
  STRUCT("GMV_UNFF" as measure, gmv_unff as value),
  STRUCT("GMV_WITH_LISTED_PRICE" as measure, gmv_with_listed_price as value),
  STRUCT("ITEM_SOLD" as measure, item_sold as value),
  STRUCT("GMV_BACKLOG" as measure, gmv_backlog as value),
  STRUCT("GMV_RETURN" as measure, gmv_return as value)
]) metrics
JOIN base_calendar c 
  ON DATE(m.order_date) = c.date

UNION ALL

SELECT 
  CURRENT_DATETIME("+7") AS refresh_time,
  c.eom as date,
  d.location,
  d.channel,
  'DO' as measure,
  d.supplier_class,
--   shipping_ward_code,
  d.do_count as value
FROM delivery_metrics d
INNER JOIN base_calendar c ON DATE(d.delivery_date) = c.date

UNION ALL 

SELECT a.* 
FROM ${ref(`agg_strategic_customer`)} as a
INNER JOIN base_calendar c ON DATE(c.eom) = a.date


UNION ALL -- Inventory cut off by last day of month

SELECT *
FROM ${ref(`agg_inventory_cutoff`)}

UNION ALL 
SELECT
CURRENT_DATETIME("+7") AS refresh_time,
eom as date,
location,
channel,
'SO' as measure,
supplier_class,
SO_count as value
FROM ${ref(`fact_strategic_sale_order`)}
