config {
    type: "table",
    description: `PIC: minh.luu, schedule: 0h00 daily
    Source
        ${source.ref}.`,
    columns: {
        order_id: "NonNull",
        product_id: "Nullable",
        created_time: "NonNull | Timezone in +7",
        outbound_time: "Nullable | from bill | Timezone in +7 ",
        outbound_quantity: "Nullable | Retrieve from accounting system | the quantity of products have be shipped from warehouse",
        price: "Nullable",
        outbound_amount: "Nullable | Retrieve from  accounting system | outbound_quatity * price for each product"
    },
    // assertions: {
    //     nonNull: ('order_id')
    // },
    tags: ('0h00')
    // bigquery: {
    //     partitionBy: "DATE(order_created_time)"
    // }
}

SELECT 
    CAST ( REGEXP_EXTRACT(do.delivery_order_code, r'\d+') AS INT) AS order_id,
    ${utils.ToTimezone(`do.outbound_time`)} AS outbound_time ,
    -- doi.product_id,

    do.delivery_order_code ,
    doi.outbound_quantity AS outbound_items,
    doi.unit_price AS outbound_price,
    doi.unit_price * doi.outbound_quantity AS outbound_value,
    warehouse_code
    
FROM ${source.platinum}.warehouse_prd_core_delivery_order AS do
LEFT JOIN ${source.platinum}.warehouse_prd_core_delivery_order_item AS doi  
    ON do.delivery_order_code = doi.delivery_order_code



