config {
    type: "table",
    description: `PIC: minh.luu, schedule: 0h00 daily
    Fact Sale Order Item after Combo Separation
    Remember exclude all order item with supplier_class=TECH
    And Tender must exclude wait_to_confirmation
    I keep these record, because other Fact Strategic have not supplier_class to filter
    Source
        ${source.ref}.marketplace_prd_order_v2_order
        ${source.ref}.tender_prd_core_tender_orders
        ${source.ref}.marketplace_prd_order_v2_order_item
        ${source.ref}.tender_prd_core_tender_order_items
        ${source.ref}.dim_supplier
        ${source.ref}.dim_sku`,
    columns: {
        oiid: "NonNull| to join mkp order_item table using mg_id = oiid. Else if join tender order_item table using mg_id = SUBSTR(oiid, 7) ",
        order_id: "NonNull",
        product_id: "NonNull | The product_id after separate combo item",
        sku_code:"NonNull | ",
        supplier_code:"NonNull | seller code",
        product_id_original:"NonNull | The product_id before separate combo item",
        sku_code_original:"NonNull | ",
        supplier_code_original	: "NonNull |",
        order_status: "Nullable | Null means unknown",
        supplier_class: `Nullable | COALESCE(  supplier_class from the seller_code field first, the supplier_class from the sku field's seller_code - by join dim_sku and use sku.seller_code to join dim supplier, the order_item seller_class field ) as supplier_class `,
        created_time: "NonNull | Timezone in +7",
        demand_quantity: "NonNull |",
        returned_quantity : "Nullable | The item quantity was returned by the customer. However, there are some orders that still have returns, but the system marked them as canceled, making it difficult to calculate revenue",
        outbound_time: "Nullable | The datetime that item has been delivered out of warehouse ",
        confirmation_time: "Nullable | confirmation datetime, timezone in +7",
        outbound_quantity: "Nullable | the quantity of products have be shipped from warehouse",
        price: "Nullable"
    },
    tags: ('0h00'),
    bigquery: {
        partitionBy: "DATE(created_time)"
    }
}

js {
    // const start_date = `"2023-12-31"`
    const start_date = `"2022-12-31"`
    const end_date = `"2030-09-25"`
}

WITH 
mkp_o AS ( 
    SELECT 
        o.order_id,
        o.warehouse_code as fc_code,
        o.sale_order_code,
        o.customer_id, 
        o.status,
        outbound_date,
        created_time,
        confirmation_date,
        delivered_time,
        "MKP" as system
    FROM
        ${source.platinum}.marketplace_prd_order_v2_order o
    WHERE o.created_date BETWEEN ${start_date} AND ${end_date}
    AND o.created_time is not null

)
, mkp_oi AS (
    SELECT 
        'mkp' || mg_id as oiid, 
        order_id,
        product_id,
        -- item_code, -- currently, This is unnecessary
        -- oi.type, -- currently, This is unnecessary
        sku as sku_code,
        seller_code,
        seller_class, 
        type,
        outbound_quantity,
        quantity AS demand_quantity,
        returned_quantity,
        extra_props,
        price,
        COALESCE(SAFE_CAST( JSON_EXTRACT_SCALAR(oi.extra_props, "$.charge_campaign_fee_value") AS int64),0) as charge_campaign_fee_value,
        COALESCE(charge_deal_fee_value,0) AS charge_deal_fee_value
    FROM 
        ${source.platinum}.marketplace_prd_order_v2_order_item oi
    WHERE created_date BETWEEN ${start_date} AND ${end_date}
    AND created_time is not null
)
, tender_o AS (
    SELECT 
        o.order_id,
        w.warehouse_code as fc_code,
        o.sale_order_code, 
        o.receiver_id * (10000) AS customer_id,
        o.status,
        o.outbound_date,
        o.created_time,
        o.confirmation_date,
        o.delivered_time,
        "TENDER" AS system
    FROM
        ${source.platinum}.tender_prd_core_tender_orders o
    LEFT JOIN ${source.platinum}.warehouse_prd_core_sale_order w
        ON o.sale_order_code = w.sale_order_code
    WHERE o.created_date BETWEEN ${start_date} AND ${end_date}
    AND o.created_time is not null
)
, tender_oi AS (
    SELECT 
        'tender' || mg_id as oiid, 
        oi.order_id,
        oi.product_id,
        -- oi.item_code,  -- currently, This is unnecessary
        -- oi.type, -- currently, This is unnecessary
        dsku.sku_code,
        oi.seller_code,
        oi.seller_class, 
        oi.type,
        oi.quantity AS outbound_quantity, -- Assumption: Tender will return all outbound 
        oi.quantity AS demand_quantity,
        0 as returned_quantity,
        oi.extra_props,
        oi.price,
        COALESCE(SAFE_CAST( JSON_EXTRACT_SCALAR(oi.extra_props, "$.charge_campaign_fee_value") AS int64),0) as charge_campaign_fee_value,
        0 AS charge_deal_fee_value
    FROM 
        ${source.platinum}.tender_prd_core_tender_order_items oi
    LEFT JOIN ${source.ref}.dim_sku dsku
        ON oi.product_id = dsku.product_id AND oi.seller_code = dsku.seller_code
    WHERE oi.created_date BETWEEN ${start_date} AND ${end_date}
    AND oi.created_time is not null

)
, o AS (
    SELECT * FROM mkp_o 
    UNION ALL 
    SELECT * FROM tender_o 
)
, oi_1 AS (
    SELECT * FROM mkp_oi 
    UNION ALL
    SELECT * FROM tender_oi
)
, oi AS (
    SELECT 
        *,
        ""
        || IF( charge_deal_fee_value < 0, "\ncharge_deal_fee_value is NEGATIVE","" )
        || IF( charge_campaign_fee_value < 0, "\ncharge_campaign_fee_value is NEGATIVE","" )
        AS note 
        ,
        ""
        || IF( charge_deal_fee_value < 0, "\ncharge_deal_fee_value = " || CAST(charge_deal_fee_value AS STRING),"" )
        || IF( charge_campaign_fee_value < 0, "\ncharge_campaign_fee_value = " || CAST(charge_campaign_fee_value AS STRING),"" )
        AS more_note
    FROM oi_1
)
, oi_combo_1 AS ( -- extract the original price or retail price of single item in combo
    SELECT 
        oi.oiid,
        oi.order_id,
        oi.product_id,
        oi.sku_code,
        -- oi.item_code,  -- currently, This is unnecessary
        oi.type, 
        JSON_EXTRACT_SCALAR( ois.sku ) as sku_single_code,
        SAFE_CAST( JSON_VALUE( ois.product_id ) as INT64 ) as product_single_id,
        -- JSON_VALUE( ois.item_code) as item_single_code, -- currently, This is unnecessary
        -- JSON_EXTRACT_SCALAR( ois.type ) as item_single_type,  -- currently, This is unnecessary

        JSON_VALUE(ois.seller_code) as product_single_seller_code,
        JSON_VALUE(ois.seller_class) as product_single_seller_class,
        SAFE_CAST( JSON_VALUE( ois.seller_price ) as INT64 ) as product_single_seller_price, 
        SAFE_CAST( JSON_VALUE( ois.quantity ) as INT64 )  as product_single_demand_quantity, -- is this is percentage < 1
        SAFE_CAST( JSON_VALUE( ois.price ) as INT64 ) as product_single_price,
        oi.seller_code,
        oi.seller_class,
        
        oi.outbound_quantity,
        oi.demand_quantity,
        oi.returned_quantity,
        oi.price,
        oi.charge_campaign_fee_value,
        oi.charge_deal_fee_value,
        note,
        more_note
    FROM oi
    , unnest( json_query_array(oi.extra_props, "$.sub_items") ) as ois -- order item single
)
, oi_combo_2 AS ( -- rename column, and calculate the price,  original_campaign_fee ,  original_deal_fee and original_combo_fee of single item to match combo
    SELECT 
        oiid,
        order_id,
        product_id as product_id_original,
        sku_code as sku_code_original,
        seller_code as seller_code_original,
        seller_class as seller_class_original,
        product_single_id as product_id,
        sku_single_code as sku_code, 
        product_single_seller_code as seller_code,
        product_single_seller_class as seller_class,
        IF(type like "NORMAL", "COMBO", type) AS type ,
    
        -- demand_quantity as demand_quantity_original, -- tại sao số bị thay đổi so với quantity ở platinum
        -- price as price_original, -- như dòng trên 
        
        -- product_single_seller_price as seller_price, -- currently, This is unnecessary
        -- demand_quantity / COUNT(1) OVER(PARTITION BY order_id, sku_code) as combo_quantity, -- currently, This is unnecessary

        demand_quantity * product_single_demand_quantity as demand_quantity, 
        outbound_quantity * product_single_demand_quantity as outbound_quantity,
        returned_quantity * product_single_demand_quantity as returned_quantity,
        product_single_price * LEAST(
            (price / sum(product_single_demand_quantity * product_single_price) over (partition by order_id, sku_code))
            , 1
        ) as price,

        product_single_price - product_single_price  * LEAST(
             (price / sum(product_single_demand_quantity * product_single_price) over (partition by order_id, sku_code))
        ) as charge_combo_fee_value, 

        0 as charge_deal_fee_value,
        0 as charge_campaign_fee_value,
        -- charge_campaign_fee_value * product_single_price / sum(product_single_demand_quantity * product_single_price) over (partition by order_id, sku_code) as charge_campaign_fee_value,
        -- charge_deal_fee_value * product_single_price / sum(product_single_demand_quantity * product_single_price) over (partition by order_id, sku_code) as charge_deal_fee_value,
        
        note 
        || IF(type like "NORMAL", "\nType: CRM <type> = <NORMAL> but Has nested combo item then <COMBO>", "")
        || IF(charge_deal_fee_value <> 0 , "\nCharge_fee: Item is <COMBO> still have <deal>, charge_deal_fee_value" , "")
        || IF(charge_campaign_fee_value <> 0 , "\nCharge_fee: Item is <COMBO> still have <deal>, charge_campaign_fee_value", "")
        AS note ,
        more_note
        || IF(charge_deal_fee_value <> 0 ,"combo_charge_deal_fee_value="|| CAST(charge_deal_fee_value AS STRING), "")
        || IF(charge_campaign_fee_value <> 0 ,"combo_charge_campaign_fee_value="|| CAST(charge_campaign_fee_value AS STRING), "")
        AS more_note
    FROM oi_combo_1
)
, oi_combo AS (
    SELECT *
    FROM oi_combo_2
)

, oi_not_combo AS (
    SELECT 
        oiid,
        order_id,
        product_id as product_id_original,
        sku_code as sku_code_original,
        seller_code as seller_code_original,
        seller_class as seller_class_original,
        product_id,
        sku_code,
        seller_code,
        seller_class,
        type,
        -- demand_quantity as demand_quantity_original,
        -- price as price_original,
        demand_quantity,
        outbound_quantity,
        returned_quantity,
        price,
        0 as charge_combo_fee_value,
        charge_deal_fee_value,
        charge_campaign_fee_value,
        note,
        more_note
    FROM oi 
    WHERE oiid not in (SELECT oiid FROM oi_combo)
)
, oi_final AS (
    SELECT * FROM oi_combo
    UNION ALL 
    SELECT * FROM oi_not_combo
)   

, fact_strategic_1 AS (
    SELECT
        oi.oiid,
        oi.order_id,
        o.sale_order_code,
        o.customer_id,
        o.fc_code,
        oi.product_id_original,
        oi.sku_code_original,
        oi.seller_code_original as supplier_code_original,
        oi.product_id,
        oi.sku_code,
        oi.seller_code as supplier_code,
        dstatus.crm_status as order_status,
        oi.outbound_quantity,
        oi.demand_quantity, 
        oi.returned_quantity,
        oi.price as sales_price,
        oi.type AS commercial_type,
        note,
        more_note,
        demand_quantity as demand_quantity_original,
        price as price_original,
        COALESCE(
            ds1.supplier_class,
            ds3.supplier_class,
            ds2.supplier_class,
            ds4.supplier_class,
            oi.seller_class
        ) as supplier_class,
        ${utils.ToTimezone(`o.created_time`)} as created_time,
        ${utils.ToTimezone(`o.outbound_date`)} as outbound_time,
        ${utils.ToTimezone(`o.confirmation_date`)} as confirmation_time,
        ${utils.ToTimezone(`o.delivered_time`)} as delivered_time,

        IF( oi.charge_campaign_fee_value <0, 0 , oi.charge_campaign_fee_value) charge_campaign_fee_value ,
        IF( oi.charge_combo_fee_value <0, 0 , oi.charge_combo_fee_value) charge_combo_fee_value ,
        IF( oi.charge_deal_fee_value <0, 0 , oi.charge_deal_fee_value) charge_deal_fee_value ,
        
    FROM o
    LEFT JOIN oi_final oi ON o.order_id = oi.order_id
    LEFT JOIN ${ref(`dim_supplier`)} ds1 ON oi.seller_code = ds1.supplier_code
    LEFT JOIN ${ref(`dim_supplier`)} ds2 ON oi.seller_code_original = ds2.supplier_code 
    LEFT JOIN ${ref(`dim_sku`)} dsku3 ON dsku3.sku_code = oi.sku_code
    LEFT JOIN ${ref(`dim_supplier`)} ds3 ON ds3.supplier_code = dsku3.seller_code
    LEFT JOIN ${ref(`dim_sku`)} dsku4 ON dsku4.sku_code = oi.sku_code_original
    LEFT JOIN ${ref(`dim_supplier`)} ds4 ON ds4.supplier_code = dsku4.seller_code
    LEFT JOIN ${ref(`dim_order_status`)} dstatus ON dstatus.order_id = o.order_id

    -- WHERE o.order_channel <> "CONSIGNMENT-RECOGNITION"
    -- WHERE ${utils.ToTimezone(`o.created_time`)} >= "2023-01-01"
    
)
, fact_strategic_2 AS (
    SELECT 
        * EXCEPT( returned_quantity, note ) ,
        fs.sales_price + fs.charge_campaign_fee_value + fs.charge_deal_fee_value + fs.charge_combo_fee_value AS listed_price,

        IF( fs.order_status like "CANCEL" AND fs.sale_order_code is null, demand_quantity, 0) as cancel_before_ffm_quantity,
        IF( fs.order_status like "CANCEL" AND fs.sale_order_code is not null, demand_quantity, 0) as cancel_after_ffm_quantity,

        IF( fs.order_status not like "CANCEL" ,(fs.outbound_quantity - fs.returned_quantity),0) as fulfilled_quantity,
        IF( fs.order_status not like "CANCEL" AND fs.order_status in ("DELIVERING","DELIVERED","COMPLETED"),(fs.demand_quantity - fs.outbound_quantity ) ,0 ) as unfulfill_quantity,
        IF( fs.order_status not like "CANCEL" AND fs.order_status not in ("DELIVERING","DELIVERED","COMPLETED"),  (fs.demand_quantity - fs.outbound_quantity ) ,0 ) as backlog_quantity,
        IF( fs.order_status not like "CANCEL" , fs.returned_quantity, 0) AS returned_quantity,

        note 
        || CASE 
            WHEN IF(fs.order_status not like "CANCEL" ,(fs.outbound_quantity - fs.returned_quantity),0) = demand_quantity THEN "\nOrder_Item_Note: Fully Fulfilled"
            WHEN IF(fs.order_status not like "CANCEL" , fs.returned_quantity, 0) = demand_quantity THEN "\nOrder_Item_Note: Fully Returned"
            WHEN fs.order_status like "CANCEL" AND fs.sale_order_code is null THEN "\nOrder_Item_Note: Cancel before FFM"
            WHEN fs.order_status like "CANCEL" AND fs.sale_order_code is not null THEN "\nOrder_Item_Note: Cancel after FFM"
            WHEN IF(fs.order_status not like "CANCEL" AND fs.order_status not in ("DELIVERING","DELIVERED","COMPLETED"),  (fs.demand_quantity - fs.outbound_quantity ) ,0 ) = demand_quantity THEN "\nOrder_Item_Note: Backlog"
            ELSE "\nOrder_Item_Note: Partial Fulfilled"
        END 
        AS note
    FROM fact_strategic_1 as fs 
)



SELECT 
  ois.oiid,
  ois.order_id,
  ois.customer_id,
  ois.sale_order_code,
  ois.order_status,
  ois.commercial_type,
  ois.created_time,
  ois.confirmation_time,
  ois.sku_code_original,
  ois.sku_code,
  ois.supplier_class, -- For filter test
  ois.note,
  ois.more_note,
  ois.listed_price,
  ois.sales_price,
  ois.supplier_code,
  
  ois.demand_quantity,
  ois.backlog_quantity, 
  ois.outbound_quantity,
  ois.fulfilled_quantity, 
  ois.returned_quantity,
  ois.cancel_before_ffm_quantity, 
  ois.cancel_after_ffm_quantity, 



FROM fact_strategic_2 ois

-- -- post_operations {
-- --     ALTER TABLE ${self()} 
-- --     ADD FOREIGN KEY (order_id) references ${ref(`dim_order`)}(order_id) NOT ENFORCED,
-- --     ADD FOREIGN KEY (product_id) references ${ref(`dim_product`)}(product_id) NOT ENFORCED;
-- -- }
