config {
    type: "table",
    description: `PIC: huong.dang, schedule: 0h00 daily
    Fact Sale Order Item after Combo Separation
    Remember exclude all order item with supplier_class=TECH
    And Tender must exclude wait_to_confirmation
    I keep these record, because other Fact Strategic have not supplier_class to filter
    Source
        ${source.ref}.marketplace_prd_order_v2_order
        ${source.ref}.tender_prd_core_tender_orders`,
    columns: {
        order_id: "NonNull",
        order_status: "Nullable | Null means unknown",
        created_time: "NonNull | Timezone in +7",
        outbound_time: "Nullable | The datetime that item has been delivered out of warehouse ",
        confirmation_time: "Nullable | confirmation datetime, timezone in +7"
    },
    tags: ('0h00'),
    bigquery: {
        partitionBy: "DATE(created_time)"
    }
}

js {
    const start_date = `"2023-01-01"`
}

WITH 
mkp_o AS ( 
    SELECT 
        o.order_id,
        COUNT(DISTINCT o.order_id) as SO_count
        o.fc_code,
        o.so_code as sale_order_code,
        o.customer_id, 
        o.order_status as status,
        o.channel,
        b.eom,
        CAST(NULL AS STRING) AS supplier_class,
        CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
        ELSE "GMV_VN_REGION_UNKNOWN" 
        END AS location,
    FROM ${source.ref}.fact_order o
    LEFT JOIN ${source.ref}.dim_calendar as b on b.date = date(o.created_at)
    LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON o.order_id = dosr.order_id
    WHERE DATE(o.created_at) >= ${start_date}
    AND o.order_status <> "CANCEL"

)

, tender_o AS (
    SELECT 
        o.order_id,
        COUNT(DISTINCT o.order_id) as SO_count
        w.warehouse_code as fc_code,
        o.sale_order_code, 
        o.receiver_id * (10000) AS customer_id,
        o.status,
        -- o.confirmation_date,
        "TENDER" AS channel,
        a.eom,
        CAST(NULL AS STRING) AS supplier_class,
        CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
        ELSE "GMV_VN_REGION_UNKNOWN" 
        END AS location,
    FROM ${source.platinum}.tender_prd_core_tender_orders o
    LEFT JOIN ${source.platinum}.warehouse_prd_core_sale_order w ON o.sale_order_code = w.sale_order_code
    LEFT JOIN ${source.ref}.dim_calendar as a on a.date = date(o.confirmation_date)
    LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON o.order_id = dosr.order_id
    WHERE o.created_date >= ${start_date} 
    AND o.created_time is not null
    AND o.status <> "CANCEL"
)

    SELECT * FROM mkp_o 
    UNION ALL 
    SELECT * FROM tender_o 



