config {
    type: "table",
    description: `PIC: minh.luu, schedule: 0h00 daily
    Source
        ${source.ref}.marketplace_prd_order_v2_order
        ${source.ref}.tender_prd_core_tender_orders
        ${source.ref}.marketplace_prd_order_v2_order_item
        ${source.ref}.tender_prd_core_tender_order_items
        ${source.ref}.dim_supplier
        ${source.ref}.dim_sku`,
    columns: {
        order_id: "NonNull",
        product_id: "Nullable",
        order_status: "Nullable | Null means unknown",
        supplier_class: `Nullable | COALESCE(  supplier_class from the seller_code field first, the supplier_class from the sku field's seller_code - by join dim_sku and use sku.seller_code to join dim supplier, the order_item seller_class field ) as supplier_class `,
        order_created_time: "NonNull | Timezone in +7",
        demand_quantity: "NonNull |",
        returned_quantity : "Nullable | The item quantity was returned by the customer. However, there are some orders that still have returns, but the system marked them as canceled, making it difficult to calculate revenue",
        outbound_time: "Nullable | The datetime that item has been delivered out of warehouse ",
        outbound_quantity: "Nullable | the quantity of products have be shipped from warehouse",
        price: "Nullable"
    },
    tags: ('0h00'),
    bigquery: {
        partitionBy: "DATE(order_created_time)"
    }
}

js {
    const event_checkpoint_date = `"2021-01-01"`
}


WITH 
-- bill as (
--     SELECT 
--         order_id,
--         min( ${utils.ToTimezone(`created_time`)} ) as bill_created_time,
--     FROM
--         ${source.platinum}.accounting_prd_core_bill 
--     GROUP BY 1
-- )

-- , 
mkp_o AS ( 
    SELECT 
        o.order_id, 
        o.status,
        ${utils.ToTimezone(`o.outbound_date`)} as outbound_time,
        ${utils.ToTimezone(`o.created_time`)} as order_created_time,
        -- bill.bill_created_time,
        do.order_channel
        
    FROM
        ${source.platinum}.marketplace_prd_order_v2_order o
    LEFT JOIN ${ref(`dim_order`)} do ON do.order_id = o.order_id
    -- LEFT JOIN bill ON o.order_id = bill.order_id

)
, mkp_oi AS (
    SELECT 
    -- mg_id,
        order_id,
        product_id,
        seller_code,
        sku,
        seller_class, 
        outbound_quantity,
        quantity AS demand_quantity,
        returned_quantity,
        price
    FROM 
        ${source.platinum}.marketplace_prd_order_v2_order_item
    
    WHERE created_date > ${event_checkpoint_date}

)
, tender_o AS (
    SELECT 
        o.order_id,
        o.status,
        ${utils.ToTimezone(`o.outbound_date`)} as outbound_time,
        ${utils.ToTimezone(`o.created_time`)} as order_created_time,
        -- bill.bill_created_time,
        "TENDER" AS order_channel
        
    FROM
        ${source.platinum}.tender_prd_core_tender_orders o
)
, tender_oi AS (
    SELECT 
    -- mg_id,
        order_id,
        product_id,
        seller_code,
        'notneednow' AS sku,
        seller_class, 
        quantity AS outbound_quantity, -- Assumption: Tender will return all outbound 
        quantity AS demand_quantity,
        0 as returned_quantity,
        price
    FROM 
        ${source.platinum}.tender_prd_core_tender_order_items oi
    WHERE
        created_date > ${event_checkpoint_date}

)
, o AS (
    SELECT * FROM mkp_o 
    UNION ALL 
    SELECT * FROM tender_o
)
, oi AS (
    SELECT * FROM mkp_oi 
    UNION ALL
    SELECT * FROM tender_oi
)
SELECT
    -- oi.mg_id,
    oi.order_id,
    oi.product_id,
    -- oi.seller_code as supplier_code,
    o.status as order_status,
    COALESCE(
        ds1.supplier_class,
        ds2.supplier_class,
        oi.seller_class
    ) as supplier_class,
    -- oi.sku,
    o.outbound_time,
    oi.outbound_quantity,
    oi.demand_quantity, 
    oi.returned_quantity,
    oi.price,
    -- CASE 
    --     WHEN o.status <> "CANCEL" and o.status <> "CANCELLED" and o.order_channel <> "CONSIGNMENT-RECOGNITION" THEN oi.demand_quantity * oi.price
    --     ELSE NULL
    -- END AS gmv ,
    -- CASE 
    --     WHEN o.order_channel <> "CONSIGNMENT-RECOGNITION" THEN oi.demand_quantity * oi.price
    --     ELSE NULL 
    -- END AS gmv_before_cancel,
    o.order_created_time


FROM oi
LEFT JOIN o ON o.order_id = oi.order_id
LEFT JOIN ${ref(`dim_supplier`)} ds1 ON oi.seller_code = ds1.supplier_code
LEFT JOIN ${ref(`dim_sku`)} dsku ON dsku.sku_code = oi.sku 
LEFT JOIN ${ref(`dim_supplier`)} ds2 ON ds2.supplier_code = dsku.seller_code

WHERE o.order_channel <> "CONSIGNMENT-RECOGNITION"



post_operations {
    ALTER TABLE ${self()} 
    ADD FOREIGN KEY (order_id) references ${ref(`dim_order`)}(order_id) NOT ENFORCED,
    ADD FOREIGN KEY (product_id) references ${ref(`dim_product`)}(product_id) NOT ENFORCED;

}