config {
    type: "table",
    description: `PIC: minh.luu, model_type: view, schedule: daily
    Source
        ${source.ref}.agg_strategic_monthly_GMV`,
    columns: {
        date: "NonNull |",
        metric_code : "NonNull | ",
        value : "NonNull | "
    }
}

SELECT
    date, 
    metric_code,
    value
FROM
    ${ref(`agg_strategic_monthly_GMV`)}

UNION ALL

SELECT
    date, 
    metric_code,
    value
FROM
    ${ref(`agg_strategic_monthly_GMV_by_SalesRegion`)}

UNION ALL

SELECT
    date, 
    metric_code,
    value
FROM
    ${ref(`agg_strategic_orders_by_Sales_Region`)}

UNION ALL

SELECT
    date, 
    metric_code,
    value
FROM
    ${ref(`agg_strategic_delivers_by_Sales_Region`)}


post_operations {
    ALTER TABLE ${self()} 
        ADD FOREIGN KEY (date) references ${ref(`dim_calendar`)}(date) NOT ENFORCED,
        ADD FOREIGN KEY (metric_code) references ${ref(`dim_strategic_metric`)}(metric_code) NOT ENFORCED;
}