config {
    type: "table",
    description: `PIC: minh.luu, schedule: 0h00 daily
    Source
        ${source.ref}.fact_bill`,
    columns: {
        order_id: "NonNull",
        product_id: "Nullable",
        created_time: "NonNull | Timezone in +7",
        outbound_time: "Nullable | from bill | Timezone in +7 ",
        outbound_quantity: "Nullable | Retrieve from accounting system | the quantity of products have be shipped from warehouse",
        price: "Nullable",
        outbound_amount: "Nullable | Retrieve from  accounting system | outbound_quatity * price for each product"
    },
    assertions: {
        nonNull: ('order_id')
    },
    tags: ('0h00'),
    bigquery: {
        partitionBy: "DATE(order_created_time)"
    }
}


WITH bill as (
    SELECT 
        distinct
        order_id,
        ${utils.ToTimezone(`created_time`)} as bill_created_time,
    FROM
        ${source.platinum}.accounting_prd_core_bill 
)
, o AS ( 
    SELECT 
        o.order_id,
        o.status,
        ${utils.ToTimezone(`o.outbound_date`)} as outbound_time,
        o.created_time as order_created_time,
        -- bill.bill_created_time,
        do.order_channel
        
    FROM
        ${source.platinum}.marketplace_prd_order_v2_order o
    LEFT JOIN ${ref(`dim_order`)} do ON do.order_id = o.order_id
    -- LEFT JOIN bill ON o.order_id = bill.order_id
    -- WHERE 
    --     created_date > ${event_checkpoint_date}
)
, oi AS (
    SELECT 
    mg_id,
        order_id,
        product_id,
        seller_code,
        sku,
        seller_class, 
        outbound_quantity,
        quantity AS demand_quantity,
        price
    FROM 
        ${source.platinum}.marketplace_prd_order_v2_order_item
    
    -- WHERE
    --     -- created_date > ${event_checkpoint_date}
    --     created_date between "2024-05-01" and "2024-06-01"
)

SELECT
    oi.mg_id,
    o.order_id,
    oi.product_id,
    oi.seller_code as supplier_code,
    COALESCE(
        ds1.supplier_class,
        ds2.supplier_class,
        oi.seller_class
    ) as supplier_class,
    oi.sku,
    o.outbound_time,
    oi.outbound_quantity,
    oi.demand_quantity, 
    oi.price,
    CASE 
        WHEN o.order_channel = "CONSIGNMENT" then 0
        WHEN o.status <> "CANCEL" and o.status <> "CANCELLED" and o.order_channel <> "CONSIGNMENT-RECOGNITION" then oi.demand_quantity * oi.price
        ELSE NULL
    END AS gmv ,
    -- vat
    (oi.outbound_quantity * oi.price ) AS outbound_amount,
    
    -- o.bill_created_time,
    o.order_created_time


FROM oi
LEFT JOIN o ON o.order_id = oi.order_id
LEFT JOIN ${ref(`dim_supplier`)} ds1 ON oi.seller_code = ds1.supplier_code
LEFT JOIN ${ref(`dim_sku`)} dsku ON dsku.sku_code = oi.sku 
LEFT JOIN ${ref(`dim_supplier`)} ds2 ON ds2.supplier_code = dsku.seller_code



post_operations {
    ALTER TABLE ${self()} 
    ADD FOREIGN KEY (order_id) references ${ref(`dim_order`)}(order_id) NOT ENFORCED,
    ADD FOREIGN KEY (product_id) references ${ref(`dim_product`)}(product_id) NOT ENFORCED;

}