config {
    type: "table",
    description: `Started time: 2023-01-01 |PIC: tu.dang; model_type: table; Schedule: 7h30
    Source:
      ${source.ref}.dim_tender_product
      ${source.ref}.dim_order_status
      ${source.ref}.fact_order_item`,
    //uniqueKey: ["mg_id"],
    name: "fact_product_tender_sales_by_date",
    tags: ["7h30"],
    //dependencies: ["lakehouse-prod-394907.gold_buymed_vn.fact_order_item"],
    columns: {
        created_date: "The date when the order was placed, timezone +7",
        product_id: "NonNull | Unique identifier for each product",
        ordered_quantity: "The total quantity of items ordered",
        ordered_amount: "The total valuation, the original valuation of all product in the order, excluded cancelled orders"
    }
}
with internal_thuocsi as 
(select  --created_at,
        date(o.created_time) as created_date,
        td.product_id,
        o.order_channel,
        sum(sales_price * demand_quantity) as ordered_amount,
        SUM(demand_quantity) as ordered_quantity
from ${source.ref}.fact_order_item oi
left join ${source.ref}.dim_order_status s on oi.order_id = s.order_id
left join ${source.ref}.dim_order o on oi.order_id = o.order_id
left join ${source.ref}.dim_tender_product td on  oi.product_id = td.product_id
where s.CRM_status not like "CANCEL" 
and date(created_at)>= "2023-01-01" 
and td.product_id is not null
GROUP BY ALL),
internal_tender as 
(
  select
  o.created_date,
    oi.product_id,
    "TENDER" as order_channel,
    sum(oi.total_amount) as ordered_amount,
    sum(oi.quantity) as ordered_quantity
from ${source.platinum}.tender_prd_core_tender_order_items oi
left join ${source.platinum}.tender_prd_core_tender_orders o on oi.order_id = o.order_id
where o.status not like  "CANCELLED" 
group by all
)
select* from internal_thuocsi
union all
select * from internal_tender