config {
    type: "table",
    description: `PIC: tu.dang; model_type: table; Schedule: 7h30
    Source:
      ${source.platinum}.marketplace_prd_order_v2_order
      ${source.ref}.dim_order
      ${source.platinum}.tender_prd_core_tender_orders`,
    //uniqueKey: ["mg_id"],
    name: "fact_tender_order",
    tags: ["7h30"],
    //dependencies: ["lakehouse-prod-394907.gold_buymed_vn.fact_order_item"],
    columns: {
        created_at: "The date and time when the order was placed, timezone +7",
        confirmed_time: "The date and time when the record was confirmed, timezone +7",
        customer_id: "Foregin key for dim_customer, a unique identifier for customer who placed the order",
        order_id: "Primary key, a unique identifier for the order",
        ordered_quantity: "The total quantity of items ordered",
        ordered_amount: "The total valuation, the original valuation of all product in the order"
    }
}

WITH
  internal_thuocsi AS (
  SELECT
    f.order_id,
    order_status,
    customer_id AS recevier_id,
    d.created_time,
    DATE(d.created_time ) AS created_date,
    so_code AS sale_order_code,
    -- delivered_time as delivered_time,
    f.province_code,
    customer_name AS receiver_name,
    shipping_ward_code,
    "INTERNAL-THUOCSI" AS SOURCE
  FROM
    ${source.ref}.fact_order f
  LEFT JOIN
    ${source.ref}.dim_order d
  ON
    f.order_id = d.order_id
  WHERE
    d.order_channel LIKE "%TENDER%"),

  internal_tender AS (
  SELECT
    --     order_code,
    order_id,
    status,
    receiver_id,
    DATETIME(TIMESTAMP(confirmation_date), 'Asia/Ho_Chi_Minh') AS created_time, -- TENDER USESING CONFIRMATION_DATE
    created_date,
    sale_order_code,
    -- datetime(delivered_time) as delivered_time,
    province_code,
    receiver_name,
    CASE
      WHEN SAFE_CAST(ward_code AS integer) > 0 THEN ward_code
      ELSE district_code
  END AS shipping_ward_code,
    SOURCE
  FROM ${source.platinum}.tender_prd_core_tender_orders 
  WHERE status NOT LIKE "WAIT_TO_CONFIRM")
  
SELECT
  *
FROM
  internal_tender
UNION ALL
SELECT
  *
FROM
  internal_thuocsi
