config {
    type: "table",
    description: "Action in product_management. Use for alert policy change field max_quantity_per_order",
    tags: ["custom_1h_past5", "PRODUCT_MANAGEMENT"],
	columns: {
	}
}

-- step 1: get necessary columns to make logic
WITH target_date AS (
  SELECT DATE_TRUNC(DATE_SUB(CURRENT_DATE("+7"), INTERVAL 100 DAY), MONTH) AS start_date
),

get_column as (
    select *
        , SAFE_CAST(ARRAY_REVERSE( REGEXP_EXTRACT_ALL( TRIM(volumes), r'(\d+)'))[SAFE_OFFSET(0)] AS FLOAT64) AS  volumes_convert
    from (
        select a.sub_sku_code
            , a.seller_code
            , b.product_id
            , b.product_name
            , b.unit
            , b.volumes
            , b.weight
            , a.max_quantity_per_order as current_limit
            , a.sku_key_sales_region_code
            , CASE
                WHEN LOWER(b.product_name) LIKE '%cồn%' THEN 'cồn'
                WHEN LOWER(b.product_name) LIKE '%oxy già%' THEN 'oxy già'
                WHEN LOWER(b.product_name) LIKE '%povidin%' THEN 'povidin'
                WHEN LOWER(b.product_name) LIKE '%nhỏ mắt%' THEN 'nhỏ mắt các loại'
                WHEN LOWER(b.product_name) LIKE '%dung dịch vệ sinh%' THEN 'dung dịch vệ sinh'
                WHEN LOWER(b.product_name) LIKE '%sữa rửa mặt%' THEN 'sữa rửa mặt'
                WHEN LOWER(b.product_name) LIKE '%nước súc miệng%' THEN 'nước súc miệng'
                WHEN LOWER(b.product_name) LIKE '%nước muối%' THEN 'nước muối'
                WHEN LOWER(b.product_name) LIKE '%dịch truyền%' THEN 'dịch truyền'
                WHEN LOWER(b.product_name) LIKE '%khẩu trang%' THEN 'khẩu trang'
                WHEN LOWER(b.product_name) LIKE '%dầu gội%' THEN 'dầu gội'
                WHEN LOWER(b.product_name) LIKE '%găng tay%' THEN 'găng tay'
                WHEN c.category_code = '7E72AXHR2A' THEN 'vật tư và thiết bị y tế'
                ELSE 'sản phẩm khác'
            END AS category_for_set_limit
        from ${ref('dim_sku_sales_region_current')} a
        left join ${ref('dim_product')} b on a.product_id = b.product_id
        left join ${ref('dim_product_category')}  c on b.product_id = c.product_id
    )
),
-- step 2: create limit_per_SO and limit_per_SO_quantity column according to logic set limit

create_set_limit_logic as (
    select *,
        CASE
            WHEN REGEXP_CONTAINS(category_for_set_limit, 'cồn|dịch truyền|nước muối|dầu gội|sữa rửa mặt|nước súc miệng')
                AND volumes_convert >= 250
                THEN CASE LOWER(unit) 
                        WHEN "thùng" THEN 2
                        WHEN "chai"  THEN 20
                     END
            WHEN REGEXP_CONTAINS(category_for_set_limit, 'khẩu trang|găng tay') 
                AND LOWER(unit) = 'hộp' AND volumes_convert >= 50
                THEN 10
        END AS limit_per_SO_policy
    from get_column
    WHERE REGEXP_CONTAINS(category_for_set_limit, 'cồn|dịch truyền|nước muối|dầu gội|sữa rửa mặt|nước súc miệng|khẩu trang|găng tay')
)

select *,
    IF(current_limit > limit_per_SO_policy, "UPDATE BY RULE QUANTITY", "OKE") AS action     
from create_set_limit_logic
where limit_per_SO_policy > 0




