config {
  type: "table",
  tags: ["custom_1h_past5", "PRODUCT_MANAGEMENT"]
}


with cte_ds as (
	select
		row_number() over (order by item_code, created_time desc) as id,
		sku as sku_code,
		is_active,
		item_code,
		TIMESTAMP_ADD(created_time, interval 7 HOUR) AS created_time
	from  ${ref('staging_sku_is_active_history')}
),

cte_min as (
	select
		item_code,
		min(id) as min_id
	from cte_ds
	group by 1
),

cte_changed as (
	select
		a.id,
		a.sku_code,
		a.item_code,
		b.is_active as active_0,
		a.is_active as active_1,
		b.created_time as active_t0,
		a.created_time as active_t1
	from cte_ds as a
	inner join cte_ds as b on
		a.item_code = b.item_code and
		a.id+1 = b.id
),

cte_never_change as (
	select
		1000000 as id,
		a.code as sku_code,
		a.item_code,
		a.is_active as active_0,
		a.is_active as active_1,
		timestamp_add(a.created_time, interval 7 hour) as active_t0,
		timestamp_add(cast(current_timestamp as timestamp), interval 7 hour) as active_t1
	from ${source.platinum}.marketplace_prd_product_v2_sku as a
	left join ${ref('staging_sku_is_active_history')} as b on a.item_code = b.item_code
	where
		b.item_code is null
),

union_all_parts as (
	select
		b.id * (-1) as id,
		b.sku_code,
		b.item_code,
		b.is_active as active_0,
		b.is_active as active_1,
		b.created_time as active_t0,
		timestamp_add(cast(current_timestamp as timestamp), interval 7 hour) as active_t1
	from cte_min as a
	left join cte_ds as b on a.min_id = b.id

	union all
	select *
	from cte_changed

	union all
	select *
	from cte_never_change
)


select
    a.*
	, if(
		a.active_0 = a.active_1,
		"NOT_CHANGE",
		"CHANGE"
	) as change_active
	, concat(a.sku_code,"_",b.sales_region_code) as sku_sales_region_code
    , b.sku_key_sales_region_code
from union_all_parts a
left join ${ref('dim_sku_sales_region_current')} b on a.item_code = b.sub_sku_code