config {
  type: "view",
  name: "fact_order_item_combo"
}


with cte_date as (
	select timestamp( date_trunc( date_sub( current_date('+7'), interval 12 month) , month ) ) as start_date
  -- select date_sub( timestamp( date_trunc( current_date('+7'), month ) ) , interval 7 hour ) as start_date
--   SELECT date_sub( timestamp( date_trunc( date_sub( current_date('+7'), interval 1 day) , day ) ) , interval 7 hour ) as start_date
),

cte_order_item as (
    select 
        oi.mg_id
        , oi.order_id
        , oi.customer_id
        -- , timestamp_add( oi.ingest_time, interval 7 hour ) as ingested_at
        -- , timestamp_add( oi.created_time, interval 7 hour ) as created_at
        -- , timestamp_add( current_timestamp, interval 7 hour ) as transformed_at
        , FORMAT_TIMESTAMP("%Y%m%d%H", oi.created_time ) as created_timekey
        , TIMESTAMP_ADD(oi.created_time, INTERVAL 7 HOUR) as created_at
        , oi.ingest_time as ingested_at
        , current_timestamp transformed_at
        , oi.extra_props
        , oi.product_id
        , oi.sku as sku_code
        , CONCAT(oi.product_id, "_", oi.seller_code) AS sku_key
        , oi.item_code
        , oi.seller_code
        , oi.type as item_type
        , oi.deal_code
        , oi.quantity as demand_quantity
        , oi.price as sales_price
        , oi.charge_deal_fee_value
        , oi.reserved_quantity
        , oi.outbound_quantity
        , oi.returned_quantity
        , oi.seller_price
        , oi.source
        , oi.vat
        , oi.none_vat
        , to_json_string(oi.tags) as tag_code
        , oi.sku_status
        , DATETIME(oi.cart_item_created_time, "Asia/Ho_Chi_Minh") AS incart_at
    FROM ${source.platinum}.marketplace_prd_order_v2_order_item as oi
    where
        created_date >= (select DATE(start_date) from cte_date)
        -- oi.ingest_time >= (select start_date from cte_date)
        -- and ifnull( oi.created_time, current_timestamp ) >= (select start_date from cte_date)
    -- qualify row_number() over (_window) = 1 AND FIRST_VALUE(action) over(_window) <> 'd'
    -- WINDOW _window AS (PARTITION BY oi.mg_id ORDER BY oi.synced_at DESC)
),

cte_combo_item as (
select
  oi.mg_id
  , oi.extra_props
  , oi.created_timekey
  , oi.created_at
  , oi.ingested_at
  , oi.transformed_at
  , oi.order_id 
  , oi.customer_id
  -- , oi.item_type
  , json_extract_scalar( bom.type ) as item_type
  , coalesce(
    json_extract_scalar( oi.extra_props, "$.campaign_code" )
    , oi.deal_code
  ) as promotion_code
  , coalesce(
    safe_cast( json_extract_scalar( oi.extra_props, "$.charge_campaign_fee_value" ) as INT64 )
    , oi.charge_deal_fee_value
  ) as promotion_amount
  , oi.seller_code
  -- , oi.product_id
  , safe_cast( json_extract_scalar( bom.product_id ) as INT64 ) as product_bom_id
  , oi.sku_code
  , oi.sku_key
  , oi.item_code
  , oi.sales_price as combo_price
  -- , oi.seller_price
  , SAFE_CAST( JSON_VALUE( bom.seller_price ) AS INT64 ) AS bom_seller_price
  , oi.demand_quantity AS  combo_quantity
  , json_extract_scalar( bom.sku ) as sku_bom_code
  , json_value(bom.item_code) as item_bom_code
  , safe_cast( json_extract_scalar( bom.quantity ) as INT64 )  as bom_quantity
  , safe_cast( json_extract_scalar( bom.price ) as INT64 ) as bom_price
  , oi.reserved_quantity
  , oi.outbound_quantity
  , oi.returned_quantity
  , oi.source
  , coalesce(
    safe_cast( json_extract_scalar( bom.none_vat ) as BOOL )
    , oi.none_vat
  ) as none_vat
  , coalesce(
    safe_cast( json_extract_scalar( bom.vat ) as INT64 )
    , oi.vat
  ) as vat
  , tag_code
  , sku_status
  , incart_at
  , TO_JSON_STRING(JSON_QUERY(bom, '$.tags')) AS sub_tag_code
from cte_order_item as oi
, unnest( json_query_array(oi.extra_props, "$.sub_items") ) as bom
), 

cte_combo_item_pricing as (
select
  mg_id
  , order_id
  , customer_id
  , created_timekey
  , created_at
  , ingested_at
  , transformed_at
  , item_type
  , promotion_code
  , promotion_amount
  , seller_code
  , sku_code as sku_orignal_code
  , sku_key as sku_orignal_key
  , item_code as item_original_code
  , sku_bom_code as sku_code
  , item_bom_code as item_code
  , product_bom_id as product_id
  , combo_quantity / COUNT(1) OVER(PARTITION BY order_id, sku_code) as combo_quantity -- nguyen.tran
  , combo_quantity * bom_quantity as demand_quantity
  , reserved_quantity * bom_quantity as reserved_quantity
  , outbound_quantity * bom_quantity as outbound_quantity
  , returned_quantity * bom_quantity as returned_quantity
  , bom_price * LEAST(
    (combo_price / sum(bom_quantity * bom_price) over (partition by order_id, sku_code))
    , 1
   ) as sales_price
  , bom_price AS sales_price_original
  , bom_seller_price AS seller_price
  , combo_price
  , source
  -- , bom_price as sales_price_original
  , case  
      when none_vat is true then -1
      else vat
    end as vat_code
  , tag_code
  , sku_status
  , extra_props
  , incart_at
  , sub_tag_code
from cte_combo_item
),

cte_normal_item as (
  select 
    oi.mg_id
    , oi.order_id
    , oi.customer_id
    , oi.created_timekey
    , oi.created_at
    , oi.ingested_at
    , oi.transformed_at
    , oi.item_type
    , coalesce(
      json_extract_scalar( oi.extra_props, "$.campaign_code" )
      , oi.deal_code
    ) as promotion_code
    , coalesce(
    safe_cast( json_extract_scalar( oi.extra_props, "$.charge_campaign_fee_value" ) as INT64 )
    , oi.charge_deal_fee_value
  ) as promotion_amount
    , oi.seller_code
    , oi.sku_code as sku_orignal_code
    , oi.sku_key as sku_orignal_key
    , oi.item_code as item_original_code
    , oi.sku_code
    , oi.item_code
    , oi.product_id
    , null as combo_quantity --nguyen.tran
    , oi.demand_quantity
    , oi.reserved_quantity
    , oi.outbound_quantity
    , oi.returned_quantity
    , oi.sales_price
    , oi.sales_price as sales_price_original
    , oi.seller_price
    , oi.sales_price AS combo_price
    , oi.source
    , case  
      when none_vat is true then -1
      else vat
    end as vat_code
    , tag_code
    , sku_status
    , extra_props
    , incart_at
    , tag_code AS sub_tag_code
  from cte_order_item as oi
  where
    oi.mg_id not in ( select mg_id from cte_combo_item_pricing )
)

select * from cte_combo_item_pricing
union all
select * from cte_normal_item