config {
  type: "table",
  description: 
        `
        Details of the items in the order, with combos split into normal products and its prices recalculated according to the corresponding combo;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: daily at 8h30, 10h30, 12h30, 15h30, 18h, 20h30;
        Source: 
            ${source.platinum}.marketplace_prd_order_v2_order_item,
            ${source.ref}.fact_order
        `,
  bigquery: {
    partitionBy: "date(created_at)",
    clusterBy: ["order_id", "sku_code"]
  },
  tags: ["8h30", "10h30", "12h30", "15h30" ,"18h", "20h30"],
  columns: {
    created_timekey: "Foreign-Key to Dim_DateTime ",
    created_at: "UTC, When the item was placed",
    item_type: "Normal: type + Combo: sub_type",
    promotion_code: "deal_code + campaign_code",
    sku_orignal_code: "Combo sku_code if buyers placed combo items",
    sku_code: "Single/BOM sku_code if its original is a combo one",
    product_id: "Single/BOM producdt_id if it original is a combo one",
    demand_quantity: "Quantity by BOM SKUs",
    sales_price: "UnitPrice by BOM SKUs"
  }
}

SELECT 
    oi.*
    , CONCAT(product_id, "_", seller_code) AS sku_key
    , o.province_code
FROM ${ref("fact_order_item_combo")} AS oi 
LEFT JOIN ${ref('fact_order')} AS o ON oi.order_id = o.order_id
