config {
  type: "view",
  tags: ["Stream"]
}

WITH cte_agg as (
SELECT
  AVG(
    DATETIME_DIFF(delivered_time, created_at, HOUR)
  ) e2e_l30d
FROM ${ref('fact_order')} as o
LEFT JOIN ${ref("dim_calendar")} as c on DATE(o.created_at) = c.Date
WHERE 
    confirmed_time IS NOT NULL
    AND delivered_time IS NOT NULL
    AND c.aging_day <= 30
)

SELECT
  "" as year_month,
  metric,
  performance
FROM
  cte_agg,
  UNNEST([
    STRUCT('E2E-30D' AS metric, e2e_l30d AS performance)
  ]) AS record


