config {
    type: 'view',
    schema: "buymed_innovation",
    description: "Margin of Circa COS.",
    //tags: ['AI_CIRCA']
}
-- SELECT 
--  e.name AS client_name
-- ,o.client_id
-- ,o.created_date
-- ,pos_type
-- ,o.client_id
-- ,pos_code
-- ,pos_name
-- ,channel
-- ,SUM(gmv) gmv
-- ,SUM(cogs_circa) cogs_circa
-- ,SUM(cogs_buymed) cogs_buymed
-- ,SUM(gross_profit_circa) gross_profit_circa
-- ,SUM(gross_profit_buymed) gross_profit_buymed
-- ,SAFE_DIVIDE(SUM(gross_profit_circa), SUM(gmv)) AS gross_margin_circa
-- ,SAFE_DIVIDE(SUM(gross_profit_circa), SUM(gmv)) AS gross_margin_buymed
-- ,SUM(voucher_circa) voucher_circa
-- ,SUM(voucher_buymed) voucher_buymed
-- ,SUM(deal) deal
-- ,SUM(net_profit_circa) net_profit_circa
-- ,SUM(net_profit_buymed) net_profit_buymed
-- ,SAFE_DIVIDE(SUM(net_profit_circa), SUM(gmv)) AS net_margin_circa
-- ,SAFE_DIVIDE(SUM(net_profit_buymed), SUM(gmv)) AS net_margin_buymed
-- FROM buymed_innovation.circa_fact_net_margin o 
-- LEFT JOIN buymed_circa_v2.entity_client e ON o.client_id = e.id
-- WHERE client_id NOT IN (5)
-- GROUP BY ALL


SELECT 
      e.client_name
    , o.client_id
    , o.completed_date
    , o.completed_return_date
    , pos_type
    , pos_code
    , pos_name
    , order_code
    , product_id
    , sku_code
    , product_name
    , brand
    , brand_type
    , product_category
    , cat2
    , cat3
    , cat4
    , channel
    , SUM(gmv) gmv
    , SUM(voucher_circa) voucher_circa
    , SUM(voucher_product) voucher_product
    , SUM(deal) deal
    , SUM(return_amount) return_amount
    , SUM(cogs_circa_return) cogs_circa_return
    , SUM(voucher_gift_circa_return) voucher_gift_circa_return
    , SUM(net_revenue) net_revenue
    , SUM(cogs_circa) cogs_circa
    , 0 as rebate
    , SUM(gross_profit_circa) gross_profit_circa
    , safe_divide(SUM(gross_profit_circa), sum(net_revenue)) as gross_margin_circa
    , SUM(voucher_gift_circa) voucher_gift_circa
    , SUM(net_profit_circa) net_profit_circa
    , safe_divide(SUM(net_profit_circa), sum(net_revenue)) as net_margin_circa
    , refresh_at 
FROM ${ref("gold_buymed_vn2", "circa_fact_net_margin")} o 
LEFT JOIN ${ref("gold_buymed_vn2", "circa_dim_entity_client")} e ON o.client_id = e.client_id
WHERE order_code <> 'DHC01184651' -- huyen.ngo hard_code, request by tri.dao
GROUP BY ALL
 