config {
    type: 'table',
    schema: "buymed_innovation",
    description: `All orders item of Circa.`,
    tags: ['AI_CIRCA', "custom_1h_past10"]
}

-- SELECT
--     a.year_month
--     , a.pos_code
--     , p.name AS pos_name
--     , b.net_revenue
--     , a.target_rev_vat_in AS target_revenue
--     , b.transactions
--     , a.target_transactions
--     , b.active_customer
--     , a.target_active_customers
-- FROM ${ref("gold_buymed_vn2", "target_sales")} AS a
--     LEFT JOIN (
--         SELECT
--             DATE_TRUNC(o.completed_date, MONTH) AS year_month
--             , o.pos_code
--             , SUM(o.total_amount - COALESCE(r.rev_return,0)) AS net_revenue
--             , COUNT(DISTINCT o.order_id) AS transactions
--             , COUNT(DISTINCT o.entity_id) AS active_customer
--             -- , 
--         FROM ${ref('gold_buymed_vn2','cos_fact_order')} AS o
--             LEFT JOIN ${ref('gold_buymed_vn2','cos_return_completed')} AS r ON o.order_code = r.order_code
--         WHERE o.status IN ('COMPLETED', 'COMPLETED_SHIPPING')
--             AND o.pos_id <> "0afdb831-b60d-4254-8822-df13e39c90e7"
--         GROUP BY ALL
--     ) AS b ON a.pos_code = b.pos_code AND a.year_month = b.year_month
--     LEFT JOIN buymed_circa_v2.entity_pos_profile AS p ON a.pos_code = p.code
-- WHERE a.year_month >= "2025-12-01"

WITH fact_order_item AS (
    SELECT
          i.order_code
        , SUM(
            i.unit_price_before_discount * (i.quantity - COALESCE(i.qty_rt, 0))
        ) AS gmv_product_raw
    FROM ${ref("gold_buymed_vn2", "cos_fact_order_item")} i
    WHERE i.client_id = 1
    GROUP BY
          i.order_code
), gmv AS (
SELECT DISTINCT
      o.pos_code
    , o.created_date
    ,type AS order_type
    , GREATEST(COALESCE(f.gmv_product_raw, 0), 0) + COALESCE(o.medicine_cutting_fee, 0) AS actual_gmv
FROM ${ref("gold_buymed_vn2", "cos_fact_order")} o
LEFT JOIN fact_order_item f ON o.order_code = f.order_code
WHERE o.client_id = 1
  AND o.status IN ('COMPLETED', 'COMPLETED_SHIPPING')
)

SELECT a.date
      ,a.pos_code
      ,p.name AS pos_name
      ,p.client_id
      ,channel
      ,target AS target_gmv
      ,SUM(b.actual_gmv) AS actual_gmv
FROM buymed_external.target_circa_2026 AS a
LEFT JOIN gmv b ON a.pos_code = b.pos_code AND a.date = b.created_date AND a.channel = b.order_type
LEFT JOIN buymed_circa_v2.entity_pos_profile AS p ON a.pos_code = p.code
GROUP BY ALL