config {
    type: 'table',
    schema: "buymed_innovation",
    description: `All online orders of Circa.`,
    tags: ['AI_CIRCA', "custom_1h_past10"]
}


SELECT 
   o.order_code
    , o.customer_phone
    , o.customer_name
    , receiver_full_address
    , o.payment_method
    , o.deliver_method
    , o.admin_note
    , o.system_note
    , o.is_split_payment
    , o.wallet_paid_amount
    , o.secondary_pay_method
    , o.secondary_pay_amount
   -- , total_product
    , o.created_date
    , o.created_time
    , canceled_by_user_type
    , o2o_status AS order_status
    , assigned_pos_code
    , assigned_pos_name
    , tags
    , affiliate_partner_code
    , affiliate_partner_type
    , distance_km
    , delivery_carrier
    , province_name
    , district_name
    , cancel_group
    -- , price AS or
    , SUM(oi.quantity * oi.price) AS revenue
    , SUM(oi.origin_price * oi.quantity) AS gmv
    , o.o2o_status AS status
    , oi.product_id
    , oi.product_name
    , oi.unit
    , oi.price AS unit_price
    , oi.quantity
    , oi.origin_price
    , is_deal1k
    , deal_name
    , campaign_name
FROM ${ref("gold_buymed_vn2", "circa_online_order_item")} AS oi
    LEFT JOIN ${ref("gold_buymed_vn2", "circa_online_order")} AS o USING(order_code)
    GROUP BY ALL


