config {
    type: "table",
    description: "PIC: tu.dang,",
    tags:"0h30",
    columns:{

    }

}
with outbound_list as
         (select fbi.order_id,
                 fbi.customer_id,
                 fbi.price as sales_price,
                 fbi.sku_code,
                 fbi.outbound_quantity,
                 fbi.po_code,
                 fbi.product_id ||"_"|| fbi.seller_code as sku_key,
                --  fbi.product_id ||"_"|| fbi.seller_code ||"_"|| ds.sales_region_code as sku_key_sales_region_code,
                 ds.location_code
          from ${ref('fact_outbound_item')} fbi
          left join 
        --   gold_buymed_vn2.dim_order_sales_region ds on fbi.order_id = ds.order_id
          ${ref('dim_customer') } ds on fbi.customer_id = ds.customer_id
--                    left join gold_buymed_vn2.dim_customer c on fbi.customer_id = c.customer_id
          where date(fbi.created_at) >= "2024-07-01"
             -- and c.customer_level in ('LEVEL_DIAMOND', 'LEVEL_PLATINUM')
             -- and c.province_code = "79"
         ),
     po_list as
         (select a.*,
                 a.price_after_discount * vat as purchase_price
          from (select po_code,
                       sku,
                       price_after_discount,
                       case
                           when vat is null then 0
                           when vat <= 0 then 0
                           else (100 - vat) / 100 end as vat
                from platinum_buymed_vn.seller_prd_purchasing_purchase_order_item poi) a),
     cte_full as
         (select ol.*,
                 pl.purchase_price,
                 sum(ol.outbound_quantity * purchase_price)                                              as purchase_amount,
                 sum(ol.outbound_quantity * ol.sales_price)                                              as sale_amount,
                 sum(ol.outbound_quantity * ol.sales_price) - sum(ol.outbound_quantity * purchase_price) as profit
          from outbound_list ol
                   left join po_list pl on ol.po_code = pl.po_code and ol.sku_code = pl.sku
          group by all
    )
select *
from cte_full

-- group by all