config {
    type:"view",
    description: "PIC: tu.dang; model_type: view"
}
select
    cast(FORMAT_DATE('%Y-%m', created_at)as string) as year_month,
    customer_id,
    count(distinct product_id) as no_products,
    sum(sales_price* demand_quantity)as order_amount,
    count(distinct order_id) as no_orders,
    sum(sales_price* demand_quantity)/count(distinct order_id) as average_order_value
from gold_buymed_vn2.fact_order_item
where date (created_at)> "2024-01-01"
group by all