config {
    type:"view",
    description: "PIC: tu.dang; model_type: view",
    columns :
    {
        "date":"daily date in calendar",
        "customer_id":"the unique identifier of the customer",
        "no_skus":"Counts the distinct number of different skus",
        "no_orders":"Counts the distinct number of different orders",
        "order_amount":"Total customer order amount",
        "average_order_value" :"the average value of each order placed by a customer"

    }
}
WITH DateSeries AS 
(
  SELECT *
  FROM UNNEST(GENERATE_DATE_ARRAY(DATE(DATE_TRUNC(current_date(), MONTH) - INTERVAL 12 MONTH), DATE(current_date()))) AS date
)
, order_item as 
(select
    -- cast(cast(FORMAT_DATE('%Y-%m', oi.created_at)as string)||"-01" as date ) as start_of_month,
    date(oi.created_at) as created_date,
    customer_id,
    count(distinct sku_code ) as no_skus,
    count(distinct product_id ) as no_products,
    sum (demand_quantity) as  order_qty,
    count(distinct oi.order_id) as no_orders,count(oi.product_id) as no_order_item,
    -- sum(sales_price* demand_quantity)/count(distinct oi.order_id) as average_order_value,
    sum(sales_price* demand_quantity) as order_amount
from ${ref('fact_order_item')} oi
left join ${ref('dim_order_status')} o on oi.order_id = o.order_id
where 
date (date_trunc( date_sub( current_date('+7'), interval 12 month) , month ))<= date(oi.created_at) and 
CRM_status not in  ("CANCEL","RETURNED")
group by all)
, user_event as 
(
    select 
        created_date,
        customer_id,
        sum(
            case
                when event = "ADD_TO_CART" then 1 else 0 end
            ) as count_add_cart,
            sum(
            case
                when event = "SKU_IMPRESSION" then 1 else 0 end
            ) as count_sku_impression,
            sum(
            case
                when event = "SKU_DETAIL_VIEW"  then 1 else 0 end
            ) as count_sku_detail_view
        from ${ref('fact_user_event_tracking')}
    where 
    date (date_trunc( date_sub( current_date('+7'), interval 3 month) , month ))<= created_date 
    -- and event = "ADD_TO_CART"
    group by 1, 2
)
, online_cus as 
(select
    created_date,
    customer_id,
    1 as is_online
from ${source.platinum}.monitoring_prd_realtime_user_customer_event oi
where DATE(created_time, "Asia/Ho_Chi_Minh")>= "2024-06-01"
qualify ROW_NUMBER() over (partition by created_date,customer_id)= 1
)
, chat_cus as 
(
    select 
        created_date,
        customer_id,
        1 as is_chat
    from ${source.platinum}.integration_prd_chat_conversation
    where DATE(created_time, "Asia/Ho_Chi_Minh")>= "2024-06-01"
    qualify ROW_NUMBER() over (partition by created_date,customer_id)= 1
)
SELECT 
    COALESCE(ds.date, oi.created_date, ue.created_date) AS date,
    COALESCE(oi.customer_id, ue.customer_id) AS customer_id,
    
    -- Metrics from order_item
    oi.no_skus,
    oi.no_products,
    oi.order_qty,
    oi.no_orders,
    oi.order_amount,
    no_order_item,
    -- Metrics from user_event
    ue.count_add_cart,
    ue.count_sku_impression,
    ue.count_sku_detail_view,
  COALESCE(oc.is_online, 0) AS is_online,
  COALESCE(cc.is_chat, 0) AS is_chat

FROM DateSeries ds
FULL OUTER JOIN order_item oi ON ds.date = oi.created_date
FULL OUTER JOIN user_event ue ON ds.date = ue.created_date AND oi.customer_id = ue.customer_id
FULL OUTER JOIN online_cus oc ON COALESCE(oi.created_date, ue.created_date) = oc.created_date 
                               AND COALESCE(oi.customer_id, ue.customer_id) = oc.customer_id
FULL OUTER JOIN chat_cus cc ON COALESCE(oi.created_date, ue.created_date, oc.created_date) = cc.created_date 
                             AND COALESCE(oi.customer_id, ue.customer_id, oc.customer_id) = cc.customer_id
WHERE COALESCE(oi.created_date, ue.created_date, oc.created_date, cc.created_date) IS NOT NULL
  AND COALESCE(oi.customer_id, ue.customer_id, oc.customer_id, cc.customer_id) IS NOT NULL
-- ORDER BY date, customer_id