config {
    type: "table",
    description: `PIC: minh.luu; model_type: table; schedule 0h00
    Source:
        ${source.silver}.marketplace_prd_customer_customer`,
    assertions:{
        nonNull: ["customer_id"],
        uniqueKey: ["customer_id"]
    },
    name: "dim_customer_test",
    tags: ["0h00"],
    columns: {
        customer_id: "",
        customer_name: "Not Null",
        customer_email: "Nullable",
        customer_address: "Nullable",
        customer_report_category: "NonNull | Is one of TECH, TENDER, MARKETPLACE, or CIRCA? Category assigned to the customer based on specific conditions: TECH: If the customer's name contains keywords like 'TECH SELLER', 'TEST', 'TECH-QC', etc. TENDER: If the customer's tags contain 'TENDER'. MARKETPLACE: If the customer's tags contain 'TERMINATE_CIRCA' or as a default category. CIRCA: If the customer's tags contain 'CIRCA'.",
        business_scope: "Nullable | Null means UNKNOWN scope",
        customer_location_code: "Nullable | if customer table doesn't has then get last order from dim_order"
    }
}

WITH stg_customer AS (
    SELECT
        dedup_customer.customer_id,
        dedup_customer.name AS customer_name,
        dedup_customer.email AS customer_email,
        dedup_customer.address AS customer_address,
        CASE
            WHEN REGEXP_CONTAINS( UPPER(name), r'TECH SELLER|TEST|TECH-QC|TS-TECH|\[TECH\]|\(TECH\)|DEMO|QC|TECH MONITOR|TECH 2') THEN "TECH"
            WHEN customer_id = 241098 THEN "CONSIGNMENT"
            WHEN customer_id = 360299 THEN "OPV"
            WHEN TO_JSON_STRING( dedup_customer.tags ) LIKE '%TENDER%' THEN 'TENDER'
            WHEN TO_JSON_STRING( dedup_customer.tags ) LIKE '%\"TERMINATE_CIRCA\"%'  THEN 'MARKETPLACE'
            WHEN TO_JSON_STRING( dedup_customer.tags ) LIKE '%CIRCA%'  THEN 'CIRCA' -- Một số terminate circa vẫn được gán nhãn là circa ví dụ customer_id in (252404,358259,369079)
            ELSE 'MARKETPLACE' -- Một số order trong dim_order bị xếp loại vào Marketplace trong khi vốn tên có là FC-CIRCA
        END AS customer_report_category,
        dedup_customer.scope  AS business_scope,
        -- CASE
        --     WHEN ward_code IS NOT NULL THEN ward_code
        --     WHEN district_code IS NOT NULL THEN district_code
        --     WHEN province_code IS NOT NULL THEN province_code
        --     ELSE NULL
        -- END AS customer_location_code
        ward_code AS customer_ward_code,
        district_code AS customer_district_code,
        province_code AS customer_province_code,

        ward_name AS customer_ward_name,
        district_code_name AS customer_district_name,
        province_code_name AS customer_province_name


    FROM 
        ${dedup.dedup(source.silver + `.marketplace_prd_customer_customer`,'*')} dedup_customer
)
, stg_customer_order AS (
    -- SELECT 
    --     customer_id,
    --     ARRAY_AGG( customer_location_code ORDER BY created_time DESC)[0] AS customer_location_code
    -- FROM ${ref(`dim_order_customer`)}  doc
    -- LEFT JOIN ${ref(`dim_order_status`)} dos ON doc.order_id = dos.order_id
    -- GROUP BY customer_id

    SELECT
        customer_id,
        ARRAY_AGG( customer_ward_code ORDER BY created_time DESC)[0] AS customer_ward_code,
        ARRAY_AGG( customer_ward_name ORDER BY created_time DESC)[0] AS customer_ward_name,
        ARRAY_AGG( customer_district_code ORDER BY created_time DESC)[0] AS customer_district_code,
        ARRAY_AGG( customer_district_name ORDER BY created_time DESC)[0] AS customer_district_name,
        ARRAY_AGG( customer_province_code ORDER BY created_time DESC)[0] AS customer_province_code,
        ARRAY_AGG( customer_province_name ORDER BY created_time DESC)[0] AS customer_province_name

    FROM ${source.silver}.marketplace_prd_order_v2_order
    GROUP BY customer_id
)

js {
    function when_case(column_name){
        return `WHEN ${column_name} IS NOT NULL AND ${column_name} NOT LIKE '0' THEN ${column_name}`
    }
}

SELECT
    c.customer_id,

    CASE
        ${when_case(`c.customer_ward_code     `)}
        ${when_case(`co.customer_ward_code    `)}
        ${when_case(`c.customer_district_code `)}
        ${when_case(`co.customer_district_code`)}
        ${when_case(`c.customer_province_code `)}
        ${when_case(`co.customer_province_code`)}
        ELSE NULL
    END AS customer_location_code,

    c.customer_ward_code as c_ward_code,
    co.customer_ward_code as co_ward_code,
    c.customer_district_code as c_district_code,
    co.customer_district_code as co_district_code,
    c.customer_province_code as c_province_code,
    co.customer_province_code as co_province_code,

    c.customer_ward_name as c_ward_name,
    co.customer_ward_name as co_ward_name,
    c.customer_district_name as c_district_name,
    co.customer_district_name as co_district_name,
    c.customer_province_name as c_province_name,
    co.customer_province_name as co_province_name

FROM
    stg_customer c
LEFT JOIN stg_customer_order co ON c.customer_id = co.customer_id
-- LEFT JOIN ${ref(`dim_geo_location`)} dgl1 ON stg_customer.customer_location_code = dgl1.location_code
-- LEFT JOIN ${ref(`dim_geo_location`)} dgl2 ON stg_customer_order.customer_location_code = dgl2.location_code


-- post_operations {
--     ALTER TABLE ${self()} ADD PRIMARY KEY (customer_id) NOT ENFORCED;
-- }