config {
    type: "table",
    tags: ["adhoc-office"],
    dependencies: ["platform_organization_prd_ticket_ticket_instance"],
    name: "fact_ticket_instance",
    description: "PIC: tu.dang; model_type: table; Schedule: At minute 5 past hour 7, 10, 13, 16 and 19",
    bigquery: {
    partitionBy: "created_date"
  }
}

with ticket_note as 
(
  select ref_code,
       STRING_AGG(message,"; -") as message_notes
from ${source.platinum}.platform_organization_prd_ticket_message
where ref_type like "TICKET_INSTANCE"
  and message_type = "INTERNAL_NOTE"
--   and ref_code = "25GGV-17036"
group by ref_code

)

select requester_code,
       requester_name,
       clasify,
       JSON_EXTRACT_SCALAR(a,'$.department_code') as department_code,
       reason_code,
       priority,
       template_topic_code,
       ticket_instance_code,
       name as ticket_name,
       JSON_EXTRACT_SCALAR(input_data,'$.userDescription') as user_description,
       cause_code,
       assignee_account_id,
       DATETIME(PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S%Ez',JSON_EXTRACT_SCALAR(JSON_EXTRACT(decision_selecteds,'$[0]'),'$.decision_time')), "Asia/Ho_Chi_Minh") as first_decision_time,
       DATETIME(PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S%Ez',JSON_EXTRACT_SCALAR(JSON_EXTRACT(decision_selecteds,'$[1]'),'$.decision_time')), "Asia/Ho_Chi_Minh") as second_decision_time,
       status as ticket_status,
       JSON_EXTRACT_SCALAR(JSON_EXTRACT(decision_selecteds,'$[0]'),'$.name') as first_decision_name,
       JSON_EXTRACT_SCALAR(JSON_EXTRACT(decision_selecteds,'$[1]'),'$.name') as senconde_decision_name,
       json_extract_scalar(input_data, '$.orderID') as order_id,
       created_date,
       case when requester_type is null then  JSON_EXTRACT_SCALAR(input_data,'$.REQUESTER_TYPE') 
       else requester_type
       end as requester_type,
       created_by_account_name,
       assignee_account_name,
       assignee_account_email,
       template_module_code,
       branch_code,
       case when created_by_account_id > 0 then "Internal"
       else "Pharmacy" end as creator_type , partner_code,
       case when picked_time is null then DATETIME(created_time, "Asia/Ho_Chi_Minh") 
       else
       DATETIME(picked_time, "Asia/Ho_Chi_Minh") end AS picked_time,
       DATETIME(created_time, "Asia/Ho_Chi_Minh") AS created_time,
       DATETIME(deadline_time, "Asia/Ho_Chi_Minh") AS deadline_time,
       root_ticket_instance_code,
       DATETIME(PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S%Ez',JSON_EXTRACT_SCALAR(extra_props,'$.completed_time')), "Asia/Ho_Chi_Minh") as completed_time,
       message_notes
from `${source.platinum}.platform_organization_prd_ticket_ticket_instance` ti,

     unnest(JSON_EXTRACT_ARRAY(assign_roles,'$')) a,
     unnest(JSON_EXTRACT_ARRAY(decision_selecteds,'$')) b
left join ticket_note as tn on ti.ticket_instance_code = tn.ref_code
-- where key like 'a0110ebd-0265-4bcb-832a-78322d27c34f'
-- requester_type like "CIRCA_FS" or
-- template_module_code like "CIRCA_FS" and branch_code like "VN"
QUALIFY ROW_NUMBER() OVER(partition by ticket_instance_code ) = 1