config {
    type: "table",
    tags: ["sku_history_change"],
    description: "SKU status history by hours ( 1 day ) || PIC: anh.letam;  model_type: table; schedule: hourly",
    name: "fact_sku_status_day_by_hour_v2",
    dependencies: ["staging_sku_status_history"],
    columns: {
        last_refreshed_at: "The timestamp indicating the last time the data was refreshed, adjusted to the +7 timezone.",
        // item_code : "A unique identifier for each item,",
        // sku_code  : "A unique identifier for the SKU, representing a specific product variant",
        // date_time : "The datetime value representing each hour in the generated timestamp array",
        // sku_system_active : "A boolean indicating whether the SKU system is active or not",
        // sales_region_code : "The code representing the sales region associated with the SKU",
        // sub_sku_sales_region_code : "A concatenation of item_code and sales_region_code to form a unique identifier for the item-region pair",
        // sku_sales_region_code : "A concatenation of sku_code and sales_region_code to form a unique identifier for the SKU-region pair.",
        // status : "The status of the SKU, indicating its availability or other conditions",
        // start_at : "The timestamp indicating when the status period for the SKU started, adjusted to the "+7" timezone",
        // end_at_custom : "The custom end timestamp for the status period, adjusted to the "+7" timezone",
        // end_at : "The original end timestamp for the status period, adjusted to the "+7" timezone"

    }
}



-- get location_code from dim_sku_sales_region_current

WITH status_history_location AS (
  SELECT
    a.sku,
    a.item_code,
    a.status,
    a.is_active,
    a.created_time,
    b.sales_region_code as location_code,
    a.ingest_time,
    a.key
  FROM
    ${ref("staging_sku_status_history")} a
  left join lakehouse-prod-394907.gold_buymed_vn.dim_sku_sales_region_current b on a.item_code = b.sub_sku_code
),

--generate 24 hours datetime series
timeseries AS (
  SELECT *
  FROM
    UNNEST(
        GENERATE_TIMESTAMP_ARRAY( TIMESTAMP_SUB(CURRENT_TIMESTAMP() , INTERVAL 1 day),
        CURRENT_TIMESTAMP(),
        INTERVAL 1 HOUR )
    ) AS timestamp
),  DateSeries AS (
  SELECT DATETIME(timestamp,'Asia/Ho_Chi_Minh') as date_time from timeseries
),

-- join with dim_sales_region_service_area to map location_code with sales_region_code
-- maybe no need to join dim_sales_region_service_area  because we already get location_code from dim_sku_sales_region_current
sku_status as (
SELECT
    sku,
    item_code,
    start_at,
    CASE
      WHEN end_at IS NULL AND start_at IS NOT NULL AND status IS NOT NULL THEN CURRENT_DATETIME("+7")
      ELSE end_at
    END AS end_at_custom,
    end_at,
    status,
    is_active,
    sales_region_code,
    -- , active
  FROM (
    SELECT
      ss.sku,
      ss.item_code,
      DATETIME(ss.created_time, 'Asia/Ho_Chi_Minh') AS start_at,
      LEAD(DATETIME(ss.created_time, 'Asia/Ho_Chi_Minh')) OVER (PARTITION BY ss.sku, ss.item_code, b.region_code ORDER BY ss.created_time ASC) AS end_at,
      ss.status,
      ss.is_active
      , b.region_code AS sales_region_code,
      -- ,
      -- CASE WHEN status = "OUT_OF_STOCK" THEN "OFF"
      -- ELSE "ON"
      -- END AS active
      ingest_time,
      key
    FROM status_history_location ss
    LEFT JOIN gold_buymed_vn.dim_sales_region_service_area AS b ON b.service_area_code = ss.location_code)

),


--get list of unique item_code and add datetime column
sku_list as (SELECT
    ss.sku,
    ss.item_code,
    ss.sales_region_code,
    CONCAT(ss.item_code, "_", ss.sales_region_code) AS sub_sku_sales_region_code
  FROM sku_status ss
  WHERE ss.sales_region_code IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ss.item_code, sales_region_code) = 1)
,

sku_date AS (
  SELECT *
  FROM sku_list, DateSeries
),

-- step 2: fill missing value, generate status from 24 hours of each item_code.
fill_backwwark_value AS (SELECT
    sd.item_code,
    CURRENT_DATETIME("+7") AS last_refreshed_at,
    sd.sku,
    sd.date_time,
    ss.start_at,
    ss.end_at,
    ss.end_at_custom,
    ss.status,
    cast(ss.is_active as string),
    ss.sales_region_code,
    sd.sub_sku_sales_region_code,
    LEFT(sd.item_code, INSTR(sd.item_code, '.', 1, 2) - 1) AS sku_code_bf,
   CASE
      WHEN CONTAINS_SUBSTR(sd.sub_sku_sales_region_code, 'MIENBAC') IS TRUE THEN "MIENBAC"
      WHEN CONTAINS_SUBSTR(sd.sub_sku_sales_region_code, 'MIENNAM') IS TRUE THEN "MIENNAM"
      WHEN CONTAINS_SUBSTR(sd.sub_sku_sales_region_code, 'MIENTRUNG') IS TRUE THEN "MIENTRUNG"
    END AS sales_region_code_bf,
    CASE
      WHEN ss.end_at_custom IS NULL THEN LEAD(ss.start_at)
        OVER (PARTITION BY sub_sku_sales_region_code ORDER BY sd.date_time ASC)
      -- last_value(ss.start_at IGNORE NULLS) over(partition by sub_sku_sales_region_code ORDER BY sd.date_time ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING)
      ELSE ss.end_at_custom
    END AS end_at_custom_v2,
    CASE
      WHEN ss.start_at IS NULL THEN DATETIME_SUB(CURRENT_DATETIME("+7"), INTERVAL 1 DAY)
      ELSE ss.start_at
    END AS start_at_v2,
    -- , s.sku_system_active
    FIRST_VALUE(ss.status IGNORE NULLS) OVER (partition by sd.sub_sku_sales_region_code ORDER BY sd.date_time ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS contrast_first_status,
    FIRST_VALUE(cast(ss.is_active as string) IGNORE NULLS) OVER (partition by sd.sub_sku_sales_region_code ORDER BY sd.date_time ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS contrast_first_active
    from sku_date as sd
    left join  sku_status as ss on sd.item_code = ss.item_code and sd.sales_region_code = ss.sales_region_code and sd.date_time between ss.start_at and ss.end_at_custom)

, in_historical as (select
    c.last_refreshed_at
    , c.item_code,
      s.product_id
    , c.sku as sku_code
    , c.date_time
    , c.sales_region_code_bf as sales_region_code
    , c.sub_sku_sales_region_code
    , c.start_at_v2
    , c.start_at
    , case
        when contrast_first_status = "OUT_OF_STOCK" and status is null and c.date_time >= date(s.sku_approved_at) then "NORMAL"
        when contrast_first_status not in ("OUT_OF_STOCK") and status is null and c.date_time >= date(s.sku_approved_at) then "UNKNOWN"
        when c.date_time < date(s.sku_approved_at) and status is null then null
        else contrast_first_status
      end as status,
      s.sku_approved_at,
      s.seller_code -- tu.dang
    , s.sku_system_active
    , first_value(c.end_at_custom_v2 IGNORE NULLS) over(partition by sub_sku_sales_region_code ORDER BY c.date_time ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) as end_at_custom_v3
    , c.end_at_custom_v2
    , c.end_at_custom
    ,c.end_at
from fill_backwwark_value c
left join gold_buymed_vn.adhoc_pm_master_sku s on c.sku = s.sku_code and c.sales_region_code_bf = s.sales_region_code
where c.date_time > CURRENT_DATETIME("+7") - INTERVAL 1 day),

-- step 3: listing toàn bộ những con sku không được ghi nhân có sự thay đổi status in L90D và join với historical

-- join with adhoc_pm_master_sku to get filter sku_system_active = true
sku_remaining as (select
        -- DATETIME(TIMESTAMP(CURRENT_DATETIME()), 'Asia/Ho_Chi_Minh') AS last_refreshed_at,
        ms.sub_sku_code as item_code,
          ms.product_id
        , ms.sku_code
        , ms.sku_system_active,
        ms.sku_approved_at
        , ms.sales_region_code
        , ms.seller_code -- tu.dang
        , ms.sku_code || "_" || ms.sales_region_code as sku_sales_region_code
        , ms.sub_sku_code || "_" || ms.sales_region_code as sub_sku_sales_region_code
        , ms.sku_system_status as status
        , CURRENT_DATETIME("+7") - INTERVAL 1 day as start_at
        , CURRENT_DATETIME("+7") as end_at_custom
        , CURRENT_DATETIME("+7") as end_at
      -- , DATEtime(current_date() - INTERVAL 3 MONTH)
  from gold_buymed_vn.adhoc_pm_master_sku ms
left join sku_list sl on ms.sku_code = sl.sku and ms.sales_region_code = sl.sales_region_code
where sl.sub_sku_sales_region_code is null and ms.sku_system_active = true )


-- get unique sku that from sku_remaining
, sku_remaining_list as (SELECT
    ss.sku_code,
    ss.sales_region_code,
    CONCAT(ss.sku_code, "_", ss.sales_region_code) AS sku_sales_region_code
  FROM sku_remaining ss
  -- WHERE ss.sales_region_code IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ss.sku_code, sales_region_code) = 1),


-- merge with 24 timestamp
   sku_remaining_date_time as (select *
  from sku_remaining_list,DateSeries)

-- union những con item_code không có trong historical data và union với hisrorical_data
  , union_all as (select
    CURRENT_DATETIME("+7") AS last_refreshed_at
    , sr.item_code,
      sr.product_id
    , md.sku_code
    , sr.seller_code -- tu.dang
    , sr.sku_system_active -- tu.dang
    , md.date_time
    , md.sales_region_code
    , sr.sub_sku_sales_region_code
    , md.sku_sales_region_code,
      sr.sku_approved_at
    , sr.status
    , sr.start_at
    , sr.end_at_custom
    , sr.end_at
from sku_remaining_date_time md
left join sku_remaining sr on md.sku_sales_region_code = sr.sku_sales_region_code and md.date_time between sr.start_at and sr.end_at_custom
where md.date_time > CURRENT_DATETIME("+7") - INTERVAL 1 day
union all
select
      c.last_refreshed_at
    , c.item_code,
      c.product_id
    , c.sku_code
    , c.seller_code -- tu.dang
    , c.sku_system_active -- tu.dang
    , c.date_time
    , c.sales_region_code
    , c.sub_sku_sales_region_code
    , c.sku_code ||"_"|| c.sales_region_code as sku_sales_region_code,
      c.sku_approved_at
    , c.status
    , c.start_at_v2  as start_at
    , c.end_at_custom_v3 as end_at_custom
    , c.end_at
from in_historical c)

/* pic: tu.dang */
-- check list product OOS real
, product_seller as -- get all seller of product,condition: only sku active
(
    select
        sr.product_id, sr.sales_region_code,
        safe_cast (count(distinct sr.seller_code) as string) as no_seller,
        string_agg( sr.seller_code,", ") as list_seller_in_product
    from gold_buymed_vn.adhoc_pm_master_sku as sr
    where sr.sku_system_active = true and sku_system_status is not null
    group by all
)
, product_seller_oos as -- get all seller of product, condition: only sku active and status sku = oos
          (
select
    sr.product_id, sr.sales_region_code,date_time,
    safe_cast (count(distinct sr.seller_code) as string) as no_seller_oos, string_agg( sr.seller_code, ", ") as list_seller_oos_in_product
from union_all as sr
where sr.sku_system_active = true and sr.status = "OUT_OF_STOCK" and status is not null
group by all
    )

select cf.*,
case
  when cf.sku_system_active = true then ps.no_seller -- pic:tu.dang
  else '' end as no_seller,
case 
  when cf.sku_system_active = true then po.no_seller_oos -- pic:tu.dang
  else '' end as no_seller_oos
from union_all cf
left join product_seller ps on cf.product_id= ps.product_id and cf.sales_region_code= ps.sales_region_code 
left join product_seller_oos po on cf.product_id= po.product_id and cf.date_time= po.date_time and cf.sales_region_code= po.sales_region_code
-- where sku_system_active = true






  




 