config {
    type: "table",
    tags: ["adhoc-office"],
    description: "SKU status history by hours ( 1 day ). PIC: Minh",
    name: "fact_sku_status_history2"
}
WITH DateSeries AS (
  SELECT *
  FROM 
    UNNEST( 
        GENERATE_TIMESTAMP_ARRAY( TIMESTAMP_SUB(CURRENT_TIMESTAMP() , INTERVAL 5 day), 
        CURRENT_TIMESTAMP(), 
        INTERVAL 1 HOUR )
    ) AS timestamp
),
-- step 1: lấy danh sách nhưng con item_code được ghi nhận có thay đổi status trong l90d
sku_status AS (
  SELECT
    sku,
    item_code,
    start_at,
    CASE
      WHEN end_at IS NULL AND start_at IS NOT NULL AND status IS NOT NULL THEN TIMESTAMP(CURRENT_DATETIME())
      ELSE end_at
    END AS end_at_custom,
    end_at,
    status,
    sales_region_code
    -- , active
  FROM (
    SELECT
      ss.sku,
      ss.item_code,
      last_updated_time AS start_at,
      LEAD(last_updated_time) OVER (PARTITION BY ss.sku, item_code, b.region_code ORDER BY last_updated_time ASC) AS end_at,
      status
      , b.region_code AS sales_region_code
      -- ,
      -- CASE WHEN status = "OUT_OF_STOCK" THEN "OFF"
      -- ELSE "ON"
      -- END AS active
    FROM gold_buymed_vn.dedup_marketplace_prd_product_v2_sku_status_historical ss
    LEFT JOIN UNNEST(JSON_EXTRACT_ARRAY(ss.location_codes)) AS a
    LEFT JOIN gold_buymed_vn.dim_sales_region_service_area AS b ON b.service_area_code = STRING(a)
  ) a
),
sku_list AS (
  SELECT
    ss.item_code,
    ss.sales_region_code,
    CONCAT(ss.item_code, "_", ss.sales_region_code) AS sub_sku_sales_region_code
  FROM sku_status ss
  WHERE ss.sales_region_code IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ss.item_code, sales_region_code) = 1
),
sku_date AS (
  SELECT *
  FROM sku_list, DateSeries
),
-- step 2: fill missing value
fill_backwwark_value AS (
  SELECT
    sd.item_code,
    DATETIME(TIMESTAMP(CURRENT_DATETIME()), 'Asia/Ho_Chi_Minh') AS last_refreshed_at,
    ss.sku,
    sd.timestamp,
    DATETIME(ss.start_at, 'Asia/Ho_Chi_Minh') AS start_at,
    DATETIME(ss.end_at, 'Asia/Ho_Chi_Minh') AS end_at,
    DATETIME(ss.end_at_custom, 'Asia/Ho_Chi_Minh') AS end_at_custom,
    ss.status,
    ss.sales_region_code,
    sd.sub_sku_sales_region_code,
    LEFT(sd.item_code, INSTR(sd.item_code, '.', 1, 2) - 1) AS sku_code_bf,
    SUBSTR(sd.sub_sku_sales_region_code, INSTR(sd.sub_sku_sales_region_code, '_') + 1) AS sales_region_code_bf,
    CASE
      WHEN ss.end_at_custom IS NULL THEN LEAD(DATETIME(ss.start_at, 'Asia/Ho_Chi_Minh'))
        OVER (PARTITION BY sub_sku_sales_region_code ORDER BY sd.timestamp ASC)
      -- last_value(ss.start_at IGNORE NULLS) over(partition by sub_sku_sales_region_code ORDER BY sd.timestamp ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING)
      ELSE DATETIME(ss.end_at_custom, 'Asia/Ho_Chi_Minh')
    END AS end_at_custom_v2,
    CASE
      WHEN ss.start_at IS NULL THEN DATETIME_SUB(DATETIME(TIMESTAMP(CURRENT_DATETIME()), 'Asia/Ho_Chi_Minh'), INTERVAL 3 MONTH)
      ELSE DATETIME(ss.start_at, 'Asia/Ho_Chi_Minh')
    END AS start_at_v2,
    -- , s.sku_system_active
    FIRST_VALUE(ss.status IGNORE NULLS) OVER (partition by sd.sub_sku_sales_region_code ORDER BY sd.timestamp ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS contrast_first_status
    from sku_date as sd 
    left join sku_status as ss on sd.item_code = ss.item_code and sd.sales_region_code = ss.sales_region_code and sd.timestamp between ss.start_at and ss.end_at_custom
    -- left join 'gold_buymed_vn.dim_sku' s on ss.sku = s.sku_code
    -- left join `gold_buymed_vn.adhoc_pm_master_sku` s on ss.sku = s.sku_code
)
, in_historical_ as 
(
select 
    c.last_refreshed_at
    , c.item_code
    , c.sku as sku_code
    , c.timestamp
    , s.sku_system_active
    , c.sales_region_code_bf as sales_region_code
    , c.sub_sku_sales_region_code
    , c.start_at_v2
    , c.start_at
    , case 
        when contrast_first_status = "OUT_OF_STOCK" and status is null then "NORMAL"
        when contrast_first_status not in ("OUT_OF_STOCK") and status is null then "UNKNOWN"
        else contrast_first_status
      end as status
    , first_value(c.end_at_custom_v2 IGNORE NULLS) over(partition by sub_sku_sales_region_code ORDER BY c.timestamp ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) as end_at_custom_v3
    , c.end_at_custom_v2
    , c.end_at_custom
    ,c.end_at
    -- , case 
    -- when status=  "OUT_OF_STOCK" and date(start_at)= date(end_at) then sku
    -- else '' end as oos_check
from fill_backwwark_value c
left join gold_buymed_vn.adhoc_pm_master_sku s on c.sku = s.sku_code and c.sales_region_code_bf = s.sales_region_code
where c.timestamp > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY)
)

SELECT * FROM in_historical_
