config {
  type: "operations",
  schema: "buymed_circa_v2",
  tags: ["buymed_circa_v2_inventory", "platinum_custom_30m"],
  description: "PIC: long.nguyen"
}

js {
  const { generateCDCScript } = require("includes/platinum_render/circa_v2_view_helpers");

  const querySQL = generateCDCScript({
    postgresDatabase: "inventory",
    dataset:          "buymed_circa_v2_raw",          
    tableName:        "inventory_count_lines",       
    rawTable:         "inventory_inventory_count_lines",

    stgDataset:       "buymed_circa_v2_staging",
    stgTable:         "inventory_inventory_count_lines",


    viewDataset:      "buymed_circa_v2",
    viewTable:        "inventory_inventory_count_lines",

    primaryKey:       "id",
    createdTime:      "created_at",
    lookbackHours:    0,
  });
}

${querySQL}