js {
                const { generateCDCScript } = require("includes/platinum_render/circa_v2_helpers");

                const querySQL = generateCDCScript({
                    postgresDatabase: "order",
                    dataset:      "buymed_circa_v2_raw",
                    tableName:    "payment_request",
                    targetDataset: "buymed_circa_v2",
                    targetTable: "order_payment_request",
                    rawTable:     "order_payment_request",
                    primaryKey:   "id",
                    createdTime:  "created_at",
                    lookbackHours: 1,
                });
        }

                config {
                type: "operations",
                schema: "buymed_circa_v2",
                tags: ["buymed_circa_v2_order", "platinum_custom_10min"]
                }

                ${querySQL}
    