js {
                const { generateCDCScript } = require("includes/platinum_render/circa_v2_helpers");

                const querySQL = generateCDCScript({
                    postgresDatabase: "product",
                    dataset:      "buymed_circa_v2_raw",
                    tableName:    "store_assortment_template",
                    targetDataset: "buymed_circa_v2",
                    targetTable: "product_store_assortment_template",
                    rawTable:     "product_store_assortment_template",
                    primaryKey:   "id",
                    createdTime:  "created_at",
                    lookbackHours: 0,
                });
        }

                config {
                type: "operations",
                schema: "buymed_circa_v2",
                tags: ["buymed_circa_v2_product", "platinum_custom_30m"]
                }

                ${querySQL}
    