js {
  const { generateCDCScript } = require("includes/platinum_render/circa_v2_helpers");

  const querySQL = generateCDCScript({
    postgresDatabase: "vision_ai",
    dataset:      "buymed_circa_v2_raw",
    tableName:    "count_aggregates_minute",
    targetDataset: "buymed_circa_v2",
    targetTable: "vision_ai_count_aggregates_minute",
    rawTable:     "vision_ai_count_aggregates_minute",
    primaryKey:   "id",
    createdTime:  "created_at",
    lookbackHours: 1,
  });
}

config {
  type: "operations",
  schema: "buymed_circa_v2_staging",
  tags: ["cdc", "platinum_custom_30m"]
}

${querySQL}
