config {
    type: "view",
    name: "agg_strategic_do",
    description: `PIC: minh.luu, model_type: view
    Count Delivery Orders Before Cancel
    Source
        ${source.ref}.dim_order_channel
        ${source.ref}.dim_order_sales_region
        ${source.ref}.dim_calendar
        ${source.ref}.fact_strategic_sale_order_item_single`,
    columns: {
        date: "NonNull | End of month",
        location: "Nullable | sales_region_code, sometime orders had not assign yet",
        channel: "NonNull | order_channel",
        measure: "NonNull | GMV-BEFORE-CANCEL",
        value: "NonNull | "
    }
}
SELECT 
    dc.eom as date,
    CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
        ELSE "GMV-VN-REGION-UNKNOWN" 
    END AS location,
    CASE
        WHEN doc.order_channel IN ("MARKETPLACE","CONSIGNMENT" ) THEN "MARKETPLACE"
        ELSE doc.order_channel
    END AS channel,
    'DO' AS measure,
    COUNT(DISTINCT do.delivery_order_code) as value

FROM ${ref(`fact_strategic_delivery_order`)} do 
LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = do.order_id 
LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON do.order_id = dosr.order_id 
LEFT JOIN ${ref(`dim_order_status`)} dos ON dos.order_id = do.order_id
LEFT JOIN ${ref(`dim_calendar`)} dc ON date(do.created_dt) = dc.date
WHERE  doc.order_channel NOT IN ("TENDER","CONSIGNMENT-RECOGNITION")
AND doc.order_channel is not null
GROUP BY 1,2,3,4

UNION ALL 

SELECT 
    dc.eom as date,
    CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
        ELSE "GMV-VN-REGION-UNKNOWN" 
    END AS location,
    order_channel  as channel,
    'DO' AS measure,
    COUNT(DISTINCT do.delivery_order_code) as value


FROM ${ref(`fact_strategic_delivery_order`)} do 
LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = do.order_id 
LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON do.order_id = dosr.order_id 
LEFT JOIN ${ref(`dim_order_status`)} dos ON dos.order_id = do.order_id
LEFT JOIN ${ref(`dim_calendar`)} dc ON date(do.confirmation_dt) = dc.date
WHERE  doc.order_channel LIKE "TENDER"
AND dos.crm_status not like "WAIT_TO_CONFIRM"
GROUP BY 1,2,3,4