config {
    type: "view",
    name: "agg_strategic_gmv-unff",
    description: `PIC: minh.luu, model_type: view"
    Source
        ${source.ref}.dim_order_channel
        ${source.ref}.dim_order_sales_region
        ${source.ref}.dim_calendar
        ${source.ref}.fact_strategic_sale_order_item_single`,
    columns: {
        date: "NonNull | End of month",
        location: "Nullable | sales_region_code, sometime orders had not assign yet",
        channel: "NonNull | order_channel",
        measure: "NonNull | GMV-BEFORE-CANCEL",
        value: "NonNull | unfulfilled amount = demand_amount - outbound_amount when order isn't delivering, delivered or completed ,Note: In tender systems, we don't consider orders valid until they are confirmed by the customer, as their confirmation is essential to making the order valuable to actionable. On the other hand, in marketplace, orders become valid upon creation, as our system handles the confirmation process, not the customer."
    }
}
SELECT 
    dc.eom as date,
    CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NOTHERN"
        ELSE "GMV-VN-REGION-UNKNOWN" 
    END AS location,
    CASE 
        WHEN doc.order_channel IN ("MARKETPLACE","CONSIGNMENT" ) THEN "MARKETPLACE"
        ELSE doc.order_channel
    END AS channel,
    'GMV-UNFF' AS measure,
    SUM((demand_quantity - outbound_quantity) * price) as value

FROM ${ref(`fact_strategic_sale_order_item_single`)} ois 
LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = ois.order_id 
LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON ois.order_id = dosr.order_id 
LEFT JOIN ${ref(`dim_order_status`)} dos ON dos.order_id = ois.order_id
LEFT JOIN ${ref(`dim_calendar`)} dc ON date(ois.created_dt) = dc.date
WHERE  doc.order_channel NOT LIKE "CONSIGNMENT-RECOGNITION"
AND doc.order_channel is not null
AND dos.crm_status in ("DELIVERING","DELIVERED","COMPLETED")
GROUP BY 1,2,3,4





