config {
    type: "view",
    name: "agg_strategic_so",
    description: `PIC: minh.luu, model_type: view
    Count Sale Orders Before Cancel
    Source
        ${source.ref}.dim_order_channel
        ${source.ref}.dim_order_sales_region
        ${source.ref}.dim_calendar
        ${source.ref}.fact_strategic_sale_order_item_single`,
    columns: {
        date: "NonNull | End of month",
        location: "Nullable | sales_region_code, sometime orders had not assign yet",
        channel: "NonNull | order_channel",
        measure: "NonNull | GMV-BEFORE-CANCEL",
        value: "NonNull | "
    }
}
SELECT 
    dc.eom as date,
    CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
        ELSE "GMV-VN-REGION-UNKNOWN" 
    END AS location,
    CASE
        WHEN doc.order_channel IN ("MARKETPLACE","CONSIGNMENT" ) THEN "MARKETPLACE"
        ELSE doc.order_channel
    END AS channel,
    'SO' AS measure,
    
    -- SUM(ois.demand_quantity) Item_Sold,
    COUNT(distinct ois.order_id) value

FROM ${ref(`fact_strategic_sale_order_item_single`)} ois 
LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = ois.order_id 
LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON ois.order_id = dosr.order_id 
LEFT JOIN ${ref(`dim_order_status`)} dos ON dos.order_id = ois.order_id
LEFT JOIN ${ref(`dim_calendar`)} dc ON date(ois.created_dt) = dc.date
WHERE  doc.order_channel NOT IN ("TENDER","CONSIGNMENT-RECOGNITION")
AND doc.order_channel is not null
AND ois.supplier_class not like "TECH"
GROUP BY 1,2,3,4

UNION ALL 

SELECT 
    dc.eom as date,
    CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NORTHERN"
        ELSE "GMV-VN-REGION-UNKNOWN" 
    END AS location,
    order_channel  as channel,
    'SO' AS measure,

    -- SUM(ois.demand_quantity) Item_Sold,
    COUNT(distinct ois.order_id) value

FROM ${ref(`fact_strategic_sale_order_item_single`)} ois 
LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = ois.order_id 
LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON ois.order_id = dosr.order_id 
LEFT JOIN ${ref(`dim_order_status`)} dos ON dos.order_id = ois.order_id
LEFT JOIN ${ref(`dim_calendar`)} dc ON date(ois.confirmation_dt) = dc.date
WHERE  doc.order_channel LIKE "TENDER"
AND dos.crm_status not like "WAIT_TO_CONFIRM"
AND ois.supplier_class not like "TECH"
GROUP BY 1,2,3,4