config {
    type: "view",
    name: "agg_strategic_do",
    description: `PIC: minh.luu, model_type: view
    Count Delivery Orders Before Cancel
    Source
        ${source.ref}.dim_order_channel
        ${source.ref}.dim_order_sales_region
        ${source.ref}.dim_calendar
        ${source.ref}.fact_strategic_sale_order_item_single`,
    columns: {
        date: "NonNull | End of month",
        location: "Nullable | sales_region_code, sometime orders had not assign yet",
        channel: "NonNull | order_channel",
        measure: "NonNull | GMV-BEFORE-CANCEL",
        value: "NonNull | "
    }
}
WITH ois AS ( -- actually, it just exclude 36 order, so if you query raw, don't need this, the error is very small, but in agg_general, dataform take all fact_strategic, so I will include it
    -- I just exclude the orders that is contains all test item
    SELECT 
        order_id,
        STRING_AGG(DISTINCT supplier_class) supplier_class
    FROM ${ref(`fact_strategic_sale_order_item_single`)} ois 
    GROUP BY 1
)

