config {
    type: "view",
    description: "PIC: huongdang"
}

main_customer as(
    SELECT *
    FROM ${ref(`dim_customer_profiling`)} dcp
    LEFT JOIN ${ref(`dim_customer`)} cust
    LEFT JOIN ${ref(`dim_fc_service_area`)} area 
    
)







SELECT 
    CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CAST(NULL AS STRING) AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER_ACTIVE' AS measure,
    CAST(NULL AS STRING) AS supplier_class,
    COUNT(distinct IF(active_customer <> 0, customer_id,NULL)) value

FROM ${ref(`dim_customer_profiling`)} dcp 
LEFT JOIN ${ref(`dim_calendar`)} dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5

UNION ALL 

SELECT 
    CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CAST(NULL AS STRING) AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER_NEW' AS measure,
    CAST(NULL AS STRING) AS supplier_class,
    COUNT(distinct IF(new_customer <> 0, customer_id,NULL)) value

FROM ${ref(`dim_customer_profiling`)} dcp 
LEFT JOIN ${ref(`dim_calendar`)} dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5

UNION ALL 

SELECT 
    CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CAST(NULL AS STRING) AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER_REACQUIRED' AS measure,
    CAST(NULL AS STRING) AS supplier_class,
    COUNT(distinct IF(reacquire_customer <> 0, customer_id,NULL)) value

FROM ${ref(`dim_customer_profiling`)} dcp 
LEFT JOIN ${ref(`dim_calendar`)} dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5

UNION ALL 

SELECT 
    CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CAST(NULL AS STRING) AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER_REPEAT' AS measure,
    CAST(NULL AS STRING) AS supplier_class,
    COUNT(distinct IF(repeat_customer <> 0, customer_id,NULL)) value

FROM ${ref(`dim_customer_profiling`)} dcp 
LEFT JOIN ${ref(`dim_calendar`)} dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5