config {
    name: "agg_strategic_customer",
    type: "view",
    description: "PIC: minhluu"
}

SELECT 
    CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CAST(NULL AS STRING) AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER-ACTIVE' AS measure,
    COUNT(distinct IF(active_customer <> 0, customer_id,NULL)) value

FROM ${ref(`dim_customer_profiling`)} dcp 
LEFT JOIN ${ref(`dim_calendar`)} dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5

UNION ALL 

SELECT 
CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CAST(NULL AS STRING) AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER-NEW' AS measure,
    COUNT(distinct IF(new_customer <> 0, customer_id,NULL)) value

FROM ${ref(`dim_customer_profiling`)} dcp 
LEFT JOIN ${ref(`dim_calendar`)} dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5

UNION ALL 

SELECT 
CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CAST(NULL AS STRING) AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER-REACQUIRED' AS measure,
    COUNT(distinct IF(reacquire_customer <> 0, customer_id,NULL)) value

FROM ${ref(`dim_customer_profiling`)} dcp 
LEFT JOIN ${ref(`dim_calendar`)} dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5

UNION ALL 

SELECT 
CURRENT_DATETIME("+7") AS refresh_time,
    dc.eom as date,
    CAST(NULL AS STRING) AS location,
    CAST(NULL AS STRING) AS channel,
    'CUSTOMER-REPEAT' AS measure,
    COUNT(distinct IF(repeat_customer <> 0, customer_id,NULL)) value

FROM ${ref(`dim_customer_profiling`)} dcp 
LEFT JOIN ${ref(`dim_calendar`)} dc ON dcp.som = dc.som 
GROUP BY 1,2,3,4,5