config {
    type: "view",
    name: "agg_strategic_gmv-return",
    description: `PIC: minh.luu, model_type: view
    Source
        ${source.ref}.dim_order_channel
        ${source.ref}.dim_order_sales_region
        ${source.ref}.dim_calendar
        ${source.ref}.fact_strategic_sale_order_item_single`,
    columns: {
        date: "NonNull | End of month",
        location: "Nullable | sales_region_code, sometime orders had not assign yet",
        channel: "NonNull | order_channel",
        measure: "NonNull | GMV-BEFORE-CANCEL",
        value: "NonNull | return amount ,Note: In tender systems, we don't consider orders valid until they are confirmed by the customer, as their confirmation is essential to making the order valuable to actionable. On the other hand, in marketplace, orders become valid upon creation, as our system handles the confirmation process, not the customer."
    }
}
SELECT 
    dc.eom as date,
    CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NOTHERN"
        ELSE "GMV-VN-REGION-UNKNOWN" 
    END AS location,
    CASE
        WHEN doc.order_channel IN ("MARKETPLACE","CONSIGNMENT" ) THEN "MARKETPLACE"
        ELSE doc.order_channel
    END AS channel,
    'GMV-RETURN' AS measure,

    SUM(price * returned_quantity) as value

FROM ${ref(`fact_strategic_sale_order_item_single`)} ois 
LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = ois.order_id 
LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON ois.order_id = dosr.order_id 
LEFT JOIN ${ref(`dim_order_status`)} dos ON dos.order_id = ois.order_id
LEFT JOIN ${ref(`dim_calendar`)} dc ON date(ois.created_dt) = dc.date
WHERE  doc.order_channel NOT IN ("TENDER","CONSIGNMENT-RECOGNITION")
AND doc.order_channel is not null
AND dos.crm_status not like "CANCEL"
GROUP BY 1,2,3,4

UNION ALL 

SELECT 
    dc.eom as date,
    CASE
        WHEN dosr.sales_region_code LIKE "MIENNAM" THEN "SOUTHERN"
        WHEN dosr.sales_region_code LIKE "MIENTRUNG" THEN "CENTRAL"
        WHEN dosr.sales_region_code LIKE "MIENBAC" THEN "NOTHERN"
        ELSE "GMV-VN-REGION-UNKNOWN" 
    END AS location,
    order_channel  as channel,
    'GMV-RETURN' AS measure,
    SUM(price * returned_quantity) as value

FROM ${ref(`fact_strategic_sale_order_item_single`)} ois 
LEFT JOIN ${ref(`dim_order_channel`)} doc ON doc.order_id = ois.order_id 
LEFT JOIN ${ref(`dim_order_sales_region`)} dosr ON ois.order_id = dosr.order_id 
LEFT JOIN ${ref(`dim_order_status`)} dos ON dos.order_id = ois.order_id
LEFT JOIN ${ref(`dim_calendar`)} dc ON date(ois.confirmation_dt) = dc.date
WHERE  doc.order_channel LIKE "TENDER"
AND dos.crm_status not like "WAIT_TO_CONFIRM"
AND dos.crm_status not like "CANCEL"
GROUP BY 1,2,3,4


