config {
    type: 'table',
    description: `Started time: 20240601 | PIC: tu.dang; schhedule: 0h00 daily; model type: table
    Source:
        ${source.silver}.monitoring_prd_collector_user_stats_*`,
    columns: {
        event: `NonNull | IN ("ADD_TO_CART", "SKU_DETAIL_VIEW") `,
        account_id: "NonNull |",
        account_type: "NonNull | IN (SELLER, USER)",
        created_time: "NonNull | Started time: 20240601",
        product_id: "NonNull |",
        province_code: "Nullable |",
        product_status: "Nullable | Null means Unknown ",
        seller_id: "NonNull |",
        has_ever_sold: "Nullable | Null means Unknown", // product has_ever_sold is Null still exists in order_v2_order_item
        screen: "NonNull |",
        source: "NonNull |",
        sku_code: "NonNull |",

    },
    tags: ['0h00']
}

WITH
  stg AS (
  SELECT
    event,
    account_id,
    account_type,
    -- TIMESTAMP_add(TIMESTAMP(created_time), INTERVAL 7 hour) AS created_time,
    created_time,
    JSON_EXTRACT_SCALAR(extra_props, '$.user_metadata.LOCATION') AS province_code,
    JSON_EXTRACT_SCALAR(extra_props, '$.metadata.screen') AS screen,
    JSON_EXTRACT_SCALAR(extra_props, '$.metadata.source') AS SOURCE,
    JSON_EXTRACT_SCALAR(extra_props, '$.numeric_metadata.quantity') AS quantity,
    JSON_EXTRACT_SCALAR(extra_props, '$.metadata.product_id') AS product_id,
    JSON_EXTRACT_SCALAR(extra_props, '$.metadata.seller_id') AS seller_id,
    JSON_EXTRACT_SCALAR(extra_props, '$.metadata.sku') AS sku_code
    -- DENSE_RANK() OVER( PARTITION BY seller_id, DATE(created_time), product_id  ORDER BY created_time ASC ) sequence_id
  FROM
    `${source.silver}.monitoring_prd_collector_user_stats_*`
  WHERE
    _TABLE_SUFFIX BETWEEN '20240601'
    AND FORMAT_DATE('%Y%m%d', CURRENT_DATE())
    AND event IN ( "ADD_TO_CART",
      "SKU_DETAIL_VIEW"))
SELECT
  event,
  account_id,
  account_type,
  created_time,
  province_code,
  screen,
  SOURCE,
  quantity,
  seller_id,
  CAST( product_id AS integer) product_id,
  sku_code,
  DENSE_RANK() OVER(PARTITION BY seller_id, DATE(created_time),
    product_id
  ORDER BY
    created_time ASC ) sequence_id
FROM
  stg

-- post_operations {
--   ALTER TABLE
--     ${self()}
--   ADD FOREIGN KEY
--     (product_id)
--   REFERENCES
--     ${ref(`dim_product`)}(product_id) NOT ENFORCED
--     ,
--   ADD FOREIGN KEY
--     (seller_id)
--   REFERENCES
--     ${ref(`dim_supplier`)}(supplier_id) NOT ENFORCED
-- }
