config {
    type: 'incremental',
    name: "fact_user_event_tracking",
    description: `Started time: 20240601 | PIC: tu.dang; schhedule: 0h00 daily; model type: table
    Source:
        ${source.silver}.monitoring_prd_collector_user_stats_*`,
    columns: {
        event: `NonNull | IN ("ADD_TO_CART", "SKU_DETAIL_VIEW","CHECKOUT","SKU_IMPRESSION") `,
        customer_id: " NonNull | The unique identifier for the customer",
        created_time: "NonNull | The datetime when the event was created, adjusted to the 'Asia/Ho_Chi_Minh' timezone",
        product_id: "Nullable |",
        province_code: "Nullable | " + docs.province_code,
        screen: "Nullable | The screen on which the event occurred. This provides additional context on the user interface interaction",
        source: "Nullable | The source of the event, indicating how the item was created",
        sku_code: "NonNull"| docs.sku,
        is_sku_customer_first_interaction_in_30_days: "NonNull | A boolean indicating whether this is the customer's first interaction with the SKU in the past 30 days. It's determined by checking if there are any previous interactions with the same customer_id, sku_code, and event within 30 days before the current created_time.",

    },
    tags: ['0h00'],
    bigquery: {
        partitionBy: "date(created_time)",
        clusterBy: ["event", "customer_id"]

    },
}

WITH
  stg AS (
  SELECT
    event,
    customer_id,
    -- TIMESTAMP_add(TIMESTAMP(created_time), INTERVAL 7 hour) AS created_time,
    created_time,
    JSON_EXTRACT_SCALAR(extra_props, '$.user_metadata.LOCATION') AS province_code,
    JSON_EXTRACT_SCALAR(extra_props, '$.metadata.screen') AS screen,
    JSON_EXTRACT_SCALAR(extra_props, '$.metadata.source') AS SOURCE,
    JSON_EXTRACT_SCALAR(extra_props, '$.metadata.product_id') AS product_id,
    JSON_EXTRACT_SCALAR(extra_props, '$.metadata.seller_id') AS seller_id,
    JSON_EXTRACT_SCALAR(extra_props, '$.metadata.sku') AS sku_code,
    JSON_EXTRACT_SCALAR(extra_props, '$.ua_metadata.CLIENT') AS client,    
    JSON_EXTRACT_SCALAR(extra_props, '$.ua_metadata.PLATFORM') AS platform,
    JSON_EXTRACT_SCALAR(extra_props, '$.metadata.host') AS host
    -- DENSE_RANK() OVER( PARTITION BY seller_id, DATE(created_time), product_id  ORDER BY created_time ASC ) sequence_id
  FROM
    `${source.silver}.monitoring_prd_collector_user_stats_*`
  WHERE
    _TABLE_SUFFIX BETWEEN '20240601'
    AND FORMAT_DATE('%Y%m%d', CURRENT_DATE())
    AND event IN ( "ADD_TO_CART",
      "SKU_DETAIL_VIEW","CHECKOUT","SKU_IMPRESSION"))
SELECT
  event,
  customer_id,
  DATETIME(created_time, "Asia/Ho_Chi_Minh") AS created_time,
  -- date(created_time, "Asia/Ho_Chi_Minh") AS created_date,
  province_code,
  screen,
  SOURCE,
  client,
  platform,
  host,
  seller_id,
  product_id,
  sku_code,
   case when STRPOS(sku_code,".") > 0 then  LEFT(sku_code,STRPOS(sku_code,".")-1)
 else sku_code end as seller_code,
  -- DENSE_RANK() OVER(PARTITION BY seller_id, DATE(created_time),  product_id  ORDER BY  created_time ASC ) sequence_id,
  CASE
    WHEN EXISTS (
      SELECT 1
      FROM stg AS sub
      WHERE sub.customer_id = stg.customer_id
        AND sub.sku_code = stg.sku_code
        AND sub.event = stg.event
        AND sub.created_time BETWEEN
          DATETIME_SUB(stg.created_time, INTERVAL 30 DAY)
          AND stg.created_time
        AND sub.created_time != stg.created_time
    ) THEN FALSE
    ELSE TRUE
  END AS is_sku_customer_first_interaction_in_30_days,
    CASE
    WHEN EXISTS (
      SELECT 1
      FROM stg AS sub
      WHERE sub.customer_id = stg.customer_id
        AND sub.sku_code = stg.sku_code
        AND sub.event = stg.event
        AND sub.created_time BETWEEN
          DATETIME_SUB(stg.created_time, INTERVAL 60 DAY)
          AND stg.created_time
        AND sub.created_time != stg.created_time
    ) THEN FALSE
    ELSE TRUE
  END AS is_sku_customer_first_interaction_in_60_days		
FROM
  stg

-- post_operations {
--   ALTER TABLE
--     ${self()}
--   ADD FOREIGN KEY
--     (product_id)
--   REFERENCES
--     ${ref(`dim_product`)}(product_id) NOT ENFORCED
--     ,
--   ADD FOREIGN KEY
--     (seller_id)
--   REFERENCES
--     ${ref(`dim_supplier`)}(supplier_id) NOT ENFORCED
-- }
