config {
    type: 'table',
    name: "fact_user_search_event",
    description: `Started time: 20240601 | PIC: tu.dang; schedule: 0h00 daily; model type: table
    Source:
        ${source.silver}.monitoring_prd_collector_user_stats_*`,
    columns: {
        event: `NonNull | In all Customer Search Action`,
        customer_id: "NonNull | The unique identifier for the customer",
        created_time: "NonNull | The datetime when the event was created, adjusted to the 'Asia/Ho_Chi_Minh' timezone",
        product_id: "NonNull | Unique identifier for each product",
        province_code: "Nullable | " + docs.province_code,
        /*screen: "Nullable | The screen on which the event occurred. This provides additional context on the user interface interaction",
        source: "Nullable | The source of the event, indicating how the item was created",*/
        sku_code: "NonNull" | docs.sku,
        is_sku_customer_first_interaction_in_30_days: "NonNull | A boolean indicating whether this is the customer's first interaction with the SKU in the past 30 days. It's determined by checking if there are any previous interactions with the same customer_id, sku_code, and event within 30 days before the current created_time.",
    },
    /* tags: ['2h00'],*/
    bigquery: {
        partitionBy: "date(created_time)",
        clusterBy: ["event", "customer_id"]
    },
}

WITH stg AS (
    SELECT
        event,
        customer_id,
        created_time,
        JSON_EXTRACT_SCALAR(extra_props, '$.user_metadata.LOCATION') AS province_code,
        -- JSON_EXTRACT_SCALAR(extra_props, '$.metadata.screen') AS screen,
        -- JSON_EXTRACT_SCALAR(extra_props, '$.metadata.source') AS source,
        JSON_EXTRACT_SCALAR(extra_props, '$.metadata.content') AS search_content,
        JSON_EXTRACT_SCALAR(extra_props, '$.metadata.status') AS search_status,
        -- JSON_EXTRACT_SCALAR(extra_props, '$.metadata.sku') AS sku_code,
        JSON_EXTRACT_SCALAR(extra_props, '$.ua_metadata.CLIENT') AS client,    
        JSON_EXTRACT_SCALAR(extra_props, '$.ua_metadata.PLATFORM') AS platform,
        JSON_EXTRACT_SCALAR(extra_props, '$.metadata.host') AS host,
        ingest_time
    FROM
    `${source.silver}.monitoring_prd_collector_user_stats_*`
  WHERE
    _TABLE_SUFFIX BETWEEN '20240701'
    AND FORMAT_DATE('%Y%m%d', CURRENT_DATE())
    -- AND event IN ( "SEARCH") 
    )
SELECT
    event,
    customer_id,
    DATETIME(created_time, "Asia/Ho_Chi_Minh") AS created_time,
    province_code,
    -- screen,
    -- source,
    client,
    platform,
    host,
    search_content,
    search_status,
    LEAD(event) over(order by created_time) as next_action
FROM
    stg
where customer_id >0 AND event IN ( "SEARCH") 





