config {
    type: 'table',
    name: "fact_user_journey",
    description: `Started time: 20240801 | PIC: tu.dang; schedule: 0h00 daily; model type: table
    Source:
        ${source.silver}.monitoring_prd_collector_user_stats_*`,
    columns: {
        event: `NonNull | Customer Events IN ( "ADD_TO_CART","SKU_DETAIL_VIEW","SKU_IMPRESSION") `,
        customer_id: "NonNull | The unique identifier for the customer",
        created_time: "NonNull | The datetime when the event was created, adjusted to the 'Asia/Ho_Chi_Minh' timezone",
        province_code: "Nullable | " + docs.province_code,
        screen: "Nullable | The screen on which the event occurred. This provides additional context on the user interface interaction",
        source: "Nullable | The source of the event, indicating how the item was created",
            },
    tags: ['0h00'],
    bigquery: {
        partitionBy: "date(created_time)",
        clusterBy: ["event", "customer_id"]
    },
}



WITH stg AS (
    SELECT
mg_id,
        event,
        customer_id,
        created_time,
--         JSON_EXTRACT_SCALAR(extra_props, '$.user_metadata.LOCATION') AS province_code,
        JSON_EXTRACT_SCALAR(extra_props, '$.metadata.screen') AS screen,
        JSON_EXTRACT_SCALAR(extra_props, '$.metadata.source') AS source,
--         JSON_EXTRACT_SCALAR(extra_props, '$.metadata.content') AS search_content,
--         JSON_EXTRACT_SCALAR(extra_props, '$.metadata.status') AS search_status,
--         JSON_EXTRACT_SCALAR(extra_props, '$.metadata.sku') AS sku_code,
--         JSON_EXTRACT_SCALAR(extra_props, '$.ua_metadata.CLIENT') AS client,
        JSON_EXTRACT_SCALAR(extra_props, '$.ua_metadata.PLATFORM') AS platform,
        JSON_EXTRACT_SCALAR(extra_props, '$.client_user_time') AS client_user_time
    FROM
    `silver_buymed_vn.monitoring_prd_collector_user_stats_*`
  WHERE
    _TABLE_SUFFIX BETWEEN '20240801'
    AND FORMAT_DATE('%Y%m%d', CURRENT_DATE())
--     AND event IN ( "SEARCH")
    )
SELECT mg_id,
--      distinct event
    event,
    customer_id,
    DATETIME(created_time, "Asia/Ho_Chi_Minh") AS created_time,
    DATE(created_time, "Asia/Ho_Chi_Minh") AS created_date,
    screen,
    source,
    client_user_time,
    platform,
    LEAD(event) over (partition by customer_id order by created_time) next_act_1,
    LEAD(event,2) over (partition by customer_id order by created_time) next_act_2,
    LEAD(event,3) over (partition by customer_id order by created_time) next_act_3,
    LEAD(event,4) over (partition by customer_id order by created_time) next_act_4
FROM
    stg
where customer_id >0