config {
    type: "table", 
    description: 
        `
        Crawled Price of Competitors;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.platinum}.marketplace_prd_product_v2_product_market_price
        `,
    tags: ["custom_1h_past10", "PRICING"]
}

SELECT
    TIMESTAMP_ADD(a.created_time, INTERVAL 7 HOUR) AS crawled_at
    , TIMESTAMP_ADD(a.last_updated_time, INTERVAL 7 HOUR) AS last_updated_time
    , JSON_VALUE(a.extra_props, '$.source') AS competitor
    , JSON_VALUE(a.extra_props, '$.market_name') AS competitor_product_name
    , SAFE_CAST(JSON_VALUE(a.extra_props, '$.market_price') AS INT64) AS competitor_price
    , SAFE_CAST(JSON_VALUE(a.extra_props, '$.product_id') AS INT64) AS product_id
    , IF(
        LOWER(JSON_VALUE(a.extra_props, '$.market_data.unit')) IN ('', "null")
        , null
        , LOWER(JSON_VALUE(a.extra_props, '$.market_data.unit'))
      ) AS competitor_unit
    , IFNULL(SAFE_CAST(JSON_VALUE(a.extra_props, '$.is_checked') AS BOOL), FALSE) AS is_checked
    , IFNULL(SAFE_CAST(JSON_VALUE(a.extra_props, '$.is_checked_manual') AS BOOL), FALSE) AS is_verified
    , IFNULL(JSON_VALUE(a.extra_props, '$.qc'), "NOT_QC_YET") AS qc
    , SAFE_CAST(JSON_VALUE(a.extra_props, '$.conversion_rate') AS FLOAT64) AS conversion_rate
    , SAFE_CAST(JSON_VALUE(a.extra_props, '$.market_price') AS INT64) * SAFE_CAST(JSON_VALUE(a.extra_props, '$.conversion_rate') AS FLOAT64) AS market_price_aft_convert
    , JSON_VALUE(a.extra_props, '$.province_code') AS province_code
FROM ${source.platinum}.marketplace_prd_product_v2_product_market_price AS a
    LEFT JOIN ${source.platinum}.marketplace_prd_product_v2_market_price_source AS b 
        ON LOWER(JSON_VALUE(a.extra_props, '$.source')) = LOWER(b.source)
WHERE 
    JSON_VALUE(a.extra_props, '$.source') IS NOT NULL
    -- AND a.created_date >= DATE_SUB(CURRENT_DATE("+7"), INTERVAL 7 DAY)
    -- AND b.is_active
    -- AND JSON_VALUE(a.extra_props, '$.is_active') = "true"
QUALIFY ROW_NUMBER() over (PARTITION BY product_id, competitor ORDER BY market_price_aft_convert DESC, last_updated_time DESC) = 1