config {
    type: "table", 
    description: 
        `
        Crawled Price of Competitors;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.platinum}.marketplace_prd_product_v2_product_market_price
        `,
    tags: ["custom_1h_past5", "PRICING"]
}

SELECT
    TIMESTAMP_ADD(created_time, INTERVAL 7 HOUR) AS crawled_at
    , JSON_VALUE(extra_props, '$.source') AS competitor
    , JSON_VALUE(extra_props, '$.market_name') AS competitor_product_name
    , SAFE_CAST(JSON_VALUE(extra_props, '$.market_price') AS INT64) AS competitor_price
    , SAFE_CAST(JSON_VALUE(extra_props, '$.product_id') AS INT64) AS product_id
    , NULLIF(
        LOWER(JSON_VALUE(extra_props, '$.market_data.unit'))
        , ''
      ) AS competitor_unit
    , IFNULL(SAFE_CAST(JSON_VALUE(extra_props, '$.is_checked') AS BOOL), FALSE) AS is_checked
    , SAFE_CAST(JSON_VALUE(extra_props, '$.conversion_rate') AS INT64) AS conversion_rate
    , SAFE_CAST(JSON_VALUE(extra_props, '$.market_price') AS INT64) * SAFE_CAST(JSON_VALUE(extra_props, '$.conversion_rate') AS INT64) AS market_price_aft_convert
FROM ${source.platinum}.marketplace_prd_product_v2_product_market_price
WHERE 
    JSON_VALUE(extra_props, '$.source') IS NOT NULL
    AND created_date >= DATE_SUB(CURRENT_DATE("+7"), INTERVAL 7 DAY)
    AND LOWER(JSON_VALUE(extra_props, '$.source')) <> 'trungtamthuoc'
QUALIFY ROW_NUMBER() over (PARTITION BY product_id, competitor, competitor_unit, is_checked ORDER BY crawled_at DESC) = 1