config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "marketplace_prd_promotion_gamification_leaderboard",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","marketplace_prd_promotion"]
}
 
  WITH silver AS (
    SELECT
      key,mg_id,account_id,lucky_wheel_code,customer_id,customer_phone,gamification_id,number_of_mission_completed,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN silver_buymed_vn.MONGOID_TIMESTAMP(mg_id) IS NOT NULL THEN DATE(DATETIME(silver_buymed_vn.MONGOID_TIMESTAMP(mg_id), 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.marketplace_prd_promotion_gamification_leaderboard
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND FIRST_VALUE(action) OVER(_window) != "d"
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          )
  ), platinum AS (
    SELECT 
      key,mg_id,account_id,lucky_wheel_code,customer_id,customer_phone,gamification_id,number_of_mission_completed,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `marketplace_prd_promotion_gamification_leaderboard`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  