
config {
  type: "view",
  schema: "platinum_buymed_vn",
  name: "marketplace_prd_product_v2_qc_product_market_price",
  description : `
  Partition by: created date
  Cluster by: source, product_id, qc
  `,
  tags:["platinum","marketplace_prd_product_v2_qc_product_market_price"]
}

WITH silver AS (
  SELECT
    key, mg_id, province_code, region_code, unit, conversion_rate, is_active, is_approved_crawl_description, product_id, origin_price, source, market_data, is_source_un_active, qc, last_updated_time, code, market_name, note, created_time, market_price, is_approved_crawl_image, synced_at, extra_props, action, ingest_time,
    CASE
      WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
      ELSE DATE('2099-01-01')
    END created_date,
    CAST(NULL AS DATETIME) AS platinum_refresh
  FROM silver_buymed_vn.marketplace_prd_product_v2_qc_product_market_price
  WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
  QUALIFY ROW_NUMBER() OVER (_window) = 1
    AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
  WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
      IF(action='d',3, IF(action='u',2,1)) DESC,
      last_updated_time DESC
  )
),

platinum AS (
  SELECT
    key, mg_id, province_code, region_code, unit, conversion_rate, is_active, is_approved_crawl_description, product_id, origin_price, source, market_data, is_source_un_active, qc, last_updated_time, code, market_name, note, created_time, market_price, is_approved_crawl_image, synced_at, extra_props, action, ingest_time,
    created_date,
    platinum_refresh
  FROM ${ref(`platinum_buymed_vn__stg`, `marketplace_prd_product_v2_qc_product_market_price`)}
)

SELECT p.*
FROM platinum p
LEFT JOIN silver s
  ON p.mg_id = s.mg_id
WHERE s.mg_id IS NULL

UNION ALL

SELECT s.*
FROM silver s
WHERE action <> "d"
