config {
    type:"view",
    schema: "platinum_buymed_vn",
    name: "marketplace_prd_pricing_v2_fee_config",
    description : `
    PIC: minh.luu
    `,
    tags:["platinum","marketplace_prd_pricing-v2"]
}

SELECT
 *,
 CASE 
    WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
    ELSE "2099-01-01"
  END AS created_date
FROM ${source.silver}.marketplace_prd_pricing_v2_fee_config o 
 QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)