config {
    type: "view",
    name: "dedup_warehouse_prd_picking_pick_ticket_item",
}

with cte_date as (
	select CAST(date_trunc(date_sub(current_date(),interval 2 month), month) as timestamp) as date_scan
	, CAST(date_trunc(date_sub(current_date(),interval 6 month), month) as timestamp) as date_scan_2
	, CAST(current_date() as timestamp) as current_date_,
)

SELECT
  *
FROM
  lakehouse-prod-394907.silver_buymed_vn.warehouse_prd_picking_pick_ticket_item o 
WHERE ingest_time > (select date_scan from cte_date)
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)