config {
    type: "view",
    name: "dedup_warehouse_prd_picking_pick_ticket_item",
}


SELECT
  *
FROM
  lakehouse-prod-394907.silver_buymed_vn.warehouse_prd_picking_pick_ticket_item o 
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)