config {
    type: "incremental",
    name: "staging_marketplace_prd_order_v2_order",
    bigquery: {
        partitionBy: "DATE(created_time)",
        clusterBy: ["mg_id"]
    }
}


SELECT
 key, 
  mg_id,
  order_id,
  status,
  SAFE_CAST( FORMAT_TIMESTAMP("%Y%m%d%H", o.created_time ) AS INT64 ) AS created_timekey,
  warehouse_code,
  source,
  created_time,
  customer_order_index,
  total_quantity,
  customer_phone,
  customer_id,
  customer_email,
  customer_shipping_address,
  customer_district_code,
  customer_province_code,
  customer_ward_code,
  ward_code,
  district_code,
  province_code,
  extra_fee,
  price,
  total_item,
  total_fee,
  total_price,
  delivery_date,
  redeem_code,
  redeem_apply_result,
  last_updated_time,
  confirmation_date,
  sale_order_code,
  is_split_delivery_order,
  sale_order_status,
  cod,
  notional_price,
  total_notional_price,
  payment_discount,
  payment_method,
  has_deal,
  voucher_discount,
  delivery_method,
  delivered_time,
  extra_props,
  tags, 
  customer_name,
  created_by_account_id,
  invoice,
  outbound_date,
  total_discount,
  system_display,
  source_detail,
  payment_method_percentage,
  ingest_time,
  synced_at,
  action
FROM
  lakehouse-prod-394907.silver_buymed_vn.marketplace_prd_order_v2_order o 
  ${ when(incremental(), `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()})`)}
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)



post_operations {
  ${
    when(incremental(),
      `
     delete
FROM ${self()} where (DATE(ingest_time), mg_id, key) in(
         SELECT
            (DATE(ingest_time), mg_id, key)
         FROM
             ${self()}
         QUALIFY ROW_NUMBER() OVER(_window) > 1
             or FIRST_VALUE(action) OVER(_window) = "d"
         WINDOW
             _window AS (
                     PARTITION
                         BY
                         mg_id
                     ORDER
                         BY
                         synced_at
                         DESC,
                         IF(action='d',3,IF(action='u',2,1)) DESC, last_updated_time DESC))
      `,
      ``
    )
  }
}