config {
    type: "incremental",
    name: "staging_accounting_prd_core_bill",
   
}


SELECT
  order_id,
sale_order_code,
status ,
order_amount ,
vat ,
total_order_amount,
received_amount,
remain_amount,
actual_amount,
created_time,
last_updated_time,
customer_id,
key,
ingest_time,
mg_id,
synced_at,
action
FROM
  lakehouse-prod-394907.silver_buymed_vn.accounting_prd_core_bill o 
  ${ when(incremental(), `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()})`)}
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)



post_operations {
  ${
    when(incremental(),
      `
     delete
FROM ${self()} where (DATE(ingest_time), mg_id, key) in(
         SELECT
            (DATE(ingest_time), mg_id, key)
         FROM
             ${self()}
         QUALIFY ROW_NUMBER() OVER(_window) > 1
             or FIRST_VALUE(action) OVER(_window) = "d"
         WINDOW
             _window AS (
                     PARTITION
                         BY
                         mg_id
                     ORDER
                         BY
                         synced_at
                         DESC,
                         IF(action='d',3,IF(action='u',2,1)) DESC, last_updated_time DESC))
      `,
      ``
    )
  }
}