config {
    type: "incremental",
    name: "staging_marketplace_prd_order_v2_order_item",
    bigquery: {
        partitionBy: "DATE(created_time)",
        clusterBy: ["mg_id"]
    }
}


SELECT
 *
FROM
  lakehouse-prod-394907.silver_buymed_vn.marketplace_prd_order_v2_order_item o 
  ${ when(incremental(), 
    `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()})`,
    `WHERE ingest_time > TIMESTAMP(CURRENT_DATE() - interval 13 MONTH)`
   )}
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)



post_operations {
  ${
    when(incremental(),
      `
     delete
FROM ${self()} where (DATE(ingest_time), mg_id, key) in(
         SELECT
            (DATE(ingest_time), mg_id, key)
         FROM
             ${self()}
         QUALIFY ROW_NUMBER() OVER(_window) > 1
             or FIRST_VALUE(action) OVER(_window) = "d"
         WINDOW
             _window AS (
                     PARTITION
                         BY
                         mg_id
                     ORDER
                         BY
                         synced_at
                         DESC,
                         IF(action='d',3,IF(action='u',2,1)) DESC, last_updated_time DESC))
--where DATE_TRUNC(created_time, DAY) = '2024-01-10' order by mg_id
      `,
      ``
    )
  }
}