config {
    type: "incremental",
    name: "staging_marketplace_prd_order_v2_order_item",
    bigquery: {
        partitionBy: "DATE(created_time)",
        clusterBy: ["mg_id"]
    }
}


SELECT
 *
FROM
  lakehouse-prod-394907.silver_buymed_vn.marketplace_prd_order_v2_order_item o 
  ${ when(incremental(), 
    `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()})`,
    `WHERE ingest_time > TIMESTAMP(CURRENT_DATE() - interval 13 MONTH)`
   )}
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)

post_operations {
  ${
    when(incremental(),
      `
      -- Create a temporary table for rows to delete
      CREATE OR REPLACE TEMP TABLE rows_to_delete AS
      SELECT
        DATE(created_time) AS created_date,
        mg_id,
        key
      FROM ${self()}
      QUALIFY ROW_NUMBER() OVER (_window) > 1
        OR FIRST_VALUE(action) OVER (_window) = "d"
      WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC,
        IF(action = 'd', 3, IF(action = 'u', 2, 1)) DESC,
        last_updated_time DESC
      );

      -- Delete rows using the temporary table
      DELETE FROM ${self()}
      WHERE (DATE(created_time), mg_id, key) IN (
        SELECT (created_date, mg_id, key) FROM rows_to_delete
      );
      `,
      ``
    )
  }
}