config {
    type: "table",
    name: "platform_billing_prd_storage_invoice_data_raw",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id'
    },
    bigquery: {
        partitionBy: "created_date"
    },
    description: `
        Ngày tháng năm: metadata "$.version"
        Ký hiệu: data "\$.template_code" Hoặc data "\$.data.invoice_series"
        Số: "invoice_number" hoặc data "\$.invoice_number" hoặc metadata "\$.invoice_number" hoặc object_code

        Vendor Side:
        tên vendor: data "\$.vendor_legal_name", "\$.paticipants\[0\].name"
        mã số thuế: data "\$.tax_number" , metadata "\$.vendorTaxCode"
        Địa chỉ: data "\$.paticipants\[0\].address"
        Điện thoại: Chưa kiếm

        Số tài khoản: Không có
            
        Buyer Side:
        tên đơn vị: data "\$.buyer_legal_name", "\$.participants\[1\].name"
        mã số thuế: data "$.participants\[1\].tax_number"
        Địa chỉ: data "\$.participants\[1\].address"

        Hình thức thanh toán: data "\$.payment_method"

        Phần items:
        STT: Không có
        Tên hàng hóa, dịch vụ: data "\$items\[0\].item_name"
        Số lô: data  "\$items\[0\].lot"
        Hạn sử dụng: data "$items\[0\].exp_date"
        ĐVT: data "$items\[0\].unit"
        Số lượng: data  "$items\[0\].quantity"
        Đơn giá: data "$items\[0\].price"
        Thành tiền: Không có
        Thuế GTGT theo % : data "items$\[0\].vat"
        Thuế GTGT: data "items$\[0\].vat_price"

        Phần tổng hợp theo thuế: data "$.tax_info"

        Tổng cộng thành tiền trước thuế GTGT: data "$.total_price"
        Tổng cộng tiền thuế GTGT : không có
        Tổng cộng tiền thanh toán : data "$.total_price_without_vat"
    `,
    tags:["platform_billing_prd_storage","custom_1h_past5"]
}


SELECT
 *, DATE(DATETIME(created_time) + INTERVAL 7 HOUR) AS created_date
FROM ${source.silver}.platform_billing_prd_storage_invoice_data_raw o 

  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)
