config {
    type: "view",
    name: "platform_billing_prd_payment_payment_item",
    schema: "platinum_buymed_vn_restricted",
    tags: ['platform_accounting_prd_reconcile'],
    description: `
    PIC: minh.luu
    Internal internal.thuocsi.vn/internal-seller/MEDX/PUR_HCM/payment

    partitionBy: "created_date"
    clusterBy: ["payment_code","object_code","object_type"]
    `
}
  WITH silver AS (
    SELECT
      key,mg_id,object_type,object_code,amount,note,created_time,last_updated_time,payment_code,payment_item_code,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn_restricted.platform_billing_prd_payment_payment_item
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,object_type,object_code,amount,note,created_time,last_updated_time,payment_code,payment_item_code,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn_restricted__stg`, `platform_billing_prd_payment_payment_item`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"