config {
    type: "view",
    name: "platform_billing_prd_invoice_v2_invoice_item",
    schema: "platinum_buymed_vn_restricted",
    tags: ['platform_billing_prd_invoice-v2'],
    description: `
    PIC: minh.luu
    Tech PIC: Thiện Bùi, Hoàng Hồ
    Internal Site: accounting.buymed.com/invoice/detail

    partitionBy: "created_date"
    `
}
  WITH silver AS (
    SELECT
      key,mg_id,invoice_code,orderItemType,last_updated_time,unit,vat_amount,created_time,price_without_vat,lot,amount_without_vat,amount,order_id,sku_code,product_id,productName,original_export_info,expiry_date,vat,outbound_infos,product_code,quantity,price,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn_restricted.platform_billing_prd_invoice_v2_invoice_item
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,invoice_code,orderItemType,last_updated_time,unit,vat_amount,created_time,price_without_vat,lot,amount_without_vat,amount,order_id,sku_code,product_id,productName,original_export_info,expiry_date,vat,outbound_infos,product_code,quantity,price,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn_restricted__stg`, `platform_billing_prd_invoice_v2_invoice_item`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"