config {
    type: "view",
    name: "platform_billing_prd_storage_invoice_data_raw",
    schema: "platinum_buymed_vn",
    description: `
    PIC: minh.luu
    Partition by: created_date
    
        Ngày tháng năm: metadata "$.version"
        Ký hiệu: data "\$.template_code" Hoặc data "\$.data.invoice_series"
        Số: "invoice_number" hoặc data "\$.invoice_number" hoặc metadata "\$.invoice_number" hoặc object_code

        Vendor Side:
        tên vendor: data "\$.vendor_legal_name", "\$.paticipants\[0\].name"
        mã số thuế: data "\$.tax_number" , metadata "\$.vendorTaxCode"
        Địa chỉ: data "\$.paticipants\[0\].address"
        Điện thoại: Chưa kiếm

        Số tài khoản: Không có
            
        Buyer Side:
        tên đơn vị: data "\$.buyer_legal_name", "\$.participants\[1\].name"
        mã số thuế: data "$.participants\[1\].tax_number"
        Địa chỉ: data "\$.participants\[1\].address"

        Hình thức thanh toán: data "\$.payment_method"

        Phần items:
        STT: Không có
        Tên hàng hóa, dịch vụ: data "\$items\[0\].item_name"
        Số lô: data  "\$items\[0\].lot"
        Hạn sử dụng: data "$items\[0\].exp_date"
        ĐVT: data "$items\[0\].unit"
        Số lượng: data  "$items\[0\].quantity"
        Đơn giá: data "$items\[0\].price"
        Thành tiền: Không có
        Thuế GTGT theo % : data "items$\[0\].vat"
        Thuế GTGT: data "items$\[0\].vat_price"

        Phần tổng hợp theo thuế: data "$.tax_info"

        Tổng cộng thành tiền trước thuế GTGT: data "$.total_price"
        Tổng cộng tiền thuế GTGT : không có
        Tổng cộng tiền thanh toán : data "$.total_price_without_vat"
    `,
    tags:["platform_billing_prd_storage","custom_1h_past5"]
}

  WITH silver AS (
    SELECT
      key,mg_id,group_entity_code,ref_type,object_type,invoice_number,data,metadata,invoice_data_id,attachment,entity_type,object_code,ref_code,created_time,last_updated_time,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.platform_billing_prd_storage_invoice_data_raw
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,group_entity_code,ref_type,object_type,invoice_number,data,metadata,invoice_data_id,attachment,entity_type,object_code,ref_code,created_time,last_updated_time,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `platform_billing_prd_storage_invoice_data_raw`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"