config {
    type: "view",
    name: "platform_billing_prd_storage_THUOCSIVN_VENDOR_invoice_object",
    schema: `platinum_buymed_vn`,
    description: `
    PIC: minhLuu 
    Partition by: created_date
    `,
    tags: ["platform_billing_prd_storage"]
}

  WITH silver AS (
    SELECT
      key,mg_id,group_entity_code,ref_type,object_type,invoice_number,data,metadata,invoice_data_id,attachment,entity_type,object_code,ref_code,created_time,last_updated_time,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.platform_billing_prd_storage_invoice_data_raw
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,group_entity_code,ref_type,object_type,invoice_number,data,metadata,invoice_data_id,attachment,entity_type,object_code,ref_code,created_time,last_updated_time,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `platform_billing_prd_storage_invoice_data_raw`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  