-- If user change order more than 5 minutes, incremental model will duplicate that order cause this model just
  -- append row, not update it
  -- so that I will remove order that created about 45 minute ago, then add the new one, also the new changed order;

WITH dedup_order_tbl as (
    select mg_id,synced_at,last_updated_time,
        
    order_id, 
    DATETIME(created_time, 'Asia/Ho_Chi_Minh') as created_time, 
    customer_id,
    CASE
        WHEN ward_code IS NOT NULL THEN ward_code
        WHEN district_code IS NOT NULL THEN district_code
        WHEN province_code IS NOT NULL THEN province_code
        WHEN region_code IS NOT NULL THEN region_code
        ELSE NULL
    END AS location_code,
    CASE
        WHEN customer_ward_code IS NOT NULL THEN customer_ward_code
        WHEN customer_district_code IS NOT NULL THEN customer_district_code
        WHEN customer_province_code IS NOT NULL THEN customer_province_code
        WHEN customer_region_code IS NOT NULL THEN customer_region_code
        ELSE NULL
    END AS customer_location_code
     
    from lakehouse-prod-394907.silver_buymed_vn.marketplace_prd_order_v2_order 
    where ingest_time >  TIMESTAMP_SECONDS(0)  
    QUALIFY ROW_NUMBER() OVER(_window) = 1 AND FIRST_VALUE(action) over(_window) <> 'd'
    WINDOW _window AS (PARTITION BY mg_id ORDER BY synced_at DESC, IF(action='d',3,IF(action='u',2,1)) DESC
    , last_updated_time DESC)
  )

SELECT 
    order_id,
    max(created_time) created_time,
    ARRAY_AGG( customer_id ORDER BY created_time DESC)[0] AS customer_id,
    ARRAY_AGG( location_code ORDER BY created_time DESC)[0] AS location_code ,
    ARRAY_AGG( customer_location_code ORDER BY created_time DESC)[0] AS customer_location_code 
FROM
    dedup_order_tbl

GROUP BY
    order_id;

