config {
    type:"operations",
    tags: ["AI_THUOCSI_TH"]
}

-- fact_order_item

CREATE OR REPLACE VIEW `rumi_buymed_th.thuocsi_tha_fact_order_item`
AS (SELECT * FROM  ${ref("buymed_innovation", "thuocsi_tha_fact_order_item")});

-- fact_order_voucher

CREATE OR REPLACE VIEW `rumi_buymed_th.thuocsi_tha_fact_order_voucher`
AS (SELECT * FROM  ${ref("buymed_innovation", "thuocsi_tha_fact_order_voucher")});


-- fact_margin

CREATE OR REPLACE VIEW `rumi_buymed_th.thuocsi_tha_fact_margin`
AS (SELECT * FROM  ${ref("buymed_innovation", "thuocsi_tha_fact_margin")});

-- fact_inbound_ticket

CREATE OR REPLACE VIEW `rumi_buymed_th.thuocsi_tha_fact_inbound_ticket`
AS (SELECT * FROM  ${ref("buymed_innovation", "thuocsi_tha_fact_inbound_ticket")});

-- fact_inventory_historical

CREATE OR REPLACE VIEW `rumi_buymed_th.thuocsi_tha_fact_inventory_historical`
AS (SELECT * FROM  ${ref("buymed_innovation", "thuocsi_tha_fact_inventory_historical")});

-- dim_customer

CREATE OR REPLACE VIEW `rumi_buymed_th.thuocsi_tha_dim_customer`
AS (SELECT * FROM  ${ref("buymed_innovation", "thuocsi_tha_dim_customer")});

-- dim_product_sku

CREATE OR REPLACE VIEW `rumi_buymed_th.thuocsi_tha_dim_product_sku`
AS (SELECT * FROM  ${ref("buymed_innovation", "thuocsi_tha_dim_product_sku")});

-- dim_inventory

CREATE OR REPLACE VIEW `rumi_buymed_th.thuocsi_tha_dim_inventory`
AS (SELECT * FROM  ${ref("buymed_innovation", "thuocsi_tha_dim_inventory")});

-- dim_initial_stock_draft

CREATE OR REPLACE VIEW `rumi_buymed_th.thuocsi_tha_dim_initial_stock_draft`
AS (SELECT * FROM  ${ref("buymed_innovation", "thuocsi_tha_dim_initial_stock_draft")});



