config {
    type: 'view',
    schema: "buymed_innovation",
    description: `All orders item in the Thailand marketplace.`,
    tags: ['AI_THUOCSI_TH']
}

WITH
    fact_order AS ( 
        SELECT
            created_date
            , DATETIME(created_time, "+7") AS created_time
            , DATETIME(a.delivered_time, "+7") AS delivered_time
            , order_id
            , customer_id
            , price AS gmv
            , status
            , sale_order_code
        FROM platinum_buymed_th.marketplace_prd_order_v2_order AS a
        WHERE 1=1
            AND created_date >= DATE_TRUNC(CURRENT_DATE("+7"), MONTH ) - INTERVAL 2 MONTH
    ),

    delivery AS (
        SELECT
            reference_code
            , MIN(DATETIME(TIMESTAMP_SECONDS(NULLIF(delivered_time,0)), "+7")) AS delivered_time
        FROM platinum_buymed_th.delivery_prd_transporting_shipping_order AS a
        WHERE 1=1
            AND created_date >= DATE_TRUNC(CURRENT_DATE("+7"), MONTH ) - INTERVAL 2 MONTH
            AND type = "DELIVERY"
        GROUP BY 1
    )

SELECT
    a.created_date
    , DATETIME(a.created_time, "+7") AS created_time
    , COALESCE(d.delivered_time, o.delivered_time) AS delivered_time
    , a.order_id
    , a.product_id
    , a.total_price
    , a.price * a.outbound_quantity AS total_outbound
    , s.seller_class
    , o.customer_id
    , o.status AS order_status
FROM platinum_buymed_th.marketplace_prd_order_v2_order_item AS a
    LEFT JOIN platinum_buymed_th.seller_prd_core_seller AS s ON a.seller_code = s.code
    LEFT JOIN fact_order AS o ON a.order_id = o.order_id
    LEFT JOIN delivery AS d ON d.reference_code = o.sale_order_code
WHERE 1=1
    AND a.created_date >= DATE_TRUNC(CURRENT_DATE("+7"), MONTH ) - INTERVAL 2 MONTH
    AND o.status <> "CANCEL"

