config {
    type: "table", 
    description: 
        `PIC: huyen.nguyenthu; | Type: Table; | Refresh Schedule: 0:30 daily;
        Source: 
            ${source.platinum}.marketplace_prd_cart_cart,
            ${source.platinum}.marketplace_prd_cart_cart_item`,
    columns: { 
        created_time: `NonNull | The datetime when customer add item to cart, adjusted to the 'Asia/Ho_Chi_Minh' timezone `,
        created_date: "NonNull | The date when when customer add item to cart",
        created_hour: "NonNull | The specify hour when when customer add item to cart",
        customer_id: "NonNull | Unique identifier for each customer",
        cart_id: "NonNull | Unique identifier for each cart",
        current_price: "NonNull | Price of item in cart",
        added_quantity: "Nullable| Quantity was added to cart",
        added_page: "Nullable | The page user added item to cart",
        sku: "NonNull | seller_code + product_code" ,
        sku_fc_code: "NonNull | product_id + seller_code + sale_region"
    },
    tags: ["0h30"]
}

with region as (
    select
        sa.sales_region_code as area,
        gl.province_code
    from ${ref('dim_geo_location')} as gl
    left join ${ref('dim_fc_service_area')} as sa
    on gl.province_code = sa.service_area_code
    where gl.location_class = 'PROVINCE'
),

cart as (
  select
    c.ref_cart_item,
    c.cart_id,
    c.customer_id,
    r.area as sale_region
  from platinum_buymed_vn.marketplace_prd_cart_cart as c
  left join region as r
    on c.province_code = r.province_code
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY c.cart_id, c.ref_cart_item ORDER BY c.ingest_time DESC) = 1
)

select
  date(timestamp_add(ct.created_time, interval 7 hour)) as created_date,
  timestamp_add(ct.created_time, interval 7 hour) as created_time,
  extract(hour from timestamp_add(ct.created_time, interval 7 hour)) as created_hour,
  ct.sku,
  ct.ref_cart,
  concat(s.sku_key, "_", c.sale_region) as sku_fc_code,
  c.customer_id,
  ct.cart_id,
  ct.current_price,
  ct.quantity as added_quantity,
  ct.page as added_page

from platinum_buymed_vn.marketplace_prd_cart_cart_item as ct
left join cart as c
  on ct.ref_cart = c.ref_cart_item
  and ct.cart_id = c.cart_id
LEFT JOIN ${ref('dim_sku')} as s
  ON ct.sku = s.sku_code
where Date(timestamp_add(ct.created_time, interval 7 hour)) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)
QUALIFY
  ROW_NUMBER() OVER (PARTITION BY ct.ref_cart, ct.sku ORDER BY ct.ingest_time DESC) = 1