config {
    type: "table", 
    description: 
        `PIC: huyen.nguyenthu; 
        Type: Table; 
        Refresh Schedule: 0h30 daily;
        Source: 
            ${source.silver}.monitoring_prd_collector_user_stats
        `,
    columns: {
        created_time: "NON-NULL | Margin date in +7 Timezone",
        customer_id: "NON-NULL",
        sku_code: "NON-NULL",
        sku_fc_code: "NON-NULL"
    },
    tags: ["0h30"]
}
WITH region AS (
    select
        sa.sales_region_code as area,
        gl.province_code
    from gold_buymed_vn2.dim_geo_location as gl
    left join gold_buymed_vn2.dim_fc_service_area as sa
    on gl.province_code = sa.service_area_code
    where gl.location_class = 'PROVINCE'
),

adjusted_events AS (
  SELECT
    timestamp_add(e.created_time, INTERVAL 7 HOUR) AS created_time,
    e.customer_id,
    e.event,
    json_value(e.extra_props, "$.ua_metadata.OS") AS device_os,
    json_value(e.extra_props, "$.ua_metadata.PLATFORM") AS device_platform,
    json_value(e.extra_props, "$.metadata.sku") AS sku_code,
    json_value(e.extra_props, "$.metadata.screen") AS page_view,
    json_value(e.extra_props, "$.user_metadata.LOCATION") AS location
  FROM ${source.silver}.monitoring_prd_collector_user_stats AS e
  WHERE e.created_time >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 14 DAY)
  AND json_value(e.extra_props, "$.metadata.sku") IS NOT NULL
)

SELECT
  ae.created_time,
  DATE(ae.created_time) AS created_date,
  EXTRACT(HOUR FROM ae.created_time) AS created_hour,
  ae.customer_id,
  ae.event,
  ae.device_os,
  ae.device_platform,
  ae.sku_code,
  CONCAT(s.sku_key, "_", r.area) AS sku_fc_code,
  ae.page_view
FROM adjusted_events AS ae
LEFT JOIN region AS r
  ON ae.location = r.province_code
LEFT JOIN gold_buymed_vn2.dim_sku as s
  ON ae.sku_code = s.sku_code