config {
    type: "table", 
    description: 
        `PIC: huyen.nguyenthu; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.platinum}.marketplace_prd_cart_cart,
            ${source.platinum}.marketplace_prd_cart_cart_item
        `,
    tags: ["custom_1h_past5", "11h00", "11h30", "19h00", "15h00", "10h00", "13h30", "16h30", "17h00", "17h30", "18h30"]
}

with region as (
    select
        sa.sales_region_code as area,
        gl.province_code
    from gold_buymed_vn2.dim_geo_location as gl
    left join gold_buymed_vn2.dim_fc_service_area as sa
    on gl.province_code = sa.service_area_code
    where gl.location_class = 'PROVINCE'
),

cart as (
  select
    c.ref_cart_item,
    c.cart_id,
    c.customer_id,
    r.area as sale_region
  from platinum_buymed_vn.marketplace_prd_cart_cart as c
  left join region as r
    on c.province_code = r.province_code
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY c.cart_id, c.ref_cart_item ORDER BY c.ingest_time DESC) = 1
)

select
  date(timestamp_add(ct.created_time, interval 7 hour)) as created_date,
  timestamp_add(ct.created_time, interval 7 hour) as created_time,
  extract(hour from timestamp_add(ct.created_time, interval 7 hour)) as created_hour,
  ct.sku,
  ct.ref_cart,
  concat(s.sku_key, "_", c.sale_region) as sku_fc_code,
  c.customer_id,
  ct.cart_id,
  ct.current_price,
  ct.quantity as added_quantity,
  ct.page as added_page

from platinum_buymed_vn.marketplace_prd_cart_cart_item as ct
left join cart as c
  on ct.ref_cart = c.ref_cart_item
  and ct.cart_id = c.cart_id
LEFT JOIN gold_buymed_vn2.dim_sku as s
  ON ct.sku = s.sku_code
where Date(timestamp_add(ct.created_time, interval 7 hour)) >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)
QUALIFY
  ROW_NUMBER() OVER (PARTITION BY ct.ref_cart, ct.sku ORDER BY ct.ingest_time DESC) = 1