config {
    type: "view",
    name: "platform_event_prd_management_event",
    description: "PIC: minhLuu",
    schema: "platinum_buymed_vn",
    // assertions: {
    //     uniqueKey: 'mg_id',
    //     nonNull: ["created_date"]
    // },
    // bigquery: {
    //     partitionBy: "created_date"
    // },
    tags: ["platform_event_prd_management"]
}

WITH silver AS (
    SELECT 
        mg_id,
        ARRAY_AGG(key order by synced_at desc)[0] AS key,
        ARRAY_AGG(action order by synced_at desc)[0] AS action,
        ARRAY_AGG(synced_at order by synced_at desc)[0] AS synced_at,
        ARRAY_AGG(last_updated_time order by synced_at desc)[0] AS last_updated_time
    FROM ${source.silver}.platform_event_prd_management_event
    GROUP BY 1
    HAVING action != "d"
)

SELECT *
FROM ${source.silver}.platform_event_prd_management_event
WHERE key IN (SELECT key FROM silver)
