config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "platform_core_prd_activity_activity",
    tags:["platinum","platform_core_prd_activity","VN.activity"]
}

  WITH silver AS (
    SELECT
      key, mg_id, created_time, fullname, `group`, path, data, primary_key, user_agent, activity_id, template_code, org_id, target, session, last_updated_time, username, entity_id, method, ip, result_status, account_id, app_id, keys, synced_at, extra_props, action, ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.platform_core_prd_activity_activity
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key, mg_id, created_time, fullname, `group`, path, data, primary_key, user_agent, activity_id, template_code, org_id, target, session, last_updated_time, username, entity_id, method, ip, result_status, account_id, app_id, keys, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `platform_core_prd_activity_activity`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"