config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "platform_iam_prd_core_user_role",
    tags:["platinum","platform_iam_prd_core","PLATFORM.iam"]
}

  WITH silver AS (
    SELECT
      key, mg_id, app_id, org_id, account_id, is_main, source, role_code, entity_id, created_time, last_updated_time, synced_at, extra_props, action, ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.platform_iam_prd_core_user_role
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key, mg_id, app_id, org_id, account_id, is_main, source, role_code, entity_id, created_time, last_updated_time, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `platform_iam_prd_core_user_role`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"