config {
    type: "view",
    name: "platform_core_prd_master_data_legal_entity",
    schema: "platinum_buymed_vn",
    tags: ["platform_core_prd_master-data"]
}
SELECT 
    *,
    CASE 
        WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
        ELSE "2099-01-01"
    END AS created_date
FROM silver_buymed_vn.platform_core_prd_master_data_legal_entity
QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER(_window) != "d"
WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
    IF(action = 'd', 3, IF(action = 'u', 2, 1))
)