
config {
  type: "view",
  schema: "platinum_buymed_vn",
  name: "circa_online_prd_consumer_benefit_log",
  description : `
  PIC: LongNguyen
  Partition by: created date
  `,
  tags:["platinum","circa-online_prd_consumer"]
}

WITH silver AS (
  SELECT
    key, mg_id, contract_id, entity_id, full_name, email, phone, level_code, level_name, created_time, last_updated_time, status, level_id, invite_expires_at, invite_send_attempts, invite_send_error, invite_send_status, invite_sent_at, invite_token, invite_claimed_at, account_id, is_active, synced_at, extra_props, action, ingest_time,
    CASE
      WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
      ELSE DATE('2099-01-01')
    END created_date,
    CAST(NULL AS DATETIME) AS platinum_refresh
  FROM silver_buymed_vn.circa_online_prd_consumer_benefit_log
  WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
  QUALIFY ROW_NUMBER() OVER (_window) = 1
    AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
  WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
      IF(action='d',3, IF(action='u',2,1)) DESC,
      last_updated_time DESC
  )
),

platinum AS (
  SELECT
    key, mg_id, contract_id, entity_id, full_name, email, phone, level_code, level_name, created_time, last_updated_time, status, level_id, invite_expires_at, invite_send_attempts, invite_send_error, invite_send_status, invite_sent_at, invite_token, invite_claimed_at, account_id, is_active, synced_at, extra_props, action, ingest_time,
    created_date,
    platinum_refresh
  FROM ${ref(`platinum_buymed_vn__stg`, `circa_online_prd_consumer_benefit_log`)}
)

SELECT p.*
FROM platinum p
LEFT JOIN silver s
  ON p.mg_id = s.mg_id
WHERE s.mg_id IS NULL

UNION ALL

SELECT s.*
FROM silver s
WHERE action <> "d"
