config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "circa_online_prd_social_poster_engagement_viewss",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","circa_online_prd_social_poster"]
}
 
  WITH silver AS (
    SELECT
key, mg_id, target_id, target_type, session_id, completed, duration_seconds, guest_id, ip_hash, last_ping_at, referrer, scroll_depth_max, started_at, user_agent, synced_at, extra_props, action, ingest_time,
        CASE
            WHEN started_at IS NOT NULL THEN DATE(DATETIME(started_at, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.circa_online_prd_social_poster_engagement_views
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          )
  ), platinum AS (
    SELECT 
     key, mg_id, target_id, target_type, session_id, completed, duration_seconds, guest_id, ip_hash, last_ping_at, referrer, scroll_depth_max, started_at, user_agent, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `circa_online_prd_social_poster_engagement_views`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"