config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "circa_online_prd_consumer_customer_address_book",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","circa-online_prd_consumer"]
}
 
  WITH silver AS (
    SELECT
      key,mg_id,customer_id,geo_location,receiver_name,full_address,is_default_address,country_code,province_code,created_time,last_updated_time,status,type,phone_number,note,ward_code,code,district_code,is_shared,address,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.circa_online_prd_consumer_customer_address_book
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,customer_id,geo_location,receiver_name,full_address,is_default_address,country_code,province_code,created_time,last_updated_time,status,type,phone_number,note,ward_code,code,district_code,is_shared,address,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `circa_online_prd_consumer_customer_address_book`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"