config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "circa_online_prd_order_order_event",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","circa-online_prd_order"]
}
 
WITH silver AS (
SELECT
    key,mg_id,order_code,action_by_name,partition_time,note,created_time,order_id,event_name,event_type,action_time,action_by_id,action_status_code,last_updated_time,synced_at,extra_props,action,ingest_time,
    
    CASE
        WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
        ELSE DATE( '2099-01-01' )
    END
    created_date,
    CAST(null as datetime) 
FROM silver_buymed_vn.circa_online_prd_order_order_event
WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
QUALIFY ROW_NUMBER() OVER (_window) = 1 
        AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
        WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC,
        IF
            (action='d',3,
            IF
            (action='u',2,1)) DESC
        ,last_updated_time DESC)
), platinum AS (
SELECT 
    key,mg_id,order_code,action_by_name,partition_time,note,created_time,order_id,event_name,event_type,action_time,action_by_id,action_status_code,last_updated_time,synced_at,extra_props,action,ingest_time,
    created_date,
    platinum_refresh
FROM ${ref(`platinum_buymed_vn__stg`, `circa_online_prd_order_order_event`)}
)
SELECT p.*
FROM platinum p
LEFT JOIN silver s 
    ON p.mg_id = s.mg_id 
WHERE s.mg_id is null 

UNION ALL 

SELECT s.*
FROM silver s
WHERE action <> "d"