config {
  type: "table",
  tags: ["custom_1h_past10", "FC_BACKLOG"]
}

SELECT
    wt.created_date
    , wt.created_time + INTERVAL 7 HOUR AS created_time
    , wt.code as ticket_code
    , wt.warehouse_code as fc_code
    , wt.status as ticket_status
    , wt.delivery_method
    , JSON_VALUE(wt.delivery_info, "$.hub_code") AS hub_code
    , wt.seller_code
    , DATE_DIFF(wt.overdue_date, current_timestamp(), DAY) + 2 as day_left
    , wt.note as ticket_note
    , wi.sku_code
    , wi.quantity
    , wi.reason as sku_note
    , timestamp_add( current_timestamp(), interval 7 hour ) as transformed_at
FROM ${source.platinum}.seller_prd_wis_withdraw_ticket AS wt
    LEFT JOIN ${source.platinum}.seller_prd_wis_withdraw_item AS wi on wt.code = wi.withdraw_code
WHERE 1=1
    AND wt.created_date >= DATE_SUB(DATE_TRUNC(CURRENT_DATE("+7"), MONTH), INTERVAL 6 MONTH)
    AND wi.created_date >= DATE_SUB(DATE_TRUNC(CURRENT_DATE("+7"), MONTH), INTERVAL 6 MONTH)
    AND wt.status NOT IN ("COMPLETED", "CANCELLED")