config {
    type: "table",
    description: 
        `
        Aggregate the purchased and sales values by product for the rebate program that doesn't have a target division;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: daily at 8h30;
        Source: 
            ${source.platinum}.seller_prd_promotion_rebate_result,
            ${source.ref}.fact_vendor_bill,
            ${source.ref}.dim_vendor,
        `,
    tags: ["8h30", "REBATE"]
}

WITH
-------- STEP 1: Retrieve the purchased value by product (amount or quantity) from the vendor bill by each rebate program -----------

    purchase AS (
        SELECT
            vbi.created_time
            , vbi.vendor_bill_id
            , vbi.po_code
            , vbi.product_id
            , vbi.sku_code
            , vbi.price
            , vbi.price_after_discount
            , vbi.quantity
            , vbi.vat
            , rri.rebate_code
            , r.condition_unit
            , r.condition_include_type
            , vbi.fc_code
            , rri.rebate_item_id
        FROM ${ref('fact_vendor_bill_item')} AS vbi
            LEFT JOIN ${ref('fact_rebate_invoice')} AS ri ON ri.vendor_bill_id = vbi.vendor_bill_id
            LEFT JOIN ${ref('fact_rebate_result_item')} AS rri ON rri.rebate_code = ri.rebate_code
            LEFT JOIN ${ref('dim_rebate')} AS r ON r.rebate_code = rri.rebate_code
        WHERE
            rri.rebate_code IS NOT NULL
            AND vbi.seller_code = 'MEDX'
            AND rri.target_division IS NULL
    ),

-------- STEP 2: Retrieve product demand & fv_vendor (only include seller MEDX, channels Marketplace & Circa, excluding CANCELED orders) --------

    sale AS (
        SELECT
            DATE(oi.created_at) AS order_date
            , oi.order_id
            , oi.product_id
            , oi.sales_price AS unit_price
            , oi.demand_quantity AS qty_ordered
            , fc.fc_code
            , CONCAT(vv.supplier_id, ' - ', vv.supplier_name) AS fv_vendor
        FROM ${ref('fact_order_item')} AS oi
            LEFT JOIN ${ref('fact_order')} AS o ON oi.order_id = o.order_id
            LEFT JOIN ${ref('dim_fc_service_area')} AS fc ON fc.service_area_code = o.shipping_province_code
            LEFT JOIN ${ref('dim_sku_sales_region_current')}  AS s ON s.sku_code = oi.sku_code AND s.fc_code = fc.fc_code
            LEFT JOIN ${ref('dim_vendor')}  AS v ON v.supplier_code = s.fv_code
            LEFT JOIN ${ref('dim_vendor')}  AS vv ON vv.supplier_code = v.line_manager_combine
        WHERE
            oi.created_at >= '2024-01-01'
            AND o.order_status <> 'CANCEL'
            AND oi.seller_code = 'MEDX'
            AND o.channel IN ('MARKETPLACE', 'CIRCA')
    ),

-------- STEP 3: Aggregate the total purchased value according to condition_unit & condition_include_type for each rebate program ---------

    agg_purchase AS (
        SELECT
            rebate_code
            , rebate_item_id
            , product_id
            , condition_unit
            , CASE
                WHEN condition_unit = 'AMOUNT' THEN
                 CASE
                    WHEN condition_include_type = 'NONE' THEN SUM( price * quantity )
                    WHEN condition_include_type = 'UNIT_AFTER_VAT' THEN SUM( price * quantity * (1 + vat / 100))
                    WHEN condition_include_type = 'AFTER_DISCOUNT' THEN SUM( price_after_discount * quantity )
                    WHEN condition_include_type = 'AFTER_VAT' THEN SUM( price_after_discount * quantity * (1 + vat / 100))
                  END
                ELSE SUM(quantity)
              END AS total_purchased_value
        FROM purchase
        GROUP BY rebate_code, product_id, condition_unit, condition_include_type, rebate_item_id
    )

-------- Final Step: Join the tables together to get the total purchased value & product demand for each rebate program ------------

SELECT
    ri.rebate_code
    , ri.target_division_code AS division_code
    , ri.target_division AS division_name
    , a.product_id
    , p.product_name
    , ri.rebate_item_id
    , a.total_purchased_value
    , CASE
        WHEN r.condition_unit = "QUANTITY" THEN SUM(b.qty_ordered)
        ELSE SUM(b.unit_price * b.qty_ordered)
      END AS sale_value
    , (
        SELECT
            SUM( s.unit_price * s.qty_ordered )
        FROM sale AS s
        WHERE a.product_id = s.product_id
            AND STRPOS(r.vendors, s.fv_vendor) > 0
            AND s.order_date BETWEEN DATE_SUB(CURRENT_DATE("+7"), INTERVAL 30 DAY) AND DATE_SUB(CURRENT_DATE("+7"), INTERVAL 1 DAY)
            AND STRPOS(r.warehouse_code, s.fc_code) > 0
      ) AS Total_GMV_30D
FROM ${ref('fact_rebate_result_item')}  AS ri
    LEFT JOIN ${ref('dim_rebate')}  AS r ON ri.rebate_code = r.rebate_code
    LEFT JOIN agg_purchase AS a ON ri.rebate_item_id = a.rebate_item_id
    LEFT JOIN sale AS b
        ON a.product_id = b.product_id
            AND STRPOS(r.vendors, b.fv_vendor) > 0
            AND b.order_date BETWEEN r.start_time AND r.end_time
            AND STRPOS(r.warehouse_code, b.fc_code) > 0
    LEFT JOIN ${ref('dim_product')}  AS p ON p.product_id = a.product_id
WHERE ri.target_division IS NULL
GROUP BY ri.rebate_code, ri.target_division_code, ri.target_division, a.product_id, p.product_name,
         ri.rebate_item_id, a.total_purchased_value, r.condition_unit, r.vendors, r.warehouse_code