config {
    type: "table",
    description: 
        `
        Aggregation by Customer & SOM;
        PIC: nguyen.tran; 
        Type: Table; 
		Refresh Schedule: hourly;
        Source: 
            ${source.ref}.fact_order,
            ${source.ref}.dim_customer,
            ${source.ref}.dim_calendar
        `,
    tags: ["custom_1h_past5"],
    bigquery: {
        partitionBy: "som",
        clusterBy: ["customer_id"]
    }
}

WITH
    cte_transaction AS (
        SELECT
            c.order_id
            , c.customer_id
            , DATE_TRUNC(DATE(created_at), MONTH) AS som
            , created_at AS created_time
            , ordered_amount
        FROM
            ${ref('fact_order')} AS C
        WHERE
            order_status <> "CANCEL"
            AND channel = "MARKETPLACE"
    )

    , order_item_l3m AS (
        SELECT
            oi.customer_id
            , DATE_TRUNC(DATE(oi.created_at), MONTH) AS som
            -- , SUM(sales_price * demand_quantity) AS gmv
            , COUNT(DISTINCT sku_code) AS no_skus
        FROM ${ref('fact_order_item')} AS oi
            LEFT JOIN ${ref('fact_order')} AS o USING(order_id)
        WHERE
            order_status <> "CANCEL"
            AND channel = "MARKETPLACE" 
            AND DATE(oi.created_at) >= DATE_SUB(DATE_TRUNC(CURRENT_DATE("+7"), MONTH), INTERVAL 3 MONTH)
            AND DATE(o.created_at) >= DATE_SUB(DATE_TRUNC(CURRENT_DATE("+7"), MONTH), INTERVAL 3 MONTH)
        GROUP BY ALL
    )

    , cte_transaction_with_previous_order_time AS (
        SELECT
          *
          , LAG(created_time) OVER (PARTITION BY customer_id ORDER BY created_time) AS previous_order_time
        FROM cte_transaction
    )

    , cte_agg_customer_and_som AS (
        SELECT
            customer_id
            , som
            , MAX(
                IF(previous_order_time < som, previous_order_time, NULL)
              ) AS last_order_time_without_cancel_before_current_month
            , MIN(
                IF( DATE_TRUNC(created_time, MONTH) = som, created_time, NULL)
              ) AS first_order_time_without_cancel_in_current_month
            , SUM(ordered_amount) AS gmv
        FROM cte_transaction_with_previous_order_time
        GROUP BY ALL
    )

    , cte_agg_customer AS (
        SELECT
            customer_id
            , MAX(created_time) AS last_order_time_without_cancel_ever
            , MIN(created_time) AS first_order_time_without_cancel_ever
        FROM cte_transaction
        GROUP BY ALL
    )

    , cte_main AS (
        SELECT
            cu.customer_id
--             , cu.location_code
            , ca.som
        FROM ${ref('dim_customer')} AS cu
            , (
                SELECT DISTINCT som
                FROM ${ref('dim_calendar')}
                WHERE date <= CURRENT_DATE("+7")
            ) AS ca
        WHERE
            ca.som >= DATETIME_TRUNC(cu.user_created_at, MONTH)
    )

    , classify AS (
        SELECT
            a.*
        --     , d.region_name
        --     , d.province_name
            , c.first_order_time_without_cancel_ever
            , c.last_order_time_without_cancel_ever
            , b.last_order_time_without_cancel_before_current_month
            , b.first_order_time_without_cancel_in_current_month
            , DATE_DIFF(b.first_order_time_without_cancel_in_current_month, b.last_order_time_without_cancel_before_current_month, DAY) AS days_return_active
            , CASE
                -- WHEN DATE_TRUNC(c.first_order_time_without_cancel_ever, MONTH) > a.som  THEN "USER_ONLY"
                WHEN /*c.first_order_time_without_cancel_ever IS NOT NULL
                     AND*/
                     b.first_order_time_without_cancel_in_current_month IS NULL THEN "CHURN"
                WHEN /*c.first_order_time_without_cancel_ever IS NOT NULL
                    AND*/ 
                    b.first_order_time_without_cancel_in_current_month IS NOT NULL THEN "ACTIVE"
                -- ELSE "USER_ONLY"
              END AS customer_business_status
            , b.gmv
            , d.no_skus
        FROM cte_main AS a
            LEFT JOIN cte_agg_customer_and_som AS b ON a.customer_id = b.customer_id AND a.som = b.som
            LEFT JOIN cte_agg_customer AS c ON a.customer_id = c.customer_id
            LEFT JOIN order_item_l3m AS d ON a.customer_id = d.customer_id AND a.som = d.som
        WHERE
            c.first_order_time_without_cancel_ever IS NOT NULL
            AND a.som >= DATETIME_TRUNC(c.first_order_time_without_cancel_ever, MONTH)
    ),

    user_only AS (
        SELECT
            a.customer_id
            , DATE_TRUNC(CURRENT_DATE("+7"), MONTH) AS som
            , CAST(NULL AS DATETIME) AS first_order_time_without_cancel_ever
            , CAST(NULL AS DATETIME) AS last_order_time_without_cancel_ever
            , CAST(NULL AS DATETIME) AS last_order_time_without_cancel_before_current_month
            , CAST(NULL AS DATETIME) AS first_order_time_without_cancel_in_current_month
            , NULL AS days_return_active
            , "USER_ONLY" AS customer_business_status
            , NULL AS gmv
            , NULL AS no_skus
        FROM ${ref('dim_customer')} AS a
            LEFT JOIN cte_agg_customer AS c ON a.customer_id = c.customer_id
        WHERE
            c.first_order_time_without_cancel_ever IS NULL 
            AND a.customer_channel IS NULL
    )

SELECT
    *
    , IF(
        customer_business_status = "ACTIVE"
        , CASE
            WHEN DATE_TRUNC(first_order_time_without_cancel_ever, MONTH) = som THEN "NEW_CUSTOMER"
            WHEN days_return_active < 30 THEN "REPEAT_CUSTOMER"
            WHEN days_return_active >= 30 THEN "REACQUIRED_CUSTOMER"
          END
        , NULL
      ) AS customer_active_type
    , CASE
        WHEN days_return_active BETWEEN 30 AND 59 THEN "REACQUIRED_AFTER_CHURN_30D"
        WHEN days_return_active >= 60 THEN "REACQUIRED_AFTER_CHURN_60D"
      END AS customer_reacquired_type
FROM classify
UNION ALL
SELECT
    *
    , NULL AS customer_active_type
    , NULL AS customer_reacquired_type
FROM user_only