config {
  type: 'table',
  description: `PIC: minhluu , model_type: table ; schedule: 0h00 daily
  Source:
    ${source.silver}.marketplace_prd_customer_priority_customer`,
  columns:{
      customer_name: "NonNull | customer_name",
      email: "Nullable | customer email",
      phone: "NonNull | customer phone",
      customer_code : "NonNull | customer code",
      hash_tag : "NonNull | Can be in one of following 'CONVERTED', 'DELETED', 'NEW'",
      priority_customer_id : "NonNull & Unique |  ",
      status: "NonNull | ",
      scope: "nullable | Can be in one of following : 'BEAUTY_SALON','CLINIC','DENTISTRY','DRUGSTORE','HOSPITAL','PATIENT','PHARMACIST','PHARMACY','PHARMA_COMPANY'",
      source: "nullable | can be in one of following : 'APP SALES','CHAT','HOMEPAGE','INTERNAL'",
      address: "Nullable | ",
      ward_code: "Nullable | ",
      district_code: "NonNull | ",
      province_code: "NonNull | ",
      pic_account_id: "NonNull | ",
      pic_username : "Nullable | ",
      last_checked_out_day : "Nullable |",
      note: "Nullable",
      created_time: "NonNull | In Timezone +7"
  },
  tags : ['0h00'],
  assertions: {
      // guaranteed columns: primary key, Source_insure_NonNull
      uniqueKey : "priority_customer_id",
      nonNull : ("priority_customer_id" )
  }
}


SELECT 
  name AS customer_name,
  email, 
  phone, 
  code as customer_code, 
  hash_tag,
  priority_customer_id, 
  status ,
  scope , 
  source ,  
  address, 
  ward_code ,
  province_code , 
  district_code, 
  last_checked_out_day,
  -- location, -- nullable | {'coordinates': [x,y],'type': "Point"}
  pic_account_id ,
  pic_username ,
  note
  
FROM 

${dedup.dedup(`silver_buymed_vn.marketplace_prd_customer_priority_customer`,'*')}

post_operations {
  ALTER TABLE ${self()} 
  ADD PRIMARY KEY (customer_code) NOT ENFORCED,
  ADD FOREIGN KEY(priority_customer_id) references ${ref(`dim_customer`)}(customer_id) NOT ENFORCED,
  ADD FOREIGN KEY(ward_code) references ${ref(`dim_geo_location`)}(location_code) NOT ENFORCED
}