config {
    type: "view",
    description: `PIC: minh.luu, model_type: view"
    Source
        ${source.ref}.dim_order
        ${source.ref}.dim_calendar
        ${source.ref}.fact_order_strategic`,
    columns: {
        metric_code: "NonNull | Concat of #_Orders and metric lv2 column",
        date: "NonNull | End of month",
        value: "NonNull | gmv"
    }
}
SELECT
    dim_calendar.eom as date,
    "ORDER" AS metric_code,
    COUNT(fact_order_strategic.order_id) as value

FROM ${ref(`fact_order_strategic`)} fact_order_strategic
LEFT JOIN ${ref(`dim_order`)} dim_order
    ON fact_order_strategic.order_id = dim_order.order_id
LEFT JOIN ${ref(`dim_calendar`)} dim_calendar
    ON fact_order_strategic.created_date = dim_calendar.date
GROUP BY 1,2
HAVING value <> 0
ORDER BY eom