config {
    type: "view",
    description: `PIC: minh.luu, model_type: view"
    Source
        ${source.ref}.dim_order
        ${source.ref}.dim_calendar
        ${source.ref}.fact_order_strategic`,
    columns: {
        metric_code: "NonNull | Concat of SalesRegion and metric lv2 column",
        date: "NonNull | End of month",
        value: "NonNull | gmv"
    }
}
SELECT
    dim_calendar.eom as date,
    CASE
        WHEN dim_order.sales_region_code LIKE "MIENNAM" THEN "OB-ORDER-BD"
        WHEN dim_order.sales_region_code LIKE "MIENTRUNG" THEN "OB-ORDER-DN"
        WHEN dim_order.sales_region_code LIKE "MIENBAC" THEN "OB-ORDER-HN"
    END AS metric_code,
    COUNTIF( fact_bill.outbound is not null or fact_bill.outbound_amount is not null) as value


FROM ${ref(`fact_order_strategic`)} fact_order_strategic
LEFT JOIN  ${ref(`dim_order`)}  dim_order
    ON fact_order_strategic.order_id = dim_order.order_id
LEFT JOIN (
    SELECT
        order_id,created_time, sum(outbound_amount) as outbound_amount, countif (outbound_time is not null) outbound
    FROM ${ref(`fact_bill`)}
    GROUP BY 1,2
)  fact_bill
    ON fact_order_strategic.order_id = fact_bill.order_id
LEFT JOIN  ${ref(`dim_calendar`)} dim_calendar
    ON DATE(fact_bill.created_time) = dim_calendar.date
WHERE order_status NOT IN ('CANCEL','CANCELLED')
AND dim_order.sales_region_code IS NOT NULL --will fix_latter
GROUP BY 1,2
HAVING value <> 0
ORDER BY eom
