config {
    type: "view",
    description: `PIC: minh.luu, model_type: view"
    Source
        ${source.ref}.dim_order
        ${source.ref}.dim_calendar
        ${source.ref}.fact_order_strategic`,
    columns: {
        metric_code: "NonNull | Concat of SalesRegion and metric lv2 column",
        date: "NonNull | End of month",
        value: "NonNull | gmv"
    }
}
SELECT
    dim_calendar.eom as date,
    'GMV-BACKLOG' AS metric_code,
    -- SUM( 
    --     fact_order_strategic.gmv
    --     - IF( order_status IN ('DELIVERING', 'DELIVERED', 'COMPLETED'), fact_order_strategic.gmv, 0) 
    --     - COALESCE(fact_order_strategic.return_amount,0)
    -- )  as value 
    -- SUM (gmv)
    SUM ( IF( order_status IN ('DELIVERING'), fact_order_item_strategic.outbound_amount , 0) )
    as value

FROM `lakehouse-prod-394907.gold_buymed_vn2.fact_order_strategic` fact_order_strategic
LEFT JOIN `lakehouse-prod-394907.gold_buymed_vn2.dim_order` dim_order
    ON fact_order_strategic.order_id = dim_order.order_id
LEFT JOIN (
    SELECT 
        order_id,supplier_class , SUM(outbound_amount) outbound_amount
    FROM ${ref(`fact_order_item_strategic`)} fact_order_item_strategic
    GROUP BY 1,2
) fact_order_item_strategic
    ON fact_order_item_strategic.order_id = fact_order_strategic.order_id
LEFT JOIN `lakehouse-prod-394907.gold_buymed_vn2.dim_calendar` dim_calendar
    ON fact_order_strategic.created_date = dim_calendar.date
WHERE order_status NOT IN ('CANCEL','CANCELLED')
AND dim_order.order_channel is not null -- fix latter
AND dim_order.order_channel not like "CONSIGNMENT-RECOGNITION"
AND fact_order_item_strategic.supplier_class NOT LIKE "TECH"
GROUP BY 1,2
HAVING value <> 0
ORDER BY eom