config {
    type: "view",
    description: `PIC: minh.luu, model_type: view"
    Source
        ${source.ref}.dim_order
        ${source.ref}.dim_calendar
        ${source.ref}.fact_order_strategic`,
    columns: {
        metric_code: "NonNull | Concat of SalesRegion and metric lv2 column",
        date: "NonNull | End of month",
        value: "NonNull | gmv"
    }
}
SELECT
    dim_calendar.eom as date,
    CASE
        WHEN fact_order_item_outbound_strategic.warehouse_code LIKE "BD" THEN "OB-ITEM-BD"
        WHEN fact_order_item_outbound_strategic.warehouse_code LIKE "DN" THEN "OB-ITEM-DN"
        WHEN fact_order_item_outbound_strategic.warehouse_code LIKE "HN" THEN "OB-ITEM-HN"
    END AS metric_code,
    SUM(fact_order_item_outbound_strategic.outbound_items) as value

FROM ${ref(`fact_order_item_outbound_strategic`)} fact_order_item_outbound_strategic
LEFT JOIN  ${ref(`dim_calendar`)} dim_calendar
    ON DATE(fact_order_item_outbound_strategic.outbound_time) = dim_calendar.date
-- WHERE order_status NOT IN ('CANCEL','CANCELLED')
-- WHERE dim_order.sales_region_code IS NOT NULL --will fix_latter
WHERE warehouse_code IN ("BD", "DN", "HN")
GROUP BY 1,2
HAVING value <> 0
ORDER BY eom