config {
    type: "view",
    description: `PIC: minh.luu, model_type: view"
    Source
        ${source.ref}.dim_order
        ${source.ref}.dim_calendar
        ${source.ref}.fact_order_strategic`,
    columns: {
        metric_code: "NonNull | Concat of SalesRegion and metric lv2 column",
        date: "NonNull | End of month",
        value: "NonNull | gmv"
    }
}
SELECT
    dim_calendar.eom as date,
    "CANCEL" AS metric_code,
    SUM(
        IF( order_status IN ('CANCEL', 'CANCELLED'),
        fact_order_strategic.ordered_amount,
        0)
    )  as value

FROM `lakehouse-prod-394907.gold_buymed_vn2.fact_order_strategic` fact_order_strategic
LEFT JOIN `lakehouse-prod-394907.gold_buymed_vn2.dim_order` dim_order
    ON fact_order_strategic.order_id = dim_order.order_id
LEFT JOIN `lakehouse-prod-394907.gold_buymed_vn2.dim_calendar` dim_calendar
    ON fact_order_strategic.created_date = dim_calendar.date
GROUP BY 1,2
HAVING value <> 0
ORDER BY eom