config {
    type: "view",
    description: `PIC: minh.luu, model_type: view"
    Source
        ${source.ref}.dim_order
        ${source.ref}.dim_calendar
        ${source.ref}.fact_order_strategic`,
    columns: {
        metric_code: "NonNull | Concat of SalesRegion and metric lv2 column",
        date: "NonNull | End of month",
        value: "NonNull | gmv"
    }
}
SELECT
    dim_calendar.eom as date,
    CASE
        WHEN dim_order.sales_region_code LIKE "MIENNAM" THEN "OB-ITEM-BD"
        WHEN dim_order.sales_region_code LIKE "MIENTRUNG" THEN "OB-ITEM-DN"
        WHEN dim_order.sales_region_code LIKE "MIENBAC" THEN "OB-ITEM-HN"
    END AS metric_code,
    SUM(fact_bill.outbound_quantity) as value

FROM ${ref(`fact_order_strategic`)} fact_order_strategic
LEFT JOIN  ${ref(`dim_order`)}  dim_order
    ON fact_order_strategic.order_id = dim_order.order_id
LEFT JOIN ${ref(`fact_bill`)} fact_bill
    ON fact_order_strategic.order_id = fact_bill.order_id
LEFT JOIN  ${ref(`dim_calendar`)} dim_calendar
    ON DATE(fact_bill.created_time) = dim_calendar.date
WHERE order_status NOT IN ('CANCEL','CANCELLED')
AND dim_order.sales_region_code IS NOT NULL --will fix_latter
GROUP BY 1,2
HAVING value <> 0
ORDER BY eom