config {
    type: "table",
    description: `circa_customer_order_daily
                  PIC: huyen.ngo ; 
                  model_type: Table ;
                  schedule: `, 
    schema: "buymed_tech",
    name: "circa_customer_product_daily",
}

WITH item_daily AS (
  SELECT
    o.entity_id                                                         AS customer_id
    , DATE(COALESCE(o.completed_at, o.created_at), 'Asia/Ho_Chi_Minh')  AS order_date
    , oi.product_id
    , oi.sku_code
    , SUM(oi.quantity)                                                  AS quantity
    , SUM(oi.amount)                                                    AS amount
  FROM `buymed_circa_v2.order_order_item` oi
  INNER JOIN `buymed_circa_v2.order_order` o ON  o.id = oi.order_id
                                             AND o.created_date >= '2000-01-01'
  WHERE oi.created_date >= '2000-01-01'
    AND o.status = 'COMPLETED'
    AND o.type IN ('ONLINE', 'OFFLINE')
    AND o.entity_id IS NOT NULL
    AND o.entity_id <> '00000000-0000-0000-0000-000000000000'
    AND (oi.gift_code = '' OR oi.gift_code IS NULL)
    AND oi.is_service_item = false
    AND oi.seller_code <> 'CIRCA_MKP'
  GROUP BY ALL
)

SELECT
  d.customer_id                 
  , d.order_date               
  , d.product_id                
  , p.product_name              
  , d.sku_code                  
  , p.brand                     
  , p.brand_type                
  , p.product_category          
  , p.cat2                      
  , p.cat3                      
  , p.cat4                      
  , d.quantity                  
  , d.amount                    
FROM item_daily d
LEFT JOIN `gold_buymed_vn2.circa_dim_master_product` p ON p.product_id = d.product_id