config {
    type: "table",
    description: `circa_customer_voucher
                  PIC: huyen.ngo ; 
                  model_type: Table ;
                  schedule: `, 
    schema: "buymed_tech",
    tags: ["circa_customer"],
    name: "circa_customer_voucher"
  
}

WITH voucher_use AS (
  SELECT
    o.entity_id                                   AS customer_id
    , o.id                                        AS order_id
    , COALESCE(o.completed_at, o.created_at)      AS order_ts
    , v.voucher_code
    , v.voucher_id
    , v.discount_amount
  FROM `buymed_circa_v2.order_order_voucher` v
  INNER JOIN `buymed_circa_v2.order_order` o ON  o.id = v.order_id
  WHERE v.is_valid = true
    AND o.status = 'COMPLETED'
    AND o.type IN ('ONLINE', 'OFFLINE')
    AND o.entity_id IS NOT NULL
    AND o.entity_id NOT IN ( '00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000001')
  QUALIFY ROW_NUMBER() OVER (PARTITION BY v.order_id, v.voucher_code ORDER BY v.created_at DESC) = 1
)

SELECT
  customer_id                                                          
  , voucher_code                                                        
  , ARRAY_AGG(voucher_id ORDER BY order_ts DESC LIMIT 1)[OFFSET(0)]     AS voucher_id      
  , TIMESTAMP_ADD(MIN(order_ts), INTERVAL 7 HOUR)                       AS first_used_at   
  , TIMESTAMP_ADD(MAX(order_ts), INTERVAL 7 HOUR)                       AS last_used_at  
  , COUNT(DISTINCT order_id)                                            AS times_used     
  , SUM(discount_amount)                                                AS discount_amount
  , DATETIME(CURRENT_TIMESTAMP(),  'Asia/Ho_Chi_Minh') AS refresh_at  
FROM voucher_use
GROUP BY ALL
ORDER BY times_used DESC