config {
    type: 'incremental',
    name: "fact_user_search_event",
    description: `Started time: 20240901 | PIC: tu.dang; schedule: 0h00 daily; model type: table
    Source:
        ${source.ref}.fact_user_event_tracking`,
    columns: {
        event: `NonNull | In all Customer Search Action`,
        customer_id: "NonNull | The unique identifier for the customer",
        created_time: "NonNull | The datetime when the event was created, adjusted to the 'Asia/Ho_Chi_Minh' timezone",
        product_id: "NonNull | Unique identifier for each product",
        province_code: "Nullable | " + docs.province_code,
        /*screen: "Nullable | The screen on which the event occurred. This provides additional context on the user interface interaction",
        source: "Nullable | The source of the event, indicating how the item was created",*/
        sku_code: "NonNull" | docs.sku,
        is_sku_customer_first_interaction_in_30_days: "NonNull | A boolean indicating whether this is the customer's first interaction with the SKU in the past 30 days. It's determined by checking if there are any previous interactions with the same customer_id, sku_code, and event within 30 days before the current created_time.",
    },
    tags: ["custom_1h_past5"],
    bigquery: {
        partitionBy: "date(created_time)",
        clusterBy: ["customer_id"]
    },
}

pre_operations {
    ${
        when(incremental(),
        `
            DELETE FROM ${self()}
            WHERE created_time >= DATETIME(CURRENT_DATE("+7"));
            DELETE FROM ${self()}
            WHERE created_time < DATETIME_SUB(DATETIME_TRUNC(CURRENT_DATETIME("+7"), MONTH), INTERVAL 1 MONTH);
        `

    )}
}

WITH stg AS (
    SELECT
        event
        , customer_id
        , created_time
        , province_code
        , client
        , platform
        , search_content
        , search_status
        , LEAD(event) over(partition by customer_id order by created_time) as next_action
        , LEAD(created_time) over(partition by customer_id order by created_time) as next_action_created_time
    FROM ${ref('fact_user_event_tracking')}
    WHERE 
        DATE(created_time) >= ${when(incremental(), `current_date("+7")`, `DATE_SUB(DATE_TRUNC(CURRENT_DATE("+7"), MONTH), INTERVAL 1 MONTH)`)}
    -- DATE(created_time) >= DATE_SUB(DATE_TRUNC(CURRENT_DATE("+7"), MONTH), INTERVAL 1 MONTH)
)
SELECT
    event,
    customer_id,
    created_time,
    province_code,
    -- screen,
    -- source,
    client,
    platform,
    search_content,
    search_status, 
    next_action,
    next_action_created_time
FROM
    stg
where customer_id >0 AND event ="SEARCH"





