config {
    type: "incremental",
    name: "platform_billing_prd_payment_transfer_request_item",
    description: "PIC: minhLuu ; Internal: Accounting/Payment",
    schema: "platinum_buymed_vn_restricted",
    assertions: {
        uniqueKey: 'mg_id',
        nonNull: ["created_date"]
    },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["another_custom_2h_past5","platform_billing_prd_payment"]
}

internal_management_prd_purchase