config {
  type: "view",
  name: "dim_customer_view",
  schema: "buymed_product_recommendation",
  description: `PIC: minh.luu; model_type: table; schedule 0h00
    Source:
        ${source.silver}.marketplace_prd_customer_customer customer
        ${source.silver}.marketplace_prd_order_v2_order order`,
  columns: {
    customer_id: "NonNull",
    customer_report_category: `NonNull | Is one of TECH, TENDER, MARKETPLACE, or CIRCA? 
      Category assigned to the customer based on specific conditions:
      - TECH: If the customer's name contains keywords like 'TECH SELLER', 'TEST', 'TECH-QC', etc.
      - TENDER: If the customer's tags contain 'TENDER'.
      - MARKETPLACE: If the customer's tags contain 'TERMINATE_CIRCA' or as a default category.
      - CIRCA: If the customer's tags contain 'CIRCA'.`,
    customer_ward_code: `Nullable | If the customer doesn't have a ward_code, then get ward_code of last order of customer 
      from the order table. Otherwise, return null.`,
     business_scope: "Nullable | Null means UNKNOWN scope",
     customer_status: "NonNull | Must be one of following: 'DELETED','ACTIVATE','INACTIVE'",
     customer_ward_code: "Nullable | If the customer doesn't have a ward_code, then get ward_code of last order of customer from the order table. Otherwise, return null."

  }
}


select customer_id, customer_report_category, 
business_scope, customer_level, customer_ward_code, customer_status
from gold_buymed_vn2.dim_customer