config {
    type: "view",
    description: `Started time: 20240601 | PIC: tu.dang; schhedule: 0h00 daily; model type: table
    Source:
        ${source.silver}.monitoring_prd_collector_user_stats_*`,
    name: "fact_user_event_tracking_view",
    schema: "buymed_product_recommendation",
    columns: {
        event: `NonNull | All Event `,
        customer_id: " NonNull | The unique identifier for the customer",
        created_time: "NonNull | The datetime when the event was created, adjusted to the 'Asia/Ho_Chi_Minh' timezone",
        product_id: "Nullable |",
        province_code: "Nullable | " + docs.province_code,
        screen: "Nullable | The screen on which the event occurred. This provides additional context on the user interface interaction",
        source: "Nullable | The source of the event, indicating how the item was created",
        sku_code: "NonNull"| docs.sku,
        is_sku_customer_first_interaction_in_30_days: "NonNull | A boolean indicating whether this is the customer's first interaction with the SKU in the past 30 days. It's determined by checking if there are any previous interactions with the same customer_id, sku_code, and event within 30 days before the current created_time.",

    }

}


select * from gold_buymed_vn2.fact_user_event_tracking