config {
    type: "table",
    description: "Schedule: daily at 12am, 12pm | PIC: dong.le",
    tags: ["6h00", "14h00", "18h00"]
}

WITH cte_date AS (
	SELECT date_sub(date_trunc(date_sub( current_timestamp() , interval 3 day), day), interval 7 hour)  as start_date
)

, cte_checkin AS (
SELECT 
	a.po_code
	, min(a.received_time) as first_checkin_ts
FROM ${source.platinum}.warehouse_prd_inbound_receipt_session as a
GROUP BY 1
)

SELECT
	ib.po_code
	, timestamp_add(ib.created_time, interval 7 hour) as po_confirmed_ts
	, timestamp_add(ch.first_checkin_ts, interval 7 hour) as first_checkin_ts
    , timestamp_add(ib.estimated_delivery_time, interval 7 hour) as ts_expected_delivery
	, ib.warehouse_code as fc_code
	, COALESCE(po.status, ib.status) as po_status
	, ib.status as inbound_status
	, COALESCE(po.vendor_code, ib.seller_code) || '_' || ib.warehouse_code  as bi_vendor_code
	, po.payment_term
	, source_document
	, po.total_without_vat_price as total_amount_before_vat
	, po.total_price as total_amount_after_vat
	, po.original_pos
	, po.type
	, po.estimated_delivery_time as expected_delivery_ts
FROM ${source.platinum}.warehouse_prd_inbound_inbound_ticket as ib
LEFT JOIN ${source.platinum}.seller_prd_purchasing_purchase_order as po on ib.po_code = po.po_code
LEFT JOIN cte_checkin as ch on ib.po_code = ch.po_code
WHERE
	ib.status = "WAITING"