config {
  type: "table",
  description: "Source: warehouse_prd_picking_pick_ticket, warehouse_prd_picking_pick_ticket_item, only select tickets with status in (ONHOLD, PICKING, WAIT_CS, WAIT_TO_ADD, WAIT_TO_PICK) | Schedule: every 30 mins from 9am-6pm | PIC: dong.le",
  name: "fact_stock_outgoing",
  tags: ["custom_30min_9to18"],
  columns: {
    so_code: "sales order code",
    ob_status: "status of pick ticket",
    created_date: "date the pick ticket was created",
    sku_fc_key: "concatenation of sku key and warehouse code",
    sku_code: "unique sku identifier",
    fc_code: "warehouse code",
    outgoing_quantity: "order quantity from pick ticket item",
    reserved_quantity: "quantity from pick ticket item"
  },
  bigquery: {
    partitionBy: "created_date",
  }
}

WITH dedup_pick_ticket AS ${dedup.dedup(
  source.silver + `.warehouse_prd_picking_pick_ticket`,
  "ticket_id, so, warehouse_code as fc_code, status, created_time",
  "timestamp(date_sub(current_date(),interval 5 day))"
)},

dedup_pick_ticket_item AS ${dedup.dedup(
  source.silver + `.warehouse_prd_picking_pick_ticket_item`,
  "ticket_id, sku as sku_code, order_quantity, quantity",
  "timestamp(date_sub(current_date(),interval 5 day))"
)}

SELECT 
    a.so as so_code
    , b.ticket_id
    , a.status as ob_status
    , DATE(a.created_time, "Asia/Ho_Chi_Minh") as created_date
    , DATETIME(a.created_time, "Asia/Ho_Chi_Minh") as created_time
    , CONCAT(c.sku_key, "_", a.fc_code) as sku_fc_key
    , b.sku_code
    , a.fc_code
    , b.order_quantity as outgoing_quantity
    , b.quantity as reserved_quantity
    , IF(quantity = 0, 0, 1) as no_reserved_sku
    , d.inventory_price
    , SUM(b.order_quantity) OVER (PARTITION BY b.ticket_id) AS total_qty
    , SUM(b.order_quantity * d.inventory_price) OVER (PARTITION BY b.ticket_id) AS total_amt
    , COUNT(DISTINCT b.sku_code) OVER (PARTITION BY b.ticket_id) AS total_sku
FROM dedup_pick_ticket_item as b
LEFT JOIN dedup_pick_ticket as a on b.ticket_id = a.ticket_id
LEFT JOIN ${ref("dim_sku")} c on b.sku_code = c.sku_code
LEFT JOIN ${ref("dim_sku_item_pricing")} d on CONCAT(c.sku_key, "_", a.fc_code) = d.sku_fc_key
WHERE
    a.status IN ("ONHOLD", "PICKING", "WAIT_CS", "WAIT_TO_ADD", "WAIT_TO_PICK")