config {
    type: "table", 
    description: 
        ` 
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: daily at 7h30 & 15h30
        Source: 
            ${source.platinum}.warehouse_prd_inventory_transfer_sku,
            ${source.platinum}.warehouse_prd_inventory_transfer
        `,
    tags: ["7h30", "15h30"],

    bigquery: {
      partitionBy: "DATE(ts_created)",
      clusterBy: ["sku_code", "reference"]
    },
}

WITH 
    cte_date as (
        select timestamp( date_trunc( date_sub( current_date('+7'), interval 6 month) , month ) ) as start_date
    )

    , cte_origin AS (
        SELECT 
            iti.mg_id
            , iti.transfer_id
            , iti.reference
            , timestamp_add(iti.created_time, interval 7 hour) ts_created
            , iti.warehouse_code as fc_code
            , iti.status
            , iti.sku as sku_code
            , iti.from_location as location_from
            , iti.to_location as location_to
            , iti.demand_quantity
            , iti.done_quantity
            , iti.location_details
            , iti.product_id
        FROM ${source.platinum}.warehouse_prd_inventory_transfer_sku AS iti
        WHERE
            iti.created_date >= (select DATE(start_date) from cte_date)
    )

    , cte_LocationDetail AS (
        SELECT 
            a.mg_id
            , a.transfer_id
            , a.reference
            , a.ts_created
            , a.fc_code
            , a.status
            , a.sku_code
            , COALESCE(a.location_from, json_value(item.location_code)) as location_from
            , a.location_to
            , a.demand_quantity
            , COALESCE(a.done_quantity, SAFE_CAST(json_value(item.done_quantity) AS INT64)) as done_quantity
            , product_id
        FROM 
            cte_origin AS a,
            UNNEST(json_query_array(location_details)) as item
    )

    , cte_Normal AS (
        SELECT * EXCEPT (location_details)
        FROM cte_origin AS a
        WHERE
            a.mg_id not in (SELECT mg_id FROM cte_LocationDetail)
    )

    , cte_Item AS (
        SELECT * FROM cte_LocationDetail
        UNION ALL
        SELECT * FROM cte_Normal
    )

    , stock_moving AS (
        SELECT 
            a.*,
            timestamp_add(b.transfer_finish_time, interval 7 hour) as ts_moving_done
            , b.type
            , b.source_location as area_from
            , b.destination_location as area_to
            , a.sku_code || "_" || a.fc_code as sku_fc_code
            , a.location_from || "_" || a.fc_code as shelf_fc_code
            , CASE
                WHEN destination_location = "WH-MISSING" AND source_location = 'WH-MAIN' THEN "MISSING-IN"
                WHEN source_location = "WH-MISSING" AND destination_location = 'WH-MAIN' THEN "MISSING-OUT"
                WHEN destination_location = "WH-MISSING" AND source_location <> 'WH-MAIN' THEN "MISSING-OTHER"
                WHEN destination_location = "WH-DAMAGE" THEN "DAMAGE-IN"
                WHEN source_location = "WH-DAMAGE" THEN "DAMAGE-OUT"
            END AS moving_type
        FROM cte_Item AS a
            LEFT JOIN ${source.platinum}.warehouse_prd_inventory_transfer AS b on a.transfer_id = b.transfer_id
        -- WHERE
        --     b.type in ('AUDIT', 'PICK', 'INBOUND', 'INTERNAL', 'CUSTOMER_RETURN', 'MISSING', 'DAMAGE_RETURN')
    )

    , calculated_price AS (
        SELECT
            s.sku_code
            , s.sales_region_code
            , s.sku_sales_region_code
            , COALESCE(NULLIF(i.price, 0), NULLIF(s.retail_price_value, 0), NULLIF(s.purchase_price, 0)) AS sales_price
            , s.purchase_price
            , s.retail_price_value AS setting_price
            , s.seller_code
            , s.seller_class
            , s.fc_code
        FROM ${ref('dim_sku_sales_region_full')} AS s
            LEFT JOIN (
                SELECT
                    sku_code
                    , o.sales_region_code
                    , SAFE_DIVIDE(SUM(demand_quantity * sales_price) , SUM(demand_quantity)) AS price
                FROM ${ref('fact_order_item')} AS oi
                    LEFT JOIN ${ref('dim_order')} AS o USING(order_id)
                WHERE 
                    oi.created_at >= '2024-06-01'
                GROUP BY ALL
            ) AS i USING(sku_code, sales_region_code)
    )

    , alt_price AS (
            SELECT
                sku_code
                , MIN(sales_price) AS alt_price
            FROM calculated_price
            GROUP BY sku_code
    )

SELECT
    a.* EXCEPT (res)
    , DATE(a.ts_moving_done) AS moving_date
    , IF(res > 0, res, b.alt_price) AS price_unit
    , CASE fc_code
          WHEN "HN" THEN
              CASE moving_type
                  WHEN "MISSING-OUT" THEN FORMAT_DATE("%Y-%m", DATE(a.ts_moving_done))
                  ELSE IF(
                    a.ts_moving_done >= '2024-08-27',
                    IF(
                        EXTRACT(DAY FROM DATE(a.ts_moving_done)) >= 16,
                        FORMAT_DATE("%Y-%m", DATE_ADD(DATE(a.ts_moving_done), INTERVAL 1 MONTH)),
                        FORMAT_DATE("%Y-%m", DATE(a.ts_moving_done))
                    ),
                    IF(
                        EXTRACT(DAY FROM DATE(a.ts_moving_done)) >= 27,
                        FORMAT_DATE("%Y-%m", DATE_ADD(DATE(a.ts_moving_done), INTERVAL 1 MONTH)),
                        FORMAT_DATE("%Y-%m", DATE(a.ts_moving_done))
                    )
                  )
              END
          ELSE
              CASE moving_type
                  WHEN "MISSING-OUT" THEN FORMAT_DATE("%Y-%m", DATE(a.ts_moving_done))
                  ELSE IF(
                      EXTRACT(DAY FROM DATE(a.ts_moving_done)) >= 16,
                      FORMAT_DATE("%Y-%m", DATE_ADD(DATE(a.ts_moving_done), INTERVAL 1 MONTH)),
                      FORMAT_DATE("%Y-%m", DATE(a.ts_moving_done))
                  )
              END
      END AS year_month_missing
    , CONCAT(s.sku_key, "_", a.fc_code) AS sku_key_fc
FROM (
    SELECT
        sm.*
        , CASE
            WHEN area_from = "WH-MAIN" AND area_to IN ( 'WH-MISSING','WH-LOST','WH-DAMAGE') THEN
                IF(c.seller_code = 'MEDX', c.purchase_price, c.sales_price)
            WHEN area_from IN ( 'WH-MISSING','WH-LOST','WH-DAMAGE') AND area_to = "WH-MAIN" THEN
                IF(c.seller_code = 'MEDX', c.purchase_price, c.sales_price)
            ELSE c.sales_price
          END AS res
    FROM stock_moving AS sm
        LEFT JOIN calculated_price AS c
            USING(fc_code, sku_code)
) AS a
    LEFT JOIN alt_price AS b USING(sku_code)
    LEFT JOIN ${ref('dim_sku')} AS s ON a.sku_code = s.sku_code