config {
    type: "table",
    description: "Schedule: daily at 12am, 12pm | PIC: dong.le",
    name: "fact_stock_balance",
    tags: ["0h00"],
    columns: {
        // Specify columns here as needed
    }
}

SELECT
    COALESCE(i.sku_code, o.sku_code) AS sku_code,
    COALESCE(i.fc_code, o.fc_code) AS fc_code,
    COALESCE(i.location, o.location) AS location,
    l.cleaned_lot AS lot,
    e.formatted_expdate AS expired_date,
    SUM(IFNULL(i.location_done_quantity, 0)) AS incoming_qty,
    SUM(IFNULL(o.location_done_quantity, 0)) AS outgoing_qty,
    STRING_AGG(i.po_code, ', ') AS po_codes,
    STRING_AGG(o.so_code, ', ') AS so_codes
FROM
    ${ref("fact_stock_lotdate_incoming")} AS i
FULL OUTER JOIN
    ${ref("fact_stock_lotdate_outgoing")} AS o
ON i.sku_code = o.sku_code
   AND i.fc_code = o.fc_code
   AND i.location = o.location
   AND i.lot = o.lot
   AND i.expired_date = o.expired_date
LEFT JOIN ${ref("dim_lot")} l ON COALESCE(i.lot, o.lot) = l.lot
LEFT JOIN ${ref("dim_expired_date")} e ON COALESCE(i.expired_date, o.expired_date) = e.expired_date
GROUP BY ALL