config {
    type: "table",
    description: "Schedule: daily at 12am, 12pm | PIC: dong.le",
    tags: ["0h00", "12h00"],
    columns: {

    }
}

WITH cte_date AS (
  SELECT 
    DATE_SUB(CURRENT_DATE('Asia/Bangkok'), INTERVAL 30 DAY) AS start_date
)

SELECT
    pti.ticket_id,
    pti.so as order_code,
    so.status as order_status,
    pt.status as ticket_status,
    pt.warehouse_code as fc_code,
    pti.tags,
    pti.sku as sku_code,
    pti.erp_product_id as product_id,
    pti.created_date,
    pti.created_time,
    CURRENT_TIMESTAMP() AS current_time,
    TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), pti.created_time, HOUR) AS reserving_hours,
    pti.order_quantity as demand_quantity,
    pti.quantity as reserved_quantity,
    pti.order_quantity - pti.quantity AS unff_quantity
FROM ${source.platinum}.warehouse_prd_picking_pick_ticket_item pti
LEFT JOIN ${source.platinum}.warehouse_prd_picking_pick_ticket pt
ON pti.ticket_id = pt.ticket_id
LEFT JOIN ${source.platinum}.warehouse_prd_core_sale_order so
ON pti.so = so.sale_order_code
WHERE pti.created_date >= (SELECT start_date FROM cte_date)
AND pt.created_date >= (SELECT start_date FROM cte_date)
AND pt.status in ("ONHOLD", "WAIT_CS")