config {
    type: "table",
    description: "Schedule: hourly | PIC: huyen.nguyenthu",
    name: "fact_stock_balance_lotdate_near_expired",
    tags: ["custom_1h_past5"],
    columns: {
        sku_code: "unique sku identifier",
        fc: "warehouse code",
        location_code: "near expired location",
        lot: "unique identifier for a specific batch or group of items",
        expired_date: "records the expiration date",
        days_remaining: "number of days left until the expired_date",
        balance_qty: "volume + incoming_qty - outgoing_qty"
    }
}

WITH agg_stock_incoming as (SELECT
        i.sku_code,
        location_fc_code,
        COALESCE(l.lot, "N/A") as lot,
        STRING(e.formatted_expdate) as expired_date,
        SUM(location_done_quantity) AS incoming_qty
    FROM ${ref("fact_stock_lotdate_incoming")} AS i
    LEFT JOIN ${ref("dim_lot")} l ON i.lot = l.lot
    LEFT JOIN ${ref("dim_expired_date")} e ON i.expired_date = e.expired_date
    WHERE DATE(created_time) >= '2024-12-12'
      AND i.fc_code IN ('DN', 'HN')
      AND CONCAT(i.sku_code, i.location_fc_code, COALESCE(l.lot, "N/A"), STRING(e.formatted_expdate)) IN (
            SELECT CONCAT(sku_code, CONCAT(location_code, "_", fc), lot, STRING(expired_date))
            FROM collector.inventory_sku_lotdate_near_expired)
    GROUP BY ALL

    UNION ALL

    SELECT
        i.sku_code,
        location_fc_code,
        COALESCE(l.lot, "N/A") as lot,
        STRING(e.formatted_expdate) as expired_date,
        SUM(location_done_quantity) AS incoming_qty
    FROM ${ref("fact_stock_lotdate_incoming")} AS i
    LEFT JOIN ${ref("dim_lot")} l ON i.lot = l.lot
    LEFT JOIN ${ref("dim_expired_date")} e ON i.expired_date = e.expired_date
    WHERE DATE(created_time) >= '2024-12-11'
      AND i.fc_code = 'BD'
      AND CONCAT(i.sku_code, i.location_fc_code, COALESCE(l.lot, "N/A"), STRING(e.formatted_expdate)) IN (
            SELECT CONCAT(sku_code, CONCAT(location_code, "_", fc), lot, STRING(expired_date))
            FROM collector.inventory_sku_lotdate_near_expired)
    GROUP BY ALL),

without_stock_incoming as (SELECT
        e.sku_code,
        CONCAT(e.location_code, "_", e.fc) AS location_fc_code,
        COALESCE(e.lot, "N/A") as lot,
        STRING(e.expired_date) as expired_date,
        0 AS incoming_qty
    FROM collector.inventory_sku_lotdate_near_expired e
    WHERE CONCAT(sku_code, CONCAT(location_code, "_", fc), lot, COALESCE(STRING(expired_date), "NA")) NOT IN (
            SELECT CONCAT(sku_code, location_fc_code, lot, expired_date)
            FROM agg_stock_incoming)
    GROUP BY ALL),

combined_stock_incoming as (SELECT *
FROM agg_stock_incoming
UNION ALL
SELECT *
FROM without_stock_incoming
GROUP BY ALL),

agg_stock_outgoing as (SELECT
        i.sku_code,
        location_fc_code,
        COALESCE(l.lot, "N/A") as lot,
        STRING(e.formatted_expdate) as expired_date,
        SUM(location_done_quantity) AS outgoing_qty
    FROM ${ref("fact_stock_lotdate_outgoing")} AS i
    LEFT JOIN ${ref("dim_lot")} l ON i.lot = l.lot
    LEFT JOIN ${ref("dim_expired_date")} e ON i.expired_date = e.expired_date
    WHERE DATE(created_time) >= '2024-12-12'
      AND i.fc_code IN ('DN', 'HN')
      AND CONCAT(i.sku_code, i.location_fc_code, COALESCE(l.lot, "N/A"), STRING(e.formatted_expdate)) IN (
            SELECT CONCAT(sku_code, CONCAT(location_code, "_", fc), lot, STRING(expired_date))
            FROM collector.inventory_sku_lotdate_near_expired)
    GROUP BY ALL

    UNION ALL

    SELECT
        i.sku_code,
        location_fc_code,
        COALESCE(l.lot, "N/A") as lot,
        STRING(e.formatted_expdate) as expired_date,
        SUM(location_done_quantity) AS outgoing_qty
    FROM ${ref("fact_stock_lotdate_outgoing")} AS i
    LEFT JOIN ${ref("dim_lot")} l ON i.lot = l.lot
    LEFT JOIN ${ref("dim_expired_date")} e ON i.expired_date = e.expired_date
    WHERE DATE(created_time) >= '2024-12-11'
      AND i.fc_code = 'BD'
      AND CONCAT(i.sku_code, i.location_fc_code, COALESCE(l.lot, "N/A"), STRING(e.formatted_expdate)) IN (
            SELECT CONCAT(sku_code, CONCAT(location_code, "_", fc), lot, STRING(expired_date))
            FROM collector.inventory_sku_lotdate_near_expired)
    GROUP BY ALL),

without_stock_outgoing as (SELECT
        e.sku_code,
        CONCAT(e.location_code, "_", e.fc) AS location_fc_code,
        COALESCE(e.lot, "N/A") as lot,
        STRING(e.expired_date) as expired_date,
        0 AS incoming_qty
    FROM collector.inventory_sku_lotdate_near_expired e
    WHERE CONCAT(sku_code, CONCAT(location_code, "_", fc), lot, COALESCE(STRING(expired_date), "NA")) NOT IN (
            SELECT CONCAT(sku_code, location_fc_code, lot, expired_date)
            FROM agg_stock_outgoing)
    GROUP BY ALL),

combined_stock_outgoing as (SELECT *
FROM agg_stock_outgoing
UNION ALL
SELECT *
FROM without_stock_outgoing
GROUP BY ALL)

SELECT
    ne.sku_code
    , ne.location_code
    , ne.fc
    , ne.lot
    , ne.expired_date
    , DATE_DIFF(ne.expired_date, CURRENT_DATE(), DAY) as days_remaining
    , i.incoming_qty
    , o.outgoing_qty
    , SUM(ne.volume + i.incoming_qty - o.outgoing_qty) as balance_qty
FROM collector.inventory_sku_lotdate_near_expired ne
LEFT JOIN combined_stock_incoming i
    ON ne.sku_code = i.sku_code
    AND CONCAT(ne.location_code, "_", fc) = i.location_fc_code
    AND ne.lot = i.lot
    AND STRING(ne.expired_date) = i.expired_date
LEFT JOIN combined_stock_outgoing o
    ON ne.sku_code = o.sku_code
    AND CONCAT(ne.location_code, "_", fc) = o.location_fc_code
    AND ne.lot = o.lot
    AND STRING(ne.expired_date) = o.expired_date
GROUP BY ALL