config {
  type: "table",
  description: "Source: warehouse_prd_picking_pick_ticket, warehouse_prd_picking_pick_ticket_item, only select tickets with status not in (CANCEL, DRAFT) | Schedule: every 30 mins from 9am-6pm | PIC: dong.le",
  name: "fact_stock_outgoing",
  tags: ["custom_1h_past5"],
  columns: {
    so_code: "sales order code",
    ob_status: "status of pick ticket",
    created_date: "date the pick ticket was created",
    sku_fc_key: "concatenation of sku key and warehouse code",
    sku_code: "unique sku identifier",
    fc_code: "warehouse code",
    outgoing_quantity: "order quantity from pick ticket item",
    reserved_quantity: "quantity from pick ticket item"
  },
  bigquery: {
    partitionBy: "created_date",
  }
}

WITH dedup_dim_order AS (
  SELECT
    order_id,
    order_type,
    order_channel
  FROM ${ref("dim_order")} 
  QUALIFY ROW_NUMBER() OVER (PARTITION BY order_id) = 1
)

SELECT 
    a.so as so_code
    , b.ticket_id
    , a.status as ob_status
    , DATE(a.created_time, "Asia/Ho_Chi_Minh") as created_date
    , DATETIME(a.created_time, "Asia/Ho_Chi_Minh") as created_time
    , CONCAT(c.sku_key, "_", a.warehouse_code) as sku_fc_key
    , b.sku as sku_code
    , a.warehouse_code as fc_code
    , b.order_quantity as outgoing_quantity
    , b.quantity as reserved_quantity
    , IF(quantity = 0, 0, 1) as no_reserved_sku
    , COALESCE(d.inventory_price, 999) AS inventory_price
    , SUM(b.order_quantity) OVER (PARTITION BY b.ticket_id) AS total_qty
    , SUM(b.order_quantity *  COALESCE(d.inventory_price, 999)) OVER (PARTITION BY b.ticket_id) AS total_amt
    , COUNT(DISTINCT b.sku) OVER (PARTITION BY b.ticket_id) AS total_sku
FROM ${source.platinum}.warehouse_prd_picking_pick_ticket_item as b
LEFT JOIN ${source.platinum}.warehouse_prd_picking_pick_ticket as a on b.ticket_id = a.ticket_id
LEFT JOIN ${ref("dim_sku")} c on b.sku = c.sku_code
LEFT JOIN ${ref("dim_sku_item_pricing")} d on CONCAT(c.sku_key, "_", a.warehouse_code) = d.sku_fc_key
LEFT JOIN dedup_dim_order e ON a.admin_id = e.order_id
WHERE
    a.created_date >= DATE_SUB(current_date, INTERVAL 1 MONTH)
    AND b.created_date >= DATE_SUB(current_date, INTERVAL 1 MONTH)
    AND a.status NOT IN ("DRAFT", "CANCEL")
    AND e.order_type = "SO"