config {
  type: "view",
  name: "dim_tag",
}



with cte_combined as (
  select
    *
    , row_number() over (partition by tag_code order by latest_created_at desc) row_num
  from (
    select ib.* from ${ref('dim_tag_inbound')} as ib
    union all
    select ob.* from ${ref('dim_tag_outbound')} as ob
  )
)


select
  a.*
  , case 
    when search( a.tag_code , "FRAGILE" ) then "FRAGILE"
    else "NORMAL"
  end is_fragile
  , case 
    when search( a.tag_code , "FROZEN" ) then "FROZEN"
    else "NORMAL"
  end is_frozen
  , case 
    when search( a.tag_code , "SAME_DAY" ) then "SAME_DAY"
    else "NORMAL"
  end is_sameday
  , case 
    when search( a.tag_code , "URGENT" ) then "URGENT"
    else "NORMAL"
  end is_urgent
from cte_combined as a
where
  a.row_num = 1