config {
  type: "table",
  description: "Source: seller_prd_purchasing_quotation_export, seller_prd_purchasing_admin_pushing_group | Extracts data with confirmed date from the last 15 days | Schedule: 8:30 am, daily | PIC: dong.le",
  name: "fact_inventory_sys_requiring",
  tags: ["8h30"],
  columns: {
    sku_fc_key: "concatentation of product_id, seller_code, and warehouse_code",
    sku_code: "sku identifier",
    warehouse_code: "fc code",
    type: "type of the purchasing quotation export, either be NORMAL or HEDGING",
    sys_required_quantity: "quantity_expect of the purchasing quotation export",
    confirmation_date: "confirmed date from purchasing admin pushing group",
  },
  bigquery: {
    partitionBy: "confirmation_date",
  }
}

SELECT
  CONCAT(s.product_id, "_", s.seller_code, "_", q.warehouse_code) as sku_fc_key,
  q.sku as sku_code,
  q.warehouse_code as fc_code,
  q.type,
  q.quantity_expect as sys_required_quantity,
  DATE(DATETIME(p.confirmed_time, 'Asia/Ho_Chi_Minh')) as confirmation_date,
  p.group_id
FROM ${source.platinum}.seller_prd_purchasing_quotation_export q
LEFT JOIN ${source.platinum}.seller_prd_purchasing_admin_pushing_group p ON q.version = p.version
LEFT JOIN ${ref("dim_sku")} s ON q.sku = s.sku_code
WHERE DATE(DATETIME(p.confirmed_time, 'Asia/Ho_Chi_Minh')) >= DATE_SUB(CURRENT_DATE(), INTERVAL 60 DAY)