config {
    type: "incremental",
    description: 
        ` 
        Snapshot table of the list of out-of-stock SKUs from sellers.
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly
        `,
    tags: ["6h30"],
    bigquery: {
        partitionBy: "snapshot_date",
        clusterBy: ["sku_code", "item_code", "product_id"]
    }
}

SELECT 
    *
    , DATE_SUB(CURRENT_DATE("+7"), INTERVAL 1 DAY) AS snapshot_date
FROM ${ref('agg_seller_oos')}
${
    when(incremental(), 
    `WHERE 
        DATE_SUB(CURRENT_DATE("+7"), INTERVAL 1 DAY) > (SELECT MAX(snapshot_date) FROM ${self()})
        AND last_oos_time < TIMESTAMP(DATE_TRUNC(CURRENT_DATE("+7"), DAY ))    
    `
)}