config {
  type: "table",
  description: "Source: marketplace_prd_order_v2_order, marketplace_prd_order_v2_order_item | Schedule: every day at 12am | PIC: dong.le",
  name: "fact_potential_sort",
  tags: ["custom_1h_past5"],
  columns: {
    "sale_order_code": "sales order code",
    "created_date": "date the sale order was created",
    "created_time": "timestamp the sale order was created",
    "status": "status of the sale order",
    "sku_fc_key": "SKU key combined with FC code",
    "sku_code": "SKU code of the item",
    "unit_price": "unit price of from sale_order_item",
    "order_quantity": "order quantity from sale_order_item",
    "reserved_quantity": "reserved quantity from sale_order_item",
    "no_reserved_skus": "indicator if the reserved quantity of order item is greater than 0",
    "order_amount": "= unit_price * order_quantity",
    "reserved_amount": "= unit_price * reserved_quantity",
    "total_qty": "sum of order_quantity for the whole sale order",
    "total_amt": "sum of unit_price * order_quantity for the whole sale order",
    "total_sku": "total distinct SKU count for the whole sale order",
    "expected_sort": "= 50% order_quantity / total_qty + 25% order_amount / total_amt + 25% / total_sku",
    "actual_sort": "= 50% order_quantity / total_qty + 25% order_amount / total_amt + 25% no_reserved_skus / total_sku",
    "potential_sort": "expected_sort - actual_sort for in-progress statuses (DRAFT, CONFIRM, RESERVING, WAIT-TO-CHECK, CHECKING, WAIT-TO-PICK, PICKING)",
    "unFF_sort": "expected_sort - actual_sort for other statuses"
  },
  bigquery: {
    partitionBy: "created_date",
  }
}

WITH dedup_sale_order AS (
  SELECT
    sale_order_code,
    admin_id,
    warehouse_code as fc_code,
    status,
    created_time,
    created_date,
    type
  FROM ${source.platinum}.warehouse_prd_core_sale_order
  WHERE --created_date >= '2024-11-01'
  DATE(timestamp(date_sub(current_date(),interval 45 day)))
),

dedup_sale_order_item AS (
  SELECT
    a.sale_order_code,
    JSON_VALUE(b.sku) as sku_code,
    -- a.reserved_quantity,
    -- a.order_quantity,
    a.unit_price,
    a.created_time,
    a.created_date,
    a.pick_items,
    CAST(JSON_VALUE(b.order_quantity) AS INT64) as order_quantity,
    CAST(JSON_VALUE(b.reserved_quantity) AS INT64) as reserved_quantity,
    CAST(JSON_VALUE(b.first_reserved_quantity) AS INT64) as first_reserved_quantity,
  FROM ${source.platinum}.warehouse_prd_core_sale_order_item a
  , UNNEST(JSON_QUERY_ARRAY(a.pick_items)) AS b
  WHERE --created_date >= '2024-11-01'
  DATE(timestamp(date_sub(current_date(),interval 45 day)))
),

dedup_dim_order AS (
  SELECT
    order_id,
    order_type,
    order_channel,
    location_code
  FROM ${ref("dim_order")} 
  QUALIFY ROW_NUMBER() OVER (PARTITION BY order_id) = 1
),

agg_sale_order_item AS (
  SELECT DISTINCT
    a.sale_order_code,
    a.created_date,
    TIMESTAMP(DATETIME(a.created_time, "Asia/Ho_Chi_Minh")) AS created_time,
    b.status,
    d.order_channel,
    CONCAT(c.sku_key, "_", b.fc_code) AS sku_fc_key,
    a.sku_code,
    a.unit_price,
    a.order_quantity,
    IFNULL(a.reserved_quantity, 0) AS reserved_quantity,
    (a.order_quantity - IFNULL(a.reserved_quantity, 0)) AS unfulfilled_quantity,
    LEAST(a.first_reserved_quantity, a.order_quantity) AS first_reserved_quantity, -- Force frq to be <= oq
    IF(a.reserved_quantity > 0, 1, 0) AS no_reserved_skus,
    IF(a.first_reserved_quantity > 0, 1, 0) AS no_first_reserved_skus,
    a.unit_price * a.order_quantity AS order_amount,
    a.unit_price * a.reserved_quantity AS reserved_amount,
    a.unit_price * LEAST(a.first_reserved_quantity, a.order_quantity) AS first_reserved_amount, -- Adjust amount accordingly
    SUM(a.order_quantity) OVER (PARTITION BY a.sale_order_code) AS total_qty,
    SUM(a.order_quantity * a.unit_price) OVER (PARTITION BY a.sale_order_code) AS total_amt,
    COUNT(DISTINCT a.sku_code) OVER (PARTITION BY a.sale_order_code) AS total_sku,
    d.location_code
  FROM dedup_sale_order_item a
  LEFT JOIN dedup_sale_order b
    ON a.sale_order_code = b.sale_order_code
  LEFT JOIN ${ref("dim_sku")} c 
    ON a.sku_code = c.sku_code
  LEFT JOIN dedup_dim_order d 
    ON b.admin_id = d.order_id
  WHERE d.order_type = "SO" 
    AND b.status <> "CANCEL"
),


agg_sale_order_item_sort AS (
  SELECT
    *,
      COALESCE(50 * SAFE_DIVIDE(order_quantity, NULLIF(total_qty, 0)), 0)
      + COALESCE(25 * SAFE_DIVIDE(order_amount, NULLIF(total_amt, 0)), 0) 
      + COALESCE(25 * SAFE_DIVIDE(1, NULLIF(total_sku, 0)), 0) AS expected_sort,
      COALESCE(50 * SAFE_DIVIDE(reserved_quantity, NULLIF(total_qty, 0)), 0) 
      + COALESCE(25 * SAFE_DIVIDE(reserved_amount, NULLIF(total_amt, 0)), 0) 
      + COALESCE(25 * SAFE_DIVIDE(no_reserved_skus, NULLIF(total_sku, 0)), 0) AS actual_sort,
      COALESCE(50 * SAFE_DIVIDE(first_reserved_quantity, NULLIF(total_qty, 0)), 0) 
      + COALESCE(25 * SAFE_DIVIDE(first_reserved_amount, NULLIF(total_amt, 0)), 0) 
      + COALESCE(25 * SAFE_DIVIDE(no_first_reserved_skus, NULLIF(total_sku, 0)), 0) AS actual_sort_first_reserved
  FROM agg_sale_order_item
)

SELECT
  *,
  (0.5 * SAFE_DIVIDE(SUM(reserved_quantity) OVER (PARTITION BY sale_order_code), total_qty))
  + (0.25 * SAFE_DIVIDE(SUM(reserved_amount) OVER (PARTITION BY sale_order_code), total_amt)) 
  + (0.25 * LEAST(SAFE_DIVIDE(SUM(no_reserved_skus) OVER (PARTITION BY sale_order_code), total_sku), 1)) AS actual_sort_percentage_full_order,
  IF(status IN ("CHECKING", "DRAFT", "WAIT_TO_PICK", "RESERVING", "WAIT_TO_CHECK", "CONFIRM", "PICKING"), expected_sort - actual_sort, 0) AS potential_sort,
  IF(status NOT IN ("CHECKING", "DRAFT", "WAIT_TO_PICK", "RESERVING", "WAIT_TO_CHECK", "CONFIRM", "PICKING"), expected_sort - actual_sort, 0) AS unFF_sort
FROM agg_sale_order_item_sort
