config {
    type: "table",
    description: "Schedule: daily at 12am, 12pm | PIC: dong.le",
    name: "fact_stock_balance",
    tags: ["0h00"],
    columns: {
        // Specify columns here as needed
    }
}

WITH agg_stock_in AS (
    SELECT
        sku_code,
        fc_code,
        COALESCE(l.lot, "N/A") as lot,
        COALESCE(expiration_status, "N/A") as expiration_status,
        COALESCE(STRING(e.formatted_expdate), "N/A") as expired_date,
        SUM(location_done_quantity) as incoming_qty,
        STRING_AGG(i.po_code, ', ') AS po_codes
    FROM ${ref("fact_stock_lotdate_incoming")} AS i
    LEFT JOIN ${ref("dim_lot")} l ON i.lot = l.lot
    LEFT JOIN ${ref("dim_expired_date")} e ON i.expired_date = e.expired_date
    GROUP BY ALL
),

agg_stock_out AS (
    SELECT
        sku_code,
        fc_code,
        COALESCE(l.lot, "N/A") as lot,
        COALESCE(expiration_status, "N/A") as expiration_status,
        COALESCE(STRING(e.formatted_expdate), "N/A") as expired_date,
        SUM(location_done_quantity) as outgoing_qty,
        STRING_AGG(o.so_code, ', ') AS so_codes
    FROM ${ref("fact_stock_lotdate_outgoing")} AS o
    LEFT JOIN ${ref("dim_lot")} l ON o.lot = l.lot
    LEFT JOIN ${ref("dim_expired_date")} e ON o.expired_date = e.expired_date
    GROUP BY ALL
)

SELECT
    COALESCE(i.sku_code, o.sku_code) AS sku_code,
    COALESCE(i.fc_code, o.fc_code) AS fc_code,
    COALESCE(i.lot, o.lot) AS lot,
    COALESCE(i.expiration_status, o.expiration_status) AS expiration_status,
    COALESCE(i.expired_date, o.expired_date) AS expired_date,
    i.incoming_qty,
    o.outgoing_qty,
    i.incoming_qty - o.outgoing_qty as balance_qty,
    i.po_codes,
    o.so_codes
FROM
    agg_stock_in AS i
FULL OUTER JOIN
    agg_stock_out AS o
ON i.sku_code = o.sku_code
   AND i.fc_code = o.fc_code
   AND i.lot = o.lot
   AND i.expired_date = o.expired_date