config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At minute 10 every 1 hour.Circa online order `,
    tags: ['circa_online'],
    name: "circa_online_order",
    columns: {
        order_code: "NonNull |" + docs.order_code,
        customer_phone: "NonNull | The unique identifier for each customer"
       
    },
    bigquery: {
        partitionBy: "DATE_TRUNC(created_date, MONTH)"

    }
}
WITH created_by AS (
            SELECT DISTINCT order_code, event_name, action_by_name 
            FROM platinum_buymed_vn.circa_online_prd_order_order_event
            WHERE event_name  = 'CREATE_ORDER'
               OR event_name = 'ADMIN_CREATE_ORDER'
     )
, delivery_time AS (
    SELECT DISTINCT order_code
                    ,DATETIME_ADD(synced_at, INTERVAL 7 HOUR) AS last_status_time
    FROM platinum_buymed_vn.circa_online_prd_order_order_event
    -- WHERE order_code = 'DH000938'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY order_code ORDER BY synced_at DESC) = 1
)
, online_order AS (
SELECT TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR)                           AS transformed_at
      ,o.order_code
      ,order_id
      ,customer_phone
      ,customer_name
      ,receiver_code
      ,receiver_name
      ,receiver_phone_number
      ,receiver_full_address
      ,district_code
      ,province_code
      ,action_by_name                                                                AS create_order_by
      ,account_id                                                                    -- tạo tài khoản sẽ có account_id, ko tạo tk ~ acount_id = 0
      ,payment_method                                                                --Banking/COD/PAYOO/BUSINESS_WALLET
      ,payment_status                                                                --COMPLETED/WAIT_FOR_PAYMENT/NULL
      ,deliver_method                                                                --FAST/NORMAL
      ,JSON_VALUE(o.extra_props, '$.is_split_payment')                               AS is_split_payment
      ,CAST(JSON_VALUE(o.extra_props, '$.wallet_paid_amount') AS INT64)              AS wallet_paid_amount
      ,CAST(JSON_VALUE(o.extra_props, '$.secondary_pay_amount') AS INT64)            AS secondary_pay_amount
      ,JSON_VALUE(o.extra_props, '$.secondary_pay_method')                           AS secondary_pay_method
      ,price
      ,total_price
      ,total_discount
      ,delivery_method_fee - CAST(JSON_VALUE(o.extra_props, '$.discount_delivery_fee') AS INT64 ) AS delivery_method_fee
      ,JSON_VALUE(o.extra_props, '$.delivery_tags')                                  AS delivery_tags
      ,JSON_VALUE(o.extra_props, '$.discount_delivery_fee')                          AS discount_delivery_fee
      ,total_product
      ,DATETIME_ADD(created_time, INTERVAL 7 hour)                                   AS created_time
      ,DATE(DATETIME_ADD(created_time, INTERVAL 7 hour))                             AS created_date
      ,DATETIME_ADD(last_updated_time, INTERVAL 7 hour)                              AS last_updated_time
     -- ,DATETIME_ADD(delivery_date, INTERVAL 7 hour)                                  AS delivery_time
      ,DATETIME_ADD(paid_time, INTERVAL 7 hour)                                      AS paid_time
      ,DATETIME_ADD(platinum_refresh, INTERVAL 7 hour)                               AS platinum_refresh
      ,l.last_status_time
      ,o.type                                                                        AS customer_type
      ,o.status                                                                      AS o2o_status -- DELIVERED/WAIT_TO_DELIVER/WAIT_TO_CONFIRM/CANCEL  
      ,o.cancellation_type
      ,o.cancellation_note
      ,sale_order_status                                                             --NULL/WAIT_TO_DELIVER/NEW/DELIVERED/CANCELED/FAIL_TO_DELIVER
      ,i.order_code                                                                  AS assigned_order_codes
      ,i.pos_id                                                                      AS assigned_pos_id  
      ,p.code                                                                        AS assigned_pos_code 
      ,p.name                                                                        AS assigned_pos_name
FROM platinum_buymed_vn.circa_online_prd_order_order o 
LEFT JOIN (
    SELECT DISTINCT order_code, reference_order_in_platform, pos_id
    FROM ${source.ref}.cos_fact_order 
    WHERE channel = 'O2O' 
         -- AND status IN ('COMPLETED', 'COMPLETE_SHIPPING','AWAITING_SHIPMENT','SHIPPING','FAILED_SHIPMENT','PICKING')
   QUALIFY ROW_NUMBER() OVER (PARTITION BY reference_order_in_platform ORDER BY order_code DESC) = 1
    ) i ON o.order_code = i.reference_order_in_platform
LEFT JOIN created_by c ON c.order_code = o.order_code
LEFT JOIN delivery_time l ON l.order_code = o.order_code
LEFT JOIN ${source.ref}.circa_pos_profile p on i.pos_id = p.id


),map_deliver AS (
SELECT DISTINCT o.*
       ,s.sender_name
       ,s.status
       ,s.pick_address
       ,s.pos_status
       ,s.deliver_status
       ,s.delivery_carrier
       ,v.voucher_code AS voucher_code 
FROM online_order o
LEFT JOIN ${source.ref}.cos_voucher_info v ON o.assigned_order_codes = v.order_code_used
LEFT JOIN (SELECT * FROM ${source.platinum}.circa_online_prd_order_sale_order
           QUALIFY ROW_NUMBER () OVER (PARTITION BY order_code ORDER BY created_time DESC) = 1       
        ) s ON o.order_code = s.order_code 
--WHERE sender_name <> 'Cửa hàng Tech Test 1'
), location as (
     SELECT distinct district_code
                   , district_name
                   , province_code
                   , province_name
FROM `gold_buymed_vn2.dim_geo_location`
)
SELECT o.* except(delivery_tags)
       ,CASE WHEN delivery_tags = 'giao-30ph' OR delivery_tags = '30ph' THEN '1. giao-30ph'
             WHEN delivery_tags = 'giao-2h' THEN '2. giao-2h'
             WHEN delivery_tags = 'giao-24h' THEN '3. giao-24h'
             WHEN delivery_tags = 'giao-96h' THEN  '4. giao-96h'
             END AS delivery_tags
       ,m.district_name
       ,m.province_name
       ,CASE
  WHEN  o2o_status <>  'CANCELED' THEN NULL
  -- 1. Thanh toán
  WHEN cancellation_type IN ('PAYMENT_EXPIRED', 'UPDATE_PAYMENT_METHOD', 'VOUCHER_ISSUE')
    THEN 'Vấn đề thanh toán'
  WHEN cancellation_type = 'OTHER'
    AND (
       cancellation_note LIKE '%PTTT%'
      OR cancellation_note LIKE '%phương thức thanh toán%'
      OR (cancellation_note LIKE '%mã giảm giá%'AND cancellation_note NOT LIKE '%cheating%' AND cancellation_note NOT LIKE '%phát sinh nhiều đơn hàng%')
      OR cancellation_note LIKE '%mã km%'
      OR cancellation_note LIKE '%voucher%'
      OR cancellation_note LIKE '%chưa áp%'
      OR cancellation_note LIKE '%chưa nhập mã%'
    )
    THEN 'Vấn đề thanh toán'

  -- 2. Hàng hóa / Tồn kho
  WHEN cancellation_type IN ('CUSTOMER_CANCEL_OR_OUT_OF_STOCK', 'PHARMACY_OUT_OF_STOCK')
    THEN 'Hàng hóa / Tồn kho'
  WHEN cancellation_type = 'CUSTOMER_CHANGES_MIND'
    AND (
      cancellation_note LIKE '%hết hàng%'
      OR cancellation_note LIKE '%không có hàng%'
      OR cancellation_note LIKE '%chờ nhập hàng%'
      OR cancellation_note LIKE '%cận date%'
    )
    THEN 'Hàng hóa / Tồn kho'
  WHEN cancellation_type = 'OTHER'
    AND (
      cancellation_note LIKE '%hết hàng%'
      OR cancellation_note LIKE '%không có hàng%'
      OR cancellation_note LIKE '%không đủ số lượng%'
      OR cancellation_note LIKE '%cận date%'
      OR cancellation_note LIKE '%hết date%'
    )
    THEN 'Hàng hóa / Tồn kho'

  -- 3. Gian lận / Rủi ro
  WHEN cancellation_type IN ('CUSTOMER_CHEATING', 'CUSTOMER_CANNOT_BE_CONTACTED', 'FAIL_TO_DELIVER')
    THEN 'Gian lận / Rủi ro / Gom đơn'
  WHEN cancellation_type = 'OTHER'
    AND (
      cancellation_note LIKE '%gom%'
      OR cancellation_note LIKE '%cheating%'
      OR cancellation_note LIKE '%thuốc sỉ%'
      OR cancellation_note LIKE '%sỉ%'
      OR cancellation_note LIKE '%giới hạn số lượng%'
      OR cancellation_note LIKE '%nghi ngờ%'
      OR cancellation_note LIKE '%Nghi ngờ%'
      OR cancellation_note LIKE '%địa chỉ không rõ%'
    )
    THEN 'Gian lận / Rủi ro / Gom đơn'

  -- 4. Đặt lại
  WHEN cancellation_type = 'CUSTOMER_ALREADY_REORDERED'
    THEN 'Đặt lại'
  WHEN cancellation_type = 'OTHER'
    AND (
       cancellation_note LIKE '%trùng đơn%'
      OR cancellation_note LIKE '%đặt lại%'
      OR cancellation_note LIKE '%đặt trùng%'
    )
    THEN 'Đặt lại'
  WHEN cancellation_type = 'CUSTOMER_CHANGES_MIND'
    AND (
      cancellation_note LIKE '%đặt lại%'
      OR cancellation_note LIKE '%đơn mới%'
    )
    THEN 'Đặt lại'

  -- 5. Cập nhật thông tin đơn
  WHEN cancellation_type IN ('UPDATE_ITEM_INFO', 'UPDATE_PHONE_OR_ADDRESS')
    THEN 'Cập nhật thông tin đơn'
  WHEN cancellation_type = 'OTHER'
    AND (
      cancellation_note LIKE '%địa chỉ%'
      OR cancellation_note LIKE '%SĐT%'
      OR cancellation_note LIKE '%số điện thoại%'
      OR cancellation_note LIKE '%thay đổi sản phẩm%'
    )
    THEN 'Cập nhật thông tin đơn'
  WHEN cancellation_type = 'CUSTOMER_CHANGES_MIND'
    AND cancellation_note LIKE '%địa chỉ%'
    THEN 'Cập nhật thông tin đơn'

  -- 6. Khách đổi ý
  WHEN cancellation_type IN ('CUSTOMER_CHANGES_MIND', 'CUSTOMER_ORDER_BY_MISTAKE', 'NOT_NEEDED')
    THEN 'Khách đổi ý'
  WHEN cancellation_type = 'OTHER'
    AND (
      cancellation_note LIKE '%không còn nhu cầu%'
      OR cancellation_note LIKE '%đổi ý%'
      OR cancellation_note LIKE '%không chờ%'
      OR cancellation_note LIKE '%cần gấp%'
    )
    THEN 'Khách đổi ý'

  -- 7. Lỗi hệ thống
  WHEN cancellation_type = 'SYSTEM_INTERNAL_ERROR'
    THEN 'Lỗi hệ thống'

  ELSE 'Chưa phân loại'
END AS cancel_group
FROM map_deliver o
LEFT JOIN location m ON o.district_code = m.district_code AND o.province_code = m.province_code
WHERE order_code NOT IN (SELECT DISTINCT order_code FROM map_deliver WHERE  sender_name IN ( 'Cửa hàng Tech Test 1'))