config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At minute 10 every 1 hour.Circa online order `,
    tags: ['circa-chat'],
    name: "circa_chat_users",
    columns: {

       
    },
    bigquery: {

    }
}

SELECT DISTINCT user_id 
               ,total_sessions
               ,total_messages
               ,last_session_id
               ,created_at AS user_created_at
               ,source
               ,address
               ,name
               ,phone
FROM platinum_buymed_vn.circa_chat_users 





