config {
    type: "table",
    description: 
        `
        Detailed information of the inbound tickets;
        PIC: nguyen.tran; 
        Type: Table; 
		Refresh Schedule: hourly;
        Source: 
            ${source.platinum}.seller_prd_purchasing_purchase_order,
            ${source.platinum}.warehouse_prd_inbound_inbound_ticket
        `,
    tags: ["INBOUND", "custom_1h_past5"],
    columns: {
		ticket_id: 'inbound ticket ID',
		fc_code: 'fc_code of ticket',
		inbound_code: "inbound ticket code",
		po_code: 'Purchase Order/PGH of Seller/Transfer Order',
		partner_code: "Vendor code for PO, Seller code for PGH",
		order_type: 'Including PO, PGH, TO & OTHER',
		inbound_type: "Including NORMAL, REPLENISHMENT, RECEIPTGIFTPRODUCTS, HEDGING, IT",
		inbound_priority: 'The priority level of inbound ticket',
		inbound_status: 'The status of inbound ticket',
		po_confirmed_ts: 'The timestamp when PO/PGH/TO was confirmed',
		total_sku: 'Number of SKUs in inbound ticket',
		total_item: 'Total Quantity in inbound ticket',
		po_status: 'The status of PO',
		po_bill_status: 'The payment status of the bill for PO/PGH/TO'
	}
}

WITH cte_date AS (
    SELECT
		  date_sub(timestamp_sub(timestamp(date_trunc(date_sub( current_date('+7'), interval 3 month), month)),interval 14 day) , interval 7 hour) as start_date
),

	check_it_popgh AS (
		with cte_data as (
			select po_code, 
				created_ts, -- as receipt_at , 
				received_ts,
				receipt_code, -- b.code,
				receipt_fc_code, --b.warehouse_code,
				destination_location, -- b.destination_warehouse_code,
				-- SPLIT(receipt_code, '-')[OFFSET(1)] as received_hub, 
				case 
					when receipt_fc_code is null then null
					when receipt_fc_code = 'TTN' and destination_location = 'BD' then false
					when receipt_fc_code != destination_location then true
					when receipt_fc_code = destination_location then false
					-- else false
				end as flag_check
				from ${ref('fact_inbound_receipts')}
				where received_packages > 0
					AND status <> "CANCEL"
			)

		select *, -- except (flag_check),
			max(flag_check) over (partition by po_code) as is_it_po_pgh
		from cte_data
        where receipt_fc_code IS NOT NULL
		qualify row_number() over (partition by po_code order by received_ts) = 1 -- and is_across_region = true
	),

	first_checkin_destination_fc AS (
		SELECT
			po_code
			, MIN(received_ts) AS first_checkin_destination_fc
		FROM ${ref('fact_inbound_receipts')}
		WHERE receipt_fc_code = destination_location
		GROUP BY 1
	),

	first_location AS (
		SELECT
			po_code
			, MIN_BY(hub_code, received_ts) AS first_received_location
            , MIN(IF(hub_code NOT IN ('HN','BD','DN'), received_ts, NULL)) AS first_received_time_at_hub
		FROM ${ref('fact_inbound_receipts')}
		-- WHERE receipt_fc_code = destination_location
		GROUP BY 1
	)

select
	i.ticket_id,
	i.warehouse_code as fc_code,
	i.code as inbound_code,
	i.po_code,
	case
		when i.seller_code in ('MEDX-HN', 'MEDX', 'MED_NT', 'MEDX_E', 'MARKETING', 'TENDER') then p.vendor_code
		else i.seller_code
	end partner_code,
    case when i.external_type = 'PURCHASE_SYS' then 'PO'
        when i.external_type = 'SELLER' then 'PGH'
        when i.external_type = 'TRANSFER' then 'TO'
        else 'OTHER'
	end as order_type, 
	CASE
		when i.external_type = 'PURCHASE_SYS' then 'INTERNAL'
        when i.external_type = 'SELLER' then 'EXTERNAL'
		when i.external_type = 'TRANSFER' then 'TO'
	END AS seller_class,
	i.type as inbound_type,
	i.priority as inbound_priority,
	i.status as inbound_status,
	timestamp_add(i.created_time, interval 7 hour) as po_confirmed_ts,
	i.total_sku,
	i.total_item,
	to_json_string(i.tags) as tags,
	p.source_document,
	p.status as po_status,
	p.bill_status as po_bill_status,
	c.received_ts AS first_received_check_in,
	l.first_received_location,
	l.first_received_time_at_hub,
	c.receipt_fc_code,
	f.first_checkin_destination_fc,
	c.is_it_po_pgh,
    TIMESTAMP_ADD(TIMESTAMP(JSON_VALUE(i.extra_props, '$.add_urgent_tag_time')), INTERVAL 7 HOUR) AS add_urgent_tag_time,
	CASE
        WHEN f.first_checkin_destination_fc IS NOT NULL AND TIMESTAMP(JSON_VALUE(i.extra_props, '$.add_urgent_tag_time')) IS NOT NULL THEN 
            IF(
				TIMESTAMP_ADD(TIMESTAMP(JSON_VALUE(i.extra_props, '$.add_urgent_tag_time')), INTERVAL 7 HOUR) 
					<= f.first_checkin_destination_fc
				, "URGENT_AT_CHECK-IN"
				, "URGENT_AFTER_INBOUND"
			) 
	END AS po_urgent,
	p.type AS po_type,
	COALESCE(TIMESTAMP_ADD(p.created_time, interval 7 hour), TIMESTAMP_ADD(ps.created_time, interval 7 hour)) AS po_created_ts

from (
    select *
    from ${source.platinum}.warehouse_prd_inbound_inbound_ticket
    where created_date >= (select DATE(start_date) from cte_date)
) i
    left join (
        select *
        from ${source.platinum}.seller_prd_purchasing_purchase_order
        where created_date >= (select DATE(start_date) from cte_date)
    ) as p on i.po_code = p.po_code
    left join (
        select *
        from ${source.platinum}.seller_prd_wis_inbound
        where created_date >= (select DATE(start_date) from cte_date)
    ) as ps on i.po_code = ps.inbound_code
    LEFT JOIN check_it_popgh AS c ON c.po_code = i.po_code
	LEFT JOIN first_checkin_destination_fc AS f ON f.po_code = i.po_code
	LEFT JOIN first_location AS l ON l.po_code = i.po_code
