config {
    type: "table",
    description: 
        `
        Items in inbound ticket;
        PIC: nguyen.tran; 
        Type: Table;
        Schedule Refresh: hourly;
        Source:
            ${source.platinum}.warehouse_prd_inbound_inbound_ticket_item
        `,
    tags:["custom_1h_past5"],
    columns:{
        ticket_id : 'Id phiếu inbound',
        parent_code: 'Đơn PO/PGH/TO nhập kho',
        sku_code: 'Mã SKU',
        qty_start: 'Số lượng item trong đơn nhập kho trước khi kiểm',
        qty_done: 'Số lượng item trong đơn nhập kho sau khi kiểm'
    }
}

WITH cte_date AS (
    SELECT
		  date_sub(timestamp(date_trunc(date_sub( current_date('+7'), interval 4 month), month)) , interval 7 hour) as start_date
)

select
	a.ticket_id,
    a.po_code as parent_code,
	a.sku as sku_code,
	a.demand_quantity as qty_start,
	a.inbound_quantity as qty_done
from ${source.platinum}.warehouse_prd_inbound_inbound_ticket_item as a
where created_date >= (select DATE(start_date) from cte_date)