config {
    type: 'operations',
    schema: "buymed_circa_recommendation",
    description: `All active product of web Circa.`,
    tags: [ "custom_1h_past10"]
}

TRUNCATE TABLE 
`buymed_circa_recommendation.circa_fact_order_completed`;


INSERT INTO 
`buymed_circa_recommendation.circa_fact_order_completed`
(
  eventType, visitorId, eventTime, purchaseTransaction, productDetails

)


WITH base_data AS (
  SELECT
      t.product_id
    , t.unit
    , CAST(JSON_VALUE(t.extra_props, '$.reserved_quantity') AS INT64) AS quantity
    , t.order_code
    , t.total_price
    , b.customer_phone
    , b.created_time
  FROM lakehouse-prod-394907.platinum_buymed_vn.circa_online_prd_order_order_item t
  LEFT JOIN platinum_buymed_vn.circa_online_prd_order_order b
    ON t.order_code = b.order_code
  WHERE b.status = 'DELIVERED'
   -- AND b.order_code = 'DH010546'
)

, final AS (
  SELECT
      a.*
    , cv.convert_rate
    , a.quantity * cv.convert_rate AS base_quantity
    , cv.base_unit
  FROM base_data a
  LEFT JOIN (SELECT * FROM buymed_circa_v2.product_retail_unit WHERE client_id = 1) cv  ON a.product_id = cv.product_id
                                                    AND LOWER(a.unit) = LOWER(cv.unit)
  WHERE quantity > 0
)

, product_level AS (
  SELECT
      order_code
    , customer_phone
    , created_time
    , product_id
    , unit
    , SUM(quantity) AS quantity
    , SUM(base_quantity) AS base_quantity
    , SUM(total_price) AS total_price
  FROM final
  GROUP BY ALL
), unit AS (
SELECT
  DISTINCT product_id
  ,JSON_VALUE(unit, '$.is_default') AS is_default
  ,JSON_VALUE(unit, '$.unit_name') AS unit_name
  ,JSON_VALUE(unit, '$.value') AS unit_value
  
FROM
 platinum_buymed_vn.circa_online_prd_product_product t,
  UNNEST(JSON_EXTRACT_ARRAY(t.retail_units)) AS unit
  WHERE JSON_VALUE(unit, '$.is_default') = 'true'
         AND JSON_VALUE(unit, '$.status') = 'ACTIVE'
)
SELECT
    "purchase-complete" AS eventType
  , customer_phone AS visitorId
  , FORMAT_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', created_time) AS eventTime
 , [STRUCT(
        CAST(SUM(total_price) AS FLOAT64) AS revenue
      , "VND" AS currencyCode
    )] AS purchaseTransaction
  , ARRAY_AGG(
        STRUCT(
            STRUCT(
                CAST(a.product_id AS STRING) AS id
            ) AS product
          , CAST(ROUND(SAFE_DIVIDE(base_quantity, COALESCE(CAST(unit_value AS INT64),1)), 3) as int64) AS quantity
        )
        ORDER BY a.product_id 
    ) AS productDetails
FROM product_level a
LEFT JOIN unit b ON a.product_id = b.product_id AND LOWER(a.unit) = LOWER(b.unit_name)
GROUP BY ALL