config {
  type: "incremental",
  schema: "buymed_circa_recommendation",
  name: "circa_fact_add_to_cart",
  tags: ["custom_1h_past10"],
  protected: true
}


pre_operations {

  ${when(incremental(), `

    DELETE FROM ${self()}
    WHERE DATE(
      TIMESTAMP(eventTime),
      'Asia/Ho_Chi_Minh'
    ) >= DATE_SUB(
      CURRENT_DATE('Asia/Ho_Chi_Minh'),
      INTERVAL 10 DAY
    );

  `)}

}

WITH unit AS (

    SELECT DISTINCT
        product_id,
        JSON_VALUE(unit, '$.unit_name') AS unit_name,
        CAST(JSON_VALUE(unit, '$.value') AS INT64) AS unit_value

    FROM
        platinum_buymed_vn.circa_online_prd_product_product t,
        UNNEST(JSON_EXTRACT_ARRAY(t.retail_units)) AS unit

    WHERE JSON_VALUE(unit, '$.is_default') = 'true'
      AND JSON_VALUE(unit, '$.status') = 'ACTIVE'

)
, base_data AS (

    SELECT
        t.* EXCEPT(
            customer_phone,
            extra_props
        ),

        JSON_VALUE(
            t.extra_props,
            '$.unit'
        ) AS unit,

        FIRST_VALUE(
            t.customer_phone IGNORE NULLS
        ) OVER (
            PARTITION BY t.session_id
            ORDER BY t.created_time
            ROWS BETWEEN UNBOUNDED PRECEDING
                     AND UNBOUNDED FOLLOWING
        ) AS customer_phone  -- huyen.ngo

    FROM platinum_buymed_vn.circa_online_prd_consumer_tracking_events t
    WHERE
        t.created_date >= DATE_SUB(
            CURRENT_DATE('Asia/Ho_Chi_Minh'),
            INTERVAL 10 DAY
        )

)
, final_data AS (

    SELECT
        t.* EXCEPT(quantity)
        , CAST(
            CASE

                WHEN t.unit IS NOT NULL
                THEN
                    t.quantity
                    * COALESCE(bu.convert_rate, 1)

                WHEN t.unit IS NULL
                THEN
                    SAFE_DIVIDE(
                        t.quantity,
                        COALESCE(u.unit_value, 1)
                    )

            END
        AS INT64) AS quantity
    FROM base_data t
    LEFT JOIN gold_buymed_vn2.circa_dim_retail_unit bu ON t.unit IS NOT NULL
        AND t.product_id = bu.product_id
        AND LOWER(t.unit) = LOWER(bu.convert_unit)
    LEFT JOIN unit u ON t.unit IS NULL
        AND t.product_id = u.product_id
)

SELECT

    'add-to-cart' AS eventType
   , customer_phone AS visitorId
    ,FORMAT_TIMESTAMP(
        '%Y-%m-%dT%H:%M:%SZ',
        created_time
    ) AS eventTime,    [
        STRUCT(
            STRUCT(
                CAST(product_id AS STRING) AS id
            ) AS product,

            quantity AS quantity
        )
    ] AS productDetails
FROM final_data
WHERE event_type = 'add_to_cart' AND product_id IS NOT NULL
     AND customer_phone IS NOT NULL