config {
    type: 'operations',
    schema: "buymed_circa_recommendation",
    description: `All active product of web Circa.`,
    tags: [ "custom_1h_past10"]
}

TRUNCATE TABLE 
`buymed_circa_recommendation.circa_fact_order_completed`;


INSERT INTO 
`buymed_circa_recommendation.circa_fact_order_completed`
(
  eventType, visitorId, eventTime, purchaseTransaction, productDetails, attributes

)

WITH base_unit_selection AS (
    SELECT
         product_id
        ,client_id
        ,base_unit
        ,ROW_NUMBER() OVER (
            PARTITION BY product_id, client_id
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM gold_buymed_vn2.cos_product_convert_base_unit
    GROUP BY ALL
)
,base_unit AS (
    SELECT
         a.*
    FROM gold_buymed_vn2.cos_product_convert_base_unit a
    LEFT JOIN base_unit_selection b
        ON a.product_id = b.product_id
        AND a.client_id = b.client_id
        AND a.base_unit = b.base_unit
    WHERE b.rn = 1
), return_detail AS (
SELECT o.code
      , order_code
       ,i.product_id
      , i.unit
      , i.sku_code
      , i.lot_date
      , o.client_id
      , CASE WHEN SUM(received_quantity) > 0 THEN SUM(received_quantity)
           ELSE SUM(i.quantity) END AS quantity
FROM `buymed_circa_v2.order_return_order` o  
LEFT JOIN (SELECT code AS order_code, return_codes  FROM buymed_circa_v2.order_order
    LEFT JOIN UNNEST(JSON_VALUE_ARRAY(order_return_codes)) AS return_codes
    WHERE return_codes IS NOT NULL ) r ON o.code = r.return_codes
LEFT JOIN `buymed_circa_v2.order_return_order_item` i ON o.id = i.return_order_id
WHERE o.status = 'COMPLETED'
GROUP BY ALL
), rt AS (
SELECT o.order_code
      , o.product_id
      , unit
      , sku_code
      , lot_date
      , o.client_id
      , SUM(quantity) AS quantity_return
      , SUM( quantity * COALESCE(t.convert_rate, 1) ) AS base_quantity_return
FROM return_detail o
LEFT JOIN base_unit t ON o.client_id = t.client_id AND o.product_id = t.product_id AND LOWER(t.convert_unit) = LOWER(o.unit)
--WHERE order_code = 'DHC00991602'
GROUP BY ALL
), base_data AS (
SELECT CASE WHEN o.type = 'ONLINE' THEN DATETIME(ol.created_time, 'Asia/Ho_Chi_Minh')
             ELSE DATETIME(o.created_at, 'Asia/Ho_Chi_Minh') END AS created_at
    ,  o.code AS order_code
    , o.client_id
    , o.status
    , i.product_id
    , i.unit
    , i.sku_code
    , i.lot_date
    , i.quantity - COALESCE(rt.quantity_return, 0) AS quantity
    , i.quantity * COALESCE(t.convert_rate, 1)  - COALESCE(rt.base_quantity_return, 0) AS base_quantity
    , CASE
        WHEN NULLIF(i.order_apply_combo_id, '') IS NOT NULL
        THEN COALESCE(ROUND(
            SAFE_DIVIDE(
                (c.combo_price - c.discount_amount)
                * c.quantity
                * SAFE_DIVIDE(
                    i.system_price * i.quantity,
                    SUM(i.system_price * i.quantity) OVER (
                        PARTITION BY o.id, i.order_apply_combo_id
                    )
                ),
                i.quantity
            )
        ), 0)
        ELSE i.unit_price
      END AS unit_price
      , CASE WHEN o.type = 'ONLINE' THEN ol.customer_phone ELSE CONCAT(0,m.phone_number) END AS customer_phone
      , JSON_VALUE(m.tags, '$[0]') AS tag
      , lo.province_name
      , p.code AS pos_code
      , CASE WHEN o.type = 'ONLINE' THEN cus.gender ELSE m.gender END AS gender
      , CASE
          WHEN o.type = 'ONLINE' THEN
            CASE
              WHEN online_dob IS NULL THEN NULL
              WHEN online_age < 18 THEN '<18'
              WHEN online_age BETWEEN 18 AND 27 THEN '18-27'
              WHEN online_age BETWEEN 28 AND 43 THEN '28-43'
              WHEN online_age BETWEEN 44 AND 59 THEN '44-59'
              ELSE '>=60'
            END
          ELSE
            CASE JSON_VALUE(m.tags, '$[0]')
              WHEN 'UNDER_18'    THEN '<18'
              WHEN 'GEN_Z'       THEN '18-27'
              WHEN 'MILLENNIALS' THEN '28-43'
              WHEN 'GEN_X'       THEN '44-59'
              WHEN 'OLDER'       THEN '>=60'
              ELSE NULL
            END
        END AS age_group
FROM `buymed_circa_v2.order_order` AS o
LEFT JOIN platinum_buymed_vn.circa_online_prd_order_order ol ON o.reference_order_in_platform = ol.order_code
LEFT JOIN platinum_buymed_vn.circa_online_prd_consumer_customer cus ON ol.account_id = cus.account_id
LEFT JOIN UNNEST([SAFE_CAST(SUBSTR(JSON_VALUE(cus.extra_props, '$.date_of_birth'), 1, 10) AS DATE)]) AS online_dob
LEFT JOIN UNNEST([
    DATE_DIFF(CURRENT_DATE('Asia/Ho_Chi_Minh'), online_dob, YEAR)
    - IF(FORMAT_DATE('%m%d', online_dob) > FORMAT_DATE('%m%d', CURRENT_DATE('Asia/Ho_Chi_Minh')), 1, 0)
]) AS online_age
LEFT JOIN `buymed_circa_v2.order_order_item` AS i ON o.id = i.order_id
LEFT JOIN rt
    ON o.code = rt.order_code
    AND i.product_id = rt.product_id
    AND LOWER(i.unit) = LOWER(rt.unit)
    AND i.sku_code = rt.sku_code
    AND i.lot_date IS NOT DISTINCT FROM rt.lot_date
LEFT JOIN base_unit AS t
    ON o.client_id = t.client_id
    AND i.product_id = t.product_id
    AND LOWER(t.convert_unit) = LOWER(i.unit)
LEFT JOIN `lakehouse-prod-394907.buymed_circa_v2.order_order_apply_combo` AS c ON i.order_apply_combo_id = c.id
LEFT JOIN `gold_buymed_vn2.circa_pos_profile` p ON o.pos_id = p.id
LEFT JOIN `buymed_circa_v2.entity_customer` m ON o.entity_id = m.id
LEFT JOIN (SELECT DISTINCT province_code, province_name FROM `gold_buymed_vn2.dim_geo_location`) lo ON p.province = lo.province_code
WHERE  o.status IN ('COMPLETED', 'COMPLETE_SHIPPING')
     AND o.created_date >= DATE_SUB(CURRENT_DATE('Asia/Ho_Chi_Minh'), INTERVAL 1 YEAR)
     AND o.client_id = 1
     AND i.product_id IS NOT NULL
)
SELECT
    "purchase-complete" AS eventType
  , customer_phone AS visitorId
  , FORMAT_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', created_at) AS eventTime
 , STRUCT(
        CAST(SUM(quantity * unit_price) AS FLOAT64) AS revenue
      , "VND" AS currencyCode
    ) AS purchaseTransaction
 
  , ARRAY_AGG(
  STRUCT(
    STRUCT(
      CAST(product_id AS STRING) AS id
    ) AS product,
    SUM(base_quantity) AS quantity
  )
  IGNORE NULLS
  GROUP BY product_id
) AS productDetails
  ,STRUCT(
    STRUCT([COALESCE(gender, '')] AS text) AS gender
    ,STRUCT([COALESCE(age_group, '')] AS text) AS age_group
    ,STRUCT([COALESCE(province_name, '')] AS text) AS area
    ,STRUCT([COALESCE(pos_code, '')] AS text) AS store_code
) AS attributes
--   , STRUCT(
--   STRUCT([gender]) AS gender,
--   STRUCT([age_group]) AS age_group,
--   STRUCT([province_name]) AS area,
--   STRUCT([pos_code]) AS store_code
-- ) AS attributes

FROM base_data
WHERE customer_phone <> '0000000000'
GROUP BY customer_phone
    ,created_at
    ,gender
    ,age_group
    ,province_name
    ,pos_code