
config {
    type: "incremental",
    name: "staging_marketplace_prd_cart_cart_item_deleted_backup",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id'
    },
    bigquery: {
        partitionBy: "created_date"
    }
}

pre_operations {
  ${
    when(incremental(),
      `
      CREATE OR REPLACE TEMP TABLE range_created_time_table AS
      SELECT MIN(DATE(created_time)) AS min_created_date, MAX(DATE(created_time)) AS max_created_date
      FROM ${source.silver}.marketplace_prd_cart_cart_item_deleted_backup WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()});
      `,
      ``
    )
  }
}

SELECT
 *,
 WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
FROM ${source.silver}.marketplace_prd_cart_cart_item_deleted_backup o 
  ${ when(incremental(), `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()})`)}
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)

post_operations {
  ${
    when(incremental(),
      `
      -- Delete rows using the temporary table
      DELETE FROM ${self()}
      WHERE created_date BETWEEN (SELECT min_created_date FROM range_created_time_table) 
        AND (SELECT max_created_date FROM range_created_time_table)
          and 
         (key) IN (
        SELECT (key) FROM ${self()} where created_date BETWEEN (SELECT min_created_date FROM range_created_time_table) 
        AND (SELECT max_created_date FROM range_created_time_table) 
        QUALIFY ROW_NUMBER() OVER (_window) > 1
        OR FIRST_VALUE(action) OVER (_window) = "d"
      WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC,
        IF(action = 'd', 3, IF(action = 'u', 2, 1)) DESC,
        last_updated_time DESC
      )
      ) ;
      `,
      ``
    )
  }
}
