
config {
    type: "incremental",
    name: "staging_marketplace_prd_cart_cart_item",
    schema: "platinum_buymed_vn",
    assertions: {
         uniqueKey: 'mg_id',
         nonNull: ['created_date'],
         rowConditions: [
        '(created_time is not null and last_updated_time is not null) or (created_time is null and last_updated_time is not null) or (created_time is not null and last_updated_time is null)',
        'action != "d"'
        
    ]
     },
    bigquery: {
        partitionBy: "created_date"
    }
}

pre_operations {
  ${
    when(incremental(), 
      `
      CREATE OR REPLACE TEMP TABLE range_created_time_table AS
      SELECT 
        MIN(created_date) AS min_created_date, 
        MAX(created_date) AS max_created_date 
      FROM (
        SELECT  
          CASE 
            WHEN created_time IS NOT NULL THEN DATE(created_time) 
            ELSE DATE(last_updated_time) 
          END AS created_date
        FROM ${source.silver}.marketplace_prd_cart_cart_item WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()}) AND 
        ((created_time IS NOT NULL AND last_updated_time IS NOT NULL) OR 
        (created_time IS NULL AND last_updated_time IS NOT NULL) OR 
        (created_time IS NOT NULL AND last_updated_time IS NULL)) AND action = "u"

      
      )
      `
    )
  }
}

-- for marketplace_prd_cart only
WITH deleted_records_table AS (
  SELECT mg_id
  FROM ${source.silver}.marketplace_prd_cart_cart_item
  WHERE action = 'd'
    AND date(ingest_time) >= current_date() - 1
)
SELECT *, 
  CASE 
    WHEN created_time IS NOT NULL THEN DATE(created_time)
    WHEN created_time IS NULL AND last_updated_time IS NOT NULL THEN DATE(last_updated_time)
    ELSE NULL
  END AS created_date
FROM (
  SELECT *
  FROM ${source.silver}.marketplace_prd_cart_cart_item o 
  ${
    when(incremental(), 
      `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()}) 
       QUALIFY ROW_NUMBER() OVER (_window) = 1`,
      `QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'`
    )
  }
  WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
      IF(action = 'd', 3, IF(action = 'u', 2, 1)) DESC,
      last_updated_time DESC
  )
) 
WHERE created_time is null and last_updated_time is null -- all record deleted include action "d"
  OR (created_time IS NOT NULL AND last_updated_time IS NOT NULL AND mg_id NOT IN (SELECT mg_id FROM deleted_records_table))
  OR (created_time IS NULL AND last_updated_time IS NOT NULL AND mg_id NOT IN (SELECT mg_id FROM deleted_records_table))
  OR (action = 'i' AND mg_id NOT IN (SELECT mg_id FROM deleted_records_table))
  
post_operations {
  ${
    when(incremental(),
      `
      -- Delete rows using the temporary table
      IF EXISTS (SELECT * from range_created_time_table where min_created_date is not null and max_created_date is not null)
      then
      DELETE FROM ${self()}
      WHERE (created_date BETWEEN (SELECT min_created_date FROM range_created_time_table) 
        AND (SELECT max_created_date FROM range_created_time_table)
          and 
         (key) IN (
        SELECT (key) FROM ${self()} where created_date BETWEEN (SELECT min_created_date FROM range_created_time_table) 
        AND (SELECT max_created_date FROM range_created_time_table) 
        QUALIFY ROW_NUMBER() OVER (_window) > 1
        --OR FIRST_VALUE(action) OVER (_window) = "d"
      WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC,
        IF(action = 'd', 3, IF(action = 'u', 2, 1)) DESC,
        last_updated_time DESC
      )
      ));
      END IF ;

      if EXISTS (SELECT mg_id as action_d
      FROM ${self()} where created_time is null and last_updated_time is null )
      then
      delete from  ${self()} where mg_id in (select mg_id from ${self()} where created_time is null and last_updated_time is null);
      end if;
      `,
      ``
    )
  }
}
