config {
    type: "table",
    description: "PIC: MinhLuu",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey:"mg_id",
    },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["platinum_custom_2h_past5","marketplace_prd_promotion"]
}
SELECT 
    *,
    CASE 
        WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
        ELSE "2099-01-01"
    END AS created_date
FROM ${source.silver}.marketplace_prd_promotion_lucky_wheel_item
QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
    IF
        (action='d',3,
        IF
        (action='u',2,1)) DESC,
    last_updated_time DESC)