config {
    type: "table",
    name: "marketplace_prd_promotion_combo_reward",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id'
    },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["custom_2h_past5"]
}

SELECT
 *,
 date(created_time) as created_date
FROM lakehouse-prod-394907.silver_buymed_vn.marketplace_prd_promotion_combo_reward o 
  
  QUALIFY ROW_NUMBER() OVER (_window) = 1
  AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)