config {
    type: "table",
    description: "Get Segment's Condition from Import Form",
    tags: ["custom_1h_past10"]
}

SELECT
    SPLIT(string_field_0, "-")[SAFE_OFFSET(0)] AS segment_id
    , UPPER(SPLIT(string_field_0, "-")[SAFE_OFFSET(1)]) AS table
    , LOWER(SPLIT(string_field_0, "-")[SAFE_OFFSET(2)]) AS field
    , UPPER(string_field_3) AS value
-- FROM ${source.collector}.data_prd
FROM ${source.external}.import_segment
