config {
    type: "table",
    description: "Get Segment's Condition from Import Form",
    tags: ["custom_1h_past10"]
}

SELECT
  a.* EXCEPT(value)
  , STRING_AGG(CONCAT('"', u, '"'), ",") AS value
FROM (
    SELECT
      SPLIT(string_field_0, "-")[SAFE_OFFSET(0)] AS segment_id
      , UPPER(SPLIT(string_field_0, "-")[SAFE_OFFSET(1)]) AS table
      , LOWER(SPLIT(string_field_0, "-")[SAFE_OFFSET(2)]) AS field
      , REGEXP_REPLACE( UPPER(string_field_3), r' ', '') AS value
  FROM ${source.external}.import_segment
) AS a
  , UNNEST(SPLIT(a.value, ",")) AS u
GROUP BY ALL
