config {
    type: "table",
    description: "Get Segment's Condition from Import Form",
    tags: ["custom_1h_past10", "CUSTOMER_SEGMENT"]
}
WITH 
    cte AS (
        SELECT
            a.* EXCEPT(value)
            , STRING_AGG(CONCAT('"', TRIM(u), '"'), ",") AS value
        FROM (
            SELECT
                SPLIT(code, "::")[SAFE_OFFSET(0)] AS segment_id
                , UPPER(SPLIT(code, "::")[SAFE_OFFSET(1)]) AS table
                , LOWER(SPLIT(code, "::")[SAFE_OFFSET(2)]) AS field
                , TRIM( UPPER(value), "\'" ) AS value
                , submit_id
                , DATE(submit_at) AS submit_date
            FROM ${source.collector}.data_prd
            WHERE DATE(submit_at) >= "2025-10-01"
                AND object = "CUSTOMER_SEGMENT"
            QUALIFY RANK() over (PARTITION BY segment_id ORDER BY submit_id DESC ) = 1
        ) AS a
            , UNNEST(SPLIT(a.value, ",")) AS u
        WHERE NOT REGEXP_CONTAINS(segment_id, r'TECHTEST_IMPORT1|TECHTESTBASE|TECH_TEST_IMPORT2|VOUCHERTECH01')
        GROUP BY ALL
)

SELECT
    TRIM(segment_id) AS segment_id,
    submit_id,
    submit_date,
    -- Customer fields
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'customer_status' THEN value END) AS customer_status,
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'customer_level' THEN value END) AS customer_level,
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'config_fc' THEN value END) AS config_fc,
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'province_name' THEN value END) AS province_name,
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'region_name' THEN value END) AS region_name,
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'customer_tag_group' THEN value END) AS customer_tag_group,
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'customer_tag_sub_group' THEN value END) AS customer_tag_sub_group,
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'last_order_at' THEN value END) AS last_purchase,
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'count_order' THEN REGEXP_REPLACE(value, r' ', '') END) AS count_order,
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'sum_gmv' THEN REGEXP_REPLACE(value, r' ', '') END) AS sum_gmv,
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'order_status' THEN value END) AS customer_order_status,
    MAX(CASE WHEN table = 'CUSTOMER' AND field = 'time_range_count_sum' THEN REGEXP_REPLACE(value, r' ', '') END) AS time_range_count_sum,

    -- Order1 fields
    MAX(CASE WHEN table = 'ORDER1' AND field = 'created_at' THEN REGEXP_REPLACE(value, r' ', '') END) AS created_at1,
    MAX(CASE WHEN table = 'ORDER1' AND field = 'order_status' THEN value END) AS order_status1,
    MAX(CASE WHEN table = 'ORDER1' AND field = 'seller_code' THEN value END) AS seller_code1,
    MAX(CASE WHEN table = 'ORDER1' AND field = 'product_id' THEN value END) AS product_id1,
    MAX(CASE WHEN table = 'ORDER1' AND field = 'product_tag' THEN value END) AS product_tag1,

    -- Order2 fields
    MAX(CASE WHEN table = 'ORDER2' AND field = 'created_at' THEN REGEXP_REPLACE(value, r' ', '') END) AS created_at2,
    MAX(CASE WHEN table = 'ORDER2' AND field = 'order_status' THEN value END) AS order_status2,
    MAX(CASE WHEN table = 'ORDER2' AND field = 'seller_code' THEN value END) AS seller_code2,
    MAX(CASE WHEN table = 'ORDER2' AND field = 'product_id' THEN value END) AS product_id2,
    MAX(CASE WHEN table = 'ORDER2' AND field = 'product_tag' THEN value END) AS product_tag2,

    -- Operator
    MAX(CASE WHEN table = 'OPERATOR' THEN UPPER(COALESCE(value,CONCAT('"',field,'"'))) END) AS operator,

    -- Type
    MAX(CASE WHEN table = 'TYPE' THEN UPPER(COALESCE(NULLIF(value, '"NAN"'),CONCAT('"',field,'"'))) END) AS type
FROM cte AS a
GROUP BY ALL