config {
    type: "table",
    description: "Result of Dynamic Segment",
    tags: ["custom_1h_past10", "CUSTOMER_SEGMENT", "0h30"]
}

SELECT
    segment_id AS voucher_code
    , voucher_id
    , processed_date
    , total_customers
    , customer_list
    , submit_id
FROM ${ref('bi_dynamic_segment_stg')} AS s
    LEFT JOIN ${ref('dim_voucher')} AS v ON v.voucher_code = segment_id
WHERE 1=1
    -- AND total_customers > 32000
    AND DATE(v.end_date) >= CURRENT_DATE("+7")
    AND voucher_id IS NOT NULL
QUALIFY ROW_NUMBER() OVER(PARTITION BY segment_id ORDER BY processed_date DESC, submit_id DESC) = 1
    AND FIRST_VALUE(total_customers) over (PARTITION BY segment_id ORDER BY processed_date DESC) > 32000
