config {
    type: "incremental",
    description: "Result of Dynamic Segment",
    //tags: ["custom_1h_past10"]
}

WITH
    segment_data AS (
        SELECT
            segment_id,
            -- Customer fields
            MAX(CASE WHEN table = 'CUSTOMER' AND field = 'customer_status' THEN value END) as customer_status,
            MAX(CASE WHEN table = 'CUSTOMER' AND field = 'customer_level' THEN value END) as customer_level,
            MAX(CASE WHEN table = 'CUSTOMER' AND field = 'config_fc' THEN value END) as config_fc,
            MAX(CASE WHEN table = 'CUSTOMER' AND field = 'province_name' THEN value END) as province_name,
            MAX(CASE WHEN table = 'CUSTOMER' AND field = 'region_name' THEN value END) as region_name,
            MAX(CASE WHEN table = 'CUSTOMER' AND field = 'customer_tag_group' THEN value END) as customer_tag_group,
            MAX(CASE WHEN table = 'CUSTOMER' AND field = 'customer_tag_sub_group' THEN value END) as customer_tag_sub_group,
            MAX(CASE WHEN table = 'CUSTOMER' AND field = 'count_order' THEN value END) as count_order,
            MAX(CASE WHEN table = 'CUSTOMER' AND field = 'sum_gmv' THEN value END) as sum_gmv,
            MAX(CASE WHEN table = 'CUSTOMER' AND field = 'time_range_count_sum' THEN value END) as time_range_count_sum,

            -- Order1 fields
            MAX(CASE WHEN table = 'ORDER1' AND field = 'created_at' THEN value END) as created_at1,
            MAX(CASE WHEN table = 'ORDER1' AND field = 'seller_code' THEN value END) as seller_code1,
            MAX(CASE WHEN table = 'ORDER1' AND field = 'product_id' THEN value END) as product_id1,

            -- Order2 fields
            MAX(CASE WHEN table = 'ORDER2' AND field = 'created_at' THEN value END) as created_at2,
            MAX(CASE WHEN table = 'ORDER2' AND field = 'seller_code' THEN value END) as seller_code2,
            MAX(CASE WHEN table = 'ORDER2' AND field = 'product_id' THEN value END) as product_id2,

            -- Operator
            MAX(CASE WHEN table = 'OPERATOR' THEN UPPER(COALESCE(value,CONCAT('"',field,'"'))) END) as operator
        FROM ${ref('bi_dynamic_segment')} AS a
        ${when(incremental(), 
            `WHERE NOT EXISTS (SELECT 1 FROM ${self()} AS b WHERE a.segment_id = b.segment_id AND CURRENT_DATE("+7") = DATE(b.processed_at))`)
        }
        GROUP BY segment_id
    ),

    get_start_end AS (
        SELECT
            * EXCEPT (count_order, sum_gmv, operator)
            , IFNULL(
                SAFE.PARSE_DATE('"%Y-%m-%d"', SPLIT(time_range_count_sum, ",")[SAFE_OFFSET(0)])
                , DATE_SUB(CURRENT_DATE(), INTERVAL SAFE_CAST(REGEXP_EXTRACT(SPLIT(time_range_count_sum, ",")[SAFE_OFFSET(0)], r'[0-9]+') AS INT64) DAY)
            ) AS start_date_time_range_count_sum
            , IFNULL(
                SAFE.PARSE_DATE('"%Y-%m-%d"', SPLIT(time_range_count_sum, ",")[SAFE_OFFSET(1)])
                , DATE_SUB(CURRENT_DATE(), INTERVAL IFNULL(SAFE_CAST(REGEXP_EXTRACT(SPLIT(time_range_count_sum, ",")[SAFE_OFFSET(1)], r'[0-9]+') AS INT64),0) DAY)
            ) AS end_date_time_range_count_sum
            , IFNULL(
                SAFE.PARSE_DATE('"%Y-%m-%d"', SPLIT(created_at1, ",")[SAFE_OFFSET(0)])
                , DATE_SUB(CURRENT_DATE(), INTERVAL SAFE_CAST(REGEXP_EXTRACT(SPLIT(created_at1, ",")[SAFE_OFFSET(0)], r'[0-9]+') AS INT64) DAY)
            ) AS start_date1
            , IFNULL(
                SAFE.PARSE_DATE('"%Y-%m-%d"', SPLIT(created_at1, ",")[SAFE_OFFSET(1)])
                , DATE_SUB(CURRENT_DATE(), INTERVAL IFNULL(SAFE_CAST(REGEXP_EXTRACT(SPLIT(created_at1, ",")[SAFE_OFFSET(1)], r'[0-9]+') AS INT64),0) DAY)
            ) AS end_date1
            , IFNULL(
                SAFE.PARSE_DATE('"%Y-%m-%d"', SPLIT(created_at2, ",")[SAFE_OFFSET(0)])
                , DATE_SUB(CURRENT_DATE(), INTERVAL SAFE_CAST(REGEXP_EXTRACT(SPLIT(created_at2, ",")[SAFE_OFFSET(0)], r'[0-9]+') AS INT64) DAY)
            ) AS start_date2
            , IFNULL(
                SAFE.PARSE_DATE('"%Y-%m-%d"', SPLIT(created_at2, ",")[SAFE_OFFSET(1)])
                , DATE_SUB(CURRENT_DATE(), INTERVAL IFNULL(SAFE_CAST(REGEXP_EXTRACT(SPLIT(created_at2, ",")[SAFE_OFFSET(1)], r'[0-9]+') AS INT64),0) DAY)
            ) AS end_date2
            , REGEXP_EXTRACT(count_order, r'[0-9]+') AS count_order
            , REGEXP_EXTRACT(count_order, r'>|<|=') AS count_order_operator
            , REGEXP_EXTRACT(sum_gmv, r'[0-9]+') AS sum_gmv
            , REGEXP_EXTRACT(sum_gmv, r'>|<|=') AS sum_gmv_operator
            , IFNULL(operator, '') AS operator
        FROM segment_data
    )

    , query_order AS (
        SELECT
            o.customer_id
            , sd.segment_id
            , COUNT(DISTINCT order_id) AS no_order
            , SUM(o.ordered_amount) AS _gmv
        FROM ${ref('fact_order')} AS o
            ,  get_start_end AS sd
        WHERE 1=1
            AND o.channel IN ("MARKETPLACE", "CIRCA")
            AND o.order_status <> "CANCEL"
            AND (
                sd.start_date_time_range_count_sum IS NULL
                OR DATE(o.created_at) BETWEEN sd.start_date_time_range_count_sum AND sd.end_date_time_range_count_sum
            )
        GROUP BY 1,2, sd.count_order, sd.count_order_operator, sd.sum_gmv, sd.sum_gmv_operator
        HAVING
            ( sd.count_order IS NULL
                OR (sd.count_order_operator = '>' AND no_order > SAFE_CAST(count_order AS INT64))
                OR (sd.count_order_operator = '=' AND no_order = SAFE_CAST(count_order AS INT64))
                OR (sd.count_order_operator = '<' AND no_order < SAFE_CAST(count_order AS INT64))
            )
            AND ( sd.sum_gmv IS NULL
                OR (sd.sum_gmv_operator = '>' AND _gmv > SAFE_CAST(sum_gmv AS INT64))
                OR (sd.sum_gmv_operator = '=' AND _gmv = SAFE_CAST(sum_gmv AS INT64))
                OR (sd.sum_gmv_operator = '<' AND _gmv < SAFE_CAST(sum_gmv AS INT64))
            )
    )

    , query_order1 AS (
        SELECT
            DISTINCT oi.customer_id, sd.segment_id
        FROM ${ref('fact_order_item')} oi
            LEFT JOIN ${ref('fact_order')} o ON oi.order_id = o.order_id
            , (SELECT start_date1, end_date1, seller_code1, product_id1, segment_id FROM get_start_end) sd
        WHERE o.channel IN ("MARKETPLACE", "CIRCA")
            AND o.order_status <> "CANCEL"
            AND (
                sd.start_date1 IS NULL
                OR DATE(oi.created_at) BETWEEN sd.start_date1 AND sd.end_date1
            )
            AND (sd.seller_code1 IS NULL OR STRPOS(sd.seller_code1, CONCAT('"',oi.seller_code,'"')) > 0)
            AND (sd.product_id1 IS NULL OR STRPOS(sd.product_id1, CONCAT('"',oi.product_id,'"')) > 0)
    )

    , query_order2 AS (
        SELECT
            DISTINCT oi.customer_id, sd.segment_id
        FROM ${ref('fact_order_item')} oi
            LEFT JOIN ${ref('fact_order')} o ON oi.order_id = o.order_id
            , (SELECT start_date2, end_date2, seller_code2, product_id2, segment_id FROM get_start_end) sd
        WHERE o.channel IN ("MARKETPLACE", "CIRCA")
            AND o.order_status <> "CANCEL"
            AND (
                sd.start_date2 IS NULL
                OR DATE(oi.created_at) BETWEEN sd.start_date2 AND sd.end_date2
            )
            AND (sd.seller_code2 IS NULL OR STRPOS(sd.seller_code2, CONCAT('"',oi.seller_code,'"')) > 0)
            AND (sd.product_id2 IS NULL OR STRPOS(sd.product_id2, CONCAT('"',oi.product_id,'"')) > 0)
    )

    , final AS (
        SELECT
            c.customer_id,
            sd.segment_id,
            CURRENT_TIMESTAMP()  + INTERVAL 7 HOUR AS processed_at
        FROM ${ref('dim_customer')} c
            LEFT JOIN gold_buymed_vn2.dim_geo_location AS g ON c.location_code= g.location_code
        CROSS JOIN  get_start_end sd
        WHERE 1=1
            -- Customer conditions
            AND (sd.customer_status IS NULL OR STRPOS(sd.customer_status, CONCAT('"',c.customer_status,'"')) > 0)
            AND (sd.customer_level IS NULL OR STRPOS(sd.customer_level, CONCAT('"',c.customer_level,'"')) > 0)
            AND (sd.config_fc IS NULL OR STRPOS(sd.config_fc, CONCAT('"',c.config_fc,'"')) > 0)
            AND (sd.province_name IS NULL OR STRPOS(sd.province_name, CONCAT('"',UPPER(g.province_name),'"')) >0)
            AND (sd.region_name IS NULL OR STRPOS(sd.region_name, CONCAT('"',UPPER(g.region_name),'"')) >0)
            AND (sd.customer_tag_group IS NULL OR STRPOS(sd.customer_tag_group, CONCAT('"',c.customer_tag_group,'"')) > 0)
            AND (sd.customer_tag_sub_group IS NULL OR STRPOS(sd.customer_tag_sub_group, CONCAT('"',c.customer_tag_sub_group,'"')) > 0)
            AND (sd.count_order IS NULL OR EXISTS (SELECT 1 FROM query_order qo WHERE qo.customer_id = c.customer_id AND qo.segment_id = sd.segment_id))
            AND (sd.sum_gmv IS NULL OR EXISTS (SELECT 1 FROM query_order qo WHERE qo.customer_id = c.customer_id AND qo.segment_id = sd.segment_id))

            -- Order conditions for NEW customers
            AND (
                sd.operator <> '"NEW"'
                OR ( NOT EXISTS (SELECT 1 FROM query_order1 qo WHERE qo.customer_id = c.customer_id AND qo.segment_id = sd.segment_id)
                    AND (sd.created_at1 IS NULL OR c.last_purchase >= start_date1)
                )
            )

            AND (
                sd.operator <> '"CHURN"'
                OR ( EXISTS (SELECT 1 FROM query_order1 qo WHERE qo.customer_id = c.customer_id AND qo.segment_id = sd.segment_id)
                    AND NOT EXISTS (SELECT 1 FROM query_order2 qoo WHERE qoo.customer_id = c.customer_id AND qoo.segment_id = sd.segment_id)
                )
            )

            AND (
                sd.operator <> '"EXCEPT"'
                OR ( EXISTS (SELECT 1 FROM query_order1 qo WHERE qo.customer_id = c.customer_id AND qo.segment_id = sd.segment_id)
                    AND NOT EXISTS (SELECT 1 FROM query_order2 qoo WHERE qoo.customer_id = c.customer_id AND qoo.segment_id = sd.segment_id)
                )
            )
    )

SELECT *
FROM final
WHERE segment_id IS NOT NULL