
config {
    type: "view",
    name: "seller_prd_purchasing_purchase_order__assert",
    schema: "dataform_assertions",
    tags: ["seller_prd_purchasing","Finance/margin"]
}
js {
    const start_timestamp = `current_timestamp() - interval 2 DAY`
    // const start_timestamp = `TIMESTAMP("1990-01-01")`
}

WITH 
-- Time Range for validate
checkpoint_tbl AS (
    SELECT 
        ${start_timestamp} AS _timestamp,
        DATE( ${start_timestamp} ,"+7") AS _date
)
-- Prepare Platinum data
, PLATINUM AS (
    SELECT mg_id, created_time,last_updated_time, ingest_time,action, platinum_refresh
    FROM ${ref(`seller_prd_purchasing_purchase_order`)} o 
    WHERE created_date >= (SELECT _date FROM checkpoint_tbl)
)
-- Prepare ingest_time range for silver to optimize cost
, tbl_timestamp AS (
    SELECT MIN(ingest_time) min_time, max(ingest_time) max_time, min(created_time) min_created_time, max(created_time) max_created_time
    FROM  ${ref(`seller_prd_purchasing_purchase_order`)} o 
    WHERE created_date >= (SELECT _date FROM checkpoint_tbl)
)
-- Prepare Silver data
, SILVER_1 AS (
    SELECT
        mg_id
        , created_time
        , last_updated_time
        , synced_at
        , ingest_time
        , action
    FROM ${source.silver}.seller_prd_purchasing_purchase_order o 
    WHERE  ingest_time BETWEEN (SELECT min_time FROM tbl_timestamp ) AND (SELECT max_time FROM tbl_timestamp )
    AND (
            created_time BETWEEN (SELECT min_created_time FROM tbl_timestamp ) AND (SELECT max_created_time FROM tbl_timestamp )
            OR created_time IS NULL -- For delete action
        )
)
-- Dedup Silver history, but not exclude delete action
, SILVER_2 AS (
    SELECT *
    FROM SILVER_1 
    QUALIFY ROW_NUMBER() OVER (_window) = 1
    WINDOW _window AS (
        PARTITION BY mg_id
        ORDER BY 
            synced_at DESC,
            IF (action='d',3, IF (action='u',2,1)) DESC, 
            last_updated_time DESC
    )
)
-- Create Action History for records
, SILVER_3 AS ( 
    SELECT 
        mg_id
        , ARRAY_AGG ( STRUCT( synced_at, last_updated_time, action ) ORDER BY synced_at DESC ) action_history
    FROM SILVER_1
    GROUP BY 1
)
-- Finish prepare Silver
, SILVER AS (
    SELECT 
        SILVER_2.*,
        SILVER_3.action_history
    FROM SILVER_2
    LEFT JOIN SILVER_3 USING(mg_id)
)

-- Validate if records is deleted right
, DELETED_RECORDS AS (
    SELECT 
        s.mg_id
        , s.action as s_action
        , p.action p_action
        , CAST(null AS INT64) AS value
        , s.ingest_time s_ingest_time
        , p.ingest_time p_ingest_time
        , p.platinum_refresh
        , s.action_history
    FROM SILVER s
    LEFT JOIN PLATINUM p ON s.mg_id = p.mg_id 
    WHERE s.action = "d"
        AND p.mg_id IS NOT NULL        
)

-- SELECT
--     "INFO DELETE ACTION CNT" , "","",CAST(COUNT(DISTINCT mg_id) AS STRING), COUNTIF(action = "d") , min(ingest_time), max(ingest_time) , current_datetime("+7")
-- FROM SILVER

-- UNION ALL

SELECT 
    "TOTAL COUNT" reason,
    "" AS mg_id,
    STRUCT ( "" as silver, "" as platinum) newest_action,
    STRUCT ( CURRENT_TIMESTAMP() as silver, CURRENT_TIMESTAMP() as platinum) ingest_time,
    COUNT(*) as value,
    CURRENT_DATETIME() platinum_refresh,
    null AS action_history
FROM SILVER

UNION ALL

SELECT 
    "DELETED_RECORDS" reason,
    mg_id, 
    STRUCT (s_action as silver, p_action as platinum) newest_action,
    STRUCT (s_ingest_time  as silver, p_ingest_time  as platinum) ingest_time,
    0 as value, 
    platinum_refresh,
    action_history
    
FROM DELETED_RECORDS

UNION ALL 
SELECT
    "MISSING_RECORDS", 
    s.mg_id, 
    STRUCT (s.action as silver, p.action as platinum) newest_action,
    STRUCT (s.ingest_time  as silver, p.ingest_time  as platinum) ingest_time,
    0 as value, 
    platinum_refresh,
    action_history
    
FROM SILVER s 
LEFT JOIN PLATINUM p 
    ON s.mg_id = p.mg_id
WHERE p.mg_id is null
AND s.action <> "d"


UNION ALL 
SELECT 
    "WRONG_UPDATE", 
    s.mg_id,
    STRUCT (s.action as silver, p.action as platinum) newest_action,
    STRUCT (s.ingest_time  as silver, p.ingest_time  as platinum) ingest_time,
    0 as value, 
    platinum_refresh,
    action_history
FROM SILVER s 
LEFT JOIN PLATINUM p 
    ON s.mg_id = p.mg_id
WHERE s.last_updated_time > p.last_updated_time
AND s.action <> "d"



/*
    SELECT mg_id, count(*)
    FROM ${ref(`seller_prd_purchasing_purchase_order`)}
    GROUP BY 1 
    HAVING COUNT(*) > 1
*/

