config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Margin of the Vietnam marketplace.`,
    tags: ['AI_THUOCSI_VN']
}

-- SELECT
--     a.created_date
--     , a.order_id
--     , CONCAT(b.sku_key, "_", o.warehouse_code) AS sku_key
--     , b.product_id
--     , a.profit
--     , a.total_price
-- FROM ${source.platinum}.monitoring_prd_realtime_supply_margin_order_sku AS a
--     LEFT JOIN ${source.platinum}.marketplace_prd_order_v2_order AS o ON a.order_id = o.order_id
--     LEFT JOIN ${ref('gold_buymed_vn2','dim_sku')} AS b ON a.sku = b.sku_code
-- WHERE 1=1 
--     AND a.created_date >= "2025-01-01"
--     AND o.created_date >= "2025-01-01"
-- UNION ALL
-- SELECT
--     a.created_date
--     , a.order_id
--     , CONCAT(a.product_id, "_", a.seller_code, "_", a.fc_code) AS sku_key
--     , a.product_id
--     , a.profit * quantity AS profit
--     , a.price * quantity AS total_price
-- FROM gold_buymed_vn2.fact_order_item_seller_margin AS a
-- WHERE 1=1 
--     AND a.created_date >= "2025-01-01"

WITH 
    fact_order AS ( 
        SELECT
            created_date
            , FORMAT_DATE("%Y-%m", created_date ) AS year_month
            , DATE_TRUNC(created_date, MONTH) AS som
            , DATETIME(created_time, "+7") AS created_time
            , DATETIME(a.delivered_time, "+7") AS delivered_time
            , order_id
            , customer_id
            , price AS gmv
            , status
            , CASE
                WHEN REGEXP_CONTAINS(TO_JSON_STRING(JSON_VALUE_ARRAY(a.extra_props, '$.customer_tags')), r'\"CIRCA\"|\"CIRCACOS\"|\"CIRCAFOFO\"|\"CIRCAFOCO\"')  THEN 'CIRCA'
                WHEN a.source = 'brand-portal' AND JSON_VALUE(a.extra_props, "$.brand_code") IN ('Q8HDUVQX', '2E84FW961P', 'PG961P') THEN 'TENDER'
                WHEN TO_JSON_STRING(JSON_VALUE_ARRAY(a.extra_props, '$.customer_tags')) LIKE '%TENDER%' THEN 'TENDER'
                WHEN a.source IN ('brand-portal', 'clinic-portal') OR customer_id IN (360299, 360439, 375375) THEN 'TENDER'
                ELSE 'MARKETPLACE'
            END AS channel,
            CASE
                WHEN SAFE_CAST(a.customer_ward_code AS INTEGER) > 0 THEN a.customer_ward_code
                ELSE a.customer_district_code
            END AS shipping_ward_code,
            total_discount,
            a.warehouse_code
        FROM ${source.platinum}.marketplace_prd_order_v2_order AS a
        WHERE 1=1
            AND created_date >= "2025-01-01"
            AND status <> "CANCEL"
        UNION ALL
        SELECT
            created_date
            , FORMAT_DATE("%Y-%m", created_date ) AS year_month
            , DATE_TRUNC(created_date, MONTH) AS som
            , DATETIME(created_time, "+7") AS created_time
            , DATETIME(a.delivered_time, "+7") AS delivered_time
            , order_id
            , 1000000 + receiver_id
            , total_amount
            -- , IF(status = 'CANCELLED','CANCEL', status) AS status
            , status
            , 'TENDER' AS channel
            , CASE
                WHEN SAFE_CAST(a.ward_code AS INTEGER) > 0 THEN a.ward_code
                ELSE a.district_code
            END AS shipping_ward_code,
            0,
            p.fc_code
        FROM ${source.platinum}.tender_prd_core_tender_orders AS a
            LEFT JOIN ${ref('gold_buymed_vn2','dim_province')} AS p ON a.province_code = p.province_code
        WHERE 1=1
            AND created_date >= "2025-01-01"
            AND status <> "CANCELLED"
    ),

    margin AS (
        SELECT
            created_date
            , order_id
            , seller_class
            , CONCAT(product_id, "_", seller_code, "_", fc_code) AS sku_key 
            , product_id
            , SUM(quantity * (price - rebate)) AS profit
            , SUM(quantity * rebate) AS cogs_after_rebate
            , SUM(quantity * price) AS total_price
        FROM gold_buymed_vn2.fact_order_item_margin_internal_outbound
        WHERE created_date >= "2025-01-01"
        GROUP BY ALL
        UNION ALL
        SELECT
            created_date
            , order_id
            , a.seller_class
            , CONCAT(a.product_id, "_", seller_code, "_", COALESCE(NULLIF(a.warehouse_code, "TA"), "BD")) AS sku_key
            , a.product_id
            , SUM(quantity * (price - purchase_price)) AS profit
            , SUM(quantity * purchase_price) AS cogs_after_rebate
            , SUM(quantity * price)
        FROM gold_buymed_vn2.fact_order_item_margin_tayau_outbound AS a
            LEFT JOIN ${ref('gold_buymed_vn2','dim_sku')} AS b ON LEFT(a.item_code, LENGTH(a.item_code) -2) = b.sku_code
        WHERE created_date >= "2025-01-01"
        GROUP BY ALL
        UNION ALL
        SELECT
            a.created_date
            , a.order_id
            , seller_class
            , CONCAT(a.product_id, "_", a.seller_code, "_", a.fc_code) AS sku_key
            , a.product_id
            , (a.buyer_fee + (a.price - a.buyer_fee) * (fulfillment_rate + listing_rate + 0.01)) * quantity AS profit
            , (a.price - a.buyer_fee) * (1 - fulfillment_rate - listing_rate - 0.01) * quantity AS cogs_after_rebate
            , a.price * quantity AS total_price
        FROM gold_buymed_vn2.fact_order_item_margin_seller_outbound AS a
        WHERE 1=1 
            AND a.created_date >= "2025-01-01"
    )

SELECT
    a.*
    , o.channel
    , o.customer_id
    , o.status AS order_status
    , g.ward_name
    , g.district_name
    , g.province_name
    , g.region_name
    , g.urban_rural
FROM margin AS a
    LEFT JOIN fact_order AS o ON a.order_id = o.order_id
    LEFT JOIN ${ref('gold_buymed_vn2','dim_geo_location')} AS g ON o.shipping_ward_code = g.location_code
WHERE o.order_id IS NOT NULL