config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Net Profit of the Vietnam marketplace.`,
    tags: ['AI_THUOCSI_VN']
}

-- WITH 
    -- fact_order AS ( 
    --     SELECT
    --         created_date
    --         , FORMAT_DATE("%Y-%m", created_date ) AS year_month
    --         , DATE_TRUNC(created_date, MONTH) AS som
    --         , DATETIME(created_time, "+7") AS created_time
    --         , DATETIME(a.delivered_time, "+7") AS delivered_time
    --         , order_id
    --         , customer_id
    --         , price AS gmv
    --         , status
    --         , CASE
    --             WHEN REGEXP_CONTAINS(TO_JSON_STRING(JSON_VALUE_ARRAY(a.extra_props, '$.customer_tags')), r'\"CIRCA\"|\"CIRCACOS\"|\"CIRCAFOFO\"|\"CIRCAFOCO\"')  THEN 'CIRCA'
    --             WHEN a.source = 'brand-portal' AND JSON_VALUE(a.extra_props, "$.brand_code") IN ('Q8HDUVQX', '2E84FW961P', 'PG961P') THEN 'TENDER'
    --             WHEN TO_JSON_STRING(JSON_VALUE_ARRAY(a.extra_props, '$.customer_tags')) LIKE '%TENDER%' THEN 'TENDER'
    --             WHEN a.source IN ('brand-portal', 'clinic-portal') OR customer_id IN (360299, 360439, 375375) THEN 'TENDER'
    --             ELSE 'MARKETPLACE'
    --         END AS channel,
    --         CASE
    --             WHEN SAFE_CAST(a.customer_ward_code AS integer) > 0 THEN a.customer_ward_code
    --             ELSE a.customer_district_code
    --         END AS shipping_ward_code,
    --         total_discount,
    --         a.warehouse_code
    --     FROM ${source.platinum}.marketplace_prd_order_v2_order AS a
    --     WHERE 1=1
    --         -- AND created_date >= "2022-01-01"
    --         AND status <> "CANCEL"
    --     UNION ALL
    --     SELECT
    --         created_date
    --         , FORMAT_DATE("%Y-%m", created_date ) AS year_month
    --         , DATE_TRUNC(created_date, MONTH) AS som
    --         , DATETIME(created_time, "+7") AS created_time
    --         , DATETIME(a.delivered_time, "+7") AS delivered_time
    --         , order_id
    --         , 1000000 + receiver_id
    --         , total_amount
    --         -- , IF(status = 'CANCELLED','CANCEL', status) AS status
    --         , status
    --         , 'TENDER' AS channel
    --         , CASE
    --             WHEN SAFE_CAST(a.ward_code AS integer) > 0 THEN a.ward_code
    --             ELSE a.district_code
    --         END AS shipping_ward_code,
    --         0,
    --         p.fc_code
    --     FROM ${source.platinum}.tender_prd_core_tender_orders AS a
    --         LEFT JOIN ${ref('gold_buymed_vn2','dim_province')} AS p ON a.province_code = p.province_code
    --     WHERE 1=1
    --         -- AND created_date >= "2022-01-01"
    --         AND status <> "CANCELLED"
    -- )

SELECT
    a.created_date
    , a.order_id
    , a.customer_id
    , a.channel
    , a.ward_name
    , a.district_name
    , a.province_name
    , a.region_name
    , a.urban_rural
    , a.gross_profit AS gross_profit
    , a.gross_profit - COALESCE(o.total_discount, 0) AS net_profit
    , a.total_price AS total_price
    , a.cogs_after_rebate AS cogs_after_rebate
FROM (
    SELECT
        a.created_date
        , a.order_id
        , a.customer_id
        , a.channel
        , a.ward_name
        , a.district_name
        , a.province_name
        , a.region_name
        , a.urban_rural
        , SUM(a.profit) AS gross_profit
        , SUM(a.total_price) AS total_price
        , SUM(cogs_after_rebate) AS cogs_after_rebate
    FROM ${ref("buymed_innovation", "thuocsi_vn_fact_margin")} AS a
    GROUP BY ALL
) AS a
    LEFT JOIN (
        SELECT
            order_id
            , SUM(discount_value) AS total_discount
        FROM ${ref("buymed_innovation", "thuocsi_vn_fact_order_voucher")}
        WHERE COALESCE(charge_fee, "") <> "COMMERCIAL_BRANDED_SPONSORSHIP"
        GROUP BY ALL
    ) AS o ON a.order_id = o.order_id
GROUP BY ALL