config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Net Profit of the Vietnam marketplace.`,
    tags: ['AI_THUOCSI_VN']
}


SELECT
    a.created_date
    , a.order_id
    , a.customer_id
    , a.channel
    , a.ward_name
    , a.district_name
    , a.province_name
    , a.region_name
    , a.urban_rural
    , a.gross_profit AS gross_profit
    , a.gross_profit - COALESCE(o.total_discount, 0) AS net_profit
    , a.total_price AS total_price
    , a.cogs_after_rebate AS cogs_after_rebate
FROM (
    SELECT
        a.created_date
        , a.order_id
        , a.customer_id
        , a.channel
        , a.ward_name
        , a.district_name
        , a.province_name
        , a.region_name
        , a.urban_rural
        , SUM(a.profit) AS gross_profit
        , SUM(a.total_price) AS total_price
        , SUM(cogs_after_rebate) AS cogs_after_rebate
    FROM ${ref("buymed_innovation", "thuocsi_vn_fact_margin")} AS a
    GROUP BY ALL
) AS a
    LEFT JOIN (
        SELECT
            order_id
            , SUM(discount_value) AS total_discount
        FROM ${ref("buymed_innovation", "thuocsi_vn_fact_order_voucher")}
        WHERE COALESCE(charge_fee, "") <> "COMMERCIAL_BRANDED_SPONSORSHIP"
        GROUP BY ALL
    ) AS o ON a.order_id = o.order_id
GROUP BY ALL