config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Competitor's Price in the Vietnam marketplace.`,
    tags: ['AI_THUOCSI_VN']
}

SELECT
    a.product_id
    , LOWER(b.unit) AS unit
    , competitor AS competitor_name
    , market_price_aft_convert AS competitor_price
    , COALESCE(market_price_before_promotion_aft_convert,market_price_aft_convert)  AS competitor_price_before_promotion
FROM ${ref('gold_buymed_vn2', 'adhoc_pricing_competitor_price')} AS a
    LEFT JOIN ${ref('gold_buymed_vn2', 'dim_product')} AS b USING(product_id)
WHERE  qc = "QC"
    AND competitor_price > 0
    AND NOT REGEXP_CONTAINS(competitor, r'P[0-9]+')
    AND LOWER(competitor) IN (
        SELECT
            LOWER(source) AS competitor
        FROM platinum_buymed_vn.marketplace_prd_product_v2_market_price_source
        WHERE NOT REGEXP_CONTAINS(source, r'P[0-9]+')
            AND COALESCE(is_active, true)
    )
