config {
    type: 'view',
    schema: "buymed_innovation",
    description: `All orders item in the Vietnam marketplace (including tender orders).`,
    tags: ['AI_THUOCSI_VN']
}

WITH
    fact_order AS ( 
        SELECT
            created_date
            , FORMAT_DATE("%Y-%m", created_date ) AS year_month
            , DATE_TRUNC(created_date, MONTH) AS som
            , DATETIME(created_time, "+7") AS created_time
            , DATETIME(a.delivered_time, "+7") AS delivered_time
            , order_id
            , customer_id
            , price AS gmv
            , status
            , CASE
                WHEN REGEXP_CONTAINS(TO_JSON_STRING(JSON_VALUE_ARRAY(a.extra_props, '$.customer_tags')), r'\"CIRCA\"|\"CIRCACOS\"|\"CIRCAFOFO\"|\"CIRCAFOCO\"')  THEN 'CIRCA'
                WHEN a.source = 'brand-portal' AND JSON_VALUE(a.extra_props, "$.brand_code") IN ('Q8HDUVQX', '2E84FW961P', 'PG961P') THEN 'TENDER'
                WHEN TO_JSON_STRING(JSON_VALUE_ARRAY(a.extra_props, '$.customer_tags')) LIKE '%TENDER%' THEN 'TENDER'
                WHEN a.source IN ('brand-portal', 'clinic-portal') OR customer_id IN (360299, 360439, 375375) THEN 'TENDER'
                ELSE 'MARKETPLACE'
            END AS channel,
            CASE
                WHEN SAFE_CAST(a.customer_ward_code AS INTEGER) > 0 THEN a.customer_ward_code
                ELSE a.customer_district_code
            END AS shipping_ward_code,
            total_discount,
            a.warehouse_code
        FROM ${source.platinum}.marketplace_prd_order_v2_order AS a
        WHERE 1=1
            -- AND created_date >= "2022-01-01"
            AND status <> "CANCEL"
        UNION ALL
        SELECT
            created_date
            , FORMAT_DATE("%Y-%m", created_date ) AS year_month
            , DATE_TRUNC(created_date, MONTH) AS som
            , DATETIME(created_time, "+7") AS created_time
            , DATETIME(a.delivered_time, "+7") AS delivered_time
            , order_id
            , 1000000 + receiver_id
            , total_amount
            -- , IF(status = 'CANCELLED','CANCEL', status) AS status
            , status
            , 'TENDER' AS channel
            , CASE
                WHEN SAFE_CAST(a.ward_code AS INTEGER) > 0 THEN a.ward_code
                ELSE a.district_code
            END AS shipping_ward_code,
            0,
            p.fc_code
        FROM ${source.platinum}.tender_prd_core_tender_orders AS a
            LEFT JOIN ${ref('gold_buymed_vn2','dim_province')} AS p ON a.province_code = p.province_code
        WHERE 1=1
            -- AND created_date >= "2022-01-01"
            AND status <> "CANCELLED"
    )

    , new_customer AS (
        SELECT
            customer_id
            , MIN_BY(year_month, created_date) AS first_order_year_month
            , MIN_BY(som, created_date) AS first_order_som
            , MIN(created_date) AS first_order_date
            , "NEW" AS customer_active_type
        FROM fact_order
        GROUP BY ALL
    )

    , reapeat_customer AS (
        SELECT
            customer_id
            , year_month
            , som
            , LEAD(som) over (PARTITION BY customer_id ORDER BY som DESC) AS before_som
        FROM fact_order
    )

    , active_customer AS (
        SELECT * , IF(DATE_DIFF(som, before_som, MONTH) = 1, "REPEAT", "REACQUIRED") AS customer_active_type
        FROM reapeat_customer
        WHERE som <> before_som
        UNION ALL
        SELECT * FROM new_customer
    )

    , order_item AS (
        SELECT
            a.created_date
            , DATETIME(a.created_time, "+7") AS created_time
            , o.delivered_time
            , a.order_id
            , a.product_id
            , CONCAT(a.product_id, "_", a.seller_code, "_", o.warehouse_code) AS sku_key
            -- , a.price AS unit_price
            , a.quantity AS ordered_quantity
            , a.total_price
            , a.price * a.outbound_quantity AS total_outbound
            , s.seller_class
            , o.channel
            , o.customer_id
            , o.status AS order_status
            , g.ward_name
            , g.district_name
            , g.province_name
            , g.region_name
            , g.urban_rural
            , o.total_discount / COUNT(1) OVER(PARTITION BY a.order_id) AS total_discount
        FROM ${source.platinum}.marketplace_prd_order_v2_order_item AS a
            LEFT JOIN ${source.platinum}.seller_prd_core_seller AS s ON a.seller_code = s.code
            LEFT JOIN fact_order AS o ON a.order_id = o.order_id
            LEFT JOIN ${ref('gold_buymed_vn2','dim_geo_location')} AS g ON o.shipping_ward_code = g.location_code
        WHERE 1=1
            AND a.created_date >= "2025-01-01"
            AND o.created_date >= "2025-01-01"
            -- AND o.status <> "CANCEL"
        UNION ALL
        SELECT
            a.created_date
            , DATETIME(a.created_time, "+7") AS created_time
            , o.delivered_time
            , a.order_id
            , a.product_id
            , CONCAT(a.product_id, "_", a.seller_code, "_", o.warehouse_code) AS sku_key
            -- , a.price
            , a.quantity AS ordered_quantity
            , a.total_amount
            , LEAST(COALESCE(SAFE_CAST(JSON_VALUE(a.extra_props, "$.completed_quantity")  AS INT64), quantity), quantity) * price AS total_outbound
            , "INTERNAL" AS seller_class
            , o.channel
            , o.customer_id
            , o.status AS order_status
            , g.ward_name
            , g.district_name
            , g.province_name
            , g.region_name
            , g.urban_rural
            , o.total_discount
        FROM ${source.platinum}.tender_prd_core_tender_order_items AS a
            LEFT JOIN fact_order AS o ON a.order_id = o.order_id
            LEFT JOIN ${ref('gold_buymed_vn2','dim_geo_location')} AS g ON o.shipping_ward_code = g.location_code
        WHERE 1=1
            AND a.created_date >= "2025-01-01"
            AND o.created_date >= "2025-01-01"
    )

SELECT
    oi.*
    , COALESCE(ac.customer_active_type, ac1.customer_active_type) AS customer_active_type
FROM order_item AS oi
    LEFT JOIN active_customer AS ac 
        ON DATE_TRUNC(oi.created_date, MONTH) = ac.som AND oi.customer_id = ac.customer_id AND ac.customer_active_type <> "NEW"
    LEFT JOIN active_customer AS ac1
        ON oi.created_date = ac1.before_som AND oi.customer_id = ac1.customer_id AND ac1.customer_active_type = "NEW"

