config {
    type: "view",
    name: "marketplace_prd_marketing_campaign_banner",
    schema: "platinum_buymed_vn",
    tags: ["marketplace_prd_marketing"]
}


SELECT *, 
  CASE 
    WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
    ELSE "2099-01-01"
  END AS created_date
FROM ${source.silver}.marketplace_prd_marketing_campaign_banner o 
  
  QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'
  WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
      last_updated_time DESC
  )