config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "pim_prd_product_product",
    description: `PIC: minh.luu
    Partition By: Created_date
    `
}
  WITH silver AS (
    SELECT
      key,mg_id,category_codes,registration_number,retail_unit,is_combo,name,volumes,width,is_prescription,atc3_code,is_frozen,similar_product_codes,retail_info,product_owner,main_category_code,slug,brand,weight,dosage_form,buymed_product_code,image_urls,created_time,unit,vat,height,atc2_code,sub_products,org_id,country_code,buymed_product_id,product_code,length,efficacy_codes,product_id,is_fragile,last_updated_time,search_keyword,origin,is_liquid,is_ingredient_special,usage,retail_unit_quantity_per_unit,manufacturer_code,hash_tag,seller_category_code,seller_sub_category_code,updated_by_id,updated_by_name,metadatas,tags,is_herb,is_portable,note,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.pim_prd_product_product
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,category_codes,registration_number,retail_unit,is_combo,name,volumes,width,is_prescription,atc3_code,is_frozen,similar_product_codes,retail_info,product_owner,main_category_code,slug,brand,weight,dosage_form,buymed_product_code,image_urls,created_time,unit,vat,height,atc2_code,sub_products,org_id,country_code,buymed_product_id,product_code,length,efficacy_codes,product_id,is_fragile,last_updated_time,search_keyword,origin,is_liquid,is_ingredient_special,usage,retail_unit_quantity_per_unit,manufacturer_code,hash_tag,seller_category_code,seller_sub_category_code,updated_by_id,updated_by_name,metadatas,tags,is_herb,is_portable,note,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `pim_prd_product_product`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"