config {
    type: "table", 
    description: 
        `
        Data Sharing for Metric.vn;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: Weekly on Monday;
        `,
    tags: ["METRIC_DATA_SHARING"]
}

SELECT
    FORMAT_DATE("%Y-%m-%d", CURRENT_DATE("+7")) AS data_delivery_date
    , FORMAT_DATE("%Y-%m-%d", DATE(a.sku_last_updated_at)) AS data_update_date
    , "THUOCSI" AS platform
    , "VIETNAM" AS country
    , a.product_id
    , a.product_code
    , a.product_name
    , product_link AS product_url
    , REGEXP_REPLACE(JSON_VALUE(b.image_urls, "$[0]"), r'storage.googleapis.com', 'cdn-gcs.thuocsi.vn') AS product_image_url
    , REGEXP_REPLACE(c.description,  r'<[^>]+>', '') AS product_specs
    , CASE
        WHEN d.product_category = "Thuốc kê đơn" THEN "Rx"
        WHEN d.product_category = "Thuốc không kê đơn" THEN "OTC"
        WHEN d.product_category = "Thuốc (Chưa phân loại)" OR d.product_category IS NULL THEN NULL
        ELSE "Non-Drug"
    END AS product_category
    , no_of_skus AS product_variant_count
    , a.sku_code AS sku_id
    , a.product_name AS sku_name
    , a.product_link AS sku_url
    , REGEXP_REPLACE(JSON_VALUE(b.image_urls, "$[0]"), r'storage.googleapis.com', 'cdn-gcs.thuocsi.vn') AS sku_image_url
    , TO_JSON_STRING(b.sub_products) AS bundle_ids
    , b.registration_number
    , b.dosage_form
    , g.efficacy_name AS therapeutic_desc
    , REGEXP_REPLACE(c.indication ,  r'<[^>]+>', '') AS indications
    , REGEXP_REPLACE(c.contraindication ,  r'<[^>]+>', '') AS contraindications
    , d.country_origin AS country_manufacturer
    , d.country_origin AS brand_origin
    , h.ingredients AS molocule
    , b.unit AS pack_type
    , COALESCE(level_4_quantity, level_3_quantity, level_2_quantity, level_1_quantity) AS pack_value
    , COALESCE(level_1_unit, level_2_unit, level_3_unit, level_4_unit) AS pack_unit
    , b.volumes AS pack_desc
    , d.brand
    , d.manufacturer_short_name AS manufacturer
    , d.is_prescription AS prescription_status
    , CASE
        WHEN d.product_category = "Thuốc kê đơn" THEN "Rx"
        WHEN d.product_category = "Thuốc không kê đơn" THEN "OTC"
        WHEN d.product_category = "Thuốc (Chưa phân loại)" OR d.product_category IS NULL THEN NULL
        ELSE "Non-Drug"
    END AS bm_big_cat
    , d.product_category AS bm_category_1
    , i.category_name AS bm_category_2
    , g.efficacy_name AS bm_category_3
    , a.seller_code AS shop_id
    , j.supplier_name AS shop_name
    , a.seller_id AS shop_platform_id
    , k.display_price AS price_before_discount
    , k.sku_display_price AS price
    , l.min_price AS price_min
    , l.max_price AS price_max
    , 1 - SAFE_DIVIDE(k.sku_display_price, k.display_price) AS price_discount_percent
    , m.available_qty AS stock
    , FORMAT_DATE("%Y-%m-%d", b.created_date) AS platform_created_at
    , FORMAT_DATE("%Y-%m-%d", n.order_updated_at) AS order_updated_at
    , m.available_status
    , m.is_hidden
    , n.sales_unit_total
    , n.sales_value_total
    , n.sales_unit_7d
    , n.sales_value_7d
    , n.sales_unit_30d
    , n.sales_value_30d
    , n.sales_unit_last_week
    , n.sales_value_last_week
    , n.sales_unit_last_month
    , n.sales_value_last_month
    , n.sales_unit_this_month
    , n.sales_value_this_month
    , IF(sku_system_status = "GIFT", TRUE, FALSE) AS flag_gwp
FROM ${ref('dim_sku_sales_region_current')} AS a
    LEFT JOIN ${source.platinum}.marketplace_prd_product_v2_product AS b ON a.product_id = b.product_id
    LEFT JOIN ${source.platinum}.marketplace_prd_product_v2_product_description AS c ON a.product_id = c.product_id
    LEFT JOIN ${ref('dim_product')} AS d ON a.product_id = d.product_id
    LEFT JOIN (
        SELECT
            product_id
            , COUNT(sku_code) AS no_of_skus
        FROM ${ref('dim_sku')}
        WHERE seller_code NOT IN ('I1I4OQEM8D','MEDX_E', 'MEDC', 'MED_NT', 'TENDER', 'MEDX-HN', 'DENX', 'MARKETING', '9SUUUUUUUU', 'QMQEM8DN9F', 'UQRRRRRRRR', 'TAM_GIA')
            AND (seller_code = "MEDX" OR seller_class = "EXTERNAL")
        GROUP BY 1
    ) AS e ON a.product_id = e.product_id
    LEFT JOIN ${ref('dim_sku')} AS f ON a.sku_code = f.sku_code
    LEFT JOIN (
        SELECT
            product_id
            , efficacy_name
        FROM ${ref('dim_product_efficacy')}
        WHERE efficacy_level= 1
    ) AS g ON a.product_id = g.product_id
    LEFT JOIN (
        SELECT
            product_id
            , STRING_AGG( ingredient_name, ', ' ORDER BY ingredient_name) AS ingredients
        FROM ${ref('dim_product_ingredient')}
        GROUP BY 1
    ) AS h ON a.product_id = h.product_id
    LEFT JOIN (
        SELECT
            product_id
            , category_name
        FROM ${ref('dim_product_category')}
        WHERE level = 1
    ) AS i ON a.product_id = i.product_id
    LEFT JOIN ${ref('dim_seller')} AS j ON a.seller_id = j.supplier_id
    LEFT JOIN (
        SELECT
            sku_code
            , MIN(sku_display_price) AS sku_display_price
            , MIN(display_price) AS display_price
        FROM ${ref('adhoc_pricing_v2')}
        WHERE SPLIT(sku_code, ".")[OFFSET(0)] NOT IN ('I1I4OQEM8D','MEDX_E', 'MEDC', 'MED_NT', 'TENDER', 'MEDX-HN', 'DENX', 'MARKETING', '9SUUUUUUUU', 'QMQEM8DN9F', 'UQRRRRRRRR', 'TAM_GIA')
        GROUP BY 1
    ) AS k ON k.sku_code = a.sku_code
    LEFT JOIN (
        SELECT
            product_id
            , MIN(sku_display_price) AS min_price
            , MAX(sku_display_price) AS max_price
        FROM ${ref('adhoc_pricing_v2')}
        WHERE SPLIT(sku_code, ".")[OFFSET(0)] NOT IN ('I1I4OQEM8D','MEDX_E', 'MEDC', 'MED_NT', 'TENDER', 'MEDX-HN', 'DENX', 'MARKETING', '9SUUUUUUUU', 'QMQEM8DN9F', 'UQRRRRRRRR', 'TAM_GIA')
        GROUP BY 1
    ) AS l ON a.product_id = l.product_id
    LEFT JOIN (
        SELECT
            sku_code
            , SUM(available_qty) AS available_qty
            , MAX_BY(
                sku_system_status,
                CASE sku_system_status
                    WHEN "NORMAL" THEN 3
                    WHEN "LIMIT" THEN 2
                    WHEN "OUT_OF_STOCK" THEN 1
                    WHEN "SUSPENDED" THEN 0
                    ELSE 0
                END
            ) AS available_status
            , NOT(MAX(sku_system_active)) AS is_hidden
        FROM ${ref('dim_sku_sales_region_current')}
        WHERE (seller_code = "MEDX" OR seller_class = "EXTERNAL")
            AND seller_code NOT IN ('I1I4OQEM8D','MEDX_E', 'MEDC', 'MED_NT', 'TENDER', 'MEDX-HN', 'DENX', 'MARKETING', '9SUUUUUUUU', 'QMQEM8DN9F', 'UQRRRRRRRR', 'TAM_GIA')
        GROUP BY 1
    ) AS m ON a.sku_code = m.sku_code
    LEFT JOIN (
        SELECT
            sku
            , MAX(created_date) AS order_updated_at
            , SUM(quantity) AS sales_unit_total
            , SUM(total_price) AS sales_value_total
            , SUM(IF(created_date BETWEEN CURRENT_DATE - 7 AND CURRENT_DATE - 1, quantity, 0)) AS sales_unit_7d
            , SUM(IF(created_date BETWEEN CURRENT_DATE - 7 AND CURRENT_DATE - 1, total_price, 0)) AS sales_value_7d
            , SUM(IF(created_date BETWEEN CURRENT_DATE - 30 AND CURRENT_DATE - 1, quantity, 0)) AS sales_unit_30d
            , SUM(IF(created_date BETWEEN CURRENT_DATE - 30 AND CURRENT_DATE - 1, total_price, 0)) AS sales_value_30d
            , SUM(IF(created_date BETWEEN DATE_TRUNC(CURRENT_DATE, WEEK(MONDAY ) ) - 7 AND DATE_TRUNC(CURRENT_DATE, WEEK(MONDAY ) ) - 1, quantity, 0)) AS sales_unit_last_week
            , SUM(IF(created_date BETWEEN DATE_TRUNC(CURRENT_DATE, WEEK(MONDAY ) ) - 7 AND DATE_TRUNC(CURRENT_DATE, WEEK(MONDAY ) ) - 1, total_price, 0)) AS sales_value_last_week
            , SUM(IF(created_date BETWEEN DATE_SUB(DATE_TRUNC(CURRENT_DATE, MONTH ), INTERVAL 1 MONTH) AND DATE_TRUNC(CURRENT_DATE, MONTH )  - 1, quantity, 0)) AS sales_unit_last_month
            , SUM(IF(created_date BETWEEN DATE_SUB(DATE_TRUNC(CURRENT_DATE, MONTH ), INTERVAL 1 MONTH) AND DATE_TRUNC(CURRENT_DATE, MONTH )  - 1, total_price, 0)) AS sales_value_last_month
            , SUM(IF(created_date BETWEEN DATE_TRUNC(CURRENT_DATE, MONTH ) AND CURRENT_DATE  - 1, quantity, 0)) AS sales_unit_this_month
            , SUM(IF(created_date BETWEEN DATE_TRUNC(CURRENT_DATE, MONTH ) AND CURRENT_DATE  - 1, total_price, 0)) AS sales_value_this_month
        FROM ${source.platinum}.marketplace_prd_order_v2_order_item AS a
            LEFT JOIN ${ref('fact_order')} AS b ON a.order_id = b.order_id
        WHERE created_date BETWEEN "2024-01-01" AND CURRENT_DATE - 1
            AND DATE(b.created_at) BETWEEN "2024-01-01" AND CURRENT_DATE - 1
            AND b.order_status <> "CANCEL"
            AND b.channel IN ("MARKETPLACE", "CIRCA")
        GROUP BY 1
    ) AS n ON a.sku_code= n.sku
WHERE 1=1
    AND (a.seller_code = "MEDX" OR a.seller_class = "EXTERNAL")
    AND a.seller_code NOT IN ('I1I4OQEM8D','MEDX_E', 'MEDC', 'MED_NT', 'TENDER', 'MEDX-HN', 'DENX', 'MARKETING', '9SUUUUUUUU', 'QMQEM8DN9F', 'UQRRRRRRRR', 'TAM_GIA')
QUALIFY ROW_NUMBER() over (PARTITION BY a.sku_code) = 1