

config {
    type: "table",
    name: "core_prd_master_data_ward",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id',
        nonNull: ["created_date"]
    },
    bigquery: {
        partitionBy: "created_date"
    },
    tags:["custom_2h_past5"]
}

SELECT
 *,
 CASE 
    WHEN created_time IS NOT NULL THEN DATE(created_time)
    ELSE "2099-01-01"
  END AS created_date
FROM ${source.silver}.core_prd_master_data_ward o 
QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)