


config {
    type: "table",
    name: "core_prd_master_data_atc",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id'
    },
    tags: ["custom_2h_past5"]
}

SELECT
 *,
 CASE 
    WHEN silver_buymed_vn.MONGOID_TIMESTAMP(mg_id) IS NOT NULL THEN DATE(silver_buymed_vn.MONGOID_TIMESTAMP(mg_id))
    ELSE "2099-01-01"
  END AS created_date
FROM ${source.silver}.core_prd_master_data_atc o 
QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)
