config {
    type: "operations",
    tags: ["custom_1h_past7","seller_prd_purchasing","Finance/margin"],
}
-- script_tag: ["assert","assert_duplicate"]

js {
    const table_name = "seller_prd_purchasing_purchase_order"
}

DECLARE _assert INT64;
DECLARE sef_dedup BOOL;
DECLARE keys ARRAY <STRING>;
DECLARE dates ARRAY <date>;

SET _assert = (
    SELECT
        COUNT(*)
    FROM (
    SELECT
        mg_id,
        COUNT(1) AS index_row_count
    FROM ${ref(`${table_name}`)}
    GROUP BY mg_id
    ) AS data
    WHERE index_row_count > 1
);

IF ( _assert <> 0 ) THEN 
    INSERT INTO lakehouse-prod-394907.dataform_assertions.log_script
        (key, created_time, name, retry_index, extra_props, platform)
        (
            SELECT 
                GENERATE_UUID(),
                CURRENT_TIMESTAMP(),
                `${table_name}__assert_operations`,
                _loop_index,
                PARSE_JSON('{"level":"CRITITCAL"}'),
                "dataform"
        );
    
    CREATE TEMP TABLE deleted_records AS (
    SELECT key, created_date
    FROM (
        SELECT key, mg_id, synced_at, action, created_date 
        FROM dataform_assertions.${table_name}
        QUALIFY ROW_NUMBER() over(w ) != 1
        WINDOW w AS (PARTITION BY mg_id ORDER BY synced_at desc, IF (action = "u", 2, 1) desc )
    ));

    SET keys = (
        SELECT ARRAY_AGG(key) FROM deleted_records
    );
    SET dates = (
        SELECT ARRAY_AGG(created_date) FROM deleted_records
    );

    SELECT *
    FROM ${ref(`${table_name}`)}
    WHERE key IN UNNEST(keys)
        AND created_date IN UNNEST(dates);
    
    SET _assert = ( -- If Still duplicate
        SELECT
            COUNT(*)
        FROM (
        SELECT
            mg_id,
            COUNT(1) AS index_row_count
        FROM ${ref(`${table_name}`)}
        GROUP BY mg_id
        ) AS data
        WHERE index_row_count > 1
    );

    ASSERT ( _assert = 0) AS "mg_id must be unique key" ;
END IF
