config {
    type: "table",
    name: "delivery_prd_transporting_delivery_truck",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id'
    },
    tags: ["platinum_custom_20m","delivery_prd_transporting"]
}
SELECT 
    *,
    CASE 
        WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
        ELSE "2099-01-01"
    END AS created_date
FROM silver_buymed_vn.delivery_prd_transporting_delivery_truck
QUALIFY ROW_NUMBER() OVER (_window) > 1
WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
    IF(action = 'd', 3, IF(action = 'u', 2, 1))
)