config {
    type: "view",
    name: "delivery_prd_transporting_customer",
    schema: "platinum_buymed_vn",
    tags: ["delivery_prd_transporting"]
}

WITH over_tbl AS (
    SELECT
        mg_id,
        ARRAY_AGG(
            key 
            ORDER BY
                synced_at DESC,
                last_updated_time DESC
            LIMIT 1
        )[0] key ,
        ARRAY_AGG(
            action 
            ORDER BY
                synced_at DESC,
                last_updated_time DESC
            LIMIT 1
        )[0] action
    FROM ${source.silver}.delivery_prd_transporting_customer
    
    GROUP BY mg_id HAVING action != "d"
)
SELECT
    *,
    CASE
        WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
        ELSE DATE( '2099-01-01' )
    END AS created_date,
    CURRENT_DATETIME() AS platinum_refresh
FROM ${source.silver}.delivery_prd_transporting_customer
WHERE key IN (SELECT o.key FROM over_tbl o)