config {
    type: "table",
    name: "delivery_prd_transporting_route",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id',
    },
    tags: ["delivery_prd_transporting", "custom_1h_past7"]
}

SELECT *
FROM ${source.silver}.delivery_prd_transporting_route
 QUALIFY ROW_NUMBER() OVER (_window) = 1 AND FIRST_VALUE(action) OVER (_window) <> 'd'
 WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC,
    last_updated_time DESC)
