config {
    type: "table",
    name: "seller_prd_purchasing_bidding",
    schema: "platinum_buymed_vn",
    assertions: {
         uniqueKey: 'mg_id',
         nonNull: ['created_date'],
         rowConditions: [
        '(created_time is not null and last_updated_time is not null) or (created_time is null and last_updated_time is not null) or (created_time is not null and last_updated_time is null)',
        'action != "d"'
    ]
     },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["custom_1h_past7","seller_prd_purchasing"]
   
}
-- for marketplace_prd_cart only
WITH deleted_records_table AS (
  SELECT mg_id
  FROM lakehouse-prod-394907.silver_buymed_vn.seller_prd_purchasing_bidding
  WHERE action = 'd'
    AND date(ingest_time) >= current_date() - 1
)
SELECT *, 
  CASE 
    WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
    ELSE "2099-01-01"
  END AS created_date
FROM (
  SELECT *
  FROM lakehouse-prod-394907.silver_buymed_vn.seller_prd_purchasing_bidding o 
  QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'
  WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
      IF(action = 'd', 3, IF(action = 'u', 2, 1)) DESC,
      last_updated_time DESC
  )
) 
WHERE (created_time IS NOT NULL OR last_updated_time IS NOT NULL )