

config {
    type: "incremental",
    name: "seller_prd_purchasing_bidding",
    schema: "platinum_buymed_vn",
    assertions: {
         uniqueKey: 'mg_id',
         nonNull: ['created_date'],
         rowConditions: [
        '(created_time is not null and last_updated_time is not null) or (created_time is null and last_updated_time is not null) or (created_time is not null and last_updated_time is null)',
        'action != "d"'
    ]
     },
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["custom_1h_past7"]
   
}

pre_operations {
  ${
    when(incremental(), 
      `
      
      DECLARE min_created_date DATE;
      DECLARE max_created_date DATE;
      DECLARE check_deleted_action INT64;
      DECLARE min_created_date_deleted DATE;
      DECLARE max_created_date_deleted DATE; 

      -- Define the range of created times
      CREATE OR REPLACE TEMP TABLE range_created_time_table AS (
        SELECT 
          MIN(created_date) AS min_created_date, 
          MAX(created_date) AS max_created_date 
        FROM (
          SELECT  
            CASE 
              WHEN created_time IS NOT NULL THEN DATE(created_time) 
              ELSE DATE("2099-01-01") 
            END AS created_date
          FROM ${source.silver}.seller_prd_purchasing_bidding 
          WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()}) 
            AND (
              (created_time IS NOT NULL AND last_updated_time IS NOT NULL) 
              OR (created_time IS NULL AND last_updated_time IS NOT NULL) 
              OR (created_time IS NOT NULL AND last_updated_time IS NULL)
            ) 
            AND action != "d"
        )
      );

      CREATE OR REPLACE TEMP TABLE get_deleted_record AS (
          SELECT mg_id 
          FROM ${source.silver}.seller_prd_purchasing_bidding 
          WHERE  ingest_time > (SELECT MAX(ingest_time) FROM ${self()}) and 
          created_time IS NULL AND last_updated_time IS NULL
        );

      -- Set the minimum and maximum created dates
      SET min_created_date = (SELECT min_created_date FROM range_created_time_table);
      SET max_created_date = (SELECT max_created_date FROM range_created_time_table);
      --SET check_deleted_action = (SELECT check FROM check_deleted_action);
      
      `
    )
  }
}

-- for marketplace_prd_cart only
WITH deleted_records_table AS (
  SELECT mg_id
  FROM ${source.silver}.seller_prd_purchasing_bidding
  WHERE action = 'd'
    AND date(ingest_time) >= current_date() - 1
)
SELECT *, 
  CASE 
    WHEN created_time IS NOT NULL THEN DATE(created_time)
    ELSE "2099-01-01"
  END AS created_date
FROM (
  SELECT *
  FROM ${source.silver}.seller_prd_purchasing_bidding o 
  ${
    when(incremental(), 
      `WHERE ingest_time > (SELECT MAX(ingest_time) FROM ${self()}) 
       QUALIFY ROW_NUMBER() OVER (_window) = 1`,
      `QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'`
    )
  }
  WINDOW _window AS (
    PARTITION BY mg_id
    ORDER BY synced_at DESC,
      IF(action = 'd', 3, IF(action = 'u', 2, 1)) DESC,
      last_updated_time DESC
  )
) 
${
    when(incremental(), 
      `WHERE created_time is null and last_updated_time is null -- all record deleted include action "d"
  OR (created_time IS NOT NULL AND last_updated_time IS NOT NULL AND mg_id NOT IN (SELECT mg_id FROM deleted_records_table))
  OR (created_time IS NULL AND last_updated_time IS NOT NULL AND mg_id NOT IN (SELECT mg_id FROM deleted_records_table))
  OR (action = 'i' AND mg_id NOT IN (SELECT mg_id FROM deleted_records_table))`,
      `WHERE (created_time IS NOT NULL OR last_updated_time IS NOT NULL )`
    )
  }


post_operations {
  ${
    when(incremental(),
      `
      
      -- Delete rows using the temporary table
      IF min_created_date IS NOT NULL AND max_created_date IS NOT NULL THEN
      DELETE FROM ${self()}
      WHERE (created_date BETWEEN min_created_date AND max_created_date)
        AND (key) IN (
          SELECT (key) FROM ${self()} 
          WHERE created_date BETWEEN min_created_date AND max_created_date 
          QUALIFY ROW_NUMBER() OVER (_window) > 1
          --OR FIRST_VALUE(action) OVER (_window) = "d"
          WINDOW _window AS (
            PARTITION BY mg_id
            ORDER BY synced_at DESC,
            IF(action = 'd', 3, IF(action = 'u', 2, 1)) DESC,
            last_updated_time DESC
          )
        );
      END IF;

      IF EXISTS(select * from get_deleted_record limit 1) THEN

        CREATE OR REPLACE TEMP TABLE get_range_deleted AS (
          SELECT 
            MIN(created_date) AS min_created_date_deleted, 
            MAX(created_date) AS max_created_date_deleted 
          FROM ${self()} 
          WHERE mg_id IN (SELECT mg_id FROM get_deleted_record) 
            AND created_date != "2099-01-01" 
        );
        
        SET min_created_date_deleted = (SELECT min_created_date_deleted FROM get_range_deleted);
        SET max_created_date_deleted = (SELECT max_created_date_deleted FROM get_range_deleted);
        IF min_created_date_deleted is not null and max_created_date_deleted is not null THEN
          DELETE FROM ${self()} 
          WHERE created_date BETWEEN min_created_date_deleted AND max_created_date_deleted 
            AND mg_id IN (SELECT mg_id FROM get_deleted_record);
        END IF;

        DELETE FROM ${self()} 
        WHERE created_date = "2099-01-01" 
          AND created_time IS NULL 
          AND last_updated_time IS NULL;
      END IF;
      `,
      ``
    )
  }
}
