config {
    type: "table",
    name: "seller_prd_core_bank",
    schema: "platinum_buymed_vn",
    assertions: {
        uniqueKey: 'mg_id'
    },
    tags:["platinum_custom_2h_past5","seller_prd_core"]
}

SELECT *
FROM ${source.silver}.seller_prd_core_bank
QUALIFY ROW_NUMBER() OVER (_window) = 1
       AND FIRST_VALUE(action) OVER (_window) <> 'd'
WINDOW
  _window AS (
  PARTITION BY
    mg_id
  ORDER BY
    synced_at DESC,
  IF
    (action='d',3,
    IF
      (action='u',2,1)) DESC)