config {
  type: "assertion",
  description: "Assure that total_amount between vendor_bill and vendor_bill item don't miss too much",
  tags: ["platinum_daily_AM_9:00","seller_prd_purchasing"],
  // dependencies: ["seller_prd_purchasing_vendor_bill"]
}

with cte_vendor_bill as (
  select
    vendor_bill_id
    ,sum(coalesce(total_price,0))              as total_amount
  from
    ${source.platinum}.seller_prd_purchasing_vendor_bill
  where
    date(date_add(issued_time,interval 7 hour)) between '2024-01-01' and '2024-12-31'
    -- vendor_bill_id = 767989
  group by
    vendor_bill_id
    ,status
),
cte_vendor_bill_item as (
  select
    vendor_bill_id
    ,sum(total_amount)  as total_amount
  from (
    select
      vbi.vendor_bill_id
      ,coalesce(vbi.total_price,0)              as total_amount
    from
      ${source.platinum}.seller_prd_purchasing_vendor_bill_item vbi
      inner join (
        select distinct
          vendor_bill_id
        from
          ${source.platinum}.seller_prd_purchasing_vendor_bill
        where
          date(date_add(issued_time,interval 7 hour)) between '2024-01-01' and '2024-12-31'
          -- vendor_bill_id = 767989
      ) vb
        on vbi.vendor_bill_id = vb.vendor_bill_id
    where
      vbi.product_id <> 0
    union all
    select
      vendor_bill_id
      ,coalesce(total_discount_after_vat*-1,0)      as total_amount
    from
      ${source.platinum}.seller_prd_purchasing_vendor_bill
    where
      date(date_add(issued_time,interval 7 hour))between '2024-01-01' and '2024-12-31'
      and total_discount_after_vat <> 0
      -- and vendor_bill_id = 767989
  )
  group by
    vendor_bill_id
)

-- select vendor_bill_id, format("%'d",cast(total_amount as int64)) as total_amount from cte_vendor_bill_item

select 
  cvb.vendor_bill_id
  ,vbm.status
  ,format("%'d",cast(cvb.total_amount as int64)) as total_amount_cvb
  ,format("%'d",cast(cvbi.total_amount as int64)) as total_amount_cvbi
  , format("%'d",cast(abs( cvbi.total_amount - cvb.total_amount) as int64)) as delta
from 
  cte_vendor_bill cvb
  left join cte_vendor_bill_item cvbi
    on cvb.vendor_bill_id = cvbi.vendor_bill_id
  left join ${source.platinum}.seller_prd_purchasing_vendor_bill vbm
    on cvb.vendor_bill_id = vbm.vendor_bill_id
where
  ((cvb.total_amount - cvbi.total_amount >= 100) or  (cvb.total_amount - cvbi.total_amount <= -100))
  and vbm.status not in ('CANCEL','DRAFT')