config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Inventory in the Vietnam marketplace.`,
    tags: ['AI_THUOCSI_VN']
}

SELECT
    product_id
    , sku AS sku_code
    , CONCAT(product_id, "_", seller_code, "_", warehouse_code) AS sku_key
    , b.seller_id
    , seller_code
    , seller_class
    , warehouse_code
    , stock_quantity
    , available_quantity
    , avg_demand_l30d AS avg_daily_demand_l30d
    , SAFE_DIVIDE(stock_quantity, avg_demand_l30d) AS stock_days
FROM ${source.platinum}.warehouse_prd_inventory_sku AS a
    LEFT JOIN ${source.platinum}.seller_prd_core_seller AS b ON a.seller_code = b.code
    LEFT JOIN ${ref('gold_buymed_vn2', 'agg_avg_demand_sku_item_l30d')} AS c ON CONCAT(product_id, "_", seller_code, "_", warehouse_code) = c.sku_fc_key
WHERE warehouse_code IN ("BD", "HN")