config {
    type: 'view',
    schema: "buymed_innovation",
    description: `Net Profit of the Vietnam marketplace.`,
    tags: ['AI_THUOCSI_VN']
}


SELECT
    a.created_date
    , a.order_id
    , a.customer_id
    , a.channel
    , a.ward_name
    , a.district_name
    , a.province_name
    , a.region_name
    , a.urban_rural
    , SUM(a.profit) AS gross_profit
    , SUM(a.net_profit) AS net_profit
    , SUM(a.voucher_discount) AS total_discount
    , SUM(a.total_price) AS total_price
    , SUM(a.cogs_after_rebate) AS cogs_after_rebate
FROM ${ref("buymed_innovation", "thuocsi_vn_fact_margin")} AS a
GROUP BY ALL
