config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 past hour 6, 8, 10, 12, 14, 16, 18, 20 and 22`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_2h_past5"],
    name: "circa_reconcile_collect",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
    partitionBy: "created_date"
}
}

with cte_pos_info as (
	select
		pp.code						as pos_code
		,pp.id						as pos_id
		,tag.tag_name
	from ${source.circa}.entity_pos_profile pp
	left join (
			select
				epp.pos_code
				,string_agg(pos_tag)		            as tag_code
				,coalesce(string_agg(et.name),'')		as tag_name
			from (
				select
					code																		as pos_code
					, json_extract_string_array(tag_code)		as tag_array
				from ${source.circa}.entity_pos_profile
			) epp
				left join unnest(tag_array)	as pos_tag
				left join ${source.circa}.entity_tag et
					on pos_tag = et.code
			group by pos_code
		) tag on tag.pos_code = pp.code
	where
		contains_substr(tag.tag_name,'test') = false
    and pp.deleted_at is null
)
,reconcile_convert as (
       Select distinct date(t.Date_convert) as created_date
                       ,Pos_code as pos_code
                       ,reconcile_amount as circa_collect
                       ,'Công nợ chuyển đổi' as type_amount
       from buymed_external.fs_new_contract t
        -- công nợ chốt tại ngày chuyển đổi
)
,reconcile as (
      select
        date(date_add(created_time, interval 7 hour) ) as created_date
       ,entity_code          as pos_code
       ,final_amount         as circa_collect
       ,'FS chưa chuyển đổi' as type_amount
       ,rec_template_code
       ,rec_code
	    from ${source.platinum}.platform_accounting_prd_reconcile_reconcile
      where
        status <> 'IN_SESSION'
        and rec_template_code = 'CIRCAFS'
        and entity_code in (select pos_code from cte_pos_info)
        and entity_code not in (select Pos_code from buymed_external.fs_new_contract)
     --lấy những FS chưa chuyển đổi

union all
       Select distinct date(date_add(l.created_time, interval 7 hour) )
           ,entity_code as pos_code
           ,sum(l.line_amount) as circa_collect
           ,'Phí theo tháng' as type_amount
           ,rec_template_code
           ,rec_code
        from ${source.platinum}.platform_accounting_prd_reconcile_CIRCA_FS_EXTERNAL_reconcile_line l
where rec_template_code = 'CIRCAFS_FEE'
--  date(date_add(l.created_time, interval 7 hour) ) > (
--                                        Select date(t.Date_convert)
--                                        from buymed_external.fs_new_contract t
--                                        where Pos_code = l.entity_code)
               and entity_code in (select Pos_code from buymed_external.fs_new_contract)
              ---- các loại phí sau chuyển đổi
group by all

union all
select distinct date(date_add(l.created_time, interval 7 hour) )
                  ,entity_code
                   ,cast(json_extract_scalar(extra_fee, '$.amount') AS FLOAT64) as amount
                   ,'Extra_fee' as type_amount
                   ,rec_template_code
                   ,rec_code
                   from ${source.platinum}.platform_accounting_prd_reconcile_reconcile l,
                   unnest (JSON_EXTRACT_ARRAY(extra_fees)) AS extra_fee
where extra_fees IS NOT NULL
      -- and date(date_add(l.created_time, interval 7 hour) ) > (
      --           Select date(t.Date_convert)
      --           from buymed_external.fs_new_contract t
      --           where Pos_code = l.entity_code)
      and (rec_template_code = 'CIRCAFS_FEE' or  rec_template_code = 'CIRCAFS_DEBT' )
      and entity_code in (select Pos_code from buymed_external.fs_new_contract)
      group by all
      -- extra phí (nhập manual) sau ngày chuyển đổi 
          
union all
Select distinct  
     created_date
     ,p.code
    ,sum(PO_amount)
    ,'Công nợ phát sinh' as type_amount
    ,'' as rec_template_code
    ,'' as rec_code

 from ${source.ref}.circa_purchase_order o 
 left join ${source.circa}.entity_pos_profile p on o.pos_id = p.id
 where o.created_date > (
                Select date(t.Date_convert)
                from buymed_external.fs_new_contract t
                where Pos_code = o.code)
      and o.code in (select Pos_code from buymed_external.fs_new_contract)
      and (o.recon_payment_method = 'PREPAYMENT_DEBT' or o.recon_payment_method = 'PURCHASING_DEBT' )
      group by all)
      -- SI sau ngày chuyển đổi)

  Select * from reconcile  t

   