config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 past hour 6, 8, 10, 12, 14, 16, 18, 20 and 22`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_2h_past5"],
    name: "circa_reconcile_AR",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
    partitionBy: "created_date"
}
}


with reconcile as (
   select
        date(date_add(created_time, interval 7 hour) ) as created_date
       ,entity_code          as pos_code
       ,Sum(final_amount )        as circa_collect
       ,'FS chưa chuyển đổi' as type_amount
       ,rec_template_code
       ,rec_code
       ,date(date_add(pay_due_time, interval 7 hour) ) as pay_due_time
      from ${source.platinum}.platform_accounting_prd_reconcile_reconcile
      where entity_code in (select Pos_code from ${source.ref}.Circa_reconcile_collect_convert)
       and rec_template_code in('CIRCAFS_DEBT','CIRCAFS_FEE')
       group by all
)
Select t.*
       ,d.created_date as Date_collected
       ,d.collected_amount 
       ,d.object_code
       ,case when (d.collected_amount is null or d.collected_amount <> t.circa_collect)
                  then 'not_enough' 
            when d.collected_amount = t.circa_collect then 'pay_enough' end as is_pay_enough
       ,case when pay_due_time <= current_date() then true 
             else false
       end as is_exceed_due_time
           from reconcile t
left join `${source.ref}.circa_reconcile_collected` d on t.rec_code = d.object_code
where circa_collect <> 0
--and t.pos_code = 'POS0243'
--and (d.collected_amount is null or d.collected_amount <> t.circa_collect)
--group by all
--having pay_due_time <= current_date()
union all
Select t.*
       ,d.created_date as Date_collected
       ,d.collected_amount 
       ,d.object_code
       ,case when (d.collected_amount is null or d.collected_amount <> t.circa_collect)
                  then 'not_enough' 
            when d.collected_amount = t.circa_collect then 'pay_enough' end as is_pay_enough
       ,case when pay_due_time <= current_date() then true 
       else false end as is_exceed_due_time
        from `${source.ref}.circa_reconcile_collect` t
left join `${source.ref}.circa_reconcile_collected` d on t.rec_code = d.object_code
where t.pos_code not in (select Pos_code from ${source.ref}.Circa_reconcile_collect_convert)
--and (d.collected_amount is null or d.collected_amount <> t.circa_collect)
and circa_collect <> 0