const order_id = `Unique identifier for each order`;
const sku = "The unique identifier for each SKU";
const sku_key = "uniquely identifies the combination of product and seller. A key generated by concatenating product_id and seller_code with an underscore";
const province_code = "A standardized code used to identify provinces within a country";
const item_code = "A code representing the item";
const product_name = "The name of product"
const supplier_code = "uniquely identifying each supplier"
const fc_code = "uniquely identifying each fulfillment center"
const pic_purchase_id = "The unique identifier for the employee, Who takes reponsible for the supplier. Purchaser for Vendor and SC for Seller";
const cic_category_id = "The unique identifier for the employee, Who takes reponsible for the supplier and working in Commercial Dpt";
const supplier_fc_code = "uniquely identifies the combination of supplier and fulfillment center, A key generated by concatenating supplier_code and fc_code";


module.exports = {
    order_id,
    sku,
    sku_key,
    province_code,
    item_code,
    product_name,
    supplier_code,
    fc_code,
    pic_purchase_id,
    cic_category_id,
    supplier_fc_code
};