const order_id = `Unique identifier for each order`;
const sku = "The unique identifier for each SKU";
const sku_key = "A key generated by concatenating product_id and seller_code with an underscore. This key uniquely identifies the combination of product and seller";
const province_code = "A standardized code used to identify provinces within a country";
const item_code = "A code representing the item";
const product_name = "The name of product"
const supplier_code = "uniquely identifying each supplier"
const fc_code = "primary-key"

module.exports = {
    order_id,
    sku,
    sku_key,
    province_code,
    item_code,
    product_name,
    supplier_code,
    fc_code
};