config {
    type: "incremental",
    protected: true,
    // description: "PIC"
    bigquery : {
        partitionBy: "created_date",
        clusterBy: ["date_index"]
    },
    tags: ["16h10"]
}


  SELECT 
    *, 
        CASE 
        WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
        ELSE "2099-01-01"
    END AS created_date,
    FORMAT_TIMESTAMP( "%y%m%d",CURRENT_TIMESTAMP()) date_index
  FROM ${ref("platinum_buymed_vn","marketplace_prd_product_v2_sku_limit")}
  

  --  SELECT *, 
  --   CASE 
  --   WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time,'Asia/Ho_Chi_Minh'))
  --   ELSE "2099-01-01"
  -- END AS created_date,
  --   FORMAT_TIMESTAMP( "%y%m%d",CURRENT_TIMESTAMP) date_index
  -- FROM silver_buymed_vn.marketplace_prd_product_v2_sku_limit
  -- WHERE last_updated_time  <= TIMESTAMP("2025-05-19T16:00:00") - INTERVAL 7 HOUR
  -- QUALIFY ROW_NUMBER() OVER (_window) = 1
  --      AND FIRST_VALUE(action) OVER (_window) <> 'd'
  -- WINDOW
  --   _window AS (
  --   PARTITION BY
  --     mg_id
  --   ORDER BY
  --     synced_at DESC,
  --   IF
  --     (action='d',3,
  --     IF
  --       (action='u',2,1)) DESC,
  --     last_updated_time DESC
  --     )