config {
    type: "view",
    name: "dedup_marketplace_prd_order_v2_order_item",
    description: "PIC: nguyen.tran"
}

SELECT
   *
FROM silver_buymed_vn.marketplace_prd_order_v2_order_item as a
WHERE
    ingest_time >= TIMESTAMP_SUB('2022-01-01', interval 7 hour)
    AND (created_time >= TIMESTAMP_SUB('2022-01-01', interval 7 hour) OR created_time is null)
--     AND mg_id = '65a625e0a7f2f194d49099e3'
QUALIFY ROW_NUMBER() OVER(_window) = 1 AND FIRST_VALUE(action) OVER(_window) <> 'd'
WINDOW 
    _window AS (
        PARTITION BY mg_id
        ORDER BY synced_at DESC, IF(action = 'd', 3, IF(action = 'u', 2, 1)) DESC, last_updated_time DESC
    )