config {
    type: "table",
    description: "PIC: minh.luu; model_type: table; schedule: 0h00"
}

SELECT
    order_id, 
    product_name, 
    type, 
    unit_code, 
    product_code, 
    unit, 
    price, 
    sku, 
    order_code, 
    seller_class, 
    unit_name, 
    vat, 
    quantity, 
    completed_quantity, 
    seller_code, 
    product_id
FROM ${dedup.dedup(
    'silver_buymed_vn.oms_prd_order_order_item',
    `*`
)}