config {
    type: "table",
    description: "PIC: minh.luu; model_type: table; schedule: 0h00"
}

SELECT 
    order_code, 
    DATETIME(TIMESTAMP(created_time), 'Asia/Ho_Chi_Minh') as created_time,
    DATE    (TIMESTAMP(created_time), 'Asia/Ho_Chi_Minh') as created_date,
    sale_order_code, 
    sale_order_status, 
    deliver_status,
    DATETIME(TIMESTAMP(delivered_time), 'Asia/Ho_Chi_Minh') as delivered_time, 
    total_price, 
    customer_id, 
    customer_province_code, 
    status, 
    customer_phone, customer_code, customer_name, customer_ward_code, country_code
FROM ${dedup.dedup(
    "silver_buymed_vn.oms_prd_order_order",
    `*`
)}