config {
    type: "incremental",
    description: "item_code status change history || PIC: minh.luu;  model_type: table; schedule: hourly past 5",
    name: "staging_sku_status_history",
    bigquery: {
        partitionBy: "DATE(created_time)",
        clusterBy: ["item_code"]
    },

    tags: ["custom_1h_past5"]
    
}

-- extract sku, item_code and status, and filter the time status of item_cod changed
js {
    const checkpoint = `CURRENT_TIMESTAMP() - INTERVAL 12 HOUR`;
    const mode = "prd";

    let incremental_bound;
    let full_refresh_bound;
    if (mode == "stg") {
        incremental_bound = `WHERE ingest_time >= TIMESTAMP("2025-11-02") AND ingest_time <= TIMESTAMP("2025-11-03")`;
        full_refresh_bound = `WHERE ingest_time >= TIMESTAMP("2025-11-01") AND ingest_time <= TIMESTAMP("2025-11-02")`;
    } else if (mode == "prd") {
        incremental_bound = `WHERE ingest_time > ${checkpoint}`;
        full_refresh_bound = `WHERE ingest_time > "2024-01-01" AND created_time > "2024-01-01"`;
    }
}

SELECT
    JSON_VALUE(extra_props, "$.sku") AS sku,
    JSON_VALUE(extra_props, "$.item_code") AS item_code,
    JSON_VALUE(next, "$.seller_class") AS seller_class,
    created_time,
    JSON_VALUE(next, "$.status") AS status,
    cast(JSON_VALUE(next, "$.is_active") as boolean ) as is_active,
    ingest_time,
    key
FROM
    ${source.silver}.marketplace_prd_product_v2_history_update_price  a
${ when(incremental(), incremental_bound, full_refresh_bound)}

QUALIFY status <> COALESCE(LAG(status) OVER (w),"::NonExistance" ) 
WINDOW w AS (
    PARTITION BY item_code
    ORDER BY created_time DESC, 
        ingest_time DESC -- Because this Mongo Collection will only be append, not upđate value
)

post_operations {
  ${
    when(incremental(),
        `
        CREATE TEMP TABLE tbl AS (
            SELECT key, item_code, created_time,status
            FROM ${self()}
            QUALIFY  status = LAG(status) OVER(w)
            WINDOW w AS (
                PARTITION BY item_code
                ORDER BY created_time DESC, 
                    ingest_time DESC -- Because this Mongo Collection will only be append, not upđate value
            )
        );
        DELETE FROM ${self()}
        WHERE key IN (
            SELECT key
            FROM tbl
        ) AND item_code IN ( select DISTINCT item_code FROM tbl)
        `,
        ``
    )
  }
}

