config {
    type: "table",
    description: "item_code status change history || PIC: minh.luu;  model_type: table; schedule: hourly past 5",
    name: "staging_sku_status_history",
    bigquery: {
        partitionBy: "DATE(created_time)",
        clusterBy: ["item_code"]
    },
    columns:{
        product_id: "",
        sku: "",
        item_code: "",
        created_date: "date with VN timezone, if created_time is null then created_date will be 2099-01-01",
        created_time: "timestamp with UTC timzone",
        status: "status",
        is_active: "is_active",
        synced_at: "synced_at",
        key: "key use to map to silver - which is unique identify in silver layer",
    },

    tags: ["custom_1h_past5"]
    
}

-- extract sku, item_code and status, and filter the time status of item_cod changed
js {
    const checkpoint = `CURRENT_TIMESTAMP() - INTERVAL 12 HOUR`;
    const mode = "prd";

    let incremental_bound;
    let full_refresh_bound;
    if (mode == "stg") {
        incremental_bound = `AND synced_at >= TIMESTAMP("2025-11-02") AND synced_at <= TIMESTAMP("2025-11-03")`;
        // full_refresh_bound = `AND synced_at >= TIMESTAMP("2025-11-01") AND synced_at <= TIMESTAMP("2025-11-02")`;
        full_refresh_bound = ``
    } else if (mode == "prd") {
        incremental_bound = `AND synced_at > ${checkpoint}`;
        full_refresh_bound = `AND synced_at > "2024-01-01" AND created_time > "2024-01-01"`;
    }
}

SELECT
    product_id,
    JSON_VALUE(extra_props, "$.sku") AS sku,
    JSON_VALUE(extra_props, "$.item_code") AS item_code,
    CASE 
        WHEN created_time IS NULL THEN DATE("2099-01-01")
        ELSE DATE(created_time + INTERVAL 7 HOUR )
    END AS created_date,
    created_time,
    JSON_VALUE(next, "$.status") AS status,
    cast(JSON_VALUE(next, "$.is_active") as boolean ) as is_active,
    synced_at,
    key
FROM
    ${source.platinum}.marketplace_prd_product_v2_history_update_price  a
WHERE json_value(a.extra_props.action_mg) in ('UPDATE_SKU', 'CREATE_SKU')
${ when(incremental(), incremental_bound, full_refresh_bound)}

QUALIFY status <> LAG(status) OVER (w) OR LAG(status) OVER(w) IS NULL
WINDOW w AS (
    PARTITION BY item_code
    ORDER BY created_time ASC, 
        synced_at ASC -- Because this Mongo Collection will only be append, not upđate value
)

-- Use Platinum_Incremental strategy

-- post_operations {
--   ${
--     when(incremental(),
--         `
--         CREATE TEMP TABLE tbl AS (
--             SELECT key, item_code, created_time,status
--             FROM ${self()}
--             QUALIFY  status = LEAD(status) OVER(w)
--                 AND LEAD(status) OVER(w) IS NOT NULL
--             WINDOW w AS (
--                 PARTITION BY item_code
--                 ORDER BY created_time DESC, 
--                     synced_at DESC -- Because this Mongo Collection will only be append, not upđate value
--             )
--         );
--         DELETE FROM ${self()}
--         WHERE key IN (
--             SELECT key
--             FROM tbl
--         ) AND item_code IN ( select DISTINCT item_code FROM tbl)
--         `,
--         ``
--     )
--   }
-- }

