config {
    type: "table",
    description: `List sản phẩm hot dealthansg 1 2025 | PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`,
    -- tags: ["10h30"],
    disabled: true,
    name: "circa_dim_price_competitor",
    columns: {/*
        */
        
    }
}

WITH market_raw AS (
    SELECT
          SAFE_CAST(JSON_EXTRACT_SCALAR(a.extra_props.product_id) AS INT64) AS product_id
        , JSON_EXTRACT_SCALAR(a.extra_props.unit) AS unit
        , JSON_EXTRACT_SCALAR(a.extra_props.source) AS comp_name
        , SAFE_CAST(JSON_EXTRACT_SCALAR(a.extra_props.conversion_rate) AS FLOAT64)
            * SAFE_CAST(JSON_EXTRACT_SCALAR(a.extra_props.market_price) AS INT64) AS comp_price
        , a.created_date
        , a.last_updated_time
    FROM `platinum_buymed_vn.marketplace_prd_product_v2_product_market_price` a
    WHERE 1 = 1
        AND JSON_EXTRACT_SCALAR(a.extra_props.source) IN ('LongChau', 'Pharmacity')
        AND JSON_EXTRACT_SCALAR(a.extra_props.product_id) IS NOT NULL
        AND JSON_EXTRACT_SCALAR(a.extra_props.qc) IN ('QC', 'QC done')
        AND LOWER(JSON_EXTRACT_SCALAR(a.extra_props.market_name)) NOT LIKE '%[ngưng bán]%'
        AND LOWER(JSON_EXTRACT_SCALAR(a.extra_props.market_name)) NOT LIKE '%[chờ hàng]%'
        AND DATE(a.last_updated_time + INTERVAL 7 HOUR)
            >= CURRENT_DATE('Asia/Ho_Chi_Minh') - 3
        AND SAFE_CAST(JSON_EXTRACT_SCALAR(a.extra_props.conversion_rate) AS FLOAT64)
            * SAFE_CAST(JSON_EXTRACT_SCALAR(a.extra_props.market_price) AS INT64) >= 1000
)

, market AS (
    SELECT
          a.product_id
        , a.comp_name
        , a.comp_price
    FROM market_raw a
    LEFT JOIN `platinum_buymed_vn.marketplace_prd_product_v2_product` b
        ON a.product_id = b.product_id
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY a.product_id, a.comp_name
        ORDER BY a.last_updated_time DESC
    ) = 1
)
SELECT
      product_id
    , MIN(a.comp_price) AS min_comp
    , COUNT(comp_name) AS no_competitor
    , STRING_AGG(comp_name, ', ') AS competitors
FROM market a
GROUP BY ALL