config {
    type: "table",
    description: `PIC: huyen.ngo; 
                  model_type: Table ;
                  schedule: At minute 15 every 2 hours.
                  Circa account online`,
    tags: ["custom_1h_past15"],
    name: "circa_account_online",
    bigquery: {
        partitionBy: "date(created_time)"
    }
}

SELECT TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR)                           AS transformed_at
       ,account_id 
       ,full_name
       ,phone_number
       ,status
       ,code
       ,customer_id
       ,gender
       ,DATETIME_ADD(created_time, INTERVAL 7 HOUR)                                  AS created_time
       ,DATE(DATETIME_ADD(created_time, INTERVAL 7 HOUR))                            AS created_date
       ,DATETIME_ADD(last_updated_time, INTERVAL 7 HOUR)                             AS last_updated_time
       ,DATETIME_ADD(platinum_refresh, INTERVAL 7 HOUR)                              AS platinum_refresh
FROM platinum_buymed_vn.circa_online_prd_consumer_customer
QUALIFY ROW_NUMBER() OVER(PARTITION BY phone_number ORDER BY created_time DESC) = 1
