config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["10h30"],
    name: "cos_dim_category",
    columns: {/*
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"*/
        
    }
}

SELECT DISTINCT code AS categories_code
               ,name
               ,client_id
               ,main_category_id
               ,CONCAT(code, '_', client_id) AS categories_code_client_id
FROM ${source.circa_os}.product_main_category
