config {
    type: "table",
    description: `dim_employee từ tháng 11/2025 detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    name: "cos_dim_employee_comission",
    columns: {
        
    }
}
WITH base_data AS (
    SELECT * FROM (
        SELECT code AS pos_code_email
              ,SPLIT(code, '_')[SAFE_OFFSET(0)] AS pos_code
              ,SPLIT(code, '_')[SAFE_OFFSET(1)] AS employee_email
              ,DATE(submit_at) AS year_month
              ,LOWER(type) AS type
              ,value
        FROM collector.data_prd
        WHERE object = 'CIRCA_EMPLOYEE'
          AND type IN ('POSITION', 'NO_WORKING_DAY')
        QUALIFY ROW_NUMBER() OVER(PARTITION BY pos_code_email, object, type ORDER BY submit_id DESC) = 1
    )
    PIVOT (
        MAX(value) FOR type IN ('position', 'no_working_day')
    )
)
,_add_email_system AS (
    SELECT * EXCEPT(no_working_day)
          ,CAST(no_working_day AS NUMERIC) AS no_working_day
          ,CASE 
              WHEN employee_email = 'bao.doan@buymed.com' THEN 'gbaugust1996@buymed.com'
              WHEN employee_email = 'chau.le@buymed.com' THEN 'chau.leminh@buymed.com'
              WHEN employee_email = 'lien.tranthi@buymed.com' THEN 'lienlientran1012@buymed.com'
              WHEN employee_email = 'oanh.nguyenkim@buymed.com' THEN 'cc.nguyenoanh@buymed.com'
              WHEN employee_email = 'trang.vothuy@buymed.com' THEN 'VN280725-007@buymed.com'
              WHEN employee_email = 'lytuyetbang@buymed.com' THEN 'bang.ly@buymed.com'
              ELSE employee_email 
           END AS email_system
    FROM base_data
)
SELECT i.*
      ,e.name AS employee_name
      ,CONCAT(FORMAT_DATE('%Y-%m', year_month), "_", pos_code, "_", email_system) AS ym_emp_pos
FROM _add_email_system i 
LEFT JOIN (
    SELECT DISTINCT email
          ,name
    FROM `buymed_circa_v2.entity_entity`
    WHERE client_id = 1
    QUALIFY ROW_NUMBER() OVER(PARTITION BY email, client_id ORDER BY updated_at DESC) = 1
) e ON i.email_system = e.email


