config {
    type: "table",
    description: `dim_employee từ tháng 11/2025 detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_1h_past5"],
    name: "cos_dim_employee_comission",
    columns: {
        
    }
}

with base_data as (
    Select * from (
    Select  code as pos_code_email
           ,split(code, '_')[SAFE_OFFSET(0)]                 as pos_code
           ,split(code, '_')[SAFE_OFFSET(1)]                 as employee_email
           ,date(submit_at)                                  as year_month
           ,lower(type)                                      as type
           ,value

    from collector.data_prd
    where object = 'CIRCA_EMPLOYEE'
          and type in ('POSITION','NO_WORKING_DAY')
         qualify ROW_NUMBER() over(partition by pos_code_email, object, type order by submit_id desc) = 1
                  ) 
    pivot (
             max(value) for type in ('position','no_working_day')
            )
                 )
,   _add_email_system as (
    Select * except (no_working_day)
           , cast(no_working_day as int64) as no_working_day
           ,case when employee_email = 'bao.doan@buymed.com' then 'gbaugust1996@buymed.com'
                 when employee_email = 'chau.le@buymed.com' then 'chau.leminh@buymed.com'
                 when employee_email = 'lien.tranthi@buymed.com' then 'lienlientran1012@buymed.com'
                 when employee_email = 'oanh.nguyenkim@buymed.com' then 'cc.nguyenoanh@buymed.com'
                 when employee_email = 'trang.vothuy@buymed.com' then 'VN280725-007@buymed.com'
                 when employee_email = 'lytuyetbang@buymed.com' then 'bang.ly@buymed.com'
                 else employee_email end as email_system
          
    from base_data

)
Select * 
       ,concat(FORMAT_DATE('%Y-%m', year_month),"_",pos_code,"_",email_system) as ym_emp_pos
      from _add_email_system
