config {
    type: "table",
    description: `Dim product | PIC: huyen.ngo; model_type: Table ;schedule: custom_1h_past20`,
    tags: ["custom_1h_past20"],
    name: "cos_dim_product",
    columns: {/*
*/
        
    }
}

WITH cte_product AS (
    SELECT DISTINCT p.product_id
          ,p.name AS product_name
          ,tp.retail_name
          ,p.volumes
          ,p.unit
          ,p.length
          ,p.height
          ,p.weight
          ,p.width
          ,is_fragile
          ,is_frozen
          ,is_herb
          ,is_ingredient_special
          ,is_portable
          ,tp.origin
          ,manufacturer_short_name
          ,tp.registration_number
          ,tp.product_category_code
          ,tp.product_category
          ,t.category_name AS cat2
          ,e.efficacy_name AS cat3
          ,tp.retail_category_name as cat4
          ,p.dosage_form
          ,tp.product_report_category
          ,mc.code AS main_category_code
          ,m.name AS manufacture_name
          ,is_combo
          ,is_gift
          ,is_etc
          ,ARRAY_TO_STRING(JSON_VALUE_ARRAY(image_urls), ', ') AS image_urls
          ,price_type
          ,tp.chronic
          ,thuocsi_product_status
          ,thuocsi_has_stock
          ,thuocsi_unit
          ,thuocsi_quantity
          ,tp.brand 
          ,p.client_id
          ,tp.user_type
          ,DATETIME_ADD(created_at, INTERVAL 7 HOUR)   AS created_at
    FROM ${source.circa_os}.product_product p
    LEFT JOIN ${source.circa_os}.product_main_category mc ON p.main_category_code = mc.code AND p.client_id = mc.client_id
    LEFT JOIN ${source.circa_os}.product_manufacturer m ON p.manufacturer_code = m.code AND p.client_id = m.client_id
    LEFT JOIN ${source.circa_os}.product_seller_category sc ON p.seller_category_code = sc.seller_category_code AND p.client_id = sc.client_id
    LEFT JOIN (SELECT DISTINCT product_id, category_name FROM `gold_buymed_vn2.dim_product_category` WHERE level = 1) t ON p.product_id = t.product_id 
    LEFT JOIN (SELECT DISTINCT product_id, efficacy_name FROM gold_buymed_vn2.dim_product_efficacy WHERE efficacy_level = 1) e ON p.product_id = e.product_id
    LEFT JOIN ${ref('dim_product')} AS tp ON p.product_id = tp.product_id
)
,inventory_summary AS (
    SELECT a.product_id
          ,a.pos_id
          ,a.client_id
          ,SUM(a.on_hand_quantity) AS total_on_hand_quantity
          ,ep.name AS pos_name
    FROM ${source.ref}.cos_fact_inventory a
    LEFT JOIN ${source.ref}.circa_pos_profile ep 
           ON a.pos_id = ep.id 
          AND a.client_id = ep.client_id
          AND ep.actual_status <> 'Inactive'
    WHERE ep.id IS NOT NULL
    GROUP BY ALL
)
,inventory AS (
    SELECT product_id
          ,SUM(total_on_hand_quantity) AS on_hand_quantity
          ,COUNT(DISTINCT CASE WHEN client_id = 1 AND total_on_hand_quantity > 0 THEN pos_id END) AS pos_os_have_stock
          ,COUNT(DISTINCT CASE WHEN client_id <> 1 AND total_on_hand_quantity > 0 THEN pos_id END) AS pos_fs_have_stock
          ,STRING_AGG(DISTINCT pos_name, ', ') AS stock_available_in_poss
          ,client_id
    FROM inventory_summary
    GROUP BY product_id, client_id
)
,ingregients AS (
    SELECT DISTINCT product_id
          ,ingredient_name
          ,volume
          ,usage
          ,client_id
    FROM ${ref('cos_dim_product_ingredient')}
    WHERE ingredient_level = 1
)
,product_base_unit AS (
    SELECT DISTINCT a.product_id
          ,a.unit AS base_unit
          ,client_id
    FROM ${source.circa_os}.product_retail_unit AS a
    WHERE a.base_unit IS TRUE 
      AND (unit IS NOT NULL OR unit <> "")
    QUALIFY ROW_NUMBER() OVER(PARTITION BY product_id, client_id ORDER BY created_at DESC) = 1
)
,convert_unit AS (
     WITH only_all_false AS (
          SELECT
            product_id
            ,client_id
          FROM  ${source.circa_os}.product_retail_unit
          GROUP BY product_id, client_id
          HAVING
            COUNTIF(purchase_allowed = TRUE) = 0
            AND COUNT(*) > 0
),filtered AS (
         SELECT
            a.product_id
           ,a.convert_rate
           ,a.unit AS convert_unit
           ,a.client_id
         FROM  ${source.circa_os}.product_retail_unit a
         JOIN only_all_false b USING (product_id, client_id)
         WHERE a.unit IS NOT NULL AND a.unit != ""
)
SELECT
   product_id
  ,convert_rate
  ,convert_unit
  ,client_id
FROM filtered
QUALIFY ROW_NUMBER() OVER ( PARTITION BY product_id, client_id  ORDER BY convert_rate DESC) = 1
UNION ALL
  SELECT a.product_id
          ,convert_rate
          ,unit AS convert_unit
          ,client_id
    FROM lakehouse-prod-394907.buymed_circa_v2.product_retail_unit AS a
    WHERE (unit IS NOT NULL OR unit <> "")
          AND purchase_allowed is true
         -- and client_id = 1
          --and product_id = 84855
    QUALIFY ROW_NUMBER() OVER(PARTITION BY product_id, client_id ORDER BY convert_rate DESC) = 1

), ts_unit AS (
    SELECT DISTINCT
        o.product_id
        ,o.convert_unit
        ,convert_rate
        ,client_id
      --  ,lower(i.unit) AS thuocsi_unit
    FROM gold_buymed_vn2.cos_product_convert_base_unit o
    LEFT JOIN (SELECT DISTINCT product_id
                               ,CASE WHEN unit = 'Tube' THEN  'Tuýp'
                                 ELSE unit END AS unit
              FROM gold_buymed_vn2.dim_product ) i
        ON o.product_id = i.product_id
       AND lower(o.convert_unit) = lower(i.unit)
    WHERE lower(i.unit) IS NOT NULL
)
,brand_type AS (
    SELECT p.product_id
          ,s.brand_type
    FROM ${ref('dim_product')} p
    LEFT JOIN ${ref('adhoc_pm_master_sku')} s USING (product_id)
    WHERE fc_code LIKE "BD"
    QUALIFY ROW_NUMBER() OVER(PARTITION BY p.product_id ORDER BY s.brand_type DESC) = 1
)
,sub_cat AS (
    SELECT p.product_id
          ,sc.name AS seller_sub_category_name
    FROM `${source.platinum}.marketplace_prd_product_v2_product` p
    LEFT JOIN `${source.platinum}.marketplace_prd_product_v2_seller_sub_category` sc ON p.seller_sub_category_code = sc.code
)
,brand_type_add AS (
    SELECT SAFE_CAST(code AS INT64) AS product_id
          ,NULLIF(value, "NAN") AS brand_type
    FROM collector.data_prd
    WHERE object = 'Product' AND type = 'BRAND_TYPE'
    QUALIFY ROW_NUMBER() OVER(PARTITION BY code, object, type ORDER BY submit_id DESC) = 1
)
,popular_product AS (
    SELECT SAFE_CAST(code AS INT64) AS product_id
          ,NULLIF(value, "NAN") AS popular
    FROM collector.data_prd
    WHERE object = 'Product' AND type = 'POPULAR'
    QUALIFY ROW_NUMBER() OVER(PARTITION BY code, object, type ORDER BY submit_id DESC) = 1  
)
,combo_on_kit AS (
    SELECT * FROM (
        SELECT CAST(code AS INT64) AS product_id
              ,1 AS client_id
              ,type
              ,value
        FROM collector.data_prd
        WHERE object = 'CIRCA' 
          AND (type = 'CIRCA_ON_KIT_PRODUCT' OR type = 'KIT_NAME')
    )
    PIVOT (
        MAX(value) FOR type IN ('KIT_NAME', 'CIRCA_ON_KIT_PRODUCT')
    )
), posm AS (

  SELECT DISTINCT
      product_id
FROM ${source.circa_os}.product_assortment_template o 
LEFT JOIN ${source.circa_os}.product_assortment_template_items i ON o.id = i.assortment_template_id
WHERE o.id = 'e9a5a24c-8b54-41a3-9b21-2ad63149eb3d'
      AND i.status = 'ACTIVE'

), tags AS (
SELECT DISTINCT
   product_id
  ,STRING_AGG(tag_name, ', ') AS tag_names
FROM ${source.ref}.dim_product_tags
GROUP BY product_id

)
SELECT DISTINCT TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) AS transformed_at
      ,pd.product_id
      ,pd.* EXCEPT (product_id)
      ,CASE WHEN ts.convert_unit IS NOT NULL THEN ts.convert_unit 
            ELSE cr.convert_unit END AS ts_unit
      ,CASE WHEN ts.convert_unit IS NOT NULL THEN ts.convert_rate
            WHEN pd.unit = 'combo' or pd.unit = 'Combo' THEN 1
            ELSE cr.convert_rate END AS ts_convert_rate
      ,CASE WHEN e.product_id IS NOT NULL THEN TRUE ELSE FALSE END AS is_allstore
      ,e.status AS status_allstore
      ,CASE WHEN tr.product_id IS NOT NULL THEN TRUE ELSE FALSE END AS is_trendy
      ,tr.status AS status_trendy
      ,CASE WHEN h.product_id IS NOT NULL THEN TRUE ELSE FALSE END AS is_hotdeal2025
      ,CASE WHEN hd.product_id IS NOT NULL THEN TRUE ELSE FALSE END AS is_hotdealjan
      ,CASE WHEN posm.product_id IS NOT NULL THEN TRUE ELSE FALSE END AS is_posm
      ,cr.convert_rate
      ,cr.convert_unit
      ,op.status AS medship_status
      ,op.unit_name AS medship_unit
      ,CASE WHEN i.on_hand_quantity > 0 THEN "Available" ELSE "Not Available" END AS stock_check
      ,pos_os_have_stock
      ,stock_available_in_POSs
      ,on_hand_quantity
      ,CASE WHEN op.product_id IS NOT NULL THEN "True" ELSE "False" END AS is_medship_product
      ,ig.ingredient_name
      ,ig.volume
      ,usage
      ,bu.base_unit
      ,COALESCE(bt.brand_type, ba.brand_type) AS brand_type
      ,seller_sub_category_name
      ,pop.popular AS is_popular
      ,CASE WHEN kit.product_id IS NOT NULL THEN TRUE ELSE FALSE END AS is_combo_on_kit
      ,kit.KIT_NAME AS kit_name
      ,po.status as web_status
      ,tag_names
FROM cte_product pd
LEFT JOIN ${source.platinum}.circa_online_prd_product_product AS op ON pd.product_id = op.product_id
LEFT JOIN inventory i ON pd.product_id = i.product_id AND pd.client_id = i.client_id
LEFT JOIN ingregients ig ON pd.product_id = ig.product_id AND pd.client_id = ig.client_id
LEFT JOIN product_base_unit bu ON pd.product_id = bu.product_id AND pd.client_id = bu.client_id
LEFT JOIN brand_type bt ON pd.product_id = bt.product_id
LEFT JOIN convert_unit cr ON pd.product_id = cr.product_id AND pd.client_id = cr.client_id
LEFT JOIN sub_cat ON pd.product_id = sub_cat.product_id
LEFT JOIN brand_type_add ba ON pd.product_id = ba.product_id
LEFT JOIN popular_product pop ON pd.product_id = pop.product_id
LEFT JOIN combo_on_kit kit ON kit.product_id = pd.product_id AND kit.client_id = pd.client_id
LEFT JOIN ${source.ref}.dim_product_online po ON po.product_id = pd.product_id 
LEFT JOIN ${source.ref}.cos_product_essential e ON pd.product_id = e.product_id --AND pd.client_id = e.client_id
LEFT JOIN ${source.ref}.cos_product_trendy tr ON pd.product_id = tr.product_id-- AND pd.client_id = tr.client_id
LEFT JOIN ${source.ref}.cos_product_hotdeal2025 h ON pd.product_id = h.product_id AND pd.client_id = h.client_id
LEFT JOIN ${source.ref}.cos_product_hot_deal_jan hd ON pd.product_id = hd.product_id AND pd.client_id = hd.client_id
LEFT JOIN posm ON pd.product_id = posm.product_id
LEFT JOIN ts_unit ts ON ts.product_id = pd.product_id and pd.client_id = ts.client_id
LEFT JOIN tags ON pd.product_id = tags.product_id
--WHERE pd.product_name NOT LIKE "%[Removed]%"

        --and pd.product_id = 1112
       --and pd.product_id = 16149
-- WHERE p.product_id>=1
-- left join efficacy e on p.efficacy_code= e.efficacy_id
