config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["10h30"],
    name: "cos_dim_product",
    columns: {/*
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"*/
        
    }
}


with cte_product as (
                     select distinct p.product_id
                            ,p.name as product_name
                            ,tp.retail_name
                            ,p.volumes
                            ,p.unit
                            ,p.length
                            ,p.height
                            ,p.weight
                            ,p.width
                            ,is_fragile
                            ,is_frozen
                            ,is_herb
                            ,is_ingredient_special
                            ,is_portable
                            ,tp.origin
                            ,manufacturer_short_name
                            ,tp.registration_number
                            ,tp.product_category_code
                            ,tp.product_category 
                            ,p.dosage_form
                            ,tp.product_report_category
                            ,mc.code as main_category_code
                            ,mc.name as product_categories
                            ,m.name as manufacture_name
                            ,is_combo
                            ,is_gift
                            ,is_etc
                            ,ARRAY_TO_STRING(JSON_VALUE_ARRAY(image_urls), ', ') AS image_urls
                            ,price_type
                            ,p.client_id
                     from ${source.circa_os}.product_product p
                              left join ${source.circa_os}.product_main_category mc on p.main_category_code = mc.code and p.client_id = mc.client_id
                              left join ${source.circa_os}.product_manufacturer m on p.manufacturer_code = m.code and p.client_id = m.client_id
                              left join ${source.circa_os}.product_seller_category sc on p.seller_category_code = sc.seller_category_code and p.client_id = sc.client_id
                              left join ${ref('dim_product')} as tp on p.product_id = tp.product_id
                              --where p.client_id = 1
                              )
,inventory as (
                   select distinct a.product_id
                              ,sum(a.on_hand_qty) as on_hand_quantity
                              ,STRING_AGG(distinct ep.name, ", ") as stock_available_in_POSs
                              ,a.client_id
                     from ${source.circa_os}.inventory_location_detail as a
                             left join ${source.circa_os}.inventory_location as b on a.location_id = b.id and a.client_id = b.client_id
                             left join  ${source.ref}.circa_pos_profile as ep on b.pos_id = ep.id and a.client_id = ep.client_id and b.client_id = ep.client_id
                             where a.deleted_at is null and lower(ep.name) <> "%test%"
                                   and ep.id is not null
                             group by all)
-- , ingregients as (
--     select
--         product_id,
--         ingredient_name,
--         JSON_VALUE(extra_props, '$.ingredients[0].ingredient_code') AS ingredient_code
--     from ${source.platinum}.pim_prd_product_product p 
--     left join ${source.platinum}.marketplace_prd_product_v2_ingredient i ON p.ingredient_code = i.ingredient_code
--     where ingredient_level = 1
-- ),

,ingregients as (
                   select distinct
                    product_id
                    ,ingredient_name
                    ,volume
                    ,usage
                    ,client_id
                   from  ${ref('cos_dim_product_ingredient')}
                   where ingredient_level = 1
                )
,product_base_unit as
      (
      select distinct a.product_id
            ,a.unit as base_unit
            ,client_id
      from ${source.circa_os}.product_retail_unit as a
      -- right join ${source.circa_os}.product_product as b on a.product_id = b.product_id
      where a.base_unit is true and (unit is not null or unit <> "")
      qualify row_number() over(partition by product_id,client_id order by created_at desc ) =1
      )
,convert_unit as (
      select a.product_id
            ,convert_rate
            ,unit as convert_unit
            ,client_id
      from ${source.circa_os}.product_retail_unit as a
      -- right join ${source.circa_os}.product_product as b on a.product_id = b.product_id
      where unit is not null or unit <> "" --and client_id = 1
      qualify row_number() over(partition by product_id ,client_id order by convert_rate desc ) =1
      )
      ,brand_type as
      (
        select p.product_id
               ,s.brand_type
        from ${ref('dim_product')} p
        left join ${ref('adhoc_pm_master_sku')} s using (product_id )
        where fc_code like "BD"
        qualify row_number() over(partition by p.product_id order by s.brand_type desc) = 1
        )
,sub_cat as (
            select p.product_id
            ,sc.name as seller_sub_category_name
        from `${source.platinum}.marketplace_prd_product_v2_product` p
        left join `${source.platinum}.marketplace_prd_product_v2_seller_sub_category` sc on p.seller_sub_category_code =sc.code
)
,brand_type_add AS (
    Select 
        SAFE_CAST(code as int64) as product_id
        , NULLIF(value, "NAN") as brand_type
    from collector.data_prd
    where object = 'Product' and type = 'BRAND_TYPE'
    qualify ROW_NUMBER() over(partition by code, object, type order by submit_id desc) = 1
),

popular_product as (
    Select 
        SAFE_CAST(code as int64) as product_id
        , NULLIF(value, "NAN") as popular
    from collector.data_prd
    where object = 'Product' and type = 'POPULAR'
    qualify ROW_NUMBER() over(partition by code, object, type order by submit_id desc) = 1  
)

select distinct timestamp_add(current_timestamp(), interval 7 hour) as transformed_at
               ,pd.product_id
               ,pd.* except (product_id)
          --   ,a.unit as retail_unit
               ,cr.convert_rate
               ,cr.convert_unit 
          --   ,a.sale_allowed as is_sale_allowed
               ,op.status as medship_status
               ,op.unit_name as medship_unit
               ,case when i.on_hand_quantity > 0 then "Available" else "Not Available" end as stock_check
               ,stock_available_in_POSs
               ,on_hand_quantity
               ,case when op.product_id is not null then "True" else "False" end as is_medship_product
               ,ig.ingredient_name
               ,ig.volume,usage
               ,bu.base_unit
               ,COALESCE(bt.brand_type, ba.brand_type) as brand_type
               ,seller_sub_category_name
               ,pop.popular as is_popular
from cte_product pd
-- left join ${source.circa_os}.product_retail_unit as a on a.product_id = pd.product_id and a.unit = pd.unit
left join ${source.platinum}.circa_online_prd_product_product as op on pd.product_id = op.product_id
left join inventory i on pd.product_id = i.product_id and pd.client_id = i.client_id
left join ingregients ig on pd.product_id = ig.product_id and pd.client_id = ig.client_id
left join product_base_unit bu on pd.product_id = bu.product_id and pd.client_id = bu.client_id
left join brand_type bt on pd.product_id = bt.product_id
left join convert_unit cr on pd.product_id = cr.product_id and pd.client_id = cr.client_id
left join sub_cat on pd.product_id = sub_cat.product_id
left join brand_type_add ba on pd.product_id = ba.product_id
left join popular_product pop on pd.product_id = pop.product_id
where product_name not like "%[Removed]%"
        --and pd.product_id = 1112
       --and pd.product_id = 16149
-- WHERE p.product_id>=1
-- left join efficacy e on p.efficacy_code= e.efficacy_id
