config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: `,
     tags: ["custom_1h_past10"],
    name: "cos_combo_on_kit"
}



Select distinct timestamp_add(current_timestamp(), interval 7 hour) as transformed_at
               ,datetime_add(o.created_at, interval 7 hour) as created_at
               ,datetime_add(o.updated_at, interval 7 hour) as updated_at
               ,o.id as combo_id
               ,o.order_id
               ,o.quantity
               ,o.product_id as combo_code
               ,o.combo_price
               ,o.seller_code
               ,concat(product_id, "_", 1) as product_client_id
from  ${source.circa_os}.order_order_apply_combo o 
where product_id in(
                 999900196
                ,999900178
                ,999900190
                ,999900192
                ,999900194
                ,999900193
                )
     and o.order_id in 
        (
        Select distinct order_id from ${source.ref}.cos_fact_order 
        where  status in ('COMPLETED', 'COMPLETED_SHIPPING' )
               and client_id = 1
        )