config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`,
    tags: ["10h30"],
    name: "cos_dim_category_for_report",
    columns: {/**/
        
    }
}

WITH cte_efficacy AS (
    SELECT DISTINCT product_id
                   ,category_code
                   ,client_id
    FROM buymed_circa_v2.product_product p
         ,UNNEST(JSON_VALUE_ARRAY(category_codes)) AS category_code
)

SELECT DISTINCT p.product_id
                ,p.category_code
                ,p.client_id
                ,CONCAT(p.product_id, "_", p.client_id) AS product_client_id
                ,CASE 
                    WHEN LOWER(TRIM(e.name)) LIKE "mắt, tai, mũi , họng" THEN "mắt, tai, mũi, họng"
                    ELSE LOWER(TRIM(e.name)) 
                 END AS category_name
FROM cte_efficacy p
LEFT JOIN buymed_circa_v2.product_category e ON p.category_code = e.code AND p.client_id = e.client_id
-- WHERE product_id = 2619
-- -- WHERE e.client_id = 1
-- --QUALIFY ROW_NUMBER() OVER(PARTITION BY product_id, category_code) = 1
