config {
    type: "table",
    description: `Danh mục hàng cửa hàng nào cũng có, giao nhanh 30 phút| PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`,
    tags: ["10h30"],
    name: "cos_product_essential",
    columns: {/*
        */
        
    }
}


SELECT DISTINCT
       o.id
      ,name
      ,product_id
      ,product_name
      ,i.status
      ,i.purchase_status
      ,DATETIME_ADD(i.created_at, INTERVAL 7 HOUR) AS created_at
      ,DATETIME_ADD(i.updated_at, INTERVAL 7 HOUR) AS updated_at
     -- ,1 AS client_id 
FROM ${source.circa_os}.product_assortment_template o 
LEFT JOIN ${source.circa_os}.product_assortment_template_items i ON o.id = i.assortment_template_id
WHERE o.id = '1430759b-40e3-4d86-86b8-8b9a1d5dae27'
     AND i.status <> 'INACTIVE'