
config {
    type: "table",
    description: `dim_customer PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    tags: ["custom_1h_past5"],
    name: "cos_dim_customer",
    columns: {
        
    }
}

WITH t AS (
SELECT DISTINCT
     customer_v2.name AS customer_name
    ,customer_v2.phone_number
    ,customer_v2.id
    ,status
    ,DATETIME_ADD(created_at, INTERVAL 7 HOUR) AS created_at
    ,DATE(DATETIME_ADD(created_at, INTERVAL 7 HOUR)) AS created_date
    ,DATETIME_ADD(updated_at, INTERVAL 7 HOUR) AS updated_at
    ,type
    ,title
    ,CONCAT(title, "", name) AS customer_title
    ,CASE WHEN title = 'Bà'
            OR title = 'Bác Gái'
            OR title = 'Chị'
            OR title = 'Cô' THEN 'Female'
          WHEN title = 'Anh'
               OR title = 'Bác Trai'
               OR title = 'Chú'
               OR title = 'Ông' THEN 'Male'
          WHEN title = 'Bạn' OR title IS NULL OR title = '' THEN 'Others' 
     END AS gender
     ,source
     , CASE WHEN source LIKE 'FC Circa%' OR source LIKE 'Nhà Thuốc%' OR source LIKE 'Nhà thuốc%' THEN 'FS'
            WHEN source NOT LIKE 'FC Circa%' AND (source LIKE 'CIRCA%' OR source LIKE 'Circa%' OR source = 'Mini Circa Vincom Đồng Khởi')  THEN 'OS'
       ELSE source END AS source_store_type
     ,ARRAY_REVERSE(REGEXP_EXTRACT_ALL(phone_number, r'[0-9]{9,11}'))[SAFE_OFFSET(0)] AS phone_number_cleaned
     ,phone_last_3_digits
     ,phone_last_4_digits
FROM buymed_circa_v2.entity_customer AS customer_v2
--WHERE source not in ('FS Test', 'Cửa hàng Tech Test 1', 'Cửa hàng Tech Test 2')
)
SELECT * EXCEPT(phone_number_cleaned)
       ,CASE
            WHEN phone_number_cleaned IS NULL THEN NULL
            WHEN STARTS_WITH(phone_number_cleaned, '84') THEN CONCAT('0', SUBSTR(phone_number_cleaned, 3))
            WHEN LENGTH(phone_number_cleaned) = 9 THEN CONCAT('0', phone_number_cleaned)
            WHEN LENGTH(phone_number_cleaned) = 10 AND STARTS_WITH(phone_number_cleaned, '0') THEN phone_number_cleaned
            ELSE phone_number_cleaned
        END AS customer_phone_cleaned
FROM t