
config {
    type: "table",
    description: `dim_sku_stock  item detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    tags: ["custom_1h_past5"],
    name: "dim_sku_stock",
    columns: {
        
    }
}

WITH inventory AS (
    SELECT a.product_id
           ,SUM(a.on_hand_qty) AS on_hand_quantity
           ,b.pos_id
           ,a.seller_code
           ,sku_code
           ,b.client_id
    FROM ${source.circa_os}.inventory_location_detail AS a
    LEFT JOIN ${source.circa_os}.inventory_location AS b ON a.location_id = b.id AND a.client_id = b.client_id
    WHERE deleted_at IS NULL
    GROUP BY ALL
)

SELECT
    s.pos_id
    ,s.product_id
    ,s.sku_code
    ,i.on_hand_quantity
    ,IF(i.on_hand_quantity > 0, "Available", "Unavailable") AS status
    ,CONCAT(s.product_id, "_", s.client_id) AS product_client_id
    ,s.client_id
FROM ${source.circa_os}.product_sku_in_pos s 
LEFT JOIN inventory i ON s.pos_id = i.pos_id AND s.sku_code = i.sku_code AND s.client_id = i.client_id
GROUP BY ALL
