config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["10h30"],
    name: "dim_lot_vat",
    columns: {/*
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"*/
        
    }
}


Select distinct
    product_id
   ,concat(product_id, "_", "1") as product_client_id
   ,client_id
   ,lot_date
   ,product_id || "_" || lot_date as product_lot_date
   ,product_id || "_" || lot_date || "_" || tax_rate || "_" || client_id as product_lot_date_vat_client_id
   ,type as vat_type
   ,tax_rate
   ,DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) AS expired_date
   ,DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) as gap
   ,CASE
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) < 0 THEN "Expired"
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) < 30 THEN "<30D"
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) >= 30 and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) < 90 THEN "<90D"
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) >= 90 and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) < 180 THEN "<180D"
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) >= 180 and DATE_DIFF( DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)), CURRENT_DATE( "+7"),day ) < 270 THEN "<270D"
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) >= 270 and DATE_DIFF( DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)), CURRENT_DATE( "+7"),day ) < 365 THEN "<365D"
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) > 365 THEN ">365D"
       END AS aging
     ,CASE
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) <= 0 THEN "1. Expired"
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), month ) <= 3  and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) > 0  THEN "2. < 3 months" 
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), month ) <= 6  and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), day ) > 3  THEN "3. < 6 months" 
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), month ) >  6 and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), month ) <= 12 THEN "4. > 6 months"
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), month ) >  12 and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), month ) <= 18 THEN "5. > 12 months"
       WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , CURRENT_DATE( "+7"), month ) >  18 THEN "6. > 18 months"
       ELSE "7. NED"
     END AS Aging_level
FROM ${source.circa_os}.product_lot
--where client_id = 1