config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`,
    tags: ["10h30"],
    name: "dim_lot_vat"

}

WITH t AS (
SELECT DISTINCT
            product_id
           ,CONCAT(product_id, "_", "1") AS product_client_id
           ,client_id
           ,lot_date
           ,product_id || "_" || lot_date AS product_lot_date
           ,product_id || "_" || lot_date || "_" || "_" || client_id AS product_lot_date_client_id
           ,type AS vat_type
           --,tax_rate
           ,DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) AS expired_date
           ,DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) AS gap
           ,CASE
               WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) <= 0 THEN "Expired"
               WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) < 30 AND DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) > 0 THEN "<30D"
               WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) >= 30 AND DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) < 90 THEN "<90D"
               WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) >= 90 AND DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) < 180 THEN "<180D"
               WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) >= 180 AND DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) < 270 THEN "<270D"
               WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) >= 270 AND DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) < 365 THEN "<365D"
               WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) >= 365 THEN ">= 365D"
             END AS aging
            --  ,CASE
            --    WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) <= 0 THEN "1. Expired"
            --    WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), MONTH) < 1 AND DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), DAY) > 0  THEN "2. < 1 months" 
            --    WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), MONTH) <= 3  AND DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), MONTH) >= 1  THEN "3. < 3 months" 
            --    WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), MONTH) <= 6  AND DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), MONTH) > 3  THEN "4. < 6 months" 
            --    WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), MONTH) > 6 AND DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), MONTH) <= 12 THEN "5. > 6 months"
            --    WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), MONTH) > 12 AND DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), MONTH) <= 18 THEN "6. > 12 months"
            --    WHEN DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, INTERVAL 7 HOUR)) , CURRENT_DATE("+7"), MONTH) > 18 THEN "6. > 18 months"
            --    ELSE "7. NED"
            --  END AS Aging_level
FROM ${source.circa_os}.product_lot
--WHERE client_id = 1
)
SELECT *
       ,CASE
            WHEN aging = "Expired" THEN "1. Expired"
            WHEN aging = "<30D" THEN "2. < 1 months" 
            WHEN aging = "<90D" THEN "3. < 3 months" 
            WHEN aging = "<180D" THEN "4. < 6 months" 
            WHEN aging = "<270D" THEN "5. < 9 months"
            WHEN aging = "<365D" THEN "6. < 12 months"
            WHEN aging = ">= 365D" THEN "7. >= 12 months"
            ELSE "8. NED"
        END AS Aging_level
FROM t
