config {
    type: "table",
    description: `Dim product | PIC: huyen.ngo; model_type: Table ;schedule: custom_1h_past15`,
    tags: ["bq_information_schema"],
    name: "dim_product_online",
    columns: {/*
*/
        
    }, bigquery: {
        partitionBy: "created_date"
    }
}


SELECT 
      TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) AS transformed_at
     ,product_id 
     , name AS product_name
     ,category_codes
     ,DATETIME_ADD(created_time, INTERVAL 7 HOUR) AS created_time
     ,DATE(DATETIME_ADD(created_time, INTERVAL 7 HOUR)) AS created_date
     ,efficacy_codes
     ,is_prescription
     ,DATETIME_ADD(last_updated_time, INTERVAL 7 HOUR) AS last_updated_time
     ,DATE(DATETIME_ADD(platinum_refresh, INTERVAL 7 HOUR)) AS platinum_refresh
     ,manufacturer_code
     ,origin
     ,seller_sub_category_code
     ,unit
     ,status
     ,updated_by_id
     ,updated_by_name
     ,ARRAY_TO_STRING(
      JSON_VALUE_ARRAY(extra_props, '$.sell_area_codes'),
    ' ,'
    ) AS sell_area
    ,JSON_VALUE(extra_props, '$.daily_limit_quantity') AS daily_limit_quantity
     ,JSON_VALUE(extra_props, '$.daily_limit_unit') AS daily_limit_unit
     ,JSON_VALUE(extra_props, '$.order_limit_quantity') AS order_limit_quantity
     ,JSON_VALUE(extra_props, '$.order_limit_unit') AS order_limit_unit
     ,DATETIME_ADD(synced_at, INTERVAL 7 HOUR) AS synced_at
FROM ${source.platinum}.circa_online_prd_product_product_filter
WHERE DATE(ingest_time )>= '2026-05-01'