config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`,
    tags: ["10h30"],
    name: "dim_combo_product"
}

WITH t AS (
    SELECT DISTINCT p.code
                   ,name
                   ,s.sub_product_id
                   ,quantity
                   ,s.unit
                   ,p.status
                   ,p.client_id
    FROM ${source.circa_os}.product_product p
    LEFT JOIN ${source.circa_os}.product_sub_product s ON SAFE_CAST(p.code AS INT) = s.product_id
)

SELECT DISTINCT           t.code AS combo_code
                         ,t.name AS combo_name
                         ,t.status
                         ,t.sub_product_id AS product_id
                         ,pr.name AS product_name
                         ,t.quantity
                         ,t.unit
                         ,t.client_id
                         ,CONCAT(pr.product_id, "_", pr.client_id) AS product_client_id
FROM t
LEFT JOIN ${source.circa_os}.product_product pr ON pr.product_id = t.sub_product_id AND t.client_id = pr.client_id
WHERE t.sub_product_id IS NOT NULL
      AND t.name NOT LIKE ('%[Tech test]%')
      AND LOWER(t.name) NOT LIKE ('%combo tech test%')
      AND t.name NOT LIKE ('%Combo Test%')
      AND t.name NOT LIKE ('%Combo TechTest 2%')
      --AND t.client_id = 1
