config {
    type: "table",
    description: `PIC: huyen.ngo; 
                  model_type: Table ;
                  schedule: At minute 15 every 1 hour.
                  dim_campaign_circa: all campaign of Circa`,
    tags: ["custom_1h_past15"],
    name: "dim_promotion_voucher_circa"
}


SELECT o.id
       ,o.code AS voucher_code
       ,o.name AS voucher_name
       ,DATETIME_ADD(start_date, INTERVAL 7 HOUR) AS start_date
       ,DATETIME_ADD(end_date, INTERVAL 7 HOUR) AS end_date
       ,CASE WHEN DATETIME_ADD(end_date, INTERVAL 7 HOUR) > TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) THEN FALSE 
             ELSE TRUE
              END                                                                   AS is_expired
       ,is_limit -- số lượng phát hành có giới hạn ko 
       ,limit_value -- số lượng giới hạn
       ,promotion_voucher_type
       ,discount_value
       ,percent
       ,voucher_generation_type
       ,DATE(DATETIME_ADD(o.created_at, INTERVAL 7 HOUR)) AS created_date
       ,DATETIME_ADD(o.created_at, INTERVAL 7 HOUR) AS created_at
       ,DATE(DATETIME_ADD(o.updated_at, INTERVAL 7 HOUR)) AS updated_date
       ,e.name AS created_by
       ,o.client_id
       ,limit_per_customer -- giới hạn đặt hàng hàng mỗi đơn
       ,apply_for_product_type 
       ,is_apply_for_all_pos
       ,first_time_order
       ,allow_include_delivery_discount
       ,promotion_campaign_id
       ,p.campaign_code
       ,p.campaign_name
FROM ${source.circa_os}.promotion_promotion_voucher o 
LEFT JOIN ${source.circa_os}.entity_entity e ON o.created_by = e.id
LEFT JOIN ${source.ref}.dim_campaign_circa p on o.promotion_campaign_id = p.id AND o.client_id = p.client_id
WHERE p.id IS NOT NULL
