config {
    type: "table",
    description: `PIC: huyen.ngo; model_type: Table ;schedule: At 10h30`
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["10h30"],
    name: "dim_lot_vat",
    columns: {/*
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"*/
        
    }
}

with t as (
Select distinct
            product_id
           ,concat(product_id, "_", "1") as product_client_id
           ,client_id
           ,lot_date
           ,product_id || "_" || lot_date as product_lot_date
           ,product_id || "_" || lot_date || "_" || tax_rate || "_" || client_id as product_lot_date_vat_client_id
           ,type as vat_type
           ,tax_rate
           ,DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) as expired_date
           ,DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) as gap
           ,case
               when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) <= 0 then "Expired"
               when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) < 30  and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) > 0 then "<30D"
               when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) >= 30 and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) < 90 then "<90D"
               when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) >= 90 and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) < 180 then "<180D"
               when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) >= 180 and DATE_DIFF( DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)), current_date( "+7"),day ) < 270 then "<270D"
               when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) >= 270 and DATE_DIFF( DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)), current_date( "+7"),day ) < 365 then "<365D"
               when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) > 365 then ">365D"
               end as aging
            --  ,case
            --    when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) <= 0 then "1. Expired"
            --    when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), month ) < 1 and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), day ) > 0  then "2. < 1 months" 
            --    when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), month ) <= 3  and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), month ) >= 1  then "3. < 3 months" 
            --    when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), month ) <= 6  and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), month ) > 3  then "4. < 6 months" 
            --    when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), month ) >  6 and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), month ) <= 12 then "5. > 6 months"
            --    when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), month ) >  12 and DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), month ) <= 18 then "6. > 12 months"
            --    when DATE_DIFF(DATE(TIMESTAMP_ADD(expired_date, interval 7 hour)) , current_date( "+7"), month ) >  18 then "6. > 18 months"
            --    else "7. NED"
            --  end as Aging_level
FROM ${source.circa_os}.product_lot
--where client_id = 1
)
Select *
       ,case
            when aging = "Expired" then "1. Expired"
            when aging = "<30D" then "2. < 1 months" 
            when aging = "<90D" then "3. < 3 months" 
            when aging = "<180D" then  "4. < 6 months" 
            when aging = "<270D"  then "5. < 9 months"
            when aging = "<365D" then "6. < 12 months"
            when aging = ">365D" then "7. < 12 months"
            else "8. NED" end as Aging_level
 from t 
