config {
    type: "table",
    description: `PIC: huyen.ngo; 
                  model_type: Table ;
                  schedule: At minute 15 every 1 hour.
                  dim_campaign_circa: all campaign of Circa`,
    tags: ["custom_1h_past15"],
    name: "dim_promotion_voucher_circa"
}

WITH order_voucher AS (
                    SELECT DISTINCT  o.voucher_code
                                    -- ,CASE WHEN limit_value = COUNT(DISTINCT o.order_code) THEN 'limit' ELSE 'not_limit' END AS check
                                    -- ,limit_value
                                    , COUNT(DISTINCT CASE 
    WHEN i.entity_id <> '00000000-0000-0000-0000-000000000000'
         AND c.phone_number IS NOT NULL
         AND c.phone_number <> ""
         AND REGEXP_REPLACE(c.phone_number, '0','') <> "" 
    THEN i.entity_id
END) AS no_customers_used
                                    ,COUNT(DISTINCT o.order_code ) AS cnt_order_used
                                    ,SUM(o.discount_amount) AS actual_discount_amount
                                    ,i.client_id
                    FROM ${source.circa_os}.order_order_voucher o
                    INNER JOIN (SELECT * FROM ${source.ref}.cos_fact_order WHERE status IN ('COMPLETED', 'COMPLETE_SHIPPING')) i ON o.order_code  = i.order_code 
                    LEFT JOIN buymed_circa_v2.entity_customer AS c ON i.entity_id = c.id       
                    GROUP BY o.voucher_code, i.client_id
)

SELECT o.id
       ,o.id AS voucher_id
       ,o.code AS voucher_code
       ,o.name AS voucher_name
       ,DATETIME_ADD(start_date, INTERVAL 7 HOUR) AS start_date
       ,DATETIME_ADD(end_date, INTERVAL 7 HOUR) AS end_date
       ,CASE WHEN o.end_date IS NULL THEN FALSE 
             WHEN DATETIME_ADD(end_date, INTERVAL 7 HOUR) > TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) THEN FALSE 
             ELSE TRUE
              END                                                                   AS is_expired
       ,is_limit -- số lượng phát hành có giới hạn ko 
       ,limit_value -- số lượng giới hạn
       ,cnt_order_used
       ,no_customers_used
       ,actual_discount_amount
       ,CASE WHEN limit_value = cnt_order_used THEN TRUE ELSE FALSE END AS is_voucher_use_up -- đã sử dụng hết hay chưa
       ,is_active
       ,promotion_voucher_type
       ,discount_value
       ,percent
       ,voucher_generation_type
       ,min_order_apply
       ,min_product_amount_apply
       ,DATE(DATETIME_ADD(o.created_at, INTERVAL 7 HOUR)) AS created_date
       ,DATETIME_ADD(o.created_at, INTERVAL 7 HOUR) AS created_at
       ,DATE(DATETIME_ADD(o.updated_at, INTERVAL 7 HOUR)) AS updated_date
       ,e.name AS created_by
       ,o.client_id
       ,limit_per_customer -- giới hạn đặt hàng hàng mỗi đơn
       ,apply_for_product_type 
       ,is_apply_for_all_pos
       ,first_time_order
       ,REGEXP_EXTRACT(
                 TRIM(
                   REGEXP_REPLACE(
                     REGEXP_REPLACE(
                       REGEXP_REPLACE(
                         REGEXP_REPLACE(
                           REGEXP_REPLACE(
                             conditions_of_use,
                             r'<[^>]*>', ' '                       -- remove HTML tags
                           ),
                           r'&nbsp;|&#160;', ' '                  -- replace nbsp
                         ),
                         r'(table|tr|td|col)\s*\{[^}]*\}', ' '    -- remove CSS text blocks
                       ),
                       r'ccp_infra.*', ' '                        -- remove metadata
                     ),
                     r'\s+', ' '                                  -- normalize spaces
                   )
                 ),
                 r'Áp dụng cho sản phẩm:.*'
  ) AS conditions_of_use
       ,CASE
             WHEN lower(conditions_of_use) like '%sản phẩm%' then 'PRODUCT'
             WHEN lower(conditions_of_use) like '%brand%' then 'PRODUCT'
             ELSE 'ORDER'
        END AS voucher_type
       ,allow_include_delivery_discount
       ,promotion_campaign_id
       ,p.campaign_code
       ,p.campaign_name
       ,concat(o.code, '_', o.client_id) as voucher_key
FROM ${source.circa_os}.promotion_promotion_voucher o 
LEFT JOIN ${source.circa_os}.entity_entity e ON o.created_by = e.id
LEFT JOIN ${source.ref}.dim_campaign_circa p on o.promotion_campaign_id = p.id AND o.client_id = p.client_id
LEFT JOIN order_voucher  v ON o.code = v.voucher_code AND o.client_id = v.client_id
WHERE p.id IS NOT NULL

