
config {
    type: "table",
    description: `dim_customer PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    tags: ["custom_1h_past5"],
    name: "dim_customer_v2",
    columns: {
        
    }
}

SELECT DISTINCT
     customer_v2.name AS customer_name
    ,customer_v2.phone_number
    ,customer_v2.id
    ,status
    ,DATETIME_ADD(created_at, INTERVAL 7 HOUR) AS created_at
    ,DATE(DATETIME_ADD(created_at, INTERVAL 7 HOUR)) AS created_date
    ,DATETIME_ADD(updated_at, INTERVAL 7 HOUR) AS updated_at
    ,type
    ,title
    ,CONCAT(title, "", name) AS customer_title
    ,CASE WHEN title = 'Bà'
            OR title = 'Bác Gái'
            OR title = 'Chị'
            OR title = 'Cô' THEN 'Female'
          WHEN title = 'Anh'
               OR title = 'Bác Trai'
               OR title = 'Chú'
               OR title = 'Ông' THEN 'Male'
          WHEN title = 'Bạn' OR title IS NULL OR title = '' THEN 'Others' 
     END AS gender
     ,source
     , CASE WHEN source LIKE 'FC Circa%' OR source LIKE 'Nhà Thuốc%' OR source LIKE 'Nhà thuốc%' THEN 'FS'
            WHEN source NOT LIKE 'FC Circa%' AND (source LIKE 'CIRCA%' OR source LIKE 'Circa%' OR source = 'Mini Circa Vincom Đồng Khởi')  THEN 'OS'
       ELSE source END AS source_store_type
     ,phone_last_3_digits
     ,phone_last_4_digits
FROM buymed_circa_v2.entity_customer AS customer_v2
WHERE source not in ('FS Test', 'Cửa hàng Tech Test 1', 'Cửa hàng Tech Test 2')
     

-- UNION ALL 

-- SELECT DISTINCT
--      entity1.name AS customer_name
--     ,entity1.phone_number
--     ,entity1.id
--     ,status
--     ,DATE(DATETIME_ADD(created_at, INTERVAL 7 HOUR)) AS created_date
--     ,type
--     ,title
--     ,CONCAT(title, "", name) AS customer_title
--     ,CASE WHEN title = 'Bà'
--             OR title = 'Bác Gái'
--             OR title = 'Chị'
--             OR title = 'Cô' THEN 'Female'
--           WHEN title = 'Anh'
--                OR title = 'Bác Trai'
--                OR title = 'Chú'
--                OR title = 'Ông' THEN 'Male'
--           WHEN title = 'Bạn' OR title IS NULL OR title = '' THEN 'Others' 
--      END AS gender
-- FROM buymed_circa_v2.entity_entity AS entity1
-- WHERE entity1.id <> '00000000-0000-0000-0000-000000000000'
--   AND entity1.id IN (
--       SELECT DISTINCT entity_id 
--       FROM buymed_circa.order_order
--       WHERE pos_id IN (
--           "b6c40920-af79-4fb0-bdc4-9965ddb885d2"
--          ,"e737c882-e90c-4fd2-8a4f-ac6afd248a33"
--       )
--   )
