
config {
    type: "table",
    description: `dim_sku_stock  item detail PIC: huyen.ngo; model_type: Table ;schedule: Refresh manual`,
    //tags: ["10h30"],
    name: "os_map_idthuocsi",
    columns: {
        
    }
}

SELECT map.*
       ,p.id AS pos_id
       ,client_id
FROM buymed_external.OS_map_IDthuocsi map 
LEFT JOIN ${source.ref}.circa_pos_profile p ON map.pos_code = p.code
