
config {
    type: "table",
    description: `dim_sku_stock  item detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_1h_past5"],
    name: "os_map_idthuocsi",
    columns: {
        
    }
}

Select map,*, p.id as pos_id, client_id from buymed_external.OS_map_IDthuocsi map 
left join ${source.ref}.circa_pos_profile p on map.pos_code = p.code
