
config {
    type: "table",
    description: `dim_sku_stock  item detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every hour`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_1h_past5"],
    name: "sku_nso",
    columns: {
        
    }
}

Select *
        ,concat(product_id, "_",1) as product_client_id
        ,1 as client_id
 from buymed_external.sku_nso
