config {
    type: "view",
    name: "platform_accounting_prd_debt_debt",
    schema: "platinum_buymed_vn_restricted",
    columns: {
        debt_template_code: "công thức công nợ",
        creditor_entity_name: "công ty",
        debtor_entity_name: "Khách hàng",
        debt_limit: "hạn mức",
        total_balance: "Dư nợ thực tế",
        total_balance_temporary: "Dư nợ tạm tính",
        total_debt: "công nợ thực tế",
        total_debt_temporary: "công nợ tạm tính"
    },
    tags: ['platform_accounting_prd_debt']
}

  WITH silver AS (
    SELECT
      key,mg_id,debt_code,template_version,apply_from_time,apply_to_time,branch_code,created_time,creditor_entity_code,creditor_entity_email,creditor_entity_name,creditor_entity_type,currency_code,debt_limit,debt_template_code,debtor_entity_code,debtor_entity_email,debtor_entity_name,debtor_entity_phone,debtor_entity_type,document_data_code,document_data_name,document_template_code,hashtag,is_credit_over_limit,is_valid_date,last_updated_time,org_id,scope,total_balance,total_balance_temporary,total_debt,total_debt_temporary,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn_restricted.platform_accounting_prd_debt_debt
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,debt_code,template_version,apply_from_time,apply_to_time,branch_code,created_time,creditor_entity_code,creditor_entity_email,creditor_entity_name,creditor_entity_type,currency_code,debt_limit,debt_template_code,debtor_entity_code,debtor_entity_email,debtor_entity_name,debtor_entity_phone,debtor_entity_type,document_data_code,document_data_name,document_template_code,hashtag,is_credit_over_limit,is_valid_date,last_updated_time,org_id,scope,total_balance,total_balance_temporary,total_debt,total_debt_temporary,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn_restricted__stg`, `platform_accounting_prd_debt_debt`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  