config {
    type: "table",
    description: `PIC: Ha.Lekim`,
    tags: ["custom_1h_past20"]
}
with 
gmv as 
(select  dp.code as pos_code, dp.name as pos_name,
a.created_date,
 sum(quantity_po*unit_price_before_discount) as gmv
from gold_buymed_vn2.fact_fin_circa_order a
left join  gold_buymed_vn2.fact_fin_circa_order_item b on a.order_id = b.order_id
inner join buymed_circa_v2.entity_pos_profile dp 
on a.pos_id = dp.id
where b.gift_code is null
and a.status not in ('CANCELED','FAILED_SHIPMENT','OUT_OF_STOCK','RETURNED')
and a.type = 'OFFLINE'
and dp.type = 'CIRCA'
and not regexp_contains(lower(dp.name), 'tech|test|text|111')
and a.created_date >= "2026-01-01"
group by all)
, target_ as (
  select month, week, date,
  pos_code,
  pos_name,
  final_target,
  from ${ref("dim_circa_os_gmv_kpi")} 
  where channel = 'OFFLINE'
  )
select t.month, 
t.week,
t.date,
t.pos_code, 
t.pos_name,
gmv, 
final_target, 
 from target_ t 
left join gmv g
on t.pos_code = g.pos_code
and t.date = g.created_date