config {
    type: "incremental",
    description: `PIC: Ha.Lekim
    type: incremental
    refresh for order_item created within 30 days`,
    bigquery: {
        partitionBy: "created_date"
    },
    tags: ["gold_custom_20m"]
}
js {
    const start_date =
      //   `date(2025, 01, 01)`
        ` DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY) `
    const end_date = ` CURRENT_DATE() `
}
pre_operations {
  DELETE
  FROM
    ${self()}
  WHERE
    created_date >= ${start_date}
}

WITH
  base_data AS (
  SELECT
    o.updated_date,
    oi.created_date,
    o.completed_date,
    o.order_code,
    o.pos_id,
    oi.order_id,
    oi.id AS item_id,
    oi.location_id,
    oi.qr_code,
    oi.sku_code,
    oi.product_id,
    oi.unit_id,
    oi.type,
    o.type AS order_type,
    oi.order_apply_combo_id,
    cb.combo_price,
    cb.discount_amount AS combo_discount_amount,
    cb.quantity AS combo_quantity,
    ru.unit,
    oi.gift_code,
    ru.convert_rate,
    -- oi.quantity AS quantity_order,
    -- oi.quantity*ru.convert_rate AS base_quantity_order,
    COALESCE(oi.quantity * poi.base_quantity_distribution, oi.quantity) AS quantity_po,
    COALESCE(oi.quantity*ru.convert_rate * poi.base_quantity_distribution, oi.quantity*ru.convert_rate) AS base_quantity_po,
    oi.unit_price,
    coalesce(case when system_price = 0 then null else system_price end, 
    case when platform_price = 0 then null else platform_price end,
    case when unit_price = 0 then null else unit_price end) as system_price,
    CASE WHEN o.channel <> 'O2O' THEN oi.promotion_event_code
              ELSE ol.promotion_event_code END AS item_discount_code,
     CASE WHEN o.channel <> 'O2O' THEN oi.discount_amount
              ELSE ol.discount_amount END AS item_discount_amount,
    CASE WHEN tag_list like '%deal_1000%' AND oi.unit_price = 1000  THEN TRUE ELSE FALSE END AS is_deal_1k,
    oi.updated_at,
    poi.base_quantity AS base_qty_allocation,
    poi.location_detail_id,
    poi.location_type,
    poi.lot_id,
    poi.fulfillment_method,
    poi.doc_code,
    poi.owner_name,
    poi.cost_price_include_tax,
    poi.cost_price_without_tax,
    poi.so_thuoc_si,
  FROM buymed_circa_v2.order_order_item oi
  LEFT JOIN buymed_circa_v2.order_order_apply_combo cb
  ON oi.order_apply_combo_id = cb.id
  LEFT JOIN buymed_circa_v2.product_retail_unit ru
  ON oi.unit_id = ru.id
  INNER JOIN ${ref("fact_fin_circa_order")} o 
  ON oi.order_id = o.order_id
  LEFT JOIN  ${ref("fact_fin_circa_online_order_item")} ol 
  ON o.ref_order_in_platform = ol.order_code AND oi.product_id = ol.product_id AND oi.unit = ol.unit
  LEFT JOIN (
  select * 
  from ${ref("fact_fin_circa_inventory_allocation")} 
  where updated_date >= ${start_date}
  and type = 'SALE_ORDERED') poi
  ON oi.id = poi.item_ref_id
  where oi.created_date >= ${start_date}
  )
  , clean_data as (
    select * except (order_apply_combo_id, item_discount_code, gift_code),
    CASE WHEN order_apply_combo_id = '' THEN NULL ELSE order_apply_combo_id END AS order_apply_combo_id,
    CASE WHEN item_discount_code = '' THEN NULL ELSE item_discount_code END AS item_discount_code,
    CASE WHEN gift_code = '' THEN NULL ELSE gift_code END AS gift_code,
    from base_data
  ),
  clean_system_price_data AS (
  SELECT
    * EXCEPT ( system_price),
    CASE
      WHEN is_deal_1k IS TRUE OR gift_code IS NOT NULL THEN system_price
      WHEN item_discount_code IS NOT NULL AND order_apply_combo_id IS NULL THEN unit_price + item_discount_amount
      WHEN order_apply_combo_id IS NOT NULL THEN combo_price*combo_quantity*SAFE_DIVIDE(safe_divide(quantity_po*system_price,
        SUM(quantity_po*system_price) OVER (PARTITION BY order_id, order_apply_combo_id)), quantity_po)
      ELSE unit_price
      END
    AS unit_price_before_discount,
    CASE
      WHEN order_apply_combo_id IS NOT NULL THEN (combo_price - combo_discount_amount)*combo_quantity*SAFE_DIVIDE(safe_divide(quantity_po*system_price,
        SUM(quantity_po*system_price) OVER (PARTITION BY order_id, order_apply_combo_id)), quantity_po)
      ELSE unit_price
  END
    AS unit_price_after_discount
  FROM
    clean_data )
SELECT
  * 
  EXCEPT (
    order_apply_combo_id,
    combo_price,
    combo_quantity,
    combo_discount_amount,
    item_discount_amount
    ),
    CASE WHEN order_apply_combo_id IS NOT NULL THEN true else false end as is_combo,
  CASE
    WHEN item_discount_code IS NOT NULL AND order_apply_combo_id IS NULL AND gift_code IS NULL THEN unit_price_before_discount - unit_price_after_discount
    ELSE 0
END
  AS item_discount_amount,
  CASE
    WHEN order_apply_combo_id IS NOT NULL AND gift_code IS NULL THEN unit_price_before_discount - unit_price_after_discount ELSE 0 END AS combo_discount_amount,
  SAFE_DIVIDE( quantity_po * unit_price_after_discount, SUM(quantity_po * unit_price_after_discount) OVER (PARTITION BY order_id)) AS item_amount_contribution,
FROM
  clean_system_price_data