config {
    type: "table",
    description: `PIC: Ha.Lekim`,
    tags: ["custom_1h_past20"]
}
with 
-- change after verify BI 
gmv as 
(select  dp.code as pos_code, dp.name as pos_name,
 sum(quantity_po*unit_price_before_discount) as gmv
from gold_buymed_vn2.fact_fin_circa_order a
left join  gold_buymed_vn2.fact_fin_circa_order_item b on a.order_id = b.order_id
inner join buymed_circa_v2.entity_pos_profile dp 
on a.pos_id = dp.id
where b.gift_code is null
and a.status not in ('CANCELED','FAILED_SHIPMENT','OUT_OF_STOCK','RETURNED')
and a.type = 'OFFLINE'
and dp.type = 'CIRCA'
and not regexp_contains(lower(dp.name), 'tech|test|text|111')
-- and date_trunc(a.created_date,week(monday))  = date_trunc(current_date(),week(monday))
and a.created_date between '2026-06-22' and '2026-06-30'
group by all)
, target_ as (
  select pos_code,
  sum(target) as target,
  sum(custom_week_target) as new_target 
  from gold_buymed_vn2.dim_fin_circa_cos_gmv_target_2026_src 
  where channel = 'OFFLINE'
  -- and  sow  = date_trunc(current_date(),week(monday))
  and sow = '2026-06-22' -- custom final week with 9 days
  group by all
  )

select date_trunc(current_date(),week(monday)) as monday_of_week, 
g.pos_code, g.pos_name,
gmv, t.target, round(t.new_target,-6) as weekly_target, safe_divide(gmv, t.target) as kpi_pct
 from gmv g
left join target_ t
on g.pos_code = t.pos_code
group by all