config {
    type: "table",
    description: `PIC: Ha.Lekim
    segmention CIRCA POS at every 1st month`,
    tags: ["monthly_1st_2h10"]

}

WITH raw_data as (
  select 
  date_trunc(a.completed_date, month) as completed_month,
  pos_code,
  pos_name, 
  order_code, 
  status, 
  gmv, 
  channel,
  coalesce(voucher_circa,0) as voucher_circa,
  deal,       
  cogs_circa
  from ${ref("gold_buymed_vn2","circa_fact_net_margin")} a
  where client_id = 1
  and channel = 'OFFLINE'
)
  , order_change AS (
    SELECT
      pos_code,
      completed_month,
      sum(gmv) gmv,
      lag(sum(gmv)) OVER (PARTITION BY pos_code ORDER BY completed_month) AS prev_gmv,
      lag(sum(gmv), 2)
        OVER (PARTITION BY pos_code ORDER BY completed_month) AS prev_prev_gmv,
      safe_divide(
        sum(gmv)
          - lag(sum(gmv)) OVER (PARTITION BY pos_code ORDER BY completed_month),
        lag(sum(gmv)) OVER (PARTITION BY pos_code ORDER BY completed_month))
        AS gmv_change,
      safe_divide(
        lag(sum(gmv))
          OVER (PARTITION BY pos_code ORDER BY completed_month)
          - lag(sum(gmv), 2) OVER (PARTITION BY pos_code ORDER BY completed_month),
        lag(sum(gmv), 2) OVER (PARTITION BY pos_code ORDER BY completed_month))
        AS prev_gmv_change,
      sum(voucher_circa) as voucher_circa,
      safe_divide(sum(voucher_circa), sum(gmv)) AS `voucher_circa_pct`,
      sum(cogs_circa) AS cogs,
      sum(gmv - cogs_circa) AS gp,
      sum(gmv - cogs_circa - voucher_circa) AS net_profit,
      safe_divide(sum(gmv - cogs_circa), sum(gmv)) AS margin,
      safe_divide(sum(gmv  - cogs_circa - voucher_circa), sum(gmv)) AS net_margin,
    FROM raw_data
    GROUP BY ALL
  )
-- classification query
SELECT
  *,
  CASE
    WHEN increase_gmv = 1 AND good_margin = 1 AND high_promotion = 0
      THEN "1. Healthy"
    WHEN increase_gmv = 1 AND good_margin = 1 AND high_promotion = 1
      THEN "4. Promotion-driven"
    WHEN increase_gmv = 1 AND good_margin = 0
      THEN "3. High GMV - Low Profit"
    WHEN increase_gmv = 1 AND high_promotion = 1 THEN "4. Promotion-driven"
    WHEN increase_gmv = 0 AND good_margin = 1 THEN "2. Unstable Growing"
    ELSE "5. Underperforming"
    END AS pos_type,
FROM
  (
    SELECT
      *,
      CASE
        WHEN gmv_change > 0 AND prev_gmv_change > 0 THEN 1
        ELSE 0
        END AS increase_gmv,
      CASE WHEN net_margin >= 0.08 THEN 1 ELSE 0 END AS good_margin,
      CASE WHEN voucher_circa_pct >= 0.1 THEN 1 ELSE 0 END AS high_promotion,
    FROM order_change
    WHERE
      completed_month = date_sub(
        date_trunc(date_add(current_date(), interval 1 day), month), INTERVAL 1 month)
  )