config {
  type: "table",
  description: 
        `
        List of SKUs corresponding to each voucher in each order;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.platinum}.marketplace_prd_order_v2_order_item,
            ${source.ref}.fact_order
        `,

  tags: ["custom_1h_past5", "PROMOTION_MKP"]
}

SELECT
    oi.order_id
    , oi.product_original_id AS product_id
    , SUM(COALESCE(oi.combo_quantity, oi.demand_quantity)) AS qty_ordered
    , SUM(COALESCE(oi.combo_outbound_quantity, oi.outbound_quantity)) AS qty_outbound
    , SUM(oi.sales_price * oi.demand_quantity) /  SUM(COALESCE(oi.combo_quantity, oi.demand_quantity)) AS price_unit
    , ov.redeem_code AS voucher_code
    , CONCAT(oi.order_id, '_', ov.redeem_code) AS order_voucher_code
    , vp.campaign_brand
    , oi.item_type
    , oi.customer_id
    , oi.sku_orignal_code AS sku_code
FROM ${ref('fact_order_item')} AS oi
    LEFT JOIN ${ref('fact_order_voucher')} AS ov 
        ON oi.order_id = ov.order_id
    LEFT JOIN 
        (SELECT DISTINCT voucher_code, product_id, campaign_brand, seller_code
        FROM ${ref('dim_voucher_product')}
        ) AS vp 
        ON vp.voucher_code = ov.redeem_code 
            AND vp.product_id = oi.product_original_id 
            AND vp.seller_code = oi.seller_code
WHERE
    vp.voucher_code IS NOT NULL
    AND vp.product_id IS NOT NULL 
    AND oi.created_at >= '2024-05-01'
    -- AND oi.item_type <> 'IN_COMBO'
    -- AND vp.campaign_brand IS NOT NULL
GROUP BY ALL