config {
    type: "table", 
    description: 
        `
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        `,
    tags: ["custom_1h_past5","PROMOTION_MKP"]
}

SELECT
    o.customer_id
    , g.gamification_code
    , g.min_total_value
    , o.order_id
    , o.created_at as order_created_at
    , sku_orignal_key
    , SUM(COALESCE(combo_quantity, demand_quantity)) AS demand_quantity
    , COALESCE(combo_price, sales_price) AS sales_price
    , SUM(COALESCE(oi.combo_outbound_quantity, oi.outbound_quantity)) AS outbound_quantity
    , IF(
            o.order_status_seq >= g.order_status_seq
            , IF(g.kind_of_value = 'ACTUAL', "OUTBOUND", "ORDERED")
            , null
      ) AS calculation_type
    , gc.segment
FROM ${ref('fact_order_item')} AS oi
    LEFT JOIN ${ref('fact_order')} AS o ON oi.order_id = o.order_id
    JOIN ${ref('dim_gamification_sku')} AS gs ON oi.sku_orignal_key = gs.sku_key
    LEFT JOIN ${ref('dim_gamification')} AS g ON gs.gamification_code = g.gamification_code
    LEFT JOIN ${ref('dim_gamification_customer')} AS gc ON gc.customer_id = oi.customer_id AND gc.gamification_code = g.gamification_code
WHERE
    oi.created_at >= '2025-03-01' AND
    o.created_at >= '2025-03-01' AND
    oi.created_at >= g.start_time
    AND oi.created_at <= g.end_time
    AND o.order_status <> 'CANCEL'
    AND gc.customer_id IS NOT NULL
    AND gc.customer_province_code IN (SELECT a.province_code FROM ${ref('dim_gamification_location')} AS a WHERE a.gamification_code = g.gamification_code)
GROUP BY ALL