config {
  type: "table",
  description: 
        `
        List of SKUs corresponding to each voucher in each order;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: daily at 8h30, 10h30, 12h30, 15h30, 18h, 20h30;
        Source: 
            ${source.platinum}.marketplace_prd_order_v2_order_item,
            ${source.ref}.fact_order
        `,

  tags: ["8h30", "10h30", "12h30", "15h30" ,"18h00", "20h30", "PROMOTION_MKP"]
}

SELECT
    oi.order_id
    , oi.product_original_id AS product_id
    , COALESCE(oi.combo_quantity, oi.demand_quantity) AS qty_ordered
    , oi.sales_price AS price_unit
    , ov.redeem_code AS voucher_code
    , CONCAT(oi.order_id, '_', ov.redeem_code) AS order_voucher_code
    , vp.campaign_brand
    , oi.item_type
FROM ${ref('fact_order_item')} AS oi
    LEFT JOIN ${ref('fact_order_voucher')} AS ov 
        ON oi.order_id = ov.order_id
    LEFT JOIN ${ref('dim_voucher_product')} AS vp 
        ON vp.voucher_code = ov.redeem_code AND vp.product_id = oi.product_original_id 
WHERE
    vp.voucher_code IS NOT NULL
    AND vp.product_id IS NOT NULL 
    AND oi.created_at >= '2024-05-01'
    -- AND oi.item_type <> 'IN_COMBO'
    AND vp.campaign_brand IS NOT NULL