config {
    type: "table", 
    description: 
        `
        The redeem codes used in each order;
        PIC: nguyen.tran; 
        Type: Table; 
        Refresh Schedule: hourly;
        Source: 
            ${source.silver}.marketplace_prd_order_v2_order
        `,
    tags: ["custom_1h_past5", "PROMOTION_MKP"]
}

WITH 
    promotion_order as (
        SELECT
            a.order_id
            , TIMESTAMP(a.created_at) AS created_at
            , DATE(a.created_at) AS created_date
            , a.ordered_amount AS gmv
            , a.customer_id
            , JSON_VALUE(r, '$.code') AS redeem_code
            , SAFE_CAST(JSON_VALUE(r, '$.discount_value') AS FLOAT64) AS discount_value
            , CONCAT(a.order_id, "_", JSON_VALUE(r, '$.code')) AS order_voucher_code
        FROM ${ref('fact_order')} AS a
            , UNNEST(JSON_QUERY_ARRAY(a.redeem_apply_result)) AS r
            
    )

SELECT 
  *
  , discount_value / SUM(discount_value) OVER (PARTITION BY order_id) AS percent
  , COALESCE(gmv * (discount_value / SUM(discount_value) OVER (PARTITION BY order_id)),0) AS gmv_voucher
FROM promotion_order