config {
  type: "view",
  description : "Calculate Throughput and latency"
}
WITH top_silver_layer AS (
  -- The most event table
  SELECT 
    "warehouse_prd_picking_pick_ticket_item" name,mg_id, last_updated_time, synced_at, ingest_time
  FROM silver_buymed_vn.warehouse_prd_picking_pick_ticket_item 
  WHERE ingest_time >= CURRENT_TIMESTAMP - INTERVAL 14 DAY

  UNION ALL 
  SELECT 
    "marketplace_prd_order_v2_order_item",mg_id ,last_updated_time, synced_at, ingest_time
  FROM silver_buymed_vn.marketplace_prd_order_v2_order_item
  WHERE ingest_time >= CURRENT_TIMESTAMP - INTERVAL 14 DAY

  UNION ALL 
  SELECT "marketplace_prd_order_v2_order_item",mg_id ,last_updated_time, synced_at, ingest_time
  FROM silver_buymed_vn.marketplace_prd_order_v2_order_item
  WHERE ingest_time >= CURRENT_TIMESTAMP - INTERVAL 14 DAY

  UNION ALL 
  SELECT "warehouse_prd_core_sale_order_item",mg_id ,last_updated_time, synced_at, ingest_time
  FROM silver_buymed_vn.warehouse_prd_core_sale_order_item
  WHERE ingest_time >= CURRENT_TIMESTAMP - INTERVAL 14 DAY

  UNION ALL 
  SELECT "monitoring_prd_collector_user_stats",mg_id ,CURRENT_TIMESTAMP(), synced_at, ingest_time
  FROM silver_buymed_vn.monitoring_prd_collector_user_stats
  WHERE ingest_time >= CURRENT_TIMESTAMP - INTERVAL 14 DAY

  UNION ALL 
  SELECT "warehouse_prd_inventory_transfer_sku",mg_id ,last_updated_time, synced_at, ingest_time
  FROM silver_buymed_vn.warehouse_prd_inventory_transfer_sku
  WHERE ingest_time >= CURRENT_TIMESTAMP - INTERVAL 14 DAY

  UNION ALL 
  SELECT "warehouse_prd_inventory_sku",mg_id ,last_updated_time, synced_at, ingest_time
  FROM silver_buymed_vn.warehouse_prd_inventory_sku
  WHERE ingest_time >= CURRENT_TIMESTAMP - INTERVAL 14 DAY

  UNION ALL 
  SELECT "warehouse_prd_picking_task_item",mg_id ,last_updated_time, synced_at, ingest_time
  FROM silver_buymed_vn.warehouse_prd_picking_task_item
  WHERE ingest_time >= CURRENT_TIMESTAMP - INTERVAL 14 DAY

)

  SELECT 
    "_All" table_name,
    mg_id ,
    COALESCE(last_updated_time, silver_buymed_vn.MONGOID_TIMESTAMP(mg_id) ) last_updated_time, 
    synced_at, ingest_time 
  FROM top_silver_layer
  UNION ALL 
  SELECT 
    table_name,
    mg_id ,
    COALESCE(last_updated_time, silver_buymed_vn.MONGOID_TIMESTAMP(mg_id) ) last_updated_time, 
    synced_at, ingest_time 
  FROM top_silver_layer
