config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "monitoring_prd_realtime_user_failed_login_v8",
    description : `PIC: MinhLuu, Internal: https://internal.thuocsi.vn/crm/customer/realtime?status=FAILED
    To be like on the Tnternal page:
        SELECT 
            m.customer_id,
            m.customer_name, 
            m.phone,
            m.address,
            m.created_time,
            m.result_error,
            m.ua_metadata
            -- Except note content, I has not find which way to map
        FROM ${source.platinum}.monitoring_prd_realtime_user_failed_login_v8 m
    `,
    tags:["platinum","monitoring_prd_realtime-user"]
}
  WITH silver AS (
    SELECT
      key, mg_id, ip, result_error, status, last_login, error_code_list, source, ua_metadata, user_metadata, user_agent, account_type, account_id, metadata, result_status, first_login, total, customer_id, created_time, last_updated_time, synced_at, extra_props, action, ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.monitoring_prd_realtime_user_failed_login_v8
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key, mg_id, ip, result_error, status, last_login, error_code_list, source, ua_metadata, user_metadata, user_agent, account_type, account_id, metadata, result_status, first_login, total, customer_id, created_time, last_updated_time, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `monitoring_prd_realtime_user_failed_login_v8`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"