config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "monitoring_prd_realtime_user_user_range",
    description : `
    PIC: minh.luu
    Partition by: created date
    cluster by: day_str, hour_from_str, user_id
    `,
    tags:["platinum","monitoring_prd_realtime-user"]
}

  WITH silver AS (
    SELECT
      key,mg_id,day_str,hour_from_str,user_id,created_time,hour_to_str,in_service_id,ip,last_updated_time,session_token,user_agent,user_type,username,ws_host,ws_host_version,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.monitoring_prd_realtime_user_user_range
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,day_str,hour_from_str,user_id,created_time,hour_to_str,in_service_id,ip,last_updated_time,session_token,user_agent,user_type,username,ws_host,ws_host_version,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `monitoring_prd_realtime_user_user_range`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
