config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "monitoring_prd_collector_user_stats",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","monitoring_prd_collector"]
}
  WITH silver AS (
    SELECT
      key,mg_id,account_id,account_type,event,result_status,result_error_code,user_agent,source,ip,customer_id,seller_id,created_time,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.monitoring_prd_collector_user_stats
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND FIRST_VALUE(action) OVER(_window) != "d"
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          )
  ), platinum AS (
    SELECT 
      key,mg_id,account_id,account_type,event,result_status,result_error_code,user_agent,source,ip,customer_id,seller_id,created_time,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `monitoring_prd_collector_user_stats`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s