config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "monitoring_prd_realtime_cs_customer_rank",
    description : `
    PIC: minh.luu
    Partition by: created date
    `,
    tags:["platinum","monitoring_prd_realtime_cs"]
}

  WITH silver AS (
    SELECT
      key,mg_id,customer_id,cycle_screenshot_str,hash_tag,customer_phone,total_order_quantity,created_time,customer_code,customer_name,province_code,district_code,avg_order_quantity,accumulate_from_str,ward_code,cycle_full_str,loyalty_point,total_gmv,avg_total_gmv,accumulate_to_str,final_rank,gmv_rank,last_updated_time,loyalty_rank,order_quantity_rank,avg_province_rank_gmv,avg_province_rank_order,avg_gmv_rank,avg_order_quantity_rank,history_gmv,history_order,synced_at,extra_props,action,ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.monitoring_prd_realtime_cs_customer_rank
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key,mg_id,customer_id,cycle_screenshot_str,hash_tag,customer_phone,total_order_quantity,created_time,customer_code,customer_name,province_code,district_code,avg_order_quantity,accumulate_from_str,ward_code,cycle_full_str,loyalty_point,total_gmv,avg_total_gmv,accumulate_to_str,final_rank,gmv_rank,last_updated_time,loyalty_rank,order_quantity_rank,avg_province_rank_gmv,avg_province_rank_order,avg_gmv_rank,avg_order_quantity_rank,history_gmv,history_order,synced_at,extra_props,action,ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `monitoring_prd_realtime_cs_customer_rank`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"
  