config {
    type: "table",
    description: `PIC: minh.luu, schedule: 0h00 daily
    The accounting system retrieves some details from the marketplace system
    Source
        ${source.platinum}.marketplace_prd_order_v2_order
        ${source.platinum}.marketplace_prd_order_v2_order_item`,
    columns: {
        order_id: "NonNull",
        product_id: "Nullable",
        created_time: "NonNull | Timezone in +7",
        outbound_time: "Nullable | Timezone in +7 | out of fulfillment center time, or picked-up by carrier time",
        outbound_quantity: "Nullable | the quantity of products have be shipped from warehouse",
        price: "Nullable",
        outbound_amount: "Nullable | outbound_quatity * price for each product"
    },
    assertions: {
        // uniqueKey: 'order_id || "__" || product_id',
        nonNull: ['order_id']
    },
    tags: ['0h00'],
    bigquery: {
        partitionBy: "DATE(created_time)"
    }
}

-- js {
--     // const event_checkpoint_date = `CURRENT_DATE() - INTERVAL 10 DAY`
--     const event_checkpoint_date = `"2024-07-19"`
-- }

WITH o AS (
    SELECT 
        order_id,
        outbound_date,
        created_time
        
    FROM
        ${source.platinum}.marketplace_prd_order_v2_order
    -- WHERE 
    --     created_date > ${event_checkpoint_date}
)
, oi AS (
    SELECT 
        order_id,
        product_id,
        -- seller_code,
        -- sku,
        outbound_quantity,
        price
    FROM 
        ${source.platinum}.marketplace_prd_order_v2_order_item
    -- WHERE
    --     created_date > ${event_checkpoint_date}
)
, bill as (
    SELECT 
        distinct
        order_id,
        created_time
    FROM
        ${source.platinum}.accounting_prd_core_bill 
)
SELECT
    bill.order_id,
    oi.product_id,
    -- oi.seller_code as supplier_code,
    -- oi.sku,
    ${utils.ToTimezone(`o.outbound_date`)} AS outbound_time,
    oi.outbound_quantity AS outbound_quantity,
    -- max_quantity as demand_quantity, 
    oi.price,
    -- vat
    (oi.outbound_quantity * oi.price ) AS outbound_amount,
    
    ${utils.ToTimezone(`bill.created_time`)} created_time


FROM bill 
LEFT JOIN o ON o.order_id = bill.order_id
LEFT JOIN oi ON o.order_id = oi.order_id


-- post_operations {
--     ALTER TABLE ${self()} 
--     ADD FOREIGN KEY (order_id) references ${ref(`dim_order`)}(order_id) NOT ENFORCED,
--     ADD FOREIGN KEY (product_id) references ${ref(`dim_product`)}(product_id) NOT ENFORCED;

-- }



