config {
    type: "view",
    description: "PIC: Huong.Dang"
}

WITH
  dim_year_month AS(
  SELECT
    DISTINCT CAST(FORMAT_DATE('%Y-%m', som) AS STRING) AS year_month,
    som
  FROM
    ${ref('dim_calendar')}
  WHERE
    date BETWEEN '2018-01-01'
    AND CURRENT_DATE()),

  min_odder_date AS (
  SELECT
    a.customer_id,
    DATE(MIN(a.created_at)) AS first_date_order,
    DATE_TRUNC(DATE(MIN(a.created_at)), MONTH) AS som_first_date_order
  FROM
    ${ref('fact_order')} AS a
  WHERE
    order_status <> "CANCEL"
  GROUP BY
    1),

  customer_calendar AS(
  SELECT
    a.customer_id,
    b.year_month,
    b.som,
    EXTRACT(YEAR
    FROM
      b.som) AS purchase_year,
    EXTRACT(MONTH
    FROM
      b.som) AS purchase_month,
  FROM
    min_odder_date AS a
  CROSS JOIN
    dim_year_month AS b
  WHERE
    b.som >= a.som_first_date_order),
    
  orders_per_month AS (
  SELECT
    customer_id,
    CAST(FORMAT_DATE('%Y-%m', created_at) AS STRING) AS year_month,
    -- EXTRACT(YEAR FROM created_at) AS purchase_year,
    -- EXTRACT(MONTH FROM created_at) AS purchase_month,
    COUNTIF(order_status <> 'CANCEL') > 0 AS has_purchase
  FROM
    ${ref('fact_order')}
  GROUP BY
    ALL),
  calendar_order AS(
  SELECT
    a.*,
    CASE
      WHEN b.has_purchase IS NULL THEN FALSE
      ELSE b.has_purchase
  END
    AS has_purchase
  FROM
    customer_calendar AS A
  LEFT JOIN
    orders_per_month AS B
  ON
    a.customer_id = b.customer_id
    AND a.year_month = b.year_month )
SELECT
  customer_id,
  som,
  year_month,
  purchase_year,
  purchase_month,
  has_purchase,
  LAG(has_purchase) OVER (PARTITION BY customer_id ORDER BY purchase_year, purchase_month) AS previous_month_purchase
FROM
  calendar_order
