config {
    type: "table",
    description: "PIC: Huong.Dang",
    tags: ["custom_1h_past5"],
    columns: {
        new_customer: "Những khách hàng có đơn hàng đầu tiên tại thuocsi trong tháng đó, stt đơn <> CANCEL. Vd: Khách hàng A có đơn hàng đầu tiên tại thuocsi vào tháng 5/2024, có stt đơn=COMPLETED, thì khách đó sẽ là New_Customer trong tháng 5/2024",
        repeat_customer: "Những khách hàng có đơn hàng 2 tháng liên tiếp tại sàn thuocsi, loại trừ những đơn hàng CANCEL. Vd: Khách hàng A có đơn hàng trong 4 / 2024 và tháng 5 / 2024,thì type của khách hàng A trong tháng 5 / 2024 sẽ là Repeat Customer",
        reacquire_customer: "Những khách hàng chưa mua hàng từ 1 tháng trở lên, tính từ tháng cuối cùng mua hàng tại thucosi, quay trở lại mua hàng, loại trừ những đơn hàng CANCEL.Vd: Tháng 3/2024 khách A có mua hàng, tháng 4/2024 khách A không mua hàng, tháng 5/2024 quay lại mua hàng, khách A sẽ là Reacquire Customer trong tháng 5/2024",
        active_customer: "Khách hàng có mua ít nhất 1 đơn trong tháng không tính Cancel",
        churn_customer: "Khách hàng tháng trước có mua ít nhất 1 đơn không tính đơn Cancel. Tháng kế tiếp không mua"
    },
    bigquery: {
        partitionBy: "som",
        clusterBy: ["customer_id"]
    }
}

-- Bảng này không loại channel = 'MARKETPLACE' như bảng dim_customer_profiling và lấy data từ fact_strategic_sale_order


WITH latest_channel AS (
  SELECT
    customer_id,
    DATE_TRUNC(DATE(order_date), MONTH) AS som,
    FORMAT_DATE('%Y-%m', DATE(order_date)) AS year_month,
    channel
  FROM ${ref('fact_strategic_sale_order')}
  WHERE status <> 'CANCEL'
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY
      customer_id,
      DATE_TRUNC(DATE(order_date), MONTH)
    ORDER BY order_date DESC
  ) = 1
),

first_order AS (
  SELECT
    customer_id,
    DATE(MIN(order_date)) AS first_order_date
  FROM ${ref('fact_strategic_sale_order')}
  WHERE status <> 'CANCEL'
  GROUP BY customer_id
)

SELECT
  a.customer_id,
  ch.channel,

  CASE
    WHEN cust.config_fc = 'MIENTRUNG' THEN 'CENTRAL'
    WHEN cust.config_fc = 'MIENBAC' THEN 'NORTHERN'
    WHEN cust.config_fc = 'MIENNAM' THEN 'SOUTHERN'
  END AS location,

  a.year_month,
  a.som,
  a.gmv,
  a.no_order,

  IF(
    DATE_TRUNC(fo.first_order_date, MONTH) = a.som,
    1,
    0
  ) AS new_customer,

  IF(
    a.has_purchase = TRUE
    AND a.previous_month_purchase = TRUE,
    1,
    0
  ) AS repeat_customer,

  IF(
    DATE_TRUNC(fo.first_order_date, MONTH) <> a.som
    AND a.has_purchase = TRUE
    AND a.previous_month_purchase = FALSE,
    1,
    0
  ) AS reacquire_customer,

  IF(
    a.has_purchase = TRUE,
    1,
    0
  ) AS active_customer,

  IF(
    a.has_purchase = FALSE
    AND a.previous_month_purchase = TRUE,
    1,
    0
  ) AS churn_customer

FROM ${ref('agg_customer_profiling_all_channel')} AS a

INNER JOIN ${ref('dim_customer')} AS cust ON a.customer_id = cust.customer_id
  AND cust.customer_report_category <> 'EMPLOYEE'

LEFT JOIN latest_channel AS ch ON a.customer_id = ch.customer_id AND a.som = ch.som
LEFT JOIN first_order AS fo ON a.customer_id = fo.customer_id