config {
    type: "view",
    description: `Repeat Customer: Những khách hàng có đơn hàng 2 tháng liên tiếp tại sàn thuocsi, loại trừ những đơn hàng CANCEL.
    Vd: Khách hàng A có đơn hàng trong 4/2024 và tháng 5/2024, thì type của khách hàng A trong tháng 5/2024 sẽ là Repeat Customer.
    PIC: Huong.Dang`
}

SELECT
  customer_id,
  year_month
FROM
  ${ref('agg_customer_profiling')}
WHERE
  (has_purchase = true
  AND previous_month_purchase = true)
