config {
    type: "table",
    description: "PIC: Huong.Dang",
    tags: ["custom_1h_past5"],
    columns: {
        new_customer: "Những khách hàng có đơn hàng đầu tiên tại thuocsi trong tháng đó, stt đơn <> CANCEL. Vd: Khách hàng A có đơn hàng đầu tiên tại thuocsi vào tháng 5/2024, có stt đơn=COMPLETED, thì khách đó sẽ là New_Customer trong tháng 5/2024",
        repeat_customer: "Những khách hàng có đơn hàng 2 tháng liên tiếp tại sàn thuocsi, loại trừ những đơn hàng CANCEL. Vd: Khách hàng A có đơn hàng trong 4 / 2024 và tháng 5 / 2024,thì type của khách hàng A trong tháng 5 / 2024 sẽ là Repeat Customer",
        reacquire_customer: "Những khách hàng chưa mua hàng từ 1 tháng trở lên, tính từ tháng cuối cùng mua hàng tại thucosi, quay trở lại mua hàng, loại trừ những đơn hàng CANCEL.Vd: Tháng 3/2024 khách A có mua hàng, tháng 4/2024 khách A không mua hàng, tháng 5/2024 quay lại mua hàng, khách A sẽ là Reacquire Customer trong tháng 5/2024",
        active_customer: "Khách hàng có mua ít nhất 1 đơn trong tháng không tính Cancel",
        churn_customer: "Khách hàng tháng trước có mua ít nhất 1 đơn không tính đơn Cancel. Tháng kế tiếp không mua"
    },
    bigquery: {
        partitionBy: "som",
        clusterBy: ["customer_id"]
    }
}

WITH min_order_date AS (
  SELECT
    customer_id,
    channel,
    DATE(MIN(order_date)) AS first_order_date
  FROM ${ref('fact_strategic_sale_order')}
  WHERE status <> 'CANCEL'
  GROUP BY
    customer_id,
    channel
),

new_customer AS (
  SELECT
    customer_id,
    channel,
    FORMAT_DATE('%Y-%m', first_order_date) AS year_month
  FROM min_order_date
)

SELECT
  a.customer_id,
  a.channel,

  CASE
    WHEN cust.config_fc = 'MIENTRUNG' THEN 'CENTRAL'
    WHEN cust.config_fc = 'MIENBAC' THEN 'NORTHERN'
    WHEN cust.config_fc = 'MIENNAM' THEN 'SOUTHERN'
  END AS location,

  a.year_month,
  a.som,
  a.gmv,
  a.no_order,

  IF(
    b.customer_id IS NOT NULL,
    1,
    0
  ) AS new_customer,

  IF(
    a.has_purchase = TRUE
    AND a.previous_month_purchase = TRUE,
    1,
    0
  ) AS repeat_customer,

  IF(
    b.customer_id IS NULL
    AND a.has_purchase = TRUE
    AND a.previous_month_purchase = FALSE,
    1,
    0
  ) AS reacquire_customer,

  IF(
    a.has_purchase = TRUE,
    1,
    0
  ) AS active_customer,

  IF(
    a.has_purchase = FALSE
    AND a.previous_month_purchase = TRUE,
    1,
    0
  ) AS churn_customer

FROM ${ref('agg_customer_profiling_all_channel')} AS a
INNER JOIN ${ref('dim_customer')} AS cust ON a.customer_id = cust.customer_id AND cust.customer_report_category <> 'EMPLOYEE'
LEFT JOIN new_customer AS b ON a.customer_id = b.customer_id AND a.channel = b.channel AND a.year_month = b.year_month