config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "marketplace_prd_product_v2_deal",
    tags:["platinum","marketplace_prd_product-v2","VN_product"]
}

  WITH silver AS (
    SELECT
      key, mg_id, code, status, image_urls, skus_key, deal_type, quantity, skus, deal_id, price, end_time, ready_time, created_time, name, hash_tag, max_quantity, start_time, area_codes, customer_level_codes, last_updated_time, last_action, sku_status, can_ready_view, can_view, system_display, ticket_code, pricing_type, max_quantity_per_customer, owner, account_id, auto_update_data_sku, seller_code, charge_deal_fee, auto_update_sku, last_updated_by, order_id, discount_percent, max_discount_value, slug, area_codes_prev, sku_prev_ver, last_auto_update_sku, auto_off_sku, auto_on_sku_combo, sku_prev, synced_at, extra_props, action, ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.marketplace_prd_product_v2_deal
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key, mg_id, code, status, image_urls, skus_key, deal_type, quantity, skus, deal_id, price, end_time, ready_time, created_time, name, hash_tag, max_quantity, start_time, area_codes, customer_level_codes, last_updated_time, last_action, sku_status, can_ready_view, can_view, system_display, ticket_code, pricing_type, max_quantity_per_customer, owner, account_id, auto_update_data_sku, seller_code, charge_deal_fee, auto_update_sku, last_updated_by, order_id, discount_percent, max_discount_value, slug, area_codes_prev, sku_prev_ver, last_auto_update_sku, auto_off_sku, auto_on_sku_combo, sku_prev, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `marketplace_prd_product_v2_deal`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"