config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "marketplace_prd_product_v2_after_rebate_price_ticket",
    tags:["platinum","marketplace_prd_product-v2","VN_product"]
}

  WITH silver AS (
    SELECT
      key, mg_id, item_code, ticket_status, after_rebate_price, category_in_charge, created_time, last_updated_time, location_codes, new_price, prev_price, prev_retail_price_value, product_code, product_id, retail_price_value, seller_code, sku, ticket_action, ticket_action_by, ticket_description, actionDate, synced_at, extra_props, action, ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.marketplace_prd_product_v2_after_rebate_price_ticket
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key, mg_id, item_code, ticket_status, after_rebate_price, category_in_charge, created_time, last_updated_time, location_codes, new_price, prev_price, prev_retail_price_value, product_code, product_id, retail_price_value, seller_code, sku, ticket_action, ticket_action_by, ticket_description, actionDate, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `marketplace_prd_product_v2_after_rebate_price_ticket`)}
  )
  SELECT p.*
FROM platinum p
WHERE NOT EXISTS (SELECT 1 FROM silver s WHERE s.mg_id = p.mg_id)  

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"