config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "marketplace_prd_product_v2_sku_main_v2",
    tags:["platinum","marketplace_prd_product-v2","VN_product"]
}

  WITH silver AS (
    SELECT
      key, mg_id, created_time, code, product_id, is_combo, version, slug, skus, max_quantity_per_order, hash_tag, is_active, status, last_updated_time, product_code, seller_code, type, manual_priority, priority, sku_items, campaign_code, time_change_status, old_slug, level, required_certificates, level_special, manual_priorities, point, point_multiplier, image_urls, from_trading, product_group_code, product_group_id, seller_certificates, synced_at, extra_props, action, ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.marketplace_prd_product_v2_sku_main_v2
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 1 DAY
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
          AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
          WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
          IF
              (action='d',3,
              IF
              (action='u',2,1)) DESC
          ,last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key, mg_id, created_time, code, product_id, is_combo, version, slug, skus, max_quantity_per_order, hash_tag, is_active, status, last_updated_time, product_code, seller_code, type, manual_priority, priority, sku_items, campaign_code, time_change_status, old_slug, level, required_certificates, level_special, manual_priorities, point, point_multiplier, image_urls, from_trading, product_group_code, product_group_id, seller_certificates, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `marketplace_prd_product_v2_sku_main_v2`)}
  )
  SELECT p.*
  FROM platinum p
  LEFT JOIN silver s 
      ON p.mg_id = s.mg_id 
  WHERE s.mg_id is null 

  UNION ALL 

  SELECT s.*
  FROM silver s
  WHERE action <> "d"