config {
    type: "view",
    schema: "platinum_buymed_vn",
    name: "marketplace_prd_product_v2_sku_contract_detail",
    tags:["platinum","marketplace_prd_product-v2","VN_product"]
}

  WITH silver AS (
    SELECT
      key, mg_id, seller_code, created_time, product_id, created_by, customer_id, code, sku_contract_code, sku, price, hash_tag, product_code, last_updated_time, synced_at, extra_props, action, ingest_time,
      
        CASE
            WHEN created_time IS NOT NULL THEN DATE(DATETIME(created_time, 'Asia/Ho_Chi_Minh'))
            ELSE DATE( '2099-01-01' )
        END
     created_date,
      CAST(null as datetime) 
    FROM silver_buymed_vn.marketplace_prd_product_v2_sku_contract_detail
    WHERE ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
    QUALIFY ROW_NUMBER() OVER (_window) = 1 
        --   AND ingest_time >= CURRENT_TIMESTAMP() - INTERVAL 16 HOUR
    WINDOW _window AS (
          PARTITION BY mg_id
          ORDER BY synced_at DESC,
        --   IF
        --       (action='d',3,
        --       IF
        --       (action='u',2,1)) DESC
          last_updated_time DESC)
  ), platinum AS (
    SELECT 
      key, mg_id, seller_code, created_time, product_id, created_by, customer_id, code, sku_contract_code, sku, price, hash_tag, product_code, last_updated_time, synced_at, extra_props, action, ingest_time,
      created_date,
      platinum_refresh
    FROM ${ref(`platinum_buymed_vn__stg`, `marketplace_prd_product_v2_sku_contract_detail`)}
  )
SELECT p.*
FROM platinum p
WHERE NOT EXISTS (SELECT 1 FROM silver s WHERE s.mg_id = p.mg_id) 

UNION ALL 

SELECT s.*
FROM silver s
WHERE action <> "d"