config {
    type: "table",
    description: `Last 13 month| PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every 2 hours.Circa OS Transaction order `
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5*/,
    tags: ["custom_2h_past5"],
    name: "fs_fact_order",
    columns: {
        order_id: "NonNull |" + docs.order_id,
        customer_id: "NonNull | The unique identifier for each customer"
        
    },
    bigquery: {
        partitionBy: "date(created_at)"
    }
}

with return_cancel as (
    select c.code
    from ${source.circa_os}.order_return_order c
    left join ${source.circa_os}.entity_pos_profile p on c.pos_id = p.id
    where c.status = 'CANCELED'
        and p.type = 'FS'
        and p.code not in ('POS0030','POS0020','POS0047')
),
cte_os as
    (select o.id as order_id
       ,pos_id, p.code as pos_code
       ,entity_id
       ,o.code as order_code
       ,o.total_amount -- Tiền hàng + phí cắt liều - giảm giá
       ,actual_total_item_amount --hình như giống o.total_item_amount
       ,o.total_item_amount -- tiền hàng
       ,discount_amount -- khuyến mãi 
       ,o.created_by
       ,o.updated_by
       ,en.name
       ,o.status
       ,o.note
       ,o.type
       ,o.source_type
       ,delivery_type
       ,channel
       ,date(DATETIME_ADD(o.created_at, INTERVAL 7 HOUR)) as created_date
       ,DATETIME_ADD(o.created_at, INTERVAL 7 HOUR) as created_at
       ,fulfillment_status
       ,reference_order_in_platform
       ,date(DATETIME_ADD(completed_at, INTERVAL 7 HOUR))  as completed_date
       ,medicine_cutting_fee -- tiền cắt liều
       ,STRING_AGG(CAST(return_id as string)) as return_codes
from ${source.circa_os}.order_order o
left join UNNEST(JSON_VALUE_ARRAY(order_return_codes)) AS return_id
left join ${source.circa_os}.entity_pos_profile p on o.pos_id = p.id
left join ${source.circa_os}.entity_entity en on o.updated_by = en.id
where o.type <> 'RETURN'
      and p.type = 'FS'
      and o.status <> 'PENDING'
      and p.code not in ('POS0030','POS0020','POS0047')
group by all)

select
    *
    , case
        when return_codes is null or return_codes in (select * from return_cancel) then "NORMAL"
        else "RETURN"
    end as order_type
from cte_os

--gmv = Giá bán * sản phẩm + bất kì phí nào khác (hiện tại có phí cắt liều) - những đơn return hoặc return 1 phần  = total_item_amount + medicine_cutting_fee - return