config {
    type: "table",
    description: `Circa OS Transaction order item detail PIC: huyen.ngo; model_type: Table ;schedule: At minute 5 every 2 hours`,
    /*Source:
      ${source.silver}.marketplace_prd_order_v2_order_item
      ${source.silver}.marketplace_prd_order_v2_order ,custom_2h_past5,*/
    tags: ["custom_2h_past5"],
    name: "fs_fact_order_item",
    columns: {

        
    }
}
with order_items as (
select distinct
  order_id
  --   o.code as order_code,
  ,oi.product_id
  ,oi.sku_code
  ,sum(al.base_quantity / convert_rate) as quantity
  ,unit
  ,unit_price
  ,oi.discount_amount
  ,(oi.discount_amount + oi.unit_price) as unit_price_before_discount
  ,oi.lot_date
  ,sum(al.base_quantity) as base_quantity
  ,oi.tax_rate
  ,oi.product_id || '_' || oi.lot_date || '_' || oi.tax_rate as product_lot_date_vat
  ,oi.sku_code || '_' || oi.lot_date || '_' || oi.tax_rate as sku_lotdate_vat
  ,al.cost_price_include_tax as base_unit_cost_price
  ,eo.name as owner_name
  ,po.code as po_code
  ,po.sale_order_number
  ,promotion_event_code
  ,po.distributor_id
  ,e.name as employee_name
  ,o.client_id
from ${source.circa_os}.order_order o
left join ${source.circa_os}.order_order_item oi ON o.id = oi.order_id
left join ${source.circa_os}.inventory_allocation as al ON oi.id = al.item_ref_id
left join ${source.circa_os}.inventory_location_detail ld ON al.location_detail_id = ld.id  and o.client_id = ld.client_id
left join ${source.circa_os}.inventory_cost_price as cp on oi.product_id = cp.product_id and o.pos_id=cp.pos_id and oi.sku_code = cp.sku_code 
left join ${source.circa_os}.order_purchase_order po on  ld.doc_code = po.code and o.client_id = po.client_id
left join ${source.circa_os}.entity_owner eo on po.owner_id = eo.id and o.client_id = eo.client_id
left join ${source.ref}.fs_product_convert_base_unit  cv on cv.product_id = oi.product_id and cv.convert_unit = oi.unit and o.client_id = cv.client_id
left join ${source.circa_os}.entity_entity e on o.updated_by = e.id
where
  o.status LIKE '%COMPLETE%'
group by all
)

select distinct i.*
      ,base_unit_cost_price * convert_rate  as  unit_cost_price
from order_items i
left join ${ref('cos_fact_order')} fo on i.order_id = fo.order_id
left join  ${source.ref}.fs_product_convert_base_unit  cv on cv.product_id = i.product_id and cv.convert_unit = i.unit and i.client_id = cv.client_id
where fo.order_id is not null

