
config {
  type: "incremental",
  schema: "buying_agent_input",
  name: "store_profile",
  tags: ["AI_Buying_Agent"],
  uniqueKey: [
    "store_id",
    "snapshot_date"
  ],

  bigquery: {
    partitionBy: "snapshot_date",
    clusterBy: ["store_id"]
  },

  description: "Circa store profile. Grain: one row per store per snapshot date."
}


-- TRUNCATE TABLE ${self()} 

-- INSERT INTO buying_agent_input.store_profile
-- (
--   store_id, store_name, store_type, province_code, district_code, thuocsi_account_id, snapshot_date
-- )

SELECT
   id                              AS store_id
  ,name                            AS store_name
  ,CASE WHEN type = 'CIRCA' THEN 'OWNED' ELSE 'FRANCHISE' END AS store_type
  ,province                                                   AS province_code
  ,district                                                   AS district_code
  ,CAST(thuocsi_id AS STRING)                                 AS thuocsi_account_id
  ,CURRENT_DATE('Asia/Ho_Chi_Minh')                           AS snapshot_date
FROM ${ref("circa_pos_profile")}
WHERE deleted_at IS NULL
      AND client_id NOT IN (5,6,7)
      AND type <> 'OTHER'
      AND province <> ''

     post_operations {

  IF NOT EXISTS (
    SELECT 1
    FROM `lakehouse-prod-394907.buying_agent_input.INFORMATION_SCHEMA.TABLE_CONSTRAINTS`
    WHERE table_name = 'store_profile'
      AND constraint_type = 'PRIMARY KEY'
  ) THEN

    ALTER TABLE ${self()}
    ADD PRIMARY KEY (store_id, snapshot_date) NOT ENFORCED;

  END IF;

}
