config {
    type: "table",
    description: `Lấy giá mua hàng ngoài của FS, dùng để compare với giá thuốc sỉ
             PIC: huyen.ngo; model_type: Table ;schedule: At minute 15 past 2 hours`,
    tags: ["custom_2h_past15"],
    name: "circafs_lastest_price",
}

WITH t AS (
SELECT DISTINCT
     product_id
    ,unit_price
    ,unit
    ,pos_id
    ,client_id
    ,created_at AS latest_order
    ,fulfillment_method
    ,vendor AS last_vendor
    ,distributor_id
FROM (
    SELECT
         i.product_id
        ,i.unit_price
        ,unit
        ,pos_id
        ,o.client_id
        ,o.created_at
        ,o.fulfillment_method
        ,o.vendor
        ,o.distributor_id
        ,ROW_NUMBER() OVER (
             PARTITION BY i.product_id, o.pos_id
             ORDER BY o.created_at DESC
         ) AS rn
    FROM ${source.ref}.cos_purchase_order o
    LEFT JOIN ${source.ref}.cos_purchase_order_item i ON o.po_id = i.po_id
    WHERE o.client_id <> 1
      AND unit_price > 0
)
WHERE rn = 1
  AND fulfillment_method = 'EXTERNAL'
),

sku_circa AS (
SELECT
     t.*
    ,p.thuocsi_id
    ,CONCAT(product_id,'_',thuocsi_id) AS product_thuocsi_id
    ,p.name
    ,m.customer_level
FROM t
LEFT JOIN ${source.ref}.circa_pos_profile p ON t.pos_id = p.id
LEFT JOIN ${source.ref}.dim_customer m ON p.thuocsi_id = m.customer_id
WHERE product_id IN (
    SELECT DISTINCT product_id
    FROM ${source.ref}.dim_product
)
ORDER BY p.name, latest_order DESC
)

SELECT
     TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 HOUR) AS transformed_at
    ,sku_circa.*
    ,sku_circa.unit_price / convert_rate AS base_unit_price
FROM sku_circa
LEFT JOIN ${source.ref}.cos_product_convert_base_unit r ON sku_circa.product_id = r.product_id
                                                       AND sku_circa.unit = r.convert_unit
                                                       AND sku_circa.client_id = r.client_id
                                                    